### ISSUE TITLE
When a table is dropped/created view is changed retrigger the metadata

### ISSUE THREAD

**Issue by BradRuderman** [hankinsoft/SQLPro#10]
When a table is dropped or view is created, trigger a refresh on the app, to refresh the meta-data. I noticed I was searching for tables and saw a table I had dropped earlier.

This is very low-priority

**Comment by windware** [comment]
Related but when I modify a table's column, it would be nice to see the columns expanded under the table tree to auto reload.

**Comment by hankinsoft** [comment]
Working on this for the next build. Hope to have it available later in the week.

![CleanShot 2020-07-06 at 11 29 04](https://user-images.githubusercontent.com/3160528/86604672-10fbaa80-bf7c-11ea-82e8-5b7bf6b0d52e.gif)

The following will be supported:
1. Running a `DROP TABLE` will remove the table from the database tree (and update autocomplete/syntax highlighting).
2. Running a `CREATE TABLE` will add the new table to the database tree (and update autocomplete/syntax highlighting).
3. Running an `ALTER TABLE` will refresh the table in the database tree (and update autocomplete/syntax highlighting).

I'll post again once the build is available.

**Comment by hankinsoft** [comment]
This has been available for a month or so now. If anyone runs into any issues or has any feedback, please let me know.
