### ISSUE TITLE
Can't run query on sqlite

### ISSUE THREAD

**Issue by tjdraper** [hankinsoft/SQLPro#100]
On an sqlite database, when I try to run the query:

```
DELETE from users
WHERE id = 5
```

I get an error

unable to open database file (Line 2)

The same query works in SQLPro for SQLite, but I’m evaluating SQLPro Studio to be the one application for all my SQL needs.

**Comment by hankinsoft** [comment]
Hi,
Unfortunately SQLPro Studio's support for SQLite is still in beta and issues like this may arise. I'm hoping to have the beta support improved within the coming months.

**Comment by hankinsoft** [comment]
Just to note, SQLPro Studio now has SQLite support (it has for some time, however I forgot to update this issue). If I can help with anything else, please let me know.
