### ISSUE TITLE
When I export JSON, the JSON isn't showing the data type used in the table.  Specifically everything is being exported as a string, with quotes.

### ISSUE THREAD

**Issue by jacksonsox** [hankinsoft/SQLPro#1000]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment details (please complete the following information):**
 - Device: [e.g. iPhone6, MacBook]
 - OS: [e.g. iOS8.1, macOS 11]
 - SQLPro app Version [e.g. SQLPro Studio 2022.x] Please ensure you specify the full app name. (ex: SQLPro Studio, SQLPro for MySQL, etc).
- Installation source: [App Store, Website download, Setapp].
- Target database server [e.g. MySQL, PostgreSQL, Microsoft SQL Server, etc]

**Additional context**

## Issues will be closed until environmental details are provided.
If the above template is not completed, issues with be closed with the statement `Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened`.

**Comment by jacksonsox** [comment]
Table Layout
CREATE TABLE IF NOT EXISTS "Figure_StarWars" (
  Series_Unique_ID char(128) NOT NULL,
  Figure_Unique_ID char(128) PRIMARY KEY NOT NULL,
  Sort_Order integer(128) NOT NULL,
  Debut_Year integer(128) NOT NULL,
  Phase char(128) NOT NULL,
  Wave char(128) NOT NULL,
  Number char(128),
  Item_Number char(128),
  UPC char(128),
  Action_Figure char(128) NOT NULL,
  Action_Figure_Package_Name char(256) NOT NULL,
  Scene char(256),
  Find_Terms char(256) NOT NULL,
  Exclude_Terms char(256),
  Amazon_ASIN char(128),
  Amazon_Short_Link char(128),
  Walmart_SKU integer(128),
  Target_TCIN integer(128),
  Target_DPCI char(128),
  EEIN char(128),
  Retail_Date char(128),
  Retail_Price real(128),
  Added_Date char(128),
  Sort_Grouping char(128),
  Tags char(256),
  FOREIGN KEY (Series_Unique_ID) REFERENCES "Series" (Series_Unique_ID)

Output Example
[
  {
    "Tags" : null,
    "UPC" : "630509773930",
    "Figure_Unique_ID" : "3200100",
    "Exclude_Terms" : null,
    "Amazon_Short_Link" : "https:\/\/amzn.to\/2U1P5XD",
    "Target_DPCI" : "087-16-3978",
    "Find_Terms" : "Darth Vader",
    "Action_Figure_Package_Name" : "Darth Vader",
    "Wave" : "1",
    "Series_Unique_ID" : "SWBSHR",
    "Debut_Year" : "2019",
    "Number" : "2019",
    "Action_Figure" : "Darth Vader",
    "Target_TCIN" : "75560480",
    "Phase" : "Figure",
    "Item_Number" : "E4384",
    "Retail_Price" : "79.99",
    "Sort_Order" : "1",
    "Amazon_ASIN" : "B07D769KSP",
    "Sort_Grouping" : "Figure - 2019",
    "Walmart_SKU" : "329409902",
    "Retail_Date" : "08\/01\/2019",
    "EEIN" : null,
    "Scene" : "The Empire Strikes Back",
    "Added_Date" : null
  },

**Comment by jacksonsox** [comment]
Exporting as XML looks similar with all values quoted.  Although, I'm not sure what XML should look like.

<rows>
  <row Series_Unique_ID="SWBSHR" Figure_Unique_ID="3200100" Sort_Order="1" Debut_Year="2019" Phase="Figure" Wave="1" Number="2019" Item_Number="E4384" UPC="630509773930" Action_Figure="Darth Vader" Action_Figure_Package_Name="Darth Vader" Scene="The Empire Strikes Back" Find_Terms="Darth Vader" Amazon_ASIN="B07D769KSP" Amazon_Short_Link="https://amzn.to/2U1P5XD" Walmart_SKU="329409902" Target_TCIN="75560480" Target_DPCI="087-16-3978" Retail_Date="08/01/2019" Retail_Price="79.99" Sort_Grouping="Figure - 2019"/>

**Comment by hankinsoft** [comment]
Thank you for the details. I’m away for the weekend, but based on what I see here and the scripts you provided I should be able to fix this up pretty early next week.

**Comment by jacksonsox** [comment]
Thank you.

Jason Gloor
Sent from my iPhone

On Aug 2, 2024, at 8:06 PM, Kyle Hankinson ***@***.***> wrote:

﻿

Thank you for the details. I’m away for the weekend, but based on what I see here and the scripts you provided I should be able to fix this up pretty early next week.

**Comment by jacksonsox** [comment]
Hi Kyle Hankinson.  Any thoughts on this JSON issue?  I'm not able to put new data into my production app.

**Comment by jacksonsox** [comment]
Thanks,
      Does it matter that its the mysql version vs. me using sqllite?
________________________________

**Comment by hankinsoft** [comment]
> Does it matter that its the mysql version vs. me using sqllite?
Sorry, I assumed you were using the MySQL version as it had listed 

> Target database server MySQL

You are using SQLPro for SQLite?

**Comment by jacksonsox** [comment]
Sorry for the mixup.

SQLPro for SQLite.

Jason
________________________________

**Comment by hankinsoft** [comment]
Can you try:

[SQLPro for SQLite.zip](https://github.com/user-attachments/files/16532708/SQLPro.for.SQLite.zip)

And see if that sorts it out? If so, I'll get the App Store build submitted as well.

**Comment by jacksonsox** [comment]
I'm getting some interesting results.  The order of the data seems wrong in the new version liked above (let's call it "new copy").  I have some screen shots of the of the original vs the new copy SQLite.zip.  I've tried to add pictures that represent the changes.  Let me know if you need more or want to chat.

Schema
<img width="1006" alt="Screenshot 2024-08-07 at 7 21 39 PM" src="https://github.com/user-attachments/assets/b66e6813-594d-43ab-bbf5-cbcdcecda879">
Data in the DB
<img width="2046" alt="Original DB Dagta" src="https://github.com/user-attachments/assets/af8afd66-cfd9-4c41-940c-5713c7b3e1a0">

New Copy Schema
<img width="972" alt="New Copy Schema" src="https://github.com/user-attachments/assets/1a4cf57e-5111-4d55-8528-155976aecc6b">
New Copy Data in DB
<img width="2042" alt="New Copy Data" src="https://github.com/user-attachments/assets/4b37318d-0207-4a68-a9a8-0c3616d1300e">

Output JSON Original and New Copy
<img width="1394" alt="Output Original and New data shifting to different columns" src="https://github.com/user-attachments/assets/fa4f2c0d-ed63-4767-85f5-18f202c9f020">

**Comment by hankinsoft** [comment]
This is very odd. So if you open the database in the old version the schema appears one way and in the new version it appears different?

- what was the old version of the app?
- can you provide me with the database?

**Comment by jacksonsox** [comment]
Hi Kyle,
  Can you send me a link to the SQLPro version from early July?  That will allow me to paste my data while working on the new version.  I’m going to try and export from an older version and import into the newest version.  I’m hoping that the import will take care of the misalignment.

If not, I’ll work on getting you a trimmed down version of my DB/Data

Jason Gloor
Sent from my iPhone

On Aug 8, 2024, at 5:41 AM, Kyle Hankinson ***@***.***> wrote:

﻿

This is very odd. So if you open the database in the old version the schema appears one way and in the new version it appears different?

  *   what was the old version of the app?
  *   can you provide me with the database?

**Comment by hankinsoft** [comment]
Sure, you can grab the previous version here:

https://www.sqlitepro.com/download.php

**Comment by jacksonsox** [comment]
What is the best way to send you the DB with data?

Jason Gloor
Sent from my iPhone

On Aug 8, 2024, at 2:19 PM, Kyle Hankinson ***@***.***> wrote:

﻿

Sure, you can grab the previous version here:

https://www.sqlitepro.com/download.php

**Comment by hankinsoft** [comment]
You can email it to kyle@hankinsoft.com.

**Comment by hankinsoft** [comment]
Could you try this build:

[SQLPro for SQLite_78.zip](https://github.com/user-attachments/files/16732252/SQLPro.for.SQLite_78.zip)

I think this should sort it out.

**Comment by jacksonsox** [comment]
Hi Kyle,
      Lools like the version below worked.  Thank you for looking at this so quickly.

Jason G.
________________________________

**Comment by hankinsoft** [comment]
Great, so just to confirm, this build sorts both the json export and the mixed up data you were seeing?

**Comment by hankinsoft** [comment]
Perfect, App Store build has been submitted as well. It usually takes ~24 hours or so for it to be approved.

**Comment by jacksonsox** [comment]
Thanks,
      I updated to the new version on the App Store.

      Thanks again for the help.

Jason G.
________________________________
