### ISSUE TITLE
Bad results table formatting

### ISSUE THREAD

**Issue by xoperator** [hankinsoft/SQLPro#1001]
Hello,

When a table with query results is rendered, sometimes it takes the whole space of the screen, and sometimes its narrowed to the left and looks pretty bad.

I am attaching the good result and a bad result, please fix.

<img width="1416" alt="Screenshot 2024-08-03 at 10 26 56" src="https://github.com/user-attachments/assets/d6d17d24-8852-476a-a472-28f5b679cc49">

<img width="1421" alt="Screenshot 2024-08-03 at 10 26 48" src="https://github.com/user-attachments/assets/7e659228-4da9-4a50-8dd3-5a9d8cce6748">

Thanks,
Ilya

**Comment by hankinsoft** [comment]
Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened
