### ISSUE TITLE
Error message box blocks the interface

### ISSUE THREAD

**Issue by ShiroTian** [hankinsoft/SQLPro#1004]
**Describe the bug**
When I import some data(16 rows) to an existing table, a message box pops up. That box is too high even overflows the screen, and I can not operate anything

**To Reproduce**
1. Import data(16 rows) to the table and popup an alert message box

**Expected behavior**

**Screenshots**
![Screenshot 2024-08-28 at 11 29 41](https://github.com/user-attachments/assets/6379ef2b-6f15-41c5-bdaa-b143831abd5f)

**Environment details (please complete the following information):**
 - Device: MacBook
 - OS: MacOS 14.6.1 (23G93)
 - SQLPro app Version SQLPro Studio Version 2024.21 (Build 111093)
- Installation source: Website download
- Target database server Microsoft SQL Server,

**Additional context**

## Issues will be closed until environmental details are provided.
If the above template is not completed, issues with be closed with the statement `Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened`.

**Comment by hankinsoft** [comment]
Hi,
A quick workaround would be to hit the escape key on your keyboard as that should close the dialog.

how are you importing the data? What steps are you taking? I’ll take a look into improving the dialog.

**Comment by hankinsoft** [comment]
Closed due to no response.
