### ISSUE TITLE
Unable to connect on iOS shortcuts.

### ISSUE THREAD

**Issue by monte517** [hankinsoft/SQLPro#1006]
**Describe the bug**

It may not be a bug and I may just need support, but I am trying to connect via shortcuts on my iPhone, and I'm getting no available connections.

**To Reproduce**
Steps to reproduce the behavior:  **There is a screen recording link below**
1. Open Shortcuts. 2. Start a shortcut and use SQL Pro in it. 3. Connect to SQL Pro via my iPhone connection in the app. Step 4. Hit play on the shortcut to run it and set the connection to ask each time. Step 5. It does not allow me to choose any connections. 

I'm assuming there's some other way to send in a connection, but I'm not aware of it. If you could please help.

**Expected behavior**
Make a simple query and export results in a JSON file.

**Screen recording:**
https://komododecks.com/recordings/-O6gxYLX_58p5EMQFiK3

**Environment details (please complete the following information):**
 - Device: [iphone 15 Pro Max]
 - OS: [e.g. iOS 18.0]
 - SQLPro Studio database client for iOS
- Installation source: Setapp
- Target database server: MySQL
- 
**Additional context**

The connection does work on my phone in the app itself and the connection works on my macOS as well.

## Issues will be closed until environmental details are provided.
If the above template is not completed, issues with be closed with the statement `Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened`.

**Comment by hankinsoft** [comment]
Hmm, it's really odd that no connections show up for you when creating the shortcut. I'm trying to figure out what that is, as I believe that to be the root of the problem. The first question would be what version of iOS are you using? I'll probably have some more over the next couple of days as I'm trying to replicate this.

**Comment by hankinsoft** [comment]
I see I'm using an older style of app intents that was made for pre iOS 16. I'm going to upgrade to the new style and see if that helps out. It will probably be next week sometime before I have an update available.

**Comment by hankinsoft** [comment]
Question 2: do you have iCloud Keychain disabled?

**Comment by monte517** [comment]
No. It is enabled.What type of value should I be trying to pass into the connection parameter in general? Like, am I giving the name of a connection? Am I having to create some type of credentials to pass in there? I guess, it might not be the app, it's just I've not encountered something to that effect. I've not tried to make SQL queries via a shortcut before. Actually, I've been using them for the last probably three, four months, truth be told, which is one of the things that led me to your app actually. So yeah, but if you've got any suggestions on it, and as far as the keychain. I do have Keychain enabled; however, my autofill default is Bitwarden, and I have them all turned on. I have Chrome, Keychain, and Bitwarden on, with Bitwarden often taking the primary default slot whenever it gives me a choice. Would that impact this?Sent from my iPhoneOn Sep 17, 2024, at 4:41 PM, Kyle Hankinson ***@***.***> wrote:﻿
Question 2: do you have iCloud Keychain disabled?

**Comment by hankinsoft** [comment]
Hi,
> What type of value should I be trying to pass into the connection parameter in general? Like, am I giving the name of a connection?

It should be giving you the list of connections you have already created in the app (the list that shows up when you launch the app minus the sample connections).

Just to confirm, you have created a connection within the app?

**Comment by hankinsoft** [comment]
2024.57 is now available - you may need to update manually from the App Store. If you get a chance, could you grab this version and let me know if that helps out?
