### ISSUE TITLE
Feature Request: Open any type of file

### ISSUE THREAD

**Issue by mredig** [hankinsoft/SQLPro#1009]
Pretty simple - a lot of apps use sqlite files as their internal file format, but use their own custom extension. It's extremely annoying to have to do the renaming dance, especially when macOS has to confirm every rename.

I think the best way to do it would be to have a checkbox in the open menu or a separate open menu option to toggle this functionality. Also, dropping *any* file on the app icon should attempt to open it as a Sqlite file.

**Environment (please complete the following information):**
 - Device: MacBook Air M1 2020
 - OS: macOS 14.5
 - SQLPro app Version SQLPro Studio Version 2024.63 (Build 111113)
- Installation source: Setapp
- Target database server: sqlite

**Requests will be closed until environmental details are provided.**

**Comment by hankinsoft** [comment]
I've got an update so you can drag any file type to the app icon or open any file type via the file -> open menu. I think that will sort what you want. Just want to confirm everything on the other issue first before I submit it.

**Comment by mredig** [comment]
That sounds great! I think that would cover everything I'm asking for :)

**Comment by hankinsoft** [comment]
A new build is available via setapp. If you get the chance could you see if this version resolves the issue for you?

**Comment by mredig** [comment]
Works great! Thank you :)

**Comment by hankinsoft** [comment]
Great, thanks for letting me know!
