### ISSUE TITLE
Feature Request: Don't show the getting started screen option

### ISSUE THREAD

**Issue by mredig** [hankinsoft/SQLPro#1010]
**Is your feature request related to a problem? Please describe.**
Yes - every time I open the app, I have to navigate the connections window. I'm mostly using SQLite on ephemeral files, so it's very irritating to have to close that before I can do anything.

**Describe the solution you'd like**
A "Don't show again" option either in the connections window or in the settings of the app.

**Environment (please complete the following information):**

- Device: MacBook Air M1 2020
- OS: macOS 14.5
- SQLPro app Version SQLPro Studio Version 2024.63 (Build 111113)
- Installation source: Setapp
- Target database server: sqlite

**Requests will be closed until environmental details are provided.**

**Comment by hankinsoft** [comment]
Investigating. Just to confirm, your saying when you open an sqlite file from 'outside' the app its still showing the connections screen?

**Comment by hankinsoft** [comment]
Also, the getting started screen should go away automatically anytime a file is opened (either via the drag/drop to icon or using the file -> open menu). Are you not seeing this behaviour?

**Comment by mredig** [comment]
That's what I've been experiencing. I currently have some dbs open, but I'll try to remember to send a video showing my exact experience when I'm done.

**Comment by mredig** [comment]
So here's what I'm experiencing:

I open a db with SQLPro Studio closed and when it opens, it gives me the new connections window, a disconnected attempt of the last session, and finally the actual file I was looking for. 

https://github.com/user-attachments/assets/80da0051-ae49-43cc-9ba7-6c0e61a12e7d

**Comment by hankinsoft** [comment]
Hmmm, ok. I have an idea whats going on, doing some investigation into it now.

**Comment by hankinsoft** [comment]
If you go into preferences and change the 'App shutdown' to 'Clean shutdown' I think that will sort this for you. From what it looks like, when you are opening the file from the file system, the app is also trying to restore the previous state of the app (the open tabs) which launches the window with tabs and the connection dialog.

Does that option sort this out for you?

**Comment by mredig** [comment]
That does it!

I still think a suppression option for the connections window would be ideal. This seems a bit unintuitive for others looking for a solution, but I'm good now. Thank you!

**Comment by hankinsoft** [comment]
Thats fair. I tend to shy away from adding additional preferences unless I get multiple requests from different users, so I'm going to consider this closed for now. I can revisit adding a preference in the future if it seems more users will benefit from that option.
