### ISSUE TITLE
App hangs and doesn't launch

### ISSUE THREAD

**Issue by gverdouw** [hankinsoft/SQLPro#1011]
**Describe the bug**
On my Intel iMac (2019) with the latest 2024.66 update I am no longer able to open the app. It just hangs using 100% CPU. I have completely uninstalled and then installed again and it still fails. I am using the Setapp version. I have left it for 10 minutes without success

**To Reproduce**
1. Install app from Setapp
2. Attempt to open...

**Expected behavior**
It should open the app successfully

**Screenshots**

<img width="1252" alt="Screenshot 2024-11-05 at 7 09 48 pm" src="https://github.com/user-attachments/assets/b249fbf8-ebd7-4e7b-8dea-0dc2437de8b7">

**Environment details:**
 - Device: iMac 27" 2019
 - OS: macOS Sequoia
 - SQLPro Studio 2024.66
- Installation source: Setapp.

**Comment by gverdouw** [comment]
Hi, unfortunately it hasn't seemed to have made any difference... I use the same setup on my work's M1 Pro MacBook Pro and it's working flawlessly still. Is there anything I can do to help? Its not crashing so there isn't a crash log... it just hangs

**Comment by hankinsoft** [comment]
New update released today. If you get the chance, please give it a try and let me know if that sorts things out?

**Comment by gverdouw** [comment]
Yeah, this update has done it. Thanks!

**Comment by hankinsoft** [comment]
Glad to hear it. Sorry for the inconvenience.
