### ISSUE TITLE
How to change SQLite version

### ISSUE THREAD

**Issue by ybart** [hankinsoft/SQLPro#1012]
SQLPro for SQLite seems to use an outdated SQLite version on my system, maybe the one bundled with macOS.

Is there some settings to update the engine ? I would like ideally to use the version I installed with Homebrew. But at least be able to choose the version.

I cannot currently use it on my DBs because of the lack of support for recent JSON features of SQLite.

**Comment by hankinsoft** [comment]
Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened.
