### ISSUE TITLE
Refund Request

### ISSUE THREAD

**Issue by user12346abc** [hankinsoft/SQLPro#1016]
Hello, I purchased a free trial for SQLPro for MSSQL and missed the date to cancel before getting charged. I haven’t used the application since the day I downloaded it. I would really appreciate if an exception could be made and I could receive a refund since I haven’t used the app. If there’s any other way of contacting you privately like email I could provide proof of purchase. I would really appreciate the help, thank you.

**Comment by hankinsoft** [comment]
Hello,
Just to confirm this is for a trial via the App Store? If that's the case, you will need to contact Apple directly, as I do not have a way to provide refunds from the App Store. Apple has an article here on how to request a refund: https://support.apple.com/en-ca/118223 and you should be able to do so with no issues. Hope that helps out! If this is not for the App Store, please re-open the issue and let me know.

**Comment by user12346abc** [comment]
Hello,
Yes, it was from the App Store, I will contact them. Thank you so much for
your help.
