### ISSUE TITLE
Exporting Results from a Query

### ISSUE THREAD

**Issue by powellae** [hankinsoft/SQLPro#103]
This may be easily done, but I am struggling with how to export the table built by a specific query I have built. Any help?

**Comment by msharp** [comment]
Currently, the only way to get the query results out of SQLPro Studio is by copy/pasting from the results grid.

IMO this is rather crude, and the header row is not included on the clipboard.

I would love to have better options for running a query and writing the results directly to a file.

**Comment by davidharrison92** [comment]
!! Bump. It'd be great if we could get text based reports as SSMS can do.

**Comment by hankinsoft** [comment]
Hi,
You can actually export results by right clicking on a result set and choosing export (or copy if you want it in the clipboard). Recent versions also add a button on each grid as well. Please see the following video for an example:

https://youtu.be/syAXSSAl6iE

Is that what you are looking for?

**Comment by msharp** [comment]
Just downloaded version 1.0.125. The new feature "Download result set as" is a big improvement.

It seems to do some odd things, like write the string "<null>" into the CSV file when there is a `NULL` in the column. IMO this is the wrong behaviour, it should just leave the CSV field empty.

Also, would be great to get automatic updates, rather than needing to manually download the new build.

**Comment by hankinsoft** [comment]
> It seems to do some odd things, like write the string "<null>" into the CSV file when there is a NULL in the column. IMO this is the wrong behaviour, it should just leave the CSV field empty.

That makes sense. I'll take a look at it for the next release.

> Also, would be great to get automatic updates, rather than needing to manually download the new build.

Unfortunately sandboxed apps are unable to auto-update as they cannot overwrite themselves. If you would prefer, you can switch to using the App Store version of the product which does auto-update, just send me an email (kyle @ hankinsoft.com) with your current license key and I can provide you with a MAS promo code.

**Comment by hankinsoft** [comment]
Hi, per email chat I sent a promo code for you to switch to the MAS version.

In response to:
> It seems to do some odd things, like write the string "<null>" into the CSV file when there is a NULL in the column. IMO this is the wrong behaviour, it should just leave the CSV field empty.

I have made a change, but not exactly as you requested. When exporting, nulls will now come out as NULL in the CSV (this matches the existing copy as csv behavior and IMO is more appropriate than a blank field). The new version is already available both in the Mac App Store and via the website. If this sorts everything out, please let me know and I will go ahead and close the issue!

**Comment by msharp** [comment]
Thanks @hankinsoft 

The string "NULL" is fairly common in CSV exports. It's easy enough to remove with sed when I don't want it.

**Comment by ntunney** [comment]
I'd love to see it export simply "" when NULL.  Just my opinion, but it would make my life much easier.

**Comment by davidharrison92** [comment]
> I'd love to see it export simply "" when NULL. Just my opinion, but it would make my life much easier.

I disagree. There is a significant difference between an empty string ("") and NULL. Nulls should be clearly identifiable apart from "".

**Comment by hankinsoft** [comment]
What I've done in the iOS version of SQLPro apps is an an options page when export is selected:

![img_6903](https://user-images.githubusercontent.com/3160528/32325838-60660dba-bfaf-11e7-9212-674529c35e93.png)

I'll add this to the macOS apps in and upcoming build and also include an option for NULLS as empty or NULL.

**Comment by ntunney** [comment]
That would be amazing, thank you.
