### ISSUE TITLE
How do I query the first 100 data by default?

### ISSUE THREAD

**Issue by litttlefisher** [hankinsoft/SQLPro#104]
Maybe I do not need to query all data, I only want to know the fields of the table, how can I query the first 100(or 10 if can) data by default?

It maybe need 10s to query all data, but I only need 0.1s to know the fields of the table.

**Comment by davidharrison92** [comment]
SELECT TOP 100 * FROM yourtable  (MSSQL)

SELECT * FROM yourtable LIMIT 100 (MySQL)

**Comment by litttlefisher** [comment]
No no no,I don't want to format the sql, I hope the software can limit the data by default. Example as PLSQL(a software) on Windows

**Comment by davidharrison92** [comment]
Right clicking the Table Name in the Obj Explorer will by default cap it at 100 rows.

![screen shot 2017-06-27 at 11 20 57](https://user-images.githubusercontent.com/3440843/27582986-d2362e00-5b2a-11e7-8613-8446b25a1b45.png)


However, limiting the software to just return 100 rows by default isn't a great idea. It leads easily into misunderstandings about that data you're returning.

**Comment by hankinsoft** [comment]
Hello,
Unfortunately SQLPro does not perform any data limiting (and this is not something I plan on implementing). SQLPro runs on the theory that a user should see the results of the query they entered and any limiting should be done by the user.
