### ISSUE TITLE
SQLPro for Postgres

### ISSUE THREAD

**Issue by alemar11** [hankinsoft/SQLPro#105]
It would be awesome if this app could show and edit the foreign keys.
Great product by the way!

**Comment by hankinsoft** [comment]
Hi,
You can edit foreign keys in the table designer. Please see the following example: https://youtu.be/b__zQBn0728

Is that what you are looking for, or am I misunderstanding?

Thanks!

**Comment by alemar11** [comment]
Thanks!! 🙏
