### ISSUE TITLE
Null datetime fields show incorrect values

### ISSUE THREAD

**Issue by nezriffic** [hankinsoft/SQLPro#107]
When a **datetime** field is **NULL**, SQLPro displays it incorrectly.

Displays (current date 2017-07-08 with time 00:00:00):
**2017-07-08 00:00:00**

While it should display:
**0000-00-00 00:00:00**

Screenshots:
**1. SQLPro:** https://www.evernote.com/l/AZILbkYGnVtJF7T_4xPIke7ECoIGMmH7XRc
**2. Other client:** https://www.evernote.com/l/AZIFnSIzGZZGaLz5biUjijuoWLCCNgAtouw

**Comment by hankinsoft** [comment]
Hi,
What database are you using (Postgres, MySQL, etc)? I'm surprised that you are not getting 'NULL' as the result rather than an 'empty date'? (As seen in the attached image).
<img width="678" alt="null" src="https://user-images.githubusercontent.com/3160528/28418602-a6c7926c-6d32-11e7-9b8b-5319c62b3d1f.png">

**Comment by nezriffic** [comment]
It is MySQL,
and the field is defined as: **`createdAt` datetime NOT NULL**

**Comment by hankinsoft** [comment]
Thank you! I'm still not quite understanding something 100%..... If the column is defined with `NOT NULL`, how does running a `WHERE IS NULL` return any records?

**Comment by hankinsoft** [comment]
I think I've reproduced it using the following query:

select CAST(0 AS DATETIME)

Looking into a fix now.

**Comment by nezriffic** [comment]
quickly did a test:

`DROP TABLE IF EXISTS testTable;
CREATE TABLE `testTable` (
  `createdAt` datetime
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SELECT * FROM testTable LIMIT 100;
INSERT INTO testTable VALUES(NULL);
-- 
ALTER TABLE testTable MODIFY createdAt datetime NOT NULL;
SELECT * FROM testTable LIMIT 100;
-- here we have the issue
`

**Comment by hankinsoft** [comment]
Are you using SQLPro Studio or SQLPro for MySQL? I've got a fix available if you are able to give it a try?

**Comment by nezriffic** [comment]
SQLPro Studio Version 1.0.114 (Build 1045)

**Comment by hankinsoft** [comment]
Could you download the following build and give it a try:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.125.app.zip

Please let me know if that sorts things up for you. If so I will also get it submitted to the Mac App Store.

**Comment by nezriffic** [comment]
sure, I'll check in few minutes

**Comment by nezriffic** [comment]
works for me, displays nicely `0000-00-00 00:00:00`

**Comment by hankinsoft** [comment]
Great thank you! I'll submit an update to the Mac App Store as well.

**Comment by nezriffic** [comment]
perfect, thanks! :)

**Comment by hankinsoft** [comment]
Mac App Store version is available now with the fix. Thanks for reporting it to me!
