### ISSUE TITLE
Preferences for Tab Style aren't saving between app launches

### ISSUE THREAD

**Issue by kinnell** [hankinsoft/SQLPro#108]
The preference for Tab Style is not getting saved. I can change it for a current session, but if I re-open the app (SQLPro Studio 1.0.124), the preference has been reset back to the default of "Tabs".

**Comment by hankinsoft** [comment]
Thanks! Fixed for the next build. Should be available later this week.

**Comment by hankinsoft** [comment]
New version is available via the Mac App Store, or if your using the website download you should see an update available via the database tree next launch (or grab it at http://www.sqlprostudio.com/download.php).

**Comment by kinnell** [comment]
Thank you!
