### ISSUE TITLE
'Tab Style' preference not respected when using 'Shift-Left' or 'Shift-Right' commands

### ISSUE THREAD

**Issue by chucksense** [hankinsoft/SQLPro#109]
When using `Shift-Left` (`Cmd-[`) or `Shift-Right` (`Cmd-]`), it is always using tabs even if Tab Style preference is set to two or four spaces.

SQLPro Studio 1.0.124 (Build 1056) on macOS 10.12.5

**Comment by hankinsoft** [comment]
Thanks, fixed for the next build.

**Comment by hankinsoft** [comment]
Which app are you using? (And is it from the Mac App Store or downloaded from our website).

**Comment by chucksense** [comment]
SQLPro Studio 1.0.124 (Build 1056) direct downloaded.

**Comment by hankinsoft** [comment]
Sorry I just realized you had posted that in the original message 👍 
New version is available at: http://www.sqlprostudio.com/download.php or the app will prompt you to upgrade next time you launch it. Please let me know if this resolves the issue for you!
