### ISSUE TITLE
Feature Request - Add shortcut mapping keys and new shortcuts

### ISSUE THREAD

**Issue by BradRuderman** [hankinsoft/SQLPro#11]
Add ability to change keyboard shorts for more then just the execution button. I would love shortcut customizations for format query and implement other shortcuts that don't currently exist such as switch tabs.

**Comment by hankinsoft** [comment]
Thank for the suggestion. I have had a few other users request customizing shortcuts, so I will look into adding a preference for customizing more in a future build.

> shortcuts that don't currently exist such as switch tabs.

FYI you can switch tabs via `Cmd + Shift + [`  and `Cmd + Shift + ]`.

**Comment by hankinsoft** [comment]
Autocomplete trigger should also be customizable (it currently defaults to the escape key).

**Comment by dharamsk** [comment]
+1

Most of my team has been using postico for a while, and I really like many of the features of sqlpro for postgres. I tried to Cmd + / to comment a line and was sad... :P

**Comment by hankinsoft** [comment]
Thanks for the +1, they really help me figure out which features to add
next! I'll move this up in my todo list.

**Comment by aaronbiller** [comment]
+1

Part of the team above 😃 
Super handy shortcut to have.

**Comment by luveti** [comment]
Any updates on this? Pretty much all code editors out there default autocomplete to `⌃Space`, with `Esc` being used to dismiss it.

**Comment by hankinsoft** [comment]
Just to note that shortcut mappings have been available for awhile now. If anyone wants any additional shortcut mappings added, please let me know!
