### ISSUE TITLE
SQLPro Studio - Copying data from results copies all columns and rows

### ISSUE THREAD

**Issue by AvonGenesis** [hankinsoft/SQLPro#110]
Just updated to SQLPro Studio Version 1.0.125 (Build 1057) and found a bug with copying data out of the results table. When selecting a single entry from the result set, it will copy all the row and column data up to that point.

Below screenshot is an example of what is happening. Select single data from result set, copy it, and paste it within the above window results in the columns and rows being copied up until that data.

<img width="1481" alt="screen shot 2017-07-21 at 12 57 49 pm" src="https://user-images.githubusercontent.com/905293/28480160-3df62770-6e14-11e7-91cb-366ba18533f9.png">

**Comment by hankinsoft** [comment]
Thank you! I’ll have this fixed early next week.

**Comment by hankinsoft** [comment]
FYI, this should be all fixed up via: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.126.app.zip and also via a new update on the Mac App Store. If you get the chance, please let me know if this sorts the issue for you!

**Comment by AvonGenesis** [comment]
Thanks, can confirm that this issue is fixed in this build. 👍

**Comment by Kullersj** [comment]
I'm still having this issue on SQLPro for Postgres

**Comment by hankinsoft** [comment]
@Kullersj ahhh yes sorry. Pushing updates now, they should be available by late tomorrow.
