### ISSUE TITLE
Feature : Foreign key linking in data grid

### ISSUE THREAD

**Issue by windware** [hankinsoft/SQLPro#112]
I have been trying this app for a few days and I see much potential to replace SequelPro as it supports multiple databases.

I have a feature request but when I list data of a table and a column has a foreign key, in SequelPro, you can click on the arrow to jump to the data right away, which is useful to see what it refers to.

Is it possible to have this implemented?

![foreign-key-link](https://user-images.githubusercontent.com/4352236/28544365-d305a0d4-70fd-11e7-93c2-d17e36b8cf60.png)

**Comment by hankinsoft** [comment]
Hi,
This has been added to all the latest versions of SQLPro. Please ensure you are using the latest versions and the links will be available.

**Comment by jim256** [comment]
@hankinsoft I'm also a huge fan of this feature. I just tried it with a Postgres table it works with in Postico, but it didn't work. When I scripted the table, I noticed the column was missing  "REFERENCES table(column)" in the DDL, though it shows in the DDL in Postico.

 Thoughts?

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.12.app.zip? I think that will sort it out. If not, could you please create a new issue? It makes it a bit easier for me to track it. Thanks!
