### ISSUE TITLE
Feature : Allow modifying "unsigned" state of a column

### ISSUE THREAD

**Issue by windware-ono** [hankinsoft/SQLPro#113]
When I go to "Alter table" on a table, I can edit its properties but there is no way to change that an INT column is "unsigned" or not, unless of course I type the SQL to modify it manually.

This becomes a problem when I try to add a foreign key, when the target column is "unsigned"  but the source column is not and I just get an error that they cannot be referenced.

**Comment by hankinsoft** [comment]
Thanks. I'll allow the column to be editable (double click to edit and manually enter type a value), plus the dropdown picker.

**Comment by windware** [comment]
Thanks.

Can you do it in a way that the 'unsigned' is a checkbox just like 'nullable' checkbox but only available under numeric types?

Sample image.
![unsigned](https://user-images.githubusercontent.com/4352236/28578085-9e1fced0-7193-11e7-8e76-0902953ce2b9.png)

**Comment by hankinsoft** [comment]
Sure! I'll work on adding the other columns you asked for as well. It will
take me a bit longer to get them all in.

**Comment by hankinsoft** [comment]
Unsigned has been added as an option when altering table columns. It's available in all the latest releases.
