### ISSUE TITLE
Feature : Allow reordering of columns with drag and drop

### ISSUE THREAD

**Issue by windware** [hankinsoft/SQLPro#114]
I'd like to reorder columns with drag and drop which is useful when I add a column on an existing table but want it somewhere above than at the end.

Currently I guess the only way is to type SQL to do that.

**Comment by hankinsoft** [comment]
Should be do-able, I see that mysql allows columns to be reordered via the alter table change/modify syntax, so I'll take a look into adding it.

**Comment by hankinsoft** [comment]
Added for the next release.

**Comment by windware** [comment]
How can you do this through the GUI?
I tried to drag columns from the table list but didn't do anything on the latest SQLPro Studio.

![screen shot 2017-10-05 at 6 30 50](https://user-images.githubusercontent.com/4352236/31200684-e152995e-a996-11e7-926d-b131db69cc37.png)

**Comment by windware** [comment]
Sorry, never mind, found it in the "Alter table" screen. Working as expected.

**Comment by hankinsoft** [comment]
Thanks for getting these marked as closed for me! I’ll hopefully be fixing
some of the other ones up within the next couple of weeks. I’ve just
recently released my products on iOS, so I’m free to work on my backlog
again :-)

**Comment by sindaniel** [comment]
How was solved?
