### ISSUE TITLE
Feature : Result grid ordering behavior

### ISSUE THREAD

**Issue by windware** [hankinsoft/SQLPro#115]
I see that in the result grid, I can sort by column from the data set of the executed query but this is, at least in my case, usually not the desired behavior.

Say, a table contains 1000 rows, and by default it selects the first 100 rows.
When I reverse the ordering by a column, I'd like to see it being ordered from the entire table but limits to the first 100 rows found not just from the first 100 rows returned by the initial query.

I can certainly get what I want by not putting 'LIMIT' clause but with a large table, it will display the entirety of the data which could be time consuming.

I can just type it all in SQL to get the desired effect, but then that kind of defeats the purpose of being able to sort of clicking on the column names.

You can see this behavior in SequelPro.

**Comment by windware** [comment]
On a related note, I'd like to see the same behavior by picking the result from the entire data set when using the filtering.

**Comment by hankinsoft** [comment]
Hi,
Unfortunately SQLPro works on the 'current user specified data set' by design. If the user wants to order/filter before the result set I leave it up to the user to update their query. I currently have no plans on changing this design.
