### ISSUE TITLE
Feature : More filtering options

### ISSUE THREAD

**Issue by windware-ono** [hankinsoft/SQLPro#116]
When I use 'Filter' on the result data set, it gives me 'contains', 'is', 'is not', 'begins with' and 'ends with' but I'd like to see a comparison operator, so, for example, I can filter for ID larger than a certain number.

Also, it would be more straighforward if you can have the filter options that is the equivalent of the SQL to know what would be queried.

Attaching sample filtering options from SequelPro.
![sequelpro-filter](https://user-images.githubusercontent.com/4352236/28545461-014ef1ee-7102-11e7-8bb0-7b7bf6cb8c1e.png)

**Comment by hankinsoft** [comment]
I've changed the filter options quite a while ago. If you find something is missing that you would specifically like, please let me know.
