### ISSUE TITLE
Feature : Keep a log of SQL that got executed

### ISSUE THREAD

**Issue by windware** [hankinsoft/SQLPro#117]
It would be nice to know what got executed by making actions through GUI, in case of miss clicking or just to make sure the action was executed as an intended SQL in a log viewer.

Attaching a sample from SequelPro.
![sql-logs](https://user-images.githubusercontent.com/4352236/28545616-a9e3d3c4-7102-11e7-92a2-153a6474cca7.png)

**Comment by hankinsoft** [comment]
Makes sense. I'll take a look into this for a future build.

**Comment by hankinsoft** [comment]
I went a separate way with this. Rather than show a log file of history, SQLPro now shows a confirmation dialog (showing the query to be executed) for any destructive or alteration actions. I do not currently plan on adding a query history as I feel this serves the purpose.
