### ISSUE TITLE
Feature : Grouping/reordering for server connection screen

### ISSUE THREAD

**Issue by windware-ono** [hankinsoft/SQLPro#119]
I'd like to have a feature to group the servers in the connection screen with manual reordering, so that if I have a few dozen servers listed, I can easily find what's where under each groups.

Sample image of grouping.
![connection-grouping](https://user-images.githubusercontent.com/4352236/28546197-d891c76a-7104-11e7-85d9-66fbd70ac2fb.png)

**Comment by heruan** [comment]
This is still missing in 2019 and I'd like this too: I have dozens of servers listed and the search feature is already very useful, but being able to also group them would be much better!

**Comment by hankinsoft** [comment]
Thanks for the reminder. I'll take a look into this in an upcoming build.

**Comment by hankinsoft** [comment]
I have a first build available that allows the creation of custom connection groups. Connections can be dragged/dropped between connection groups. It also allows expanding/collapsing groups. I still need to add an option to reorder the groups themselves. Any feedback is welcome.

https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.25.app.zip
