### ISSUE TITLE
Feature : Double click action on functions/stored procedures

### ISSUE THREAD

**Issue by windware** [hankinsoft/SQLPro#120]
Currently, if I double click on any of functions and stored procedures, they do nothing but it feels convenient if you can open the modify screen or some read only screen of the function for a quick view of what it is about.

**Comment by hankinsoft** [comment]
Makes sense. Fixed for the next build. (Both double click and cmd + down now display the alter statement for functions & procedures).

**Comment by hankinsoft** [comment]
Just to note all the recent builds should have this fixed. If you get the chance, please take a look and let me know if you still see any issues.

**Comment by windware** [comment]
Working great.
