### ISSUE TITLE
Feature : Reset auto increment counter

### ISSUE THREAD

**Issue by windware-ono** [hankinsoft/SQLPro#121]
I'd like to be able to reset the auto increment counter of an auto incrementing column with and without specifying the number.

Currently, I guess I can only do that through typing SQL.

Sample image from SequelPro.
![reset-auto-increment](https://user-images.githubusercontent.com/4352236/28546410-9b336d1e-7105-11e7-922b-262dc00f1b7f.png)

**Comment by hankinsoft** [comment]
Going to close this for now unless I receive additional request for it.
