### ISSUE TITLE
Feature : Character encoding for table/column

### ISSUE THREAD

**Issue by windware-ono** [hankinsoft/SQLPro#122]
I'd like to be able to read (and modify) the character encoding for a table and a column.

Attaching sample image from SequelPro.

[tables]
![character-encoding-table](https://user-images.githubusercontent.com/4352236/28546629-623ad08c-7106-11e7-805c-7fa24b93e1f3.png)

[columns]
If a character encoding is not specified for a column, it shows greyed out by showing the character encoding from the table.
![character-encoding-column](https://user-images.githubusercontent.com/4352236/28546651-76f9fa52-7106-11e7-8599-de38d04466e8.png)

**Comment by hankinsoft** [comment]
I'm going to close this, but will consider re-opening it if I receive additional requests for it.
