### ISSUE TITLE
Bug : Do not allow 'Accept' button to be pressed until database information is loaded on 'New table'

### ISSUE THREAD

**Issue by windware** [hankinsoft/SQLPro#124]
When the server isn't as responsive, trying to create a new table and types in the table name, you're allowed to click 'Accept' to create one, except you get an error saying, "Unknown storage engine 'Loading'".

![new-table-loading](https://user-images.githubusercontent.com/4352236/28547432-c1f04e64-7109-11e7-8251-5d167b8f30c2.png)

**Comment by hankinsoft** [comment]
Thanks. Fixed for the next build.

**Comment by hankinsoft** [comment]
Just to note all the recent builds should have this fixed. If you get the chance, please take a look and let me know if you still see any issues.

**Comment by windware** [comment]
Looks good.
