### ISSUE TITLE
Feature: MSSQL Table Valued Function => Select Top 100 Rows... Context Menu Item

### ISSUE THREAD

**Issue by APM3** [hankinsoft/SQLPro#125]
It would be nice to have a "Select Top 100 Rows..." context menu item on Table Valued Functions for MSSQL.  Popup Dialog box to allow Parameters to be set if needed for call.

**Comment by hankinsoft** [comment]
Makes sense. I'll look into this for a future build.

**Comment by hankinsoft** [comment]
This has been available for awhile, however I forgot to update the issue. If you get the chance, please give it a try and let me know if the issue has been sorted for you.
