### ISSUE TITLE
'Script as > CREATE to' sometimes does not generate first column

### ISSUE THREAD

**Issue by martinrybak** [hankinsoft/SQLPro#126]
Here is an example of the primary key column `idMobileDeviceToken` not being generated.

```
CREATE TABLE [Foo].[Bar]
(
  [idUser] [uniqueidentifier]  NOT NULL,
  [DeviceID] [nvarchar](75)  NOT NULL,
  [Token] [nvarchar](40)  NOT NULL,
  [Created] [datetime]  NOT NULL DEFAULT (getdate()),
  [LastUsed] [datetime]  NOT NULL DEFAULT (getdate())
)
ALTER TABLE [Foo].[Bar] ADD CONSTRAINT Foo_Bar_Key PRIMARY KEY  ([idMobileDeviceToken])
```

Using SQLPro Studio 1.0.126 (build 1059) with Microsoft SQL Server 2014 (SP2-GDR)

**Comment by hankinsoft** [comment]
If you get the chance, could you post the raw SQL for this table (as generated by visual studios)? I've tried to reproduce this issue myself but so far I haven't been able to.

**Comment by martinrybak** [comment]
Here is the output from SSMS v17.1:

```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Foo].[Bar](
	[idMobileDeviceToken] [int] IDENTITY(1,1) NOT NULL,
	[idUser] [uniqueidentifier] NOT NULL,
	[DeviceID] [nvarchar](75) NOT NULL,
	[Token] [nvarchar](40) NOT NULL,
	[Created] [datetime] NOT NULL,
	[LastUsed] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idMobileDeviceToken] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Foo].[Bar] ADD  CONSTRAINT [DF_Bar__Created]  DEFAULT (getdate()) FOR [Created]
GO

ALTER TABLE [Foo].[Bar] ADD  CONSTRAINT [DF_Bar__LastUsed]  DEFAULT (getdate()) FOR [LastUsed]
GO
```

**Comment by hankinsoft** [comment]
Thanks, I've been able to reproduce the issue and am working on a fix. The missing column happens when the table specified is not the same schema as the users default schema.

**Comment by hankinsoft** [comment]
I've got a build available for testing. Are you using SQLPro for MSSQL or SQLPro Studio?

**Comment by martinrybak** [comment]
SQLPro Studio

**Comment by hankinsoft** [comment]
Can you try
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.134.app.zip?
That should sort it out. Please let me know if you get a chance.

**Comment by martinrybak** [comment]
👍
