### ISSUE TITLE
Feature : Selectable ENUM fields

### ISSUE THREAD

**Issue by windware-ono** [hankinsoft/SQLPro#129]
I'd like to be able to modify the table definition for ENUM fields by selecting the already defined values.

Also, for the data list, it would be convient to modify the value by picking the defined values from a drop down (with null if nullable).

Attaching the screenshot from SequelPro.
![enum-definition](https://user-images.githubusercontent.com/4352236/28900962-f4aa3c48-782f-11e7-96c0-1b1ec5674c3d.png)
![enum-value](https://user-images.githubusercontent.com/4352236/28900963-f4c7db68-782f-11e7-856e-9b5eb4e7f820.png)

**Comment by hankinsoft** [comment]
I'm going to close the issue for now. If I receive more requests for this, I will look further into it.

**Comment by xC0der** [comment]
Bump - Being able to see the enum values in the alter table view, as well as being able to change them without having to script out the table should be a pretty core feature.
