### ISSUE TITLE
Feature : Connect to Oracle db as sysdba 

### ISSUE THREAD

**Issue by jibe22** [hankinsoft/SQLPro#130]
Hi,

Is it possible to add a "as sysdba" connection with Oracle ?

Thanks,

jibe

**Comment by hankinsoft** [comment]
Hi. I just had an update approved via SetApp which contains the option to pick a 'role' for Oracle connections. If you get the chance, would you be able to give it a try? The Oracle connection screen should now look like this.

<img width="1009" alt="screen shot 2017-10-05 at 8 40 45 am" src="https://user-images.githubusercontent.com/3160528/31225555-057c00d8-a9a9-11e7-8003-2792b104cc3c.png">

I'm not sure how long it takes for SetApp updates to flow down to the users, but I was notified ~4 hours ago that the update was approved.

**Comment by jibe22** [comment]
Hi !

I just tried and it’s working !

Thank you!

Jean-Baptiste 

Envoyé de mon téléphone portable.
