### ISSUE TITLE
Feature : resizable window for connections list

### ISSUE THREAD

**Issue by jibe22** [hankinsoft/SQLPro#131]
Hi,

Is it possible to make the connection list window resizable or / and to add a search field to make easier to find a connection ? 

Thanks,

jibe

**Comment by hankinsoft** [comment]
Hi,
A search option has been added. I've had troubles getting resize to work properly (https://stackoverflow.com/questions/48567326/full-width-nscollectionviewflowlayout-with-nscollectionview). I'm hoping to get it working at some point, but its a bit lower priority at the moment.

**Comment by hankinsoft** [comment]
Just to note, resize of the connection window is now available for all apps. It's only supported on macOS 10.14+ (Mojave) as older versions of macOS have a bug when resizing NSCollectionViews.
