### ISSUE TITLE
Issue : no message when using "cmd + q" shortcut

### ISSUE THREAD

**Issue by jibe22** [hankinsoft/SQLPro#132]
Hi,

When using "cmd + q", there's no message to warn a file was not saved.

Using the red dot is OK, but only if just one tab is open… a second one won't be saved…

Thanks,

jibe

**Comment by hankinsoft** [comment]
Fixed for the next build.

**Comment by hankinsoft** [comment]
This should be all fixed up. I think your using the SetApp version if I remember correctly and that was updated a few days ago.

**Comment by jibe22** [comment]
Hi,

Yes, it’s fixed now even in the Setapp version. Thanks !

Jean-Baptiste Rouault 

Envoyé de mon téléphone portable.
