### ISSUE TITLE
[BUG] Returns null when column has a special character

### ISSUE THREAD

**Issue by FCO** [hankinsoft/SQLPro#133]
at least using LATIN1 database

**Comment by hankinsoft** [comment]
Which database server is this for? MySQL?

**Comment by FCO** [comment]
PostgreSQL 

Enviado do meu iPhone

Em 4 de ago de 2017, à(s) 19:11, Kyle Hankinson <notifications@github.com> escreveu:

> Which database server is this for? MySQL?
> 
> On Fri, Aug 4, 2017 at 11:10 AM Fernando Correa de Oliveira <

**Comment by hankinsoft** [comment]
I've never been able to reproduce this issue. Could you possible create a single sample query which reproduces the issue?
