### ISSUE TITLE
BUG: MSSQL DateTimeOffset not presented correctly in Query Results

### ISSUE THREAD

**Issue by APM3** [hankinsoft/SQLPro#134]
DateTimeOffset results are showing with a ':' separator between the seconds and fractional seconds.  It should be a '.'.
Example:
'2017-08-16 13:21:35:4079676 -07:00' should show as '2017-08-16 13:21:35.4079676 -07:00'

**Comment by hankinsoft** [comment]
Thank you, this is fixed for the next build.

**Comment by bendoh** [comment]
I'm still experiencing this issue in 1.0.191 (build 4351)

**Comment by hankinsoft** [comment]
FYI this is available in all the latest builds. If you get the chance, please make sure you are using the latest build and give it a try. If your not seeing the proper behaviour please take a screenshot of what you are seeing along with a screenshot of the 'about' dialog.
