### ISSUE TITLE
Feature: Table specific function text autocompletion

### ISSUE THREAD

**Issue by Nathan389** [hankinsoft/SQLPro#135]
Some PostgreSQL extensions like PostGIS offer a great number of default functions (~1150) and it would be helpful if they were included as part of the text autocompletion as well as more prompt refresh to autocompletion after a new table or function is added, rather than disconnecting and reconnecting to the server.

**Comment by hankinsoft** [comment]
Adding the postgis autocomplete seems like a good idea. I'll take a look into this for an upcoming build.

**Comment by hankinsoft** [comment]
> more prompt refresh to autocompletion after a new table or function is added, rather than disconnecting and reconnecting to the server.

This has been added.

For PostGIS, does anyone have a list of functions it adds? I'm looking to add them but I'm having a hard time finding a reference guide.

**Comment by hankinsoft** [comment]
Closed for now. I will add more PostGIS items when more users request it.
