### ISSUE TITLE
Feature: Make username optional for Postgres

### ISSUE THREAD

**Issue by ascendbruce-hb** [hankinsoft/SQLPro#136]
Why:

* For Postgres, username is actually optional. I do that in localhost for ease of development.
* Surely I can create an account with password to workaround this. But it will be nice to handle it out of the box. [PSequel](http://www.psequel.com/) does that.

![image](https://user-images.githubusercontent.com/12945452/30530731-d7eeee6c-9c7b-11e7-8c8b-be123cf96a2d.png)

My env:

macOS Sierra 10.12.3
PostgreSQL 9.6.2
SQLPro Studio 1.0.130 (build 1066)

**Comment by raytorres280** [comment]
any update on this issue? this is the single thing keeping me from purchasing.

**Comment by hankinsoft** [comment]
Username will no longer be required as of the next release.

**Comment by hankinsoft** [comment]
Just to note, username is no longer a requirement in all the latest versions.
