### ISSUE TITLE
Default Constraint being added randomly

### ISSUE THREAD

**Issue by Prefinem** [hankinsoft/SQLPro#139]
Just had this issue, didn't find a setting or anything for it.

1) Creating or altering a table
2) add a column
3) change name of column
4) try and remove / update column type which fails because of a constraint already added to column
5) write drop constraint query by hand and remove it
6) continue editing column fine

This is on a SQL Server connection.  Ran into it a few times today while creating a few tables.  Coworker also experiences it (not just my computer).

If I could turn autosave off until I am ready to save, that would fix it, or view constraints would make it easier to remove them.

MacBook Pro
Mac OS X 10.12.6
SQLPro Studio Version 1.0.127 (Build 1061)

**Comment by hankinsoft** [comment]
What type of database server was this happening with? Is anyone else seeing this issue?

**Comment by Prefinem** [comment]
SQL Server 2016

**Comment by hankinsoft** [comment]
Your using the table designer? Can you update to the latest version of the app? In the older version you would have been using changes were made on the fly based. In the latest versions, the table designer waits until you hit apply, then shows you the query its going to use for the creation/alter. If you see the constraint being added here, could you post a screenshot and/or steps of what your doing to see it?

**Comment by Prefinem** [comment]
I just tested and it seems to have been fixed in the latest version.  Closing ticket for non issue

**Comment by hankinsoft** [comment]
Thanks for letting me know and sorry for the long delay!

**Comment by Prefinem** [comment]
No worries!
