### ISSUE TITLE
Feature Improvement: Selecting a query from history

### ISSUE THREAD

**Issue by BradRuderman** [hankinsoft/SQLPro#14]
When selecting a query from the history dropdown it shouldn't replace the whole query in the window, it should append it to where the cursor is. Often times I want to see how I changed a query over time, not replace the whole query.

**Comment by hankinsoft** [comment]
I'm doing some history window improvements now, so I just wanted to ask a few questions about this.

> 'it shouldn't replace the whole query in the window, it should append it to where the cursor is.'

The new history window has a 'Restore in new tab' option, which opens the specified query in a new tab. Would that suite your needs?

**Comment by BradRuderman** [comment]
It would suite my needs but it wouldn't be ideal, since it could become tab hell. I think the default behavior is to just append it wherever the cursor is. With complex queries its nice to be able to run the query you want then as you build a larger query you go to your status history and embed one of your previous queries as a sub query. It would also be nice for query history to persist between application closes. Not sure if it already does that or not.

**Comment by hankinsoft** [comment]
Hello,
I've decided to keep the 'replace' as the default action as this seems to be what most users lean towards (the most common use case seems to be open a new tab and then restore from history, replacing the empty contents).
