### ISSUE TITLE
Export table data as CSV?

### ISSUE THREAD

**Issue by ocdtrekkie** [hankinsoft/SQLPro#140]
I really wanted to try pulling my data into an Excel spreadsheet for something, and I couldn't come up with any way to get my data out of my SQLite file short of finding some other piece of software to do it. I was hoping I could copy and paste out of the data tab or something.

I'm using SQLPro for SQLite on Windows 10. Fantastic software, it's helped me a lot as I worked on my own software.

**Comment by hankinsoft** [comment]
The latest version should now be available and includes export to csv. You can right click on a table in the database tree and choose 'Export' -> 'CSV', or you can right click on any data grid and choose the same. Please let me know if that sorts the issue out for you!

**Comment by ocdtrekkie** [comment]
Just tried it. Looks great.

I successfully exported a table with 1.2 million records in it, so it seems pretty robust.
