### ISSUE TITLE
Feature: Icon/color code FK in sidebar

### ISSUE THREAD

**Issue by guojenman** [hankinsoft/SQLPro#141]
In sidebar, primary keys get a key icon, that's great but there's no easy way to tell which columns are foreign keys. There's no easy way to know what columns are foreign keys.

Suggestions:
1. Add "FK," to the type label below the name. i.e, "FK, int not null"
2. Use different color for FK
3. Use an icon like PK

**Comment by hankinsoft** [comment]
Closing for now. If I receive additional requests for this, I will push it forward and take a further look into getting it added.
