### ISSUE TITLE
bug: auto-complete should change case of letters already typed

### ISSUE THREAD

**Issue by guojenman** [hankinsoft/SQLPro#143]
assuming we have a table called "MY_TABLE"

**current:**
when i type "my_", autocomplete finishes this to "my_TABLE"

**expected:**
autocomplete should fix casing and complete to "MY_TABLE"

**Comment by hankinsoft** [comment]
FYI this should be fixed in all of the latest builds. if you get the chance, please give it a try and let me know if you are still seeing invalid behaviour.

**Comment by jim256** [comment]
@hankinsoft I'm seeing this when using both tab or return to autocomplete

Snowflake 3.42.3
PostgreSQL 10.9
SQLPro Studio 2019.09.20 (Build 110546)
macOS 10.14.6 (18G95)

**Comment by hankinsoft** [comment]
When you see this behaviour, how is `my_TABLE` displayed in the database tree? Autocomplete SHOULD be replacing it with exactly what it found in the database (if its lowercase, SQLPro should make it lowercase - if it was uppercase, SQLPro should be making it uppercase). Is this not the behaviour you are seeing? Would it be possible to get a screenshot after autocomplete has been inserted showing both the table in the database tree, plus the inserted table? Thanks!

**Comment by jim256** [comment]
It looks like build 110553 from #295 took care of this. Previously, if I'd typed "my_" and the table in the database was all caps ("MY_TABLE)", autocomplete would complete it as "my_TABLE". It now completes it correctly as "MY_TABLE".

**Comment by hankinsoft** [comment]
Ok. If you run into this again, please prove the screenshots requested above. Thanks!
