### ISSUE TITLE
Fields with Spaces in Automated INSERT statements

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#144]
Hiya,

When using the Right Click --> Copy as Insert  options, if the originating field has a space in the name (which, yes, I know if pretty poor practice, but I didn't write the DB!), it causes errors:

e.g.
`INSERT INTO TabelName (SOP Number Prefix, Shipment Name, Model Number, Machine ID...`

should really say
`INSERT INTO TabelName ([SOP Number Prefix], [Shipment Name], [Model Number], [Machine ID]...`

Cheers,
Dave

**Comment by hankinsoft** [comment]
Thanks, fixed for the next build.

**Comment by hankinsoft** [comment]
Just to check are you using SQLPro for MSSQL or SQLPro Studio? I cannot remember. I have a Studio version with the fix available here: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.144.app.zip

**Comment by davidharrison92** [comment]
Thanks, just tried that and it looks good.
