### ISSUE TITLE
Meta - Support Registration Broken

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#145]
The replacement for PHPBB has an issue when registering. Doesn't send the first confirmation link, and re-sending it returns the following fatal error:

**URL: **https://www.hankinsoft.com/q2a/index.php?qa=confirm

Question2Answer fatal error:
Could not send email confirmation

Stack trace:

require() in index.php:27
require() in qa-index.php:183
qa_get_request_content() in qa-page.php:824
require() in qa-page.php:203
qa_send_new_confirm() in confirm.php:50

**Comment by hankinsoft** [comment]
Thanks! I've removed the forum as it was receiving more spam that I could keep up with. The forum now redirects to a hosted forum that I don't need to manage spam, emails, etc.
