### ISSUE TITLE
JSON export issues.

### ISSUE THREAD

**Issue by nomoon** [hankinsoft/SQLPro#147]
The JSON export has a few problems with following the spirit of the JSON standard (http://www.json.org/):

1.  Numeric type results are exported as quoted strings containing the numbers (i.e. `"key": "5"` instead of `"key": 5`). JSON natively supports number values, and this issue means there's no way to know if an exported value is a number except by parsing it (as a string) and then checking if it's numeric.
2. NULL results are exported as quoted strings of `"key": "<null>" ` instead of using JSON's native `"key": null`. I wonder if `true` and `false` do the same?
3. In exported strings, double-quotes, carriage returns, tabs and newlines are escaped... but so are forward slashes. This creates some very weird situations where a string value contains, for example, HTML, where we see things like `"<p>a paragraph<\/p>\r\n"` and need to manually find/replace out the offending slashes.

If these could be fixed, the JSON export would be really solid!

**Comment by bendoh** [comment]
# 2 is a pretty bad one. This should definitely be fixed. AFAIK there is no native SQL type for true and false, it's just TINYBIT 0 or 1 by convention.

I also experienced a situation where the JSON would simply not export at all until I restarted the program. It would prompt for a file but then when I clicked "save", the file was not created.

**Comment by hankinsoft** [comment]
Hi,
I have item 2 fixed for the next build and should be able to resolve item 1 as well. Per item 3, this is the default for json reading and writing via objective-c's NSJSONSerialization class. Also per the JSON spec, forward slashes can be optionally escaped (and in my research it seems most libraries default to escape them). So at the moment I have no plans for modifying item 3.

**Comment by hankinsoft** [comment]
I have this fixed up. Which product are you using and I can post a build.

**Comment by nomoon** [comment]
@hankinsoft I'm using SQLPro Studio on SetApp.

**Comment by bendoh** [comment]
SQLPro for MSSQL here

**Comment by hankinsoft** [comment]
Hi. The SetApp version of SQLPro has been updated with the item 1 & 2 resolved. If you get the chance, could you give it a try? I'll be pushing a MSSQL update early next week.

**Comment by nomoon** [comment]
@hankinsoft: I can confirm from the SetApp version that issues 1 & 2 are solved. Issue 3 seems also not to trouble my JSON parser after all.

**Comment by hankinsoft** [comment]
Latest App Store SQLPro for MSSQL build also includes the json export updates.
