### ISSUE TITLE
Bug: 'Alter table' feature not working - COLUMNS view is blank

### ISSUE THREAD

**Issue by Sironfoot** [hankinsoft/SQLPro#148]
SQLPro Studio version 1.0.138 (Build 1076) running on macOS High Sierra. Connecting to a MySQL database (version 5.6.22).

I can't seem to edit/alter tables, when I right click on the table in the list view on the left and select 'Alter table', I just get a blank view under COLUMNS heading...

![Image of SQLPro bug](http://dominicpettifer.com/static/images/sql-pro-bug-1.png)

This is the alter table view on the same DB table in MySQLWorkbench:

![Image of MySQLWorkbench](http://dominicpettifer.com/static/images/workbench.png)

This only seems to happen in some tables though, other tables in the retailer-api database shown seem to work just fine. However, the foreign key view looks a bit crazy:

![Image of foreign keys view in SQLPro](http://dominicpettifer.com/static/images/sql-pro-bug-2.png)

I don't have *that* many foreign keys on that table, lol, only 2.

**Comment by hankinsoft** [comment]
Hi!
What happens if you run the following query on your mysql database (replace {TABLE_NAME} with the proper table name specified). Also, what is the table name? (Just curious about special characters).

```
SELECT 
    DISTINCT
    column_name, 
    column_type, 
    column_default, 
    is_nullable, 
    COLUMN_KEY, 
    DATA_TYPE, 
    CHARACTER_MAXIMUM_LENGTH, 
    NUMERIC_PRECISION, 
    NUMERIC_SCALE, 
    COLUMN_KEY, 
    EXTRA,
    ORDINAL_POSITION
FROM 
    information_schema.columns 
WHERE 
    table_schema = DATABASE() 
    AND table_name = '{TABLE_NAME}' 
order by 
    ordinal_position ASC
```

For the foreign keys, what happens if you run the following query (again replace {TABLE_NAME} with the proper table):

```
SELECT
  i.TABLE_NAME,
  i.CONSTRAINT_TYPE,
  i.CONSTRAINT_NAME,
  k.REFERENCED_TABLE_NAME,
  k.REFERENCED_COLUMN_NAME,
  k.COLUMN_NAME,
  c.UPDATE_RULE,
  c.DELETE_RULE
FROM
  information_schema.TABLE_CONSTRAINTS i
INNER JOIN
  information_schema.KEY_COLUMN_USAGE k ON i.CONSTRAINT_NAME = k.CONSTRAINT_NAME
INNER JOIN
  information_schema. REFERENTIAL_CONSTRAINTS c ON c.CONSTRAINT_NAME = k.CONSTRAINT_NAME
WHERE i.CONSTRAINT_TYPE = 'FOREIGN KEY'
AND i.TABLE_SCHEMA = DATABASE()
AND i.TABLE_NAME = '{TABLE_NAME}
```

Could I get a screenshot of the results and/or errors from each query? Thanks!

**Comment by Sironfoot** [comment]
I've just noticed something. Alter table only fails on tables that have a hyphen in their name (e.g. "supported-api-methods"). Other non-hypenated tables work fine. When I perform a SELECT I normally have to surround the table name with backticks, e.g. ``SELECT * FROM `supported-api-methods`;`` so maybe it's a special character issue?

As for the 2 queries, the first one runs fine and returns (in CSV):

```
column_name,column_type,column_default,is_nullable,COLUMN_KEY,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE,COLUMN_KEY,EXTRA,ORDINAL_POSITION
id,int(10) unsigned,NULL,NO,PRI,int,NULL,10,0,PRI,auto_increment,1
retailerId,int(10) unsigned,NULL,NO,MUL,int,NULL,10,0,MUL,,2
apiMethodId,int(10) unsigned,NULL,NO,MUL,int,NULL,10,0,MUL,,3
dateAdded,datetime,NULL,NO,,datetime,NULL,NULL,NULL,,,4
enableTesting,tinyint(3) unsigned,1,NO,,tinyint,NULL,3,0,,,5
useProxy,tinyint(3) unsigned,1,NO,,tinyint,NULL,3,0,,,6
```

The second query returns about 18 foreign key records in both SQLPro Studio AND MySQLWorkbench. But in MySQLWorkbench, the Alter table view only shows 2 foreign key constraints are set up (in the Foreign Key tab). A bit weird!

```
TABLE_NAME,CONSTRAINT_TYPE,CONSTRAINT_NAME,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME,COLUMN_NAME,UPDATE_RULE,DELETE_RULE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_apiMethods,api-methods,id,apiMethodId,RESTRICT,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_apiMethods,api-methods,id,apiMethodId,RESTRICT,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_apiMethods,api-methods,id,apiMethodId,RESTRICT,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_retailers,retailers,id,retailerId,CASCADE,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_retailers,retailers,id,retailerId,CASCADE,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_retailers,retailers,id,retailerId,CASCADE,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_apiMethods,api-methods,id,apiMethodId,RESTRICT,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_apiMethods,api-methods,id,apiMethodId,RESTRICT,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_apiMethods,api-methods,id,apiMethodId,RESTRICT,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_retailers,retailers,id,retailerId,CASCADE,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_retailers,retailers,id,retailerId,CASCADE,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_retailers,retailers,id,retailerId,CASCADE,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_apiMethods,api-methods,id,apiMethodId,RESTRICT,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_apiMethods,api-methods,id,apiMethodId,RESTRICT,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_apiMethods,api-methods,id,apiMethodId,RESTRICT,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_retailers,retailers,id,retailerId,CASCADE,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_retailers,retailers,id,retailerId,CASCADE,CASCADE
supported-api-methods,FOREIGN KEY,fk_supportedApiMethods_retailers,retailers,id,retailerId,CASCADE,CASCADE
```

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.144.app.zip? That should sort both issues I think. Please let me know.

**Comment by Sironfoot** [comment]
Thanks!! Working now. Columns and foreign keys appear correctly. One other issue though, I can't seem to change the 'Default" value when adding a new column, it stays as NULL, regardless whether column type is int and I set a numeric value, or set a string value on a Varchar type. I *can* set the Default value for existing columns though. Shall I file this as a separate bug? The original issue is fixed though. Thanks for that.

**Comment by hankinsoft** [comment]
Thanks for letting me know! Yes, separate bug for the default issue please :)
