### ISSUE TITLE
[Bug] Host setting display inconsistency

### ISSUE THREAD

**Issue by windware** [hankinsoft/SQLPro#150]
Very trivial issue but the icon view seems to have lost the host information on MySQL entries.
Not sure if this is because I edited them on recent versions and also while the list view shows the hosts as "localhost" which is what's in the settings but without the port number and in the icon view, it's shown as 127.0.0.1 but without the SSH tunnel setting mentioned.

![list](https://user-images.githubusercontent.com/4352236/31449911-1a44a364-aee3-11e7-86be-f97ab9786c33.png)

![icon](https://user-images.githubusercontent.com/4352236/31450011-4d8bb8ac-aee3-11e7-9a0a-e5a133ffd397.png)

**Comment by hankinsoft** [comment]
Thanks, fixed for the next build.
