### ISSUE TITLE
Export and import PG Dumps

### ISSUE THREAD

**Issue by issunboshi** [hankinsoft/SQLPro#152]
Hi,

I'm relatively new Postgres and so would prefer to do somethings in a GUI. Your Postgres tool has been great so far.

However most backups of DBs I can generate e.g. from Heroku are dumps and SQLPro doesn't seem to allow this. Is there a way to get around this?

Thanks,

Cliff

**Comment by hankinsoft** [comment]
Closing this as a copy of #101. I've been working on adding export options. Postgres export support will be added soon.
