### ISSUE TITLE
SQLPro for MSSQL does not show nanoseconds properly.

### ISSUE THREAD

**Issue by nyukhalov** [hankinsoft/SQLPro#153]
SQLPro for MSSQL 1.0.191 (Build 4351) does not show nanoseconds properly.
They are always set to 0.

A screenshot is [here](https://imgur.com/TWqD0Dt)

**Comment by hankinsoft** [comment]
Thank you, this is fixed for the next build.

**Comment by hankinsoft** [comment]
FYI this has been fixed for a bit. Are you able to test the latest version and confirm you see the fix? https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.1.0.200.app.zip for website build or just update to the latest MAS version.

**Comment by nyukhalov** [comment]
Hi @hankinsoft ,

the new version [works correctly](https://imgur.com/auPwcBk), thanks for the fix (:

**Comment by hankinsoft** [comment]
Thanks for confirming!
