### ISSUE TITLE
Feature Request - Add cmd-/ shortcut for commenting/uncommenting

### ISSUE THREAD

**Issue by owenscott** [hankinsoft/SQLPro#154]
This is related to https://github.com/hankinsoft/SQLPro/issues/11 but I thought it might be worthy of its own issue.

Most text editors these days have `cmd-/` as a shortcut for automatically commenting or / uncommenting code. E.g.

![foo](https://user-images.githubusercontent.com/1028109/32496456-529020fc-c3da-11e7-901e-e2fe03a88b2a.gif)

I use MSSQL Pro mostly for rapid prototyping of queries, and so having this kind of functionality would be really helpful. I'm sure I'm not the only user who has instinctively tried `cmd-/` and was surprised that it didn't work already!

**Comment by dotob** [comment]
i think this already exists. at least in the current version

**Comment by hankinsoft** [comment]
Hi,
SQLPro uses Cmd minus for toggle/untoggle of comments. I have an open item to make shortcuts customizable. When that option is added, I'll set this as an option as well.

**Comment by hankinsoft** [comment]
(Just wanted to note that latest versions of SQLPro allow you to customize this keyboard shortcut).
