### ISSUE TITLE
Feature/Bug: Remember size of hidden results pane

### ISSUE THREAD

**Issue by longbored** [hankinsoft/SQLPro#156]
I'd love for the results pane to remember its original (re)size after it is hidden. Currently, it always takes up 2/3(?) of the vertical space, and is able to be resized - it keeps that new size, so long as the results aren't hidden. However, once those results are hidden, the size of the results pane is reset, and will return to taking up the initial 2/3 of the vertical space when displayed again. Honestly, I don't know if this should be classified as a bug, or feature request. Regardless, I'd love for this to be how it functions.

**Comment by hankinsoft** [comment]
I don't currently have a plan for implementing a saved state based on the query. If I get more requests for this I will consider it but unfortunately not for the time being.
