### ISSUE TITLE
Error when altering materialized views in PostgreSQL

### ISSUE THREAD

**Issue by machsx** [hankinsoft/SQLPro#157]
When selecting **Alter materialized view** the automated generated script contains a minor error with regard to the name of the view. The script gives errors if the name is not corrected.
E.g. for a materialized view with name `main.mvtest` the script reads:
```
DROP MATERIALIZED VIEW main;

CREATE MATERIALIZED VIEW mvtest.main AS
mvtest. SELECT ...
...
```
which is wrong. Tested in PostgreSQL

**Comment by hankinsoft** [comment]
Thank you, this will be fixed for the next build. Sorry for the delay.

**Comment by hankinsoft** [comment]
Closing. This has been fixed for awhile.
