### ISSUE TITLE
Icon is very very small when pinned to windows taskbar (SQLPro for SQLite)

### ISSUE THREAD

**Issue by GZidar** [hankinsoft/SQLPro#158]
On windows 10 machine the application icon appears like a small black dot on a light blue background. It would be ideal if the icon was bigger and perhaps did not have the blue square background at all. I realise this is a trivial issue.

**Comment by hankinsoft** [comment]
FYI I just published an update which I think will sort the issue. I'm not postive how long it takes for an update to be available via windows 10 app store. Once you see the update could you let me know if the icon looks better? If not, could you possible provide a screenshot? Thanks!

**Comment by hankinsoft** [comment]
The new version is available via the store. If you get the chance, please update and let me know if you find the icon better. Thanks!

**Comment by GZidar** [comment]
The update has fixed the issue, it looks much better now. I know it was a minor thing but thanks for taking the time to address it.
