### ISSUE TITLE
Enable Keychain access to store credentials for connections

### ISSUE THREAD

**Issue by toastytheog** [hankinsoft/SQLPro#16]
I have two types of credentials I used to connect to a mssql server, one is windows authentication, the other is mssql authentication. I am unable to save both, and I end up having to re-enter the password anytime I switch.

**Comment by hankinsoft** [comment]
Thank you for the note. I'm working on a new connection screen which should sort this out. No ETA at the moment as I still have a few things to figure out with it.

**Comment by hankinsoft** [comment]
Could you grab the latest build (http://www.macsqlclient.com/download.php) and see if this does the trick for you?

**Comment by hankinsoft** [comment]
The new connection window sorts this out.
