### ISSUE TITLE
Milliseconds not displaying for MySQL DATETIME(3)

### ISSUE THREAD

**Issue by toddhickerson** [hankinsoft/SQLPro#160]
SQLPro for MySQL 1.0.55 (build 1092)
MySQL 5.7.20

Steps to Reproduce:

DROP TABLE IF EXISTS TestTable;
CREATE TABLE TestTable (column1 DATETIME(3));
INSERT INTO TestTable (column1) SELECT NOW(3);
SELECT * FROM TestTable;

Observe results from SQLPro:
2017-12-09 18:21:47

Observe results from MySQLWorkbench:
2017-12-09 18:22:09.859

Note that SQLPro does not show the milliseconds.

You might also want to ensure DATETIME(6) shows the nanoseconds, as well.

Thank you!

**Comment by hankinsoft** [comment]
FYI this should be fixed up in all the latest builds.
