### ISSUE TITLE
Permission denied when trying to open files from a dropbox-synced folder on Mac OS

### ISSUE THREAD

**Issue by LokeSonne** [hankinsoft/SQLPro#161]
version:
SQLPro 1.0.151 (build 1089)
Mac OS 10.12.6
Dropbox 40.4.46

Issue:
Opening files in a dropbox synced folder gives error:
The document “INSERT_CompanyTag” could not be opened. You don’t have permission.
To view or change permissions, select the item in the Finder and choose File > Get Info.

My user account has read/write permissions on the file

If I restart my computer I can usually open the files. After a while i start getting the errors. The error only affects SQLPro. I can open the files with no problem in VS Code and every other application I have tried.

**Comment by hankinsoft** [comment]
Hi,
I believe this was related to https://github.com/hankinsoft/SQLPro/issues/99 which has been resolved by Apple macOS updated. If you see this issue again, please ensure you are using the latest macOS version and let me know.
