### ISSUE TITLE
ERROR: relation "..." down not exist

### ISSUE THREAD

**Issue by 242617** [hankinsoft/SQLPro#162]
When altering table with any schema, I get the error:
![2018-01-10 18 10 02](https://user-images.githubusercontent.com/1251525/34779531-895f491c-f631-11e7-902b-85a35b1faeb8.png).

When I'm editing table without any schema, everything OK.

SQLPro Studio v-1.0.154 (Build 1096). MacOSX 10.13.2.

**Comment by hankinsoft** [comment]
I’ve made a fix to the table designers in sqlpro to always specify schema when altering tables. If you get the chance, please give it a try again and let me know if you still see the issue.
