### ISSUE TITLE
[request] Connection Colours

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#163]
Hi There,

When working with a number of different connections, setting a colour on tabs is helpful to keep from confusing them. This would be stored against each connection, and then displayed along the tab. 

As an example, RoyalTSX does this quite nicely. (https://www.royalapplications.com/ts/mac/features)

Dave

**Comment by hankinsoft** [comment]
Check out https://github.com/hankinsoft/SQLPro/wiki/Tab-Colors  -- I think this will do what you are looking for?

**Comment by davidharrison92** [comment]
That'll do the trick! Thanks a lot.
