### ISSUE TITLE
Create Table - Calculated Fields / Defaults

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#164]
Hi,

When using the "Create Table" shortcut, there are differences in what SQLPro Studio (1.0.156) generates to SQL Server Mgmt. Studio.

For example, here's the line for a column out of SSMS:

`	[GPSOP]  AS ([OrderPrefix]+CONVERT([char](17),[customerID])) PERSISTED,
`

and here it is from SQLPro Studio:

`	GPSOP varchar(22) NULL
`

SSMS actually alters the table after Creation to apply Default values, where as SQLPro does it in the CREATE step. 

SQLPro: ` 	Complete tinyint NOT NULL DEFAULT ((0)), `
SSMS:  ` 	[Complete] [tinyint] NOT NULL, ` 
and then`  ALTER TABLE [dbo].[tablename] ADD  CONSTRAINT [DF_tablename]  DEFAULT ((0)) FOR [Complete] `

**Comment by hankinsoft** [comment]
This is when doing 'Script as' -> 'Create'? Or something else? I'm not
exactly sure what you are saying :)

**Comment by davidharrison92** [comment]
Yes. 

In this case, I'm trying to take the code from some exiting DB Tables and use it to create similar tables in other DBs.

**Comment by davidharrison92** [comment]
Any news here?

**Comment by hankinsoft** [comment]
I've got the calculated part fixed for the next build.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.1.0.200.app.zip?

**Comment by davidharrison92** [comment]
Thanks Kyle = that's done the trick!
