### ISSUE TITLE
(SSH) failed to call libssh2_session_handshake with error code: -5

### ISSUE THREAD

**Issue by dotob** [hankinsoft/SQLPro#165]
after the last update 1.0.156 (Build 1107) this error pops up and permits connection via ssh tunnel. 
happened on a mac with high sierra

**Comment by dotob** [comment]
hey guys what going on?

**Comment by cswilliams** [comment]
I'm also seeing this issue. When I try to tunnel through an ubuntu 16.04 server that is setup using the "modern" settings recommended here: https://infosec.mozilla.org/guidelines/openssh

I get the following error:
```(SSH) Failed to call libssh2_session_handshake with error code: -5.```

On the server I am tunneling through, I see the error:
```Jul 16 08:29:18 sshd[10957]: fatal: Unable to negotiate with xxx.xxx.xxx.xxx port 55120: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]```

 I believe this app needs to be updated to support more recent SSH ciphers.

**Comment by hankinsoft** [comment]
Just to note the app has been updated with the most recent ciphers. If you are still seeing this issue, please let me know.

**Comment by subhareng** [comment]
Still having the issue with the updated version, I have highsierra 10.13.6
<img width="1264" alt="Screen Shot 2019-04-04 at 1 15 46 PM" src="https://user-images.githubusercontent.com/9383119/55587381-1666a700-56e0-11e9-8ff7-875eafd65469.png">

**Comment by hankinsoft** [comment]
-13 looks to be a protocol issue. I think I can add some extra logging around this. It will take a few days before I have a build available with the logging.

**Comment by hankinsoft** [comment]
Hi! SQLPro for Oracle has been updated in the App Store to include extra logging around the libssh2_session_handshake issue. Could you please give the app a try and let me know the new error message? Ideally, could you please email the log file to me via kyle @ hankinsoft.com? You can find the log by going to 'view' -> 'log'.

**Comment by djErock** [comment]
I get this error when connecting to MySQL after I upgraded to 1.0.465: 

Connection Failed. Error in server handshake .... 

I first thought I had some cache somewhere causing the issue but I had my DBA team download and install and they get the error as well.

Here are some of the logs:

Application is becoming active.
2019/04/24 09:26:38:630  NSApp sendAction: collectionItemViewDoubleClick
2019/04/24 09:26:38:630  doConnect: naus-vps-mema01 (detected port: 3306 specified port: 0)
2019/04/24 09:26:38:646  HSDispatchGroup enter com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:26:38:709  mysql_library_init result: 0. Client info: 10.3.12.
2019/04/24 09:26:38:709  Using cached ip address 10.248.102.174 for host {{my host name}}
2019/04/24 09:26:38:790  Using cached ip address 10.248.102.174 for host {{my host name}}
2019/04/24 09:26:38:901  MySQLClient::disconnect settings reconnect = 0
2019/04/24 09:26:38:901  MySQLClient::disconnect begin mysql_close
2019/04/24 09:26:38:901  MySQLClient::disconnect finished mysql_close
2019/04/24 09:26:38:901  SQLProConnectingWindowController endSheetWithReturnCode: OK
2019/04/24 09:26:38:903  HSDispatchGroup leave com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:26:38:904  Failed to connect with error: Error in server handshake
2019/04/24 09:26:38:904  Clearing internal database connection details.
2019/04/24 09:26:43:917  Application is resigning activity.
2019/04/24 09:27:23:149  Application is becoming active.
2019/04/24 09:27:25:636  User wants to open logs. Path is: /Users/erik/Library/Containers/com.hankinsoft.osx.sqlprostudio/Data/Library/Logs/SQLPro Studio
2019/04/24 09:27:25:822  Application is resigning activity.
2019/04/24 09:27:31:990  Application is becoming active.
2019/04/24 09:27:32:157  NSApp sendAction: collectionItemViewDoubleClick
2019/04/24 09:27:32:158  doConnect: {{my host name}} (detected port: 3306 specified port: 0)
2019/04/24 09:27:32:168  HSDispatchGroup enter com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:27:32:214  Using cached ip address 10.248.102.174 for host {{my host name}}
2019/04/24 09:27:32:324  MySQLClient::disconnect settings reconnect = 0
2019/04/24 09:27:32:324  MySQLClient::disconnect begin mysql_close
2019/04/24 09:27:32:325  MySQLClient::disconnect finished mysql_close
2019/04/24 09:27:32:325  SQLProConnectingWindowController endSheetWithReturnCode: OK
2019/04/24 09:27:32:327  HSDispatchGroup leave com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:27:32:327  Failed to connect with error: Error in server handshake
2019/04/24 09:27:32:327  Clearing internal database connection details.
2019/04/24 09:27:34:786  Application is resigning activity.
2019/04/24 09:27:40:338  Application is becoming active.
2019/04/24 09:27:40:494  NSApp sendAction: collectionItemViewDoubleClick
2019/04/24 09:27:40:494  doConnect: {{my host name}} (detected port: 3306 specified port: 0)
2019/04/24 09:27:40:504  HSDispatchGroup enter com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:27:40:548  Using cached ip address 10.248.102.174 for host {{my host name}}
2019/04/24 09:27:40:659  MySQLClient::disconnect settings reconnect = 0
2019/04/24 09:27:40:659  MySQLClient::disconnect begin mysql_close
2019/04/24 09:27:40:659  MySQLClient::disconnect finished mysql_close
2019/04/24 09:27:40:660  SQLProConnectingWindowController endSheetWithReturnCode: OK
2019/04/24 09:27:40:665  HSDispatchGroup leave com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:27:40:665  Failed to connect with error: Error in server handshake
2019/04/24 09:27:40:665  Clearing internal database connection details.
2019/04/24 09:27:43:586  Application is resigning activity.

**Comment by djErock** [comment]
@hankinsoft ^^

**Comment by hankinsoft** [comment]
Erik, it does not look like you are using SSH? Could you please create a separate issue for this? You can grab the last version of SQLPro for MySQL at https://d3fwkemdw8spx3.cloudfront.net/mysql/SQLProMySQL.1.0.425.app.zip

**Comment by djErock** [comment]
https://github.com/hankinsoft/SQLPro/issues/241

**Comment by djErock** [comment]
@hankinsoft Can you give me a link to an older version fo SQL Pro Studio and not the MySQL specific version. My license doesn't work for it. I believe I upgraded from < 1.0.452

**Comment by hankinsoft** [comment]
Is anyone still having tunnel issues in the latest versions? The tunnel library has been replaced completely and seems to have sorted most reported issues.
