### ISSUE TITLE
User-Defined Table Type (TVP) scripts broken

### ISSUE THREAD

**Issue by jgcoding** [hankinsoft/SQLPro#168]
steps to repro:

- select a UDTT/TVP.
- choose a script from the context menu
- choose an output
- the new file, new query window, or the clip-board contain only the word "unhandled"

<img width="565" alt="udtt_tvp script broken" src="https://user-images.githubusercontent.com/1755616/35525829-a3de893a-04f3-11e8-88e4-a282d28b2a5f.png">

**Comment by hankinsoft** [comment]
Hi. As per this conversation https://sqlpro.forumbee.com/t/x1ppcd  - I believe this issue is all fixed up? Could you confirm if you get the chance? Thanks!
