### ISSUE TITLE
Feature: Right Click objects to Define

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#169]
Similar to as in the Side Bar, right click could give options to script it as a modify/create.

**Comment by hankinsoft** [comment]
Could you define this one a bit more? What do you mean by 'objects'?

**Comment by davidharrison92** [comment]
Sorry it was a little unclear. SQL Objects. Stored Procedures, Views, Tables, Functions etc..

**Comment by hankinsoft** [comment]
I think I finally understand what you mean -- your talking about right clicking in the query editor, not the database tree?

**Comment by davidharrison92** [comment]
> I think I finally understand what you mean -- your talking about right clicking in the query editor, not the database tree?

Sorry for the silence, but yes that's the idea. 

It's not a desperate need - I'm getting by just fine by selecting the object, copying it into the Sidebar filter, and going from there.

**Comment by hankinsoft** [comment]
I've had a couple requests for this - I'm going to see what I can do for the next build.

**Comment by hankinsoft** [comment]
Hi. As of https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.16.app.zip you can now right click on a table name in the query editor and perform a few actions such as:

Select first 1,000 rows
Script as -> Create, Drop & Create, Drop

Looks something like this:
<img width="1010" alt="Screen Shot 2019-09-16 at 2 18 02 PM" src="https://user-images.githubusercontent.com/3160528/64978887-eb869e80-d88c-11e9-95cc-c2cfd9fa285c.png">

Currently it only supports tables.

**Comment by davidharrison92** [comment]
Hi Kyle,
This is great! I've already found a few chances to use it, and it's been so helpful. 

One slight issue, is that it's case sensitive (even when our MS SQL Database isn't).

![Screenshot 2019-09-18 at 14 16 08](https://user-images.githubusercontent.com/3440843/65151900-e5282c00-da1e-11e9-9a77-5196749487bf.png)
![Screenshot 2019-09-18 at 14 16 17](https://user-images.githubusercontent.com/3440843/65151904-e8231c80-da1e-11e9-818c-4b973010deea.png)

**Comment by hankinsoft** [comment]
Thanks for that, I'll get this fixed up for the next build.

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.18.app.zip should sort the case specific issue. Please let me know.
