### ISSUE TITLE
Configure Default Copy Format

### ISSUE THREAD

**Issue by BradRuderman** [hankinsoft/SQLPro#17]
I am finding myself copying to excel (tab delimiter) more then CSV. It would be nice to configure the default copy to settings.

**Comment by msharp** [comment]
I would love to have better options for running a query and writing the results directly to a file. 

Copy/pasting is crude, especially with 100,000+ rows, and the header row is not included on the clipboard

**Comment by hankinsoft** [comment]
The latest version of SQLPro Studio and SQLPro for Postgres both allow you to pick the default separator and delimiter for copy from results grid. If anyone gets a chance, please give it a try and let me know if that does the trick. Preference can be set from the 'Preferences' -> 'Keyboard' tab.
