### ISSUE TITLE
Auto-complete not working when using table aliases

### ISSUE THREAD

**Issue by justingrant** [hankinsoft/SQLPro#170]
Using SQLPro for SQL Server, I'm not getting autocomplete to work for queries that use table aliases. For example: 

```
select *
from SomeTable foo
where foo.Bar is not null
```

In the query above, when I'm typing the WHERE clause, after I type _foo._, SQLPro doesn't show any autocomplete. But if I didn't use an alias, then autocomplete works fine. 

I'd expect autocomplete to work whether or not I use a table alias.

**Comment by andyoneal** [comment]
same on SQLPro for Postgres

**Comment by andyoneal** [comment]
It looks like auto-complete DOES work if you include "as". In the above example, add "as" like "from SomeTable as foo" and auto-complete works fine.

@hankinsoft PostgreSQL says [the "as" is optional](https://www.postgresql.org/docs/current/queries-select-lists.html#QUERIES-COLUMN-LABELS). Admittedly, it's safer to use "as" given the keyword issue, but I've gotten into the habit of leaving it off. Is it possible to have auto-complete work in both cases?

**Comment by hankinsoft** [comment]
Hi. Sure, I'll add this as a todo item on my list. I don't have an ETA at
the moment as I'm working on a fairly large task of exporting for each
database system but I'll take a look at it soon after that's complete.

**Comment by hankinsoft** [comment]
I've got a build available for testing. If anyone is available for testing, could you let me know which product you are using?

**Comment by hankinsoft** [comment]
<img width="1303" alt="Screen Shot 2019-04-22 at 10 02 13 AM" src="https://user-images.githubusercontent.com/3160528/56501610-c4968d00-64e5-11e9-8a98-a74ab1680fe4.png">

Just wanted to note this is available in all the latest versions. Please give it a try if you get the chance.

**Comment by textpotential** [comment]
I am using MSSQL on ipad and I can not get field level autocomplete to work with or without the AS keyword.

**Comment by hankinsoft** [comment]
Thanks, I hadn’t released the iOS updated yet. They should be available mid-week. I’ll post here once they have been updated.

**Comment by andyoneal** [comment]
new version works great! thanks!

**Comment by hankinsoft** [comment]
Thanks! Just to note, the latest SQLPro for MSSQL on iOS also now supports table alias's with any without AS.
