### ISSUE TITLE
MSSQL Multithread?

### ISSUE THREAD

**Issue by mkormendy** [hankinsoft/SQLPro#172]
Does the the SQLPro Studio have multithreaded access?

**Comment by hankinsoft** [comment]
Hi,
I’m not exactly sure what you’re asking. Yes SQLPro is multithreaded.

**Comment by mkormendy** [comment]
Well apparently, when I am querying our SQL Database with Microsoft SQL Server Management Studio,  the server shows that my account is querying the DB in threads of multiples. But with SQLPro Studio on my mac .. it's only showing the queries operate as one thread.

**Comment by hankinsoft** [comment]
Hey Mike,
What happens if you open two tabs and have both of them run

WAITFOR DELAY '00:00:60';

 You should see multiple threads if you’re using something like sp_who2.
Normally SQPPro will use a connection pool though, so if one query finishes
before another one executes you won’t see multiple threads.

Cheers,
Kyle

**Comment by mkormendy** [comment]
Well it shows two separate threads for those two separate queries. But they show up as one thread per connection. One question: does SQLPro use ODBC to make its connections to MSSQL?

**Comment by hankinsoft** [comment]
Hello,
SQLPro uses FreeTDS to make its SQL Server connections. SQLPro runs one
query at a time per connection -- each connection runs on its own thread.
I'm thinking we may be using different nomenclatures for threads?

**Comment by mkormendy** [comment]
Well I figure that certain connection protocols are allowed natively to run multithread operations based on a query. I know for certain that ODBC connections cannot initiate multithreaded operations.

**Comment by hankinsoft** [comment]
Were there any more details you wanted me to provide on this?

**Comment by mkormendy** [comment]
Sorry for the letting this go stale. I'm not sure what more to do here, so I'll close this ticket.
