### ISSUE TITLE
Minor UI: ellipsis on "Save" and "Save As" should be swapped

### ISSUE THREAD

**Issue by jaymiethomas** [hankinsoft/SQLPro#174]
The ellipsis convention is confusing on the `File` menu.

The "save" function appears on the menu as `Save...` but doesn't lead to a dialog box (unless the file is new and unsaved), and so should be `Save`.

The "save as" function appears as `Save As` but should be `Save As...`because it will always lead to a dialog box being shown.

**Comment by hankinsoft** [comment]
Thanks, I'll fix this up for the next builds.

**Comment by hankinsoft** [comment]
Thanks, I've got this fixed up for the next build.
