### ISSUE TITLE
UI Issue - Squished shortcut keys

### ISSUE THREAD

**Issue by webRat** [hankinsoft/SQLPro#178]
![squished](https://user-images.githubusercontent.com/59866/37978320-c7f7f634-31b3-11e8-96d3-aa72170836d7.png)

**Comment by hankinsoft** [comment]
Are you seeing this in any other apps, or do you have any type of system extensions turned on? SQLPro just uses the default type of menus that macOS provides and should behave as any other app.

**Comment by webRat** [comment]
Must have been a system glitch, I confirmed that it's not doing this anymore and I haven't updated anything - nor are any other apps demonstrating this behavior.

¯\_(ツ)_/¯

Closing ticket.
