### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by zhaoxy2850** [hankinsoft/SQLPro#179]
Hi guys,
I bought SQLPro yesterday, it's a wonderful software. 
I want to suggest a feature "limit results" that the SQLPro can add a query limit for me if I forgot to put the limit at the end of the SQL. Because if the table is very large then some SQLs may cause the database to stuck.
Thank you very much!

**Comment by hankinsoft** [comment]
Hello,
Thanks for the request. Unfortunately this is not something I plan on implementing. I'm not a fan of modifying queries which users are executing, as then you get into cases of results not respecting what the user entered.
