### ISSUE TITLE
Amazon Redshift Support

### ISSUE THREAD

**Issue by BradRuderman** [hankinsoft/SQLPro#18]
I am just going to start listing the bugs here when using SQLPro for Postgres with redshift:
1) The columns aren't listed when you expand the table definitions

**Comment by stevekdavis** [comment]
That's the first thing I found too.

**Comment by hankinsoft** [comment]
Should be resolved here:
https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres18a.app.zip
