### ISSUE TITLE
alter view should preserve schemanames for all involved tables (Postgres)

### ISSUE THREAD

**Issue by msageryd** [hankinsoft/SQLPro#181]
Recreate:
**1. create a view with reference to a table in another schema**

```

CREATE OR REPLACE VIEW schema1.my_view AS 
SELECT schema2.field_a
FROM schema2.table_x
```

**2. Edit this view in SQL Pro for Postgres**
This is what you get (notice the lack of schema for table_x):

```
CREATE OR REPLACE VIEW schema1.my_view AS 
SELECT schema2.field_a
FROM table_x
```

This script will probably be fine to run, because you are logged in as a user with schema search path. But in production you might have removed schema search paths from your production users as a (minimal) security measure.

**3. Include the script from step 2 in your database upgrade script**
**Boom**.. You'll get bit. I can't count the times I've been bit by this. 
Please fix this.

**Comment by hankinsoft** [comment]
Just to note this has been fixed for a while. If you get the chance, please let me know if you are still seeing this.

**Comment by hankinsoft** [comment]
Sorry, I'm wrong about that. Please ignore.

**Comment by hankinsoft** [comment]
Ok, sorry for the delay. This is fixed for the next build. It will be available either late this week or early next.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.06.06.app.zip? That should sort the issue.
