### ISSUE TITLE
alter function should preserve schema for domain types

### ISSUE THREAD

**Issue by msageryd** [hankinsoft/SQLPro#182]
Recreate:
**1. create a function with domain type from another schema in argument list**
Showing only the function interface below
```
CREATE OR REPLACE FUNCTION schema1.my_function(
  _guid uuid DEFAULT pgcryptpo.gen_random_uuid(), 
  _another_argument schema2.my_domain_type
)
```

**2. Edit this function in SQL Pro for Postgres**
This is what you get:

```
CREATE OR REPLACE FUNCTION schema1.my_function(
  _guid uuid DEFAULT gen_random_uuid(), 
  _another_argument my_domain_type
)
```

This script will probably be fine to run, because you are logged in as a user with schema search path. But in production you might have removed schema search paths from your production users as a (minimal) security measure.

**3. Include the script from step 2 in your database upgrade script**
**Boom**.. You'll get bit. I can't count the times I've been bit by this. 
Please fix this.

**Comment by hankinsoft** [comment]
Fixed for the next build. Will be available late this week, or early next.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.06.06.app.zip? That should sort the issue.
