### ISSUE TITLE
Configuration Request: Ability to turn off the prompt asking to save changes

### ISSUE THREAD

**Issue by kinnell** [hankinsoft/SQLPro#184]
I suspect you may have 2 type of users. Users that use SQLPro to write the occasional SQL code and may want to save those changes and users that use SQLPro to run queries and have no intention on using SQLPro as a text editor.

For example, I prefer to use Atom/VS Code for writing SQL because it is far superior as a text editor and allows me to manage folders and has a file tree view..etc, but will copy and paste SQL over to SQLPro when it comes to querying or executing because I prefer the SQL-dedicated interface. Therefore, there is no instances where I need to save SQL in SQLPro and would love to save time and effort declining prompts asking me if I'd to save, because I never will via a configuration option in Preferences.

I'd wager you may have other users that will find themselves using SQLPro as a means to query and troubleshoot issues on databases rather than a SQL composer and would like this option as well.

**Comment by davidharrison92** [comment]
Might a better option just be to include an extra option on the save prompt that just says "Delete All Tabs".

I tend to find myself with 10+ tabs open at the end of the day, and maybe one will be worth saving (e.g. writing Stored Proc, all the others are just testing / checking supporting data), so removing that prompt would cause me to lose the useful work if I accidentally ⌘ + Q'd.

**Comment by hankinsoft** [comment]
What I'm thinking is adding a 'Close all tabs' item to the file menu. The behaviour will be to have on prompt similar to this:

<img width="1904" alt="unsaved" src="https://user-images.githubusercontent.com/3160528/39055283-30823582-448a-11e8-9253-e89c05183406.png">

I would also alter the right click tab menu item 'Close all tabs' to use the same behaviour. Would that suite all needs?

I am against adding a preference for disabling the save prompts completely. Something like that users may forget they have turned on and accidentally close documents without saving them.

**Comment by davidharrison92** [comment]
> I would also alter the right click tab menu item 'Close all tabs' to use the same behaviour. Would that suite all needs?

Sounds good to me. Maybe a keyboard shortcut too?

**Comment by hankinsoft** [comment]
Done and done (actually already in the latest build:
https://sqlprostudio.com/download.php). Keyboard shortcut is Ctrl-Shift-W.
