### ISSUE TITLE
UI/UX Request: Search for Connections & Default To Focus

### ISSUE THREAD

**Issue by kinnell** [hankinsoft/SQLPro#185]
It would be fantastic and improve usability if there was a search for connections that would search connection aliases on the Connect menu and by default, it the focus would go there first.

I have many connections and having to scroll to find what I want is annoying, especially without the ability to "star" connections that would get prioritized at the top. Being able to open up SQLPro or click Connect and be able to quickly type the connection and select it with arrow keys and hit ENTER to connect would be a fantastic improvement on the UI/UX of one of the core functions of the app.

I would remove the Support button and replace it with this search bar. If an app was using prime real estate for a "Report a Problem / Get Help" type button, I would think either their app was really poorly designed that figuring out how to use the app was unintuitive or that it was poorly developed and needed a way for users to report a lot of bugs. Not only does the prominence of the button in the Connect screen take away from improving core functionality of the app, but it sends the wrong message to newer users.

**Comment by hankinsoft** [comment]
Search has been added for the next build. Hopefully early next week. No plans on removing the support button from the connection window.

**Comment by hankinsoft** [comment]
Just to note this has been in the last few versions. Is the feature what you were looking for?

**Comment by kinnell** [comment]
Yes! This feature has been a great addition! Thank you!
