### ISSUE TITLE
Connection DB Not Updating after "USE DBNAME"

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#187]
By default, most of my tabs open with the first DB in the sidebar, e..g "ARCHIVE1"

Normally the fastest way of changing it is to run "USE <dbname>" (e.g. "USE DEV").

Previously, this would update the DB Name in the connection picker, but it's not in the new version (1.0.165)

**Comment by hankinsoft** [comment]
Thanks, I've identified a state where this sometimes happens and have it
fixed for the next build.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.170.app.zip? That should sort it.

**Comment by davidharrison92** [comment]
Looks good to me. Not seen this for a while now.
