### ISSUE TITLE
Feature: View / Edit Database Object Permissions (SQL Server)

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#192]
Perhaps the biggest reason I'm still living with SQL Sever Management Studio (SSMS) is to add/edit permissions for Tables/Views/Procedures/Functions etc. 

I understand that this is possible using the sql `GRANT` command, but the GUI reduces errors significantly.

**Comment by hankinsoft** [comment]
Hi,
Unfortunately, at the moment I have no plans for a permission viewer. If I receive more requests to do so, I'll consider adding it.
