### ISSUE TITLE
Don't connect to sample connections when disabled

### ISSUE THREAD

**Issue by chucksense** [hankinsoft/SQLPro#193]
## Overview
To solve for #175, a feature was introduced to allow hiding the sample connections from the connection picker.  The app still tries to connect.

### Pre-requisites: 
1. Have "Disable sample connections" option enabled.  
2. Have some mechanism to monitor network connections (e.g., in router, Little Snitch, nettop, NetUse etc).

### Steps to reproduce:
1. Launch app
2. Pay attention to outgoing network connection attempts as the Connection dialog is displayed

### Expected result
Connections to the sample connections' servers **are not** attempted.

### Actual result
Connections to the sample connections' servers **are** attempted.

**Comment by hankinsoft** [comment]
Thanks, I've reproduced this. I'll fix it for an upcoming build.

**Comment by hankinsoft** [comment]
If you get the chance, could you please confirm that this is fixed in the latest build? Its been available for awhile, I however forgot to update the note.

**Comment by Bulletninja** [comment]
How do we disable/remove them?

**Comment by Bulletninja** [comment]
Found it 
![image](https://github.com/user-attachments/assets/dd5ce84f-27ca-4056-9d96-8ae44c5b83f4)
