### ISSUE TITLE
Error connecting to Oracle

### ISSUE THREAD

**Issue by ccakes** [hankinsoft/SQLPro#194]
I'm trying to connect to an Oracle DB but I get this error.
```
Failed to connect. ORA-12154: TNS:could not resolve the connect identifier specified
```

Most of the Google results are geared around keeping the connection profiles in a file and this error pointing to that file being incorrect. I'm just punching the connection details into the SQLPro GUI though and not using TNS.

Worth noting, this is my first time using an Oracle DB. Most experience is with Postgres.

The same connection details work fine using Oracle SQL Developer. Any ideas?

**Comment by hankinsoft** [comment]
Hi. Could you grab the latest version of the app (
https://sqlprostudio.com/download.php, 1.0.177 (1142)). I fixed this issue
last last week for another user (the service name was not being passed to
the connection properly), so I believe grabbing the latest copy should sort
it for you. If not, please let me know and I will investigate further.

Cheers,
Kyle

**Comment by ccakes** [comment]
Oops - should have checked for an update. That did it, cheers 👍
