### ISSUE TITLE
smalldatetime MS sql server

### ISSUE THREAD

**Issue by nickteff** [hankinsoft/SQLPro#195]
The conversion of a datetime (`YYYY-DD-MM hh:mm:ss.mmm`) to a smalldatetime (`YYYY-DD-MM hh:mm:00`) has an issue.  The conversion *displayed* is `YYYY-DD-MM hh:mm:00.000`.  For example try the following snippet.

```SQL
SELECT CAST('2007-05-08 12:35:29.123' AS smalldatetime)
```
Output is `2007-05-08 12:35:00.000` but should be `2007-05-08 12:35:00`

Running this in SSMS produces the expected result.

**Comment by hankinsoft** [comment]
Thanks, I've fixed this for a build that will be available later this week.
