### ISSUE TITLE
Database list not working 

### ISSUE THREAD

**Issue by ktemo** [hankinsoft/SQLPro#196]
After the update for 1.0.131 the list of databases stopped working, now it just says there are 0 databases. This is the SQLPro for PostgreSQL

![screen shot 2018-06-19 at 13 24 59](https://user-images.githubusercontent.com/660153/41616746-588bc444-73c4-11e8-9776-c11157795f84.png)

**Comment by hankinsoft** [comment]
Hmmm, your right I am able to reproduce this. I'll have it fixed up within
a few days. Also noticed the SQLPro for Postgres does not respect the
keyboard shortcut to bring that popup up (cmd + shift + d). I'll fix that
up too. Thanks for letting me know.

**Comment by ktemo** [comment]
thanks, I will be waiting :)

**Comment by hankinsoft** [comment]
Can you try
https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.1.0.132.app.zip?
That should sort the issue.

**Comment by ktemo** [comment]
it seems to work but I am unable to try it with more than 1 DB connection now, it says I have to restore the purchase but I click and nothing happens, although the license says is valid

**Comment by hankinsoft** [comment]
Oh crap, I see what you mean. I uploaded the build with a wrong setting.
I'll have a fixed build shortly.

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.1.0.133.app.zip
should have everything sorted. Sorry about that!

**Comment by ktemo** [comment]
It works fine now! than you!! 👍
