### ISSUE TITLE
Error connecting to Oracle

### ISSUE THREAD

**Issue by arthurire** [hankinsoft/SQLPro#197]
I'm trying to connect to an Oracle DB but I met the following error:

`Failed to connect. ORA-12154: TNS:could not resolve the connect identifier specified`

The last version that works for me is 1.0.172(1136)

I tried the latest version that you've mentioned in [Issue 194](https://github.com/hankinsoft/SQLPro/issues/194), the error still exists.

All my packages are downloaded from Setapp.

Please let me know if I could provide more details for you to investigate this issue.

**Comment by hankinsoft** [comment]
Sorry for the delay. Did you still need help with this issue?

**Comment by arthurire** [comment]
> Sorry for the delay. Did you still need help with this issue?

I found you've fixed this error in previous updates. Thank you.
