### ISSUE TITLE
Ctrl + ] : Show matching command 

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#198]
As this currently works with brackets, would it be possible to have this highlight the matching keyword?

```
IF <condition> 

...
...

END
```

The IF and END here would be the matches.

**Comment by hankinsoft** [comment]
I’m going to look into this shortly and see what I can come up with. No ETA for completion as it depends on the difficulty.

**Comment by hankinsoft** [comment]
I'm adding the Ctrl + ] support for a few keywords in the next build. It will switch between the start/end of a control statement. A quick example as shown below.

![2019-04-10 10 51 06](https://user-images.githubusercontent.com/3160528/55884647-cd4ea100-5b7e-11e9-95e9-0d26e1422ec6.gif)

This will be available hopefully late this week or early next. I'll post again once its available.

**Comment by hankinsoft** [comment]
You can also CTRL + Shift + ] to highlight the range.

**Comment by davidharrison92** [comment]
Awesome! Is this IF statements as well as CASE?

**Comment by hankinsoft** [comment]
Yes, IF and CASE statements are covered. if you have an example
procedure/function you want to send me ( kyle @ hankinsoft.com ), I can do
some double checks with it to verify all cases are covered.

**Comment by hankinsoft** [comment]
FYI, this is in all the latest versions. If you get the chance, please give it a try.
