### ISSUE TITLE
Table names containing keywords are not escaped in 'Select top 100' context menu

### ISSUE THREAD

**Issue by hankinsoft** [hankinsoft/SQLPro#20]
Example using SQLPro for Postgres.
1. create table "order"
2. choose "Select top 100 rows" in context menu for this table
   the following sql will be generated
   "SELECT \* FROM order LIMIT 100;"
3. execute it

result 

ERROR: syntax error at or near "order"
LINE 1: SELECT \* FROM order LIMIT 100;
^. (Line 1)

(see http://www.hankinsoft.com/forum/viewtopic.php?f=24&t=768 for original).

**Comment by heruan** [comment]
Same for SQL Server, e.g. for a table named `User`:
```
SELECT TOP 100 * FROM User;
```
where it should be
```
SELECT TOP 100 * FROM [User];
```
I'd also like an option to have *all* text qualified with the database delimiters (i.e. square brackets in SQL Server, back-ticks in MySQL and so on).

**Comment by hankinsoft** [comment]
I had been putting this one off due to the use of keywords generally being considered improper. I'll look at speeding it up though. I've split the secondary suggestion (an option to have all text qualified) into a separate issue #51

**Comment by heruan** [comment]
I agree, since the use of keywords is generally considered improrer having those keywords recognized and qualified for every database dialect would be an overkill and redundant.

I would stick with the *qualify all or none* option, it sounds more correct and clean.

**Comment by hankinsoft** [comment]
This was added quite some time ago.
