### ISSUE TITLE
"Disable sample connections" does not disable sample connections or remain set

### ISSUE THREAD

**Issue by unikitty37** [hankinsoft/SQLPro#201]
To reproduce: install version 1.0.133 (build 282).

- Open the preferences window and check "Disable sample connections".
- Close the preferences window.
- Quit the app.
- Relaunch the app.

Expected behaviour:

- The sample connections are no longer shown.
- On opening the preferences window, "Disable sample connections" is still checked.

Actual behaviour:

- The sample connections are still shown.
- On opening the preferences window, "Disable sample connections" has been unchecked.

(Incidentally, putting the version and build number in issue reports would be easier if the About window supported selecting them and hitting ⌘C :)

**Comment by hankinsoft** [comment]
This should be all sorted out. I also added the ability to copy the version from the about window.
