### ISSUE TITLE
Support for scram-sha-256

### ISSUE THREAD

**Issue by bkircher** [hankinsoft/SQLPro#202]
Howdy, 

I have `password_encryption = scram-sha-256` set in `postgresql.conf`. Connection with SQLPro for Postgres Version 1.0.133 (Build 282) fails with "authentication method 10 not supported"

<img width="417" alt="sql-pro" src="https://user-images.githubusercontent.com/536464/42954816-99672d7a-8b7d-11e8-8167-8a512738764a.png">

**Comment by hankinsoft** [comment]
Looks like I need to update the Postgres client to the latest version to support authentication method 10. I'm investigating doing so now.

**Comment by bkircher** [comment]
Works in latest release: Version 1.0.142 (Build 293). Thanks.
