### ISSUE TITLE
SSH tunnel fails while ip exists in known_hosts

### ISSUE THREAD

**Issue by cokeeffekt** [hankinsoft/SQLPro#203]
SSH tunnel fails public key auth when the ssh server ip is in the known_hosts file.

Removing it from the known_hosts fixes the issue, until i ssh back in and it gets added to known_hosts file again.

SQLPro Studio Version 1.0.177 (Build 1141)
macOS 10.13.6 (17G62a)

**Comment by hankinsoft** [comment]
Just to note this should be all fixed up in the latest version. If you get the chance, please give it a try and let me know if your still receiving the issue.
