### ISSUE TITLE
Trying to alter a SQLite table to add a new column crashes everytime.

### ISSUE THREAD

**Issue by daveob1964** [hankinsoft/SQLPro#204]
Working on Windows 10, opening a SQLite file, selecting a table, right-clicking alter. Clicking + to add a new column. Put in new field name and App crashes.

If I leave the field name as default it works, and I can then modify it successfully after exiting the alter dialog and re-entering.

**Comment by hankinsoft** [comment]
Thanks! I've reproduced the issue and am working on a fix. Hopefully its available mid-next week.

**Comment by hankinsoft** [comment]
The latest build was approved yesterday. That should fix this issue up. Please give it a try if you get the chance.

**Comment by daveob1964** [comment]
Thanks, I’ll have a look shortly.

**Comment by daveob1964** [comment]
Thanks, works great now.
How about a way to create a new DB on starting the app, rather than having to open an existing one?

**Comment by hankinsoft** [comment]
Sorry for the delay - just wanted to note that the latest version of SQLPro for SQLite on Windows includes a 'create new database' on the startup window, along with 'file' -> 'new' menu item which will also create a new blank database. If you have any issues or questions, please let me know.
