### ISSUE TITLE
SQLPro Studio - A few features not working with schemas(only tested with a Postgres db)

### ISSUE THREAD

**Issue by gordroid** [hankinsoft/SQLPro#205]
Hi,

I'm working with a db(a postgres db, if helps) with a lot schemas, and there are a few features that are not working. So far i've found this:

1. Indexes are not visible either in the left hand menu tree or in the alter table view. This is the only error i was able to grab `ERROR:  relation "myTable" does not exist LINE 14: WHERE  idx.indrelid = 'myTable'::regclass`, it might be a schema prefix issue.
2. Triggers are listed in both the left hand menu tree or in the alter table view, but when the trigger is expanded in the tree and is double clicked, a new tab is open but empty, so the trigger code is missing.
3. ~Import from csv is not possible(only public tables are listed)~ **Duplicated**

Please, let me know if i need to create one issue per item in my list, and i'll do it.

**Comment by superscott** [comment]
Have the same issue with Indexes with the `::regclass` error.

Here is a copy of what the creation SQL for our Indexes look like, all of the indexes are on foreign primary keys:
```
CREATE UNIQUE INDEX mes_idx_unique ON mes.mess
USING btree (a_id, se_id, e_id, sec_id);

CREATE INDEX mes_idx_div_id ON mes.mess
USING btree(div_id, a_id);

CREATE INDEX mes_idx_e_id ON messaging.messages
USING btree (e_id);
```

**Comment by hankinsoft** [comment]
Hi!
All of these issues should be sorted in the latest version. I've ensured schema is specified when details are being loaded. If you get the chance, please give it a try and let me know.

**Comment by gordroid** [comment]
Hi Kyle!

I'm on Version 2019.05.29 (Build 110486), i'm getting the same issues.

<img width="265" alt="Screen Shot 2019-06-05 at 18 01 06" src="https://user-images.githubusercontent.com/650441/58990553-8a92f900-87bc-11e9-922d-ad84114ca170.png">

Cheers!

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.06.06.app.zip? That should sort the issue.

**Comment by gordroid** [comment]
Work a treat. Thanks Kyle!

**Comment by superscott** [comment]
Confirmed, linked zip download worked for me as well.

**Comment by hankinsoft** [comment]
Thanks all. I’ll get the AppStore and Setapp versions of the app submitted
as well.
