### ISSUE TITLE
Mojave Beta

### ISSUE THREAD

**Issue by hankinsoft** [hankinsoft/SQLPro#206]
First beta is available. Currently only SQLPro for MSSQL.
Download at: https://s3.amazonaws.com/sqlprostudio/mssql/SQLProMSSQL.1.0.216.app.zip

#### Known issues

* About dialog has a few issues.
* Database tree text turns black when focus is lost (ie a dialog).
* Clicking the 'actions' button on the result set does not enable dark mode for the context menu. (If your in dark mode, this context menu is light).

#### Feedback

I'm thinking about modifying the 'theme' options within SQLPro and limiting it to only include a 'Light' and a 'Dark' theme. Themes would apply based on users OS preference. Users could still customize the individual light/dark themes, but would not be able to add other themes.

**Comment by gordroid** [comment]
Hi Kyle, the release is working great as far as i could test so far, the only thing is that at the moment it looks like support to Dark mode is not quite there:

<img width="1440" alt="screen shot 2018-10-02 at 17 12 06" src="https://user-images.githubusercontent.com/650441/46374900-4c12d080-c668-11e8-8b55-e5b8252ec957.png">
<img width="1440" alt="screen shot 2018-10-02 at 17 12 48" src="https://user-images.githubusercontent.com/650441/46374901-4c12d080-c668-11e8-8dee-710f7e27f3c3.png">
<img width="1440" alt="screen shot 2018-10-02 at 17 21 06" src="https://user-images.githubusercontent.com/650441/46374902-4cab6700-c668-11e8-9c09-071becedfe58.png">

Let me know if you need more feedback or testing my side, i'll be happy to help.

**Comment by gordroid** [comment]
Hi Kyle, the release is working great as far as i could test so far, the only thing is that at the moment it looks like support to Dark mode is not quite there(i've deleted sensible parts of the images):

<img width="1440" alt="screen shot 2018-10-02 at 17 12 06" src="https://user-images.githubusercontent.com/650441/46375350-99dc0880-c669-11e8-923d-45d35ccf9e77.png">
<img width="1440" alt="screen shot 2018-10-02 at 17 12 48" src="https://user-images.githubusercontent.com/650441/46375351-99dc0880-c669-11e8-804a-30f62facb537.png">
<img width="1440" alt="screen shot 2018-10-02 at 17 21 06" src="https://user-images.githubusercontent.com/650441/46375352-9a749f00-c669-11e8-8931-620e2b18f7fd.png">

Let me know if you will need further feedback or testing my side, totally happy to help here!
