### ISSUE TITLE
SQLPro for  PostgreSQL: displaying notices.

### ISSUE THREAD

**Issue by Alexound** [hankinsoft/SQLPro#207]
Greetings.

There is no output containing messages, when running functions containing code such as:
`RAISE NOTICE 'Notice;`

Haven't found an option to enable it, or, maybe, I'm looking in the wrong place, so I apologize in advance.
If this feature is not present, it would be great, if implemented.

**Comment by hankinsoft** [comment]
Hi,
Notices are currently not displayed within the UI. I'll take a look into adding them.

**Comment by hankinsoft** [comment]
Notices have been added for the next build and will be available early next week.

**Comment by Alexound** [comment]
Greetings!
Great news, thanks for letting me know!
