### ISSUE TITLE
macOS Mojave Dark theme issue

### ISSUE THREAD

**Issue by egantz** [hankinsoft/SQLPro#208]
Hi!

I just noticed that there's a bar that looks odd in the dark theme -
![sqlpro studio untitled 1 sql 2018-09-25 12-32-51](https://user-images.githubusercontent.com/4982233/46028787-793b0e00-c0bf-11e8-9a54-ee2c3ce37243.jpg)

Hope it'll be fixed soon, can't see nothing :)

**Comment by egantz** [comment]
I'm using Setapp and the author pushed an update with a fix claiming he accidentally pushed a wrong build to prod. all good now! closing this ticket.

**Comment by gerald-romero** [comment]
Mine is a direct download from https://www.sqlprostudio.com/ and is still broken. SQLProStudio.1.0.300.app.zip
