### ISSUE TITLE
Feature Request: Connection to Cassandra Databases

### ISSUE THREAD

**Issue by BrendanThompson** [hankinsoft/SQLPro#209]
Hi there,

I feel that it would be extremely useful if SQLPro Studio was also able to connect up to Cassandra. There are a few products out there at the moment that do it on the Mac, but nothing that's good to use.

**Comment by hankinsoft** [comment]
Hi, I generally add database support based on request feedback, so if this continues to receive more requires, I'll consider supporting Cassandra.
