### ISSUE TITLE
Mojave Release Dark mode

### ISSUE THREAD

**Issue by gordroid** [hankinsoft/SQLPro#211]
Hi Kyle, the release is working great as far as i could test so far, the only thing is that at the moment it looks like support to Dark mode is not quite there(i've deleted sensible parts of the images):

<img width="1440" alt="screen shot 2018-10-02 at 17 12 06" src="https://user-images.githubusercontent.com/650441/46375768-b75da200-c66a-11e8-8eb7-f637d39442e7.png">
<img width="1440" alt="screen shot 2018-10-02 at 17 12 48" src="https://user-images.githubusercontent.com/650441/46375769-b75da200-c66a-11e8-9727-738c0031d70a.png">
<img width="1440" alt="screen shot 2018-10-02 at 17 21 06" src="https://user-images.githubusercontent.com/650441/46375770-b75da200-c66a-11e8-98b8-a435dedb4fb0.png">

Let me know if you will need further feedback or testing my side, totally happy to help here!

**Comment by hankinsoft** [comment]
Hi! The latest build https://www.sqlprostudio.com/download.php should sort that issue!

**Comment by gordroid** [comment]
Excellent Kyle, thanks so much, unfortunatelly i bought it from the App Store, so i don't have a licence number to activate it, i need to wait for Apple's lax release times. 🙀 

Fell free to close the issue! Cheers!

**Comment by hankinsoft** [comment]
All apps have been updated with dark mode.
