### ISSUE TITLE
SQLPro Studio now has significantly longer lag now when executing/running queries (1.0.302)

### ISSUE THREAD

**Issue by kinnell** [hankinsoft/SQLPro#212]
Upgraded to version 1.0.302 and I'm now seeing significantly longer lags when executing & running queries, even on a local docker database. This use to be **significantly** faster in previous versions. It's been a while since I've seen an app go into beachball spinning mode! ![spining-weel 2018-10-03 11_56_14](https://user-images.githubusercontent.com/526343/46422984-7fef0400-c703-11e8-8e40-739be289353a.gif)
 
Here's a gif of me trying to run a quick query 3 times. The first time from menu command (Data > Run Query) and the 2nd/3rd times from my designated keyboard shortcut. Running the same query from other apps (SQLOps, VSCode) takes a fraction of the time. This is definitely a regression.

![2018-10-03 11-50-11 2018-10-03 11_51_27](https://user-images.githubusercontent.com/526343/46423053-aca31b80-c703-11e8-9655-d23f7e82cf26.gif)

**Comment by hankinsoft** [comment]
Thanks, I am investigating this.

**Comment by hankinsoft** [comment]
If you do a simple:

select "hello world";

Do you receive any lag? (Could you post a video of that)?

Also, what version of macOS are you using? Have you upgraded to Mojave, or are you running High Sierra/Other?

Thanks!

**Comment by kinnell** [comment]
Yeah, the lag exists for queries that aren't looking up data (eg. `select null` or `select 'hello world'`)

![2018-10-04 14-22-42 2018-10-04 14_24_18](https://user-images.githubusercontent.com/526343/46494590-37a61380-c7e1-11e8-9724-b2f5363cf33a.gif)

Took 3.134 seconds!

<img width="344" alt="screenshot 2018-10-04 14 24 49" src="https://user-images.githubusercontent.com/526343/46494613-44c30280-c7e1-11e8-9e1e-a67abc49a35d.png">

And my work laptop is currently on High Sierra. I upgraded my personal laptop to Mojave last night, but haven't upgraded SQLPro yet because of this lag in the latest version so I'm a bit hesitant to test if the lag exists for the same version on Mojave as well while connecting to the same servers/databases.

**Comment by hankinsoft** [comment]
"And my work laptop is currently on High Sierra" - Thats the one you're seeing the lag on right?

Also, are you using the Mac App Store version, or the website version?

Finally, one last thing I was wondering if you could check -- Would you be able to enable the sample servers from the app preferences and try the `select 'hello world'` on the sample server and see if you get the same delay? I'm thinking you will, but I just want to rule out everything else.

**Comment by kinnell** [comment]
Yep, work laptop on High Sierra with SQLPro Version (1.0.302) is where the lag is happening. And I'm currently using the website version.

And the same issue with sample connection. I tried all the database types and each type had a lag.

![2018-10-04 15-44-31 2018-10-04 15_45_36](https://user-images.githubusercontent.com/526343/46498926-c2404000-c7ec-11e8-8b0f-e89628939219.gif)

**Comment by kinnell** [comment]
I just upgraded SQLPro to 1.0.302 on my machine running Mojave and there is no lag there. Seems like a High Sierra issue.

**Comment by hankinsoft** [comment]
Could you grab 
https://www.macsqlclient.com/download.php and give it a try? On the system you are seeing the lag when running a query, could you send me the log files after running a query? You can find them by hitting 'View' -> 'Logs'. Logs can be emailed directly to kyle @ hankinsoft.com

**Comment by kinnell** [comment]
@hankinsoft Version 1.0.309 (Build 1176) has resolved the issue for me! Thank you, Kyle, as always, for prioritizing great client support!
