### ISSUE TITLE
Allow "soft tabs" when tab style configured to spaces

### ISSUE THREAD

**Issue by kinnell** [hankinsoft/SQLPro#213]
It's great that we can configure the tab style within SQLPro Studio and opt for inserting spaces instead of tabs. When tab style is configured as tabs, it seems that the behavior allows both indentation (via hard tabs aka tabs of a specific width) and alignment (via soft tabs aka tabs that vary in width up to that previous specific width that allows the cursor to get to the next "tabstop"). However, when tab style is configured to use spaces, only "hard tabs" exist. 

For example, let's say tab style is configured to "4 spaces". Currently, pressing tab will simply insert 4 spaces (aka hard tabbing which is good for indentation). However, I feel that like "tab configuration", soft tabs should also be enabled so that the expected behavior should be to insert up to 4 spaces to get to the next tab stop. Because of lack of soft tabs in spaces, it's difficult to use spaces to align things.

Many text-editors like Atom, VSCode, allow soft-tabbing when spaces are configured so this configuration would make it much easier to have a more consistent experience.

### Tab Style as Tab Behavior (Soft & Hard Tabs)
![2018-10-03 12-16-56 2018-10-03 12_32_33](https://user-images.githubusercontent.com/526343/46424921-6b613a80-c708-11e8-8048-4e10430434f7.gif)

### Tab Style as Spaces Behavior (Only Hard Tabs and No Soft Tabs)
![2018-10-03 12-19-45 2018-10-03 12_30_04](https://user-images.githubusercontent.com/526343/46424868-4bca1200-c708-11e8-8496-e091c7008807.gif)

As seen in the examples above, a hard tab is inserted if on a new line and a soft tab spaces or something) if the cursor is after some characters on the line (if tabs is configured to N spaces and the cursor is currently on the Mth spot, then add (N - (M % N)). Currently, tab style as tab width behaves as both soft & hard tabs but the spaces configuration only behaves as hard tabs which makes the tab style configuration only useful if the goal is only indentation and not also alignment.

**Comment by hankinsoft** [comment]
This makes sense. I'll look into adding it for an upcoming build.

**Comment by hankinsoft** [comment]
Going to close this. If I get additional requests for it in the future I'll take a look into re-opening it.
