### ISSUE TITLE
Database Object Search Performance

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#214]
On the current version of the app - 1.0.302 - the performance of the left-panel search field is noticeably slower, and results in the app hanging (beach balling).

For reference this is a large MS SQL Server (8 databases, thousands of objects each, Microsoft Dynamics)

**Comment by davidharrison92** [comment]
Any news on a new build here? This is becoming a real problem. It's now actually getting quicker to use other apps (SSMS, TablePlus) for most work, even though I prefer SQLPro Studio.

**Comment by hankinsoft** [comment]
Just to confirm, you are seeing slowness when you start typing in the
search bar? Would you possibly be able to perform a search, then email me
the logs? (kyle @ hankinsoft.com)? Thanks!

**Comment by davidharrison92** [comment]
Hi @hankinsoft  - sorry to be the bearer of bad news, but this search pane is crawling again.

**Comment by hankinsoft** [comment]
Could you email me the log file? kyle @ hankinsoft.com please.
