### ISSUE TITLE
Returning NULL instead of float

### ISSUE THREAD

**Issue by 242617** [hankinsoft/SQLPro#215]
I've float numbers returning as NULL.

Example:
```select 0.1 as result from dual```

Other apps returns _0.1_ but SQLPro Studio returns _NULL_.
Version 1.0.309 (Build 1176).

**Comment by hankinsoft** [comment]
Hmmm, I'm not able to reproduce this connecting to an Oracle 12c db. What version oracle database are you connecting to?
<img width="1162" alt="screen shot 2018-10-15 at 9 13 24 am" src="https://user-images.githubusercontent.com/3160528/46950344-c5dc8e00-d05a-11e8-890f-e82b065d7e2f.png">

**Comment by 242617** [comment]
Hm...
Oracle Database 11g Enterprise Edition 11.2.0.4.0 - 64bit Production.

**Comment by hankinsoft** [comment]
Ok. I'm going to add a bit of extra logging around handing numbers and post a new version to get some additional logging. Are you using SQLPro from the App Store, our Website, or Setapp?

**Comment by 242617** [comment]
Thank you. I download app from your website.

**Comment by hankinsoft** [comment]
FYI, the latest version of the app contains the extra logging I mentioned. if you get the chance, please give it a try and see if you can reproduce. Please send the log files (available from 'View' -> 'Logs') to kyle @ hankinsoft.com.
