### ISSUE TITLE
[Bug] Favorite Query cannot be renamed

### ISSUE THREAD

**Issue by rayl-brbio** [hankinsoft/SQLPro#216]
![image](https://user-images.githubusercontent.com/35660781/47277219-736a1700-d5f0-11e8-981f-4db97b0a2630.png)
the name of the query cannot be renamed anyhow

**Comment by hankinsoft** [comment]
Hi!
You need to use the highlighted box for renaming favourites. Please give that a try and let me know if it sorts the issue you are seeing.

![47277219-736a1700-d5f0-11e8-981f-4db97b0a2630](https://user-images.githubusercontent.com/3160528/47565242-38bcf300-d8fe-11e8-9eb5-acd73fba4e3a.png)
