### ISSUE TITLE
Find + Replace: ⌘ + ⇧ + F

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#217]
Would it be possible to have the Find + Replace bars both appear when this key combination is pressed (commonly used elsewhere in mac apps).

Currently its necessary to click the "Replace" checkbox.

Thanks!
Dave

**Comment by hankinsoft** [comment]
Hey Dave,
The default macOS find/replace shortcut is actually `⌘ + ⌥ + F` rather than `⌘ + ⇧ + F`. The default shortcut should be working within SQLPro (just gave it a try to verify). Could you give this a try and see?

**Comment by davidharrison92** [comment]
Ah brilliant. Thanks for that.
