### ISSUE TITLE
Windows Perpetual Pricing?

### ISSUE THREAD

**Issue by tfreedman** [hankinsoft/SQLPro#219]
I just installed SQLPro Studio (and the Postgres version) on Windows, and was disappointed to find out that the pricing information is totally unclear for both products. The Mac version appears to have a perpetual license for $125CAD (which is totally fine), and the wiki page here (https://github.com/hankinsoft/SQLPro/wiki/License) confirms that.

However, on the Windows side, things are way less clear. After installing it and running a query, I'm told I need to activate it to view results, with a "free" 1-week trial. Except the "free" trial wants a credit card, so it can charge me monthly. Considering how ambiguous everything has been up to this point (including the lack of any pricing info or comparison for the other, lesser Windows versions) , there's no way I'd  sign up.

![license](https://user-images.githubusercontent.com/850412/48343877-92812500-e641-11e8-80d3-76a4b298e8ae.png)

Considering that dialog boxes like that get other companies to the top of [/r/assholedesign](https://www.reddit.com/r/assholedesign/comments/9uips5/microsoft_email_tries_to_mask_a_1_week_free_trial/), I'd strongly suggest adding a perpetual license version, or, if you intentionally only want to make this a subscription product, communicate how much this actually costs before I spend a bunch of time configuring various databases, and revise the Windows pages (https://www.sqlprostudio.com/windows.html) to not have things like Mac-only buy buttons (I have to assume that buy button is only for the Mac version, because there's zero place in the Windows version to get a license or activate with a key).

**Comment by hankinsoft** [comment]
Hi. Unfortunately the displayed dialog is part of the Microsoft App Store and i’m unable to customize it in anyway. I will however add some information to the App Store description stating that results are unavailable without a subscription.
