### ISSUE TITLE
Better support for escaping keywords

### ISSUE THREAD

**Issue by hankinsoft** [hankinsoft/SQLPro#22]
In SQLPro for Postgres, keywords should be escaped in table names (specifically for the 'SELECT top 100' context menu and autocomplete, but there may be more locations).

**Comment by heruan** [comment]
Not only for Postrgres, but also for SQL Server (and maybe all platforms).

Is this a duplicate of https://github.com/hankinsoft/SQLPro/issues/20? They're both pretty old, any update since they were issued?

**Comment by hankinsoft** [comment]
Closing due to duplicate. I'll update a response on the other entry :)
