### ISSUE TITLE
[SECURITY] Queries can still be run on disconnected password-protected databases

### ISSUE THREAD

**Issue by skylarmb** [hankinsoft/SQLPro#220]
Product: SQLPro for Postgres

STR:
1. Set up a database. Do not check the "remember password" box.
2. Connect to database using the password. Do not check the "remember password" box.
3. Run a query on a that database.
4. Right click the database in sidebar  -> Disconnect.
5. Run the query again in your open tab.
6. The query still works even though the DB is disconnected and should be password protected, since the "remember password" box is NOT checked. Authentication should be lost at step 4 but apparently persists until the application is killed. 

This is a fairly big security flaw. Any past database that I have connected to in the past using a password (and the "remember password" box is NOT checked) remains accessible until I quit the application.

**Comment by hankinsoft** [comment]
Thanks, fixed for the next build.
