### ISSUE TITLE
Don't ask to save every query

### ISSUE THREAD

**Issue by powelski** [hankinsoft/SQLPro#221]
Currently, if we edit the default query generated by SQLPro, it will ask if we want to save it. I think this is very troublesome, because we really don't want to save a query that often. It would be nice to either have an option to disable asking, or to improve an algorithm and ask only if the query has been edited certain way. For example, I don't think many people want to save the query with just removed `LIMIT` clause. This, along with opening new tab for every SQL table viewed, makes for time consuming experience, where we need to answer `Delete` to every question if we want to save the query.

EDIT

I think there is some bug, because sometimes the dialog never appears in the newest version, and sometimes it appears every time I edit the query any way (like deleting the semicolon).

**Comment by skylarmb** [comment]
I would also love to see this. At least the option to turn off asking to save or control when it shows. For example, it makes more sense to ask to save if the query was opened from a file on disk than if it was written from scratch in the editor.

I probably only save 1 in 100 queries I write from scratch, so this dialog gets annoying quickly.

**Comment by hankinsoft** [comment]
Would a secondary keyboard shortcut do the trick for this? For example if cmd-shift-w was pressed the tab would be closed without a prompt to save?

**Comment by powelski** [comment]
I think that saving a query is such an exotic need that it would be an overhead to use 3 keys to close tabs, especially that SQLPro is quite aggressive with opening separate tabs for each table.

**Comment by skylarmb** [comment]
Agreed that personally the default cmd+w behavior I would prefer would be do not prompt, however I understand different people have different needs and use cases. Thats why I suggested simply adding the ability to turn off prompting as a setting and have the default behavior be the current behavior (prompt).

**Comment by powelski** [comment]
The option seems to be the best compromise. I think not too many people will use the prompt. If you want to save a query, it’s probably rather long one and the chances you forget to save it is not too big of you just spent some time writing it. I understand the thinking pattern behind current behavior, but I think that SQL queries are different than regular files on many levels.

**Comment by jaymiethomas** [comment]
@hankinsoft Not worthy of creating a separate issue this, but also on that prompt for unsaved changes, using "Delete..." as the wording on the button is a bit terrifying, as you're in a data manipulation environment.

Could this be "Don't save" instead?  (It doesn't need the eliipsis, as it isn't presenting a subsequent window).

**Comment by hankinsoft** [comment]
FYI, I changed the "Delete" text to "Don't save" a few releases ago. I haven't made a firm decision on changing the prompts for this.

**Comment by MDooley47** [comment]
I came here to ask for the same improvement. Just adding a checkbox in the preferences to turn on and off "Ask to save on exit." would be hugely beneficial.

**Comment by hankinsoft** [comment]
I've been doing some work in this area and I'm going to post updates on #63. Going to close this item as a duplicate.
