### ISSUE TITLE
Window Size issue on Start

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#224]
When re-launching, the window is often too large for the window. Most typically, when disconnecting a monitor. Occasionally too big (wide) for external (apple thunderbolt) display.

Then window can't be re-sized either using the click + drag arrows (will only allow it to stretch, but not shrink) or third party tools (I use SizeUp).

Version 1.0.320 (Build 110320)
macOS Mojave 10.14.1 (18B75) / MacBook Pro (Retina, 15-inch, Mid 2015)

<img width="1440" alt="screenshot 2018-12-14 at 09 06 39" src="https://user-images.githubusercontent.com/3440843/49994011-3c750980-ff80-11e8-92c2-1c0650caf3fe.png">

**Comment by hankinsoft** [comment]
Hi! The resize issue is fixed in the latest build. I’ll have to investigate
the startup size issue though.

**Comment by hankinsoft** [comment]
Just to confirm this is all fixed in the latest build. If you get the chance could you verify?

**Comment by davidharrison92** [comment]
Kyle, not had this for a while now.

Thanks a lot.

**Comment by davidharrison92** [comment]
Hi Kyle - sorry to bring bad news, but this has reoccurred.

Version 2019.09.16 (Build 110540)

**Comment by hankinsoft** [comment]
Thanks Dave - just to check, do you mean the window is to large on launch, or you cannot resize? (Or both)?

**Comment by davidharrison92** [comment]
![Screenshot 2019-10-10 at 11 04 57](https://user-images.githubusercontent.com/3440843/66559956-43dc5380-eb4e-11e9-992c-f97a8b9d9074.png)

Regardless of what size the main window is, the connect window always fills 100% of the width of the monitor.

**Comment by hankinsoft** [comment]
Just to check, are you able to resize that window manually? (Secondary question, what OS version are you using)?

**Comment by davidharrison92** [comment]
Kyle,

Both the main and the connections window can be resized with the mouse. 

macOS Mojave / 10.14.6 (18G103)

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.45.app.zip? I think that will sort the issue out. Please let me know if not.
