### ISSUE TITLE
SQLPro for SQLite doesn't refresh data correctly on Windows

### ISSUE THREAD

**Issue by ocdtrekkie** [hankinsoft/SQLPro#225]
I was writing an app using SQLite, and intended to use SQLPro for SQLite to check my work. Sure enough, my prepared statements didn't work originally, and so things like `@FieldName` were in the data when viewed in SQLPro. I tried tons of solutions for my code, and no matter what, the output seemed to show the `@FieldName` in SQLPro, even though each time I deleted the SQLite file completely, and closed both my application and SQLPro.

What really confused me, was I changed the `@FieldName` to `@Name` in my prepared statements... and it was still dropping "`@FieldName`" into the database, which was impossible, my code didn't have that string in it at all anymore!

I tried changing the filename of the SQLite database... and my code was working fine. I changed the filename back to the original, and SQLPro is showing the invalid data. Even if I "Reload" in SQLPro, it shows data from a version of the SQLite file that doesn't even exist anymore. I even opened up the file that shows `@FieldName` instead of the data in a text editor, and can see the real data, but SQLPro cannot.

**Comment by ocdtrekkie** [comment]
So I took a file that was showing the invalid `@FieldName` entries in SQLPro, literally renamed it and reopened it in SQLPro, and the correct data displays. Rename it back to the original filename, and SQLPro returns to displaying the invalid data. Which is to say it's very clear SQLPro is for some reason caching the contents of a database it opens at a given filename, and then refusing to actually ever look at what the current data at that filename contains thereafter.

**Comment by hankinsoft** [comment]
Hey Jacob,
Could you post a screenshot with what your seeing? The mention of prepared
statements is confusing me as SQLPro does not allow you to interact with
prepared statements, so I’m not sure exactly what you are seeing being
cached. A screenshot should help.

Cheers,
Kyle

**Comment by ocdtrekkie** [comment]
Sorry, prepared statements has nothing to do with the problem, I was just explaining the history of my issue. Let me simplify:

- My app created an SQLite database with bad data, which I looked at in SQLPro.
- I closed SQLPro, deleted the SQLite database entirely, and fixed my code.
- My app created a new SQLite database with good data, at the same filename.
- SQLPro still shows the bad data from the original database when I open the file.

Since SQLPro shows the correct data if I rename the file to some other filename before opening it, and I can also see the correct data if I open the database file with some other application, the issue appears to be that SQLPro has cached the original data somehow.

**Comment by hankinsoft** [comment]
Hmmm ok. Thank you for the clarification, that will help me out. I’ll do
some investigating and see what I can find.

**Comment by wvdvegt** [comment]
Any update on this issue? I keep seeing only 8 records from a database (clearly cached somewhere).

**Comment by hankinsoft** [comment]
Unfortunately not yet. Just to confirm, you are using windows as well?

**Comment by wvdvegt** [comment]
Yes, Windows.

Strangely enough does the SQLite/SQL Server Compact Toolbox (a VS addon) update correctly.

I did some searching with SysInternals ProcMon and found that there are copies of the SQLite files inside a folder:

C:\Users\<>\AppData\Local\Packages\HankinsoftDevelopmentInc.SQLProforSQLite_z7k90xbbeqz64\LocalCache\Roaming\P1_Telegram

The path will differ a bit on other machines. Removing the files there immediately let me open and see al records in a sqlite3 file. At the same time a new copy appeared in above folder.  It could be that if you open a file, the SQLite code makes a copy to this location (it seems the UWP app storage).

Another thing is that the close button (top right of the window) doesn’t seem to work. I need to use File|Close to close the application.

**Comment by hankinsoft** [comment]
Hmmm, thanks for that. Just trying to reproduce, but I'm not having any luck so far. A few questions:

1. How are you opening the file? IE, is it in the 'recent files' list, are you double clicking the sqlite file from explorer, are you using file -> open?

2. What version of Windows are you using? (Specifically Edition, Version and OS build if you could).

For the close button, do the minimize and maximize buttons work? Thanks!

**Comment by wvdvegt** [comment]
Hi

It does not seem to matter how I open a file. 

I think the copying is not done by you in code but under-the-hood by the SQLite lib.

Using a fully patched Win10 Enterprise Edition (but till without the just released may 2019 update).

The Ver command returns: 'Microsoft Windows [Version 10.0.17763.529]'

The minimize button does not work and turns the mouse into a resize cursor. The maximize seem to work. Double clicking the system menu on the left side closes the app without issues.

I think what to do is just delete the copies when you close a database or exit the app. Question however is which managed folder contains these copies (you need one with 'LocalCache' in the path).

https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.ApplicationData

ApplicationData.Current seems to contain a number of cache folders. My suggestion would be to debug and check which of those matches the folder I posted/mailed earlier.

Then only delete files opened from a ‘normal' folder if they are also present in the cache folder (and maybe some other precautions if necessary). Bit dirty solution but not being able to view the files is worse.

**Comment by ocdtrekkie** [comment]
Just popping in to say I really appreciate someone else providing help to solve this issue, @wvdvegt!

**Comment by wvdvegt** [comment]
Thx, just like to debug and help solving issues/bugs. 
This issue renders this very nice tool pretty useless (just bought it).

I was able to delete the files manually after the SQLPro was closed (so that is already a workaround as is).
The folder i mentioned will not be hard to find in explorer.

**Comment by wvdvegt** [comment]
Just noticed that when i open a database from another UWP app (so located in a managed folder as well), no copy is made.

**Comment by wvdvegt** [comment]
And closer inspection: A copy of all non-managed files (those outside the local\packages folders) is made when the file list dialog is shown at startup.

**Comment by hankinsoft** [comment]
Would either of you be willing to try a non-app store version of this app? It would be a regular installer/uninstaller. I'm trying to narrow down if its specifically due to the App Store wrapping (SQLPro is a WPF app and uses the [desktop bridge](https://docs.microsoft.com/en-ca/windows/msix/desktop/desktop-to-uwp-root) to run via the App Store, which I think might be the root cause, but this will help me confirm).

**Comment by wvdvegt** [comment]
Hi
Off-course! Happy to do some further testing.

**Comment by ocdtrekkie** [comment]
I have very limited free time right now, but if you aren't able to get what you need from @wvdvegt I can try to find a little time to play around.

**Comment by hankinsoft** [comment]
@wvdvegt can you try: http://sqlitepro.com/downloadWindows.php? Thats a Windows installer that will install SQLPro for SQLite. Please uninstall the version from the windows App Store first. I'm looking to confirm that the direct file gets modified now and you no longer have the refresh issue.

**Comment by wvdvegt** [comment]
Hi

This version seems to work just fine.
I tested with both a managed file and an unmanaged file. Data reload database updates the number of records nicely.

So it seems like the store version takes a snapshot of the database into the cache folder and never updates or removes this snapshop.

**Comment by hankinsoft** [comment]
Thank you for letting me know! I will add code to clear the cache on
startup for the windows store version. One more thing if you get the
chance? Does the close button work in that installer version?

**Comment by hankinsoft** [comment]
Just to note, I've rebuilt the software using a much newer version of windows bridge packaging. I've never been able to reproduce this, so if anyone runs into this again, please let me know.
