### ISSUE TITLE
Autocomplete issue previously fixed now recurring

### ISSUE THREAD

**Issue by h4ns3n** [hankinsoft/SQLPro#226]
I have submitted an issue regarding autocomplete functionality in the past (via email) and have received great support. In the latest build it seems that all the previous issues that were rectified have now returned. Perhaps your latest build excludes branches from adhoc fixes or those branches were never merged... or something. 

Version 1.0.320 (Build 110320)

1. I had previously raised an issue around autocomplete not working when the case of a table name requires that table name to be wrapped in quotes. Autocomplete works for tables names in lower case. Your response to the initial fix was that quotes were excluded in your code and after including them, autocomplete worked fine. 

```
select * from schema.table1 as a
where a.
```
the alias a. will return autocomplete column names

```
select * from schema."Table1" as a
where a.
```

The alias a will not return autocomplete column names.

**Comment by hankinsoft** [comment]
Hi, looks like this one is a similar but different issue. Quotes by themselves still work, however specifying schema name, then quotes does not currently work. I'm investigating this now.

**Comment by hankinsoft** [comment]
Are you using SQLPro Studio, or SQLPro for Postgres?

**Comment by h4ns3n** [comment]
I’m uding SQLPro Studio

Paul Hansen
0741115748

**Comment by h4ns3n** [comment]
Resolved with the update provided for issue https://github.com/hankinsoft/SQLPro/issues/227
