### ISSUE TITLE
Functions created with specified schema names not displaying on SQLPro

### ISSUE THREAD

**Issue by h4ns3n** [hankinsoft/SQLPro#227]
SQLPro Studio (Version 1.0.320 (Build 110320)
Postgres on premise DB connection

When a function is created under a specified schema name, that function does not appear in the function list drop down. I'm not sure exactly what the conditions are for those functions that do display. 

This is similar to an email issue I had raised, but these were occurring for views.  That email came from paul.hansen@???.co.za on October 10 2018

**Comment by hankinsoft** [comment]
If you run this query:

SELECT 
    n.nspname,
    p.proname, 
    pg_catalog.pg_get_function_identity_arguments(p.oid)
FROM 
    pg_catalog.pg_namespace n 
    JOIN pg_catalog.pg_proc p ON p.pronamespace = n.oid 
WHERE 
    n.nspname NOT IN (
        'pg_catalog', 'information_schema'
    )
AND n.nspname = ANY(current_schemas(false))
ORDER BY n.nspname,
	p.proname

Do you see the functions you are looking for?

**Comment by hankinsoft** [comment]
Nevermind. I've fixed this for the next build.

**Comment by hankinsoft** [comment]
I'm aiming for late this week.

**Comment by hankinsoft** [comment]
Can you grab https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.325.app.zip and give it a try please?

**Comment by h4ns3n** [comment]
> Can you grab https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.325.app.zip and give it a try please?

Apologies for the long delay, I have completed testing on this build and I now see all all functions regardless of schema. 

Thank you for you quick resolution, as always!
