### ISSUE TITLE
Mac: enter + exit fullscreen - then can't resize smaller

### ISSUE THREAD

**Issue by ajoslin103** [hankinsoft/SQLPro#228]
On a Mac - latest everything - SqlProPostgres vers. 1.0.315 

Once you enter + exit fullscreen (from the view menu) then you can't resize the window smaller, only larger

**Comment by hankinsoft** [comment]
Thanks, I have a fix for this which I will make available later this week. A quick solution is to collapse then expand the database tree. After that you should be able to resize.
