### ISSUE TITLE
mysql returns hex value when using from_base64() function

### ISSUE THREAD

**Issue by newbieh4cker** [hankinsoft/SQLPro#229]
![image](https://user-images.githubusercontent.com/23703741/51150948-122ea880-18ac-11e9-9d1b-3971af8478a7.png)

When I use other client(such as sequel pro) or type into mysql console directory, function returns plain text. How can I fix it?

**Comment by newbieh4cker** [comment]
when next build will be available???

**Comment by hankinsoft** [comment]
Sorry, I forgot to post and update. The build has been available for awhile - if you get the chance, please try in the latest version.
