### ISSUE TITLE
Table data filtering UI glitch

### ISSUE THREAD

**Issue by michalzelinka** [hankinsoft/SQLPro#230]
Rendering of the filtering elements often fails as these elements don't even appear in the expected area expanded after the Filter button press.

macOS Mojave 10.14.2 @ MacBook Air 2012
App version 1.0.315 (Build 3105)

![screen recording 2019-01-15 at 10 05 03](https://user-images.githubusercontent.com/5228484/51170190-18be1f80-18ae-11e9-821f-cbaf725679a7.gif)

**Comment by Wings994** [comment]
This issue still exists on 1.0.440.

**Comment by hankinsoft** [comment]
I've not been able to reproduce this issue and I'm not sure why. Are you seeing this on all tables? If you switch away from the selected table and switch back, does the filter show up? If you open the sample Sakila database do you still see this same issue?

**Comment by michalzelinka** [comment]
I'm able to reproduce it quite reliably, right after opening the app; even with a sample DB.

Switching to another table and back seems to be the way to make the filter bar content visible. Possibly same layout issue?

https://www.dropbox.com/s/47vxh9g82t8vp6m/sqlpro_filter_bug.mov?dl=0

**Comment by Wings994** [comment]
I'm seeing the same thing as michalzelinka. So switching tables and switching back makes the filters show up.

**Comment by hankinsoft** [comment]
Could either of you give https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.1.0.454.app.zip a try? If that sorts the issue for you, I will also upload it to the App Store.

**Comment by michalzelinka** [comment]
Fixed on my machine. 👍

**Comment by hankinsoft** [comment]
Great! Posting the update to the App Store now. It should be available generally within a couple of days. I'll close the issue once that version is online.
