### ISSUE TITLE
Can't update int column (because it's quoted ?)

### ISSUE THREAD

**Issue by m-thomson** [hankinsoft/SQLPro#231]
I'm trying to do a simple update of an int column which is failing. Looking at the error message it appears the field in question is being surrounded by single quotes, perhaps that's why?

<img width="957" alt="screenshot_c3bead" src="https://user-images.githubusercontent.com/5273016/52167754-f28de180-26ed-11e9-999b-ba81c30d3b5a.png">

I noticed that this error didn't happen on *all* int fields, just the ones that have triggers so I think that may be a clue. Here is the trigger I'm using:

```
CREATE TRIGGER cidUpdate
  BEFORE UPDATE ON stream
  FOR EACH ROW
  BEGIN
    SET new.changes = new.cidHi - new.cidLo + 1;
  END;
```

And the full schema:
<img width="753" alt="screenshot_e3166a" src="https://user-images.githubusercontent.com/5273016/52167789-ad1de400-26ee-11e9-9bdd-bb151d5cdf15.png">

A couple asides:

Is there anywhere to see a log of the queries the App performs? I couldn't find it, and the mysql general_log feature doesn't seem to log failed queries.

You really ought to close all the Github issues that you've resolved. It was a pain browsing through them to see if this has come up before.

Thanks.

PS: I'm using Version 1.0.403 (Build 110403.5)

**Comment by hankinsoft** [comment]
This was fixed in a recent build. If you get the chance, please give the latest update a try and let me know.
