### ISSUE TITLE
Format option to capitalize SQL syntax verbs and keywords

### ISSUE THREAD

**Issue by davidfilat** [hankinsoft/SQLPro#232]
I've come to love SQLPro Studio and I mostly use it for my job, but one thing I miss from other MySQL GUIs is the way they use to beautify code. The SQLPro Studio 'Format' option mostly works the same, but one thing it lacks is to automatically capitalize the SQL syntax keywords. 

Here is how SQLPro Studio formated a snippet:
![image](https://user-images.githubusercontent.com/1475163/52444108-232bac00-2b30-11e9-8a0a-f3c377fb5ebd.png)

And here is how TablePlus beautified the same snippet:
![image](https://user-images.githubusercontent.com/1475163/52444062-ff686600-2b2f-11e9-93b7-92690e7f62c0.png)

I think it would be awesome if you could add the same to SQLPro format option.

Thank you for your great work!

**Comment by hankinsoft** [comment]
Sure, that's pretty easy. I think it would probably make sense to uppercase
functions (such as COUNT) as well.

**Comment by davidfilat** [comment]
Hi,
I see the feature was added in the last release. Thank you very much!
But there are still some problems:
1. The function names are not capitalized.
2. Table names are capitalized in the WHERE clause, thus invalidating the query.
Here are two screenshots of a query before and after Format was applied:
![image](https://user-images.githubusercontent.com/1475163/52531781-6ef27700-2d23-11e9-9dfe-2dd1dce4cff1.png)

![image](https://user-images.githubusercontent.com/1475163/52531784-7ade3900-2d23-11e9-871f-0873b6923b14.png)

**Comment by hankinsoft** [comment]
Thanks David! I actually didn’t mean to release that yet :) I forgot I had
it part done when I when I released a crash fix for someone else. You must
be using setapp? One quick question based on your screenshot — are you
connecting to a postgres database? Or other? Thanks!

**Comment by davidfilat** [comment]
Sorry for such a late reply! I see, it happens to me too way more often than it should! 😆 
Yes, I'm using the Setapp version and the screenshots are from a MySQL (MariaDB) connection.
Hope it will be helpful for you! 
May God bless you!

**Comment by hankinsoft** [comment]
Hi! I've added this in a testing build (available here: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.34.app.zip). If you get the chance, please give it a try and let me know if this is what you were looking for.

You can change the formatting settings by opening `Preferences`, then going to the formatter tab. You can change keywords, functions and tables/columns. The options available are:

- **No action**: the word does not get modified.
- **Uppercase**: the word gets uppercased.
- **Lowercase**: the word gets lowercased.
- **Match database**: the word matches what was found in the database.

<img width="552" alt="Screen Shot 2019-10-04 at 3 53 30 PM" src="https://user-images.githubusercontent.com/3160528/66232424-2d9e4580-e6bf-11e9-8d18-7d7031f9e164.png">
