### ISSUE TITLE
Failed to perform update SQL Server?

### ISSUE THREAD

**Issue by DevZ1** [hankinsoft/SQLPro#233]
Hi,

every time i want to update a field i get the following error? The app is really useless like this if i can not alter any data :-( Can you help please, whats going on? I use version Version 1.0.408 (Build 110408)

Msg 1934, Level 16, State 1.
UPDATE failed because the following SET options have incorrect settings: 'QUOTED_IDENTIFIER'. Verify that SET options are correct for use with indexed views and/or indexes on computed columns and/or filtered indexes and/or query notifications and/or XML data type methods and/or spatial index operations.

**Comment by hankinsoft** [comment]
Hi,
I'm investigating this issue. What version is your SQL Server? (Seen in the
database tree)? Thanks!

**Comment by yaboisandeep** [comment]
you can solve it as:
SET QUOTED_IDENTIFIER OFF
ALTER STATEMENT
SET QUOTED_IDENTIFIER ON

**Comment by DevZ1** [comment]
Hi,

thank you for your reply.
I don't want to write my update in SQL Statements. I want to query my table
and edit the values inplace in the table layout.
Then executing Set quoted_identifier OFF doesnt have any use at all. It
still shows me the same error :-(

Best Regards

**Comment by DevZ1** [comment]
Also the whole app crashes when i do SET QUOTED_IDENTIFIER OFF

**Comment by DevZ1** [comment]
Editing this table in MS SQL Management Studio is btw no problem at all.

**Comment by hankinsoft** [comment]
Hi, could you please post the sql server version your connecting to? That should help me figure out the issue.

**Comment by DevZ1** [comment]
Hi Kyle,

version is 14.00.2002
CLR Version v4.0.30319
SQL Server 2017

Thank you.

**Comment by hankinsoft** [comment]
Hi, I've been trying to reproduce this option but so far no luck. Are you trying to update the results of a view or table? Would it be possible for you to send me the table/view definition and possible an export a portion of the object as CSV? You can email me directly via kyle@hankinsoft.com.

**Comment by hankinsoft** [comment]
Also are you using SQLPro Studio or SQLPro for MSSQL - I made a chance to detect if quoted identifier is required or not which should fix the issue regardless but if you could still provide the above information that would be very helpful.

**Comment by hankinsoft** [comment]
If you are using SQLPro Studio, the latest version: http://sqlprostudio.com/download.php should sort this for you.
