### ISSUE TITLE
Fill in values with Script as > INSERT

### ISSUE THREAD

**Issue by heruan** [hankinsoft/SQLPro#234]
Using `Script as > INSERT` doesn't fill in the values (at least for Postgres), e.g. it generates

```sql
INSERT INTO my_table (my_column) VALUES(/* user required */)
```

It would be useful to have the values part, to be able to export/import data between databases.

**Comment by hankinsoft** [comment]
Hi,
If you run the results from a query (select * from x) you can do a ‘select
all’ followed by right click, ‘copy as’ -> ‘insert’ from the result set.
That will include all the values. Please let me know if that helps!

**Comment by heruan** [comment]
Yeah, that helps a lot!
