### ISSUE TITLE
Autocomplete not working consistently (with or without aliases)

### ISSUE THREAD

**Issue by h4ns3n** [hankinsoft/SQLPro#235]
Version 1.0.409 (Build 110409)
Postgres DB

After updating to the latest build, SQLPro autocomplete has stopped working for certain tables. All tables are picked up when entering the schema name, but once autocomplete is invoked for the selected table, no column names are returned. It does work for certain tables, but I cannot see the reason for it working for some and not for others. The issue is not case sensitivity.

The previous version of SQLPro had no such issues.

The logs shows the following:

2019/02/15 11:19:50:236  completionsForPartialWordRange partial keyword is: kh.Add
2019/02/15 11:19:50:236  getCompletions has 1 results. (Removed 0).
2019/02/15 11:19:50:236  updateCompletion called with partial word (Add).
2019/02/15 11:19:50:236  NSApp sendAction: tableViewSelectionDidChange.navigateAction
2019/02/15 11:19:50:236  navigateCompletion (Add_Ons_To_Bill)
2019/02/15 11:19:50:763  insertCompletion (Add_Ons_To_Bill) (extended)
2019/02/15 11:19:50:764  insertCompletion -- going to cleanupCompletion
2019/02/15 11:19:56:581  completionsForPartialWordRange partial keyword is: a.
2019/02/15 11:19:56:582  getCompletions has 0 results. (Removed 0).  

Please provide the query SQL Pro runs to return the columns for tables and I'll test on my side to ensure expected columns are returned by Postgres.

**Comment by hankinsoft** [comment]
Hi,
Can you post the results of these two queries:

-- Basic tables and views
SELECT 
    n.nspname as default_schema, 
    t.relname as table_name, 
    a.attname as column_name,
    format_type(atttypid, atttypmod) AS column_type 
FROM 
    pg_class t 
    JOIN pg_catalog.pg_namespace n ON n.oid = t.relnamespace 
    JOIN pg_attribute a on a.attrelid = t.oid 
    AND a.attnum > 0 
    AND NOT a.attisdropped 
WHERE 
    t.relkind in ('r', 'm', 'v', 't') 
    AND attnum > 0 
UNION 
    -- Materilized views are not stored in the postgres
    -- information_schema table.
SELECT 
    ns.nspname as table_schema, 
    mv.relname as table_name, 
    atr.attname as column_name, 
    format_type(atttypid, atttypmod) AS column_type 
FROM 
    pg_class mv 
    INNER JOIN pg_namespace ns ON mv.relnamespace = ns.oid 
    INNER JOIN pg_attribute atr ON atr.attrelid = mv.oid 
    AND atr.attnum > 0 
    AND NOT atr.attisdropped 
WHERE 
    mv.relkind = 'm' 
ORDER BY 
    2, 3, 4

Query 2:
SELECT current_schemas(false)

Lastly, what schema is the table you are attempting to view autocomplete from? Thanks!

**Comment by h4ns3n** [comment]
@hankinsoft  Apologies for not seeing the questions above. i can confirm the issue has been resolved with version 1.0.465
