### ISSUE TITLE
SQLPro Studio crashes when editing procedure

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#236]
Version 1.0.411 (Build 110411)  running on MacOS 10.14.1 (18B75)

Steps taken:

Connect to DB (MS SQL 2014)
Search for object, right click -> Script to, Alter 

In this case I was just deleting a commented section (10 lines) of code out of 1000 lines total.

The app freezes, sits at 100% CPU in Activity Monitor, then eventually dies.

**Comment by hankinsoft** [comment]
Thanks Dave. Could you grab the latest version? I added some debug logging
around this issue: https://sqlprostudio.com/download.php. If you reproduce
it, could you send me the log files? Are you able to reproduce this by
following the same steps every time? If so, could you email me (kyle @
hankinsoft.com) the query and the range you delete?

Cheers,
Kyle

**Comment by davidharrison92** [comment]
I've narrowed it down a little further. The app dies when you select whole lines and delete them (double click, drag down for the ones I need).

I'll send you the logs and a snippet of the affected code.

**Comment by hankinsoft** [comment]
Thanks Dave. I believe I have this all fixed up here:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.417.app.zip

If you get the chance, please give it a try and let me know how it goes.

**Comment by davidharrison92** [comment]
Thanks Kyle - can't replicate it on that build.
