### ISSUE TITLE
sql editor panel horizontal scrolling bug

### ISSUE THREAD

**Issue by cr00maui** [hankinsoft/SQLPro#237]
MacOS 10.14.3 (18D109)
SQLPro Studio Version 1.0.413 (Build 110413)

When script text is long enough to cause horizontal scrolling and the insertion point is not near the left margin and one attempts to scroll to the left margin the text snaps back away from the left margin leaving the text clipped in the viewport. The only way to get to the left margin is using the keyboard (arrow keys).

**Comment by hankinsoft** [comment]
Could you post a screenshot or video? I’m not able to reproduce this issue and I’m not completely understanding the issue.

**Comment by hankinsoft** [comment]
FYI, I've been able to reproduce & fix this by disabling word wrap. I've got the fix available in the next release.

**Comment by cr00maui** [comment]
Thanks Kyle,

Sorry for the lock of response. I can confirm the issue is fixed.

Chris

**Comment by hankinsoft** [comment]
No problem! Thanks for the reply :D
