### ISSUE TITLE
Unable to delete row if using context menu

### ISSUE THREAD

**Issue by bomb-on** [hankinsoft/SQLPro#238]
I am unable to delete a row when using context menu.

Step 1:
![Screenshot 2019-03-22 at 11 52 44](https://user-images.githubusercontent.com/1420287/54821229-7a797c00-4c99-11e9-9247-c1c1c1b1f688.png)

Step 2:
![Screenshot 2019-03-22 at 11 52 57](https://user-images.githubusercontent.com/1420287/54821242-82d1b700-4c99-11e9-982c-2c4f80efad6d.png)

Step 3:
![Screenshot 2019-03-22 at 11 53 04](https://user-images.githubusercontent.com/1420287/54821254-87966b00-4c99-11e9-8592-b696066e34ce.png)

SQLPro Studio Version 1.0.426 (Build 110426)  (happened with all other versions in past 2 years)
macOS Version 10.14.3 (18D109) (happened with all other versions in past 2 years)

**Comment by hankinsoft** [comment]
Hi, I’ve added the scheme name to delete queries. The build will be available later this week.

**Comment by hankinsoft** [comment]
Hi, the update is available via the Mac App Store, as well as https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.1.0.431.app.zip if your using website builds. If you get the chance, please give that a try and let me know if it sorts the issue.

**Comment by bomb-on** [comment]
App didn't offer me any updates, neither I saw the update in App Store, but after manually downloading it and trying it out, I can confirm this works now. Thanks.

**Comment by hankinsoft** [comment]
Awesome, thank you for letting me know!
