### ISSUE TITLE
auto-complete doesn't work for some table

### ISSUE THREAD

**Issue by newbieh4cker** [hankinsoft/SQLPro#239]
auto-complete doesn't work for table 'access_log'.

![image](https://user-images.githubusercontent.com/23703741/55454340-8ca0d600-561a-11e9-8dad-414d4cd4b58a.png)

but, it works for table 'mst_users'

![image](https://user-images.githubusercontent.com/23703741/55454395-c376ec00-561a-11e9-86d5-40c5acac2576.png)

Why is is happening?

**Comment by hankinsoft** [comment]
Is this a newly added table? It can take a few minutes for autocomplete to
add new tables. If you restart the app, does the autocomplete update?

**Comment by newbieh4cker** [comment]
1. insert few tables
2. wait for 10 minutes
3. auto-complete not working
4. restart sql pro studio
5. still auto-complete not working...

**Comment by hankinsoft** [comment]
Hmm, ok thank you. I’m working on adding some autocomplete debugging for #235 but I’m stlll at least a week or more away. I’ll post it here when it’s available.

**Comment by newbieh4cker** [comment]
I just reinstall sql pro studio, and auto complete is working....
