### ISSUE TITLE
Numerics Need to show more decimals

### ISSUE THREAD

**Issue by BradRuderman** [hankinsoft/SQLPro#24]
Currently numerics are only showing 3 decimal places, they should show 9 by default.

**Comment by hankinsoft** [comment]
I've updated how decimal numbers are stored internally to the app for the next release. I believe this should sort the issue you are seeing (and I tested to confirm that it fixes a previous issue we have solved before with decimals). I'll post a note here once the build is available.

**Comment by hankinsoft** [comment]
Build has been available for awhile. If anyone still sees this issue, please let me know.
