### ISSUE TITLE
Inconsistent listing of PostgreSQL schemas/tables with identical connection settings

### ISSUE THREAD

**Issue by bomb-on** [hankinsoft/SQLPro#240]
I am using 2 (almost) identical databases with the same setting for "Group schemas in database tree" (Automatically) but one of them does apply grouping while other doesn't. In both of databases there's dozens of schemas, each with dozens of tables so I'd expect that "Automatic" setting would apply grouping in the same way. This is happening consistently every time I open either of databases.

![Screenshot 2019-04-11 at 11 33 32](https://user-images.githubusercontent.com/1420287/55955144-1a4e7800-5c50-11e9-9006-ebc7b669dfd4.png)

**Comment by hankinsoft** [comment]
Thanks, two questions about the database which is NOT grouping the schemas.

1. Could I get a screenshot of what you see when the 'tables' node is expanded?
2. What do you get for results if you run the following query (screenshot would be best):

SELECT 
    n.nspname AS "Name", 
    pg_catalog.pg_get_userbyid(n.nspowner) AS "Owner", 
    pg_catalog.array_to_string(n.nspacl, chr(10)) AS "Access privileges", 
    pg_catalog.obj_description(n.oid, 'pg_namespace') AS "Description" 
FROM 
    pg_catalog.pg_namespace n 
WHERE 
    n.nspname !~ '^pg_' 
    AND n.nspname <> 'information_schema' 
ORDER BY 
    1;


Thanks!

Feel free to email me the results if you don't want to post them here. kyle @ hankinsoft.com.

**Comment by bomb-on** [comment]
It seems that now when I explicitly selected "Yes" for grouping option and changed back to "Automatically", tables are grouped in schemas in that connection where they weren't earlier :/

Anyways, when "tables" node is expanded, i see all the schemas/tables listed in `schema_name.table_name` format and expanding them further shows me the table structure (columns).

![Screenshot 2019-04-11 at 12 21 25](https://user-images.githubusercontent.com/1420287/55956999-cb571180-5c54-11e9-964e-6ddb3f1e988c.png)


About the query you asked, I'm really not sure if this is shareable in any way. Is there some specific user's access privilege you're interested in? I am using superuser to connect to both databases, but issuing that query on each of them, I see that there is a bit of difference indeed.

**Comment by hankinsoft** [comment]
> It seems that now when I explicitly selected "Yes" for grouping option and changed back to "Automatically", tables are grouped in schemas in that connection where they weren't earlier :/

Hmmm, ok so it sounds like the setting wasn't saving properly?


For the query, all I really need is to know how many unique schemas return and to make sure that the query does not error.

Result from:

SELECT
count(distinct n.nspname)
FROM
pg_catalog.pg_namespace n
WHERE
n.nspname !~ '^pg_'
AND n.nspname <> 'information_schema';

would be fine (basically does this return more than one?)

**Comment by bomb-on** [comment]
Ah, right, this query results in `53` in one database and `70` in other :) Looks like now "Automatically" works as expected after I was changing it myself. Maybe it was just some corrupt settings, I'm using this tool for a long time now so maybe some updates related to this were just not updated correctly?

**Comment by hankinsoft** [comment]
Automatic was just added in the latest release.. previously it was a yes/no and the setting was kind of hidden (had many users asking about it). I added automatic as I figured that would probably be best case for most users - it sounds like there might be an issue with the saving/loading of this setting, so I'll take a look and see if I can figure that out.

**Comment by bomb-on** [comment]
Ok, thanks for looking at this, but it seems like now everything is fine on my end. Will report back if I notice some irregularities and hopefully help to pinpoint the source of the issue.
