### ISSUE TITLE
Connection Failed. Error in server handshake .... MySQL

### ISSUE THREAD

**Issue by djErock** [hankinsoft/SQLPro#241]
I get this error when connecting to MySQL after I upgraded to 1.0.465 - Running MACOS Mojave 10.14.4:

Connection Failed. Error in server handshake ....

This worked fine in the previous version as I have been using this for a while and have a license. I first thought I had some cache somewhere causing the issue but I had my DBA team download and install and they get the error as well.

Here are some of the logs:

Application is becoming active.
2019/04/24 09:26:38:630 NSApp sendAction: collectionItemViewDoubleClick
2019/04/24 09:26:38:630 doConnect: naus-vps-mema01 (detected port: 3306 specified port: 0)
2019/04/24 09:26:38:646 HSDispatchGroup enter com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:26:38:709 mysql_library_init result: 0. Client info: 10.3.12.
2019/04/24 09:26:38:709 Using cached ip address 10.248.102.174 for host {{my host name}}
2019/04/24 09:26:38:790 Using cached ip address 10.248.102.174 for host {{my host name}}
2019/04/24 09:26:38:901 MySQLClient::disconnect settings reconnect = 0
2019/04/24 09:26:38:901 MySQLClient::disconnect begin mysql_close
2019/04/24 09:26:38:901 MySQLClient::disconnect finished mysql_close
2019/04/24 09:26:38:901 SQLProConnectingWindowController endSheetWithReturnCode: OK
2019/04/24 09:26:38:903 HSDispatchGroup leave com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:26:38:904 Failed to connect with error: Error in server handshake
2019/04/24 09:26:38:904 Clearing internal database connection details.
2019/04/24 09:26:43:917 Application is resigning activity.
2019/04/24 09:27:23:149 Application is becoming active.
2019/04/24 09:27:25:636 User wants to open logs. Path is: /Users/erik/Library/Containers/com.hankinsoft.osx.sqlprostudio/Data/Library/Logs/SQLPro Studio
2019/04/24 09:27:25:822 Application is resigning activity.
2019/04/24 09:27:31:990 Application is becoming active.
2019/04/24 09:27:32:157 NSApp sendAction: collectionItemViewDoubleClick
2019/04/24 09:27:32:158 doConnect: {{my host name}} (detected port: 3306 specified port: 0)
2019/04/24 09:27:32:168 HSDispatchGroup enter com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:27:32:214 Using cached ip address 10.248.102.174 for host {{my host name}}
2019/04/24 09:27:32:324 MySQLClient::disconnect settings reconnect = 0
2019/04/24 09:27:32:324 MySQLClient::disconnect begin mysql_close
2019/04/24 09:27:32:325 MySQLClient::disconnect finished mysql_close
2019/04/24 09:27:32:325 SQLProConnectingWindowController endSheetWithReturnCode: OK
2019/04/24 09:27:32:327 HSDispatchGroup leave com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:27:32:327 Failed to connect with error: Error in server handshake
2019/04/24 09:27:32:327 Clearing internal database connection details.
2019/04/24 09:27:34:786 Application is resigning activity.
2019/04/24 09:27:40:338 Application is becoming active.
2019/04/24 09:27:40:494 NSApp sendAction: collectionItemViewDoubleClick
2019/04/24 09:27:40:494 doConnect: {{my host name}} (detected port: 3306 specified port: 0)
2019/04/24 09:27:40:504 HSDispatchGroup enter com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:27:40:548 Using cached ip address 10.248.102.174 for host {{my host name}}
2019/04/24 09:27:40:659 MySQLClient::disconnect settings reconnect = 0
2019/04/24 09:27:40:659 MySQLClient::disconnect begin mysql_close
2019/04/24 09:27:40:659 MySQLClient::disconnect finished mysql_close
2019/04/24 09:27:40:660 SQLProConnectingWindowController endSheetWithReturnCode: OK
2019/04/24 09:27:40:665 HSDispatchGroup leave com.hankinsoft.connectionWindowDispatchGroup
2019/04/24 09:27:40:665 Failed to connect with error: Error in server handshake
2019/04/24 09:27:40:665 Clearing internal database connection details.
2019/04/24 09:27:43:586 Application is resigning activity.

**Comment by hankinsoft** [comment]
Thank you for creating the new issue. Can you please post version details of your MySQL server? That should help me figure out what is going on.

**Comment by djErock** [comment]
We are running MEMSql version 6.7.3 ... According to our team: MemSQL is supposed to work with MySQL clients/connectors/syntax but with 6.3 (mem), we've seen this handshake error on other MySQL clients.  The issue seems to be Oracle changed the default authentication protocol with MySQL 8, so the posted solution seems to be having the ability to change the authentication protocol within the various clients `default-auth=mysql_native_password`.  Since mysql_native_password was the default for so long, I'm not sure most clients allow you to do this.  So the alternative is to downgrade the java or C mysql connector to an earlier version (not ideal).

**Comment by djErock** [comment]
I would imagine that if you allowed for both keys -> default-auth=mysql_native_password || mysql_native_password ... This shouldn't be an issue and would put your product ahead of the game in comparison to other tools we are seeing this with. GL

**Comment by hankinsoft** [comment]
Please try this version:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.429.app.zip

**Comment by djErock** [comment]
Yeah, unfortunately downgrading didn't work either but thanks for the link though.

**Comment by hankinsoft** [comment]
You don't happen to know which version you were using previously, do you?
An older version is: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.403.app.zip

**Comment by djErock** [comment]
Lifetime License key was purchased January 8, 2019, so whatever the latest was as of that date

**Comment by djErock** [comment]
1.0.403 Did not work either

**Comment by hankinsoft** [comment]
The latest version as of January 8'th would have been:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.320.app.zip

**Comment by djErock** [comment]
SQLProStudio.1.0.320.app.zip does work, Thank you for being super responsive. If at all possible, can you keep this thread updated when the MEM fix is in?

**Comment by hankinsoft** [comment]
Will do. Unfortunately I don't currently have an ETA as I have a few other higher priority issues at the moment.

**Comment by djErock** [comment]
No rush, I can work with this version until something comes out.

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.04.30.app.zip? If that fails to connect, can you email me the log file via kyle @ hankinsoft.com?

**Comment by djErock** [comment]
Yes, It worked

**Comment by hankinsoft** [comment]
Thanks!
