### ISSUE TITLE
Feature: More obvious Active Tab

### ISSUE THREAD

**Issue by jsoconnell** [hankinsoft/SQLPro#242]
I'm using environment-specific tab colors to more clearly delineate when I'm in dev vs. production. When I have multiple editor tabs open across multiple environments, the current shading that is used to indicate active vs. inactive tabs is too subtle to determine at-a-glance what tab is actually active.

Example:

<img width="1317" alt="Screen Shot 2019-05-01 at 7 40 02 PM" src="https://user-images.githubusercontent.com/11394519/57052767-71e07200-6c57-11e9-9188-bca57d7cdc80.png">

_It's unclear at a quick glance that "Untitled 5" is the active tab_

**Comment by hankinsoft** [comment]
I'll take a look into this. Even from your screenshot its pretty hard to tell which tab is active.

**Comment by hankinsoft** [comment]
Can you grab https://sqlprostudio.com/download.php and let me know what you think of the color changes?

**Comment by jsoconnell** [comment]
Yes! Highlighted tab very obvious now. Thanks!

[image: Screen Shot 2019-05-08 at 2.44.17 PM.png]

**Comment by hankinsoft** [comment]
Great! I'll be rolling this out as part of the next version update. Should be available in all products by mid-next week at the latest.

**Comment by hankinsoft** [comment]
Looks like you are using SQLPro for Postgres? The website version has been updated and the Mac App Store version has been submitted for review. Along with the 'more obvious active tabs', I've also added a custom color picker when editing connections. If/when you get the chance, please give them a look.

**Comment by jsoconnell** [comment]
Amazing, these changes are great, thank you so much!!
