### ISSUE TITLE
Query failed to load without an error

### ISSUE THREAD

**Issue by heruan** [hankinsoft/SQLPro#245]
I'm getting this error for any action from context menus:

```
/* Query failed to load without an error. */
```

![sqlpro-studio-failed-gifsicle](https://user-images.githubusercontent.com/851745/57466515-20506c80-7281-11e9-8c05-848562d898be.gif)

Version 2019.05.08 (Build 110475.1)

**Comment by hankinsoft** [comment]
Thanks. This is through the latest App Store version?

**Comment by hankinsoft** [comment]
I've reproduced. Fixing now. Quick solution is to double click the table
which will provide the same default 'select top 1000' behaviour.

**Comment by heruan** [comment]
Yes, the update was automatic but I guess it was yesterday and the day before it worked.

**Comment by hankinsoft** [comment]
Fix has been submitted to apple and should be available by tomorrow.
