### ISSUE TITLE
Comma inserted as grouping for TOP/LIMIT

### ISSUE THREAD

**Issue by neongrau** [hankinsoft/SQLPro#246]
SELECT TOP 1,000 * FROM ...

After double clicking a table instead of showing the first 1000 rows as usual. Since latest App Store Update there is a comma which ofc breaks the SQL.

**Comment by hankinsoft** [comment]
Ahhhhh whoops. Submitted a fixed build, it should be available within 24 hours.

**Comment by neongrau** [comment]
Thanks, working again!
