### ISSUE TITLE
Feature: Import sql

### ISSUE THREAD

**Issue by Chrispycode** [hankinsoft/SQLPro#247]
It would be really nice to be able to import sql dumbs.

**Comment by hankinsoft** [comment]
Hi! Could you explain what your looking for a bit further? In my head, I think 'open the sql file and hit run', which can be done now. Pretty sure that's not what your looking for, so any details would be great :D

**Comment by Chrispycode** [comment]
Yes I would like to be able to import an sql database dumb in to an empty database, not just open the file

**Comment by Chrispycode** [comment]
![Bildschirmfoto 2019-06-07 um 09 20 27](https://user-images.githubusercontent.com/22537998/59087668-a2c25f80-8905-11e9-9b71-1867a62563ae.png)
That's what I mean I want to be able to Import sql not just csv
