### ISSUE TITLE
SQLPro Studio - Script as -> CREATE to - not working when table name is not all lowercase

### ISSUE THREAD

**Issue by gordroid** [hankinsoft/SQLPro#248]
I'm using SQLPro Studio and a Postgres db.

The `Script as -> CREATE to` - is showing an error when the table name is not all lowercase. 

`Script as -> DROP to` and `Script as -> INSERT to` are working perfect, but, funny enough, 
on the other hand in the `Script as ->  DROP and CREATE to` is only working the drop part, the create part is showing the same error.

**Comment by hankinsoft** [comment]
Thank you, I've got this fixed for the next build. It should be available by the end of the week.

**Comment by gordroid** [comment]
Thank you Kyle!

**Comment by gordroid** [comment]
Hi Kyle!

Reopening this issue, on `Script as -> CREATE to` the table name was correctly fixed as you mentioned, but it has the same issue with the schema name, needs to be on double quotes.

The `Script as -> DROP to` works perfect, as it did, and it does use double quotes on both, schema and table.

Cheers!

**Comment by hankinsoft** [comment]
Ahhhh, your schema needs escaping? I didn’t clue into that - I think that
will help me sort a few of the other issues out too. Hopefully I’ll have a
fix available later this week. Are you open to trying a website build once
it’s available?

**Comment by gordroid** [comment]
Yeah, sorry i didn't report the schema as well.
I am, glad to help, let me know then. Cheers!

**Comment by gordroid** [comment]
It will probably fix #205 as well.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.06.06.app.zip? That should sort the issue.

**Comment by gordroid** [comment]
Work a treat. Thanks Kyle!
