### ISSUE TITLE
SQLPro Studio, for views, Script as > CREATE to, is failing (Postgres)

### ISSUE THREAD

**Issue by pelicanorojo** [hankinsoft/SQLPro#249]
In all its versions (file, clipboard, new query window), CREATE to is just generating:

`
CREATE OR REPLACE VIEW schema.view AS
`

Empty body

**Comment by hankinsoft** [comment]
Thanks, I've got this fixed for the next build. It will be available later this week or early next.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.06.06.app.zip? That should sort the issue.
