### ISSUE TITLE
close tab button: at right margin with complementary color

### ISSUE THREAD

**Issue by pelicanorojo** [hankinsoft/SQLPro#250]
First let me tell your tool is amazing.
I am not a UX guy, but maybe you could cross check with somebody what about to put the close tab button on right margin, and maybe with a more visible color (maybe when is used the amazing custom color tab features, I use red for production )

**Comment by hankinsoft** [comment]
Thanks for the note! I'm not 100% exactly sure what your saying. Would it be possible to get a screenshot with a bit of markup on it? That would help me out a ton. Thank you!

**Comment by hankinsoft** [comment]
Hi,
I think I understand what you mean by complimentary colour for the close button. I've made an improvement for this in the next release. Per changing the alignment of the close button, I've no plans for that --- current the close button alignment matches other macOS system apps such as Safari and Xcode.

Here is an example of the new close button tint (mouseover) as it will appear in the next builds.

<img width="762" alt="Close button tint" src="https://user-images.githubusercontent.com/3160528/60343206-da16b000-9989-11e9-9bd6-95751a064e9a.png">

**Comment by pelicanorojo** [comment]
Cool. Seems good. Thanks!
