### ISSUE TITLE
Add an option to disable iCloud connection

### ISSUE THREAD

**Issue by jameszillow** [hankinsoft/SQLPro#251]
When running queries in SQLPro, I can't help but see my `iCloud Drive -> SQLPro` fill up with `Untitled __` files

would it be possible to disable this option?

I love the product, but I don't necessarily want temporary these files going in/out of my iCloud account.  Would be great if this was an option to disable

I also feel this causes some slowness, because whenever I open up a new tab, I get the rainbow wheel for at least 5 seconds which I assume is from connecting/creating the temp file in iCloud.

**Comment by hankinsoft** [comment]
Hmmm, I've never noticed this before, but I see the files on my system as well. I'll take a look and see what I can find.

**Comment by jameszillow** [comment]
i appreciate it, thank you so much.

**Comment by hankinsoft** [comment]
Can you grab the latest version? That should sort it out.

**Comment by jameszillow** [comment]
thank you @hankinsoft 

it seems to have resolved the issue!  

really appreciate your quick response to this one, i'll go ahead and close this out :)
