### ISSUE TITLE
I bought the lifetime OSX SQL Pro Studio from the App store. Where do I get the license to activate it. Nothing was sent. Thanks!

### ISSUE THREAD

**Issue by joshuaoas** [hankinsoft/SQLPro#252]

**Comment by hankinsoft** [comment]
Hi,
If you purchase from the App Store, you won't get a license key as the App
Store has its own way to track purchases. If your being prompted for a
license key, please see:
https://github.com/hankinsoft/SQLPro/wiki/MAS-license-key.

**Comment by hankinsoft** [comment]
Hi, did that help sort the issue out?

**Comment by joshuaoas** [comment]
Got it, thanks!
