### ISSUE TITLE
Formatted query gets all upper-cased

### ISSUE THREAD

**Issue by heruan** [hankinsoft/SQLPro#253]
I'm sure this wasn't happening before, but since one of the latest updates when I right click and "Format query" the query gets formatted but also all keywords are upper-cased. It would be desirable to have a setting for that, instead!

**Comment by hankinsoft** [comment]
Closing as a copy of #232 (working on formatting options is in progress).

**Comment by hankinsoft** [comment]
(also just to note, there is an update to this):

> Hi! I've added this in a testing build (available here: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.34.app.zip). If you get the chance, please give it a try and let me know if this is what you were looking for.
> 
> You can change the formatting settings by opening `Preferences`, then going to the formatter tab. You can change keywords, functions and tables/columns. The options available are:
> 
> - **No action**: the word does not get modified.
> - **Uppercase**: the word gets uppercased.
> - **Lowercase**: the word gets lowercased.
> - **Match database**: the word matches what was found in the database.
> 
> <img width="552" alt="Screen Shot 2019-10-04 at 3 53 30 PM" src="https://user-images.githubusercontent.com/3160528/66232424-2d9e4580-e6bf-11e9-8d18-7d7031f9e164.png">
>
