### ISSUE TITLE
Do we have plan support Redis or MongoDB?

### ISSUE THREAD

**Issue by chuongtrh** [hankinsoft/SQLPro#255]
Do you have plan support Redis or MongoDB in SQLPro?
It is not an issue. Just only a question.
Thanks!

**Comment by hankinsoft** [comment]
Yes, MongoDB beta is actually in process and should be available in SQLPro Studio soon.

**Comment by chuongtrh** [comment]
Good to know. Thank your team!
Hope SQLPro Studio supports Redis too.

**Comment by gordroid** [comment]
It would be awesome if Redis support can be added, +1 on that.

**Comment by hankinsoft** [comment]
FYI the build at https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.06.11.app.zip has the MongoDB beta re-enabled.

**Comment by chuongtrh** [comment]
@hankinsoft Any update about Redis?
