### ISSUE TITLE
The preference 'Enable line wrap' is default ticked and not editable (greyed out)

### ISSUE THREAD

**Issue by Budders** [hankinsoft/SQLPro#257]
Steps to reproduce 

1. go to preferences > Query editor > General > Enable line wrap
2. Try and untick 
3. Expected, you disable line wrap | Actual, It is still enabled

Version 2019.06.06 (Build 110490.2) | MacOS Version 10.14.5 (18F132)

**Comment by hankinsoft** [comment]
Unfortunately in Mojave (10.14.x) disabling word wrap is not an option. Disabling word wrap is broken system-wide (see TextEdit [system build macOS app] and try to disable word wrap - although you can disable it via the UI, it does nothing in the app itself). I've contacted Apple about this, but unfortunately won't be able to support disabling word wrap until its fixed within the OS itself. I'll leave the issue open for now with hope that macOS 10.15 sorts the issue out.

**Comment by yeysman** [comment]
TextEdit doesn't have the option to disable wrap line. And according to apple forum - never had this option.
The option of TextEdit "Wrap to page" means wrapping to page (page borders) or if we disable it - wrap to window borders. So, TextEdit always wraps the line. It seems wrapping line is not the bug of OS, it is the feature of TextEdit.
@hankinsoft Does it mean SQLstudio will never have the option to disable wrap line?

**Comment by hankinsoft** [comment]
Closing as Wrap has been re-enabled as an option in SQLPro as long as you are running macOS 10.14.6 and above.
