### ISSUE TITLE
only one database is shown at side bar

### ISSUE THREAD

**Issue by kzhui125** [hankinsoft/SQLPro#258]
I have two databases, but it only shows one at the side bar.

<img width="635" alt="1" src="https://user-images.githubusercontent.com/11925432/59286387-37c8ae00-8ca2-11e9-92ce-dd9409fc3f8b.png">
<img width="441" alt="2" src="https://user-images.githubusercontent.com/11925432/59286389-38614480-8ca2-11e9-92b7-6c92c916d1a4.png">

**Comment by hankinsoft** [comment]
Do you have a database specified if you edit the connection?

**Comment by kzhui125** [comment]
@hankinsoft yes

Thanks.
