### ISSUE TITLE
SQLPro License Key

### ISSUE THREAD

**Issue by shaan-draft** [hankinsoft/SQLPro#259]
Recently updated SQLPro and it's prompting for a license key. How do I recover my existing license key?

**Comment by hankinsoft** [comment]
Which SQLPro app are you using? Generally if you purchased through the App
Store, but are being prompted for a license key, you need to follow this
article: https://github.com/hankinsoft/SQLPro/wiki/MAS-license-key

**Comment by shaan-draft** [comment]
I don't think I purchased through the App Store; if I recall correctly I purchased directly from the SQLPro website.

**Comment by hankinsoft** [comment]
Hi,
You should have an email with the license key. If you are unable to find
it, please either post the email here or email me directly via kyle @
hankinsoft.com and I can attempt to look up the license key.

Cheers,
Kyle
