### ISSUE TITLE
Feature Request: When using CoreData show actual Entity names

### ISSUE THREAD

**Issue by funky-monkey** [hankinsoft/SQLPro#26]
Hi Kyle, 

First off - I really enjoy working with SQLPro! 
Secondly - I use SQLPro for SQLite almost on a daily basis and mainly in combination with CoreData.
One of the things I run into constantly is the the internal naming of entities and field names that don't correspond between the raw SQLite db and Xcode. For instance in Xcode an entity is named `Contact` but in the SQLite db it's called `ZCONTACT`, which makes it daunting when reading or creating queries.

Would it be possible to see the actual entity and field names in SQLPro? This would probably be only a visual thing and not a functional thing (since underwater it still works the same). 
Maybe a checkbox "Show enity and fieldnames for using coredata". 

Just trying my luck here - If it's not possible then no worries :-)

Thanks in advance, 
Sidney

**Comment by hankinsoft** [comment]
Hi,
I've decided this change is not something that is going to make it in. I feel like displaying tables/columns differently than they would be queried against would make things very confusing to the end user. Sorry about that!
