### ISSUE TITLE
MySQLPro for Mysql does not show datetime correctly

### ISSUE THREAD

**Issue by dougreid72** [hankinsoft/SQLPro#260]
MySQL Workbench with correct value for DateTime field

<img width="439" alt="Screen Shot 2019-06-25 at 1 22 18 PM" src="https://user-images.githubusercontent.com/48137265/60124697-d4ce2100-974f-11e9-8864-55a631c1d872.png">

MySQLPro for MySQL with generic value for time
<img width="462" alt="Screen Shot 2019-06-25 at 1 18 55 PM" src="https://user-images.githubusercontent.com/48137265/60124716-de578900-974f-11e9-81b1-7011b1220aba.png">

**Comment by hankinsoft** [comment]
Hmm, thats odd. Could you post the table structure please?

**Comment by dougreid72** [comment]
<img width="988" alt="Screen Shot 2019-06-25 at 2 05 16 PM" src="https://user-images.githubusercontent.com/48137265/60125855-4e670e80-9752-11e9-8c61-77052ffc143f.png">

**Comment by dougreid72** [comment]
Also the RESTful API I have running on the system also shows the correct values for the time.

**Comment by hankinsoft** [comment]
Hmmm, very odd... still unable to reproduce the issue (see attached screenshot). A few questions to help figure out whats going on:

1. What MySQL version are you connected to? (visible in the database tree)
2. Are you running a simply select * query, or is there any sort of date time math going on?
3. What happens if you do a `SELECT now()`?

**Comment by hankinsoft** [comment]
<img width="1162" alt="Example" src="https://user-images.githubusercontent.com/3160528/60127412-87a97980-9766-11e9-974b-cde9b3f4239c.png">

**Comment by dougreid72** [comment]
MySQL Version: 5.7.24
No date time math.  
Get same answer if I get all columns or a subset
now() does give the correct answer.

**Comment by hankinsoft** [comment]
FYI I believe I've figured this out. Hope to have a new build available by tomorrow.

**Comment by hankinsoft** [comment]
Can you download and try https://d3fwkemdw8spx3.cloudfront.net/mysql/SQLProMySQL.2019.06.27.app.zip? That should sort the issue out.

**Comment by dougreid72** [comment]
I am away from office today.  I will check out the build at home later tonight.

**Comment by dougreid72** [comment]
I finally got back to my desk.  The new version fixed the problem.  What was the issue?

**Comment by hankinsoft** [comment]
Thanks for letting me know! The problem was with date time parsing specifically with milliseconds - it would cause the parser to fail on the h/m/s for some reason.
