### ISSUE TITLE
Crashes when opening WebSQL DBs from Google Chrome

### ISSUE THREAD

**Issue by pete27** [hankinsoft/SQLPro#261]
The app crashes each time when I try to open a DB created by Google Chrome. On a mac, the folder is located here: 
~/Library/Application Support/Google/Chrome/Default/databases

**Comment by hankinsoft** [comment]
Which app are you using, SQLPro Studio or SQLPro for SQLite?

**Comment by pete27** [comment]
SQLPro for SQLite latest version from the Mac App Store. But previous versions also crashed since a couple of months.

**Comment by pete27** [comment]
Actually it rather freezes with the rainbow wheel instead of crashing. I have to force quit.

**Comment by hankinsoft** [comment]
Hmmm, I'm not able to reproduce this (I don't use Chrome much, so my db is probably pretty empty). Would it be possible for me to get a copy of your database? I'm not sure what exactly these contain, so I dunno if this would be a privacy issue or not.

**Comment by hankinsoft** [comment]
Just to confirm, this is all fixed up? (Based on emailed database I received)?
