### ISSUE TITLE
Would like to have a '|' delimiter option on the Export Result Set As

### ISSUE THREAD

**Issue by rjenningsnypr** [hankinsoft/SQLPro#262]
Under the CSV option - add a pipe delimiter option (in addition to comma and tab)

MS SQL Studio has the pipe option and it would be nice to be able to run same queries and all people be able to output to pipe delimited CSV file.

**Comment by hankinsoft** [comment]
Thanks, I've added Pipe as an option for the next build. Should be available late this week or early next.

**Comment by hankinsoft** [comment]
Hi, just an FYI that the latest version has this option. The website version is available here: http://macsqlclient.com/download.php and the Mac App Store version should be available within a day or so. When you get a chance, please give it a try and let me know if that sorts the problem.
