### ISSUE TITLE
Numeric field showing incorrect precision

### ISSUE THREAD

**Issue by brevalessio24** [hankinsoft/SQLPro#264]
**OS**: MacOS High Sierra 10.13.6
**Connected DB**: SQL Server 2012
**Issue**: A column in the production server has type `numeric(8, 2)`. The SQLPro for MSSQL client connected to that DB shows `numeric(5)`. 
Altering the column type from `numeric(5)` to  `numeric(8, 2)` works fine, but the client keeps showing the wrong type.

Thanks

**Comment by hankinsoft** [comment]
Thank you, I've got this fixed for the next release (in both the database tree and the alter table view).

<img width="1071" alt="Screen Shot 2019-07-15 at 10 27 38 AM" src="https://user-images.githubusercontent.com/3160528/61219872-81664780-a6eb-11e9-98eb-09524545aa9e.png">

**Comment by hankinsoft** [comment]
Are you using SQLPro for MSSQL or SQLPro Studio?

**Comment by brevalessio24** [comment]
SQLPro for MSSQL

**Comment by hankinsoft** [comment]
The website version is available here: http://macsqlclient.com/download.php and the Mac App Store version should be available within a day or so. When you get a chance, please give it a try and let me know if that sorts the problem.

**Comment by brevalessio24** [comment]
Problem fixed, many thanks.
