### ISSUE TITLE
Smart Naming of Queries/Tabs

### ISSUE THREAD

**Issue by amilham** [hankinsoft/SQLPro#265]
Hi there,
SQLPro Studio is an invaluable tool but there are a few relatively minor changes that would make it much more efficient to work with.
Probably the most common thing I do in the app is to double-click on a table to get the "SELECT * FROM [TableName] LIMIT 1000" query. But each time I do that, it creates a tab called "Untitled [##].sql". The end result is that I have dozens of tabs open all called "Untitled" and I can't actually tell what they are.
Two things that would be _huge_ improvements:

- When doing "Select top 1,000" rows, automatically name the file something related to the table. Instead of "Untitled 47.sql" it could be "USERS Top 1000.sql" or something like that.
- If a tab is already open with one of the "top 1000" queries, double-clicking on a table name should jump to that existing tab instead of opening a new query (maybe have double-clicking jump to it, but retain the creation of a new query when doing it from the right-click menu.)

Thanks!
Andrew

**Comment by hankinsoft** [comment]
Hey Andrew - if you update to the latest version item 1 has already been implemented. I’ll have to think about item two (two thoughts I see right away - should the query be executed again at that point and what if the user has changed the query).

**Comment by hankinsoft** [comment]
Hi - I've decided to pass on the second two items for the time being. I'm not a fan of changing tab names based on context. I might revisit this in the future, but no plans for the time being.

The first item is available in the latest version of all SQLPro apps.
