### ISSUE TITLE
Autoupdate Changelog

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#266]
It'd be nice to see what bugs are fixed / features are added in each update. 

Apple's Software Update is (arguably) a great example of this: 

<img width="780" alt="Screenshot 2019-07-25 at 10 23 39" src="https://user-images.githubusercontent.com/3440843/61862744-48398e80-aec6-11e9-8e85-f1b8870440f4.png">

**Comment by hankinsoft** [comment]
Hey Dave, if you switch to the App Store version, you will get better auto updates and a change log included - I added the ability to enter your license key in the App Store version a few months ago, so it’s as easy as downloading and entering your license when prompted to purchase.

**Comment by hankinsoft** [comment]
As of 2019.46 the database tree now has a 'release notes' item available. Release notes are available at https://www.sqlprostudio.com/releasenotes/.

**Comment by hankinsoft** [comment]
And just to note, that build is available here: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.46.app.zip.
