### ISSUE TITLE
SQLPRO Crashes

### ISSUE THREAD

**Issue by dfarrand1415** [hankinsoft/SQLPro#267]
I just purchased SQL Pro for Mac OSX to work with an Azure SQL DB.

The first time I ran a query it crashed.

Tried it again.  I dont have time to mess with it.  I'd like my money back.  If you cant/wont do that, I will be disputing the charge on my CC

Regards

Dan

**Comment by hankinsoft** [comment]
No problem, your order has been cancelled and refunded.
