### ISSUE TITLE
MySQL Blanks displayed as NULLs

### ISSUE THREAD

**Issue by rickyphan** [hankinsoft/SQLPro#269]
![image](https://user-images.githubusercontent.com/6601161/62142812-f70e0e00-b2bc-11e9-8bf7-c10c058b4b7a.png)

Version 2019.07.19 (Build 110506)

Is this intentional? If so, it is a little bit misleading.

**Comment by hankinsoft** [comment]
Ahhh, no that shouldn't happen. I was doing some work in the last update to handle additional charactersets and I see that's where this issue got added in. I'll get this fixed up and submit a new build.

**Comment by rickyphan** [comment]
Looks great thanks!
