### ISSUE TITLE
Feature request: Oracle Schemas

### ISSUE THREAD

**Issue by dlitty** [hankinsoft/SQLPro#270]
Please break out each Oracle schema into its own tree node:

For schemas, what if I did the same thing as I do for Postgres connections? If there is more than one schema, I group them into their own tree node. So you would have

Schema 1

Tables
Views
Etc
Schema 2

Tables
Views
Etc

**Comment by hankinsoft** [comment]
If you get the chance can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.18.app.zip?

By default it will group schemas as long as more than one schema exists. You can enable or disable this option in the connections 'Advanced' settings.

**Comment by dlitty** [comment]
Looks & works great - thank you!

Thanks,
Dan

**Comment by hankinsoft** [comment]
Great, thank you! I’ll get the App Store version updated as well.
