### ISSUE TITLE
Feature request: Oracle delimiter

### ISSUE THREAD

**Issue by dlitty** [hankinsoft/SQLPro#271]
Right now we have scripts that we run periodically that I actually have to run in a different tool because they are separated within the body by a semicolon.  These are entire PL/SQL blocks of code that produce errors unless you run them all together.  An example:

```
DECLARE 
    v_user_name             VARCHAR2 ( 16 ); 
    v_opcode                skujournal.opcode%type;
    v_error                 dl_export_errors.error_message%type;
BEGIN 
    v_user_name := 'dlitty'; 
    v_opcode := 'LSI-CON-EXPORT';
    
    FOR vr IN ( SELECT lsi_common_pkg.isbn(ean) as sku
                  FROM dl_eans )
    LOOP
        BEGIN
            dbms_output.put_line( 'Exporting SKU: ' || vr.sku );
            cms_state_pkg.export( p_sku_in => vr.sku, p_user_in => v_user_name, p_opcode_in => v_opcode );
        EXCEPTION WHEN OTHERS THEN
            v_error := sqlerrm;
            INSERT INTO dl_export_errors (sku, error_message, export_time) values (vr.sku, v_error, sysdate);
        END;       
    END LOOP;    
END;
/;

```

**Comment by dlitty** [comment]
So in the above example, we would specify / as the delimiter, so that everything before that gets run as a single "command".

**Comment by hankinsoft** [comment]
Hi. How would you specify / as the delimiter currently? (I'm investigating adding support for this).

**Comment by dlitty** [comment]
Well, in your tool you can’t, currently.   Oracle’s default delimiter in their tool is not the semicolon, so they treat that entire group as a block.  I believe Oracle’s default for PL/SQL is /.  Their implementation is a bit different that other RDBMS’s in that the semicolon is only a delimiter within a potentially larger scope (the PL/SQL block).  If the block happens to consist of only a single line (e.g., a select or update or whatever), then a semicolon will work, but not if any other constructs are used (such as the example above).

Hopefully that makes sense - please let me know if not.  

BTW, I’ve seen in other tools the ability to specify the default delimiter at the connection level - so any oracle connections can be set to / while MySQL or sql server can use the semicolon, etc.

**Comment by hankinsoft** [comment]
So is this basically the same as how SQL Server uses GO as a seperator? Except Oracle uses / as a default (but it can be modified)?

**Comment by dlitty** [comment]
Yes.   GO in sql server is very similar when in the Transact-SQL context.

**Comment by hankinsoft** [comment]
Hi -- if you ran the following:

<img width="1162" alt="Screen Shot 2020-03-02 at 9 47 28 AM" src="https://user-images.githubusercontent.com/3160528/75681975-039b8000-5c6b-11ea-9c4a-a41d1d055047.png">

What would you expect to happen on the two:

> select 123 from dual;
> select 456 from dual;

Should that work, or should that throw an error because they are not separated with a /?

**Comment by dlitty** [comment]
that should fail, yes.  The following would work without error, as it is just two blocks:

declare id number;
begin
   dbms_output.put_line('foo');
end;

/

declare id number;
begin
select 123 into id from dual;
select 456 into id from dual;
end;

/

**Comment by hankinsoft** [comment]
Ah ok. That makes this much easier - I’m hoping I can have a build available early next week if not sooner with this.

**Comment by dlitty** [comment]
Super!   Thanks.

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.23.app.zip and see if that does the trick?

**Comment by dlitty** [comment]
That does appear to work, yes!   The only other thing I might suggest is making the actual separator itself configurable per connection - some tools do allow that, and you might have scripts already written that use different separators.

**Comment by hankinsoft** [comment]
This has been available for awhile now. If you run into any issues with it, please do let me know.
