### ISSUE TITLE
Monthly license shows expired but Apple App store shows that the subscription has been paid.

### ISSUE THREAD

**Issue by ralflukner** [hankinsoft/SQLPro#272]
My ProSQL app acts unlicensed even though the Apple App Store shows it is current through Aug 29, 2019.

**Comment by hankinsoft** [comment]
Hi. Please see https://github.com/hankinsoft/SQLPro/wiki/App-Store-Subscription-not-Renewing.

**Comment by ralflukner** [comment]
Restore purchases corrected the issue.  I did not figure this out because "Restore Purchases" did not look like a button or link (was gray text).   My mistake.

**Comment by hankinsoft** [comment]
No worries! Thanks for letting me know it’s sorted out.
