### ISSUE TITLE
Query cannot be cancelled

### ISSUE THREAD

**Issue by qaqtech** [hankinsoft/SQLPro#275]
With the latest build on macOS "Version 2019.08.09 (Build 10476.5)", the performance has deteriorated on multiple fronts. 

Any query with large dataset the output never completes. If we cancel the query, the control does not return to the query window. The only was out is to close the query window and open again.

**Comment by hankinsoft** [comment]
Hi,
I’m away for the week, but I’ll check into this as soon as I’m back (early next week). Sorry for the delay.

**Comment by bpaterni** [comment]
Happening here as well. Witnessing it happening on postgres. Not even a large query. With limit 1000, seems hang somewhere when retrieving results, since the bottom counter only says ~100, but query time duration continues to tick up. :(

**Comment by hankinsoft** [comment]
Hi. There is a new build available on the Mac App Store. Can you give this a try and see if it sorts the issue?

**Comment by synalysis** [comment]
> give this a try

Unfortunately it doesn't help. In my case (PG hosted by Google) I get 1000 results quickly but when I increase the LIMIT to for example 100000 and run the query again I read "Running: 300 records. 2 minutes..." and the query never ends.

**Comment by hankinsoft** [comment]
Anyone able to try this build? https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.08.26.app.zip (its SQLPro Studio, but all your existing connections will be available). If that sorts things up, I'll get all versions submitted to the App Store.

**Comment by synalysis** [comment]
> Anyone able to try this build? 

Looks good now!

**Comment by jim256** [comment]
@hankinsoft I've been seeing this with all builds (Postgres 10.9, Postgres 10.1, and Snowflake 3.43.3) since I first started using the app a month or so ago.

Currently using Version 2019.09.27 (Build 110555)
macOS 10.14.6 (18G95)

Is the build I have the latest? It's still a test build from other issues we've squashed together. Not sure if / when I should switch to the App Store version?

**Comment by hankinsoft** [comment]
If you run into this, please post the log file. Per App Store version, I submitted a new version last night - the version you are using would be the equivalent.

**Comment by jim256** [comment]
@hankinsoft , just doing a quick test, it seemed to cancel alright with Postgres 10.1, but not with Snowflake 3.44.2
[com.hankinsoft.osx.sqlprostudio 2019-10-07--17-25-35-008.log](https://github.com/hankinsoft/SQLPro/files/3698720/com.hankinsoft.osx.sqlprostudio.2019-10-07--17-25-35-008.log)

Log file attached.

SQLPro Studio 2019.33 (Build 110561)
macOS 10.14.6 (18G103)

**Comment by jim256** [comment]
@hankinsoft, just wanted to follow up here and make sure it hadn't gotten missed

**Comment by hankinsoft** [comment]
Not forgotten - snowflake cancellation works a bit different than some of the other query providers I use, so I’ve just been trying to figure out the best way to go about getting it working properly. Hopefully I’ll have it sorted out next week.

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.46.app.zip should let you cancel queries with Snowflake.

**Comment by jim256** [comment]
Seems to be working great for me now! THANKS. Very nice to not have to close a tab and open a new one (and then lose all undo history) every time I need to cancel a query :) Good to close this out in my opinion

**Comment by jim256** [comment]
@hankinsoft unfortunately, I'm seeing this now again (having to close a tab and open a new tab every time I want to cancel a query because it's unable to stop execution)

SQLPro Studio 2020.09 (Build 110634.5)
macOS 10.15.3 (19D76)
Snowflake 4.3.1

I was for sure seeing it before the recent 2 SQLPro Studio App Store releases as well (the one before the startup crash as well as the one with various fixes, including the #362 fix)

**Comment by jim256** [comment]
@hankinsoft this is actually starting to become more of an issue. Some large / expensive queries that I had "cancelled", just doing testing, were actually still running (some for up to 2 hours) on the server and I had no idea, and they were preventing other people's queries from even being started 😬 

SQLPro Studio 2020.14 (Build 110641)
macOS 10.15.3 (19D76)
Snowflake 4.5.2

**Comment by hankinsoft** [comment]
For the next build, I've added some extra logging around cancelling snowflake queries. I'm also working on updating the snowflake library used.

**Comment by jim256** [comment]
I think that has been improved, but not eliminated entirely. I'm still unable to cancel some Snowflake queries, though other times I can.

**Comment by hankinsoft** [comment]
Log file please :) I added some extra logging for this.

**Comment by jim256** [comment]
@hankinsoft completely missed your comment here!

I disconnected from all other databases, closed all other tabs, closed the app, deleted the log, rebooted my laptop, and then started it.
I started the app with the one tab with my query already open, waited about 20 seconds for it to colorize everything and finish starting, then hit execute.
I let it run about 25 seconds and then issued the keyboard shortcut to abort. The timer at the bottom of the screen then stops, the spinning wheel in the query tab continues to spin, and the Execute / Cancel button is disabled and shows "Cancelling".
I wait about 25 more seconds, then go into the Snowflake Web UI and issue an abort request to the query from there. About 2-3 seconds later, SQL Pro Studio fully enables the tab again with the message:
SQL execution canceled (Line 402)
Command cancelled by user.
The timer at the bottom then updates to reflect the actual time passed.

This seems to be more of an issue with heavier queries. If I do a simple SELECT * LIMIT 50000 and terminate it before it finishes, it usually does so without a problem. This query was 402 lines with many CTEs that built on each other, joins, calculations, and some JSON parsing.

Log file.
[com.hankinsoft.osx.sqlprostudio 2020-04-10--17-49-31-502.log](https://github.com/hankinsoft/SQLPro/files/4462780/com.hankinsoft.osx.sqlprostudio.2020-04-10--17-49-31-502.log)


Hopefully in all those details there's something that'll help you crack the code!


SQLPro Studio 2020.35 (Build 110664.5)
macOS 10.15.4 (19E287)
Snowflake 4.11.0

**Comment by hankinsoft** [comment]
For the latest build (2020.38), I've improved Snowflake cancelling to run `select system$cancel_query('CURRENT_QUERY_IDENTIFIER')` along with the pre-existing cancel api. I believe this should help out with the issue you are seeing with long running queries not being cancelled. Please give it a shot and let me know if that helps out.

**Comment by jim256** [comment]
@hankinsoft, I'm pretty sure I've noticed improvements here. Things seem to cancel more quickly.

I really thought the cancel query thing would do it, but I just tested it on one of my larger queries and no dice. I waited about 30 seconds, watched and refreshed the web UI History pane, and saw it just continue to run until I aborted it there, at which point SQLPro Studio recognized it had been canceled.

Anything further I can provide here?

**Comment by jim256** [comment]
Also, just to be clear then, should I expect that if I ever have data in temporary tables and cancel a query, that my session will be terminated and I'll lose all that data?

**Comment by hankinsoft** [comment]
> Anything further I can provide here?

When your on the 'Web UI History Pane' and you cancel a query from SQLPro, do you see a:
"select system$cancel_query('xxxxxx');" get run?

When you abort the query through the webui, does log a query run?

> Also, just to be clear then, should I expect that if I ever have data in temporary tables and cancel a query, that my session will be terminated and I'll lose all that data?

Currently yes. I'm planning on changing this, but I have a bit to rework before that will be ready.

**Comment by jim256** [comment]
@hankinsoft, good to know.

I strangely, I don't see cancel_query get run after canceling from either (whether via SQLPro Studio or the web UI). I see plenty of other "SELECT SYSTEM$..." queries, but nothing with the word "cancel" in it.

**Comment by jim256** [comment]
@hankinsoft, I just canceled another query (a very basic one) via SQLPro Studio and it resolved within about 2 seconds. I thought I'd go check the query history in the web UI for that particular query. This time, I did see the cancel query in the history pane.

**Comment by hankinsoft** [comment]
Could you post or email me the complex query? Understandable if not due to security.

**Comment by hankinsoft** [comment]
You can ignore the previous. I've found something that I'm investigating.

**Comment by hankinsoft** [comment]
I believe I have figured out why you cannot cancel some queries but can cancel others. I've got a build submitted (2020.42) which includes this. Hopefully available tomorrow.

**Comment by hankinsoft** [comment]
The latest build was approved by Apple a few hours ago. If you get the chance, please give it a try on your larger query. You will see 2-3 query’s run in the background (It depends on the situation) and the query should cancel relatively quick.

**Comment by jim256** [comment]
@hankinsoft , I think it works! I let it run for 3 min and cancelled. Then let it run for 1 min and cancelled. Worked both times. Saw the "select system$cancel_query('[QUERY_GUID]') in the history as well.
Thank you!!!!!!!!!!!!!!!

**Comment by hankinsoft** [comment]
Great! I'm going to close this. Please let me know if you run into any additional issues.
