### ISSUE TITLE
SQLPro Studio OS X - MySQL/MariaDB Bit length missing

### ISSUE THREAD

**Issue by natepelzel** [hankinsoft/SQLPro#277]
I have a table in my MariaDB database that has columns of type BIT(8).  However, when I view them in SQLPro Studio, they seem to be converted to BIT(1).

Table CREATE query:

```SQL
CREATE TABLE `roles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `employees` bit(8) NOT NULL DEFAULT b'0',
  `teams` bit(8) DEFAULT b'0',
  `users` bit(8) NOT NULL DEFAULT b'0',
  `contractors` bit(8) NOT NULL DEFAULT b'0',
  `designs` bit(8) NOT NULL DEFAULT b'0',
  `leads` bit(8) NOT NULL DEFAULT b'0',
  `sales` bit(8) DEFAULT b'0',
  `roles` bit(8) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `IDX_648e3f5447f725579d7d4ffdfb` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1
```

Here is a screenshot of what I see in SQLPro Studio:

![SPSIssue](https://user-images.githubusercontent.com/13549003/63550302-9c4c8880-c4ef-11e9-91a2-e178e00bd690.png)

And what I'd prefer to see (from a competing product):

![SPIssue](https://user-images.githubusercontent.com/13549003/63550375-c605af80-c4ef-11e9-8c24-a01b57584ac1.png)

**Comment by hankinsoft** [comment]
Thanks. I will take a look into this this week and should be able to get it sorted out.

**Comment by hankinsoft** [comment]
Can you download and try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.08.26.app.zip? That should fix this up.

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.27.app.zip should sort the bit setting issue out. If you get the chance, please let me know.

**Comment by natepelzel** [comment]
Sorry, been a little tied up at work.  Just got around to testing it today.  I have a license through iTunes/MAS, and it doesn't look like I can activate this one that way.  I used up my trial period on the last one you sent me.  How should I proceed?

**Comment by hankinsoft** [comment]
No worries! You should be able to go ahead and download the latest build (https://sqlprostudio.com/download.php) and your trial will be updated to include 7 new days - each update of SQLPro resets the trial days.

**Comment by natepelzel** [comment]
Oh right on.  I just downloaded and tested and all is working as expected.  Thanks so much!

**Comment by hankinsoft** [comment]
Thanks for letting me know. I’ll get the macos and iOS App Store versions updated to include this as well.
