### ISSUE TITLE
Is there a way to disable quotes on autocomplete

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#279]
On every table or column name that I use autocomplete for, the name is surrounded with quotes.

For example, let's say I'm going to query from the ORDERS table. I type:
FROM or

and it offers the completion of ORDERS. If I hit tab and accept the suggestion, it changes to:
FROM "ORDERS".

Is there a way to disable the quotes being used on all autocomplete suggestions?

On macOS 10.14.6 (18G87), Snowflake 3.39.1, SQLPro Studio 2019.08.27 (Build 110518.5)

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.08.30.app.zip? That should sort it. Please let me know.

**Comment by jim256** [comment]
Love it! Works great.
