### ISSUE TITLE
NULLs being displayed as 0 in query results window

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#280]
Is happening for me on various ID columns. Not sure if it would happen on a string column. Haven't seen that.

Very misleading. Until I switched to a different client, I was really starting to think my data was screwed up.

Don't know it if it's related to #269 

On macOS 10.14.6 (18G87), Snowflake 3.39.1, SQLPro Studio 2019.08.27 (Build 110518.5)

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.08.30.app.zip? That should sort it. Please let me know.

**Comment by jim256** [comment]
Seems to work in this build! Would you like me to close the issue now or keep it open?

**Comment by hankinsoft** [comment]
I'll close it out. The App Store version has been submitted for review, so it will be available all around shortly 👍. Thanks for letting me know everything was sorted out for you.

**Comment by jim256** [comment]
@hankinsoft Any chance I could have some sort of trial extension to continue testing? I didn't use it at all for the first while because of #274 , then stopped using it once I hit #280 . Would love to be able to give it a thorough evaluation now.

**Comment by hankinsoft** [comment]
Hi. I have a first year free promo available at the moment: https://www.sqlprostudio.com/tdt.html. In addition license keys created through this will also work on the iOS version of the app (https://apps.apple.com/app/sqlpro-studio/id1273366668).

**Comment by jim256** [comment]
That's awesome! Just got my license. Thanks a lot! I'll continue to provide further feedback.

**Comment by jim256** [comment]
@hankinsoft I just recommended SQLPro Studio to my brother since I recommend it to everyone. He said that he was unable to get the discount code from here to work. Is that expected?

**Comment by hankinsoft** [comment]
Hmmm no, that should still work. What browser is he using? Are there any JS errors?

**Comment by jim256** [comment]
@hankinsoft , Sorry, looks like he had gone about it wrong. Squared away. Thank you!
