### ISSUE TITLE
Script As: Create To table in SQLPro for Oracle not working

### ISSUE THREAD

**Issue by jseila** [hankinsoft/SQLPro#281]
When I right click on a table and use the script as -> Create To New Query Window I get the following error: 

/* Generation failed with the following error: 

ORA-31603: object "PPDM_COLUMN_ALIAS" of type TABLE not found in schema "COMMERCELINK"
ORA-06512: at "SYS.DBMS_METADATA", line 6069
ORA-06512: at "SYS.DBMS_METADATA", line 8666
ORA-06512: at line 1

*/

Any idea why this error is occurring and how to correct it? 

Thanks,

Joseph

**Comment by hankinsoft** [comment]
Hi,
It might be a permissions issue. What happens if you run the following query:

SELECT
  dbms_metadata.get_ddl('TABLE', 'PPDM_COLUMN_ALIAS', 'COMMERCELINK')
FROM
  dual

?

**Comment by hankinsoft** [comment]
It does seems as if its a permissions error - see https://stackoverflow.com/questions/26026068/dbms-metadata-get-ddl-not-working.
