### ISSUE TITLE
Feature Request: Option to Show Tables and Views Together in Navigation Pane

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#282]
It would be nice to be able to have the option to show tables and views together in one list in the left pane. I know that some apps do this and some don't. I'm personally a fan, so it would be nice to at least have that as an option.

**Comment by hankinsoft** [comment]
Thanks for the suggestion. I'll add this to the backlog - as this receives more requests I'll push it up higher in priority.

**Comment by cwolcott** [comment]
If the request is implemented it would be nice if the icons for a table and view are a little more different to help identify them in a combined list.

**Comment by hankinsoft** [comment]
Going to close this for now unless I receive additional requests.
