### ISSUE TITLE
Feature Request: Increase Keyboard Shortcut Customizations

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#283]
It would be great to have greater control over which keyboard shortcuts do what. Currently, most of them are fixed, and you can only change 3. Personally, I'd like to change both the currently-customizable options to currently-unavailable shortcuts (being used by non-customizable shortcuts) and be able to change the non-customizable shortcuts to other things.

For example:
 - I like CMD + R to show / hide the query results window, but this is not a customizable shortcut.
 - I like CMD + E to execute a query (so that I can easily do it with just my left hand), but this shortcut is unavailable because it is being used by another, non-customizable shortcut ("Use Selection for Find").

**Comment by hankinsoft** [comment]
Thanks for the suggestions! I'll have a look at adding a few more customizable shortcuts and see what I can come up with.

**Comment by jim256** [comment]
Awesome news! I use shortcuts pretty heavily, so that'll be great.

**Comment by jim256** [comment]
@hankinsoft just wanted to check in here and see what your thoughts were. Really looking forward to customizing a few things, even just like hiding the results window with CMD + R so I don't need two hands for it

**Comment by hankinsoft** [comment]
Investigating. What do you mean by
> I like CMD + R to show / hide the query results window, but this is not a customizable shortcut.

Specifically 'this is not a customizable shortcut'? Are you getting an error of some sort? Could you post a screenshot?

**Comment by hankinsoft** [comment]
Please give https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.31.app.zip a try.

**Comment by jim256** [comment]
THANK YOU! Awesome stuff. Love it.

**Comment by jim256** [comment]
@hankinsoft shoot, I forgot about the ability to change tabs with something like control + tab and control + shift + tab (to go backward). Is this a shortcut that could also be customized?

**Comment by hankinsoft** [comment]
Can you give me an example of what keys you would remap to next/previous tab? (An example ensures I test with those keys when I get this improvement added).

**Comment by jim256** [comment]
Sorry, I'm not sure I understand completely. What I'd personally like is:
- Next tab: Ctrl + Tab
- Previous tab: Shift + Ctrl + Tab

However, it may be even better to make them user-mappable.

Does that answer your question?

**Comment by hankinsoft** [comment]
It does thank you. I've got this ready for the next release (late this week).

**Comment by hankinsoft** [comment]
Added for this build: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.35.app.zip

**Comment by jim256** [comment]
Love it! Looks to be squared away 😄
