### ISSUE TITLE
Feature Request: Hide Results of Intermediate CTEs

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#287]
I've got a query (which I often do) where I get an initial data set in a CTE, then perform a couple steps / transformations in subsequent CTEs, and then do a final SELECT to output the final data.

Right now, SQLPro Studio will output a message for every intermediate CTE along the way, even though though the message is essentially empty.

I would like to see these hidden, and only show the results of the final SELECT.

Please see screenshot below for current behavior that I"m trying to describe:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/15026225/64635923-e1146280-d3bd-11e9-82c3-53d90088a920.png">

**Comment by jim256** [comment]
Snowflake 3.41.2
SQLPro Studio 2019.09.11 (Build 110536)
macOS 10.14.6 (18G95)

**Comment by jim256** [comment]
@hankinsoft , just wanted to check in and see what your thoughts were here. Still seeing it with build 110553.

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.27.app.zip should sort this. I didn't make it an option, but rather 'status' messages like this now go to the messages tab. Please let me know if that sorts it.

**Comment by jim256** [comment]
Love it! Thank you so much. Very nice to have that.
