### ISSUE TITLE
Feature Request: Smart Automatic Tab Renaming

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#289]
I used to use an add-on to SQL Server Management Studio that would automatically name your query tabs based on their content. This would be a really useful feature, as it makes it easier to identify queries at a glance.

The add-on did it in the following format
[SELECT/UPDATE/DELETE] - Table Name - Database Name

It also allowed some configuration of this so that you could change which elements were in the name and their order.

It would also be nice to have this update itself each time the query was executed.

**Comment by jim256** [comment]
I think the product I used to use just used the base table (the first one right after the FROM). I'm sure that idea could be improved upon, but (in my opinion) it's a decent MVP approach to make one query distinguishable from another 90% of the time.

**Comment by jim256** [comment]
@hankinsoft just wanted to follow up here to make sure you saw my last message. Thoughts?

**Comment by hankinsoft** [comment]
Hi - this is not something I'm currently planning to implement. Maybe if I get enough requests, or possible I will add an option for extensions to allow this in the future.
