### ISSUE TITLE
Bug: Autocomplete Suggestion With Enter Acceptance Inserts Blank Spaces and Tabs After Suggestion

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#290]
Sometimes when I accept an autocomplete suggestion using the return key, the suggestion will be inserted, followed by 2 tabs and 4 spaces

Sometimes it also inserts a hard return.

Seems to happen with columns and tables.

Snowflake 3.41.2
macOS 10.14.6 (18G95)
SQLPro Studio 2019.09.11 (Build 110536)

**Comment by hankinsoft** [comment]
I'm going to close this for now. If you see it again and can grab a video, please let me know and we can reopen.

**Comment by jim256** [comment]
Just started happening again, so I thought I'd come check out the issue again.
This time it was happening with PostgreSQL 10.9.
I did a little experimentation. It's not totally consistent. With columns, it only seems to happen if you already have at least one column beforehand. If it's the first column in the query, there's no issue.

Please see the attached video for a simple example.
[ReturnKeyInsertingBlankSpaces.mov.zip](https://github.com/hankinsoft/SQLPro/files/3632509/ReturnKeyInsertingBlankSpaces.mov.zip)

**Comment by hankinsoft** [comment]
Thanks, reproduced. I'll get this fixed for the next build (probably tomorrow).

**Comment by hankinsoft** [comment]
Fixed for this build: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.20.app.zip. This might also fix #292 and additionally fixes an issue which could cause slowdowns on enter/exit fullscreen.

**Comment by hankinsoft** [comment]
I'm going to close this. If you do see it again, please let me know.
