### ISSUE TITLE
Connect appends @localhost ip to Login name

### ISSUE THREAD

**Issue by rhunton** [hankinsoft/SQLPro#291]
Hi - i'm connecting via my vpn server (10.10.0.7 ip) and configuring my connection to MySQL server at 10.10.0.12 and attempting to use a login defined in the database with ssh tunneling disabled.  If I specify the user ID as "userid", the login fails with a message "userID@10.10.0.7" which of course doesn't exist.  if I specify the user ID as "userid@10.10.0.12" the login fails with a message "userid@10.10.0.12@10.10.0.7".  How can I force it to use a userID of simply userid@10.10.0.12?

**Comment by hankinsoft** [comment]
Hi,
Could you please post a screenshot of the error you are seeing? That should
help me out figure what is going on. Thanks.

**Comment by rhunton** [comment]
Sure.
This:
![image](https://user-images.githubusercontent.com/46053181/64929084-436ec800-d7ef-11e9-9768-88b26bd3160b.png)
Yields This:
![image](https://user-images.githubusercontent.com/46053181/64929090-74e79380-d7ef-11e9-8ef0-35e04d233c2d.png)
And This:
![image](https://user-images.githubusercontent.com/46053181/64929101-934d8f00-d7ef-11e9-8a28-8decdde2d0dc.png)
Yields This:
![image](https://user-images.githubusercontent.com/46053181/64929110-b24c2100-d7ef-11e9-9978-f34dcbf5197e.png)

10.10.0.7 is the NAT ip on the inside of my VPN server.  rhunton@10.10.0.12 would be the correct ID.

**Comment by rhunton** [comment]
Hi - looks like I was a problem at my end.  I'm connecting fine now.  Thanks!
