### ISSUE TITLE
Bug: Snowflake: Boolean Field Display

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#294]
NULLs or Boolean fields are displaying as:
TRUE: 1
FALSE: Cell has no contents / is empty (but doesn't display NULL as other fields)

We have the same table in Postgres, replicated to Snowflake. The field shows up correctly when I connect to the Postgres table from SQLPro Studio, and it shows up correctly when I look at it in Snowflake through the Snowflake.com editor. Just seems to be connecting to Snowflake from SQLPro Studio where I see the issue.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/15026225/65364274-01b69680-dbce-11e9-8086-9f269d766d60.png">

SQLPro Studio 2019.09.20 (Build 110546)
Snowflake 3.42.3
macOS 10.14.6 (18G95)

**Comment by hankinsoft** [comment]
Thanks, fixed for next build (will be early next week, I'll post the build once its up).

<img width="708" alt="Screen Shot 2019-09-20 at 9 21 35 PM" src="https://user-images.githubusercontent.com/3160528/65365077-b790dd80-dbec-11e9-9e0f-803488d20e0d.png">

**Comment by hankinsoft** [comment]
I've been working on #295 and haven't pushed a new version up as of yet. I'm hoping to have both available tomorrow.

**Comment by jim256** [comment]
😃 awesome news! Looking forward to it

**Comment by hankinsoft** [comment]
Fixed in https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.24.app.zip. Please confirm if you get the chance.

**Comment by jim256** [comment]
Awesome! Not seeing any more empty cells for false 💪 

But, I am seeing the following:
TRUE: 1
FALSE: 0

Is this the intended behavior? I personally prefer the text TRUE/FALSE as it makes it tell to see at a glance that the column datatype is boolean. Happy to file a separate feature request if that's the case.

**Comment by jim256** [comment]
@hankinsoft , I think this is fixed! Thank you so much. Now I see "true", "false", or NULL.
