### ISSUE TITLE
Feature Request: Use fuzzy / full-text search in autocomplete

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#295]
I would love to see autocomplete search full object names when trying to match!

Many times I only know part of the particular column name I'm after. Other times, I may want to see all the fields ending in "_at" because we frequently append that to the end of our datetime columns, and this would allow me to see all my datetime field choices in the table I'm working in.

For example, if I have a column named "order_date":
Current behavior: I type "dat" and nothing appears. I type "ord" and the suggestion appears.
Requested behavior: I type "dat" and all fields (including order_date) that contain "dat" appear. I type "ord" and all fields containing "ord" appear.

Would be great to have this for all objects (columns, tables, schemas, databases, functions, etc.).

**Comment by hankinsoft** [comment]
Added full text search for autocomplete in https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.24.app.zip. Please confirm if you get the chance.

**Comment by jim256** [comment]
You're a monster! So nice to have this in the works.

Unfortunately, as I type, it'll overwrite later text.

For example, if I have:

SELECT
	b.
	
FROM
	table b

And I'm looking for all fields containing "_at", and I type "_a", it highlights everything all the way through "FROM". If I wait a few seconds or type "t" to finish it out, it replaces everything through "FROM", such that I'm left with:

SELECT
		b._a	table b

Would you like me to file a separate bug?

**Comment by hankinsoft** [comment]
No need to file a separate bug - I’ll get this sorted up tomorrow - sorry
about that. You should be able to download the previous release if this is
a road block for the day :(

**Comment by jim256** [comment]
No worries! I'm just excited about the feature. Sounds great.

**Comment by hankinsoft** [comment]
Can you give https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.25.app.zip a try? It should sort this issue and also changes the display for #294. Possibly fix #292 but I'm less hopeful on that one.

**Comment by jim256** [comment]
Hmm, app keeps crashing when running a query. Some queries will work, some won't. Can't quite nail down a pattern.

Hoping this will help:
[SQLProStudioCrash.log](https://github.com/hankinsoft/SQLPro/files/3653711/SQLProStudioCrash.log)

**Comment by hankinsoft** [comment]
Looks like its related to the true/false conversion. I'll have a sorted build uploaded shortly.

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.09.25.1.app.zip

FYI issue was on nullable boolean columns - trying to convert a null to true/false.

**Comment by jim256** [comment]
Got it. Good to know! You're a machine with how quickly you crank these updates out. I'll give this one a shot now (reverted to the previous build earlier today).

**Comment by hankinsoft** [comment]
Hi,
I do have a Windows version buts its no where near as complex as the macOS version - unfortunately the demand is not there to work on it as much as the macOS version, so the windows version does not support many features that macOS has (Snowflake support is not present in the Windows version at all).

**Comment by jim256** [comment]
Good to know! When on Windows, I would actually probably only use it for MySQL 95% of the time. Is it something you consider pre-release in terms of quality? Or is it fully production ready, just without all the features?

I think that we can probably close out this issue. Seems to correctly replace stuff and search the whole object name. Thank you so much!!! Love this.

**Comment by hankinsoft** [comment]
Its available on the Windows App Store (search for SQLPro Studio). Its the very very basics at the moment and unfortunately does not allow entering a cross platform license key as of yet.
