### ISSUE TITLE
Feature Request: Autocomplete Matching Without Schema Name

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#296]
It would be awesome if autocomplete could look for matches in all schemas for table names.

Current behavior:
- If a schema is specified, autocomplete offers suggestions
- If schema is omitted, there are no autocomplete suggestions

Requested behavior:
- If a schema is specified (in the actual query), autocomplete offers suggestions only within that schema
- If a schema is omitted, autocomplete offers suggestions from all schemas (and shows the fully-qualified suggestions in schema.table.column_name format)

**Comment by hankinsoft** [comment]
Which type of database are you seeing this with?

What do you mean by:
> If a schema is specified (in the actual query)

(Screenshot please if possible)?

**Comment by jim256** [comment]
Seeing this with Snowflake 3.44.1 and Postgres 10.1 and 10.9.

Example:
Let's say I have a schema called order_system.

If I type:
SELECT
	*
	
FROM
	order_system.

, autocomplete will suggest a list of all tables in that schema after typing the period.

If I type:
SELECT
	*
	
FROM

I will not get any autocomplete suggestions. If I type the first character or two of a table name, I will still not get any suggestions. If I start with [schema_name]., and start typing the table name, I will get suggestions.

**Comment by jim256** [comment]
It looks like autocomplete will now suggest matches from all schemas, but won't insert the schema name when a suggestions is accepted, resulting in a "SQL compilation error: Object '[TABLE_NAME]' does not exist or not authorized." kind of error.

**Comment by jim256** [comment]
@hankinsoft just wanted to give this a bump. I often query from Snowflake, and we have quite a few schemas that are replications of production systems. As things are now, I'm unable to get autocomplete for a table inside of a schema unless I fully qualify.

It looks like things have improved on this front somewhat since I last commented here, so I'll make an updated example.

Let's say I have a schema called order_system and a schema called fulfillment_system. Let's say they both have a table called products.

Current behavior
If I type:
SELECT * FROM pro
I get a suggestion for the order_system product table (and the schema is shown on the right side of the suggestion window in parenthesis), but not for fulfillment_system. If I accept the suggestion for order_system (which says "products (order_system)"), then it just inserts "products", without fully qualifying it. Since it isn't fully qualified, I get an error if I try to run the query.

Desired behavior:
To have autocomplete suggest matches from any schema (unless I've already typed in a schema, like "order_system.").
To have autocompleted-inserts include the schema name (if the database has multiple schemas).

**Comment by hankinsoft** [comment]
Something like this?

![CleanShot 2020-06-11 at 12 12 00](https://user-images.githubusercontent.com/3160528/84404159-ddc43680-abdc-11ea-9be4-cf5205d38e77.gif)

First loop through the gif, DBO is not my current schema, so autocomplete inserts DBO.actor. Then I set dbo as my schema and autocomplete no longer inserts DBO.

**Comment by hankinsoft** [comment]
This is now available in the latest version. Please give it a try and let me know if you run into any issues.

**Comment by jim256** [comment]
@hankinsoft this is awesome!

One small request: if there is a table named "product" in two schemas, it will only show one of them in the auto-complete suggestion list. It'd be really useful for me to be able to see them all.

**Comment by jim256** [comment]
@hankinsoft, I just realized one more thing:

Before accepting suggestion:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/15026225/85914208-90f57800-b7f8-11ea-8f9a-9ee82a41a41d.png">

After accepting suggestion:
<img width="322" alt="image" src="https://user-images.githubusercontent.com/15026225/85914220-9e126700-b7f8-11ea-8edb-40af84f0c6bd.png">

**Comment by hankinsoft** [comment]
Thanks, fixed for the next build.

**Comment by hankinsoft** [comment]
2020.61 is now available which fixes this. If you get the chance, please give it a test and confirm its working as you would expect.

**Comment by jim256** [comment]
@hankinsoft, awesome! Seems fixed.

**Comment by hankinsoft** [comment]
Just going back through some older issues. I think we are good to close this one?

**Comment by jim256** [comment]
Yep, I think so. Just tested again.
