### ISSUE TITLE
Bug: Autocomplete Unavailable in JOIN ON Clauses

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#297]
I've noticed recently that I don't get autocomplete suggestions when writing ON clauses for JOINs.

This will sometimes also cause me to only get autocomplete suggestions for the primary table in the query. For example:

SELECT
	o. -- Autocomplete suggestions appear
,	p. -- Autocomplete suggestions do not appear
	
FROM
	orders o
	JOIN products p ON o.product_id = p.id -- Autocomplete suggestions did not appear for columns in ON clause

It seems to be intermittent. Sometimes it will work for the first ON clause, but not for successive AND conditions in the same clause.

Postgres 10.1 and Snowflake 3.44.1
macOS 10.14.6 (18G103)
SQLPro Studio 2019.30 (Build 110558)

**Comment by hankinsoft** [comment]
Hi. https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.33.app.zip should sort this issue. Please let me know if you get the chance.

**Comment by jim256** [comment]
I think this took care of it! I am, however, noticing that columns will show when typing a table name immediately after the from. Not sure if this was happening before or not.

Example:
I have a table named products. This table has columns such as product_id and product_price.

If I type:
SELECT * FROM prod

Autocomplete will suggest product_id, product_price, and then (at the bottom of the list) products (the table). Would you prefer I open a separate issue for this?

**Comment by hankinsoft** [comment]
Hi,
>  however, noticing that columns will show when typing a table name
immediately after the from. Not sure if this was happening before or not.
It looks like this is a recent bug. Lets leave it with this issue for the
moment (I've got it fixed, but I'm working on a bigger change that's going
to take me the better part of this week before I can post a new build).

**Comment by hankinsoft** [comment]
This should be fixed in https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.35.app.zip.

**Comment by jim256** [comment]
Looks like it's now taken care of for all tables after the first one in the FROM.

In this build, autocomplete is suggesting column names and table names when I start to type a table name immediately after "FROM"

**Comment by hankinsoft** [comment]
Should be sorted in this build: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.40.app.zip.

**Comment by jim256** [comment]
Seems to be working great! Thanks for your hard work
