### ISSUE TITLE
Feature Request: Prioritize Column Name Colors Over Function Colors

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#298]
Sometimes I have column names that are colorized as functions:

<img width="139" alt="image" src="https://user-images.githubusercontent.com/15026225/66422643-46f90780-e9c7-11e9-8065-83a9264b349d.png">

I'd like to request that a word be colorized as a keyword only if it isn't a column name (or at least only if it isn't being used as a column name, as in the screenshot above being that it's directly after the table alias)

**Comment by hankinsoft** [comment]
In this specific case, you're seeing this with Postgres? When you use a keyword as a column in postgres, I thought it needed to be escaped/quoted? (Like p."asin")? Is that not the case? (Just trying to figure this out). I can make it so anything after <tableName>. is treated as a column first, but I just want to correct my understanding.

**Comment by jim256** [comment]
I apologize - I should have been more clear:
- this was with Postgres
- I can use p.asin (without quotes / escaping)

**Comment by jim256** [comment]
@hankinsoft looks to be resolved with the latest build! I appreciate your giving so much attention to these issues and knocking them all out at once so quickly. A solid update
