### ISSUE TITLE
Bug: Snowflake: MIN Function Not Colorized

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#299]
The MIN function doesn't seem to be colorized on Snowflake connections:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/15026225/66422810-a22afa00-e9c7-11e9-8c70-f8208b6b0230.png">

FWIW, it works fine on Postgres 10.1 and 10.9

Snowflake 3.44.2
SQLPro Studio 2019.33 (Build 110561)
macOS 10.14.6 (18G103)

**Comment by hankinsoft** [comment]
Fixed for the next build. Will be available late this week.

**Comment by jim256** [comment]
Seems to also be fixed in  2019.36 (Build 110564) with Snowflake 3.45.1! Awesome stuff. Thank you so much for such a superb app and far-above-average responsiveness / drive to improve it.
