### ISSUE TITLE
Line Numbers Off in Display

### ISSUE THREAD

**Issue by BradRuderman** [hankinsoft/SQLPro#30]
<img width="382" alt="untitled_1_sql" src="https://cloud.githubusercontent.com/assets/2366784/12411248/e08e30f2-be31-11e5-8ede-157a0472d7db.png">

**Comment by hankinsoft** [comment]
Should be fixed up here: http://www.macpostgresclient.com/download.php.

**Comment by hankinsoft** [comment]
This has been fixed. If you still see the issue in the latest version, please let me know.
