### ISSUE TITLE
Feature Request: Autocomplete: Include CTEs and Derived Tables

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#300]
Right now, if I create a CTE, autocomplete will not suggest the name of the CTE in the FROM of later queries, nor will it suggest column names. Same goes for derived tables.

I don't know if this would be too performance-hungry, but it would definitely be nice.

If not, it would still be nice to have the column names and CTE/Derived Table names colorized.

**Comment by hankinsoft** [comment]
CTEs will now be included in autocompletion with this build:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.35.app.zip

derived tables not yet - they will take a bit more effort (but please try the CTEs and let me know if they work properly for you).

**Comment by jim256** [comment]
Definitely getting there!

Item 1:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/15026225/66589239-52753b80-eb4b-11e9-8f59-d4fe6769ee8d.png">

Item 2:
It seems to work with the very first CTE, but not with subsequent CTEs. So if I have three CTEs in a row, autocomplete will recognize the CTE name and column names of the first CTE, but nothing from the others.

Seems to be the same for Snowflake 3.45.1 as with Postgres 10.9
macOS 10.15 (19A583)
SQLPro Studio 2019.36 (Build 110564)

**Comment by hankinsoft** [comment]
Hmmmm, just to verify that's a valid CTE? I thought column names had to be included in the CTE such as:

WITH Employee_CTE (EmployeeNumber, Title)    <--- column names here
AS
(SELECT NationalIDNumber,
        JobTitle
 FROM   HumanResources.Employee)
SELECT EmployeeNumber,
       Title
FROM   Employee_CTE

Is that not the case with snowflake?

**Comment by hankinsoft** [comment]
Ok, I found a document listing CTEs in the style you posted above. That will be a bit harder to parse out, but I'll take a look into. For the currently build you are using only CTEs that include the column names will work properly :D

**Comment by jim256** [comment]
Understood! Thanks again.

**Comment by hankinsoft** [comment]
CTEs (multiple styles) should be sorted in this build: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.40.app.zip.

They work pretty good IMO!

<img width="394" alt="Screen Shot 2019-10-11 at 12 35 30 PM" src="https://user-images.githubusercontent.com/3160528/66671403-46b07480-ec32-11e9-892f-f8b760684eb1.png">

<img width="699" alt="Screen Shot 2019-10-11 at 10 34 37 AM" src="https://user-images.githubusercontent.com/3160528/66671408-4912ce80-ec32-11e9-9711-2e32e463aa27.png">

Subqueries are still not handled yet.

**Comment by jim256** [comment]
Nice!

Two things I just came across:

Some parentheses showing up in the suggestions list:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/15026225/66858759-34db1400-ef47-11e9-9f45-caa1a81cc32c.png">


Second CTE not being recognized

<img width="394" alt="image" src="https://user-images.githubusercontent.com/15026225/66858731-21c84400-ef47-11e9-977b-81302ab15694.png">

**Comment by hankinsoft** [comment]
Fix will be available later this week with one caveat:

Some columns will be unable to determine the column names. An example would be:

```
WITH myCTE AS
(
    SELECT 1, 2 + 3, 3 + 4 as myAlias, 4 + 5 myAliasWithoutAs
)
SELECT * FROM myCTE
```

In this case the column will display as 'unknown column 1', 'unknown column 2', 'myAlias', 'myAliasWithoutAs'.

If you run the above CTE postgres will provides `?column?` for the unknown columns, SQL Server will provide an error (requires alias), Snowflake will use the full text as the column name. In each case you would be unable to use the `unknown columns` in the query. The workaround of specifying column names in the CTE title such as `WITH myCTE (col1, col2, col3, col4) AS` or using an alias for columns. It should however display the proper number of columns.

Again, fix will be available later this week.

**Comment by jim256** [comment]
Sounds like an awesome approach! Perhaps it may also make sense to consider using the word "unaliased" in the place of "unknown", just so it's more explicit, if you think that's better.
Thank you!

**Comment by hankinsoft** [comment]
Available in https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.45.app.zip.

Should sort both unknown cte columns as well as consecutive CTEs.

<img width="555" alt="Screen Shot 2019-10-18 at 10 34 14 AM" src="https://user-images.githubusercontent.com/3160528/67099336-25043f80-f194-11e9-8a3f-fe3eab0917fd.png">

**Comment by jim256** [comment]
Love it!! Thanks.
