### ISSUE TITLE
Feature Request: Increase Query History from 100 to 1000

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#301]
I'd like to see more query history stored. Just tried to go find one, but couldn't because it had been too long.

It might be even more handy if this were a user-configurable limit

**Comment by hankinsoft** [comment]
I'll do some testing for increase the default (the 100 limit was arbitrarily picked). No plans to make this configurable - As a rule of thumb I try to keep as few as possible configuration items in SQLPro.

**Comment by jim256** [comment]
Thank you!

**Comment by hankinsoft** [comment]
Should be fixed in https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.35.app.zip.

**Comment by jim256** [comment]
@hankinsoft , just saw all the issues this addresses! You're an animal. Excited to try it out. Any other changes in this build?

**Comment by hankinsoft** [comment]
> Any other changes in this build?

Yes, the main change in the build in the `App Shutdown` -> `Save state` preference now preserves the database tree. If you have `Save state` enabled, when you quit the app then re-open the app it should mostly appear in the same state as it had before (a few item states are not preserved such as recordsets). Feel free to give that option a try and leave any feedback you find!

**Comment by jim256** [comment]
That's another great change. Cool!

**Comment by jim256** [comment]
@hankinsoft, just tried the new build. Unfortunately, I can't get it to launch. Don't know if it's of help or not, but attached is the Apple crash report thing:
[SQLProStudio_Crash.log](https://github.com/hankinsoft/SQLPro/files/3713502/SQLProStudio_Crash.log)


Tried it a few times, but it crashed each time.

The log file just says:
> 2019/10/10 09:59:13:117  Application com.hankinsoft.osx.sqlprostudio v110563 has launched.

**Comment by hankinsoft** [comment]
Give me like ten minutes. Waiting for the build to be approved by Apple.

**Comment by hankinsoft** [comment]
Ugh, its taking forever to be approved today. Sorry for the delay.

**Comment by jim256** [comment]
No worries. I'll go back to an older build for now.

**Comment by hankinsoft** [comment]
Sorry about that. Build is now available at https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.36.app.zip when you get the chance.

**Comment by jim256** [comment]
I think it's working!

Also, I love how the history won't increment for the exact same query (if it's already the most recent in the history). Very nice implementation 👌
