### ISSUE TITLE
Feature Request: Results Pane Filter Functionality / Default Table View

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#305]
Let's say I have a products table. One row there has a product_id of 1001. If I right-click a table name in a query and click "Select top 1,000 rows" or double-click the table in the navigation pane, I get the default SELECT * FROM [table_name] LIMIT 1000.

I'll often just want to open a table and quickly find a row therein. So I'll open it using one of the above-mentioned ways, use Cmd + Shift + F, and then throw in my value.

I thought for a while that the filter function simply wasn't working, because it would often not return values that I knew were there. I think it's that it's applying the LIMIT 1000 first.

I'm not sure of the best way to address this. I can see that, if I'd typed my own custom query and then used the filter, that I'd obviously want it to only return the results of that query. But, when I'm just looking at the table, it'd be nice to not have this happen.

I thought about this for a bit. In my opinion, I think it may make the most sense to treat the results-pane filters as regular WHERE clauses, applying them before the "LIMIT 1000".

Depending on perspective, it may make sense to only apply this when the default query has not been modified in any way.

Thoughts?

**Comment by hankinsoft** [comment]
Hi, I plan on eventually taking a different route with this. Adding a 'query builder' which would take care of the overall filtering (and leaving the results grid filter option as is -- just filtering the results of the query). However, it's not something that I currently have an ETA on.

**Comment by jim256** [comment]
Understood. Personally, I like the idea of treating the filters the same as they would be if entered as part of the WHERE clause - meaning that they would be applied before the LIMIT clause.
That being said, that's just my personal opinion

Would you like me to close this out then?

**Comment by hankinsoft** [comment]
Yes, let's close for now. I don't currently have plans for updating the filter to apply to the WHERE.
