### ISSUE TITLE
Feature Request: Default Filter Condition to "is" Rather Than "is less than" When a Specific Column is Chosen

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#307]
Currently, the default filter condition in the results filter pane is "contains". In my opinion, it would make the most sense if this changed to "is" when a specific field that is incompatible with "contains" is chosen from the column list, rather than defaulting to "is less than".

**Comment by hankinsoft** [comment]
I've added 'contains' as a valid option for all fiends in the next release. So for example if a numeric field has a value of 123456 and you choose contains and enter 45 this field will be considered a result. I think that will invalidate the item you listed above?

**Comment by jim256** [comment]
Yeah, that sounds great! Just tested it, and it seems to be working well.

Also, I absolutely love that you added linking on foreign key fields so that I can just click on a field and have it automatically generate a query with that in the WHERE clause.

This app really is the best. Awesome to see things continuing to move forward so rapidly!
