### ISSUE TITLE
Crashes on Mac OS both Mojave and now Catalina.  Tried old builds also

### ISSUE THREAD

**Issue by jwathen1** [hankinsoft/SQLPro#308]
SqlPro for sqlite crashes on launch on my MacBook Pro late 2017
It was a great program, but I cannot get it to open as soon as I open it, it crashes.
Worked great before one of the later updates, even with the new update it crashes as soon as I open.

**Comment by hankinsoft** [comment]
Any chance you could post the crash log? Could you try the latest version from https://sqlitepro.com/download.php and see if you still see the issue?

**Comment by jwathen1** [comment]
> Any chance you could post the crash log? Could you try the latest version from https://sqlitepro.com/download.php and see if you still see the issue?

Yes, I was already using the latest version and I just downloaded your link and same issue. 
Here is the crash log.
[SQLPro for SQLite_2019-10-12-091720_Josephs-MacBook-Pro.zip](https://github.com/hankinsoft/SQLPro/files/3720704/SQLPro.for.SQLite_2019-10-12-091720_Josephs-MacBook-Pro.zip)

**Comment by hankinsoft** [comment]
Are you using the system unzip utility? Or something like `betterzip` or `archive manager`? I ask because in the stacktrace, I see its attempting to load a `xib` file and the non-system unarchives sometimes correct these xib files and this issue occurs (crashing at startup).

**Comment by hankinsoft** [comment]
Also, as far as you can remember, have you ever opened a .mdb file with SQLPro?

**Comment by jwathen1** [comment]
HiI use winzip but had installed from App StoreNo I use a different program for mob on a VM instance



Sent from Yahoo Mail for iPhone


On Sunday, October 13, 2019, 6:57 PM, Kyle Hankinson <notifications@github.com> wrote:


Also, as far as you can remember, have you ever opened a .mdb file with SQLPro?

**Comment by jwathen1** [comment]
I am not using WinZip to unzip files to use with the program.I am using sqlite3 files from Ancestry app and other genealogy programs.
I deleted the application and used your link and also I tried to load from the Apple AppStore.Same results.
Is there anything I can try or folder to delete?
Thanks
Joe
    On Sunday, October 13, 2019, 06:52:05 PM EDT, Kyle Hankinson <notifications@github.com> wrote:  
 
 
Are you using the system unzip utility? Or something like betterzip or archive manager? I ask because in the stacktrace, I see its attempting to load a xib file and the non-system unarchives sometimes correct these xib files and this issue occurs (crashing at startup).

**Comment by hankinsoft** [comment]
Would you be ok to try removing the application saved state? If you are comfortable in terminal, you can do so by closing the app, then running the following command:

`/Users/kylehankinson/Library/Containers/com.hankinsoft.osx.sqliteprofessional`

This will remove the recovery state and will give the app a fresh start when it launches. It should prevent and crashes from restoring the app state and should start you at the app launch screen.

**Comment by jwathen1** [comment]
That worked and the application now opens properly.Thank you
    On Wednesday, October 16, 2019, 07:30:49 AM EDT, Kyle Hankinson <notifications@github.com> wrote:  
 
 
Would you be ok to try removing the application saved state? If you are comfortable in terminal, you can do so by closing the app, then running the following command:

/Users/kylehankinson/Library/Containers/com.hankinsoft.osx.sqliteprofessional

This will remove the recovery state and will give the app a fresh start when it launches. It should prevent and crashes from restoring the app state and should start you at the app launch screen.
