### ISSUE TITLE
Escape Column Names in a Create Table

### ISSUE THREAD

**Issue by BradRuderman** [hankinsoft/SQLPro#31]
When right clicking and choosing create table, the DDL is populated but the column names aren't escaped.

**Comment by hankinsoft** [comment]
Should be fixed in the latest build:
https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres18a.app.zip

**Comment by hankinsoft** [comment]
This should be all fixed up, but if you are still seeing it, let me know.
