### ISSUE TITLE
SQLPro for PostgreSQL crashes with PostgreSQL12

### ISSUE THREAD

**Issue by esb-dev** [hankinsoft/SQLPro#310]
After update to PostgreSQL 12 the app crashes as soon I want to open a database.
Any hints what to do?

**Comment by hankinsoft** [comment]
Can you try this build? https://t.co/r8eCYWhYhm?amp=1 I believe that will sort the issue. A secondary workaround would be to specify the database name in your connection. (I'll have an App Store update available later this week).

**Comment by esb-dev** [comment]
This works fine.

Kind regards 
Burkhardt

> Am 17.10.2019 um 18:15 schrieb Kyle Hankinson <notifications@github.com>:
> 
> Can you try this build? https://t.co/r8eCYWhYhm?amp=1 I believe that will sort the issue. A secondary workaround would be to specify the database name in your connection. (I'll have an App Store update available later this week).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

—
Prof. Dr. Burkhardt Renz
Fachbereich MNI
Technische Hochschule Mittelhessen (THM)
Wiesenstr. 14
D-35390 Gießen Germany
+49 0641 309 2393
https://esb-dev.github.io
