### ISSUE TITLE
It is not possible to insert record into a SQLite database table (option always disabled)

### ISSUE THREAD

**Issue by mwhite05** [hankinsoft/SQLPro#312]
<img width="455" alt="Screenshot 2019-10-23 14 32 18" src="https://user-images.githubusercontent.com/11068771/67423292-faeebb00-f5a1-11e9-800a-99db1ab5196f.png">

**Comment by hankinsoft** [comment]
Thanks, I'm investigating. Two questions if you get the chance:

1. Does the table involved have a primary key?
2. Is this a simple or complex query (is it a basic select x from table, or does it contain joins)?

Thanks!

**Comment by mwhite05** [comment]
1. It doesn't seem to matter either way. I added two test tables, one with a primary key and one without. I even tried a third using autoincrement on the primary key and it didn't help.

2. None of the tables involved contain relationships and I'm only trying to insert to a single table. I double-click the table name in the sidebar and then right click in the results area to try to insert and that's when I see the Insert row is disabled.

`CREATE TABLE test1 (id PRIMARY KEY, name TEXT, value TEXT)`
`CREATE TABLE test2 (name TEXT, value TEXT)`
`CREATE TABLE test3 (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, value TEXT)`

**Comment by hankinsoft** [comment]
Thanks, I think I have this fixed up. I'll be posting a build hopefully tomorrow, but if not it will be early next week (hoping to have the updated searching ready for testing as well).

**Comment by hankinsoft** [comment]
If you get the chance, please give the following build a try:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.48.2.app.zip

That should sort the insert menu item issue. Please let me know.

**Comment by mwhite05** [comment]
Thank you, this is working in the latest build.
