### ISSUE TITLE
Bug: Autocomplete: Inserts both CTE alias and original table alias

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#314]
If I accept the autocomplete suggestion here, it'll insert both aliases and complete it as ap.p.id, which will fail when I try to execute.

<img width="208" alt="image" src="https://user-images.githubusercontent.com/15026225/67791223-b26d4c80-fa3c-11e9-9f9f-4d45236eca53.png">

SQLPro Studio 2019.46 (Build 110573)
macOS 10.15 (19A602)
PostgreSQL 10.1, PostgreSQL 10.6, PostgreSQL 10.9, Snowflake 3.48.1

**Comment by hankinsoft** [comment]
Thank you. Fixed for the next build (later this week).

**Comment by hankinsoft** [comment]
Fixed for https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.50.app.zip. Also, I've added a neat feature where CTEs and Aliases are now included in syntax highlighting.

**Comment by jim256** [comment]
Using 2019.54 (Build 110602.5)

Seems to be fixed. Thank you, sir!

The new syntax highlighting is also awesome. I love that you'll often proactively add other, helpful things when fixing something in particular. Good stuff.
