### ISSUE TITLE
Bug: Autocomplete: Suggestion box runs off bottom of screen

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#315]
If I've got a long query and am at the bottom of the screen, the autocomplete suggestion box will run off the bottom of the screen if there are too many suggestions:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/15026225/67791748-9e761a80-fa3d-11e9-8cdf-5f422b8a25dc.png">

SQLPro Studio 2019.46 (Build 110573)
macOS 10.15 (19A602)
PostgreSQL 10.1, PostgreSQL 10.6, PostgreSQL 10.9, Snowflake 3.48.1

**Comment by hankinsoft** [comment]
Fixed for the next build (available later this week).

![CleanShot 2019-10-29 at 14 38 30](https://user-images.githubusercontent.com/3160528/67793560-d3906600-fa59-11e9-8182-10fcf4b8ffb8.gif)

**Comment by hankinsoft** [comment]
Should be sorted in https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.50.app.zip.

**Comment by jim256** [comment]
Using 2019.54 (Build 110602.5)

Seems to be fixed! Also absolutely loving the other improvements made in this version. This is an absolute top-notch SQL tool. Love it.
