### ISSUE TITLE
MySQL syntax error with table name is groups

### ISSUE THREAD

**Issue by chuongtrh** [hankinsoft/SQLPro#316]
MySQL version 8.0.17.

When select double click into the table list. It will select default 1000 rows of the table

`SELECT * FROM groups LIMIT 1000;`

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups LIMIT 1000' at line 1 (Line 1)`

Fixed SQL:
SELECT * FROM \`groups\` LIMIT 1000;

Reason: MySQL from version 8.0.2 added **groups** in [keywords](https://dev.mysql.com/doc/refman/8.0/en/keywords.html)

Please support in next version. Thanks

![image](https://user-images.githubusercontent.com/7924855/67852778-a1f1ca80-fb3f-11e9-88b5-1da40e6eef43.png)

**Comment by hankinsoft** [comment]
Hi,
A temporary workaround will be to manually escape the table named groups. Try the following query:

SELECT * FROM `groups` LIMIT 1000;

**Comment by hankinsoft** [comment]
Are you using SQLPro Studio, or SQLPro for MSSQL? I've got a fixed build for SQLPro Studio available here: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.50.app.zip.

**Comment by chuongtrh** [comment]
SQLPro Studio for MySQL. 
Thank you for quick fixed!

**Comment by hankinsoft** [comment]
This is available in the latest SQLPro for MySQL version as well - https://d3fwkemdw8spx3.cloudfront.net/mysql/SQLProMySQL.2019.52.zip.

**Comment by hankinsoft** [comment]
Just to note this is also available now via the Mac app store. Please let me know if you run into anymore issues.
