### ISSUE TITLE
Crash with large query, possibly due to line wrapping(?)

### ISSUE THREAD

**Issue by bpaterni** [hankinsoft/SQLPro#317]
Hi, I'm not sure if you indirectly receive crash reports that have been sent to apple via their automatic crash reporting tool, but I thought I would submit an issue here anyway.

I've encountered a crash lately that seems fairly reproducible. The crash occurs when I'm in the query window constructing a large, but simple insert-select query, and the problem may be caused in some way by line wrapping that is occurring due to the amount of columns involved.

Below are 2 crash reports I've saved from the crash report tool:

https://pastebin.com/QY76mV4X
https://pastebin.com/P5K8i3KS

Let me know if you need further information.

**Comment by hankinsoft** [comment]
Also, any estimate how large the query was? And what type of database
server are you connecting to?

**Comment by bpaterni** [comment]
No direct table aliases/ctes, and shouldn't have been any indirect aliases/ctes that I know of. The query was a simple insert-from-select, as in:

    insert into <TABLE-DEST> (column1, column2, ...)
    select (column1, column2,...) from <TABLE-SRC> where columnx in (
    identifier1
    ,identifier2
    ,...
    ,identifier750
    )

Maybe it's possible that the columns involved might related to a table alias, but I believe the chances of that are low.

The DB was SQL Server.

**Comment by hankinsoft** [comment]
Thank you. If you get the chance, can you try build https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.50.app.zip and let me know if you continue to see if the issue?

**Comment by bpaterni** [comment]
I tried reproducing the crash by copying identifiers, building the select statement, and then copying the select columns to the insert statement. The crash would most often occur as I finished typing the right parenthesis around the insert clause, and attempting to jump the cursor back to the front of the line.

This build seems to have fixed the crash though, thanks! :)

**Comment by hankinsoft** [comment]
Thanks for letting me know that sorted it out! I'll get this submitted to the App Store as well.
