### ISSUE TITLE
SQLPro Studio Version 2019.53 (Build 110595.5) (APP STORE) asks for license

### ISSUE THREAD

**Issue by pverhoye** [hankinsoft/SQLPro#318]
Hi!

I just updated to the new app store version and now SQLPro Studio asks for a license. I have 7 days :)

Thanks!

**Comment by hankinsoft** [comment]
Ahhhh, sorry about that! I uploaded the website build rather than the App Store build :( I've submitted a new build - these are generally approved within ~24 hours, so it should be available way before the 'trial' expires. Again, very sorry about that!

**Comment by pverhoye** [comment]
Hi Kyle! No problem! Mistakes are what make us human! 
Thanks for acting so fast!

**Comment by hankinsoft** [comment]
Just to note, this should be all fixed up. Please let me know if your all set if you get the chance, and again, sorry for the issue!

**Comment by pverhoye** [comment]
Yes! I saw the update and it works!!
