### ISSUE TITLE
Views are no longer listed when connecting to an Amazon Redshift instance

### ISSUE THREAD

**Issue by danroyo** [hankinsoft/SQLPro#32]
SQLPro for Postgres

Just upgraded from 1.0.11 (Build 37) to 1.0.17 (Build 86).  Previously, views would be properly listed when the "Views" caret was expanded, however the new version doesn't seem to properly detect views.

![screen shot 2016-02-17 at 11 22 39 am](https://cloud.githubusercontent.com/assets/4440684/13116371/c35fb1e6-d569-11e5-935d-356d21e7c99d.png)

**Comment by hankinsoft** [comment]
Is that a materialized view or regular view that is missing?

**Comment by danroyo** [comment]
It's a regular view

**Comment by hankinsoft** [comment]
Can you please give this a try:
https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres18a.app.zip

It should do the trick. If you confirm, I will push the update to the mac
app store. I can also give you a non-mas license key to use in the
meantime. Please email kyle @ hankinsoft.com and I can provide you with it.

**Comment by danroyo** [comment]
It works, thanks so much!

**Comment by hankinsoft** [comment]
No problem. I'll submit the update to the mac app store as well.
