### ISSUE TITLE
Cannot use "Open File"

### ISSUE THREAD

**Issue by Privatesmee** [hankinsoft/SQLPro#320]
When I click on Open File, nothing happens. I have just accepted the latest update for MSSQL Pro and I am now facing this issue.

**Comment by Privatesmee** [comment]
This is for 2019.54 (Build 10486.5)

**Comment by hankinsoft** [comment]
Thank you. I've reproduced and fixed the issue. I'll have the build submitted to Apple shortly and it should be available within ~24 hours. Sorry for the issue!

**Comment by Privatesmee** [comment]
Thank you for the fix. This now works correctly.
