### ISSUE TITLE
"File>Open File" not working in Version 2019.54 (Build 10486)

### ISSUE THREAD

**Issue by William-Sheehan** [hankinsoft/SQLPro#323]
When I use "File>Open File" or the keyboard shortcut (⌘O), nothing happens now that I have upgraded to this new version. The only way that I can open files is to "right-click/Open With" on .sql files.

**Comment by hankinsoft** [comment]
I’ve got a fix for this that will be available early next week. Sorry about that.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.2019.57.app.zip? That should sort this out.
