### ISSUE TITLE
History

### ISSUE THREAD

**Issue by lward99** [hankinsoft/SQLPro#324]
The program as far as I can tell only holds history for a session. Is there a way to hold forever?

**Comment by hankinsoft** [comment]
Hi - the history should be getting held continuously per connection. This is not what you are seeing?

**Comment by lward99** [comment]
Per connection yes. But is there not a way to keep the query history/logs permanently? After connection?

**Comment by hankinsoft** [comment]
Sorry, I mean 'per individual connection' not per launch of the
application. If you close the app and re-open an existing connection the
history that you ran on that connection should still be available.

**Comment by hankinsoft** [comment]
Are you opening an SQLite database by any chance?
