### ISSUE TITLE
Feature Request: zerofill attribute support

### ISSUE THREAD

**Issue by gclove** [hankinsoft/SQLPro#326]
For MySQL 

```sql
CREATE TABLE zerofill_table (
    i1 INT UNSIGNED ZEROFILL,
    i2 INT UNSIGNED
);
```

**Comment by hankinsoft** [comment]
Sure, I'll add this for the next build.

**Comment by hankinsoft** [comment]
Are you using SQLPro for MySQL or SQLPro Studio? And is it installed via the App Store, Website or Setapp? (I'll have a build available for testing tomorrow).

**Comment by gclove** [comment]
I'm using **SQLPro Studio  Setapp** . Thank you very much .
> Version 2019.57 (Build 110603)

**Comment by hankinsoft** [comment]
New version has been submitted too Setapp. It should be available within ~24 hours.

**Comment by gclove** [comment]
Yes, it's ready . Thank you .
