### ISSUE TITLE
MSSQL Database Export for its trigger

### ISSUE THREAD

**Issue by alextang96** [hankinsoft/SQLPro#327]
Hi Developer, There are no such options to extract all tables trigger to another server. I want to export the trigger script into create trigger procedure. Could you please add it? I am your registered user.

**Comment by hankinsoft** [comment]
I'll investigate adding an option. Currently you would need to right click on each trigger and choose 'script as' -> 'create to' -> 'new window'.

**Comment by hankinsoft** [comment]
Fixed for the next build (2022.1). Exporting or scripting a MSSQL table will now include the tigger. Should be available sometime next week.

**Comment by hankinsoft** [comment]
Closing. If you find issues with the trigger exporting, please let me know.
