### ISSUE TITLE
Copy selected as insert does not produce valid SQL for bools

### ISSUE THREAD

**Issue by bpaterni** [hankinsoft/SQLPro#328]
Hi hankinsoft, just wanted to inform you of a bug in the "copy selected as insert" functionality. Ever since booleans started being rendered as "true/false" in the query results pane, they also get rendered as true/false when a user attempts to "copy selected as insert".

I think the colored true/false is a net positive for result readability, but it would be nice if the bools got restored to "0/1" (or whatever the bool literal is for the current SQL dialect -- been seeing this with MSSQL) with the copy functionality.

Thanks for your help! :)

**Comment by hankinsoft** [comment]
Thanks for the note. A quick workaround would be to uncheck `Display bools as true/false` in the `appearance -> results`  preference section.

![CleanShot 2019-11-25 at 09 31 00](https://user-images.githubusercontent.com/3160528/69544538-51b33000-0f66-11ea-907a-df68e5b20289.gif)

If you get the chance, could you let me know which database server are you using?

**Comment by bpaterni** [comment]
Thanks :)

Yep, the database server is SQL Server

**Comment by hankinsoft** [comment]
Fyi the latest version of the app will now automatically use 1/0 rather than true/false when doing a copy as insert no matter what you have set for display.
