### ISSUE TITLE
Markdown Tables are broken

### ISSUE THREAD

**Issue by isaacsanders** [hankinsoft/SQLPro#329]
https://help.github.com/en/github/writing-on-github/organizing-information-with-tables

The Markdown table format (such as when copying) is currently broken.

The format linked above is correct.

**Comment by hankinsoft** [comment]
Thanks -- I'll take a look into fixing this for the next build.

Also -- test:

+----------+----------+
| ?column? | ?column? |
+----------+----------+
| hello    | world    |
+----------+----------+

**Comment by hankinsoft** [comment]
Fixed for next build (available later this week or early next). There is now two options -> `Formatted text (Monospace)` and `Formatted text (Markdown)`.

| ?column? | ?column? |
| --- | --- |
| hello | world |

**Comment by hankinsoft** [comment]
The latests update for SQLPro Studio is available via http://sqlprostudio.com/download.php and the App Store. If you get the chance, please let me know if this sorts it out for you.

**Comment by isaacsanders** [comment]
@hankinsoft The table looks correct now, thanks!
