### ISSUE TITLE
Segfault when opening/closing connection to oracle db

### ISSUE THREAD

**Issue by bpaterni** [hankinsoft/SQLPro#330]
Hi, a crash occurred when trying to open/close a connection to an Oracle db. Loading the connection in the server pane took longer than expected. So I attempted to close the connection in order to try again (probably a bad idea). This resulted in the cursor busy spinner spinning for a prolonged period of time when sqlpro was the focus. Eventually resulting in a crash and segfault:

https://pastebin.com/ibN9GSUn

**Comment by hankinsoft** [comment]
Just an FYI that I'm investigating this. Hope to have some info available early next week.

**Comment by hankinsoft** [comment]
Just to note this should be all sorted up in the latest versions. If your still having any issues, please let me know.

**Comment by bpaterni** [comment]
Hi hankinsoft, I recall there was 2 (maybe 3) automatic updates to sqlpro today. Unfortunately after the latest update (2019.64 Build 110617.5) the hang and crash did happen again. This time I did not attempt to disconnect and just let it run its course. I'll include the crash report linked below, but maybe I'm not actually on the latest version if updates take some time to propagate?

https://pastebin.com/wzAx4W2D

**Comment by hankinsoft** [comment]
Are you seeing this on the sample database connection as well? Does it crash right away, or do you get a spinning beach ball first?

**Comment by hankinsoft** [comment]
I've pushed a new version of SQLPro Studio to the App Store with some updates that will hopefully fix the oracle crash. If you get a chance, could you give it a try and let me know?

**Comment by bpaterni** [comment]
Hey Kyle, the update came through on the app store today, and the crash did occur again when attempting to open an oracle connection.

https://pastebin.com/7XgNjQxf

It doesn't crash right away, but I do get the spinning beach ball for a couple minutes before the crash.
The connection to the sample oracle db must be blocked by corporate since I'm unable to establish a connection to it.

**Comment by hankinsoft** [comment]
Can you try the latest App Store build if you get the chance? That should sort it out.

**Comment by bpaterni** [comment]
Hey Kyle, yep, I think that did it! I haven't been using oracle frequently lately, but by coincidence, I needed to use it soon after I pulled the latest update of the app. And made use of an oracle connection a couple of times after with no crashes so far!

I think it's okay to mark this issue as closed.

Thanks so much for working to fix this issue! :)
