### ISSUE TITLE
Bulk changes to multiple rows SQL Query error

### ISSUE THREAD

**Issue by michaelkirkpatrick** [hankinsoft/SQLPro#331]
When I try to update multiple rows in my database -- in this example, updating the admin flag from "1" to "0" for multiple users -- by updating the fields in the table view and then clicking "Preview and Apply" button, I get a SQL syntax error after clicking "Apply" in the "Confirm changes" window. I'm assuming because there aren't any semicolons at the end of the lines. Code below.

### Confirm changes window

UPDATE
	users
SET
	admin = '0'
WHERE
	id = '0f227c3c-e3b1-d819-c4e9-2d0115b5dee1'
LIMIT 1

UPDATE
	users
SET
	admin = '0'
WHERE
	id = '2de3635c-5f3e-b8fd-df07-ece898767f3b'
LIMIT 1

UPDATE
	users
SET
	admin = '0'
WHERE
	id = '3ab24fc1-a07d-93d2-4115-eb18f0abf39e'
LIMIT 1

### Error Message

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UPDATE
	users
SET
	admin = '0'
WHERE
	id = '2de3635c-5f3e-b8fd-df07-ece8987' at line 9`

**Comment by hankinsoft** [comment]
Sorry about that. I’ve got a fix ready for that. What app are your using and what platform (App Store, setapp, website)?

A temporary solution is to copy the query, paste it in a new query window, add semicolons after the limit 1 then run it.

**Comment by michaelkirkpatrick** [comment]
Confirmed. By adding in a semicolon after `LIMIT 1`, the query execute without issue. The automatic query generator seems to have an issue where it's not adding query delimiters.

**Comment by michaelkirkpatrick** [comment]
App Store version Version 2019.57 (Build 10482.5)

**Comment by hankinsoft** [comment]
Thanks. new build should be available by tomorrow. Sorry about that.

**Comment by michaelkirkpatrick** [comment]
No worries! Glad you're aware of the issue. Looking forward to the fix.

**Comment by hankinsoft** [comment]
This should be all sorted out in the latest builds. If you get the chance, please give it a try and let me know.

**Comment by michaelkirkpatrick** [comment]
Issue is resolved in Version 2019.63 (Build 10484.5). Thank you!
