### ISSUE TITLE
Error when creating Nullable timestamp field

### ISSUE THREAD

**Issue by jredman-prev** [hankinsoft/SQLPro#332]
When using the alter table form, if I attempt to add a timestamp column which is marked as nullable, and has a default of NULL. The command errors out with an invalid default value.

This appears to be because the SQL it attempts to run is not specifying the column as Null
see the attached screenshots.
![Screen Shot 2019-12-03 at 1 53 36 PM](https://user-images.githubusercontent.com/57718451/70081239-25d32280-15d6-11ea-99a3-9635c09272d9.png)
![Screen Shot 2019-12-03 at 1 53 47 PM](https://user-images.githubusercontent.com/57718451/70081250-28357c80-15d6-11ea-99ad-4aea988b1774.png)

**Comment by jredman-prev** [comment]
The correct sql should be
ALTER TABLE smartFlows ADD COLUMN 'KYLE_WHY?!' TIMESTAMP NULL DEFAULT NULL;

**Comment by hankinsoft** [comment]
Huh, your right. MySQL columns by default do not require NULL but for some reason TIMESTAMP columns are an edge case which do (https://stackoverflow.com/a/212947/12257392). I'll get that fixed up.

**Comment by hankinsoft** [comment]
This is fixed in the latest builds. Please give it a try if you get the chance.
