### ISSUE TITLE
Sidebar won't show

### ISSUE THREAD

**Issue by isaacsanders** [hankinsoft/SQLPro#333]
I am using Version 2019.64 (Build 110617) now, but the left sidebar has stopped working.

**Comment by hankinsoft** [comment]
What do you mean by ‘the left sidebar has stopped working’. Is it possible it has been collapsed? (See the buttons at the top right of the ui).

**Comment by isaacsanders** [comment]
I can't expand it. I try to expand it, and it starts to expand, then collapses again.

**Comment by hankinsoft** [comment]
Hmmm, very odd. A few questions if you get a chance:

1. What version of macOS are you running?
2. Are you using the top UI bar buttons to open the side bar, or dragging? (If you try the alternative option does it work)?
3. Do you happen to remember if you left the sidebar on 'database tree' or 'search mode' (the two top tab options)?
4. If you set app shutdown to 'Clean shutdown' then relaunch, does the sidebar work again?

**Comment by hankinsoft** [comment]
Hi, just wanted to check in. Did any of those option help out.

**Comment by isaacsanders** [comment]
I have been seeing this more often lately, I will circle back and answer questions for you.
