### ISSUE TITLE
Bug: Trying to indent selected text with tab sometimes overwrites with a tab

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#335]
This doesn't always happen, and I haven't picked up on the pattern yet.

Sometimes, when I select text in the query editor and hit tab (in order to tab over / increase the indent of the highlighted query), it deletes / overwrites the query and just inserts a tab. Other times, it will do what I want (increase indent).

macOS 10.15.1 (19B88)
SQLPro Studio 2019.64 (Build 110617.5)
Most recently noticed with Snowflake 3.51.1, but may be independent of connection

**Comment by hankinsoft** [comment]
I haven't been able to reproduce this --- If you see it happen could you grab the logs and post them? That should help me figure it out.

**Comment by jim256** [comment]
@hankinsoft, sure thing. Can you remind of me of where to find them again?

**Comment by hankinsoft** [comment]
Yes, you can find them by going to 'View' -> 'Logs' (sorry for the delay).

**Comment by jim256** [comment]
@hankinsoft , I thought I had a pattern figured out for it the other day, but tested it and it worked just fine the second time.

It just happened again. Here's the log file:
[com.hankinsoft.osx.sqlprostudio 2020-02-04--23-42-09-200.log](https://github.com/hankinsoft/SQLPro/files/4156769/com.hankinsoft.osx.sqlprostudio.2020-02-04--23-42-09-200.log)

**Comment by hankinsoft** [comment]
Hmmm, it looks as if autocomplete is triggering and trying (and succeeding)
to enter a completion with blank text. I'll see what I can do. Thanks for
the log!

**Comment by jim256** [comment]
@hankinsoft I'll often write a piece of code in a separate tab, refine it until it's what I want, and then copy it into a larger query as one of many CTEs.

FWIW, I just experienced this issue again (it happens extremely frequently), and I noticed that I was able to indent it just fine in the original tab where I'd written it. It was only in the tab where I'd pasted it that trying to tab it all over just wipes it all out.

**Comment by jim256** [comment]
Definitely intermittent, though. I just tried indenting the same piece of text that I first did, after repasting (from the same source) and it worked. Both times it was from another SQLPro Studio tab. The first time (when it didn't work) was with 0 initial indentation from the source tab. The second time (when it did work) was with 1 tab of initial indentation from the source tab. Not sure if that has anything to do with it.

Another log attached.
[com.hankinsoft.osx.sqlprostudio 2020-02-17--23-51-24-478.log](https://github.com/hankinsoft/SQLPro/files/4216740/com.hankinsoft.osx.sqlprostudio.2020-02-17--23-51-24-478.log)

**Comment by hankinsoft** [comment]
Can you reproduce with this build:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.12.app.zip

I've added additional logging for failure states.

Is it possible that you have a key other than shift pressed down when hitting tab? Such as ctrl, or cmd? That would cause the indentation to fail.

**Comment by jim256** [comment]
@hankinsoft it's happening with 2020.14 (Build 110641). Does that also have the additional logging for failure states? Or should I try specifically with the one above?

I am certain that I am pressing only the tab key in these instances.

**Comment by hankinsoft** [comment]
Yep please for logs from 2020.14!

**Comment by jim256** [comment]
@hankinsoft here you are good sir
[com.hankinsoft.osx.sqlprostudio 2020-02-28--23-10-20-778.log](https://github.com/hankinsoft/SQLPro/files/4269525/com.hankinsoft.osx.sqlprostudio.2020-02-28--23-10-20-778.log)

**Comment by hankinsoft** [comment]
Thanks!
I just have my phone at the moment but I see that the app seems to think
either another key is down or some other keyboard state has happened.


Once I’m back on my computer I’ll lookup the 65536 and try to figure out
what’s going on.

**Comment by hankinsoft** [comment]
It looks like cap locks is on which is causing the 65536 flag. I'll add code to ignore cap locks which should fix it!

**Comment by hankinsoft** [comment]
FYI that build also has the extra logging for https://github.com/hankinsoft/SQLPro/issues/346.

**Comment by jim256** [comment]
@hankinsoft ah that makes sense! Glad we found the problem 💪 
Ok great. That quotes issue happened again today a bunch of times. I’ll be sure to capture a log for it and send it your way Monday.

**Comment by jim256** [comment]
@hankinsoft seems to be resolved with the latest build! Thanks so much 😄
