### ISSUE TITLE
csv file failing to import after latest update

### ISSUE THREAD

**Issue by fionalindberg** [hankinsoft/SQLPro#336]
version: Version 2019.64 (Build 10500.5)

Every week for several years I've imported ecommerce .csv files from one of our partners into SQL Server via your import from CSV option. Works like a charm. This week the files failed, see screenshot. To eliminate that is was the partner files changing, I went back to the previous week and attempted to reimport them and I have the same failure. I can't see in preferences any settings that would have changed for file processing. Any help is appreciated.

![Import failed](https://user-images.githubusercontent.com/55409441/70287434-e3a80d80-179c-11ea-9113-d91db8426205.png)

**Comment by hankinsoft** [comment]
Just as an fyi the latest build should sort this out. Please give it a try if you get the chance.

**Comment by fionalindberg** [comment]
Thanks Kyle,

Will do. Monday will be the next time I pull the transaction file and
import so I'll let you know if there are any issues but I'm confident there
won't be.

Best regards,

**Comment by fionalindberg** [comment]
Kyle,

I meant to circle back with you and it got away from me. Yep, build 70
restored the csv import functionality. Thanks a million.
