### ISSUE TITLE
Postgres foreign tables are inaccessible

### ISSUE THREAD

**Issue by heruan** [hankinsoft/SQLPro#337]
Working on a Postgres database with foreign tables isn't currently possible as foreign tables are not visible. I'd expect to find them inside a "Foreign Tables" folder, as of "Views" and "Materialized Views".

**Comment by hankinsoft** [comment]
Working on this for the next build.

**Comment by hankinsoft** [comment]
Quick question if you get the chance -- there are beginning to be quite a few nodes in the postgres database tree for all the different types of tables, views, etc. Would it make sense to remove all these separate nodes and just have one 'tables/views' node which would display the object type underneath the table/view/etc name? Similar to how columns show the data types underneath the column name?

**Comment by heruan** [comment]
The current layout it's tidy (database > schema > tables/views/etc), but maybe if you make it an option in the `View` menu some other users might like it better.

**Comment by hankinsoft** [comment]
Could you give this build a try? https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.67.app.zip

That should add the foreign tables and allow you to view the columns, double click to select, etc.

**Comment by heruan** [comment]
It works smoothly!

**Comment by hankinsoft** [comment]
Great, I will get this submitted to the App Store as well. Thanks for
letting me know.

**Comment by hankinsoft** [comment]
This is now available via the Mac app store.
