### ISSUE TITLE
Feature : Allow add column comment

### ISSUE THREAD

**Issue by iiinsomnia** [hankinsoft/SQLPro#338]

**Comment by hankinsoft** [comment]
What type of database?

**Comment by iiinsomnia** [comment]
mysql

**Comment by hankinsoft** [comment]
I'll have this available for the next version:

<img width="1162" alt="Screen Shot 2019-12-10 at 3 12 30 PM" src="https://user-images.githubusercontent.com/3160528/70560732-8080f700-1b5f-11ea-9d96-d273adbc530e.png">
