### ISSUE TITLE
Invalid button

### ISSUE THREAD

**Issue by iiinsomnia** [hankinsoft/SQLPro#339]
![image](https://user-images.githubusercontent.com/6582246/70518586-94cfee80-1b75-11ea-8a58-6dca9cf2017d.png)

**Comment by hankinsoft** [comment]
Hi. The button is currently there so that the UI looks more similar to Xcode. It does currently not function, but I do have plans for it in the future.

**Comment by iiinsomnia** [comment]
suggest for table DDL
