### ISSUE TITLE
Feature : Allow add table DDL view

### ISSUE THREAD

**Issue by iiinsomnia** [hankinsoft/SQLPro#340]

**Comment by hankinsoft** [comment]
You can see the DDL of a table in one of two ways:

1. Right click the table in the database tree and choose 'Script as' -> 'Create to' -> 'New tab'.
2. Right click on the table in the query editor and choose 'Script as' -> 'Create statement'.

![CleanShot 2019-12-10 at 08 49 41](https://user-images.githubusercontent.com/3160528/70530900-40535180-1b2a-11ea-8a3e-50c382fde301.gif)
