### ISSUE TITLE
SQLite: New tables don’t save

### ISSUE THREAD

**Issue by bedchr** [hankinsoft/SQLPro#341]
I created a new SQLite database using SQLProforSQLite and then parsed data into it. Database opens fine and no issues. I update the data and query away and no issues. The moment I go to import a CSV it imports but once it’s done I wait a little bit to close it. When I reopen it nothing saves and the CSV I imported is not there. Without the CSV part I still get the file malformation errors. Running the latest version of program and on Mac OS X Catalina.

**Comment by hankinsoft** [comment]
FYI im investigating this issue. As a workaround, I would suggest manually saving via CMD-S.

**Comment by hankinsoft** [comment]
Just to note, I believe this is all sorted in the latest version (has been for a bit, but I forgot to update this issue). If you get a chance to give it a try, please let me know.
