### ISSUE TITLE
Bug: When deleting a row, the wrong row is removed from the list.

### ISSUE THREAD

**Issue by jamesalanfinnigan** [hankinsoft/SQLPro#342]
Right click on a row and choose the delete selected row.  The SQL command will appear and press ok.  The correct row (id) is deleted but the list still shows the deleted item.

**Comment by hankinsoft** [comment]
Could you reproduce this and post a log file? You can find the log by going to 'View' -> 'Logs'.

**Comment by hankinsoft** [comment]
I’ve made some changes around this for the latest build. If you get the chance, could you give it a try?
