### ISSUE TITLE
Bug: Open File... Cmd-O no longer works on 2019.54

### ISSUE THREAD

**Issue by rjenningsnypr** [hankinsoft/SQLPro#344]
- SQLPro for MSSQL:
- Hitting cmd-O or using the menu produces no file dialog window to pick a file. Open Recent works so if you're in a bind (and I was today!) you have to rename the file you want to open to one that was opened recently.
- SQL color highlighting seems to be gone.

- MacOS 10.14.6

**Comment by hankinsoft** [comment]
What version are you using? Could you post a screenshot of the about dialog?

**Comment by rjenningsnypr** [comment]
I said in the title: 2019.54 (it's also "Build 10486")

There is no screenshot to be had because doing File...Open produces NO such dialog window to let you select a file to open. It just returns. The "File" menu highlights for a brief moment and that's all there is.

Would it be possible to get the previous version somewhere? This is a show stopper for me at work.

If I can find my license key I can try to test this on a MacOS 10.15 and see if there is any difference but we need to stay on 10.14 for the time being (for compatibility with other 32 bit apps.)

**Comment by rjenningsnypr** [comment]
![Screen Shot 2019-12-16 at 5 23 52 PM](https://user-images.githubusercontent.com/36858227/71415974-731e3f00-262c-11ea-8aec-8ba81b3f5ff5.png)

But here's a shot not showing the SQL syntax highlighting

**Comment by rjenningsnypr** [comment]
![Screen Shot 2019-12-24 at 9 03 57 AM](https://user-images.githubusercontent.com/36858227/71416021-a8c32800-262c-11ea-83a3-95a665e0cd40.png)
Here's a screen shot where it's not showing the SQL syntax highlighting.

**Comment by hankinsoft** [comment]
Can you grab https://www.macsqlclient.com/download.php? That should fix the CMD-O issue. Per syntax highlighting, how large is the file you are opening? Syntax highlighting disables automatically on larger files in order to preserve performance.

**Comment by rjenningsnypr** [comment]
Thanks - CMD-O works. My sql files can get fairly large and that appears to be the problem with the highlighting not working.
