### ISSUE TITLE
Bug: Autocomplete Column Names Inserts Quotes

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#346]
Often when I let autocomplete finish a column name for me, it inserts double quotes around the column name. At first, I thought this would maybe be only for column names that were also reserved words or something like that, but it does it for all column names.

I haven't been able to determine a pattern for when its does / doesn't yet, though.

I think I noticed this as of once build prior to the one I'm on.

SQLPro Studio 2019.70 (Build 110624.5)
macOS 10.15.1 (19B88)
Snowflake 3.54.4

**Comment by jim256** [comment]
@hankinsoft just wanted to make sure this got seen.

I'll capture logs the next time it happens.

For what it's worth, sometimes it'll start happening very consistently, again and again and will be resolved (temporarily) via fully quitting and restarting the app.

Still happening with:
SQLPro Studio 2020.01 (Build 110625.5)
macOS 10.15.2 (19C57)
Snowflake 4.2.1

**Comment by hankinsoft** [comment]
Hi! For escaping table paths in snowflake I use the following regex:

[^a-z_0-9]+    (non case sensitive).

So basically if your table contains anything other than a-z, 0-9 or an underscore it will be escaped. Do you have tables outside of this being escaped? Can you give me an example of the table name which you are seeing escaped?

Thanks!

**Comment by jim256** [comment]
I appreciate your quick explanation!

Yes, it seems to happen with any / every table (products, market_orders, order_items, etc.) until I restart the app.

**Comment by jim256** [comment]
@hankinsoft I realized I forgot to tag you in my last reply, so I'm commenting again to make sure this got seen

**Comment by hankinsoft** [comment]
For the next version I added extra logging in the snowflake escape code. Once you get 2020.10 (hopefully later today or tomorrow) please provide me with the log file once you see the issue occur.

**Comment by jim256** [comment]
@hankinsoft was just able to capture it.

Before tab to autocomplete:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/15026225/75699559-e6b47c00-5c6d-11ea-8a27-fedffb6dc0b6.png">

After tab tp autocomplete:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/15026225/75699575-ed42f380-5c6d-11ea-8a67-f7639054ee3f.png">

Log:
[com.hankinsoft.osx.sqlprostudio 2020-03-02--17-07-15-156.log](https://github.com/hankinsoft/SQLPro/files/4276773/com.hankinsoft.osx.sqlprostudio.2020-03-02--17-07-15-156.log)

**Comment by hankinsoft** [comment]
Thank you - fixed for the next build.

**Comment by jim256** [comment]
@hankinsoft awesome! That will be nice. Thank you so much.

**Comment by jim256** [comment]
@hankinsoft haven't seen this in the new build. I think we can probably close it out! Thank you. Super nice to be able to fully use autocomplete again.
