### ISSUE TITLE
Customizing toolbar does not stick between sessions

### ISSUE THREAD

**Issue by tsuliwaensis** [hankinsoft/SQLPro#347]
When customizing the toolbar on SQLPro for SQLite, the changes revert after closing the app.

**Comment by hankinsoft** [comment]
I'm not sure what you mean? SQLPro for SQLite does not offer an option to customize the toolbar?

**Comment by tsuliwaensis** [comment]
The option that appears when you right-click on the toolbar.

<img width="860" alt="Screen Shot 2020-01-15 at 7 46 10 PM" src="https://user-images.githubusercontent.com/40817465/72493467-bceee500-37e6-11ea-90f5-8da53fd4bc13.png">

<img width="610" alt="Screen Shot 2020-01-15 at 7 46 27 PM" src="https://user-images.githubusercontent.com/40817465/72493471-c0826c00-37e6-11ea-9b44-c64a6a096278.png">

**Comment by hankinsoft** [comment]
Are you using SQLPro for SQLite from the website, or App Store? I've got a fixed build on the website that I think will sort this.

**Comment by tsuliwaensis** [comment]
I have the App Store version.

**Comment by hankinsoft** [comment]
New version is online which should sort this out. Please let me know if you get the chance.

**Comment by tsuliwaensis** [comment]
It works now. Thank you!
