### ISSUE TITLE
Background color cannot be set to white

### ISSUE THREAD

**Issue by yoktan** [hankinsoft/SQLPro#348]
Version 2019.70 (Build 10502)

Suddenly after updating my Preferences, the background color of my windows are all set to a color even if my Preferences > Appearance > Query Editor > Background = White 

This may seem trivial but it's really making it hard to work with the app!

I've failed to solve the issue by:
- Installing the latest build
- Resetting Preferences to deafaults
- Trashing ~/Library/Preferences/com.hankinsoft.osx.tinysqlstudio.plist
- Connecting to the test connection (Adventure Works)

Screenshots showing the issue:
[Window](http://yoktan.com/SQL1.png)
[Prefs](http://yoktan.com/SQL2.png)

**Comment by hankinsoft** [comment]
Hi,
Can you set your `Query Execution Style` to be disabled? See https://github.com/hankinsoft/SQLPro/wiki/Execute-query-in-cursor-range.

**Comment by yoktan** [comment]
That solved it :)
I also noticed that the Query Execution prefs changed recently. The old pref of having the option of disabling execution of the entire tab was super useful to avoid executing multiple queries (I'm careful, but this has happened to me before and when it does, it's usually trouble).
