### ISSUE TITLE
Recurring Intermittent Error: Write to the server failed.

### ISSUE THREAD

**Issue by yoktan** [hankinsoft/SQLPro#349]
Version 2019.70 (Build 10502)
Connection to Microsoft SQL Azure (RTM) - 12.0.2000.8

I regularly (like maybe once out of 20 queries) get the following error:

**Msg 20006, Level 9, State 0.
Write to the server failed.**

From what I read this is supposed to mean that the server is unavailable… But I'm obviously connected to it, and if I re-execute the query, it goes through (usually on the first try, but sometimes I need to try 2 times, and more rarely: 3 times).

Also, a colleague of mine using a Microsoft client doesn't encounter this issue as often: maybe once a week… (note: he is on a different network). 

Is it possible this is a bug or that there's something I can do to improve the reliability of the connection?

**Comment by hankinsoft** [comment]
The next time you run into this, could you send me the log file? You can find it by going to 'View' -> 'Logs' from within the app. You can post the log file here, or email it directly to me via kyle @ hankinsoft.com. If you email it, please reference this issue.

**Comment by hankinsoft** [comment]
Do you have the app installed from the Mac app store, or via the website? Would you be able to test a build if I provide it outside of the Mac app store?

**Comment by yoktan** [comment]
I **believe** I installed directly from the website. In any case, yes, I can install a build from you.
Thanks

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.09.app.zip?

**Comment by yoktan** [comment]
Thanks Kyle. Problem gone. Note: 
1. You sent me a Trial version
2. It did crash on me in the middle of me just writing a query (but I was using text shortcuts, so maybe that cause it) — sorry, no log.
Cheers

**Comment by hankinsoft** [comment]
Hi,

> 1. You sent me a Trial version

You must have installed from the App Store then - If you had a website license key entered, this would have not appeared as a trial but simply registered using the license key you had previously entered. The App Store version is also available.   (Or the second possibility is that you were using/purchased SQLPro for MSSQL? If thats the case, let me know).

> 2. It did crash...

I've identified a crash with that build and will have the fix available shortly.

**Comment by yoktan** [comment]
Thanks Kyle. Yes, I don't have a license for Studio, I have one for SQLPro for MSSQL.
Cheers

**Comment by hankinsoft** [comment]
Ah, sorry about that. SQLPro for MSSQL build is available here: https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.2020.14.app.zip

That should also sort any crashes when typing a query.

**Comment by hankinsoft** [comment]
If your still having any issues, please let me know.
