### ISSUE TITLE
Connection refresh does not work with Postgres

### ISSUE THREAD

**Issue by rodriguise** [hankinsoft/SQLPro#350]
macOS Version: 10.15.2 (19C57)
App Version: Version 2020.01 (Build 110625.5)

This pertains to Postgres. 

When making changes at the root of a connection (i.e. Create Database), clicking `Refresh` from the mouse menu only collapses the container for that connection, the database list is not refreshed. I have to disconnect and reconnect to see the new database.

**Comment by hankinsoft** [comment]
Thanks for the note on this. I believe I've got it sorted for the next build which should be available next week.

**Comment by hankinsoft** [comment]
Can you try this build and see if it helps to sort it out:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.02.app.zip

**Comment by rodriguise** [comment]
Works great! Thank youa and looking forward to the update

**Comment by hankinsoft** [comment]
This fix is now available via both the website and App Store.
