### ISSUE TITLE
Can't save document - MacOS greater than Mojave

### ISSUE THREAD

**Issue by yoktan** [hankinsoft/SQLPro#351]
Version 2019.70 (Build 10502)

Hi,

I regularly get the following error after SQL Pro has been open for a while (a few days): 

**The document “XXXX.sql” could not be saved. You don’t have permission.**

This error goes away if I restart the app…

A similar error was reported in the past https://github.com/hankinsoft/SQLPro/issues/99
But it was supposed to be fixed for newer versions of Mac OS. My OS is way past Mojave; I'm on  10.13.6 and I still get the error.

If I try a Save As — the error becomes that I don't have perms to write to the directory (even though it's like any other directory's perms) BUT I CAN write to the directory if I restart the app.

And if I pick the "Duplicate" file option, that just crashes the app…

**Comment by hankinsoft** [comment]
Hi,
Unfortunately 10.13.6 is actually older than Mojave (Mojave is macOS 10.14). Unfortunately you will continue to see this issue until upgrading to a newer OS. Sorry about that :(
