### ISSUE TITLE
Can't delete Postgres procedure

### ISSUE THREAD

**Issue by doerwalter** [hankinsoft/SQLPro#352]
I've created two overloaded procedures in Postgres:

```sql
create schema sqlprobug;

create procedure sqlprobug.foo() language plpgsql as $$ begin null; end; $$;

create procedure sqlprobug.foo(x integer) language plpgsql as $$ begin null; end; $$;
```

When I try to delete the second one from SQLProStudio I get the error "ERROR:  sqlprobug.foo(integer) is not a function"

Versions are:

SQLProStudio: Version 2019.64 (Build 110617)
macOS: 10.15.2 (19C57)
Postgres.app: Version 2.3.3e (68)

**Comment by doerwalter** [comment]
Note that the following SQL code works as expected:

```sql
drop procedure sqlprobug.foo(x integer);
```

**Comment by hankinsoft** [comment]
Thanks, I've reproduced this. Hope to have a fix available early next week.

**Comment by hankinsoft** [comment]
You may need to refresh the 'functions' node before it works (if you have app state saving turned on) as new tree information is needed from the database.

**Comment by doerwalter** [comment]
My trial version timed out, so I can no longer test this.

**Comment by hankinsoft** [comment]
Sorry, I notice I forgot to post the fixed build to you. Its available here: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.02.app.zip. That build should sort the issue.

**Comment by hankinsoft** [comment]
(And it will also reset your trial for another 7 days).

**Comment by doerwalter** [comment]
Deleting procedures now works, however the dialog still states:
```
Do you really want to drop the function 'foo'?
Once a function has been removed, it cannot be recovered.
```

I wonder if this should use "procedure" instead of "function".

**Comment by hankinsoft** [comment]
Good point! I'll have a fix available hopefully later today.

**Comment by hankinsoft** [comment]
The fix is now available in the latest update (available via the website and the App Store). Please give it a try if you get the chance.

**Comment by doerwalter** [comment]
My trial version has expired again, so I can't try this out.

**Comment by hankinsoft** [comment]
Hi,
Each time there is a new version available the trial automatically renews. The latest version is at https://sqlprostudio.com/download.php

**Comment by doerwalter** [comment]
OK, thanks. Now the dialog uses "Procedure" instead of "function". However IMHO the word "procedure" should be lowercased, i.e.

```
Do you really want to drop the procedure 'foo'?
```

instead of

```
Do you really want to drop the Procedure 'foo'?
```

**Comment by hankinsoft** [comment]
Thanks! I've been having that debate with someone else as well. Haven't decided on the if I will use capitals or not as of yet. For the moment I'm going to leave it as is.
