### ISSUE TITLE
Too many open connections - Postgres

### ISSUE THREAD

**Issue by sariabod** [hankinsoft/SQLPro#353]
I just noticed that when you open a tab and run a query then then close the tab it does not kill the connection. After a bit of time doing things to the database this adds up. At one point I could see almost 50 connections being taken up despite not having any tabs open. I had to completely exit the app to finally remove them. Is there a setting to reuse connections instead of creating a new one every time or at least kill the connection when the tab is closed?

SQLPro Studio - Version 2020.01 (Build 110625.5)
MacOS - 10.15.1 (19B2106)
PostgreSQL - 11.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit

**Comment by hankinsoft** [comment]
I'm working on a fix for the next build. It should be available early next week.

**Comment by hankinsoft** [comment]
Can you try this build and see if it helps sort it out?
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.02.app.zip

**Comment by sariabod** [comment]
So far so good. I opened a bunch of connections and could see each connection increase by one with each tab. As I went in reverse and closed the tabs, the connections dropped accordingly. Thanks for quick fix!

**Comment by hankinsoft** [comment]
No problem! FYI the fix is now available via both the App Store and website.

**Comment by iredmedia** [comment]
didn't want to create a new issue, but was curious what the connection logic is? I opened SQLPro today and my connections spiked, I had a lot of tabs open but have never had trouble until this week.
