### ISSUE TITLE
SQLPro for Oracle end-of-file error

### ISSUE THREAD

**Issue by jngk2** [hankinsoft/SQLPro#354]
Hi,

This is a valid PL/SQL query. The DECLARE section causes an error.

![image](https://user-images.githubusercontent.com/43384793/73258842-745c0200-41be-11ea-9a22-5031976318b0.png)

Does SQLPro for Oracle not support PL/SQL?

Thanks!
J

**Comment by hankinsoft** [comment]
Unfortunately PL/SQL support is not 100%. I'll have to investigate this.

**Comment by hankinsoft** [comment]
Hi -- would this be the same issue as #271?

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.23.app.zip and see if that does the trick?

**Comment by hankinsoft** [comment]
Closing as a duplicate of #271.
