### ISSUE TITLE
Group Child Tables under Parent Table

### ISSUE THREAD

**Issue by isaacsanders** [hankinsoft/SQLPro#355]
We use daily partitioning in our database, so it can be difficult to navigate our data in SQLPro as is. It would be more ideal to me that the parent tables could have the child tables nested inside rather than as siblings in the sidebar UI.

**Comment by hankinsoft** [comment]
This is with PostgreSQL? (I've not used child tables so I'm just trying to figure it out)

**Comment by isaacsanders** [comment]
Yeah! One way to implement time-based partitioning in Postgres is with table inheritance.

**Comment by hankinsoft** [comment]
If you get the chance, could you let me know if this query runs successfully for you?

```
SELECT 
    table_schema, 
    table_name,
    (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid,
    (SELECT inhparent FROM pg_inherits WHERE inhrelid = (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid) AS parentOID
FROM 
    information_schema.tables 
WHERE 
    table_type LIKE '%TABLE%' 
    AND table_catalog != 'postgres ' 
    AND table_schema NOT IN (
        'information_schema', 'pg_catalog'
    )
    
UNION 
SELECT 
    table_schema, 
    table_name,
    (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid,
    (SELECT inhparent FROM pg_inherits WHERE inhrelid = (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid) AS parentOID
FROM 
    information_schema.tables 
WHERE 
    table_type LIKE '%TABLE%' 
    AND table_catalog = 'postgres' 
    
ORDER BY 
    table_schema, 
    table_name;
```

**Comment by isaacsanders** [comment]
:+1:

**Comment by hankinsoft** [comment]
So you would want to see something like the following?

<img width="1697" alt="Screen Shot 2020-01-29 at 1 03 04 PM" src="https://user-images.githubusercontent.com/3160528/73378926-c1f86d80-4297-11ea-9eee-b50148ad946f.png">

(`government_invoices` inherits from `invoices` -> creation query is shown in the query editor).

**Comment by isaacsanders** [comment]
Maybe something under a "Child Tables" folder, but that's the right idea!

**Comment by hankinsoft** [comment]
> Maybe something under a "Child Tables" folder, but that's the right idea!

I think I'm going to skip the 'Child Tables' folder for now for a few reasons:

1. I think inherited tables will be fairly uncommon, so having 'Child Tables' folder would be unused 90%.

2. Not sure if I will get any pushback from removing the inherited tables from the outer 'Tables' node... but if I do, I think having to drill down even one node further would make the pushback worse.

Not saying its not a possibility in the future, but for now I'll be pushing the build like this and seeing if/what feedback I get on it.

Can/are you able to test a beta build if I upload it later today?

**Comment by isaacsanders** [comment]
Yup!

**Comment by hankinsoft** [comment]
Can you try this build please:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.02.app.zip

**Comment by isaacsanders** [comment]
I think if you would list partitions after columns and indexes and triggers., that would work for me. We have a couple hundred partitions for most of our tables, so the UI gets a little cluttered for me.

Seeing indexes and triggers as folders, it inclines me more toward the extra folder, as it might be more or less common than triggers.

I understand that you will have pushback, though.

**Comment by hankinsoft** [comment]
Ohhhhhh, you have a couple hundred inherited tables? I can see why you might want a folder then. I'll add it.

**Comment by hankinsoft** [comment]
Can you try this build if you get the chance:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.03.app.zip

This also has my first attempt at fixing https://github.com/hankinsoft/SQLPro/issues/334. Please let me know if you run into any issues, or if this helps to sort the issue.

**Comment by hankinsoft** [comment]
Just wanted to check if this helped out? Its also avaialble in the latest update (available via the website and the App Store). Please give it a try if you get the chance.

**Comment by isaacsanders** [comment]
Hey! Sorry for my lack of reply. Things got hectic. I will reply when I’m at my desk later this morning.
