### ISSUE TITLE
Missing "run selected query"

### ISSUE THREAD

**Issue by fulldecent** [hankinsoft/SQLPro#356]
You can run all queries but you can not run just one query.

<img width="1080" alt="Screen Shot 2020-01-30 at 09 41 01" src="https://user-images.githubusercontent.com/382183/73459339-b020d400-4344-11ea-9a18-ddde5321ea5c.png">

**Comment by hankinsoft** [comment]
There is a preference for this. See https://github.com/hankinsoft/SQLPro/wiki/Execute-query-in-cursor-range
