### ISSUE TITLE
Better tab titles

### ISSUE THREAD

**Issue by doerwalter** [hankinsoft/SQLPro#358]
It seems that for Postgres connections currently the only tab that gets a reasonable title is the tab I get when I double click a table or when I select "Alter table" from the right-click popup on a table (probably because of #265).

However when I double click on anything else (a view, a function, a sequence, etc.) the tab title simply displays "Untitled 16.sql". This makes it hard to keep an overview of which tabs I've got open.

Also the tab title should contain the type of object (i.e not just "foo", but "function foo" or similar). Also the titles should always display the schema name (i.e. "function bar.foo" would be best).

**Comment by hankinsoft** [comment]
Sorry for the delay in response!

I'm working on the first part:

> However when I double click on anything else (a view, a function, a sequence, etc.) the tab title simply displays "Untitled 16.sql". This makes it hard to keep an overview of which tabs I've got open.

For the next build. Once thats been added I'll investigate adding the object type.

**Comment by hankinsoft** [comment]
As of the next build, tabs can also now be manually renamed.
![CleanShot 2020-05-21 at 10 07 07](https://user-images.githubusercontent.com/3160528/82564191-b97db880-9b4e-11ea-8a74-5c2ac83e2861.gif)

I don't currently plan on adding the object type to the tab title unless I receive more requests for that. Once the rename tab item has been rolled out to all versions of the app, I will consider this item closed unless any additional issues are found.
