### ISSUE TITLE
Bug: Drop View Tries to Use Drop Table Syntax

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#359]
If I right-click on a view and click "Drop Table" (there is no "Drop View") then it tries to use the "DROP TABLE [table_name]..." syntax and fails.

SQLPro Studio 2020.01 (Build 110625.5)
macOS 10.15.2 (19C57)
Snowflake 4.2.2

**Comment by hankinsoft** [comment]
Fixed for the next build (late this week or early next week).

**Comment by hankinsoft** [comment]
This should be fixed in the latest update (available via the website and the App Store). Please give it a try if you get the chance.
