### ISSUE TITLE
Cannot export to SQLite 2 format

### ISSUE THREAD

**Issue by Pondus59** [hankinsoft/SQLPro#360]
HI, when I try to export from SQLPro for SQLite in SQLite 2 format, it does not create a file. There are no error messages. I can expert to MySQL though. What could be wrong?

**Comment by hankinsoft** [comment]
I think I've reproduce this. Do you have SQLPro for SQLite installed via the App Store, Setapp or Website?

**Comment by Pondus59** [comment]
It was through the App Store

**Comment by Pondus59** [comment]
While I have you, just a brief note on error messages: When I was building the database, I got a few helpfull error messages along the way. However, they were only on screen so briefly that I had to make a recording of the screen to be able to go back and see what they actually said. Perhaps something the could be fixed in the future ;-)

**Comment by hankinsoft** [comment]
Do you have any of those recordings? I'm not exactly sure what you mean, so those should help.

**Comment by Pondus59** [comment]
I will make som for you later. For now, the most important thing for me is to find a way of fixing the data export issue

**Comment by hankinsoft** [comment]
New version is up on the App Store. Please give it a try and see if that sorts the issue out.

**Comment by Pondus59** [comment]
Thanks, But It does not appear under updates in my App Store, so how do I get the update?

**Comment by Pondus59** [comment]
OK, new version available now (Thanks!) and I uploaded it. Export works fine, but program crashes as soon as the export is done. 
[Error repport.docx](https://github.com/hankinsoft/SQLPro/files/4169754/Error.repport.docx)

**Comment by hankinsoft** [comment]
Thanks - I think I've got this fixed for the next build (I wasn't able to reproduce, but I THINK I saw whats going on). I've also added a progress dialog for the export. It will be available early next week.

**Comment by hankinsoft** [comment]
Should be all better in the latest build (2020.09). Please give it a try and let me know if that sorts it for you.
