### ISSUE TITLE
Enhancement Request / Bug: Beautify Inserts Blank Space After Each Line

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#362]
Each time the beautify command is used, it inserts a blank space at the end of every line. It would be great to not have those spaces there.

SQLPro Studio 2020.01 (Build 110625.5)
macOS 10.15.3 (19D76)
Snowflake 4.2.2, PostgreSQL 10.9, etc.
(I've noticed this since I started using the product but just hadn't reported it - so I don't think it's related to a particular data source (version))

**Comment by hankinsoft** [comment]
Hmmm, screenshot of what you mean? 😁

**Comment by jim256** [comment]
@hankinsoft 
Before "Beautify":
<img width="123" alt="image" src="https://user-images.githubusercontent.com/15026225/74052565-644eda00-4997-11ea-9a00-89f93eb7d7a1.png">


After "Beautify":
<img width="130" alt="image" src="https://user-images.githubusercontent.com/15026225/74052581-6dd84200-4997-11ea-82f3-97cdbc8452a4.png">


It just literally inserts a single blank space character at the end of each line (except for the very last line, I think).

**Comment by hankinsoft** [comment]
Ahhhh ok. I’ll get that fixed.

**Comment by hankinsoft** [comment]
This should be fixed in the latest update (available via the website and the App Store). Please give it a try if you get the chance.

**Comment by jim256** [comment]
Seems to be taken care of! 💪 Thanks a lot
