### ISSUE TITLE
Regression: navigation between tabs loses my draft query

### ISSUE THREAD

**Issue by Clarko** [hankinsoft/SQLPro#363]
I often cross-reference different tables' schema & data when I'm writing a query. In earlier versions of SQLPro that was OK and I didn't lose my half-written query, but the most recent update (2020.06) has made it destructive. Repro steps:

1. Start writing in the Query tab
2. Partway through, navigate to the Schema tab or Data tab
3. Navigate back to the Query tab

If I execute the query it is saved. Unexecuted queries are not saved. But I can't run a half-written _destructive_ query just to force the app to remember it.

**Comment by hankinsoft** [comment]
Sorry about that! I've got a fix for this submitted. It should be available within ~24 hours.

**Comment by hankinsoft** [comment]
Latest build is available and should short this out. Version should be 2020.09. Please give it a try if you get the chance.

**Comment by Clarko** [comment]
Thank you!
