### ISSUE TITLE
Add Support for adding connections via a Postgres URI

### ISSUE THREAD

**Issue by lifeiscontent** [hankinsoft/SQLPro#364]
e.g. `postgres://user:pass@host:port/database` should work when pasting into Sever host.

**Comment by hankinsoft** [comment]
Working on adding this for the next build.

**Comment by hankinsoft** [comment]
![CleanShot 2020-02-13 at 10 02 50](https://user-images.githubusercontent.com/3160528/74442545-0ebb7700-4e48-11ea-9baa-147d74f95ff8.gif)

Ready for the next build. When you post a URI into the host field it will get the user/password, host port and database (for whichever values are specified).

**Comment by hankinsoft** [comment]
Are you using SQLPro Studio or SQLPro for Postgres?

**Comment by hankinsoft** [comment]
This is available in the latest versions. If you have any issues with it, please let me know.

**Comment by lifeiscontent** [comment]
@hankinsoft I'm using SQLPro for Postgres, have yet to test it. will do today! Thank you for the quick turnaround! It was a nice surprise 😅
