### ISSUE TITLE
License Activation Issue

### ISSUE THREAD

**Issue by bedchr** [hankinsoft/SQLPro#365]
Hi,
I purchased SQLPro For SQLite in August 2019 and after the update the other day I am now being asked to  activate my license. I purchased this through iTunes. Do I now have to switch to a subscription in order to continue to use this?

**Comment by hankinsoft** [comment]
Hi,
It sounds like you might have the website version downloaded? The App Store
version of SQLPro for SQLite should never request a license key. Can you
try deleting your copy and reinstalling it from the App Store? If you are
still being promoted can you send a screenshot of what exactly you are
seeing?

**Comment by bedchr** [comment]
I just removed it and reinstalled it from the App Store. It opens fine but when I query the data, these  slanted grey bars cover the results. It happens on all my SQLite databases,  not just the test one I’m uploading now.
<img width="1543" alt="02494CEE-C700-423F-95E9-D61247C56659" src="https://user-images.githubusercontent.com/31600707/74457839-ceafc080-4e56-11ea-8e34-38d51d5f980f.png">

**Comment by hankinsoft** [comment]
Hmmm, thats very odd. Could you post a screenshot from the about dialog
(SQLPro for SQLite -> About)? When you hit activate what do you see?

**Comment by bedchr** [comment]
Here’s the about screen the activate screen.
<img width="469" alt="31247CFD-8C78-4C2A-98C7-62984F9F346B" src="https://user-images.githubusercontent.com/31600707/74459207-ec7e2500-4e58-11ea-9ad5-4a16fc02e218.png">
<img width="636" alt="B65AD6D4-724A-43B7-A2C4-F3E4E4FA5F5B" src="https://user-images.githubusercontent.com/31600707/74459208-ec7e2500-4e58-11ea-829e-e2b4dc16f6fd.png">
<img width="623" alt="DF60CE55-4B77-4F99-AB65-A8EA50BC24B0" src="https://user-images.githubusercontent.com/31600707/74459210-ed16bb80-4e58-11ea-99e8-cecadd737f01.png">

**Comment by hankinsoft** [comment]
Thanks. I think I see whats going on - I've submitted a new build to Apple
which generally takes ~24 hours or so to activate. Please feel free to
reach out to me via kyle @ hankinsoft.com and I can provide you with a
license key to use on the website version (https://sqlitepro.com).
Unfortunately the store version does not accept license keys.

**Comment by bedchr** [comment]
Thank you!

**Comment by hankinsoft** [comment]
The update is now available (2020.10). If you get the chance, can you give it a try? Thank you, and again sorry for the issue!

**Comment by bedchr** [comment]
Hi
Still getting the activation screen issue.

**Comment by bedchr** [comment]
I even tried uninstalling then restarting and reinstalling it.

**Comment by hankinsoft** [comment]
A second update is now available (2020.11) that should sort it. Sorry for the issue!

**Comment by bedchr** [comment]
The second one worked. The activation screen no longer appears. Thank you for your help and quick response!

**Comment by hankinsoft** [comment]
No problem! Sorry about that.

**Comment by pempempempem** [comment]
Hi I get this issue all the time whenever my subscription gets updated

**Comment by dr-ranjitha** [comment]
I had the same issue @bedchr mentioned. "bedchr commented on Feb 13" 

The solution provided by @hankinsoft "hankinsoft commented on Feb 13" worked. Thanks.
