### ISSUE TITLE
Save (⌘ + S) always opens Save Dialog 

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#366]
Steps to reproduce:

1.  Write some SQL
2.  Save it (e.g. as "important_query.sql")
3.  Make a change to the SQL
4.  Hit File, Save (or ⌘ + S)

Instead of saving a new version of the file ("important_query.sql"), it reopens the Save Dialog (same behaviour as hitting ⌘ + ⇧ + S) .

![Screenshot 2020-02-14 at 09 36 20](https://user-images.githubusercontent.com/3440843/74519421-8dc6b300-4f0d-11ea-9713-c84bcf4e069f.png)

SQL Pro Studio, Version 2020.08 (Build 110632). macOS 10.15.3 (19D76)

**Comment by cwolcott** [comment]
I do not have this issue.  

SQL Pro Studio, Version 2020.11 (Build 110636).  macOS 10.14.6 (18G3020)

**Comment by hankinsoft** [comment]
Sorry I haven't responded on this one --- I haven't been able to reproduce:

![CleanShot 2020-03-03 at 08 14 39](https://user-images.githubusercontent.com/3160528/75774863-3efb8480-5d27-11ea-84b0-599cb25a2425.gif)

Next time you reproduce, can you send the most recent log file? Probably only need about the last 10 lines. Should be something like:

```
2020-03-03 08:17:20:095 SQLPro Studio[4520:36917] SQLDocument customSaveDocument:
2020-03-03 08:17:20:096 SQLPro Studio[4520:36917] Calling saveToUrl: file:///Users/kylehankinson/Downloads/Untitled%202.sql, type: SQLDocument saveOperation: 0
2020-03-03 08:17:24:317 SQLPro Studio[4520:36917] Application is resigning activity.

```

**Comment by hankinsoft** [comment]
Just wanted to check if you are still seeing this issue?

**Comment by cwolcott** [comment]
After re-reading this ticket again, I have seen it periodically.  I will try to duplicate and write a new ticket when I see it.
