### ISSUE TITLE
Enhancement Request: Support for 2FA Over SSH

### ISSUE THREAD

**Issue by jgajnak** [hankinsoft/SQLPro#367]
First of all - great product! I'm thrilled to have this kind of tool on macOS, and to be able to support a fellow developer.

I work with databases that require SSH tunneling, but our tunnels also include a 2FA solution (a YubiKey, in my case). Unfortunately I haven't been able to get that solution working natively in the application. Based on the error messages, I'm guessing the current tunneling is being thrown off by the "YubiKey for 'smith'" prompt that gets returned by sshd during login.

I can work around it by creating the SSH tunnel manually and manually port forwarding, but obviously that's not ideal. Could this be put onto your backlog?

**Comment by hankinsoft** [comment]
Would it be possible for you to reproduce a connection, then send me (kyle @ hankinsoft.com) the log file? You can find it by going to 'View' -> 'Logs'. I do a bit of logging around the SSH tunnelling code so that might help me figure something out.

**Comment by hankinsoft** [comment]
As per email discussions this is now supported as of build 2020.14.
