### ISSUE TITLE
Enhancement Request: Organize connections into folders

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#368]
I am currently managing 25 connections and am currently giving detailed aliases to have them organized.  Have you thought about allowing connections to be placed in folders so they can be organized in a clean manner?

**Comment by hankinsoft** [comment]
Thanks for the suggestion. I've got support partially implemented for this, so I will finish it up in one of the upcoming builds.

**Comment by cwolcott** [comment]
Great thank you

**Comment by cwolcott** [comment]
If you need any secondary testing for this feature request let me know.

**Comment by hankinsoft** [comment]
Going to close as a copy of #119. I'm hoping to have a build with initial support for this available within the next few weeks.
