### ISSUE TITLE
Viewing Redshift tables produces an error

### ISSUE THREAD

**Issue by pauls-ai2** [hankinsoft/SQLPro#369]
When I try to view tables in my Redshift database, I get the following error:
![Screenshot 2020-02-17 13 29 54](https://user-images.githubusercontent.com/39743357/74687555-9a573f80-5189-11ea-8577-88d00357017c.png)
![Screenshot 2020-02-17 13 29 27](https://user-images.githubusercontent.com/39743357/74687558-9c210300-5189-11ea-92a4-a67b625452fb.png)

Version 2020.05 (Build 1100631)
Mac 10.13.6

**Comment by hankinsoft** [comment]
Fixed for the next build. Hope to have it available later today.

**Comment by hankinsoft** [comment]
Could you try: 
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.12.app.zip

That should sort it.

**Comment by pauls-ai2** [comment]
Yep! That did the trick! Thanks :)

**Comment by hankinsoft** [comment]
Thanks for letting me know! I will have an App Store update along with SQLPro for Postgres updates available for this later in the week.

**Comment by hankinsoft** [comment]
This is sorted in all the latest builds.
