### ISSUE TITLE
support import from *.sql

### ISSUE THREAD

**Issue by iiinsomnia** [hankinsoft/SQLPro#370]
- export

![image](https://user-images.githubusercontent.com/6582246/74718646-9f8dba80-526d-11ea-87dc-ab491a3e76fe.png)

- import

![image](https://user-images.githubusercontent.com/6582246/74718693-b207f400-526d-11ea-830e-275a9946ead0.png)

**Comment by hankinsoft** [comment]
With `Import -> From SQL` it should just let you pick a file and run that script again the database?

**Comment by iiinsomnia** [comment]
Yes, it means I can import which the exported SQL file.

**Comment by hankinsoft** [comment]
This has been added as of the latest build.
