### ISSUE TITLE
mongodb supports json view for records

### ISSUE THREAD

**Issue by iiinsomnia** [hankinsoft/SQLPro#371]

**Comment by hankinsoft** [comment]
Sure, Ill take a look into this for one of the upcoming builds.

**Comment by iiinsomnia** [comment]
Great！

**Comment by hankinsoft** [comment]
Something like this?

![CleanShot 2020-03-02 at 13 49 24](https://user-images.githubusercontent.com/3160528/75702863-aca6a280-5c8c-11ea-8c2d-d189473dcf7f.gif)

**Comment by hankinsoft** [comment]
First version with support is available at https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.18.app.zip. Please give it a try if you get the chance.

**Comment by iiinsomnia** [comment]
good!
