### ISSUE TITLE
Oracle update fails when Primary Key includes a datetime

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#372]
I not happy with the design of the table, but this is causing an error when applying an update to the table.  The Primary key for this table is a datetime, varchar, varchar.

I am attempting the column **RETRIEVED** and **JOBS**.
![image](https://user-images.githubusercontent.com/3777526/75124573-254ea300-567e-11ea-99ae-0c17ac47d8ee.png)

When I press the Preview and Apply button the following statement is automatically built.
![image](https://user-images.githubusercontent.com/3777526/75124515-a22d4d00-567d-11ea-9b68-7aa7a4cab3cd.png)

When I press the apply button the following error occurs and thus the row is not updated.
![image](https://user-images.githubusercontent.com/3777526/75124544-e9b3d900-567d-11ea-8113-30eb905e79c6.png)

When the same update is performed in SQL Developer the following statement is built.  It uses the internal columns to perform the WHERE instead of the defined PRIMARY KEY. 
![image](https://user-images.githubusercontent.com/3777526/75124611-7199e300-567e-11ea-8d9b-ef43dbf1ce35.png)

----------
**SQLPro Studio Version 2020.14 (Build 110641)**

**Comment by hankinsoft** [comment]
Makes sense. I’ll look into a fix for this.

**Comment by hankinsoft** [comment]
Is CRON_DATE a DATE field or a TIMESTAMP field?

**Comment by cwolcott** [comment]
It is a TIMESTAMP(6) field

**Comment by hankinsoft** [comment]
Could you give this build a try?
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.15.app.zip

It now uses TO_DATE and TO_TIMESTAMP in WHERE clauses to sort the issue. I cannot use ROWID and ORA_ROWSCN as those columns are not always available via SQLPro.

**Comment by cwolcott** [comment]
That works just fine, thank you.  Go ahead and close the ticket when **SQLPro Studio Version 2020.15 (Build 110642)** is officially released.

**Comment by hankinsoft** [comment]
Closing as the new version is available on the App Store.
