### ISSUE TITLE
Oracle functions showing as <nil> in side menu

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#373]
When I look at my artifacts in Oracle the 6 functions are showing as \<nil\>.
![image](https://user-images.githubusercontent.com/3777526/75282719-83df6280-57df-11ea-8c33-db70106b92dd.png)

Here is what I see in SQL Developer:
![image](https://user-images.githubusercontent.com/3777526/75282790-a4a7b800-57df-11ea-8653-3f329c5be1e5.png)

----------
Here is the definition for the first function in the list (HUMANIZE_FILESIZE):

```
create or replace FUNCTION "HUMANIZE_FILESIZE" (bytes in number)
  RETURN VARCHAR2 IS
    i NUMBER;
    result VARCHAR2(20);
   type array_t is varray(7) of varchar2(3);
   fs array_t := array_t(' B', ' kB', ' MB', ' GB', ' TB', 'PB', 'EB');

begin
   if bytes is null then
      return  'Unknown';
   end if;
      if bytes = 0 then
      return  'Unknown';
   end if;
   i := FLOOR(LN(bytes) / LN(1024));
   RETURN CONCAT(ROUND(bytes / POWER(1024, i), 2), fs(i+1));
end;
```
----------

**Comment by hankinsoft** [comment]
Thank you - I've got this fixed for an upcoming build later this week.

**Comment by hankinsoft** [comment]
Could you try: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.17.app.zip if you get the chance?

**Comment by cwolcott** [comment]
Did not fix it. In fact the items just no longer show up.

For **Oracle 11g** instance the picture above is still accurate with 1 stored procedure and 7 functions.  In SQLPro Studio Version 2020.15 it was showing the Stored Procedure and 7 \<nil\> like the picture above.  But now in SQLPro Studio Version 2020.17 there are no artifacts showing in either Stored Procedures or Functions.
![image](https://user-images.githubusercontent.com/3777526/75686738-bcad8a80-5c6a-11ea-9299-7186c2a18919.png)

For **Oracle 18c** instance in SQLPro Studio Version 2020.17 the Stored Procedure is showing but there are no artifacts showing in Functions.
![image](https://user-images.githubusercontent.com/3777526/75686695-abfd1480-5c6a-11ea-9eeb-bd2e6dc75f5c.png)

---------
SQLPro Studio Version 2020.17 (Build 110644)

**Comment by hankinsoft** [comment]
Could you try running this query and letting me know what the results are:

```
SELECT
  all_objects.OWNER,
  all_objects.OBJECT_NAME,
  all_arguments.ARGUMENT_NAME,
  all_arguments.DATA_TYPE,
  all_arguments.IN_OUT,
  CASE all_arguments.IN_OUT WHEN 'OUT' THEN 1000
  ELSE all_arguments.POSITION END AS CUSTOM_POSITION
FROM
    all_objects
    LEFT JOIN all_arguments ON all_objects.object_id = all_arguments.object_id
WHERE all_objects.OWNER NOT IN ('ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSNMP','DIP','DVF','DVSYS','EXFSYS','GSMADMIN_INTERNAL','GSMCATUSER','GSMUSER','LBACSYS','MDSYS','MGDSYS','OJVMSYS','OLAPSYS','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OUTLN','RDSADMIN','SI_INFORMTN_SCHEMA','SYS','SYSBACKUP','SYSDG','SYSKM','SYSTEM','TSMSYS','WMSYS','XDB','XS$NULL')
AND object_type = 'FUNCTION'
ORDER BY 1,2,CUSTOM_POSITION ASC
```

**Comment by hankinsoft** [comment]
If you get no results, could you possible change the `LEFT JOIN` to a `LEFT OUTER JOIN` and see if that sorts it for you?

**Comment by cwolcott** [comment]
So when I run the initial query (with only LEFT JOIN) in Oracle 18c I get the expected list of 7 functions and arguments belonging to SBADMIN:
![image](https://user-images.githubusercontent.com/3777526/75707636-3b1b2400-5c8d-11ea-8711-1d7839da3509.png)

But when I open the Function dropdown under Programmability nothing shows:
![image](https://user-images.githubusercontent.com/3777526/75707748-7d446580-5c8d-11ea-880a-9533400693c5.png)

**Comment by hankinsoft** [comment]
Can you right click the functions note and choose 'Refresh'? I don't think
that will fix the problem, but the database tree is cached in-between
sessions, so it might. I'm also going to add some extra logging for the
next build to see if I can find an error occurring anywhere.

**Comment by cwolcott** [comment]
Yea refreshing the tree at Functions didn't do anything.  I also deleted the log, reopened SQLPro Studio and opened the Function tree, but no issues showed in the log.  Let me know if there is anything else you need me to do.

**Comment by hankinsoft** [comment]
Can you try: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.18.app.zip? And send me the log file if the database nodes do not show? (You can find it by going 'View' -> 'Logs').

**Comment by cwolcott** [comment]
I will try when I get home tonight, about 2 hours.

**Comment by cwolcott** [comment]
![image](https://user-images.githubusercontent.com/3777526/75732905-c9a99880-5cc1-11ea-99fd-7b35a0c15444.png)

![image](https://user-images.githubusercontent.com/3777526/75732870-b26aab00-5cc1-11ea-9e0e-969eef2434d0.png)

`2020/03/02 20:07:33:646  OracleDatabaseTreeEntrySectionFunctions:loadFunctions - Failed to load functions with error: ORA-00918: column ambiguously defined.

Query was:SELECT
  all_objects.OWNER,
  all_objects.OBJECT_NAME,
  all_arguments.ARGUMENT_NAME,
  all_arguments.DATA_TYPE,
  all_arguments.IN_OUT,
  CASE all_arguments.IN_OUT WHEN 'OUT' THEN 1000
  ELSE all_arguments.POSITION END AS CUSTOM_POSITION
FROM
    all_objects
    LEFT JOIN all_arguments ON all_objects.object_id = all_arguments.object_id
WHERE OWNER = 'SBADMIN'
AND object_type = 'FUNCTION'
ORDER BY 1,2,CUSTOM_POSITION ASC
`

**Comment by cwolcott** [comment]
Looks like you just need to add **all_objects** to the where clause for **all_objects**.OWNER = 'SBADMIN'.OWNER = 'SBADMIN'

`SELECT
  all_objects.OWNER,
  all_objects.OBJECT_NAME,
  all_arguments.ARGUMENT_NAME,
  all_arguments.DATA_TYPE,
  all_arguments.IN_OUT,
  CASE all_arguments.IN_OUT WHEN 'OUT' THEN 1000
  ELSE all_arguments.POSITION END AS CUSTOM_POSITION
FROM all_objects
LEFT JOIN all_arguments ON all_objects.object_id = all_arguments.object_id
WHERE all_objects.OWNER = 'SBADMIN' AND object_type = 'FUNCTION'
ORDER BY 1,2,CUSTOM_POSITION ASC`

**Comment by hankinsoft** [comment]
Thanks! I realized I had two paths in the code (one for when grouping by schemas one for not) and in one instance the all_objects was not being specified.

Can you try:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.19.app.zip

That should sort it out. Please let me know.

**Comment by cwolcott** [comment]
Looks good in Version 2020.19 (Build 110646).  Thanks
