### ISSUE TITLE
SQL Server IDENTITY column

### ISSUE THREAD

**Issue by RaphaelZimermann** [hankinsoft/SQLPro#374]
Hello!

I started testing SQLPro, and I missed something very important when creating tables in SQL Server: The IDENTITY directive, for creating incremental fields.

My suggestion at this point would be that there was a type called IDENTITY in the list of field types that automatically generated the script below:

**CREATE TABLE** .... (
....
	[FIELD NAME] int NOT NULL **IDENTITY(1,1)**
....
)

**Comment by hankinsoft** [comment]
FYI I'm going to look into improving IDENTITY support for a build hopefully this week or next.

**Comment by reholmes27** [comment]
Is there any update on this? Having just started testing the software this is a key feature for me.

**Comment by hankinsoft** [comment]
Sorry, I had gotten distracted from this. I'm actively working on adding this now.

**Comment by maria-mcdorman** [comment]
I'm having this issue also. Creating a new database. Serious pain to deal with identities when I have to do them by script every time. Thanks :)

**Comment by hankinsoft** [comment]
Partially implemented, just trying to get the logic right.

<img width="1162" alt="Screen Shot 2020-04-22 at 11 45 20 AM" src="https://user-images.githubusercontent.com/3160528/79996369-c5625600-848e-11ea-938c-18c6fac871dc.png">

**Comment by hankinsoft** [comment]
I've got the first build available with identity support:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.38.app.zip

If anyone gets the chance, please check it out and let me know if you have any feedback. Please note, that you can only add/edit an identity for new columns (or a new table). An additional improvement to the table designer is that you can now drag/drop to reorder columns when creating a new table.

Assuming this does what everybody needs, I'll also get it released for SQLPro for MSSQL and the app store builds.

**Comment by hankinsoft** [comment]
Going to close this. If you anyone has any issues or requests with this, feel free to reopen and let me know.

**Comment by SamJarmanPP** [comment]
Uses this today - works a treat, thank you!
