### ISSUE TITLE
Materialised views have disappeared

### ISSUE THREAD

**Issue by h4ns3n** [hankinsoft/SQLPro#375]
After the update to 2020.14 I can no longer see any materialised views on Postgres in SQL Pro Studio. Please resolve ASAP.

**Comment by h4ns3n** [comment]
@hankinsoft how long do you expect it will take to resolve?

**Comment by hankinsoft** [comment]
I'm working on posting a temporary build now. I should a website build available shortly.

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.15.app.zip should fix the Materialized Views issue. Please note that this build will have some issues with the Postgres table designer as it is actively being worked on. A new build will be available later this week which sorts that out.

**Comment by h4ns3n** [comment]
Thanks, will test and post feedback

**Comment by h4ns3n** [comment]
Thanks @hankinsoft, Materialized Views are back. I'll post any additional issues found.

**Comment by heruan** [comment]
I'm experiencing the same issue with 2020.14 (Build 110641.5), so I downloaded the fixed build from the link but my license isn't recognized anymore; I guess because I purchased via App Store 🤔

BTW I've activated the trial and tested it: views are back 👍

**Comment by hankinsoft** [comment]
I’m hoping to have the App Store build available by tomorrow. I’ve also
recently been re-doing the create/alter table functionality for Postgres,
so I’m just doing some final testing on that before getting it submitted.
