### ISSUE TITLE
Connection Title differences

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#376]
I provide an Alias to all of my connection definitions.  After connecting to a database is there any reason you use the Alias for SQL Server but not for Oracle in you your side menu?  I assume this is just an oversite.

I can not copy the screen because of hostname information being displayed.

For SQL Server it shows the connection to be:
   Alias (Login)
   Version information of Instance

For Oracle is shows the connection to be:
   Servername (Login)
   Version information of Instance

Not sure what it does for other Database types.

**Comment by hankinsoft** [comment]
Thanks, I have this fixed for the next build (early next week).

**Comment by cwolcott** [comment]
What is the standard for closing issues.  Would you like me to come back and close after verifying the release or do you close out issues.

**Comment by hankinsoft** [comment]
Once I have a build available, I’ll post it and request that you give it a
try if/when possible. Then I’ll wait for a response, or if no response is
received in ~2 weeks from the fix being available on all platforms I’ll
generally close the issue myself.

**Comment by hankinsoft** [comment]
Could you try: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.17.app.zip if you get the chance?

**Comment by cwolcott** [comment]
Looks great. Thanks for the update.
