### ISSUE TITLE
Drag row makes app crashed when add a new column

### ISSUE THREAD

**Issue by iiinsomnia** [hankinsoft/SQLPro#378]
![image](https://user-images.githubusercontent.com/6582246/75837500-011e5f00-5e00-11ea-8fd8-451b7bb8cc95.png)

**Comment by hankinsoft** [comment]
Which type of database did you see that with? (MySQL, Postgres, mssql, ...)?

**Comment by iiinsomnia** [comment]
- Version 2020.14 (Build 110641)
- MySQL

**Comment by iiinsomnia** [comment]
In addition, I hope that it supports add new column after which column selected, and in this way, there is no need to drag.

**Comment by hankinsoft** [comment]
Thanks, I've reproduced. Working on the fix and I'll add it so if you have a row selected, the new column gets added directly after.

**Comment by iiinsomnia** [comment]
That's Good !

**Comment by hankinsoft** [comment]
I've got a build available here if you want to give it a try:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.22.app.zip

One note - if your new column is NOT the last column in the table it will add both a `ADD COLUMN` then an `ALTER COLUMN` to change the positioning. The alter column is added for cases where you may have moved other columns as well (say you add a column, then move a pre-existing column after it --- the column needs to be added before the other column can be moved after it).
