### ISSUE TITLE
Feature Request: Shortcut to change connection for current query

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#379]
It would be handy to have a keyboard shortcut to open the connections switcher when in a query, just to avoid having to use the mouse for the sake of speed

In case "connections switcher" is a little vague, I'm referring to this:
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/15026225/76008042-398b6f00-5ecc-11ea-9bfe-f77634f980b8.png">

On another note, I love the in-app update checker / notifier! Very slick.

**Comment by hankinsoft** [comment]
CMD - Shift - H 😁

https://github.com/hankinsoft/SQLPro/wiki/Keyboard-shortcuts

I think it’s also under the View menu but I’m away from my system at the
moment so I’m not 100% positive on that.

**Comment by hankinsoft** [comment]
I think it’s actually cmd - shift - d and my documentation is wrong.

**Comment by jim256** [comment]
@hankinsoft Yesss. Thank you good sir. At least my opening this issue wasn't a complete waste then, so I feel better about that 😉
