### ISSUE TITLE
Customize result-grid font size

### ISSUE THREAD

**Issue by hankinsoft** [hankinsoft/SQLPro#38]
Multiple users have requested to have the results grid customizable (specifically the font size).

**Comment by windware** [comment]
+1. With font family as well.

**Comment by manngo** [comment]
Ditto with Font Family in particular. I would prefer a monospace font (I use Source Code Pro) because some results are not meant to be textual, and monospaced fonts make data easier to read and understand.

**Comment by hankinsoft** [comment]
This is now available in the latest version of SQLPro Studio (https://sqlprostudio.com/download.php) and will be rolling out to the other SQLPro products shortly.

**Comment by manngo** [comment]
I just need to say Thank you!
