### ISSUE TITLE
Unable to connect using ipv6 literals

### ISSUE THREAD

**Issue by yangm97** [hankinsoft/SQLPro#380]
I'm using SQLPro Studio from Setapp and I'm unable to connect to ipv6 hosts using the ipv6 literal, either with our without `[]`. 
Looks like the parser gets confused and thinks it's formatted as host:port when I try without `[]`:
 
```
could not connect to server: Connection refused
	Is the server running on host "200:7e03:x:x:x:x:x:x" and accepting
	TCP/IP connections on port 7?
```

When I try with `[]` I get:

```
could not translate host name "[200:7e03:x:x:x:x:x:x]" to address: nodename nor servname provided, or not known
```

(redacted ip for privacy)

**Comment by hankinsoft** [comment]
What type of database are you attempting to connect to? (MySQL, SQLServer, other)?

**Comment by yangm97** [comment]
PostgreSQL.

**Comment by hankinsoft** [comment]
Could you try this build? https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.29.app.zip

If that does not work, would you possibly be able to send me the logs via kyle @ hankinsoft.com?

**Comment by yangm97** [comment]
Thank you. Using the bare ip works but the `[]` notation doesn't. I also noticed that build still shows "failed to resolve host" on the list.

**Comment by hankinsoft** [comment]
Thanks! I didn't realize square brackets meant something in ipv6. I'll get that sorted out. I think I have the 'failed to resolve host' working properly for the next build. I hope to have another build ready for later this week with these fixes.

**Comment by hankinsoft** [comment]
I was able to get things figured out quicker than I though. If you get the chance, can you try the following build:

https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.31.app.zip

That should sort square bracket support and fix the failed to resolve host issue.

**Comment by yangm97** [comment]
Yeah, it's more common when hitting a service which requires the ip:port notation though, i.e. `http://[::1]:8080`.

**Comment by hankinsoft** [comment]
So I think I'm good too close this? The .31 build worked well for you?

**Comment by yangm97** [comment]
I'm still on .30, guess Setapp didn't rollout that build for me yet.

**Comment by hankinsoft** [comment]
Ah, sorry I hadn’t pushed it to setapp yet. I’ll get that submitted later today.

**Comment by hankinsoft** [comment]
Setapp approved the build roughly an hour ago. Should be appearing as an update roughly anytime.

**Comment by yangm97** [comment]
Sorry for the late reply, I missed the last notification. The latest Setapp build still won't show the right status for bare ipv6 hosts, the actual connection is still fine though.

<img width="215" alt="image" src="https://user-images.githubusercontent.com/4412002/77671493-77793180-6f66-11ea-9ae8-df415d8bf845.png">

**Comment by hankinsoft** [comment]
No worries! If you don't mind, could you let me know what format you are entering your host as? And do you have a port specified either in the host field (via <ip>:port) or in the user specified field?

**Comment by yangm97** [comment]
I sent you a screenshot by email.

**Comment by hankinsoft** [comment]
Thank you! Reproduced and fixed for the next build (will be available mid next week).

**Comment by hankinsoft** [comment]
The latest version is available via Setapp. Please give this a test if you get the chance.

**Comment by yangm97** [comment]
Ok, seems like everything is perfect now. Thanks!
