### ISSUE TITLE
Request: Make Default "LIMIT 1000" Apply after GUI table filters

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#381]
I know we've touched on this before, but I wanted to bring it up again.

I'd really like the filters that can be applied via the visual filters in the GUI to apply before the "LIMIT 1000" filter, or to automatically delete the LIMIT 1000 from the query text if a visual filter is applied.

Whenever I see someone else using another tool that works this way (Postico, TablePlus, etc), I find myself really wishing SQLPro Studio did as well. The fact that it doesn't makes me almost never use the feature, because the only way it's useful is if the record I'm looking for just happens to be in the first 1000 records.

Thoughts?

**Comment by hankinsoft** [comment]
Hmmm I have an idea on this which might be neat. Let me do a bit more
thinking on this. No eta or promises at the moment.

**Comment by jim256** [comment]
@hankinsoft ok, great! I appreciate your being willing to give it a second look

**Comment by hankinsoft** [comment]
This is what I'm currently looking into:

![CleanShot 2020-03-11 at 10 55 50](https://user-images.githubusercontent.com/3160528/76424478-1149b780-6387-11ea-8bdf-f109a63e9014.gif)

Basically performing actions on a 'simple select' will do a 'temporary' update to your query (showing you modified query with a transparent state) and display the updated results. I don't yet have an ETA as I still need to figure out the filters with it and I still need to figure out what happens if the user switches back to the query editor (I'm thinking the temporary portion of the query will get selected allowing the user to delete it if they want).

**Comment by jim256** [comment]
@hankinsoft that seems like a really great implementation. I'd personally love that. Very cool! Thanks again for being so innovative and receptive to feedback

**Comment by hankinsoft** [comment]
When the next build is out (hopefully later today), it both fixes a bunch of issues you've mentioned (#346, #335, #298, #275) plus adds the first initial (sorting only) support. To get the sorting only, you need to run the query "EnableRemoteSorting=true" in its own tab, then close that tab. Any feedback you have on this would be greatly welcome.

**Comment by jim256** [comment]
@hankinsoft whoa, awesome!
I was actually really wanting sort, too. Because I'll notice co-workers using the tool I used to use for Postgres (Postico) be able to do that, and it's so handy. So that seems like an awesome place to start.

Looks like the build hasn't come through just yet, but I'll definitely grab it the moment it does and keep you posted. Thank you!

**Comment by jim256** [comment]
@hankinsoft , just a heads up, I was still on 2020.14. The app didn't ever detect any updates. Maybe that was before in-app update checking? I thought I'd seen it before that, though. Anyway, I just went to the App Store to look, and it looks like I hadn't been using the App-Store version. So I was really behind! Anyway, just wanted to give a heads up that it didn't notify me of an update in the app, so I thought there just was no newer version.

**Comment by jim256** [comment]
@hankinsoft how does the "EnableRemoteSorting=true" query work? Do I need to run that once and done? Or once per connection? Or once per connection every time after the app has been closed? Or something else?

**Comment by jim256** [comment]
Ok. You asked for feedback. My feedback: I absolutely love it! Thank you so much. Extremely useful.

Sort of off topic and definitely minor: I'm also noticing that after the query re-runs (after the sort), it takes me back to the first column. Such that if I'm trying to see the most recent created_at entry, for example, and had to scroll to the right to see that column and click sort, I need to scroll back to the right again to see it after the sort. I can't remember if it used to be like that...it sort (see what I did there?) of seems like it didn't, but I don't remember for sure.

Happy to submit it in a separate issue to be able to discuss / track it there!

**Comment by hankinsoft** [comment]
> I'm also noticing that after the query re-runs (after the sort), it takes me back to the first column

I'll set it up so that when the sorting happens all of your columns will become the same sizes they were and it will restore the horizontal scroll position. I think it makes sense to scroll to the top though. For this, I would like to keep anything related in this same issue for the time being as the feature is not public yet.

**Comment by jim256** [comment]
Awesome! FWIW, I'm already using this feature a ton already. *So* nice to have it enabled, so thanks again.

I agree that it makes sense to reset vertical scrolling each time. I also love that it doesn't ask me to save the query when I go to close it if all I've done is scroll and have that automatically-inserted "ORDER BY ..." in the query.

**Comment by hankinsoft** [comment]
What do you think should happen to the 'temporary' portion of the query when the user focus back on the query window? I had two thoughts:

1. Select it so that it can be deleted should they wish.
2. Remove it (but then the order by/etc in the results grid does not match up).
3. Other?

**Comment by jim256** [comment]
Hmm. That's kind of a tough one. I've thought about it for a minute, and I think maybe #1. Arguments can definitely be made for other approaches, but I think that'd probably be the best overall approach. Allows the user to easily get rid of it, or easily keep it by just hitting an arrow key right after. Also keeps things in sync.

As a side note, I just got thinking that it may also make sense to a) have the query automatically beautified and/or b ) have the results pane take up more of the screen by default when a table/view has been double-clicked, given that the actual SQL text is so minimal and you're usually doing it to explore data.

**Comment by jim256** [comment]
@hankinsoft this may be nitpicky, but I'd *imagine* relatively simple to implement. I just noticed that if I try to sort a result set of less than 1000 records, it still executes a new query on the server with that ordering applied. Not a huge deal, but it 's slower and obviously consumes some resources. Would be handy if it checked the result-set size prior to deciding if it should sort what's already been retrieved vs executing a new query with the remote sort.

**Comment by hankinsoft** [comment]
Sure, I’ll detect a TOP or LIMIT keyword and do local sorting if either of those is not found.

**Comment by jim256** [comment]
@hankinsoft , the situation I'm hitting right now is just double-clicking the table in the database tree pane, and getting the default query with the LIMIT 1000 keyword. For some tables, there are fewer than 1000 records in the entire table. In those instances, it would be handy to do local sorting. Maybe local sorting could also be used if the total number of records returned was fewer than the number specified by LIMIT or TOP?

**Comment by hankinsoft** [comment]
Ahhhhh, ok that makes sense. I'll get that done. Hoping to have a new build
out next week.

**Comment by jim256** [comment]
@hankinsoft Awesome!
One more piece of feedback here, I'd say that more than 50% of the time, a table is probably going to be more or less in ascending order for columns that are kind of "ordered" by default (like primary IDs, dates, etc.). What are your thoughts on making the default sort on first click DESC, and the second sort ASC (opposite of how it is now)?

Example: say I double-click a table to get a quick look. It selects the first 1000 rows. If I'm looking for recent records, for example, I may click to sort on a date field or ID field. That first click will essentially order it in much the same way it came back the first time.

I recognize that I can just right-click and choose descending (which I will do for now), but just got thinking that DESC *might* be more commonly wanted as the default than ASC.

**Comment by hankinsoft** [comment]
That makes sense. That was a simple fix and is ready for the next build (hopefully early next week).

**Comment by jim256** [comment]
@hankinsoft great. Excited for the next release! Also, I'm going to ask my work to pay for a license since I use the app so much and you've put so much into it.

**Comment by hankinsoft** [comment]
FYI the latest App Store build (v2020.33 should be available as of earlier today) adds:

+ Default sort as descending.
+ No server side sorting if the results are less than the specified LIMIT (or TOP), or no limit/top specified.
+ Selects the text in the query editor when you focus back on it.
+ Saves result grid column width and scroll position.

I THINK that covers everything we have discussed for this? (Other than needing to apply it with Filters), but if not, please let me know.

**Comment by jim256** [comment]
@hankinsoft I think so! Getting the new build now. For some reason, it wasn't (and still doesn't) show up in the "Updates" section of the App Store, but if I manually search for the app and pull it up, it shows it was updated yesterday and has an "Update" button.

FWIW, the app itself isn't notifying me of an update either, which I think I saw a couple builds back. I also just went to do a manual download from SQLPro Studio to see which build that gave me (assuming that was the build the in-app update checker checked against) and it gave me 2020.14. You're probably already aware of both these things, but I just thought I'd throw them out in case.

**Comment by hankinsoft** [comment]
For the time being, I've made the decision that filters are going to remain LOCAL. I might re-visit this in the future, but not at the moment for a few reasons:

1. I haven't had many requests for this.
2. Its a ton of work.
3. I think the feature could be confusing to end users.

I will consider investigating it again in the future, but for now the filters will remain local.
