### ISSUE TITLE
Add support for copying postgres connection

### ISSUE THREAD

**Issue by lifeiscontent** [hankinsoft/SQLPro#384]
E.g. when a connection is selected if I press Cmd+C it should copy the postgres connection URI.

<img width="1312" alt="Screen Shot 2020-03-16 at 10 54 37 AM" src="https://user-images.githubusercontent.com/180963/76786583-af1cf800-6774-11ea-8656-e27d55da8730.png">

I was going to suggest right-click to copy. If you wanted to do that, I'd suggest adding

- Edit
- Remove
- Duplicate
- Copy URI

as right click menu options.

**Comment by hankinsoft** [comment]
Thanks! Added for the upcoming 2020.47 version (aiming for early next week).

**Comment by hankinsoft** [comment]
This is in all the latest versions. If you get the chance, please let me know if that does what you were looking for.

**Comment by lifeiscontent** [comment]
@hankinsoft really appreciate your efforts and quick releases! I absolutely love your product 👍
