### ISSUE TITLE
Wiki example shell command fix

### ISSUE THREAD

**Issue by jon-shipley** [hankinsoft/SQLPro#385]
The wiki page:
https://github.com/hankinsoft/SQLPro/wiki/SQL-Server-System-Databases

Offers the following suggestion for showing MS-SQL default databases:
```
SQLPro Studio
defaults com.hankinsoft.osx.sqlprostudio ApplicationPreference-DisplayMSSQLSystemDatabases -bool YES
```

This should be:

```
SQLPro Studio
defaults write com.hankinsoft.osx.sqlprostudio ApplicationPreference-DisplayMSSQLSystemDatabases -bool yes
```

This works in macOS Catalina 10.15.3

**Comment by hankinsoft** [comment]
Thanks, I’ve got that fixed. I’m going to leave this issue open though and add a UI option for it as enough users have asked about that.

**Comment by hankinsoft** [comment]
The latest version of SQLPro Studio on the Mac app store and Setapp both now have this option as a 'Per Connection' setting in the 'Advanced' dialog.
