### ISSUE TITLE
SQL Pro Studio - specify application intent?

### ISSUE THREAD

**Issue by jon-shipley** [hankinsoft/SQLPro#386]
Is there a way of specifying a read-only application intent when connecting to MS-SQL database?

In my case, this is Azure SQL Server.

Many thanks

**Comment by hankinsoft** [comment]
Not yet. I’ve started support for that but don’t currently have an ETA.

**Comment by jon-shipley** [comment]
That's great!  Thanks 👍

**Comment by hankinsoft** [comment]
I’m going to leave this open so that I don’t lose track of it. Once I get it fully implemented I’ll post a note then close it shortly after.

**Comment by hankinsoft** [comment]
FYI, the latest version of SQLPro Studio on the Mac app store and Setapp both now allow MSSQL connections to set a 'Read-only intent' in the advanced parameters. Setting this intent will remove all UI which makes database changes. If you get the chance, please give it a try and let me know if that's what you were looking for.

**Comment by jon-shipley** [comment]
That's exactly what I was looking for 💯 Many thanks.

**Comment by felciano** [comment]
> now allow MSSQL connections to set a 'Read-only intent'

This is great -- thank you! Will this also be available for the "SQLPro for SQLite" app on Setapp?
