### ISSUE TITLE
Bug / Feature Request: Enable Connecting to servers without standards-compliant certificates

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#387]
I'm not sure if this is a bug or needs to be a feature request. In SQLPro Studio, I'm trying to connect to an AWS-hosted Postgres 10.3 database. It connects, but tells me "No databases" in the tree. In the connections view, it says "Timeout connecting to port 0".

If I try to connect in Postico, I get a warning that I have to confirm before connecting that says:
'Postico can't verify the identity of the server "[HOST]". If you connect, you are vulnerable to a man-in-the-middle attack.' In the details, it says that the certificate is not standards compliant.

I was just onboarding an intern and he went with SQLPro Studio at my recommendation, but we're unable to connect to a few databases because of this. I'm talking with others on my team about the certificate issue, but thought it'd also be nice to have the option to connect to instances such as these in SQLPro Studio.

SQLPro Studio 2020.31 (Build 110658.5)
macOS 10.15.3 (19D76)
Postgres 10.3 on AWS

**Comment by hankinsoft** [comment]
Could I get the log for this too please?

**Comment by hankinsoft** [comment]
And a screenshot of the warning dialog?

**Comment by jim256** [comment]
Sorry, it's probably annoying to have to ask for the log every time. I'll make that a default from now on.

As a side note, it would be super handy to have a "Redact all connection info from logs" kind of option, so that I could simply upload the log file directly, without having to go through the file to remove all connection info.

Log file:
[com.hankinsoft.osx.sqlprostudio 2020-03-24--19-18-33-547.log](https://github.com/hankinsoft/SQLPro/files/4377277/com.hankinsoft.osx.sqlprostudio.2020-03-24--19-18-33-547.log)

SQLPro Studio doesn't generate a warning dialog. It connects, but just shows "No Databases" in the databases tree.

Postico warning dialog:
![image](https://user-images.githubusercontent.com/15026225/77469185-51238c80-6dd4-11ea-848b-d08b291f76d7.png)

**Comment by hankinsoft** [comment]
Are you connecting through an SSH tunnel? (Just trying to figure out what's up).

**Comment by jim256** [comment]
@hankinsoft negative, no SSH tunnel.

**Comment by hankinsoft** [comment]
The latest version of the app (2020.33) has been approved earlier today and should be available shortly. Can you let me know if you still have issues connecting to this server? (And if so, provide the updated log via email)?

**Comment by hankinsoft** [comment]
Did you get a chance to see if this was sorted?

**Comment by jim256** [comment]
@hankinsoft , I was still experiencing the issue, but I can't remember exactly when I updated to what version and when I stopped seeing it. On April 14, I worked with one of the devs on my team who implemented what we thought could be a partial fix for this on all of the problem servers. So, I hate to say it, but I'm not sure what ended up doing the trick. I don't see the issue anymore.

**Comment by hankinsoft** [comment]
Ok! I'm going to close the issue. if you run into it again, feel free to let me reopen.
