### ISSUE TITLE
Insert/Update sheet does not properly quote field names.

### ISSUE THREAD

**Issue by jake-b** [hankinsoft/SQLPro#388]
Hi there. 

I have a table that has an column named "order" 

Since this is a keyword, it needs to be quoted in queries.

When using the insert/update sheet, I will typically get this error: 

`near "order": syntax error`

A minor issue, but one that I hit every time I work with that table.

Updated issue with the following info: 
Version 2020.11 (Build 4183.5)

**Comment by hankinsoft** [comment]
Hi, what type of database are you using? MySQL, Postgres, other? I should be able to fix that up pretty easy.

**Comment by jake-b** [comment]
Oops, forgot you make multiple versions :). I'm in my Sqlite version. 
Thanks!

**Comment by jake-b** [comment]
I just tried SQLite Mac Version 2020.35 (Build 4185.5) and I think it works for updates (Choosing a row and selecting "Edit" at the bottom)

I think it still occurs when you click the "+" sign at the bottom an and try to add a row this way-- the "near "order": syntax error" still occurs.

**Comment by hankinsoft** [comment]
Thanks, fixed for the next build! Sorry for the delay.

**Comment by hankinsoft** [comment]
Just wanted to check if you were still seeing this issue? Or if everything is all set?

**Comment by jake-b** [comment]
A quick check of Version 2020.40 (Build 4188.5) seems to show that the issue is resolved.  Thank you.
