### ISSUE TITLE
"Copy selected as intert" doesn't escape table names

### ISSUE THREAD

**Issue by yangm97** [hankinsoft/SQLPro#390]
Using Postgres.

Expected output: `INSERT INTO public."Client" ("UUID", "name"...`
Actual output: `INSERT INTO public.Client ("UUID", "name"...`

If the table is named `User` it will generate a different invalid output: `INSERT INTO <TABLE> ("UUID", "name"...`

**Comment by hankinsoft** [comment]
Thank you - fixed for the next build. I'm investigating the IP issue as well.

**Comment by hankinsoft** [comment]
The latest version is available via Setapp. Please give this a test if you get the chance.

**Comment by yangm97** [comment]
Looks good.
