### ISSUE TITLE
Feature Request: Add "Functions" Node to Connection Tree for Snowflake

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#391]
I can see functions (among other things such as foreign tables, types, etc.) in the tree for Postgres connections and various for MySQL connections, but only "Tables" and "Views" for Snowflake connections.

I just added a function and it would be really nice to be able to be able to view it via the interface. Is it possible to add all additional nodes for Snowflake connections?

**Comment by hankinsoft** [comment]
Working on adding both functions and procedures nodes for the next build (2021.06). Should be available later this week.

**Comment by hankinsoft** [comment]
This has been added to the latest version. If you get the chance, could you please take a look and see if your procedures or functions are visible?

**Comment by jim256** [comment]
Looks like we're square here!
