### ISSUE TITLE
Widows Postgres connection does not work

### ISSUE THREAD

**Issue by rodriguise** [hankinsoft/SQLPro#392]
A server running on localhost connects but does not show any tables, just the spinner. I can't find any options to disable SSL for the connection in the app, the local service does NOT have SSL.

SQLStudio Pro Version: 2020.43
Local Postgres: 12.2
Remote Postgres: 11.6

A remote server with SSL connects but displays the error below:

---------------------------
Failed to load entries
---------------------------
42883: no binary output function available for type aclitem
---------------------------
OK   
---------------------------

Logs:
[SQLPro (3).log](https://github.com/hankinsoft/SQLPro/files/4405791/SQLPro.3.log)

**Comment by hankinsoft** [comment]
Investigating. Thanks for the log!

**Comment by hankinsoft** [comment]
Submitted a fix for this. SQLPro v2020.44. It should hopefully be available by tomorrow.

**Comment by hankinsoft** [comment]
Just wondering if you had a change to give the fixed version a try?
