### ISSUE TITLE
Inline-edit and Copy-as-Insert not retaining escaped characters

### ISSUE THREAD

**Issue by mcackay** [hankinsoft/SQLPro#393]
Noticed some issues while trying to store a regex in a MySQL database:

For example, trying to store the following regex in a VARCHAR column: ```^WH\d{8}$```

This needs to be escaped on the initial insert:
```INSERT INTO <table> SET col='^WH\\d{8}$'```

If you then try to edit the field value using the GUI, to change say "WH" to "WB" then the backslash drops out of the edit. The preview of the changes shows: 
```UPDATE <table> SET col = '^WB\d{8}$' WHERE id = 1```

Similarly selecting the row and 'copying selected as insert' also drops the escape on the backslash:
```INSERT INTO <table> SET col = '^WB\d{8}$'```

**Comment by hankinsoft** [comment]
Thank you for the note. This is fixed for the next version which will be available either later this week or early next.

**Comment by hankinsoft** [comment]
Should be sorted in the latest App Store version (available now: 2020.35). (Which app are you using and where is it installed from -- App Store, website, Setapp?)

**Comment by mcackay** [comment]
Running SetApp, version 2020.31 (Build 110658).
Doesn't appear to be fixed in this release -- copy-as-insert, inline-field-edit all drop the escape on the backslash for me.

**Comment by hankinsoft** [comment]
Can you check for an update? The latest version in Setapp should be 2020.35:

<img width="580" alt="Screen Shot 2020-04-08 at 11 30 25 AM" src="https://user-images.githubusercontent.com/3160528/78796262-785d8a80-798c-11ea-954a-34867050b0fa.png">

Maybe try relaunching Setapp or a reboot if the update is not downloading yet?

**Comment by hankinsoft** [comment]
Just wondering if you happen to receive the new version via Setapp and if the issue is sorted?
