### ISSUE TITLE
Bug: SQL Editor wrapping prematurely when multiple tab characters are used

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#395]
If I am using multiple tab characters to format a block of SQL + comments in order to make it more-readily readable for the next developer, the editor wraps the line very prematurely. Even if I have other lines in the same query window that are 6x longer that are not wrapped, tab will wrap early. This isn't a recent bug issue.
Example screenshot below and log file attached.

[com.hankinsoft.osx.sqlprostudio 2020-03-31--18-53-06-510.log](https://github.com/hankinsoft/SQLPro/files/4411053/com.hankinsoft.osx.sqlprostudio.2020-03-31--18-53-06-510.log)

![image](https://user-images.githubusercontent.com/15026225/78064342-d8ca4780-734e-11ea-9fa8-f9900855e2bf.png)

Where I put the "1" is the last area it lets me tab to before wrapping to the next line.

SQLPro Studio 2020.31 (Build 110658.5)
macOS 10.15.4 (19E266)
Snowflake 4.11.0 and Postgres

**Comment by hankinsoft** [comment]
Fixed for the next build.

**Comment by hankinsoft** [comment]
Should be sorted in the latest App Store version (available now: 2020.35).

**Comment by jim256** [comment]
@hankinsoft seems to be sorted! Very nice to have that working so well. Thank you again good sir.
