### ISSUE TITLE
Bug: Autocomplete Table Name Escape Characters for Snowflake

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#396]
The Fivetran Shopify connector for Snowflake brings in orders in an "ORDER" table. Since this is a reserved word, SQLPro Studio tries to escape it with brackets and autocomplete makes it "[ORDER]". This gives a syntax error of "unexpected '['".

It looks like Snowflake wants to use double quotes as escape characters. I tried brackets and single quotes and neither worked. If I escape with double quotes, it works.

SQLPro Studio 2020.31 (Build 110658.5)
macOS 10.15.4 (19E266)
Snowflake 4.11.0

**Comment by jim256** [comment]
Also, FWIW, it seems that autocomplete for the ORDER table doesn't work because of the double quotes. If I typed "o." , there's no suggestion popup.

**Comment by hankinsoft** [comment]
> It looks like Snowflake wants to use double quotes as escape characters. I tried brackets and single quotes and neither worked. If I escape with double quotes, it works.

Fixed for the next build.

>Also, FWIW, it seems that autocomplete for the ORDER table doesn't work because of the double quotes. If I typed "o." , there's no suggestion popup.

Just to check, do you mean "o".? (o OUTSIDE the quotes?) I don't believe that putting the period inside quotes is valid and if a table name is quoted autocomplete SHOULD work:

![Screen Shot 2020-03-31 at 7 39 46 PM](https://user-images.githubusercontent.com/3160528/78081645-6aee4200-7387-11ea-8300-a714a049ad85.png)

Could you post a screenshot to help me out? Thanks!

**Comment by jim256** [comment]
@hankinsoft 
I'm sorry, that was a really poor way of describing the issue.

What I should have said is that if you alias the ORDER table as o, then trying to do
`SELECT o.` doesn't provide any suggestions.

Screenshot of autocompleting after alias on a quoted table:
![image](https://user-images.githubusercontent.com/15026225/78162623-6025c280-7404-11ea-8eb5-c1a26d012967.png)


Screenshot of autocompleting after alias on a non-quoted table:
![image](https://user-images.githubusercontent.com/15026225/78162616-5e5bff00-7404-11ea-9f7d-1b9f23e29bde.png)

**Comment by hankinsoft** [comment]
Ahhhh, that makes more sense. Thanks, I'll look into sorting that out.

**Comment by jim256** [comment]
@hankinsoft while you're diving into this, I'll mention that I also just noticed that the right-click table options like "Select top 1,0000 rows" and "Script as" are disabled on a table that's been escaped with double-quotes (looks like same goes for brackets), at least in the case of this Shopify ORDER table.

**Comment by hankinsoft** [comment]
Should be sorted in the latest App Store version (available now: 2020.35).

**Comment by jim256** [comment]
@hankinsoft Awesome! Seems to work great. And super nice to not have to manually change those characters every time now + have aliases / autocomplete working for them. Thanks again 😄

**Comment by jim256** [comment]
@hankinsoft , I failed to notice previously that the issue of not being able to right-click on the table name in a query is still present for Snowflake table names escaped with double quotes:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/15026225/78920774-26326d00-7a51-11ea-8251-2cfa3fbc3f8f.png">

**Comment by hankinsoft** [comment]
Fixed for the next build.

**Comment by hankinsoft** [comment]
Latest build (2020.38) is available which should sort this out. Please let me know if you get a chance.

**Comment by jim256** [comment]
@hankinsoft, seems to be taken care of!
