### ISSUE TITLE
NOT WORKING! I signed up for 1 free and yearly subscription

### ISSUE THREAD

**Issue by magnus-flynotes** [hankinsoft/SQLPro#397]
I activated the free trial and purchased a yearly subscription on app store. IT DOES NOT WORK!

Called apple support and they directed me submit the issue here.

Very frustrating. Please sort out.

How to fix this now?

**Comment by hankinsoft** [comment]
Hi,
The quickest fix is to uninstall and re-install the app. See here for full details: https://github.com/hankinsoft/SQLPro/wiki/App-Store-Subscription-not-Renewing.

Please let me know if that helps to sort things out.

**Comment by magnus-flynotes** [comment]
Thanks for the prompt reply.

Sorry it does not give me this option on App Store. It just says "Open".

What to do?

**Comment by hankinsoft** [comment]
Try these steps:

1. Close SQLPro
2. Close the App Store.
3. Delete SQLPro from your system (see https://support.apple.com/en-ca/HT202235).
4. Open the App Store and download SQLPro again.

Your subscription should now be recognized as the app store receipt has been updated.

**Comment by magnus-flynotes** [comment]
Thank you. It is now working.

Thanks for your super fast support and resolution!!!

**Comment by hankinsoft** [comment]
No problem!

**Comment by magnus-flynotes** [comment]
Thanks!


---
Magnus Traff
Chief Technology Officer

M: +44(0)7596 063 299
A: Public Hall, 1 Horse Guards Avenue,  Westminster, London, SW1A 2HU, UK
W: www.flynotes.co.ukE: magnus@flynotes.co.uk




This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee, you should not disseminate, distribute or copy this email. Please notify the sender immediately by email if you have received this email by mistake and delete this email from your system. If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by magnus-flynotes** [comment]
Hi,

I purchased a license and all of sudden I am asked to enter the license key again!

Can you please provide me with the key?

Thanks,
Magnus


---
Magnus Traff
Chief Technology Officer

M: +44(0)7596 063 299
A: Public Hall, 1 Horse Guards Avenue,  Westminster, London, SW1A 2HU, UK
W: www.flynotes.co.ukE: magnus@flynotes.co.uk




This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee, you should not disseminate, distribute or copy this email. Please notify the sender immediately by email if you have received this email by mistake and delete this email from your system. If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by hankinsoft** [comment]
Hi,
If you continually see the issue, I suggest cancelling your App Store subscription and purchasing via the webstore. For users running into this issue, I can provide either a 10% discount or I could instead provide a promo code for three months free (let me know if that's what you would prefer). I have an article available at https://github.com/hankinsoft/SQLPro/wiki/App-Store-Subscription-not-Renewing with details.

**Comment by magnus-flynotes** [comment]
Hi Kyle,

I am not sure what you mean. Are you saying I must purchase a license again?
I have paid for 1 year already. Please advice.


Invoice
APPLE ID
magnus@flynotes.co.uk BILLED TO
MasterCard .... 8007
Magnus Traff
14 Lockwood Chase
Oxley Park
Milton Keynes, MK4 4ER
GBR
INVOICE DATE
08 Apr 2020 SEQUENCE NO.
1-3588750470
ORDER ID
MVKZWGS2WV DOCUMENT NO.
162334197603
App Store
SQLPro Premium (Automatic Renewal)
SQLPro Premium (Automatic Renewal) (Yearly)
Renews 08 Apr 2021

Report a Problem
£55.99
Inclusive of VAT at 20%
Subtotal   £46.66
VAT charged at 20%   £9.33
TOTAL £55.99
Get help with subscriptions and purchases. Visit Apple Support.

**Comment by hankinsoft** [comment]
Hi,
The quick solution (as listed in the article here: https://github.com/hankinsoft/SQLPro/wiki/App-Store-Subscription-not-Renewing), is to uninstall and reinstall the app. That will let you to continually use the application.

If you continually see the issue, I suggest cancel your App Store subscription and purchasing via the webstore instead.

**Comment by magnus-flynotes** [comment]
Will try.

Thanks,
Magnus
