### ISSUE TITLE
Can't change Data Type from menu, SQLite 

### ISSUE THREAD

**Issue by mariolacko** [hankinsoft/SQLPro#398]
Can't change Data Type in SQLite from menu. Menu is empty.

<img width="1382" alt="SQLProStudio_SQLite" src="https://user-images.githubusercontent.com/959399/78139518-f4098580-7428-11ea-99c8-e621a55d6b68.png">

**Comment by hankinsoft** [comment]
Thank you! I'll get this sorted for the next build and will post a note here once it is available.

**Comment by hankinsoft** [comment]
Fixed for the next build:

<img width="1162" alt="Screen Shot 2020-04-02 at 12 46 03 PM" src="https://user-images.githubusercontent.com/3160528/78269432-f4188c80-74df-11ea-9e96-1026d04becf9.png">
