### ISSUE TITLE
Feature Request: Increase size of History window

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#399]
I'll often run a query a bunch of times, iterating as I go. Most of the time, the very top of the query (what's visible in the History preview) may be the exact same over many iterations, so I can't tell which I'm looking at quickly without scrolling down each time after hitting the next button.

It would be awesome if this window were either dynamically resizable in the UI, had a configurable size in the preferences pane, or were just much larger (I think I'd personally prefer the entire length of the screen given that there probably wouldn't be any disadvantage to it, and about double or triple the width).

Personally, I think I'd prefer to have everything that's currently on the bottom of the pop up (query #, the restore options, etc.) moved to the top of the pop up if this is implemented, so that they're right next to where your mouse already is if you open the history window via a click.

By the way, I LOVE the improvements to the error message text! SO helpful, particularly on the display I'm using. Thank you.

**Comment by hankinsoft** [comment]
SQLPro Studio v2022.24 has been approved on the App Store and adds a persistent resizable history window. Please let me know if this sorts this out.

**Comment by hankinsoft** [comment]
Please let me know if this needs anything else.
