### ISSUE TITLE
Feature Request: Enable UI Row Inserting / Editing Without Locking UI

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#401]
It would be great if I could make changes to a row without the UI being restricted to only that action. Sometimes I need to look at another table or query to know exactly what changes I'm trying to make, but either have to note those values down elsewhere or memorize them before trying to insert / edit.

**Comment by hankinsoft** [comment]
Working on this for the next version. This will also include #57.

**Comment by hankinsoft** [comment]
Here is the new insert and duplicate for the next release:

![CleanShot 2020-05-13 at 09 29 20](https://user-images.githubusercontent.com/3160528/81812491-94f56100-94fc-11ea-9234-69d4bf39ce67.gif)

You can also right click a row and choose edit to find the larger edit dialog which has more options such as import/export and view as hex.

**Comment by jsoconnell** [comment]
@hankinsoft +1 for this feature, was about to add a similar feature request but this does the trick!

**Comment by jim256** [comment]
@hankinsoft, I went to use this feature yesterday and hit some issues.

I wanted to just leave a few fields empty / null, but when it tried to execute, it failed on datetime fields with the 'DEFAULT' value.

A dialog box pops up saying "Failed to Run Update. Incorrect datetime value: 'DEFAULT' for column 'date_deactivated' at row 1. (Error #1292)".

Log file attached:
[com.hankinsoft.osx.sqlprostudio 2020-05-28--15-37-14-166.log](https://github.com/hankinsoft/SQLPro/files/4696677/com.hankinsoft.osx.sqlprostudio.2020-05-28--15-37-14-166.log)
MySQL 8.0.19
SQLPro Studio 2020.48 (Build 110679.5)
macOS 10.15.4 (19E287)

**Comment by hankinsoft** [comment]
Hmm, I'm not able to reproduce. Could you possibly send me the DDL of the table?

**Comment by jim256** [comment]
@hankinsoft, as generated by SQLPro Studio (macOS):

```
CREATE TABLE `subscriptions` (
    `id` INT NOT NULL AUTO_INCREMENT,
	`user_id` INT NOT NULL,
	`alert_condition_id` INT NOT NULL,
	`date_deactivated` DATETIME DEFAULT NULL,
	`date_created` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`date_modified` DATETIME DEFAULT NULL ON
	UPDATE
		CURRENT_TIMESTAMP,
		PRIMARY KEY (`id`),
		UNIQUE KEY `UK_subscriptions` (`user_id`, `alert_condition_id`),
		KEY `FK_subscriptions_alert_condition_id` (`alert_condition_id`),
		CONSTRAINT `FK_subscriptions_alert_condition_id` FOREIGN KEY (`alert_condition_id`) REFERENCES `alert_conditions` (`id`)
) ENGINE = INNODB AUTO_INCREMENT = 97 DEFAULT CHARSET = utf8;
```

**Comment by jim256** [comment]
@hankinsoft just following up here as I hit this again

**Comment by hankinsoft** [comment]
I haven't been able to reproduce this. What version of MySQL are you connected too?

![CleanShot 2020-08-31 at 10 45 24](https://user-images.githubusercontent.com/3160528/91726796-34576600-eb77-11ea-8cb2-5cea606b2a98.gif)

I'm using the same table DDL as you (minus the foreign key constraint), so the MySQL version is all I can think of that might be the difference.

**Comment by jim256** [comment]
@hankinsoft , I think I realized what was happening.
I was filling in values for the first couple of columns and hitting tab each time to move to the next one. After I'd made the last change, I hit tab again, which took me to a cell that still had 'DEFAULT' in it, and I hit enter. That caused it to think I was trying to actually insert the text value 'DEFAULT':

![image](https://user-images.githubusercontent.com/15026225/92152158-771b7700-eddf-11ea-9925-57b784a7927b.png)

**Comment by hankinsoft** [comment]
This should be fixed in any build after 2020.77. Please give it a try if you get the chance.

**Comment by hankinsoft** [comment]
I believe this is all sorted? If you get the chance, are you still seeing any issues with this?

**Comment by jim256** [comment]
Seems to be sorted. Thanks!
