### ISSUE TITLE
Feature Request: Add "IS NULL" and "IS NOT NULL" to GUI Query Results Filters

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#402]
It would be handy to be able to be able to filter query result records to only records that were NULL or not NULL by using the GUI filters.

**Comment by hankinsoft** [comment]
FYI, I have to re-do most of the filter UI for this and #381 which is why that portion hasn't been completed yet. It's on my list to do soon.

**Comment by jim256** [comment]
Ok, that makes sense. I was about to bump this. Thanks for the update!

**Comment by hankinsoft** [comment]
This is now available in the latest version. Please give it a try and let me know if you run into any issues.

**Comment by hankinsoft** [comment]
#381 is not sorted for this build yet - just the null is not null.

**Comment by jim256** [comment]
@hankinsoft awesome! Seems to work great. I'm good to have this closed.
