### ISSUE TITLE
Bug: Custom Previous / Next Tab Keyboard Shortcuts not Persisted through Updates

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#403]
Each time I update to a new version via the App Store, it wipes out my the keyboard shortcuts I've set for tab switching. (Shift + Tab and CMD + Shift + Tab). I've customized other keyboard shortcuts (toggle line comment, for example) and they persist across updates.

**Comment by hankinsoft** [comment]
+ Fixed for the next build.

**Comment by hankinsoft** [comment]
Latest build (2020.38) is available which should sort this out. Please let me know if you get a chance.

**Comment by jim256** [comment]
@hankinsoft, resolved! Thank you.
