### ISSUE TITLE
Feature Request: Snowflake - Enable Cross-Database Autocomplete and Syntax Highlighting

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#404]
When writing a query in Snowflake that uses multiple databases, autocomplete will only work for whichever database I have chosen in the database picker, even if I fully qualify all, some, or none of the tables. The highlighting also doesn't recognize tables (or schemas) from other databases and leaves them as plain white text. Would be really handy to have it work for other databases in the same Snowflake instance! Note: it does already work for all schemas within the current database.

When an autocomplete suggestion for a table is accepted, it'd also be great if it inserted the fully-qualified table name if from a different database, since that is required for the query to run.

macOS 10.15.4 (19E266)
SQLPro Studio 2020.35 (Build 110664.5)
Snowflake 4.11.0

**Comment by jim256** [comment]
@hankinsoft just wanted to give this a bump and specify that cross-schema and cross-database would really make this complete.

**Comment by hankinsoft** [comment]
I’ve got no objections to this, but I cannot put an ETA on it at the moment. I have some customers with literally 1000s of databases and I would need to ensure not to drastically degrade performance when handing these. Just need to think about it a bit before I look into any sort of implementation.

**Comment by jim256** [comment]
Makes total sense!

**Comment by hankinsoft** [comment]
Hi. Just wanted to let you know I've been making progress with this and hope to have it available either next week, or the week after. The attached video shows it generally working - I just need to finish syntax highlighting support for other databases and make a few performance improvements.

![CleanShot 2020-06-04 at 14 20 32](https://user-images.githubusercontent.com/3160528/83792001-db0f9180-a670-11ea-9af8-577471ca523c.gif)

**Comment by jim256** [comment]
@hankinsoft this is awesome! 😄 Very cool to hear. I was just wishing for this again earlier today (and most days, to be honest, since I'm constantly doing cross-db joins in Snowflake). Looking forward to it!

**Comment by hankinsoft** [comment]
This is now available in the latest version. Please give it a try and let me know if you run into any issues.

**Comment by jim256** [comment]
@hankinsoft LOVE THIS. THANK YOU!!! I'm good to consider it closed, though I would personally vote for a color other than orange for other-schema highlighting in the dark theme.

**Comment by hankinsoft** [comment]
The next build can now change the database color in the appearance. I'll post here once it is available. Default is still orange, unless you have a suggestion :D

**Comment by jim256** [comment]
@hankinsoft, cool! Maybe some kind of magenta / pink? I don't think that's used elsewhere, is it?

**Comment by hankinsoft** [comment]
2020.61 is now available which adds the option to change the database color as well as changes the default color to pink. If you get the chance, please give it a test and confirm its working as you would expect.

**Comment by jim256** [comment]
@hankinsoft, I guess I can't remember how this was working before, but in this version I don't get any suggestions in the FROM for tables in other DBs until I qualify with DB_NAME.SCHEMA_NAME. Maybe this is by design, though. If so, I think I'd personally vote to move the suggestions one level higher - meaning that, if I do need to qualify for other DBs, only make me type in the DB name before I start getting suggestions for table names, rather than having to also specify the schema.

The DB_NAME is also colored straight red for me. I reset all settings to default and it's red on all themes.

**Comment by hankinsoft** [comment]
> @hankinsoft, I guess I can't remember how this was working before, but in this version I don't get any suggestions in the FROM for tables in other DBs until I qualify with DB_NAME.SCHEMA_NAME. Maybe this is by design, though. If so, I think I'd personally vote to move the suggestions one level higher - meaning that, if I do need to qualify for other DBs, only make me type in the DB name before I start getting suggestions for table names, rather than having to also specify the schema.

This is for snowflake? I'll have to investigate - in my testing (I generally use MSSQL), you cannot access the tables from another database UNLESS you specify the schema. So `SELECT * FROM OtherDatabase.Table` is not valid.

> The DB_NAME is also colored straight red for me. I reset all settings to default and it's red on all themes.

I've changed the color a bit more for the next build.

**Comment by jim256** [comment]
@hankinsoft, I should have been more explicit. What I meant is that it'd be nice to have autocomplete suggest things from all the schemas in the other database (just as it does for the "active" database), though it would indeed have to insert the schema name upon acceptance of the suggestion in order to execute the query.

**Comment by jim256** [comment]
@hankinsoft still love this feature. I thought I'd mentioned this somewhere, but can't find it now.

If I have two tables with the same name in two different schemas, autocomplete will only suggest one of them.

Would you like me to open a different issue for this?

**Comment by jim256** [comment]
@hankinsoft just wanted to give this a slight bump to make sure you saw it since it may be an easy win given that the primary implementation is already done

**Comment by jim256** [comment]
Closing this one since the overall request is finished and #464 documents the remaining issue.
