### ISSUE TITLE
Enhancement: Pass-through table selection when initiating import

### ISSUE THREAD

**Issue by mcackay** [hankinsoft/SQLPro#405]
I initiate an import by right-clicking on the table I want to bring data into and choosing "Import > From CSV". 

However in the dialogue that pops up after choosing the file, it always defaults to the first able in the list, even though i specifically may have selected a table. 

It would be great if it remembered which table i selected to import into, and defaulted to that.

**Comment by hankinsoft** [comment]
Hmmm, it should already be passing through. A few questions to help me out with this:

1. What type of database are you connecting to? (Sql server, mysql, Postgres, etc).
2. What version of the app are you using?
3. Whats the full path of the table you are attempting to import into? (Including schema name).

Thanks!

**Comment by hankinsoft** [comment]
I was able to reproduce this. It's sorted for the next build.

**Comment by hankinsoft** [comment]
Latest build (2020.38) is available which should sort this out. Please let me know if you get a chance.
