### ISSUE TITLE
Feature Request: Snowflake with Okta authentification

### ISSUE THREAD

**Issue by mkhudon** [hankinsoft/SQLPro#406]
My company uses Okta to authenticate when login in to Snowflake. Would it be possible to add support for this in SQLPro Studio?

Refer to this article for more information: https://community.snowflake.com/s/article/Okta-SSO-with-Snowflake-Part-2-JDBC-SQL-Tools

Thanks!

macOS 10.15.4
SQLPro Studio 2020.35 (Build 110664)

**Comment by hankinsoft** [comment]
Hi,
A few questions:

If you specify an authenticator:
1. Do you still enter a username and password?
2. Are you prompted with a SSO dialog within the current app you are using?
(Could I get a screenshot or video of this if possible)?

Thanks!

**Comment by mkhudon** [comment]
Hum… Maybe I am configuring this incorrectly. Where would I specify the authenticator? I don't see the option in the connection window.

![Snowflake Settings](https://user-images.githubusercontent.com/93592/78812962-49e6ac00-799a-11ea-98f9-3b3f53ffaaa6.png)

**Comment by hankinsoft** [comment]
Sorry, I meant if you specify one in another app :) I saw from the first
link you provided how to you would specify the connection in a JDBC
connection string, but I was looking for more info on what happens after
that.

**Comment by mkhudon** [comment]
Ah! No, I haven't tried with another app. I have been using the Snowflake web interface for now, but I would prefer using SQLPro if I could. :)

**Comment by hankinsoft** [comment]
Ahhhh ok. I opened a support request on the snowflake c library to see if
it supports authenticators (
https://github.com/snowflakedb/libsnowflakeclient/issues/193). The answer
to if I can support it, depends on this.

**Comment by hankinsoft** [comment]
+ Current `libsnowflakeclient` does not support this. Unfortunately I won't be able to add support for the time being.

**Comment by mkhudon** [comment]
That's too bad. Thanks for following up.

**Comment by hankinsoft** [comment]
No problem! Sorry for the bad news. I'm going to close this issue for the time being as its not something I'm going to be able to currently implement. I'll re-evaluate later on and see if libsnowflakeclient adds additional support.
