### ISSUE TITLE
Create View / Alter View produce strange SQL

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#409]
This is MySQL (connection is to AWS RDS MySQL 5.7.22)

A couple of problems:

1. statement always begins `CREATE OR REPLACE <view name> ` . Should be juste `CREATE VIEW <view name>` or `ALTER VIEW <view name>`

2. Backticks and brackets everywhere! 

3. complete loss of formatting - the entire view sits as one line.

I've attached the output from SQLProStudio, and the SQL that I used to create it.
[SQLProBug - Views.zip](https://github.com/hankinsoft/SQLPro/files/4466031/SQLProBug.-.Views.zip)

**Comment by hankinsoft** [comment]
Hey Dave,
Unfortunate that’s how MySQL stores the view internally. It does not keep the original statement users ran to create a view. You can see similar behaviour by running:

show create view my_view_name;

I’ve through about trying to clean up the view code smartly, but I decided against it as I didn’t want to risk breaking the sql code. Instead I leave it to the end users to run the query pretty print if they wish.

**Comment by davidharrison92** [comment]
Ah, cheers! Sorry for blaming you for this!
