### ISSUE TITLE
Snowflake bug: -10 being displayed as 18446744073709551606

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#410]
I've got a Snowflake field of type NUMBER(38,0) according to Script As and according to the Snowflake Web UI. It's value is -10, but is being displayed in the query results window of SQLPro Studio as 18446744073709551606

When I use TYPEOF, it shows as an integer.. 🤔 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/15026225/79176914-ba3c6580-7dbe-11ea-8d41-00cc3d2f212b.png">

Log:
[com.hankinsoft.osx.sqlprostudio 2020-04-14--01-43-29-578.log](https://github.com/hankinsoft/SQLPro/files/4472667/com.hankinsoft.osx.sqlprostudio.2020-04-14--01-43-29-578.log)

SQLPro Studio 2020.35 (Build 110664.5)
macOS 10.15.4 (19E287)
Snowflake 4.11.2

**Comment by jim256** [comment]
Looks like a similar issue for -1

**Comment by hankinsoft** [comment]
Thanks, fixed for the next build (everything was being treated as unsigned, so negative values were wrapping).

**Comment by hankinsoft** [comment]
Latest build (2020.38) is available which should sort this out. Please let me know if you get a chance.

**Comment by jim256** [comment]
@hankinsoft, also resolved!
