### ISSUE TITLE
sqlite version is old

### ISSUE THREAD

**Issue by meddulla** [hankinsoft/SQLPro#412]
The included driver for sqlite is old (3.24). Window functions were introduced in 3.25 so this is quite an annoyance (just had to install tableplus even though i have a license for sqlpro studio). My current version is Version 2020.35 (Build 110664). Except for this, it's a great product. Thanks!

**Comment by hankinsoft** [comment]
Sorry about that, I'll get this fixed up for the next build. Are you using SQLPro through the website, App Store, or Setapp (I'll post a build for what your using first).

**Comment by meddulla** [comment]
Through the website. Thanks!

**Comment by hankinsoft** [comment]
Can you grab https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.38.app.zip and let me know if that sorts it?

**Comment by meddulla** [comment]
Looks good! Thanks!

**Comment by bhj** [comment]
@hankinsoft Hi, any word on a similar update for SQLPro for SQLite? `RENAME COLUMN` doesn't seem to work in 2020.35 (Build 4185). Thanks for the great app!
