### ISSUE TITLE
Connection Group not working

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#413]
I been working on other things for the past 6 weeks and was curious if #119 had been completed.  So I downloaded the latest release 2020.35 and noticed that there was a "Connection Group" under the new menu item.  So I tried it and no connection group was created.  All that is shown is the default connection group "My Connections" and my 17 connections.

So I download 2020.25 which had the initial build for this enhancement, but I had the same issue.  The dialog comes up, but when I hit accept nothing happens.
![image](https://user-images.githubusercontent.com/3777526/79500168-06bfb500-7ffa-11ea-93d3-54b913037590.png)

I don't see any errors in the log.

**Comment by hankinsoft** [comment]
Hi,
So when you hit accept, nothing at all happens? What if you hit return? The dialog neither disappears or displays an error message?

**Comment by cwolcott** [comment]
Good question. So if I enter a Connection group name of AbcXyz and hit Enter or the Accept button the dialog goes away, but no new group is created.  All I see is the default "MY CONNECTIONS (17 connections)" with all my connections under it and no other group.

**Comment by hankinsoft** [comment]
Hmmm, ok - any you are not seeing any groups like the following show up near the bottom?

<img width="1355" alt="Example" src="https://user-images.githubusercontent.com/3160528/80279992-71967d80-86d7-11ea-9cc0-b9c1dea3274c.png">

What OS version are you running?
Could you try creating a group, then sending me the log file? (You can email it directly via kyle @ hankinsoft.com).

**Comment by cwolcott** [comment]
Sent

**Comment by cwolcott** [comment]
Decided to give it a try again and it is now working just fine with **Version 2020.35**.  I went ahead and downloaded the last Version **Version 2020.39** and everything still works.  Not sure why it started working
