### ISSUE TITLE
Row won't delete when doing multiple queries

### ISSUE THREAD

**Issue by SamJarmanPP** [hankinsoft/SQLPro#414]
Steps to reproduce:

1) Run a query that selects two tables, eg
```
select * from foo
select * from bar
```

2) Right click the row in either of the result sets
3) Click delete
4) Run same query again

Actual Result: Row still present
Expectation: Row not still pleasant

**Comment by hankinsoft** [comment]
Hi,
Sorry for the delay in response. A few questions:

1. What database type are you using? (MySQL, Postgres, MSSQL, Other)?
2. Does the delete query preview show the appropriate query?
3. Can you post the query here please?
4. Does the UI get updated before you re-run the query? (When you delete, do the rows disappear from the UI?)

Thanks!

**Comment by hankinsoft** [comment]
Hi, just wanted to check in and see if you were still seeing this?

**Comment by SamJarmanPP** [comment]
Hi @hankinsoft Yesterday I updated to to the latest version of SQL Pro for MSSQL (which I found this bug in originally) and I am not able to replicate.

I am also not able to replicate any more - so thats annoying but good for this issue haha. 

I'm going to close this now and I'll re-open if I can ever reproduce. 

Thanks!

**Comment by hankinsoft** [comment]
Thanks for letting me know! FYI I
Did make some improvements specifically for deleting mssql results when multiple result sets were returned, which might have been what you were seeing.

**Comment by SamJarmanPP** [comment]
Ah yes that does ring a bell - perhaps that was it!
