### ISSUE TITLE
Application crash when closing tabs

### ISSUE THREAD

**Issue by bpaterni** [hankinsoft/SQLPro#416]
I've encountered this crash in the past, just never submitted a github issue for it, and I don't think one exists. This happened to me when I was cleaning up a sqlpro instance with some old tabs. Closing tabs in quick succession and/or closing a tab with an active query running may play a part in the crash?

The crash report dump is here: https://pastebin.com/xKa0EhWW

**Comment by hankinsoft** [comment]
Thank you for the crash dump. I'm investigating this issue.

**Comment by hankinsoft** [comment]
FYI I've submitted a fix to the App Store today for this. It should be available in ~24 hours.

**Comment by hankinsoft** [comment]
Please let me know if you see this issue after updating to the latest version. If I haven't heard back in a week, I will close the issue (feel free to reopen it if you do see it after that).

**Comment by bpaterni** [comment]
Thank you for the quick fix! Been running the updated version for a few days and haven't seen the same crash yet. (but haven't been closing tabs in quick succession either...:)

**Comment by hankinsoft** [comment]
Great! I'm not seeing anything in the crash reports either, so I'm going to close the issue for now. Please feel free to reopen the issue if you see it again.
