### ISSUE TITLE
New postgres db:  connection disconnects too soon?

### ISSUE THREAD

**Issue by mpalazz** [hankinsoft/SQLPro#418]
Hello!   I was wondering if you have any advice.  I have recently set up a postgres server at a remote location with mostly default settings.   We have no issues connection without ssh, but our connection is timing out about every 10-15 minutes?  I've never had this issue before with sqlpro (studio) and I was wondering if you have any recommendations for keeping the connection alive?  

FYI: Refresh doesn't work - I always have to disconnect and reconnect.  

Thanks!

**Comment by hankinsoft** [comment]
Thanks for the note, I will investigate. What is the exact error you are seeing? Could I get a screenshot?

**Comment by mpalazz** [comment]
Sure.  Seems like a parameter on the server side.   Sorry this doesn't have more info:
  
![Screen Shot 2020-04-30 at 7 08 51 AM](https://user-images.githubusercontent.com/5777989/80720689-1d621380-8ab2-11ea-8576-5f84097c16bb.png)

**Comment by mpalazz** [comment]
From the postgres log:
`2020-04-30 09:07:32.798 UTC [24222] LOG:  could not receive data from client: Connection timed out`

**Comment by mpalazz** [comment]
I have figured out the issue here.  This is a server-side TCP timeout issue.  Thanks for looking.
