### ISSUE TITLE
Can't delete the app from MacBook

### ISSUE THREAD

**Issue by GaCoder2164** [hankinsoft/SQLPro#419]
I installed the trial version from the App Store and cannot delete the app. The button never presents an X like other apps. How do I fully remove it? I'm new to Macs.

**Comment by hankinsoft** [comment]
Hi,
It sounds like you downloaded the app from the website which generally means you need to delete it from your downloads folder. Open your downloads folder in finder and look for SQLPro for SQLite. Right click (or ctrl click) and choose 'move to trash'.
