### ISSUE TITLE
Column data types in result headers

### ISSUE THREAD

**Issue by hankinsoft** [hankinsoft/SQLPro#42]
"something that pgAdmin does when it displays the query results grid – the header row for the grid contains the column name, but then you can turn on a preference to display the data type for the column underneath the name. It's just a handy thing when when poking around in a new database to see the data types and tweak queries accordingly, rather than nesting into the object tree on the left to get data types for each column."

**Comment by jdonnici** [comment]
Here's a sample screenshot from pgAdmin III...

![pgadmin_grid_headers_datatype](https://cloud.githubusercontent.com/assets/421813/14570479/a9e6d88c-0301-11e6-8457-1632a513c40b.png)

**Comment by hankinsoft** [comment]
Hi. I've looked into this, but decided not to add it. While column data types are known for user created tables, in custom queries the underlying column types are not specifically known and this leaves a 'what should be displayed' in the header question.

**Comment by jdonnici** [comment]
Got it... thanks for the followup!
