### ISSUE TITLE
SQLPro MSSQL - using with VPN?

### ISSUE THREAD

**Issue by aaksyonenko** [hankinsoft/SQLPro#423]
Is there a way to have SQLPro use the VPN selectively for internal resources?  Without having to force the entire traffic from the system over VPN?
Web browsers do this, I can access internal sites on VPN, and if I access external sites — traffic is direct, without being routed through VPN.  Is this something that could possibly be added to SQLPro?  Difficult to use it when working remotely without...

**Comment by hankinsoft** [comment]
For you connections, are you specifying a host name, or an IP address?

**Comment by aaksyonenko** [comment]
IP.  If I specify a host name - it responds with "host not found".  If I specify IP it responds with "host unavailable or connection refused".  I am connecting to a named instance, specifying the server name as "ip_address\instance_name".  Strangely enough, when I connect to another system that only has a default SQL install (not a named instance) it's connecting fine.

**Comment by hankinsoft** [comment]
Ahhhh, I didn't realize you were using instances. Instance lookup will unfortunately fail on a VPN as instance lookups use UDP broadcasts which do not play well with VPNs. Is it possible for you to find out the port associated with your instance? If so, you can specify the port directly which should sort the issue out for you.

**Comment by aaksyonenko** [comment]
Yessss!  Worked!  Thanks!  :-)  Now, if only a fix could be made for hotkeys to recognize function keys...    :-)  was trying to assign "F5" as the execute hotkey, just like SSIS, but it just keeps bringing up a list of SQL verbs, and I can't figure out where that's controlled.

**Comment by hankinsoft** [comment]
Could you possible add that as a separate issue? I took a quick look thinking it might be easy, but its not a '10 minute fix'. F5 is a default macOS 'display autocomplete' shortcut (see https://osxdaily.com/2011/04/21/word-completion-mac-os-x/), so I'll need to do a bit of work to figure that out and get it sorted out.
