### ISSUE TITLE
Import CSV with Null 

### ISSUE THREAD

**Issue by chriskinsman** [hankinsoft/SQLPro#424]
I have a CSV I am attempting to import.

Some columns are empty and look like:

columna,columnb,columnc
123,,345

ColumnB is define as a timestamp with a time zone. Have also tested without a timezone It is nullable.

When I attempt to import this file I get:

Failed to perform insert with error: ERROR:  invalid input syntax for type timestamp: ""

Version: 2020.37 (Build 1047808)

Any ideas on how to get import to work?

**Comment by chriskinsman** [comment]
And if I try and skip the column SQL Pro crashes with a quit unexpectedly..

**Comment by chriskinsman** [comment]
Forgot to mention this is Postgres

**Comment by hankinsoft** [comment]
Thanks for the details, I'm taking a look into it.

**Comment by hankinsoft** [comment]
Just wanted to check in and see if you had a chance to give this a try?
