### ISSUE TITLE
Export / Import Parity

### ISSUE THREAD

**Issue by chriskinsman** [hankinsoft/SQLPro#425]
Postgres SQL
Version 2020.37

Table with a integer[] type in Postgres 11.5

Export with SQL Pro

Exports as {123}

Import with SQL Pro

--> Failed to perform insert with error: ERROR:  syntax error at or near "{"

**Comment by hankinsoft** [comment]
Just making sure I 100% understand. You are exporting the table as CSV, then re-importing it?

**Comment by hankinsoft** [comment]
Fixed for the next build. Hoping to have something you can try tomorrow, I'm just working on get #424 fixed for it as well.

**Comment by hankinsoft** [comment]
If you get the chance can you try https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.2020.40.app.zip? That should sort both this issue and #424.

**Comment by chriskinsman** [comment]
I was just exporting / reimporting to test that I had the format right for the import.  Figured if you exported in that syntax you should import in that syntax.  Will try that build tonight.

**Comment by hankinsoft** [comment]
Just wanted to check in and see if you had a chance to give this a try?
