### ISSUE TITLE
SQLite Pro For Mac Asking For Activation

### ISSUE THREAD

**Issue by bedchr** [hankinsoft/SQLPro#427]
Hi,

This happened a few months ago and then it was fixed and now it’s happening again. I updated my SQLite pro for Mac and I’m being prompted with a window that says you have 7 days left in your trial. I purchased this through the Mac App Store for a fixed price last year so I don’t have a license key.

**Comment by hankinsoft** [comment]
Can you send me an email via kyle@hankinsoft.com? I'll provide you with a
license key to use until this is sorted. I submitted the wrong
version again and have already submitted a fix. I've also made a change to
my system so I should be unable to submit the wrong version again.

**Comment by hankinsoft** [comment]
FYI the latest build is available on the Mac app store and sorts this out.
