### ISSUE TITLE
Feature Request: Publicly shareable log files

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#429]
I'd love to be able to set an option to have the log file not contain any connection information whatsoever (host, ssh host, database name, username, password, etc.). Especially as more logging is added to help track down issues, it starts to consume more time to go through a log file before posting it to ensure that I'm not accidentally exposing sensitive company information. 

I'd hate to accidentally post a log file that contained, for example, the host, username, and password. This discourages me from creating issues and/or posting log files, because at times I don't have the time to carefully go through the log file to ensure that I'm not doing just that.

**Comment by hankinsoft** [comment]
I've been working on this slowly. Every new version has a bit more stripped out, then as I receive new logs I try and find more to strip out.

**Comment by jim256** [comment]
@hankinsoft got it, good to know.

**Comment by hankinsoft** [comment]
I've made quite a few changes around this in the latest version. Please give it a try and let me know if you are still seeing anything that you think should be removed.

**Comment by jim256** [comment]
@hankinsoft great! Will do

**Comment by jim256** [comment]
Here's an example of where my DB name was getting put into the log. You can search for `MY_DB_NAME_REDACTED` to find instances.
[SQLPro-TempTableDoesntExist.log](https://github.com/hankinsoft/SQLPro/files/5349033/SQLPro-TempTableDoesntExist.log)

**Comment by hankinsoft** [comment]
Going to close this unless I receive additional requests for it.
