### ISSUE TITLE
Unexpected EOF from server

### ISSUE THREAD

**Issue by rtorino** [hankinsoft/SQLPro#43]
Return `Unexpected EOF from server` on connection. I been trying to many times to connect, but still get the same error. Refer to this [screen shot](http://imgur.com/ka4tTcL).

**Comment by hankinsoft** [comment]
Hmm this is a new one to me. A few questions to get started:

1. Is this a cloud hosted db? If so, what provider?
2. What version of SQL Server is running?
3. Are you connecting to a named instance?
4. Are you connecting to the default port?
5. Are you using SA or Windows Authentication?

Thanks!

**Comment by rtorino** [comment]
1. Yes, it's hosted on AWS EC2 instance.
2. SQL Server 2014
3. No, through instance public URL
4. Yes, 1433
5. SA

**Comment by hankinsoft** [comment]
Hmm, ok. A few more questions:

1. Do you know which E2C instance you used? I'm going to attempt with
'Microsoft
Windows Server 2012 R2 Standard edition, 64-bit architecture, Microsoft SQL
Server 2014 Standard edition. [English]' to see if I can reproduce.

2. Are you using any anti-virus/malware tools? Macfee will sometimes block
tcp connections.

**Comment by mlmajor** [comment]
I am having this same kind of behavior.  I am using a locally hosted system.  I am using Windows Authentication.  I am getting the EOF error as shown at the above link.  Was this issue ever resolved?

**Comment by hankinsoft** [comment]
Unfortunately no, I was never able to reproduce the issue. What version of SQL Server are you using? If you are using TLS 1.2 exclusively that could cause the issue. If that is the case, I do not have a resolution yet.

**Comment by mlmajor** [comment]
I will find out the specifics and let you know.  Thanks much
Melissa

On Sep 2, 2016, at 2:07 PM, Kyle <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately no, I was never able to reproduce the issue. What version of SQL Server are you using? If you are using TLS 1.2 exclusively that could cause the issue. If that is the case, I do not have a resolution yet.

**Comment by mlmajor** [comment]
OK, here is the information pertaining to our setup:

We are using SQL Server 2012 and we are not using TLS.

I was able to enter my AD authentication credentials in this manner,
username as “domain\username”  and the tool now works!

Thanks,
Melissa

**Comment by hankinsoft** [comment]
Thank you for letting me know you were able to resolve the issue. I may add
a warning that windows auth needs to be entered in that format.
