### ISSUE TITLE
The app hangs and crashes trying to export few data to CSV

### ISSUE THREAD

**Issue by madeger** [hankinsoft/SQLPro#430]
SQLProPremium with lifetime license, just purchased, over macOS X Mojave 10.14.6

Selecting export over a little table (about 1000 rows and 7 varchar columns), the software increase resource consuming and, after a while, crashes.

![Export command](https://user-images.githubusercontent.com/65180498/81581461-1048fc80-93af-11ea-9a22-5713db13588f.png)

![CSV exporting hangs](https://user-images.githubusercontent.com/65180498/81581442-09ba8500-93af-11ea-864d-1fe6def24787.png)

The database is mounted on a parallels Windows XP host, is accessed smoothly, and the table is fully read quickly.

![Table read performance](https://user-images.githubusercontent.com/65180498/81581408-fefff000-93ae-11ea-8a95-4301b117611b.png)

**Comment by hankinsoft** [comment]
Hi,
I'm pushing an update to the App Store now which I think will sort this out. It should be available in ~24-48 hours. Once its available, I'll write a post here to confirm if that sorts the issue.

**Comment by hankinsoft** [comment]
Hi. The new version is available via the App Store. Please update and give it a try. If you are still seeing the issue, please provide an updated crash log. Thank you!

**Comment by hankinsoft** [comment]
Just wanted to check if that helped out?
