### ISSUE TITLE
ORA-00942 error trying to export as CSV

### ISSUE THREAD

**Issue by madeger** [hankinsoft/SQLPro#431]
SQLProPremium with lifetime license, just purchased, over macOS X Mojave 10.14.6 and Oracle 10g XE on a parallels Windows XP host, accessed smoothly, with tables fully read quickly.

![Export command](https://user-images.githubusercontent.com/65180498/81698359-26fe5a80-9466-11ea-883f-e076e66ff045.png)

![Schermata 2020-05-12 alle 15 28 52](https://user-images.githubusercontent.com/65180498/81698071-ca02a480-9465-11ea-8769-db105cc1f9f7.png)

![Schermata 2020-05-12 alle 15 29 05](https://user-images.githubusercontent.com/65180498/81698086-ce2ec200-9465-11ea-99af-2c3622053366.png)

**Comment by hankinsoft** [comment]
Reproduced. Working on fix.

**Comment by hankinsoft** [comment]
Submitted the build, sorry about that. Quick workaround: do a select * from <your table>. Right click on the results and choose 'Export result set as' -> 'CSV'.

**Comment by madeger** [comment]
Thank you for your quick reply.

Right click on the results and choose 'Export result set as' -> 'CSV' does not include column headers.

**Comment by hankinsoft** [comment]
Hi,
There is a checkmark for 'Include column names'. This is generally enabled by default.

<img width="497" alt="Screen Shot 2020-05-12 at 11 08 59 AM" src="https://user-images.githubusercontent.com/3160528/81702372-8eee7a00-9441-11ea-9e67-4f9e53fce751.png">

**Comment by madeger** [comment]
You are right. I was using "Copy selected as" -> "Comma separated". But there is also "Export result set" on bottom.

**Comment by hankinsoft** [comment]
A new version is available that sorts this. Please upgrade and give it a try if you get the chance.

**Comment by hankinsoft** [comment]
Just wanted to check if that helped out?
