### ISSUE TITLE
Bug in SQLPro Studio (MSSQL) with script generation

### ISSUE THREAD

**Issue by aaksyonenko** [hankinsoft/SQLPro#432]
On right-click of stored proc name in list (possibly also true for functions and views, haven't checked), if you choose "Modify" or "Script as —> ALTER", the script that is generated is actually "CREATE", not "ALTER".
See attached screenshot.
![2020-05-13_15-35-21](https://user-images.githubusercontent.com/22381393/81857257-ff73c480-952f-11ea-82bb-138591a21425.png)

**Comment by hankinsoft** [comment]
Thano you. What type of database is this? MSSQL, MySQL, Postgres?

**Comment by aaksyonenko** [comment]
MSSQL

**Comment by hankinsoft** [comment]
What version of the app are you using? You can find this by going to 'SQLPro for MSSQL' (or 'SQLPro Studio') -> 'About'.

**Comment by hankinsoft** [comment]
Nevermind, I think I see the issue.

**Comment by hankinsoft** [comment]
Hi,
This is fixed in the App Store and Setapp versions of SQLPro Studio. If you get the chance, could you give that a try? If your using the website version, let me know and I can provide that as well.

**Comment by aaksyonenko** [comment]
I downloaded the app from your site at https://www.sqlprostudio.com/download.php, I'd rather continue doing that for updates to make sure I don't break licensing or anything

**Comment by hankinsoft** [comment]
I’ll have that available later today.

**Comment by hankinsoft** [comment]
Can you grab https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.45.app.zip and give it a try?

**Comment by aaksyonenko** [comment]
crash.
[SQL Pro Crashdump.txt](https://github.com/hankinsoft/SQLPro/files/4635455/SQL.Pro.Crashdump.txt)

**Comment by hankinsoft** [comment]
Sorry about that. Can you grab https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.46.app.zip and give it a try?

**Comment by aaksyonenko** [comment]
Yep, works correct now.  Another thing I noticed is that the word GO occasionally has issues.  Like, if my proc definition ends on a GO - an error is raised.

**Comment by hankinsoft** [comment]
> Another thing I noticed is that the word GO occasionally has issues. Like, if my proc definition ends on a GO - an error is raised.

This is when you are running a procedure? Could I get a possibly get a screenshot of the query and the error message next time you see this?

**Comment by aaksyonenko** [comment]
Actually, I cannot duplicate it anymore with v.2020.46, I think you fixed it :-)

**Comment by hankinsoft** [comment]
Ok! If you see it again, please feel free to let me know and open a new issue.
