### ISSUE TITLE
Create Function fails

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#433]
Should I be able to create functions using SQLPro Studio?

Below is a simple function that we use to pretty print file sizes, I can run this script in SQL Developer without any issues.  But in SQLPro Studio it stops after the first ';' and thus fails.
```
create or replace FUNCTION "HUMANIZE_FILESIZE" (bytes in number)
  RETURN VARCHAR2 IS
    i NUMBER;
    result VARCHAR2(20);
   type array_t is varray(7) of varchar2(3);
   fs array_t := array_t(' B', ' kB', ' MB', ' GB', ' TB', 'PB', 'EB');

begin
   if bytes is null then
      return  'Unknown';
   end if;
      if bytes = 0 then
      return  'Unknown';
   end if;
   i := FLOOR(LN(bytes) / LN(1024));
   RETURN CONCAT(ROUND(bytes / POWER(1024, i), 2), fs(i+1));
end;
```
**---------------------------------------**
**SQLPro Studio - Version 2020.40**

**Comment by hankinsoft** [comment]
Hi,
You might need to change your delimiter via the `Edit Connection` -> `Advanced` window. Change it from ; to / and you should be set.

<img width="1162" alt="Screen Shot 2020-05-21 at 10 55 01 AM" src="https://user-images.githubusercontent.com/3160528/82565953-9f91a500-9b51-11ea-9b47-a72bf8e73ba7.png">

Please give that a try and let me know if it sorts everything out.
