### ISSUE TITLE
Display Types in the tree list for Oracle databases

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#434]
Is it possible to show defined Types in the tree list?

![image](https://user-images.githubusercontent.com/3777526/82509519-1c7f3900-9ad6-11ea-8cc8-214d54ac7c68.png)

**------------------------------------
SQLPro Version 2020.40**

**Comment by hankinsoft** [comment]
Not currently. I will add this for a future build.

**Comment by hankinsoft** [comment]
What context menu actions would you want for types? 'Script as CREATE' and DROP?

**Comment by cwolcott** [comment]
That would be fine

**Comment by hankinsoft** [comment]
Does

`select * from user_types;` give the list of types you are looking for?

**Comment by cwolcott** [comment]
Kyle, was this comment for me?

**Comment by hankinsoft** [comment]
Yeah, I'm planning on adding the types, I just wanted to make sure those were the types you wanted to see there?

**Comment by cwolcott** [comment]
Yes, please

**Comment by hankinsoft** [comment]
Added for the next build (2022.21) which should be available in a day or two.

**Comment by cwolcott** [comment]
Running SQLPro fo Oracle 2022.21 (Build 508.5) and the new Types doesn't show the correct information.

When I execute `select * from user_types` i get the following 4 records.
![image](https://user-images.githubusercontent.com/3777526/162659758-45502dc5-4e8d-46f5-a539-885c84d9b824.png)

But the tree is show something different.  The **Types** look like it is has double the entries from **Views**.
![image](https://user-images.githubusercontent.com/3777526/162659883-78035ce1-939a-48a2-8066-000f5ca5d292.png)

**Comment by hankinsoft** [comment]
My bad. Could you check the latest build if you get a chance? You might need to right click and refresh the types node.

**Comment by cwolcott** [comment]
I need to determine why 2 of the 4 objects are not shown.
Seem to be missing SPLIT_TBL and PIVOTIMPL.  I will look into it this weekend.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/3777526/164897409-41e7f4d6-751e-4538-a3ab-38224c8028dc.png">

**Comment by hankinsoft** [comment]
1. What do you get if you run the query:

```
SELECT
    OWNER,
    TYPE_NAME
FROM
    ALL_types
WHERE OWNER = '< your schema >'
ORDER BY 1,2;
```

**Comment by cwolcott** [comment]
All good.  Too many development databases to keep straight.  The 4 objects were from a different database.  This seems to be working just fine.
