### ISSUE TITLE
No empty string in a column default

### ISSUE THREAD

**Issue by hepabst** [hankinsoft/SQLPro#435]
Not showing an empty string in a column default when viewing with an DESCRIBE table or ALTER TABLE in existing tables that have empty strings as defaults for char and varchar types.

**Comment by hankinsoft** [comment]
What type of database is this with? MySQL, Postgres, mssql, other?

**Comment by hepabst** [comment]
Mysql

Herbie

**Comment by hankinsoft** [comment]
I've made some changes for this in the latest build. If you get the chance, please give it a try and let me know if everything is working how you expect.
