### ISSUE TITLE
Can’t open SQLite on iPad

### ISSUE THREAD

**Issue by mariolacko** [hankinsoft/SQLPro#436]
There is no way how to open / create SQLite database on iPad 

![image](https://user-images.githubusercontent.com/959399/82659182-8ad41080-9c28-11ea-929b-8bfe7684f274.png)

**Comment by hankinsoft** [comment]
For iPad, you would be opening an sqlite file from your iCloud Drive?

**Comment by mariolacko** [comment]
Yes, but i can't see SQLite menu like in SQL Pro for macOS. 
(top right corner on screenshot, no SQLite menu)

**Comment by hankinsoft** [comment]
The first build of SQLPro Studio with SQLite support is now available. To open a SQLite file, choose the Plus button as if you were adding another connection, then SQLite, then 'Open existing'.

**Comment by hankinsoft** [comment]
Closing as SQLite support has been added.
