### ISSUE TITLE
Can't manage foreign keys in MySQL

### ISSUE THREAD

**Issue by mariolacko** [hankinsoft/SQLPro#437]
I can't add new foreingn keys in MySQL 10.3.21.

There is no column names in pop-up.

<img width="1108" alt="Snímka obrazovky 2020-05-22 o 18 47 00" src="https://user-images.githubusercontent.com/959399/82690662-e8825000-9c5c-11ea-9c3c-b5792d816af1.png">

**Comment by hankinsoft** [comment]
I believe I have reproduced this. Investigating now.

**Comment by hankinsoft** [comment]
Fixed for the next build (planned to be available later this week).

<img width="1050" alt="CleanShot 2020-05-25 at 09 46 18@2x" src="https://user-images.githubusercontent.com/3160528/82814047-b8a99700-9e6c-11ea-8579-73b78b49acba.png">

**Comment by hankinsoft** [comment]
This should be sorted in the latest version. Please give it a try and let me know if you are still seeing any issues.
