### ISSUE TITLE
Preferences hang

### ISSUE THREAD

**Issue by pdofak** [hankinsoft/SQLPro#438]
I'm unable to open the SQLite Pro Preferences on Mac. Maybe it is just my iMac. Haven't tried another machine yet.
Trying to open Preferences get Beachball Eternal.

**Comment by hankinsoft** [comment]
Hmmm, sorry about that.

Two questions:
1. What version of the app are you running? (Can you send a screenshot from 'SQLPro for SQLite' -> 'About' menu item?
2. Can you let the beachball hang for ~3 minutes. That should cause a crash. If possibly, can you post the resulting crash log?

**Comment by pdofak** [comment]
Hi,
No apologies needed. Things happen! :)
My message was just an FYI in case you were unaware. Maybe it’s just my system. Maybe it’s a more universal problem.
I did reboot and try a few times in case it was some transient problem.

SQLite version 1.0.27


This is a typical iMac:


There are a few startup items:


Beachball is eternal I think. I let it go for several hours. Trying to get a crash report after Force Quit doesn’t produce anything on screen. Do you know of some way to force or sleuth out a crash report?

Anything I can do to help, just let me know.

Cheers
PD

**Comment by hankinsoft** [comment]
> version 1.0.27

That version is suuuuuuper old - like six years old. Can you grab https://www.sqlitepro.com/download.php and let me know if that sorts it out?

**Comment by hankinsoft** [comment]
Going to close this. If you are still seeing the issue on the latest version, please let me know.
