### ISSUE TITLE
no such module: RTREE 

### ISSUE THREAD

**Issue by tsuliwaensis** [hankinsoft/SQLPro#439]
There is a SQLite database I modify regulary, but since updating to the latest version of SQLPro, I've been getting the error `no such module: RTREE` when running an update statement that has successfuly run in the past (multiple times over many years). The error doesn't occur when I run the update statement in Terminal. Wondering if something changed in version 2020.40 (Build 4188.5)

**Comment by hankinsoft** [comment]
> Wondering if something changed in version 2020.40 (Build 4188.5)

Yes, I switched to the latest version of SQLite, but did not compile with the RTREE setting enabled. I have re-enabled this for the next build which I plan for later this week. Sorry about that!

**Comment by hankinsoft** [comment]
This should be sorted in the latest version. Please give it a try and let me know if you are still seeing any issues.

**Comment by tsuliwaensis** [comment]
Yes, it's fixed. Thank you!
