### ISSUE TITLE
Invalid quote characters

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#44]
As described here:
http://www.hankinsoft.com/forum/viewtopic.php?f=10&p=2718&sid=1ef1d9a2dbdea1c86209054f56973dcf#p2718

**Comment by hankinsoft** [comment]
Can you confirm this has been fixed in the latest build? (http://macsqlclient.com/download.php).

**Comment by davidharrison92** [comment]
Looks fixed in 1.0.63
