### ISSUE TITLE
Require a connection through proxy server (Socks / HTTP)

### ISSUE THREAD

**Issue by alextang96** [hankinsoft/SQLPro#440]
As title, nice to have it. Because my network has block all the port using 1433. My network is only open 80 and 443. So that I can only connect to a v2Ray Proxy, which open Socks / HTTP proxy, for a TCP connection on other ports.

**Comment by hankinsoft** [comment]
Thanks for the request! I'll get this added to the backlog and as I see more requires come in for it, I will take a look into adding it.

**Comment by hankinsoft** [comment]
Going to close this for the time being. If I receive more requests for it I can take a  further look into it, but currently it's not something I've got an ETA for.
