### ISSUE TITLE
Can't alter table from GUI

### ISSUE THREAD

**Issue by mariolacko** [hankinsoft/SQLPro#441]
I can't alter MariaDB (10.3.21) table from GUI.

My changes (one blue line):
<img width="1214" alt="SQLPro_edit" src="https://user-images.githubusercontent.com/959399/83144227-5e6e3780-a0f3-11ea-8f05-5d0aefd18cb2.png">

Auto-generated code:

```SQL
ALTER TABLE odbor ADD COLUMN nazov varchar NOT NULL;
```

Error message:
<img width="1214" alt="SQLPro_error" src="https://user-images.githubusercontent.com/959399/83144237-629a5500-a0f3-11ea-8b9f-6e0611332a34.png">

It works after manual changes:

```SQL
ALTER TABLE odbor ADD COLUMN nazov varchar(255) NOT NULL DEFAULT '';
```

**Comment by hankinsoft** [comment]
Hi,
I think if you change your `Type` column from `varchar` to `varchar(255)` in the UI that will sort the issue.
