### ISSUE TITLE
Windows version is very different than the Mac version

### ISSUE THREAD

**Issue by jwathen1** [hankinsoft/SQLPro#442]
I have the Mac version which is great. I purchased the Windows version, not sure why you have to purchase Windows version and not Mac, but the Windows version is missing several key features.
Like export the data to cvs and other formats.

**Comment by hankinsoft** [comment]
Hi,
You can export a table to CSV by right clicking, choosing export, then CSV. Such as:

![Screen Shot 2020-05-28 at 8 19 37 PM](https://user-images.githubusercontent.com/3160528/83203804-a8b9dd80-a120-11ea-9e82-b7d5ec5cf3eb.png)

You can also export query results by right clicking the results, choosing 'Export' and 'CSV' such as:

![Screen Shot 2020-05-28 at 8 20 52 PM](https://user-images.githubusercontent.com/3160528/83203883-d43cc800-a120-11ea-8dce-719e05f006c1.png)

The Windows Version is behind the macOS version and I am working on getting feature parity. I have a roadmap available at #311. If you have specific features you would like to see added sooner than later, please post them on that post. Thanks!

**Comment by hankinsoft** [comment]
Going to close this. Please add requests/issues to #311 for the time being.

**Comment by jwathen1** [comment]
I like the Mac function to export all tables at once.ideally also if you could map the relationships of data in tables and structure.
Also, I just downloaded your program for my Mac. I have already purchased a license from the Windows store.Which I do not use. Do I also now have to purchase a separate Mac license?
Thanks,
Joseph Wathen
    On Thursday, May 28, 2020, 07:23:22 PM EDT, Kyle Hankinson <notifications@github.com> wrote:  
 
 


Hi,
You can export a table to CSV by right clicking, choosing export, then CSV. Such as:



You can also export query results by right clicking the results, choosing 'Export' and 'CSV' such as:



The Windows Version is behind the macOS version and I am working on getting feature parity. I have a roadmap available at #311. If you have specific features you would like to see added sooner than later, please post them on that post. Thanks!

**Comment by hankinsoft** [comment]
Hi,
Unfortunate you can’t share a license purchased from the Mac App Store or windows store as their is no simple way to share the data between the two. The only licenses which are cross platform are subscription license keys purchased from my webstore (they are the same price and use my own authentication method).
