### ISSUE TITLE
Inserting a row does not quote all field names

### ISSUE THREAD

**Issue by halindrome** [hankinsoft/SQLPro#443]
I am using MariaDB 10.3 and SQL Studio Pro Version 2020.45 (Build 110673)

I have a table where I stupidly named one column 'with' and another column 'when'.  I guess that one or both of these are reserved.  Regardless, if I use the insert row feature on this table the generated SQL fails to actually insert because if the reserved word conflict.   I think the system should just quote all of the field names to be safe.

**Comment by hankinsoft** [comment]
Just wanted to note that I've got this sorted in the next version. Hope to have it available later this week.

**Comment by hankinsoft** [comment]
Hi, if you get a chance, please give this a try in the latest version. It should be all fixed up.
