### ISSUE TITLE
Edit button on table page grayed out

### ISSUE THREAD

**Issue by ldirksen** [hankinsoft/SQLPro#445]
SQLPro 2020.40 Build 4188.5 on Mac 10.15.4

Create a 7 column table but can't add data because the +/- buttons and the edit button don't respond

**Comment by ldirksen** [comment]
I create a table, seven columns.  I click the “+” key and it populates nicely.

I create a second table, ten columns.  The “+”, “-“, and “Edit” buttons are grayed out and I can’t find a key stroke that will allow me to start populating the rows.

Here is the Structure:

CREATE TABLE IF NOT EXISTS Cars (
  "Chassis#" integer(5) PRIMARY KEY NOT NULL,
  "Motor#" integer(6),
  ProdDate char(10),
  Dealer char(30),
  Coachbuilder char(35),
  OrigBody char(35),
  OrigOwner char(35),
  CurrentOwner char(35),
  Provenance char(128),
  Comments char(128)
);
Created a third table.  Also unable to populate its rows.  Any suggestions?

**Comment by hankinsoft** [comment]
Could you send me a screenshot? I'm trying to reproduce (using that same DDL) but I haven't been able too. Just trying to figure out what's up.

**Comment by ldirksen** [comment]
Here’s a couple of screen shots.  My ‘pictures’ table seems to be fine.  My ‘Cars’ table is the one where I can’t populate rows with data.

I am in Phoenix, UTC +8.  Thanks for any help you can provide.

Larry

**Comment by ldirksen** [comment]
Any suggestions on what I might do next?

ld

**Comment by hankinsoft** [comment]
Hi - I'm working on adding a bit of logging to the next built to help diagnose. I hope to have it available within a few days. FYI the screenshots didn't actually come through - I think maybe due to email? If you get a chance, could you upload them directly to the GitHub issue (at https://github.com/hankinsoft/SQLPro/issues/445)?

**Comment by ldirksen** [comment]
Kyle - deleting the field size (5 )for the Primary Key  in my Cars table allows it to operate properly.

I assume this is a syntax issue related to SQLite and not SQLPro.

**Comment by hankinsoft** [comment]
Thanks for letting me know you were able to get this sorted out.
