### ISSUE TITLE
Import CSV - New Table not created

### ISSUE THREAD

**Issue by eduardoguilarducci** [hankinsoft/SQLPro#447]
When we try to import a CSV file with NEW TABLE, the creation table are not working.

Steps do reproduce:

Import CSV
Select New Table
Issue will be there

SO: Mac OS Mojave - 10.14.6
SQL PRO Studio: 2020.59 (build 110681)

<img width="420" alt="Screen Shot 2020-06-12 at 08 00 37" src="https://user-images.githubusercontent.com/1053355/84505326-edeb1d00-ac93-11ea-8cd0-a499887ffe9b.png">

<img width="630" alt="Screen Shot 2020-06-12 at 10 01 20" src="https://user-images.githubusercontent.com/1053355/84505339-f17ea400-ac93-11ea-962d-4ae4a5870d26.png">

**Comment by hankinsoft** [comment]
1. What type of database are you trying to import into? (SQLite, MySQL, other)?
2. Could you possibly provide the csv file?

**Comment by KODIKAS-NL** [comment]
I'm having the same issue.
If it try to import any csv and select to create a new table it fails with an "invalid object name" error.
I do see the table name appear briefly in the tree under the database, but after the import fails it does not exist anymore.
<img width="1291" alt="Screenshot 2020-06-17 at 09 58 08" src="https://user-images.githubusercontent.com/58047787/84871854-57e33800-b081-11ea-8b91-e971326432e5.png">

<img width="735" alt="Screenshot 2020-06-17 at 09 58 40" src="https://user-images.githubusercontent.com/58047787/84871893-67628100-b081-11ea-8e16-c679aeb2b999.png">

Running MS SQL 2019 on docker:
https://hub.docker.com/_/microsoft-mssql-server
image: 2019-GA-ubuntu-16.04

**Comment by eduardoguilarducci** [comment]
Hi @hankinsoft 

> 1. What type of database are you trying to import into? (SQLite, MySQL, other)?
SQLServer

<img width="152" alt="Screen Shot 2020-06-24 at 10 39 43" src="https://user-images.githubusercontent.com/1053355/85567189-08fc4c00-b607-11ea-9d91-866b8ff550cd.png">

> 2. Could you possibly provide the csv file?
Any CSV file, no matter how many columns or data type.

**Comment by hankinsoft** [comment]
I've reproduced this. Working on a fix now.

**Comment by KODIKAS-NL** [comment]
> I've reproduced this. Working on a fix now.

I justed installed the update from the app store and the import works again, thanks!

**Comment by eduardoguilarducci** [comment]
**On Version 2020.61 (Build 110688) the table creation worked very well.** 

But now, its reading empty cell's and insertin millions of unecessary records. 

I will create another issue. 

Thank you @hankinsoft
