### ISSUE TITLE
Combining fields not working

### ISSUE THREAD

**Issue by StatsGuy77** [hankinsoft/SQLPro#448]
Hi all,

I just got the licence and previously have only really used SQL Management Studio, so my issue is likely just learning the nuances of the different platforms.  I'm attempting to create a variable that uses a year (I've cast is as CHAR) and added string and a second year(cast as CHAR as well).  For example in the query I've written:
CASE
WHEN (Month IN 1,2,3) THEN CAST(Year - 1 AS CHAR) + ' - ' + CAST(Year AS CHAR)
WHEN (Month NOT IN 1,2,3) THEN CAST(Year AS CHAR) + ' - ' + CAST(Year +1 AS CHAR)
END AS [Fiscal Year]

My results are the addition of the years I attempt to combine in a text value.

Where am I going wrong?

Thanks,

Martin

**Comment by hankinsoft** [comment]
I think you want the [concat](https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-transact-sql?view=sql-server-ver15) function rather than using `+`. FYI, the platform (macOS/Windows) has no effect here - running SQL is sent to the server which processes the SQL and provides results/errors.
