### ISSUE TITLE
Suggestion: different background color per server

### ISSUE THREAD

**Issue by janjongboom** [hankinsoft/SQLPro#449]
I just bought SQLPro for Postgres, looks great so far. One thing that I would find helpful would be to set a different shade of f.e. the header per server. I might have a connection open to both my local dev server and to our production database, and I would like a visual cue of which server I'll be executing a command on.

F.e. something like this where you can change the shade of the header bar per connection and use the same one in the menu so that's clear:

![image](https://user-images.githubusercontent.com/816856/84874260-a3e3ac00-b084-11ea-832d-ec72d5384ae5.png)

**Comment by hankinsoft** [comment]
Do I have good news for you! Edit your connection and Choose a color below the 'alias' option:

<img width="489" alt="Screen Shot 2020-06-17 at 7 43 26 AM" src="https://user-images.githubusercontent.com/3160528/84888844-4ba1af80-b06e-11ea-8de8-30426dc52886.png">

The color will follow your connection everywhere. Connection dialog, database tree, tab, etc.

<img width="1046" alt="Screen Shot 2020-06-17 at 7 46 17 AM" src="https://user-images.githubusercontent.com/3160528/84889121-b7841800-b06e-11ea-8a6a-17f35b215d7c.png">

Let me know if that helps out!

**Comment by janjongboom** [comment]
@hankinsoft Perfect I hadn't realized that!

**Comment by hankinsoft** [comment]
> @hankinsoft Perfect I hadn't realized that!

No worries! Unfortunately I'm not great at advertising or documenting what features SQLPro has :)
