### ISSUE TITLE
SSH public/private key auth

### ISSUE THREAD

**Issue by Lozzano** [hankinsoft/SQLPro#45]
Hi there,

It states within the app that public/private key auth isn't available yet. Is there any ETA on when it would be available? Would love to test your app, but we only use keys for auth.

**Comment by hankinsoft** [comment]
I've had multiple using requesting this lately, so I will add it in soonish! No better ETA at the moment, as I've never worked with ssh via public key authentication, so I need to do some figuring out first.

**Comment by bdawson** [comment]
Bump

**Comment by hankinsoft** [comment]
Which product are you using? This features should be in everything but
MSSQL so far.

**Comment by bdawson** [comment]
I was trying out SQLPro Studio for the first time and couldn’t connect to a MySQL DB running on an Amazon EC2 instance. The db uses a pw but the connection to the server is made with a .pem file. Access denied. I quit trying when I came upon Lassano’s thread.

**Comment by hankinsoft** [comment]
All SQLPro apps have supported this for well over a year now. Anyone not seeing it, please ensure to update to the latest version.
