### ISSUE TITLE
App crashes after editing entry

### ISSUE THREAD

**Issue by Francis20** [hankinsoft/SQLPro#450]
Version 2020.59 (Build 4200.5) Editing data: After entering a value in a row the app crashes. (Mac version)

**Comment by alanwhiteley** [comment]
I am seeing the same problem with version 2020.59 (Build 4200.5). The app just crashes when entering data into one column value within a row and tabbing out to the next column. If I enter data in a column and press enter (to cease editing but not to move to the next column) the app does not crash, but scrolls back up to row 1 of the table (which is rather annoying when editing row thousands and something). Look forward to the fix.

**Comment by hankinsoft** [comment]
What type of database are the two of you connecting two? (MySQL, Postgres, MSSQL, etc)? I'm investigating the crash logs and have an idea what's going on, but I haven't been able to reproduce it yet. Just trying to narrow it down a bit further.

**Comment by Francis20** [comment]
Hello,

I‘m using SQLite,

have a good time

Herbert Dapper

**Comment by alanwhiteley** [comment]
SQLite too.

**Comment by hankinsoft** [comment]
FYI I've reproduced this and am working on the fix.

**Comment by hankinsoft** [comment]
I've got this fixed for the next build. The updated build should be available in ~24-48 hours.

**Comment by Francis20** [comment]
Hi Kyle,

that’s cool! Thank you very much!

Kindly

Herbert

**Comment by hankinsoft** [comment]
This is available in all the latest builds (2020.61). Is anyone still seeing the issue after updating to that version?

**Comment by alanwhiteley** [comment]
Appears to be fixed for me. Many thanks for sorting this out. Alan...
