### ISSUE TITLE
Favorite Queries Backup

### ISSUE THREAD

**Issue by chadburns** [hankinsoft/SQLPro#451]
Where are the "Favorites" or Favorite Queries stored, so that I can easily make a 2nd backup copy or make sure not to lose them when I change computers?

**Comment by hankinsoft** [comment]
Favorites are currently stored in the iCloud keychain - that means they should automatically transfer between devices as long as you have iCloud Keychain enabled on both (and are using the same iCloud account).

**Comment by chadburns** [comment]
Oh.  Awesome!  Thank you!

Chad
