### ISSUE TITLE
License key activation

### ISSUE THREAD

**Issue by tiffanyjsouthard** [hankinsoft/SQLPro#452]
Never received license key after purchase through Apple.

**Comment by hankinsoft** [comment]
Sorry for the delay on response.

You will not receive a license key when purchasing from the App Store. Instead your purchase is tied to the apple account used to make the purchase. Is you are being prompted only for a license key, then you might have the website version of the app installed. My suggestion would be to uninstall the app, then re-install it from the App Store. That should sort everything out.

**Comment by tiffanyjsouthard** [comment]
Thanks!  

It’s no longer prompting me for license key.
