### ISSUE TITLE
Feature Request: Snowflake: Recognize "//" comment syntax

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#456]
This query will run successfully if executed:
![image](https://user-images.githubusercontent.com/15026225/86035492-adacce00-b9f9-11ea-9e25-ba73c6596f3c.png)

Even though there is no comma between the column names, given that "//" is considered a comment in SnowSQL. It would be great to have the editor recognize this, so that the "Toggle Comment" shortcut works and so that the text looks disabled.

**Comment by hankinsoft** [comment]
Added for the next build.

<img width="230" alt="Screen Shot 2020-06-30 at 2 31 12 PM" src="https://user-images.githubusercontent.com/3160528/86157898-69dfc480-bade-11ea-82fc-92a8cabca57d.png">

**Comment by hankinsoft** [comment]
2020.61 is now available which adds this. If you get the chance, please give it a test and confirm its working as you would expect.

**Comment by jim256** [comment]
@hankinsoft, works great! Thanks a lot.

As an aside, when I'm the one who's opened an issue and you've completely resolved it, would you prefer that I be the one to close it or just post that it looks good to me and wait for you to close?

**Comment by hankinsoft** [comment]
> As an aside, when I'm the one who's opened an issue and you've completely resolved it, would you prefer that I be the one to close it or just post that it looks good to me and wait for you to close?

If you have opened the issue, and you have confirmed its sorted, feel free to close it out. Especially if no one else has commented in the issue. I usually try to post updated from 'think about it', 'working on it', 'fixed pending release', and 'its available'. Once I hit 'its available' if there is no feedback in a month or so, I close the issue myself.
