### ISSUE TITLE
Feature Request: Snowflake: Recognize "ZEROIFNULL" keyword

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#457]
It would be nice to have [this](https://docs.snowflake.com/en/sql-reference/functions/zeroifnull.html) recognized by autocomplete and highlighted by the SQL editor.

**Comment by hankinsoft** [comment]
Added for the next build.

**Comment by jim256** [comment]
@hankinsoft, awesome. I guess I'd add that if it's realistic to add any other missing keywords in bulk, that'd be great.

**Comment by hankinsoft** [comment]
Next build is now available which adds ZEROIFNULL. I haven't added all of the functions as I haven't found as easy way to copy them all.
