### ISSUE TITLE
Bug: Column names shifted horizontally in query results while query is executing

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#458]
During query execution, the first-most column is often (though not always) shifted horizontally to the left partway, cutting off part of the column header and the results.

The moment query execution finishes, the results shift themselves to display properly.

During query execution:
![image](https://user-images.githubusercontent.com/15026225/86036988-f6658680-b9fb-11ea-9ba9-86d3ba85c269.png)

After query execution:
![image](https://user-images.githubusercontent.com/15026225/86037009-fd8c9480-b9fb-11ea-9249-bbf7821c4fac.png)

Log file:
[com.hankinsoft.osx.sqlprostudio 2020-06-29--17-24-14-032.log](https://github.com/hankinsoft/SQLPro/files/4847093/com.hankinsoft.osx.sqlprostudio.2020-06-29--17-24-14-032.log)

SQLPro Studio 2020.59 (Build 110683.5)
macOS 10.15.5 (19F101)
Snowflake 4.21.3

**Comment by jim256** [comment]
While this is happening, I can manually scroll over to see everything just fine

**Comment by hankinsoft** [comment]
This has been fixed for a bit, sorry I forgot to mention it. If you get the chance, could you confirm if this is sorted for you?

**Comment by jim256** [comment]
Fixed for me. Thanks!
