### ISSUE TITLE
Feature Request: Enable multi-line editing

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#459]
It would be really convenient to be able to edit multiple lines at once (supporting CMD + arrow, typing new characters, etc.).

Currently, every single time I want to do this (which is relatively frequent), I copy the query to VS Code, do my editing, and come back:

![image](https://user-images.githubusercontent.com/15026225/86053775-43eeed00-ba16-11ea-978d-b335d08eff2c.png)

I personally really like the implementation in VS Code and would love to see the exact same thing in SQLPro Studio!

**Comment by hankinsoft** [comment]
Closing as a copy of #200 (which I noted I would re-open when it received more requests).
