### ISSUE TITLE
CSV choose text qualifiers

### ISSUE THREAD

**Issue by heruan** [hankinsoft/SQLPro#46]
I've bought SQLPro Studio from the Apple Store and when exporting data from a query to CSV, I can't choose which text qualifier to use, and if I export `varchar` data with `"` within it the CSV gets messed up. For example:

```
+----+------------+------------+
| ID | Text       | Date       |
+----+------------+------------+
| 11 | foo        | 2016-05-17 |
| 12 | foo, "bar" | 2016-05-17 |
+----+------------+------------+
```
I get this:
```csv
ID,Text,Date
11,foo,2016-05-17
12,"foo, "bar"",2016-05-17
```
Choosing a custom text qualifier (e.g. `'`) the output would be:
```csv
ID,Text,Date
11,foo,2016-05-17
12,'foo, "bar"',2016-05-17
```

**Comment by hankinsoft** [comment]
Thank you, I have reproduced this and will have a fix shortly.

**Comment by heruan** [comment]
Having also the possibility to use custom separator, it would be cool. The ideal for CSV export would be:

1. option to choose separator (<kbd>,</kbd>, <kbd>;</kbd>, <kbd>|</kbd>, <kbd>TAB</kbd>, etc.);
2. option to choose text qualifier (<kbd>"</kbd>, <kbd>'</kbd>, etc.);
3. option to enable the text qualifier for every field.

**Comment by hankinsoft** [comment]
I've got a first version that does the following:

1. Adds an option to pick a separator.
2. Adds an option to pick a qualifier.
3. Adds an option to include/disable headers.
4. Fixes escaping the text qualifier.

In your example of:
12,"foo, "bar"",2016-05-17    the export would now be (the qualifier is escaped by doubling the qualifier)
12,"foo, ""bar""",2016-05-17

The separator and qualifier can be picked from a dropdown or the user can enter a single character to use.

Preview gif here: http://g.recordit.co/zGQ0p7K2so.gif

You can download the build at: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.19.app.zip

If you get the chance, please give it a try and let me know if that does the trick for you.
You mentioned you purchased from the MAS. Please email kyle @ hankinsoft.com and I can provide you with a license key to use with the website download.

I have not added a per field text qualifier yet. I'm going to need to think about that one a bit more.

**Comment by heruan** [comment]
I've tested the trial: seems fine to me. I emailed for the license, thank you!
