### ISSUE TITLE
Feature Request: Autocomplete: More Generous Matching

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#461]
If I have two tables, one named report_daily_issues and another named report_issues, and I type in:

```
SELECT
	*
	
FROM
	report_iss
```

, I would like to see autocomplete suggest both tables. Currently, it will suggest only "report_issues".

**Comment by hankinsoft** [comment]
I believe this is fixed as of the new fuzzy autocomplete matching? Could you confirm if that is the case if you get the chance?

**Comment by jim256** [comment]
Looks like that did the trick.
