### ISSUE TITLE
Feature Request: Ask for password if session ends

### ISSUE THREAD

**Issue by PeteFox** [hankinsoft/SQLPro#463]
It would be helpful if the client could ask for a new password instead of completely killing a session when the password used stops working (for example if someone is using temporary password tokens).

```
FATAL:  PAM authentication failed for user "my_user"
FATAL:  pg_hba.conf rejects connection for host "xxx.xxx.xx.xxx", user "my_user", database "my_db", SSL off.
```

Currently this causes us to have to start a completely new session, and our queries in the previous session would have to be moved to the new one.

**Comment by hankinsoft** [comment]
Hi,
Few questions:

1. This is postgres?
2. The password that expires is the postgres users password? (Not a SSH tunnel or some other password)?
3. Do you save a password as part of the connection? Or do you leave that unchecked and enter it during the connection?
4. If you enter a new password, would you expect the connections saved password to be updated?

Thanks!

**Comment by PeteFox** [comment]
Hi, I'm sorry I didn't see your questions until now.

1: Yes
2: Yes
3: No - I leave it unchecked because the passwords are temporary tokens that work for x hours
4: No
