### ISSUE TITLE
Feature Request: Query Results Pane: Highlight row number when cell is selected

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#465]
When looking at a really wide table and/or using a really large screen, it'd be really handy to be able to have the row number(s) on the left highlight when you select cells in the query results pane.

Example:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/15026225/87087717-d6e70e80-c1f0-11ea-9c31-a39be8ea5e52.png">
I'd like to see the "1" in the red box have some sort of highlighting.

**Comment by hankinsoft** [comment]
This one is easy - I'll get it fixed similar to how text selection in the
query editor highlights the selected lines. Will post here once the next
build is available. That said, I am away next week so the build will be a
bit away.

**Comment by jim256** [comment]
@hankinsoft , I think you added this. I see that the row number gets a very very slight bold. I'd personally like something more easily-distinguishable. It doesn't quite jump out like I was hoping

**Comment by hankinsoft** [comment]
> I'd personally like something more easily-distinguishable. It doesn't quite jump out like I was hoping

I'm open to suggestions. Currently, I've made it match what the text editor does for highlighted lines.

**Comment by jim256** [comment]
Maybe just make the line number font a little larger and a little more bolded? Or add a minor outline to the whole row of the result set?

**Comment by jim256** [comment]
I've decided that I personally would like a minor/light border/outline around the whole row. Would make it extremely easy to do an exaggerated side swipe on the touchpad on a wide table and easily retain which row you were looking at.

**Comment by hankinsoft** [comment]
Sorry for the delay in responses lately. I've been working on BigSur and XCode 12 compatibility. I hope to have some responses out for some items soon.

**Comment by hankinsoft** [comment]
The latest build has this although I forgot to mention it in the release notes. In the following screenshot, row 7 has a slight background highlight:
<img width="1198" alt="Screen Shot 2021-11-08 at 8 56 48 AM" src="https://user-images.githubusercontent.com/3160528/140745914-fd213220-e683-4b7c-b615-b34b7c6f69fd.png">

It highlights based on the users highlight color system preference.

Please let me know if that does the trick.

**Comment by hankinsoft** [comment]
Going to close. If you happen to find this is not sorted, please let me know.
