### ISSUE TITLE
List in Favorite Not Appear

### ISSUE THREAD

**Issue by ppongsakorn** [hankinsoft/SQLPro#466]
I used SQLPro Studio via Setapp.
Version 2020.61 (Build 110688)
All query in favorite not appear.

<img width="815" alt="Screen Shot 2563-07-10 at 17 51 36" src="https://user-images.githubusercontent.com/3600474/87147020-176c8800-c2d6-11ea-9ccb-1efa7e514887.png">

**Comment by hankinsoft** [comment]
Have you switched computers? Favourites are stored `per device`.

**Comment by ppongsakorn** [comment]
I use the same laptop. it shown favorite connection (my connection) but not show favorite query.
Where is the path store favorite list?

**Comment by hankinsoft** [comment]
I've re-done how favourite queries are stored. Can you please update to the latest and let me know if this is still an on going issue?

**Comment by hankinsoft** [comment]
Going to close this. If you see the again once updated to the 2022.x version, please let me know.
