### ISSUE TITLE
Feature Request: Option to script table inserts with column list

### ISSUE THREAD

**Issue by RodeoChuck** [hankinsoft/SQLPro#467]
MSSql can not process table inserts commands that do not have a column list in them.  It would be a nice to be able to toggle a  preference so that when I right click a table and then Export > MySql > new window and run the output against another MSSql instance it will works. 

From MSSql:
An explicit value for the identity column in table 'dbo.MyNewTable' can only be specified when a column list is used....

**Comment by hankinsoft** [comment]
Hi,
This should be all sorted. If you get the chance, please give it a try in the latest version. Please let me know if you run into any issues.

**Comment by hankinsoft** [comment]
Closing. If this is found to still be an issue, please re-open.
