### ISSUE TITLE
Bug: SQLPro Studio on Mac extremely slow on load

### ISSUE THREAD

**Issue by kinnell** [hankinsoft/SQLPro#468]
I can't pinpoint which version this issue started to occur in, but in recent versions, whenever I open SQLPro Studio, it takes a few minutes for it to all load. All I get is the spinning pinwheel on this screen:

<img width="1316" alt="Screen Shot 2020-07-15 at 00 17 15@2x" src="https://user-images.githubusercontent.com/526343/87502884-d73c3b00-c630-11ea-8e65-3867c5065cfe.png">

It's getting really frustrating as one of the reasons I use SQLPro Studio is for its speed in being able to quickly run queries on various databases, but if it takes 3-4 minutes to load, then I need to start looking elsewhere for an alternative tool.

Attached is the logs.

[com.hankinsoft.osx.sqlprostudio 2020-07-15--04-16-18-115.log](https://github.com/hankinsoft/SQLPro/files/4922877/com.hankinsoft.osx.sqlprostudio.2020-07-15--04-16-18-115.log)

SQLPro Studio - Version 2020.61 (Build 110689)
macOS 10.15.5 (19F101)

**Comment by hankinsoft** [comment]
Sorry about that. Im away this week, but I will check the log as soon as I get back. I think a quick work around would be to change the ‘application startup’ preference to clean shutdown instead of restore state (I only have my phone at the moment so I’m not 100% sure what the preference is called).

**Comment by sariabod** [comment]
The setting is called "App shutdown" under General.
<img width="573" alt="Screen Shot 2020-07-15 at 2 22 27 PM" src="https://user-images.githubusercontent.com/1268903/87597601-ef4ea180-c6a6-11ea-8b11-d1e3071cf0b7.png">

**Comment by kinnell** [comment]
> Sorry about that. Im away this week, but I will check the log as soon as I get back. I think a quick work around would be to change the ‘application startup’ preference to clean shutdown instead of restore state (I only have my phone at the moment so I’m not 100% sure what the preference is called).

Hey @hankinsoft ! I updated that setting to "Clean shutdown" but unfortunately, the issue still persists.

Looking forward to hearing from you when you get a chance sometime next week.

**Comment by hankinsoft** [comment]
FYI I had a look at your log file and believe I see what's going on. I'm working on a fix for it.

**Comment by hankinsoft** [comment]
If you get the chance, could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.63.app.zip? The first load should be faster for sure as it will clear a cache. Once connected to a server/databases a new cache will be created and this would be if/when you would see the slowness (next startup). In addition to improving the speed, I've added additional logging, so if you do see this slowdown, please let me know.

**Comment by kinnell** [comment]
Hey Kyle, so the first load did take a while, but subsequent loads were much faster. Will the first load after every restart also be slow? Or will it be this fast going forward?

Could this have something to do with the fact that some of the connections I have pre-configured aren't always connectable every time I load the app? Some of them require a VPN connection to actually connect, others I have set up for specific docker containers, so depending on which ones I have running, some of my configured connections will always be offline. In the past, this hasn't been an issue with boot time for the app, but just throwing that out there.

**Comment by hankinsoft** [comment]
Hi,
So the underlying issue was due to a change for #190 and #404. Basically I had added an autocomplete cache, so that autocomplete is only updated on launch once every 24 hours, otherwise its taken from a saved cache (autocomplete is also updated if the user force refresh's the server or database node and hits refresh, or makes a change/adds/removes a table).

Loading the autocomplete cache was slow on a large dataset. The speed you are seeing now, should be the speed you continue to see.

If you get the chance, the next time you re-launch the app, could you send me the log file? You can find it by going to 'view' -> 'logs'. I can be emailed via kyle @ hankinsoft.com. I just want to check and see what speeds your getting now and see if I can tweak anything else.

**Comment by kinnell** [comment]
Hey Kyle,

Sorry for not responding earlier, but I'm running into this error again. I was having issues again on `2020.63` so I updated to `2020.72` to see if that would resolve my issues, but alas, I'm still having issues.

Basically takes over a minute again on every load. 

From my understanding, the lag is due to a autocomplete cache refresh. I disabled autocomplete and restarted the app, but I still have the same issues. From the logs, I'm still seeing AutocompleteCache getting updated despite autocomplete being turned off.

As I may have conveyed in the past, I prefer using SQLPro Studio over VSCode/Azure Data Studios because of the speed/performance. I do most of my SQL writing in VSCode, but for quickly troubleshooting issues and querying on specific databases, SQLPro Studio has been a blessing. However, 1 minute of app load significantly hurts my productivity. As mentioned above, many of my connections require a VPN connection, but I don't always need to be connected because I can work on a local Docker container for development work. Yet the logs seem to indicate that attempts are made to refresh autocomplete cache on all connections, despite most of them not even being accessible. Even if the autocomplete cache is taken from a saved cache, there's no need because I can't connect to that connection anyways to be able to utilize autocomplete.

If there was to be an autocomplete cache refresh, I would expect it to only take place if autocomplete is enabled and it should take place in the background and not on app load. Making sure autocomplete cache is up to date isn't critical to block a user from using the app. I understand that other users may want more powerful autocomplete functionality like in #404 but if it increases cache refresh times for everyone, it should be an opt-in preference given not all your users require it.

Here's the log:

[com.hankinsoft.osx.sqlprostudio 2020-08-26--20-02-36-966.log](https://github.com/hankinsoft/SQLPro/files/5137632/com.hankinsoft.osx.sqlprostudio.2020-08-26--20-02-36-966.log)

**Comment by hankinsoft** [comment]
Hi,
I've made a few changes around this for the latest version.

1. It should be faster and now runs on a background thread (you should see no delay).
2. Disabling autocomplete disables this.

> I understand that other users may want more powerful autocomplete functionality like in #404 but if it increases cache refresh times for everyone, it should be an opt-in preference given not all your users require it.

Completely agreed! I thought my performance testing with this was enough to cover the larger datasets, but looking at your log files, I completely under-estimated a 'large cache' size. I believe that item 1 above should basically make the autocomplete cache invisible too you.

Please let me know!

**Comment by kinnell** [comment]
Hey Kyle, that's great to hear! Is that build with those aforementioned changes released? I haven't gotten an update notification and the version from the website is still `2020.72`. Let me know if you have a timeline for release if you haven't had a chance to release it yet.

**Comment by hankinsoft** [comment]
FYI I've done a bunch of changes to autocomplete, from limiting the amount of cached data to having the processing run in the background. Please let me know if you still run into autocomplete delays when using one of the latest versions.
