### ISSUE TITLE
Bug: Autocomplete and syntax highlighting not recognizing "COALESCE"

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#469]
The word COALESCE is not colorized and autocomplete does not suggest it.

SQLPro Studio 2020.61 (Build 110689.5)
macOS 10.15.5 (19F101)
Snowflake 4.24.1

**Comment by hankinsoft** [comment]
Added for the next build.

**Comment by jim256** [comment]
@hankinsoft , looks like it's colorized, but autocomplete still does not suggest

**Comment by hankinsoft** [comment]
Can you check if autocomplete is suggesting it now?

**Comment by jim256** [comment]
@hankinsoft just tested it, and it is not.

SQLPro Studio 2020.77 (Build 110714.5)
macOS 10.15.6 (19G2021)
Snowflake 4.31.2

**Comment by jim256** [comment]
Looks like it is now for Snowflake, but not for Postgres.

As a side note, Postgres also doesn't suggest / recognize `CURRENT_TIMESTAMP`

Let me know if you'd like me to open a separate issue for these?

Postgres 10.13
2020.96 (Build 110739)
macOS 11.0.1 (20B29)

**Comment by hankinsoft** [comment]
Fixed in submitted build (2021.56).

**Comment by jim256** [comment]
Seems to be fixed.
