### ISSUE TITLE
SQLPro Crashes when changing appearance Version 2020.61 (Build 10512.5)

### ISSUE THREAD

**Issue by HitTrax** [hankinsoft/SQLPro#470]
Change  fonts, create or edit appearance crashes app on Macbook Pro 2013
Version 2020.61 (Build 10512.5)

![Screenshot 2020-07-15 at 4 59 38 pm   Date  15-07-2020](https://user-images.githubusercontent.com/68416378/87756620-94ef4580-c84c-11ea-99a8-9dc1adb600ff.png)
![Screenshot 2020-07-15 at 5 02 14 pm   Date  15-07-2020](https://user-images.githubusercontent.com/68416378/87756628-97ea3600-c84c-11ea-8054-ec31195e4307.png)
![Screenshot 2020-07-15 at 5 02 22 pm   Date  15-07-2020](https://user-images.githubusercontent.com/68416378/87756631-99b3f980-c84c-11ea-96b7-5acc11b2be24.png)

**Comment by mishu017** [comment]
> Change  fonts, create or edit appearance crashes app on Macbook Pro 2013
> 
> Version 2020.61 (Build 10512.5)
> 
> 
> 
> ![Screenshot 2020-07-15 at 4 59 38 pm   Date  15-07-2020](https://user-images.githubusercontent.com/68416378/87756620-94ef4580-c84c-11ea-99a8-9dc1adb600ff.png)
> 
> ![Screenshot 2020-07-15 at 5 02 14 pm   Date  15-07-2020](https://user-images.githubusercontent.com/68416378/87756628-97ea3600-c84c-11ea-8054-ec31195e4307.png)
> 
> ![Screenshot 2020-07-15 at 5 02 22 pm   Date  15-07-2020](https://user-images.githubusercontent.com/68416378/87756631-99b3f980-c84c-11ea-96b7-5acc11b2be24.png)
> 
> 


Support []()

**Comment by hankinsoft** [comment]
Sorry for the delay - I have been away this week (and still am). I hope to have this sorted early next week.

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.64.app.zip and see if that helps out?

**Comment by HitTrax** [comment]
Hello Kyle. Thank you. The issue is resolved with this version.

Regards John Ialuna
Hit Trax MIDI Files


On 23 Jul 2020, at 2:26 am Thu, 23 Jul 20, Kyle Hankinson <notifications@github.com> wrote:


Could you try https://sqlprostudio.s3.us-east-1.amazonaws.com/studio/SQLProStudio.2020.64.app.zip <https://sqlprostudio.s3.us-east-1.amazonaws.com/studio/SQLProStudio.2020.64.app.zip> and see if that helps out?

**Comment by HitTrax** [comment]
Hello Kyle.

I am being prompted to purchase a licence. Does my existing license for SQLPro for MSSQL cove this new app?

Regards, John Ialuna
Hit Trax MIDI Files & MP3 Backing Tracks

Email:	email@MIDI.com.au
Web:	www.MIDI.com.au
SKYPE:	HitTrax

On 23 Jul 2020, at 2:26 am Thu, 23 Jul 20, Kyle Hankinson <notifications@github.com> wrote:


Could you try https://sqlprostudio.s3.us-east-1.amazonaws.com/studio/SQLProStudio.2020.64.app.zip <https://sqlprostudio.s3.us-east-1.amazonaws.com/studio/SQLProStudio.2020.64.app.zip> and see if that helps out?

**Comment by hankinsoft** [comment]
Hi,
MSSQL is available here: https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.2020.65.app.zip

**Comment by HitTrax** [comment]
Thanks Kyle.

The crashing issue is resolved however changing font size in the query window does not change and apply. Font size works in the results window only.

Regards, John Ialuna
Hit Trax


On 26 Jul 2020, at 2:01 am Sun, 26 Jul 20, Kyle Hankinson <notifications@github.com> wrote:


Hi,
MSSQL is available here: https://sqlprostudio.s3.us-east-1.amazonaws.com/mssql/SQLProMSSQL.2020.65.app.zip <https://sqlprostudio.s3.us-east-1.amazonaws.com/mssql/SQLProMSSQL.2020.65.app.zip>

**Comment by HitTrax** [comment]
Hello Kyle

The app still crashes when updating Preferences>Appearance>Query Editor on MAC OS Mojave 10.14.6 . Is it possible to have this fixed? I have impaired sight and th font is too small to work with.

Regards, John Ialuna
Hit Trax

On 26 Jul 2020, at 2:01 am Sun, 26 Jul 20, Kyle Hankinson <notifications@github.com> wrote:


Hi,
MSSQL is available here: https://sqlprostudio.s3.us-east-1.amazonaws.com/mssql/SQLProMSSQL.2020.65.app.zip <https://sqlprostudio.s3.us-east-1.amazonaws.com/mssql/SQLProMSSQL.2020.65.app.zip>

**Comment by hankinsoft** [comment]
Investigating this now. I might have a few more questions shortly.

**Comment by hankinsoft** [comment]
Hi,
I haven't been able to reproduce this as of yet. When you launch the preferences, are any of the themes highlighted on the left side?

**Comment by hankinsoft** [comment]
Also, is the app crashing, or not applying your font size?

**Comment by hankinsoft** [comment]
I've uploaded https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.2020.66.app.zip. Can you give that a try and see if it helps?

**Comment by HitTrax** [comment]
Hello Kyle.

The app becomes non-responsive in the QUERY window when any query theme is selected. 

NOTE - font name in query window  shows ‘.’ preceding the font name. This is he window that makes the app non-responsive.

The Results window displays the correct font name and I can change settings in the RESULTS window without affecting the app.

Regards, John Ialuna 



On 29 Jul 2020, at 2:09 am Wed, 29 Jul 20, Kyle Hankinson <notifications@github.com> wrote:






Hi,
I haven't been able to reproduce this as of yet. When you launch the preferences, are any of the themes highlighted on the left side?

Also, is the app crashing, or not applying your font size?

**Comment by hankinsoft** [comment]
Sorry, this issue got lost in my head as resolved. Could you update to the latest version and see if you are still seeing this? If so, would you consider the option of setting up a screen sharing sessing with me? I think that would help me figure out whats up.

**Comment by HitTrax** [comment]
Hello Kyle.

The issue is resolved, thank you.

Regards, John Ialuna
Hit Trax MIDI Files


On 29 Sep 2020, at 11:54 pm Tue, 29 Sep 20, Kyle Hankinson <notifications@github.com> wrote:


Sorry, this issue got lost in my head as resolved. Could you update to the latest version and see if you are still seeing this? If so, would you consider the option of setting up a screen sharing sessing with me? I think that would help me figure out whats up.
