### ISSUE TITLE
Feature Request: Autocomplete: Allow reverse cycling in suggestion list

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#473]
It would be great to be able to hit the up arrow on the keyboard when on the first item in the autocomplete suggestion list and have it go to the bottom of the list. It would also be nice to be able to hit the down arrow when on the last item in the list and have it loop back to the top.

**Comment by hankinsoft** [comment]
Added for the next build.

**Comment by jim256** [comment]
@hankinsoft Thanks for adding this! Closing.
