### ISSUE TITLE
Crash when exporting a database

### ISSUE THREAD

**Issue by spicymatt** [hankinsoft/SQLPro#477]
The app crashes when exporting to JSON and XML.

[Crashlogs.zip](https://github.com/hankinsoft/SQLPro/files/5001928/Crashlogs.zip)

**Comment by hankinsoft** [comment]
Thank you! I'll take a look and get back to you.

**Comment by spicymatt** [comment]
here is a sample database
please fix as it is a regression from previous versions 
[74A2AC80-1FD5-4644-B3B0-63DF65150B41.lrcat.zip](https://github.com/hankinsoft/SQLPro/files/5008724/74A2AC80-1FD5-4644-B3B0-63DF65150B41.lrcat.zip)

**Comment by hankinsoft** [comment]
A few questions:

1. Are you using the export button at the top right of the app interface, or right clicking on a table and choosing export?
2. Does the app crash as soon as you do this, or do you get prompted to choose a directory to export to first?

(I haven't been able to reproduce this - I'm able to export the database you provided with no issues, so I'm still trying to figure out whats up).

**Comment by spicymatt** [comment]
Data > Export > Json : crashes immediately, without prompt
I can run the export using the "Lite" version
The crash is systematic
I also tried when right clicking on just 1 table. It crashes as well.

**Comment by hankinsoft** [comment]
I've pushed a new version of the app live. Can you check and see if the issue is sorted?

**Comment by spicymatt** [comment]
hello

it seems to work now. Thanks

matthieu
