### ISSUE TITLE
How can I configure connection setting of  port number of Oracle Server?

### ISSUE THREAD

**Issue by msjuck** [hankinsoft/SQLPro#479]
Hello, I use SQLPro Studio Version 2020.61 (Build 110689.5)with a Premium license.

I just create a new connection of the oracle server with port number 11521.

But I can't find port configuration in connection setting.

How can I configure connection setting of  port number of Oracle Server?

Thank you.

**Comment by hankinsoft** [comment]
Hi,
For setting the port in oracle, enter the host as the format of:
hostname:port

So if it was myserver.com port 1234, you would enter
myserver.com:1234

Please let me know if that helps out.
