### ISSUE TITLE
Autocomplete Removes Line on some cases

### ISSUE THREAD

**Issue by sinklair** [hankinsoft/SQLPro#481]
I have been reliably able to reproduce this using `aa` as a table alias. See demo here: https://jmp.sh/7C57z6f

Repro Steps
1. Create a SELECT query with no fields selected but with a table name aliased as `aa`
2. Make sure the FROM clause is on a new line
3. After the word SELECT, type a space and the letter `a` - autocomplete starts
4. Autocomplete the word `aa` or press `a` again

Result: Carriage return is removed from text

Expected: Carriage return remains

**Comment by sinklair** [comment]
This applies also in some circumstances when I'm trying to alias a field using the `as` keywork. Autocomplete on `as` is removing any trailing carriage return.

**Comment by hankinsoft** [comment]
Thank you (especially for the video). I've reproduced and am working on a fix now.

**Comment by hankinsoft** [comment]
Fixed for the next build. Interestingly, the issue was due to the `aa` alias (or any table/alias of repeating letters - ie bb, cc, zzzzz, etc).

**Comment by hankinsoft** [comment]
The new build has been up for a few days - if you get a chance, could you give this a try?

**Comment by sinklair** [comment]
Confirmed. Issue is resolved. Thanks so much
