### ISSUE TITLE
Stored Procedure body is being cropped

### ISSUE THREAD

**Issue by flouback** [hankinsoft/SQLPro#482]
version 2020.66 (build 110697) - SetApp subscription

Stored Procedure body is being cropped after running in SQLPro Studio, 
resulting in head only procedure ... both in editor and database.

It seems to have influence on this statement ...
SET NOCOUNT ON;

Removing it, works. This issue in recently, I've been using the same procedure in previous versions of 
SQLPro Studio with out problems.

**Comment by hankinsoft** [comment]
Hi,
Any chance I could get the full procedure? You can post it or email it to
me via kyle @ hankinsoft.com. That should help me figure out what’s up.

Cheers,
Kyle

**Comment by hankinsoft** [comment]
I believe https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.73.app.zip will sort this out.
