### ISSUE TITLE
Overwrite Mode

### ISSUE THREAD

**Issue by timthacker63** [hankinsoft/SQLPro#483]
This could be me not doing something correct. But all paste are now in an overwrite mode instead of insert. If I have a blank space and paste a multi-line code it will create as an overwrite instead of insert. Line 14 shows before and after.

<img width="1132" alt="Screen Shot 2020-08-10 at 12 39 22 PM" src="https://user-images.githubusercontent.com/11658141/89807433-9a1b7980-db06-11ea-84f5-c53c9a4f4d9f.png"> 

<img width="1132" alt="Screen Shot 2020-08-10 at 12 39 39 PM" src="https://user-images.githubusercontent.com/11658141/89807418-9687f280-db06-11ea-81b6-0d894b567fc9.png">

**Comment by hankinsoft** [comment]
Hmm, sorry about that. I'm investigating this now.

**Comment by hankinsoft** [comment]
Reproduced and working on the fix. Which SQLPro app are you using and is it from the App Store or Website (I'll get that build available first).

**Comment by timthacker63** [comment]
I think I got it from the App Store.

**Comment by hankinsoft** [comment]
The fixed build has been available for a bit - can you confirm that you are no longer seeing this behaviour?

**Comment by timthacker63** [comment]
Seems to be working great. Thanks!
