### ISSUE TITLE
Disable Multiple Cursor support

### ISSUE THREAD

**Issue by glukow** [hankinsoft/SQLPro#484]
Is there a way to disable/turn off multiple cursor support? It seems like anytime I attempt copy and past a few lines of sql, the editor goes into multiple cursor support and the formatting of what I was copying and pasting gets messed up.

I'm using SQLPro for MSSQL Version 2020.68 (Build 10519.5)

**Comment by hankinsoft** [comment]
Hi. Sorry about that, there was a bug with the initial version. If you are
using the website version, a new build is already available. The app store
build has been submitted, it just needs to be approved by Apple (this
generally happens within 24 hours).

**Comment by glukow** [comment]
Version 2020.71 correct this issue.
