### ISSUE TITLE
Scalar Value Error on line that doesn't exist

### ISSUE THREAD

**Issue by Shanew27** [hankinsoft/SQLPro#485]
Msg 137, Level 15, State 2.
Must declare the scalar variable "@result". (Line 63)

32 lines of sql @result declared on line 6
execution on last line 32

![image](https://user-images.githubusercontent.com/46818968/90413940-bf633700-e074-11ea-8026-8976dad25d06.png)

**Comment by hankinsoft** [comment]
Thank you - I've reproduced and am working on a fix.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.73.app.zip? That should sort it.

**Comment by Shanew27** [comment]
Yes, this works great thank you

**Comment by Shanew27** [comment]
When will a fix be pushed out. The trial that you sent is expired and your product is useless to me. Can you provide a prorated refund of my app store purchase?

Shane

**Comment by Shanew27** [comment]
Is there an update on a fix?

**Comment by hankinsoft** [comment]
Hi,
The fix should already be available - you need to remove the version I sent and switch back to the app store version of the app.

**Comment by hankinsoft** [comment]
> Can you provide a prorated refund of my app store purchase?
For app store refunds, you would need to contact Apple directly via the 'Report a problem' link on the initial app store receipt.

**Comment by Shanew27** [comment]
Ok, I will try but the app store is still showing the same version I have installed, 2020.72. You sent me a 2020.73 version and have already uninstalled it because it was a trial version there are no fixes in the app store the newest is the same version I have the issue with.  Am I missing something? I’m willing to try something different if you can guide me.

Shane

[cid:image001.png@01D685D6.D21FC000]

[cid:image002.png@01D685D6.D21FC000]
[cid:image003.png@01D685D6.D21FC000]

**Comment by Shanew27** [comment]
I honestly just want it fixed so I can use a product I used to absolutely love. There was no better product until the current version.

Shane

**Comment by Shanew27** [comment]
Yes, that is correct.

Shane

**Comment by hankinsoft** [comment]
Looks like that one didn't get updated. I'll get it submitted to apple right now. It usually takes ~24 hours for the update to become available. Sorry about that, I didn't realize that was the one you were using.

**Comment by Shanew27** [comment]
No problem, I appreciate you taking care of it.

Shane

**Comment by hankinsoft** [comment]
FYI 2020.76 is now available on the app store. If you get the chance, please give it a try and confirm if we are all set.
