### ISSUE TITLE
Some views, but not all, have duplicated field lists in left database tree

### ISSUE THREAD

**Issue by stevetjamisonTM** [hankinsoft/SQLPro#487]
I'm seeing that some views, but not all, show a duplicated list of fields in the database tree. When this happens, the full set of fields are listed again, in the same order, just after the first set. This would look like:

field1
field2
field3
field1
field2
field3

**Comment by hankinsoft** [comment]
Thanks - this is with PostgreSQL?

**Comment by stevetjamisonTM** [comment]
Sorry -- Redshift. So similar to postgresSQL, but not exactly. I'm using SQLPro for Postgres Version 2020.73 (Build 1047816), though this was happening in older versions as well.

**Comment by hankinsoft** [comment]
If you run this query:

```
SELECT 
	attname AS column_name, 
	format_type(atttypid, atttypmod) AS column_type, 
	NOT attnotnull AS is_nullable, 
	pg_index.indexrelid AS is_pk, -- primary key index id
    (SELECT DISTINCT substring(pg_catalog.pg_get_expr(d.adbin, d.adrelid) for 128)
                                    FROM pg_catalog.pg_attrdef d
                                    WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum AND a.atthasdef) AS default_value
FROM 
	pg_attribute AS a
	LEFT OUTER JOIN pg_index ON a.attrelid = pg_index.indrelid 
	AND indisprimary 
	AND a.attnum = ANY(string_to_array(textin(int2vectorout (indkey)), ' ')::int[]) 
WHERE 
	attrelid = '{ESCAPED_TABLE_PATH}'::regclass
	AND attnum > 0 
	AND NOT attisdropped;
```

And replace `{ESCAPED_TABLE_PATH}` with your schema.viewName, do you receive the duplicate columns?

**Comment by stevetjamisonTM** [comment]
I do not get dupes with that query.

**Comment by hankinsoft** [comment]
Hmmm ok. And these are just regular views, not materialized or external views you are seeing the dupes with?

**Comment by stevetjamisonTM** [comment]
Yep -- regular views.

**Comment by hankinsoft** [comment]
Hi, sorry for the delays on this. Would it be possible for you to share a screenshot of the database tree showing the duplicate columns? I'm just trying to figure out if I can see anything which may cause the issue.

**Comment by stevetjamisonTM** [comment]
Here's a test view I created, and an image of the tree.

```
create view dev.test_view
as select null as column1, 
	null as column2
```

![image](https://user-images.githubusercontent.com/32876441/108448107-1ff34c80-722f-11eb-9705-8da9497153a2.png)

**Comment by stevetjamisonTM** [comment]
I'm currently using SQLPro for Postgres `Version 2020.73 (Build 1047816)`

**Comment by hankinsoft** [comment]
If you get the chance, could you download: https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.2021.14.app.zip

and give that a try?

**Comment by stevetjamisonTM** [comment]
Looks good on my end, thank you!

On Fri, Feb 19, 2021 at 10:01 AM Kyle Hankinson <notifications@github.com>
wrote:

> If you get the chance, could you download:
> https://sqlprostudio.s3.us-east-1.amazonaws.com/postgres/SQLProPostgres.2021.14.app.zip
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__sqlprostudio.s3.us-2Deast-2D1.amazonaws.com_postgres_SQLProPostgres.2021.14.app.zip&d=DwMCaQ&c=FzKP-epUFUaLJmW5WcADWkbVOTbLc04gxpGZ8RZoG3o&r=1Gd7p7pPxVJeozddaA1WaCjXfcLdXLfu6SKwbwDb-S4&m=_vxZidFqjft-E-jrXGaXwj_X7oU8h3k9ZIhtmq1dwU8&s=hLaVrATg9Miid_FMErM6wxboxcxin-fWwcj9N3avwHE&e=>
>
> and give that a try?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hankinsoft_SQLPro_issues_487-23issuecomment-2D782128966&d=DwMCaQ&c=FzKP-epUFUaLJmW5WcADWkbVOTbLc04gxpGZ8RZoG3o&r=1Gd7p7pPxVJeozddaA1WaCjXfcLdXLfu6SKwbwDb-S4&m=_vxZidFqjft-E-jrXGaXwj_X7oU8h3k9ZIhtmq1dwU8&s=m_K2GCVd-QAGDlfr38hUFZ71bhdpyUPRw6jOQksVC3w&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH22PGMRLWP7CP4TRRJ4XHDS7Z4MXANCNFSM4QF43U3A&d=DwMCaQ&c=FzKP-epUFUaLJmW5WcADWkbVOTbLc04gxpGZ8RZoG3o&r=1Gd7p7pPxVJeozddaA1WaCjXfcLdXLfu6SKwbwDb-S4&m=_vxZidFqjft-E-jrXGaXwj_X7oU8h3k9ZIhtmq1dwU8&s=Pg8KmSic1JO2Wl0t4UGCxN1h14-AlHUUJmvRaTs0Ijo&e=>
> .
>


-- 
*Steve Jamison, PhD*
Manager, Analytics
TrueMotion, Inc.
stevej@gotruemotion.com

Follow us on LinkedIn! <https://www.linkedin.com/company/truemotion/>




*Get in the game - save the shoes!
<http://www.ted.com/talks/mark_bezos_a_life_lesson_from_a_volunteer_firefighter.html>*

**Comment by hankinsoft** [comment]
Great, thank you for letting me know.
