### ISSUE TITLE
Sqlite: Delete Rows UI improperly escapes single-quotes in fields

### ISSUE THREAD

**Issue by grahams** [hankinsoft/SQLPro#488]
If I have a field containing a single quote, and then try to delete that row using the minus button in the UI, the delete will fail because the single quote is improperly escaped:

The broken query:
```DELETE FROM MyNewTable WHERE  test = 'this is another\' test';```

Instead of escaping the quote with `\'` it should instead be `''`

So, the query should be:
```DELETE FROM MyNewTable WHERE  test = 'this is another'' test';```

I've attached a simple db you can use to test this.
[escapetest.sqlite.zip](https://github.com/hankinsoft/SQLPro/files/5124613/escapetest.sqlite.zip)

Let me know if there's any other ifnormation I can provide.

**Comment by hankinsoft** [comment]
Sorry for the delay. I've got this fixed for the next build which should be available early next week.

**Comment by hankinsoft** [comment]
When you get the chance, please give the latest update a try and let me know if this issue has been resolved for you.

**Comment by grahams** [comment]
Looks good!  Thanks!
