### ISSUE TITLE
SQLPro for Oracle should support SSH tunneling (like SQLPro for MySQL)

### ISSUE THREAD

**Issue by heyitsbarry** [hankinsoft/SQLPro#49]
Hopefully this is a lightweight feature request, since support exists on other SQLPro apps.  Thanks!

**Comment by hankinsoft** [comment]
I'm not a big oracle user, so I was not sure if tunnelling would make sense or not. I will add this in for the next release!

**Comment by heyitsbarry** [comment]
Hey Kyle- thanks for the quick response.  I'm not usually a big Oracle user either, but I was running into firewall issues that require tunneling...
Thanks again!

**Comment by hankinsoft** [comment]
Hi. SSH Tunnelling for Oracle has been added for awhile now, I just forgot to close the issue.
