### ISSUE TITLE
Shows field names as row values

### ISSUE THREAD

**Issue by tewe** [hankinsoft/SQLPro#490]
SQLPro for SQLite 2020.61 on macOS 10.14.6 does not work with files created by https://www.apimac.com/mac/idatabase/ 6.2

Its tabular display repeats the field names for every row, instead of the actual values.

<img width="1508" alt="Screenshot 2020-08-31 at 15 08 45" src="https://user-images.githubusercontent.com/645412/91723767-91b1de00-eb9c-11ea-88f8-34d39e52ba23.png">

Compare with the CLI.

```
sqlite3 database.db 

SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.

sqlite> SELECT * from data_table;

1|1598879245.68885|1598879275.38351|A service|My username|Some e-mail|HTTP||Hello|What password
```

I used the included Accounts template for this sample, but can reproduce it with other databases.

[database.zip](https://github.com/hankinsoft/SQLPro/files/5150436/database.zip)

**Comment by hankinsoft** [comment]
Could you possibly post the DDL of that table? Or better yet, include the
database?

**Comment by tewe** [comment]
I attached the database a minute after creating the issue. Please don't use GitHub via e-mail.

**Comment by hankinsoft** [comment]
Can you give
https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2020.75.app.zip
a try? If you confirm that sorts it out, I will also get the app store
version updated as well.

**Comment by tewe** [comment]
2020.75 works for me. Thanks!
