### ISSUE TITLE
Snowflake: "DATE" always unnecessarily-escaped in double quotes.

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#492]
Whenever I accept an autocomplete suggestion for a column named 'DATE', it always inserts it with double quotes:
`SELECT "DATE"`

This also applies for a few others such as 'MONTH', 'YEAR', etc. These aren't reserved words in Snowflake and can be used without escaping. It would be nice to have this disabled for non-reserved words :)

SQLPro Studio 2020.75 (Build 110709.5)
macOS 10.15.6 (19G2021)
Snowflake 4.31.1

**Comment by hankinsoft** [comment]
Fixed for the next build.

**Comment by jim256** [comment]
Seems to be working well. Thanks.
