### ISSUE TITLE
Window Functions not colorized in editor nor suggested in autocomplete

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#495]
Window functions and their syntax don't seem to suggested nor colorized

![image](https://user-images.githubusercontent.com/15026225/92759809-573f0280-f34d-11ea-8cad-a6c58a43a9a5.png)

MySQL 8.0.21
Snowflake 4.31.2
macOS 10.15.6 (19G2021)
SQLPro Studio 2020.77 (Build 110714.5)

FWIW, they are both suggested and colorized on Postgres 10.

**Comment by hankinsoft** [comment]
Added for the next build.

**Comment by jim256** [comment]
Seems to be working well. Thanks.
