### ISSUE TITLE
Columns or any other Table properties not showing / accessible

### ISSUE THREAD

**Issue by Elratheon** [hankinsoft/SQLPro#496]
Im using SQL Pro Studio to access Azure (MSSQL).

Some of table, can show the column names (see picture below), some of table is not showing.

If the column names is not showing, the scripting command of "Create To" also not showing any columns in the result.

<img width="802" alt="Screen Shot 2020-09-14 at 16 36 58" src="https://user-images.githubusercontent.com/71258982/93070152-b59b1680-f6a8-11ea-81d0-7cebe51b3858.png">

Now I understand that it work only if the table name is not using any period (.) in the name. So it works for Accounting.[COA], but not working for Accounting.[Journal.Header]

My prediction is somehow may be in the code, somebody forgetting to use the bracket '[ ]' 

More over, if I'm using "select top 1000 rows" command for a table that has one period in the name, it will not working well,  **in which the table name in the script is not using bracket**

<img width="1362" alt="Screen Shot 2020-09-14 at 16 42 00" src="https://user-images.githubusercontent.com/71258982/93070612-483bb580-f6a9-11ea-82cf-ee5e51eab12f.png">

however, if I'm using "select top 1000 rows" command for a table that has more thane one period in the name, it will working well, **in which the table name in the script is using bracket**

<img width="1362" alt="Screen Shot 2020-09-14 at 16 42 21" src="https://user-images.githubusercontent.com/71258982/93070740-73bea000-f6a9-11ea-8b26-8439b4823d84.png">

**Comment by hankinsoft** [comment]
Could you give this version a try and see if it helps out:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.79.app.zip

**Comment by Elratheon** [comment]
Hi,

Yes, it works nicely now.

Just fyi, I noticed though, the table "refresh" menu shortcut did not work.
So the table that previously expanded in the left pane, can not restore the
columns even after refresh. However the database "refresh" shortcut command
works nicely. Well done, thank you

Regards

**Comment by hankinsoft** [comment]
Refresh has been fixed for the next build.
