### ISSUE TITLE
Export to CSV using Pipe Not Working

### ISSUE THREAD

**Issue by diek** [hankinsoft/SQLPro#498]
I love the pipe because many files are riddled with commas and I read #262, but it is not working. I attempted to export twice to csv with pipe, each time it just used a comma.

![Screen Shot 2020-09-17 at 01 16 34](https://user-images.githubusercontent.com/1261158/93419567-88ef2680-f883-11ea-9fce-ef95a12b2951.png)
<img width="1156" alt="Screen Shot 2020-09-17 at 01 19 11" src="https://user-images.githubusercontent.com/1261158/93419682-d79cc080-f883-11ea-80f0-0a2fe410f182.png">

**Comment by hankinsoft** [comment]
Fixed for the next build. Should be available later this week.

**Comment by diek** [comment]
I just tested it, worked perfectly. Thanks for resolving the issue :)
