### ISSUE TITLE
I purchased, but not received license

### ISSUE THREAD

**Issue by kinglezhuang** [hankinsoft/SQLPro#499]
Order number: 093702111159

I downloaded the app from https://www.sqlitepro.com & then installed it.
After i pressed the license through menu, click purchase & jump to website for payment.
I filled my email: kinglezhuang@vip.qq.com, firstname: kingle, lastname: zhuang & pay it.
No response & not received license key

**Comment by hankinsoft** [comment]
Hi.
Have you received the license? I see a purchase went through a few hours after this issue was posted.

**Comment by kinglezhuang** [comment]
> Hi.
> Have you received the license? I see a purchase went through a few hours after this issue was posted.

Not yet, i lose my money

**Comment by kinglezhuang** [comment]
I receive now, too later
