### ISSUE TITLE
'Unknown type. 241.' for version 1.0.86 of SQL Pro for MSSQL for columns with datatype xml

### ISSUE THREAD

**Issue by tim-hoffmann** [hankinsoft/SQLPro#50]
Hi,

since version 1.0.86 of SQL Pro for MSSQL I'm getting 'Unknown type. 241.' for columns with datatype XML. 

Any suggestions?

Regards
Tim

**Comment by hankinsoft** [comment]
Hello,
Can you try build https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.1.0.91.app.zip? That should solve the issue for you. If you are using the mac app store build, it will be available early next week. If you need a license key for the website download please email kyle @ hankinsoft.com.

**Comment by tim-hoffmann** [comment]
Thanks! I'm going to wait for the app store update.
