### ISSUE TITLE
Feature Request SQLPro Studio iPadOS: Better integration with file providers

### ISSUE THREAD

**Issue by georgziganek** [hankinsoft/SQLPro#502]
I have my queries in .sql file format stored in a git repository. Using the app “Working Copy”,  I can access them from SQLPro Studio. But it would be great If I could add a folder from an external file provider so that I have easy access to the files from the repository. Right now I can access all files from a folder but only if it’s in the SQL Pro Studio iCloud  folder.

Something like these would be cool:
![IMG_0239](https://user-images.githubusercontent.com/71907804/94346512-b4e07980-fff2-11ea-9084-6814cef5e688.jpeg)

**Comment by hankinsoft** [comment]
Sorry, i'm not 100% understanding what you are asking. Does the 'Files' tab, then 'Open file', not allow you to pick this folder? It should allow you to browse to the 'Working Copy' folder?

**Comment by hankinsoft** [comment]
Just wanted to check in - Does the 'Files' tab, then 'Open file', not allow you to pick this folder? It should allow you to browse to the 'Working Copy' folder? Is this not what you mean?

**Comment by georgziganek** [comment]
Hi Kyle,

no, that's not what I mean. I can currently access the files in external providers. What I have in mind is to add permanent access to a folder, similiar to how apps like Ulysses, iA Writer or 1Writer handle it: you grant the app access to the folder in the desired location, you can easily navigate to the desired folder or file. The folder stays there until you remove it.

![C528DDC0-CF0F-47EB-B2FE-DE8848ED813A_1_102_a](https://user-images.githubusercontent.com/71907804/96769595-f4f20c80-13a4-11eb-89cc-71696360aa6d.jpeg)

See Screenshot of how 1Writer does it:

![A2AA610F-6A09-479D-B1CC-5F45881425B8_1_201_a](https://user-images.githubusercontent.com/71907804/96769785-32569a00-13a5-11eb-9a50-99f8254b845f.jpeg)

A quick fix that would be helpful in the meantime would be a keyboard shortcut to open the file window, e.b. CMD + O

Let me know if you have further questions. Thanks!

**Comment by hankinsoft** [comment]
I've got the 'Open File' shortcut ready for the next build. I've got a few more things I need to get fixed up on the iOS version, then I will get it submitted. I plan on it being available mid-next week.

**Comment by hankinsoft** [comment]
I don't currently plan on making any additional changes to the files explorer. If I get additional requests for this I will investigate it further.
