### ISSUE TITLE
Feature Request: Autocomplete: Snowflake Add "CURRENT_DATE" reserved word (and any other reserved words not currently present)

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#504]
If I type `SELECT CURRENT_DA`, autocomplete does not suggest `CURRENT_DATE`. It'd be nice to have that added, along with any other reserved words not already in autocomplete.

SQLPro Studio 2020.83 (Build 110722.5)
macOS 10.15.7 (19H2)
Snowflake 4.31.3

**Comment by jim256** [comment]
It looks like this is working in 2020.88. However, it doesn't match the case of the DB (Snowflake). If I start typing it with lower case, it'll complete it with lower case. If I start typing with upper case, it'll complete with upper case.

I'd also like to request that `CONVERT_TIMEZONE()` and `QUALIFY` be added.

**Comment by hankinsoft** [comment]
> it doesn't match the case of the DB (Snowflake)

Do you know if snowflake keywords always uppercase? Or just in your specific database?

**Comment by hankinsoft** [comment]
As far as I can tell this seems to be the case (all snowflake queries should be uppercase). I'll get that fixed up.

**Comment by hankinsoft** [comment]
Hi, this should all be fixed up for the latest version (2020.96). If you get the chance, please give it a try.

**Comment by jim256** [comment]
Seems to be good to go! Thanks
