### ISSUE TITLE
Not all triggers displayed 

### ISSUE THREAD

**Issue by alexjer** [hankinsoft/SQLPro#505]
Hi
When I try to see triggers under a table I see only triggers created by table owner.
if trigger created by other user not by table owner I can't see it

**Comment by hankinsoft** [comment]
Hi. What type of database are you seeing this with?

**Comment by alexjer** [comment]
Oracle 18c

**Comment by hankinsoft** [comment]
Fixed for the next build.

**Comment by alexjer** [comment]
Thank you.

**Comment by alexjer** [comment]
I use Mac App Store, can you please upload to the App Store?
I will check

**Comment by hankinsoft** [comment]
Hi - are you using SQLPro Studio or SQLPro for Oracle?

**Comment by alexjer** [comment]
SQLPro for Oracle

**Comment by alexjer** [comment]
Hi 
I check and still can't see the triggers

**Comment by hankinsoft** [comment]
This should now be available in the latest version of the apps. Please update and let me know if that helps out.

**Comment by alexjer** [comment]
Version 2020.96 (Build 490.5)(SQLPro for Oracle) my version. last in Mac app store
Still can't see the triggers

**Comment by hankinsoft** [comment]
If you run the following query:

SELECT
    TRIGGER_NAME,
    TRIGGER_TYPE
  FROM
    all_triggers
  WHERE
    BASE_OBJECT_TYPE = 'TABLE'
  AND
    TABLE_NAME = '{YOUR_TABLE}'
  AND OWNER = '{YOUR_SCHEMA}'

And replace YOUR_TABLE and YOUR_SCHEAM with the table/schema, do you get any results?

**Comment by alexjer** [comment]
Only for Table owner 
Not triggers created by other schemas for this table

**Comment by alexjer** [comment]
SELECT
    TRIGGER_NAME,
    TRIGGER_TYPE
  FROM
    all_triggers
  WHERE
    BASE_OBJECT_TYPE = 'TABLE'
  AND
    TABLE_NAME = '{YOUR_TABLE}'
I get all with that query

**Comment by hankinsoft** [comment]
Ahhhh, I see what your saying. Just to check, if you add ` AND TABLE_OWNER = '<the schema>'` does that work properly?

I think I'm using the wrong owner field ---- and if I eliminate owner completely, then if a table with the same name exists in two different schemas exists, then that would cause some issues. If using TABLE_OWNER works, I'll get that fixed and submitted right away.

**Comment by alexjer** [comment]
Table owner work for me

**Comment by alexjer** [comment]
Can you please upload to the Mac app store after the fix(SQLPro for Oracle)?

**Comment by hankinsoft** [comment]
Yep, getting this uploaded now.

**Comment by alexjer** [comment]
Thank you

**Comment by alexjer** [comment]
Hi
Now I see the triggers but can't edit them
1. right click on a trigger
2. Script As
3. Create to
4. New query window
Window opened without a trigger. just blank window

**Comment by hankinsoft** [comment]
A fix has been submitted. If you use 'save state' you may need to disconnect and reconnect, as the database tree previously did not store the full path for a trigger.

**Comment by alexjer** [comment]
I reconnect and I see a trigger in the database tree, but I can't perform operation on the trigger.
When I want to see trigger body or edit it, I can't. That bug actually resolved. Now trigger is visible but useless. Are you want I will close this issue and will open new one for the trigger operations?

**Comment by hankinsoft** [comment]
Sorry - I mean I’ve submitted a new fix for this issue. It needs to be reviewed by apple before it will be available.

**Comment by alexjer** [comment]
Thank you

**Comment by alexjer** [comment]
Hi I check the last version and I see trigger body thanks a lot, but trigger body looks like:
CREATE TRIGGER "OWNER"."TRIGGER_NAME" when trigger and table owner is the same
CREATE TRIGGER TRIGGER_NAME when trigger and table owner is different.
