### ISSUE TITLE
Limit number of result rows when select

### ISSUE THREAD

**Issue by alexjer** [hankinsoft/SQLPro#507]
Hi can you please 
1. Add limit number of select result rows in preferences .
and add button for bring other results in case limited number of rows not enough.
Or 
2. show limited number of records first and then run select for other results excluding displayed 

When I run select on huge table it take many time and cancel not response, so I need all the time write "where rownum <100"

**Comment by hankinsoft** [comment]
> Add limit number of select result rows in preferences .

Do you mean a limit option for when you double click a table name? The current amount is 1,000 - you wish to be able to change this?

**Comment by hankinsoft** [comment]
Hi,
Unfortunately automatically liming the number of query results is not something I have plans on adding. I will take a look into Oracle query cancellation, but I'm not sure there are many improvements which can be made there (I think I've taken a look at that in the past, but I will double-check).

**Comment by monty-dev** [comment]
I agree with @alexjer  - Having the same issue with a 32M row table. Every editor I've used thus far has had an automatic limit of X number of rows, typically 500-1000 and It helps a lot. Hope to see this in SQLPro.

**Comment by hankinsoft** [comment]
Just wanted to note that I have NO plans on automatically limiting result set counts on user enetered queries. You can double click on a table name or (or right click and choose select top 1000 rows) if you need a limit.
