### ISSUE TITLE
Bit fields in MSSQL

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#508]
I’m using SQLPro Studio.

When I query a MSSQL table with a `BIT` column, the result grid displays `true` or `false`. While that is clearly the intention, I think it would be more appropriate to display the native `1` or `0`.

I was surprised that using either 1/0 or true/false works (as it does on SSMS).

Thanks

**Comment by hankinsoft** [comment]
Hi,
You can disable true/false via the preferences. Head to the 'Appearance' tab, then the sub 'Results' tab and uncheck 'Display bools as true/false'.

**Comment by manngo** [comment]
HI

Thanks for the information. The only problem is that this setting is for all results, so that a database like PostgreSQL which truly has a boolean type, also yields `1` or `0`.

**Comment by hankinsoft** [comment]
FYI I've been procrastinating on this off as I'm not sure the best solution. Some users tend to prefer the true/false in SQL Server for the bits. While obviously you do not. Just wondering what your preferred solution for this item would be?

**Comment by hankinsoft** [comment]
Closing for now. If anyone has any suggestions on what they would prefer to see, please let me know.
