### ISSUE TITLE
Issues with connections running amok and causing servers to get overloaded.

### ISSUE THREAD

**Issue by dougreid72** [hankinsoft/SQLPro#509]
It seems like connections are staying open and creating large amount of connections.  I am not sure to help with the debug

**Comment by hankinsoft** [comment]
Which type of database are you seeing this with?

**Comment by dougreid72** [comment]
MySQL

----
Doug Reid

HaaF Consulting, LLC
Computer Consulting
Winfield, KS
Doug.Reid@haafconsulting.com
C 620-218-2887

**Comment by dougreid72** [comment]
One of the connection types is SSL and the other is a localhost that gets wormholed to a connection on another computer (local port 7779 gets redirected to port 3360 on the server.

----
Doug Reid

HaaF Consulting, LLC
Computer Consulting
Winfield, KS
Doug.Reid@haafconsulting.com
C 620-218-2887

**Comment by dougreid72** [comment]
one of my coworkers saw that it was doing a lot permission checks.

**Comment by hankinsoft** [comment]
Do you have a bunch of databases on the same server? I'm thinking it might be related to how servers searching/autocomplete is cached.

**Comment by dougreid72** [comment]
My new company has about 140 customers and each customer has 5 databases (700 databases).    I have been using several MySQL applications the last few weeks and they are not having issues.

----
Doug Reid

HaaF Consulting, LLC
Computer Consulting
Winfield, KS
Doug.Reid@haafconsulting.com
C 620-218-2887

**Comment by hankinsoft** [comment]
Ahhhh, ok - so you are in the range of ~700+ databases? Could you possibly send me your log files? You can find them via 'View' -> 'Logs'. You can email them directly to me via kyle@hankinsoft.com.

**Comment by dougreid72** [comment]
Asking my boss about sending the logs.

----
Doug Reid

HaaF Consulting, LLC
Computer Consulting
Winfield, KS
Doug.Reid@haafconsulting.com
C 620-218-2887

**Comment by dougreid72** [comment]
I ran one query after connecting.

----
Doug Reid

HaaF Consulting, LLC
Computer Consulting
Winfield, KS
Doug.Reid@haafconsulting.com
C 620-218-2887

**Comment by hankinsoft** [comment]
I've made some changes to how autocomplete loads background details which I believe will sort this out. If you get the chance, could you give this a try and let me know if everything is sorted?

**Comment by dougreid72** [comment]
How do I pull the update?  I do not see a new version on the app store.

**Comment by hankinsoft** [comment]
Whats the current version you are using? Could you send a screenshot of the about dialog?

**Comment by dougreid72** [comment]
2021.03 (Build 105011.5



----
Doug Reid

HaaF Consulting, LLC
Computer Consulting
Winfield, KS
Doug.Reid@haafconsulting.com
C 620-218-2887

**Comment by hankinsoft** [comment]
Hmmm, that build should actually have the fix in it. You are still seeing the connections being left open?

**Comment by dougreid72** [comment]
I have not tested it yet.  I will try it tonight.


----
Doug Reid

HaaF Consulting, LLC
Computer Consulting
Winfield, KS
Doug.Reid@haafconsulting.com
C 620-218-2887

**Comment by hankinsoft** [comment]
Closing. If you find this is still an issue, please let me know.
