### ISSUE TITLE
An option to have all text qualified with the database delimiters

### ISSUE THREAD

**Issue by hankinsoft** [hankinsoft/SQLPro#51]
> I'd also like an option to have all text qualified with the database delimiters (i.e. square brackets in SQL Server, back-ticks in MySQL and so on). Originally mentioned in issue #20

**Comment by neongrau** [comment]
Same problem preventing a commit of edited record values.
E.g. i have a table `emails` that has a column `from` and another named `to`.
SQLPro fails when trying to edit the record.

Also same issue when generating an INSERT snippet to clipboard.

**Comment by hankinsoft** [comment]
I don't plan on an option to always have fields/table names qualified. Instead I have improved the auto-qualified-required detection. If anyone runs into anything else that needs to be qualified and has failed to have been qualified, please let me know.
