### ISSUE TITLE
Crash on closing tabs

### ISSUE THREAD

**Issue by dlitty** [hankinsoft/SQLPro#510]
The most recent update of SQLPro (Version 2020.87 (Build 110728.5) has introduced a crash every time I go to close a tab - this is on MacOS 10.15.6; I typically have lots of tabs open, and they re-open on re-launch, so this is a fairly sizable productivity hit.

**Comment by hankinsoft** [comment]
I've got this fixed and am trying to submit the build. iTunes Connect is giving me a bit of an issue, but it should be sorted shortly. Sorry about that.

**Comment by dlitty** [comment]
Great, thank you.

**Comment by hankinsoft** [comment]
A new version has been released and is on the app store.

**Comment by dlitty** [comment]
Thanks - so far so good - I'll let you know if I see it again.
