### ISSUE TITLE
Feature Request: On Import allow truncation of table

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#511]
Would it make sense to have a checkbox that would allow truncating a table before having data imported?  By default it would be unchecked.

If checked you could alert the user that 3,456 rows will be removed before the import.

![image](https://user-images.githubusercontent.com/3777526/95593187-5d410580-0a17-11eb-912e-878e46c281ac.png)

**Comment by hankinsoft** [comment]
Good idea. I'll get this added for an upcoming build.

**Comment by hankinsoft** [comment]
This has been added to all the latest app versions. Please give it a try and let me know if everything works as you expected.

**Comment by cwolcott** [comment]
Sorry for not commenting, yes it worked perfectly.
