### ISSUE TITLE
Deleting table causes program crash

### ISSUE THREAD

**Issue by TGit911iger** [hankinsoft/SQLPro#515]
After deletion of a table with an external tool, eg Microsoft Management Studio, and then pressing refresh in SQLPro causes a program crash. SQLPro ended abnormally.

**Comment by hankinsoft** [comment]
Any chance you could post the crash log? I've been unable to reproduce this. Also what version are you seeing this with?

**Comment by hankinsoft** [comment]
Also, are you refreshing the table and choosing refresh? Or the 'Tables' node?

**Comment by TGit911iger** [comment]
> Also, are you refreshing the table and choosing refresh? Or the 'Tables' node?

Refreshing table

**Comment by TGit911iger** [comment]
Version 2020.88 (Build 10527.5)

**Comment by TGit911iger** [comment]
No log this time. I am sorry - will send if I get a new one.

**Comment by hankinsoft** [comment]
Going to close this for now - if you are able to reproduce and get a log, please let me know.
