### ISSUE TITLE
Setup dockerized MySQL in SQLProStudio

### ISSUE THREAD

**Issue by aymanapatel** [hankinsoft/SQLPro#516]
I am trying to connect my docker MySQL container to SQLProStudio on Windows

`docker-compose.yml`:
    ---
    version: '2'
    services:
    
      mysql:
        image: debezium/example-mysql:1.2
        container_name: mysql
        ports:
          - 3306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=debezium
          - MYSQL_USER=mysqluser
          - MYSQL_PASSWORD=mysqlpw
        volumes:
          - ${PWD}/data/movies.sql:/docker-entrypoint-initdb.d/z99_dump.sql

I have run `docker-compose up` and getting the following response for `docker ps`:

    CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                               NAMES
    93572714f0d8        debezium/example-mysql:1.2   "docker-entrypoint.s…"   3 minutes ago       Up 30 seconds       0.0.0.0:3306->3306/tcp, 33060/tcp   mysql

While connecting, getting this issue in SQLProStudio: Unable to connect to any of the specified mysql hosts docker

Note connection string below:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/ZlzQ3.png

**Comment by AymanArif** [comment]
Was able to connect to database:

Now the issue is with running SQL scripts.

SQL Script:


    GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'replicator' IDENTIFIED BY 'replpass';
    GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'debezium' IDENTIFIED BY 'dbz';
    
    -- Create the database that we'll use to populate data and watch the effect in the binlog
    CREATE DATABASE demo;
    GRANT ALL PRIVILEGES ON demo.* TO 'mysqluser'@'%';
    
    use demo;


When I try to run this, I am getting the following error:

    Access denied for user 'mysqluser'@'%' (using password: YES)
