### ISSUE TITLE
SQL PRO - MS SQL MFA

### ISSUE THREAD

**Issue by michaelseven** [hankinsoft/SQLPro#517]
Hi there
Any change to get MFA for MS SQL (Multi Factor Authentication) in a future release of SQL Pro

Can't use MS SQL databases on Azure with MFA.

Many Thanks!

**Comment by hankinsoft** [comment]
Hi - MFA is on my TODO, but I don't have an ETA as of yet. The current solutions I've tried to implement have not been successful, so I'm still investigating.

**Comment by michaelseven** [comment]
Hi there,

Nice one.
I am just happy to hear that there is an option to get MFA in it.
Nice piece of software. Many thanks!

—
Best Regards
Michael Michalewicz
https://mac4u.tech

PGP encryption key attached.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
