### ISSUE TITLE
An option to configure default 'copy from results grid'

### ISSUE THREAD

**Issue by hankinsoft** [hankinsoft/SQLPro#52]
Currently copy always copies as CSV. An option to configure the default copy would be great.

**Comment by msharp** [comment]
I would love to have better options for running a query and writing the results directly to a file. 

Copy/pasting is crude, especially with 100,000+ rows, and the header row is not included on the clipboard.

**Comment by hankinsoft** [comment]
Closing as a duplicate of #17.

**Comment by hankinsoft** [comment]
The latest version of SQLPro Studio and SQLPro for Postgres both allow you to pick the default separator and delimiter for copy from results grid. If anyone gets a chance, please give it a try and let me know if that does the trick. Preference can be set from the 'Preferences' -> 'Keyboard' tab. Please leave any responses in #17.
