### ISSUE TITLE
Windows 2020.57 Postgres Connection Issue

### ISSUE THREAD

**Issue by MikeDotNetty** [hankinsoft/SQLPro#520]
I have downloaded SQLPro studio from the Windows Store (as instructed).  The version that is provided is 2020.57.  When attempting to connect to a Postgres db (using IPv6 address) I am presented with the following error:

![image](https://user-images.githubusercontent.com/62762681/97580160-57609380-19c9-11eb-81bb-7c30199b2aa2.png)

I know the connectivity DOES exist as I am able to connect to this database via .NET code.  Please advise.

**Comment by hankinsoft** [comment]
Thank you for the report. I fixed a similar issue on the macOS version and I don't think the fix ever made it over to the Windows version. I'll take a look into this.

**Comment by MikeDotNetty** [comment]
Thanks @hankinsoft much appreciated!

**Comment by hankinsoft** [comment]
I've got the build submitted. Windows builds usually take ~24 hours or so to become available.

**Comment by MikeDotNetty** [comment]
@hankinsoft thanks for the quick development.  I will check the windows store tomorrow and confirm for you that it works!  Much appreciated!

**Comment by MikeDotNetty** [comment]
@hankinsoft follow up, what build number should I be looking for?

**Comment by hankinsoft** [comment]
2020.60

**Comment by hankinsoft** [comment]
Just wanted to check in - if you get the chance can you let me know if your seeing the new build and if that sorts the ipv6 issues for you? The build should be available (it was approved ~10 hours ago).

**Comment by MikeDotNetty** [comment]
It just updated and I currently have version 2020.61
![image](https://user-images.githubusercontent.com/62762681/98128370-d94b3380-1e85-11eb-9a2e-02532c00df6c.png)

**Comment by MikeDotNetty** [comment]
@hankinsoft More importantly, now that I have this updated version, I CAN log in using an IPv6 address!  Thanks!!!!

**Comment by hankinsoft** [comment]
Great, thanks for letting me know. I pushed .61 with a license fix unrelated to the ipv6 issue.

**Comment by MikeDotNetty** [comment]
@hankinsoft One follow-up.  This could very well be related to the Postgres db that I am connecting to, BUT when I am using SqlPro > connect to the Postgres db (over IPv6) > and expand the db and the "Tables" folder in the "Database Tree", I am not presented any tables...but I do know there are tables in the database I am connected to as I am able to query them (in SqlPro).  So my question is: are there any known issues with presenting the list of tables in a Postgres database in SqlPro studio?  I have a co-worker using the Mac version experiencing the same thing (with the same DB, so it might be the DB causing this issue).  Thanks again!

**Comment by hankinsoft** [comment]
Two questions:

1. What is your Postgres server version?
2. If you run the following query do you get results, or an error:

SELECT 
    table_schema, 
    table_name,
    (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid,
    (SELECT DISTINCT inhparent FROM pg_inherits WHERE inhrelid = (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid) AS parentOID
FROM 
    information_schema.tables 
WHERE 
    table_type LIKE '%TABLE%' 
    AND table_catalog != 'postgres ' 
    AND table_schema NOT IN (
        'information_schema', 'pg_catalog', 'pg_internal', 'pg_toast'
    )
    
UNION 
SELECT 
    table_schema, 
    table_name,
    (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid,
    (SELECT DISTINCT inhparent FROM pg_inherits WHERE inhrelid = (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid) AS parentOID
FROM 
    information_schema.tables 
WHERE 
    table_type LIKE '%TABLE%' 
    AND table_catalog = 'postgres' 
    
ORDER BY 
    table_schema, 
    table_name;

**Comment by MikeDotNetty** [comment]
@hankinsoft Thanks for the quick response.   It looks like Postgres 10.5, and that query you provided produces 0 results.
![image](https://user-images.githubusercontent.com/62762681/98141947-35698400-1e95-11eb-8c92-204cab64f838.png)

**Comment by hankinsoft** [comment]
If you run:

SELECT
table_schema,
table_name,
table_type
FROM
information_schema.tables

Do you see the tables you are looking for? If so, what is the table_type field for them?

**Comment by MikeDotNetty** [comment]
@hankinsoft as it turns out, this is an "issue" with our db, everything we have access to are VIEWs not TABLES.  So I guess maybe a future enhancement to sqlPro to include Postgres VIEWS?  :)

**Comment by hankinsoft** [comment]
Sure! The macOS app version already has views, so I should be able to add that to the Windows version without too much difficulty. It will probably be either late this week or early next week.

**Comment by MikeDotNetty** [comment]
@hankinsoft THANKS!  Also my last response was entered as you were responding, but to answer your question, the two types I see are "BASE TABLE" and "VIEW" .

USING this query:

SELECT
distinct(table_type)
FROM
information_schema.tables

**Comment by MikeDotNetty** [comment]
@hankinsoft I noticed that the SqlPro version was recently updated on my machine (2020.72) and I can see it supports VIEWS now!!!  Much appreciated!

**Comment by hankinsoft** [comment]
Awesome. And to confirm, if you expand a view, do you see the columns underneath it as well?

**Comment by MikeDotNetty** [comment]
@hankinsoft While I CAN see all the views, if I expand a view I do NOT see the columns. :(
