### ISSUE TITLE
Application hangs no querying for a short period of time

### ISSUE THREAD

**Issue by duncanelliot** [hankinsoft/SQLPro#521]
Hi there, I am using The application in conjunction with mySQL. It works very well except for one thing. As soon as you stop querying for a short amount of time, around a minute, the next query that you submit to the server takes a long time. It doesn't even have to be a query it could be refreshing the list of tables. I had the same problem in sequel workbench and solve it by reducing the Keep alive interval to 60. After I did that I could go away for hours and come back to my computer and submit a simple statement and it would execute instantly without having to think about it. Right now the application needs to spend about 10~15s before it actually process of the sequel query if you leave it unattended. My set a time out option on the server is set to 10. I attach to this there log of theMight set a time out option on the server is set to 10. I attach to this thread the log of the application. If you look at the end you can see that there is a 15s delay between application resuming an application becoming active which I think is the issue. I've yet to find the equivalent to the keep-alive interval option in the application. 

Thanks
[com.hankinsoft.osx.mysql 2020-10-29--15-24-56-456.log](https://github.com/hankinsoft/SQLPro/files/5459826/com.hankinsoft.osx.mysql.2020-10-29--15-24-56-456.log)

**Comment by hankinsoft** [comment]
Hi,
Hmmm, in that log file I'm not seeing any delays when executing a query. 

I see:
2020/10/29 16:06:26:382  User is going to execute a query of 29 length. Selection range is: {26, 0}.
2020/10/29 16:06:26:692  Result set 56 has finished with 28 rows.

Which is quite quick, followed by:

2020/10/29 16:10:03:631  User is going to execute a query of 29 length. Selection range is: {26, 0}.
2020/10/29 16:10:03:945  Result set 57 has finished with 28 rows.

Which is again pretty quick.

**Comment by duncanelliot** [comment]
Hi,

I still think there is something not quite right.

I right clicked on a stored procedure to modify it and it took 30s to load it. 
It started at **2020/10/30 16:31:15:412** 
and finished at **2020/10/30 16:31:43:370**
After that it was sub 1 second...something must be happening. Some kind of handshake that takes ages.

See log file for details of the event.

Best,

Duncan

[export.txt](https://github.com/hankinsoft/SQLPro/files/5466417/export.txt)

**Comment by hankinsoft** [comment]
Could you try this build:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.93.app.zip

I've added additional logging that will assist with tracking it down and confirming the issue is where I think it is - I've made a small change which might help out with this.

**Comment by duncanelliot** [comment]
Im giving it a go now. Note that I was using the mysql version not the studio version

**Comment by duncanelliot** [comment]
Nope, I can come back to the app after being inactive and run a simple statement, it executes without delay. No problem there but if I right click on a database to refresh, it takes 75 second. The weird thing is that, prior to taking 75 seconds to connect, the app executed SQL statement (simple select *) instantly. See logs
![Uploading Screenshot 2020-10-30 at 20.03.53.png…]()

**Comment by duncanelliot** [comment]
It is still taking ages to retrieve the connection:

2020/10/30 20:20:11:525  MySQLClient isConnected (ping) took 18.18 seconds.
2020/10/30 20:20:11:525  Reusing connection from pool (6125D7DE7F35F1217964D620FC5688CB).
2020/10/30 20:20:11:525  executeQuery:... find connection took 18.18 seconds.
2020/10/30 20:20:11:525  Disabling system sleep until query finishes.
2020/10/30 20:20:11:526  Enter autorelease block: com.hankinsoft.sqlpro.HSQueryTabViewController.doExecute

**Comment by hankinsoft** [comment]
> The weird thing is that, prior to taking 75 seconds to connect, the app executed SQL statement (simple select *) instantly. See logs

Each tab gets its own connection to the database, and the database tree also gets its own (this ensures things such as temporary tables and transactions do not interfere with each other). So each is independent of the other.

Thanks for providing the log - it does confirm to me that the `ping` is what's causing the delay (and unfortunately confirms that the code I added to try and sort that had no effect). I'm doing a bit of research to see what I can figure out.

**Comment by hankinsoft** [comment]
Could you try this build:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.95.app.zip

Please let me know if it helps to sort the issue.

**Comment by duncanelliot** [comment]
Hi there,

The connection seems to drop with that version.

Happy to do a screen share.

Best,

Duncan

**Comment by hankinsoft** [comment]
Hi,
I've recently made some changes around how the tab database pool works. If you get the chance, could you update to the latest version and see if you continue to see this?

**Comment by duncanelliot** [comment]
Hi there,

I have a different query this time. I wasn't able to get the build version working but I want to use the application as it is. I have purchased a license with Apple but I do not know what my license key is and I have not received an email telling me what it is. Can you help me out?


Thanks,

Duncan

**Comment by hankinsoft** [comment]
Hi,
App Store purchases won’t have a license key. If your App Store purchase is not being recognized I have an article here with some suggestions:

https://www.sqlprostudio.com/blog/13-app-store-subscription-not-activating

Please let me know if that helps out.

**Comment by duncanelliot** [comment]
Ha yes, it worked when I restarted

The connection still drops between tabs though.

Would you like to screenshare?

Best

Duncan

**Comment by hankinsoft** [comment]
I should be able to do a screen share tomorrow. What would be your preferred application to do so?

**Comment by duncanelliot** [comment]
Zoom. I am on UK time.

**Comment by hankinsoft** [comment]
Would you be available currently?

**Comment by hankinsoft** [comment]
Hi,
I've made some changes to how connections are stored per tabs in the recent versions. Are you still seeing this issue?
