### ISSUE TITLE
Views not removed from list when dropped

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#523]
I love how you animate the addition and removal of DB artifacts.

I just noticed that when I drop a view via query it is not removed from the list (tables are).  So I need to refresh the Views folder by hand.  When it is created it is added to the Views folder.

Version 2020.85 (Build 110724)

**Comment by hankinsoft** [comment]
This should now be available in the latest version of the apps. Please update and let me know if that helps out.

**Comment by cwolcott** [comment]
Verified. The entry for a view is removed from the list when a view is dropped.
