### ISSUE TITLE
Views menu says "Drop Table"

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#524]
If you try to drop a view using the menu it says "Drop Table" and creates a Drop table command.

![image](https://user-images.githubusercontent.com/3777526/97719074-0c17b500-1a9d-11eb-853c-293ccb2bd86c.png)

**Comment by hankinsoft** [comment]
Just to check, for this one and #523 are these both --- Oracle?

**Comment by cwolcott** [comment]
YesSent from Samsung Galaxy S8+
-------- Original message --------From: Kyle Hankinson <notifications@github.com> Date: 10/30/20  10:49  (GMT-05:00) To: hankinsoft/SQLPro <SQLPro@noreply.github.com> Cc: cwolcott <chris.wolcott@comcast.net>, Author <author@noreply.github.com> Subject: Re: [hankinsoft/SQLPro] Views menu says "Drop Table" (#524) 
Just to check, for this one and #523 are these both --- Oracle?

**Comment by hankinsoft** [comment]
This should now be available in the latest version of the apps. Please update and let me know if that helps out.

**Comment by cwolcott** [comment]
Verified in Version 2020.96.  The menu for views now says "Drop view ..." instead of "Drop table ..."
