### ISSUE TITLE
No support with license issue

### ISSUE THREAD

**Issue by roberttheunissen** [hankinsoft/SQLPro#525]
Impossible to contact Hankinsoft. Paid the full amount in app store and application keeps asking for valid license (which is not issued when purchasing via Apple app store). No email, no tel, no response via LinkedIn. Bad stuff! Reported to Apple and refund on its way. You could pay a bit more attention to customer service. We would be out of business if we treated customers like this.

**Comment by hankinsoft** [comment]
Hi,
The issue you mention sounds like one I've seen before. I've got an article available here:
https://github.com/hankinsoft/SQLPro/wiki/App-Store-Subscription-not-Renewing

If you are looking for help in the future, support links are available in three locations:

1. In the app store itself (this is the same for every app on the app store).
<img width="973" alt="Screen Shot 2020-11-03 at 8 18 58 AM" src="https://user-images.githubusercontent.com/3160528/97984790-a2a1ea00-1dad-11eb-8b5f-fbb10afbe5ed.png">

2. On the launch screen of the application.
<img width="659" alt="Screen Shot 2020-11-03 at 8 20 14 AM" src="https://user-images.githubusercontent.com/3160528/97984839-b4838d00-1dad-11eb-8af5-4f57c0e38912.png">

3. Via the 'Help' -> 'Support' menu of the application.
