### ISSUE TITLE
build SQLProStudio.2020.85.app slow result set display

### ISSUE THREAD

**Issue by n7swd** [hankinsoft/SQLPro#526]
The current build SQLProStudio.2020.85.app takes 8mins to get a result set of 200K. Where SQLProdStudio.2020.72.app displays in 8 seconds the same query.

**Comment by n7swd** [comment]
The connection is to an AWS REDSHIFT. Also, SQLProStudio.2020.61.app does the same query display in 8 seconds also.

**Comment by hankinsoft** [comment]
Any chance I could get a copy of the log file (from the 8 minute query). You can either post it here or email me via kyle@hankinsoft.com.

**Comment by hankinsoft** [comment]
Also, are you using SSH tunneling? Or a straight connection?

**Comment by n7swd** [comment]
Sure how do I get it? Location

**Comment by jim256** [comment]
You can get the log file by going to View -> Logs
<img width="535" alt="image" src="https://user-images.githubusercontent.com/15026225/98154636-4cf33d80-1e92-11eb-9be9-1496f9e68c5c.png">

**Comment by n7swd** [comment]
I will work on greaing that today.. Thanks for the fast response,,,
 

Sent: Wednesday, November 04, 2020 at 11:39 AM

**Comment by n7swd** [comment]
Sent: Wednesday, November 04, 2020 at 11:39 AM

**Comment by hankinsoft** [comment]
Hi,
I've posted a new build available. Could you try and update and let me know if that helps out? The new build number is 2020.96 - If that does not work, could you post the log file? Please upload it directly to github as the email response send previously, unfortunately, did not attach the log file.

**Comment by n7swd** [comment]
I will post old log... SELECT * FROM <tablename> LIMIT 100000
-- build 2020.85 2 mins 21 seconds
-- build 2020.72 12.842 seconds -- log file of this build..

[com.hankinsoft.osx.sqlprostudio 2020-11-15--23-30-18-908.log](https://github.com/hankinsoft/SQLPro/files/5548988/com.hankinsoft.osx.sqlprostudio.2020-11-15--23-30-18-908.log)

**Comment by n7swd** [comment]
Sorry I can not build 2020.96, but I did upload log file to GitHub

**Comment by caseyjerk** [comment]
I believe I am also running into this issue. Similarly  connecting to AWS redshift, it takes over 5 minute to return 300k rows from a table. Is there a way for me to roll back to a previous version? I was on .85 and I tried .104 and both are the same speed.

**Comment by n7swd** [comment]
I noticed the same issue with 104. So I am running 78

**Comment by jim256** [comment]
@hankinsoft , I wonder if this could be related to #428 ? Looks like on both Redshift and Snowflake, speed of simple row retrieval is much slower than when trying with different clients. Obviously #526 started happening much more recently, but I just got thinking about how they are similar and figured I'd mention it.

**Comment by hankinsoft** [comment]
FYI I've been working on this - and hope to have a build available later this week. Ideally it will resolve the issue, but if not there is additional logging which also adds extra details.

**Comment by hankinsoft** [comment]
The latest version of SQLPro Studio (2020.107) is now available via the App Store. If anyone gets the chance, could they check and see if this sorts the Postgres slowness? I'm 99% sure the former speed will be improved.

**Comment by hankinsoft** [comment]
Closing as this has been fixed. If anyone still sees the issue, please let me know.
