### ISSUE TITLE
Snowflake: "PUBLIC" and "NAME" always unnecessarily-escaped in double quotes.

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#527]
Similar to #492

Whenever I accept an autocomplete suggestion for an object named 'NAME' or 'PUBLIC', it always inserts it with double quotes:
```
SELECT "NAME"
```
```
SELECT "PUBLIC"
```

These aren't reserved words in Snowflake and can be used without escaping.

macOS 10.15.7 (19H2)
SQLPro Studio 2020.88 (Build 110729.5)
Snowflake 4.36.4

**Comment by jim256** [comment]
It looks like Postgres also does this for `name`

**Comment by hankinsoft** [comment]
This should all be fixed in the latest version (2020.100).

**Comment by jim256** [comment]
Looks like `name` is fixed for both, but I'm still seeing `"` around `PUBLIC` when it's the name of a schema in Snowflake.

macOS 11.0.1 (20B29)
SQLPro Studio 2020.100 (Build 110751.5)
Snowflake 4.38.1

**Comment by hankinsoft** [comment]
If you get the chance, can you try this in the latest build for me please?

**Comment by jim256** [comment]
Just tested via double-clicking a table name in a schema called PUBLIC and it still quoted it.
SQLPro Studio 2021.05 (Build 110767.5)

**Comment by jim256** [comment]
Seems to be fixed now.
