### ISSUE TITLE
SQLPro locks all the databases up on the server and no one can restore

### ISSUE THREAD

**Issue by SQLServerDBANorwex** [hankinsoft/SQLPro#529]
SQLPro (confirmed with many different users) locks up all the databases on the server where no one can run restores of the databases.  

MSSQL 2014 SP3 CP4 developer

SQL Pro version
Version 2020.82 (Build 10524)

**Comment by hankinsoft** [comment]
I've got an update submitted that I believe will sort this out. It should be available later today.

**Comment by hankinsoft** [comment]
There is a new update available. Can you update and see if that helps out? The new build number is 2020.96.

**Comment by hankinsoft** [comment]
Closing as I believe this has been fixed.
