### ISSUE TITLE
Multi-Factor Authentication for SQLpro / PostgresQl

### ISSUE THREAD

**Issue by adorzhiev** [hankinsoft/SQLPro#53]
Hi!
Sorry for my english at first!

We using Multi-Factor Authentication to connect some our servers 
(by getting a temporary code to phone / Google Authenticator)

is there any chance in SQLpro ?

Thanx

**Comment by adorzhiev** [comment]
can you add this features in future ?

thanks a lot

**Comment by hankinsoft** [comment]
Hi, which host are you using that offers two form authentication? (So that I can test with it)? Thank you!

**Comment by adorzhiev** [comment]
Hi!
You can use any hosts for a test .. it doesn't matter
if I understand correctly the question

thank you!

**Comment by clearsensespw** [comment]
@adorzhiev sorry to write on a very old bug - but how you set up multi-factor authentication in postgresql for google authenticator ?

**Comment by hankinsoft** [comment]
Hi, unfortunately the moment I have no plans for multi-factor authentication unless I get more requests to add it in.
