### ISSUE TITLE
Can you refund me the software license that I purchased repeatedly?

### ISSUE THREAD

**Issue by arcstep** [hankinsoft/SQLPro#530]
I don't know if it is appropriate to post on github, but I did not find other channels. Hope to be forgiven if you send it wrong.

My question is: Can you refund me the software license that I purchased repeatedly?

When I purchased SqlPro on the AppStore on November 2nd, I downloaded SqlPro for Postgress and SqlPro Studio at the same time. 

When I decided to purchase the lifetime authorization, I clicked the Postgres version by mistake. 

After finding the problem, I called the official Apple customer service and they made a refund request. I thought the refund was successful, so I immediately purchased the Studio version of lieftime.

But then I found that the refund was not successful, so I spent about 1,000 RMB more to buy this software, which made me very distressed. 

So I came to ask your company for help.

The merchant order number I purchased repeatedly is `MQKFND1L14a0` and the transaction order number is `4200000815202011020401075965`.

You can contact me via 43801@qq.com, Thank you!

**Comment by hankinsoft** [comment]
Hi,
Unfortunately I cannot refund any purchases made via the App Store. My suggestion would be to contact them again stating: “the application does not work. It crashes upon startup”. That has been the most successful way to receive refunds from Apple in the past.

**Comment by arcstep** [comment]
I will try it! Thank you!

**Comment by hankinsoft** [comment]
No problem. I'm going to close this issue as I won't be able to provide further assistance with getting a refund via the app store. Again, telling them `the application does not work. It crashes upon startup` would be the best route to receive a refund from them.
