### ISSUE TITLE
Lifetime License Isn't Applying

### ISSUE THREAD

**Issue by MikeDotNetty** [hankinsoft/SQLPro#531]
@hankinsoft I recently purchased a "Lifetime" (windows) license.   I applied this on version 2020.72:
![image](https://user-images.githubusercontent.com/62762681/99249430-1c879980-27d8-11eb-8858-2373cdea51cf.png)

However when I execute queries I am prompted with this message:
![image](https://user-images.githubusercontent.com/62762681/99249485-35904a80-27d8-11eb-992c-b1e5a84cc57a.png)

Any insight would be appreciated.  Thanks!

**Comment by hankinsoft** [comment]
Could you post your order number? I'll take a look based on that. (Search your email for Fastspring - Order number will generally start with SQLPRO#####-####....

**Comment by MikeDotNetty** [comment]
@hankinsoft sorry for the delay in responding, but the order number is: SQLPRO201113-8244-11186.  Please let me know if you need anything else form me.  Thanks!

**Comment by hankinsoft** [comment]
Got it figured out. Build submitted (it also fixes the columns not showing up for views on postgres).

**Comment by hankinsoft** [comment]
This has been submitted and approved. The update (2020.74) should now be available in the app store.

**Comment by MikeDotNetty** [comment]
@hankinsoft I got the update and the license appears to work now!  Thanks!   Also yes the columns are now showing under the views!  Thanks again!!
