### ISSUE TITLE
Can't See Columns in Foreign Table (Postgres)

### ISSUE THREAD

**Issue by elliotnfi** [hankinsoft/SQLPro#532]
Can query foreign table and get results, but can't see table structure (columns etc.):
![image](https://user-images.githubusercontent.com/59617047/99293532-68523700-2808-11eb-9123-085d8d010ec3.png)

**Comment by hankinsoft** [comment]
Could you try running the following query:

```
SELECT 
	attname AS column_name, 
	format_type(atttypid, atttypmod) AS column_type, 
	NOT attnotnull AS is_nullable, 
	pg_index.indexrelid AS is_pk, -- primary key index id
    (SELECT DISTINCT substring(pg_catalog.pg_get_expr(d.adbin, d.adrelid) for 128)
                                    FROM pg_catalog.pg_attrdef d
                                    WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum AND a.atthasdef) AS default_value
FROM 
	pg_attribute AS a
	LEFT OUTER JOIN pg_index ON a.attrelid = pg_index.indrelid 
	AND indisprimary 
	AND a.attnum = ANY(string_to_array(textin(int2vectorout (indkey)), ' ')::int[]) 
WHERE 
	attrelid = '"<SCHEMA>".<TABLENAME>'::regclass
	AND attnum > 0 
	AND NOT attisdropped;
```

against your database? (Please replace <SCHEMA> and <TABLENAME>) with the ones, you are seeing the issue with. Does this give you any results?

**Comment by elliotnfi** [comment]
Yes, I see column names and types with the above.

**Comment by hankinsoft** [comment]
Ahhhhh, I see what's up. Are you using the app store version or website version? Also, SQLPro Studio, or SQLPro for Postgres?

**Comment by elliotnfi** [comment]
App store version of SQLPro for Postgres.

**Comment by hankinsoft** [comment]
Uploading to the app store now. It usually takes ~24 hours or so to be approved. Once it's available I'll post a note here to check and confirm if it's fixed for you.

**Comment by elliotnfi** [comment]
Awesome, thanks Kyle

**Comment by hankinsoft** [comment]
Hi - the latest version is now available (2020.97). Can you update and see if you can see the columns now? You might need to disconnect and reconnect if you have the app setup to save state between launches.

**Comment by elliotnfi** [comment]
Perfect! Thanks again Kyle

**Comment by hankinsoft** [comment]
No problem! Thanks for letting me know this is all fixed up.
