### ISSUE TITLE
Idea: Rename "Connect" button to "Connections"

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#533]
Given that this button takes you to a screen of all your connections, allowing you to add, edit, etc., and that don't actually connect until you're within the window and click "Connect" again, sometimes I think it may make more sense to rename the button.

**Comment by hankinsoft** [comment]
I'm debating this in my head. Not sure if I like changing it or not. I'm going to give this a few more days to mull over.

**Comment by jim256** [comment]
👌  Definitely not my call and I'm not set on it, but just thought I'd throw it out there as it seemed intuitive to at least me.

**Comment by manngo** [comment]
I like the idea, but I can see an argument that this button also leads to a new connection. Visually, changing the name to `Connect …` at least makes it clear that there’s another step.

**Comment by hankinsoft** [comment]
> I like the idea, but I can see an argument that this button also leads to a new connection. Visually, changing the name to `Connect …` at least makes it clear that there’s another step.

I like `Connect...`. I'll get it changed in the next couple of versions.

**Comment by hankinsoft** [comment]
This has been completed for the latest builds.
