### ISSUE TITLE
SqlPro Studio Version 2020.99 (Build 110750.5) Lost connection when query executed more than 10 seconds

### ISSUE THREAD

**Issue by Lbsl** [hankinsoft/SQLPro#534]
Query always fail after running for 10 seconds

![image](https://user-images.githubusercontent.com/7035546/99478054-b09b6180-298e-11eb-96d0-55329f8bd50e.png)

**Comment by hankinsoft** [comment]
Fixed for the next build. I'll be getting it submitted shortly, so it should be available within ~24 hours. Sorry for the issue.

**Comment by Lbsl** [comment]
Fixed now in version 2020.100, thanks
