### ISSUE TITLE
Show all databases in connection

### ISSUE THREAD

**Issue by henrikabellarsen** [hankinsoft/SQLPro#535]
When I connect to my SQL server, I need to select a database (or connect to server default). It would be nice, if SQLPro would show all databases, if I chose not to specify a database.

I have over 40 database to maintain, and I need to create a connection for each one. If I could create one connection and see all databases, that would be a blizz :-)

**Comment by hankinsoft** [comment]
Hi,
Are you using macOS? If so, you don't actually need to specify a database in the connection editor. If you leave it blank, you will get all the databases in the database tree upon connection.

**Comment by henrikabellarsen** [comment]
I'm on MacOS. If i don't specify a default database, I get: Cannot open user default database. Login failed. (Msg 4064, Level 11)."

**Comment by hankinsoft** [comment]
What is the user's default database set to be? Does the database exist?

**Comment by henrikabellarsen** [comment]
What do you know... I juste neded to set the default database on the server and: voila! Thanks for the hint :-)

**Comment by hankinsoft** [comment]
Glad it's sorted out! If you run into anything else please let me know.

If you find that you are enjoying the app, please consider leaving a review on the app store! As an independent developer, reviews help me out a ton :)
