### ISSUE TITLE
Feature Request: Auto-capitalize keywords as you type

### ISSUE THREAD

**Issue by svsantos96** [hankinsoft/SQLPro#536]
I love the option in the query auto-formatter to capitalize mysql keywords. I've seen it done in other editors and I think it would be great if there was an option to auto-capitalized keywords and function names after you have completed them. So "selec" would become "SELECT" after you type the "t".

**Comment by jim256** [comment]
I've noticed this, too, and would like it.

FWIW, in the meantime, in case you weren't already aware you can also just not type the last character of the word and wait a moment for autocomplete to suggest it (because then it'll replace, for example, `selec` with `SELECT`).

**Comment by samrainey-mytech24** [comment]
I would also like to see this added. I realize there is the autocomplete selection and format SQL option, but having it auto-capitalize would be a nice time saver and convenient.

**Comment by jim256** [comment]
I'd definitely like to request this for words that you actually use autocomplete to accept.

For example, if I type `FROM products`, autocomplete will suggest the Snowflake table `PRODUCTS`. If I hit enter to accept it, it leaves it lowercased, which isn't intuitive, since it'd replace/capitalize the whole thing had I written `FROM product` and then accepted the finished suggestion.

**Comment by hankinsoft** [comment]
I've got this ready for a build next week:

![CleanShot 2023-03-15 at 11 49 11](https://user-images.githubusercontent.com/3160528/225347055-14417867-4680-45f0-b385-5057826343b4.gif)

You will have to enable a 'replace case as typing' option under 'Settings' -> 'Formatting' tab. The formatting will match the preferences already set on that screen. I will post here once the build is available.

**Comment by hankinsoft** [comment]
Going to close this issue as it's been in the store for a bit now. If anyone runs into any issues with it, please feel free to reopen and let me know.
