### ISSUE TITLE
App Crashes on macOD Big Sur 11.01 version 

### ISSUE THREAD

**Issue by ravihence** [hankinsoft/SQLPro#537]
I just updared SQLProStudio.2020.85.app version in my latest macOS and app started crashing. 
I can't open app anymore. 
Please fix and update me. 
ALso, any way I can download old version of SQLProStudio?

**Comment by hankinsoft** [comment]
You can grab the old version here:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.85.app.zip

To confirm:
1. You are currently using Big Sur?
2. You are seeing the crash report using SQLPro 2020.101?

Any chance you could you post the crash report?

**Comment by ravihence** [comment]
The old version your shared is the one I updated today and started crashing. 
I need a version before this. 

Yes, I am suing Bg Sur

PFA crash log. 


Best Regards, 
Ravi Boyareddy,

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.101.app.zip and see if that's working for you? This version is better optimized for BigSur.

You still see a crash after that, the older version is:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.74.app.zip

**Comment by ravihence** [comment]
Now. No version works. :-( 

PFA log 


Best Regards, 
Ravi Boyareddy,

**Comment by hankinsoft** [comment]
Are you trying to send the crash files via email? If so, they are not coming through :(

**Comment by ravihence** [comment]
Yes. I am sending as attachments. 
Can you confirm if you got all in this email? 

Best Regards, 
Ravi Boyareddy,

**Comment by hankinsoft** [comment]
Received email, but the attachments/crash logs are not available. I think you need to post them directly here:
https://github.com/hankinsoft/SQLPro/issues/537

**Comment by ravihence** [comment]
PFA 
[2020.101.pdf](https://github.com/hankinsoft/SQLPro/files/5575554/2020.101.pdf)
[2020.74.pdf](https://github.com/hankinsoft/SQLPro/files/5575556/2020.74.pdf)
[2020.82.pdf](https://github.com/hankinsoft/SQLPro/files/5575557/2020.82.pdf)
[SQLPRO-CRASH-LOG.pdf](https://github.com/hankinsoft/SQLPro/files/5575558/SQLPRO-CRASH-LOG.pdf)

**Comment by hankinsoft** [comment]
Could you give this verison a try:
https://d3fwkemdw8spx3.cloudfront.net/temp/SQLProStudio-T1.zip

I've made some changes based on the crash logs you've posted. Please let me know if this sorts the issue.

**Comment by ravihence** [comment]
Same issue. PFA log 

[2020.102.pdf](https://github.com/hankinsoft/SQLPro/files/5579100/2020.102.pdf)

**Comment by hankinsoft** [comment]
Can you try this build:
https://d3fwkemdw8spx3.cloudfront.net/temp/SQLProStudio-T2.zip

It's not going to fix the crash, but it has additional logging in the crashing method, and it also SHOULD open the logs folder automatically. You should just need to click on finder after SQLPro has crashed. If the logs folder is NOT open, then navigate too: 

> cd "~/Library/Containers/com.hankinsoft.osx.sqlprostudio/Data/Library/Logs/SQLPro Studio"

And post the log file.

**Comment by ravihence** [comment]
PFA log 
[com.hankinsoft.osx.sqlprostudio 2020-11-22--06-54-42-210.log](https://github.com/hankinsoft/SQLPro/files/5580136/com.hankinsoft.osx.sqlprostudio.2020-11-22--06-54-42-210.log)

**Comment by hankinsoft** [comment]
Are you ok if your 'autosave' information is cleared? If so, you can remove the folder:

`~/Library/Containers/com.hankinsoft.osx.sqlprostudio/Data/Library/Autosave Information`

And the app should launch without any issues. I'm still investigating the underlying crash.

**Comment by ravihence** [comment]
I delete Autosave Information
and launched the last 2 apps you gave me. Both are crashing. 
log is attached 
[com.hankinsoft.osx.sqlprostudio 2020-11-22--06-54-42-210.log](https://github.com/hankinsoft/SQLPro/files/5581314/com.hankinsoft.osx.sqlprostudio.2020-11-22--06-54-42-210.log)

**Comment by hankinsoft** [comment]
Hmmm, that's very odd. I'm going to create another build with additional debug logging and post it shortly.

**Comment by hankinsoft** [comment]
Please try:
https://d3fwkemdw8spx3.cloudfront.net/temp/SQLProStudio-T3.zip

Again, I've added additional logging around the crash point and the log folder should open upon launch.

**Comment by ravihence** [comment]
Hi 
I think I figured the issue out. 
I have opened recently a file directly from mail attachment with SQLStudioPro. Looks like its permission issue and everytime the studio loads, it looks for the file and it getting crashed. I just deleted the file from mail downloads, and SQLStudioPro opened with out crash. 
May be something for you to look and fix. 
Let me know if you need more details. 
PFA log created with t3. 
[com.hankinsoft.osx.sqlprostudio 2020-11-23--14-17-23-296.log](https://github.com/hankinsoft/SQLPro/files/5583675/com.hankinsoft.osx.sqlprostudio.2020-11-23--14-17-23-296.log)

**Comment by hankinsoft** [comment]
Thanks for the note and the log file. I've added some code to the 'restore state' routine that will check if the user has access to restored files on startup. If they do not, the file will be skipped.
