### ISSUE TITLE
SQL Pro for MSSQL Crashes on Big Sur

### ISSUE THREAD

**Issue by bmturney** [hankinsoft/SQLPro#538]
When I try to export a result set to CSV, it appears to export the file fine, but the app crashes immediately afterwards

**Comment by hankinsoft** [comment]
Thanks, I'm trying to figure this out. For some reason, the crash seems to happen if you save to a new file - replacing an existing file seems to work fine. I'm hoping to have it sorted out by the end of the week.

**Comment by hankinsoft** [comment]
If you are using the website version, a fix is available at:
https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.2020.104.app.zip

The App Store version has been submitted and should be available in ~24 hours or so.

**Comment by hankinsoft** [comment]
Just wanted to check in and see if this sorted the issue for you?
