### ISSUE TITLE
Support schema grouping in postgre

### ISSUE THREAD

**Issue by typeoneerror** [hankinsoft/SQLPro#54]
When you have quite a few schemas in a database, listing by "schema.table_name" gets a bit unwieldy. I'd love to see grouping by schema a la pgAdmin.

![screen shot 2016-09-29 at 11 36 18 am](https://cloud.githubusercontent.com/assets/218700/18967780/65352e2e-863b-11e6-9e9a-d0f8a9b1cf72.png)

![screen shot 2016-09-29 at 11 37 15 am](https://cloud.githubusercontent.com/assets/218700/18967783/6872c1aa-863b-11e6-8aad-3e2b052e7359.png)

**Comment by hankinsoft** [comment]
I'll be resolving this soon as its been one of the most requested features:
http://www.hankinsoft.com/forum/viewtopic.php?f=23&t=906

**Comment by hankinsoft** [comment]
Sorry, this has been implemented I just never closed the ticket. If you edit a postgres connection, choose advanced (just above the save button), then check (or uncheck) the checkmating that notes something about grouping (sorry I’m away from my Mac at the moment so I can’t rember the exact option name). You may need to disconnect and reconnect for the schema grouping to appear.

**Comment by donaldhurst** [comment]
No problem, I checked on my connection and this check box is currently checked yet I'm not seeing my schema's grouped still. I'm happy to send you more details but I'd rather do it via twitter DM or somewhere else offline. Let me know if that works for you.

**Comment by hankinsoft** [comment]
An you try unchecking that box, then closing and re-opening the connection
(right click disconnect on the database tree then reconnect). I think my
wording on the checkbox may convey the meaning backwards. Feel free to
reach out to me either through email or Twitter. Both of which are
available directly via the ‘support’ dropdown on the main connection list
(startup screen) of the app.

**Comment by donaldhurst** [comment]
Ah that was it, checkbox needed to be unchecked and now I see them grouped. Thanks for the support, exact feature I needed for our RedShift DB!

**Comment by hankinsoft** [comment]
Great! Any suggestions for alternative wording? 😁
