### ISSUE TITLE
TABs length issue

### ISSUE THREAD

**Issue by yeysman** [hankinsoft/SQLPro#540]
Hello,

It looks like SQLpro adds one character to the string with tabs.
My SQLpro and AzureStudio have similar tabs setting (1 tab = 4 spaces).
For some reason, if stored procedure or function contains a mix of spaces and tabs the alignment being broken.
At the same time if I cut not aligned part and insert it back (without any changes) - it will be inserted with correct alignment.

Please see the attached screenshot.
![image](https://user-images.githubusercontent.com/3490139/100541513-1b7d5000-324d-11eb-9696-fb4cfcf5d5a7.png)

You can notice that in SQLpro string with 3 tabs longer than a string with 12 spaces by 1 one character.

SQLpro
Version 2020.103 (Build 110759.5)

**Comment by jim256** [comment]
I've noticed that if it's mixed tabs vs spaces that they aren't quite aligned as well.

**Comment by yeysman** [comment]
Hello,
Any updates on this issue?

**Comment by hankinsoft** [comment]
Hi,
Sorry for the delay. I've been procrastinating on this partly because I don't 100% understand. Let me ask a few questions to try and get more details.

On the screenshots you posted in the initial post, where did the query come from? Was it pasted into the query editor, was it opened from a file, or was it a 'Script as' item?

To confirm, if you take that query, cut it then paste it back in, it works properly?

**Comment by yeysman** [comment]
Hello, @hankinsoft please see my comments below.

> On the screenshots you posted in the initial post, where did the query come from? Was it pasted into the query editor, was it opened from a file, or was it a 'Script as' item?
It was opened by "right-click on procedure/function" -> modify. But actually, it is no matter how and from where you opened code. There is an issue with tab size. 

> To confirm, if you take that query, cut it then paste it back in, it works properly?
Yes. If we cut and then past - alignment is fixed.

In order to reproduce this case you can try the following:
1. Go to settings and select "Tab style" to "Tabs"
2. Do three tabs and write something
3. Go to settings and switch "Tab style" to "4 spaces"
4. Go back to the editor, put a new line, and click "tab" button 3 times.
You will find that 12 spaces shorter than 3 tabs by 1 character.

It seems app doesn't use correct tab size.

**Comment by hankinsoft** [comment]
Thank you! I believe I have this all fixed up. Here is a video showing a tab character along with <x> spaces. Switching the tab preferences will now properly size the tab character to match <x> spaces. If spaces is not set (just tabs), then the tab width defaults to be 4 spaces wide.

![CleanShot 2021-02-02 at 08 07 02](https://user-images.githubusercontent.com/3160528/106598361-fe574d00-652d-11eb-9b00-5a14265c6e1d.gif)

This will be in the next build (either late this week or early next).

**Comment by yeysman** [comment]
@hankinsoft, thank you. 
Just want to clarify. There is no issue with spaces, but there is an issue with tab lengths.
The app makes the tab a bit longer than 4 characters. Why a bit longer? :) Because it is less than 5, but more than 4. :) 
![image](https://user-images.githubusercontent.com/3490139/106604813-d20cf200-6568-11eb-9de1-bdccbd28d9da.png)

Also, there is another (or maybe the same) issue with tabs. You can try to make a tab using font-size 14pt. It makes a bit more than 4 spaces. 
But if you increase a font-size to 18pt the app makes a tab size bit longer than 3 spaces. If you again increase a font-size - the tab size will be reduced. Meantime, if we reduce the font-size to 12pt the tab size will be increased to 5 spaces.

Something going wrong here :)

Please notice, all of this related to tab style "tab".

**Comment by hankinsoft** [comment]
Hi. If I'm understanding everything properly, this fix will resolve everything stated. Previously the tab-stop size was hardcoded. Now a tab size is being calculated based on the font and font size. As long as a fixed-width font size is being used, the next build should take care of it. (Couple of screenshots attached).

<img width="267" alt="Screen Shot 2021-02-02 at 10 55 10 AM" src="https://user-images.githubusercontent.com/3160528/106617638-31590b00-6545-11eb-98de-eb7bf37e3a3e.png">
<img width="211" alt="Screen Shot 2021-02-02 at 10 54 40 AM" src="https://user-images.githubusercontent.com/3160528/106617639-31590b00-6545-11eb-9664-a53898145276.png">

**Comment by yeysman** [comment]
@hankinsoft, it is great! 
Thank you. 
Waiting for the update :)

**Comment by yeysman** [comment]
@hankinsoft, today I updated SQLpro from appstore.
v. 2021.08 (Build 110770.5)

Now we have another very annoying issue with scrolling. It seems app each time recalculates the height of the editor area. 
In order to reproduce:
1. Create some function/stored procedure.
2. Put the code which takes 500-1000 lines (queries, comments, etc)
Already at this point, you will find an issue with smooth scrolling

https://user-images.githubusercontent.com/3490139/106710401-8d339a80-65fe-11eb-8839-dfad216d4db3.mov

3. Save procedure/function in DB. and close editor tab
4. Open this procedure (right-click "modify") and try to scroll

https://user-images.githubusercontent.com/3490139/106709555-64f76c00-65fd-11eb-9b41-5db2489e9d57.mov

I posted it here because I think it caused because of the fix for tabs.

**Comment by hankinsoft** [comment]
2021.09 is submitted with the fix.

**Comment by yeysman** [comment]
@hankinsoft, thank you.
The last update almost fixed the issue. There are still exist abrupt stops during scrolling to the top but is not so critical.

**Comment by hankinsoft** [comment]
Great! I'm going to mark this as closed as I think we are all set. FYI the latest build 2021.10 which is now available also had quite a performance update for syntax highlighting which might help with abrupt scrolls now and then.
