### ISSUE TITLE
Feature Request: Remember SQLite My Connections

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#541]
When reopening SQLPro, previous database connections are maintained in the My Connections window except for any opened SQLite databases. Would it be possible to include these as well?

I’m not sure, but if this becomes available, would it then be possible to allow a custom colour for SQLite tabs?

**Comment by hankinsoft** [comment]
> When reopening SQLPro, previous database connections are maintained in the My Connections window except for any opened SQLite databases. Would it be possible to include these as well?

Thanks for the feedback - I've been debating this myself. I'll take a look at adding it shortly.

> I’m not sure, but if this becomes available, would it then be possible to allow a custom colour for SQLite tabs?

That makes sense. I've never thought about the fact you couldn't set them for SQLite. I'll look at this during the same time.

**Comment by hankinsoft** [comment]
Hi, the most recent build now remembers SQLite connections and lets you set tab colors for them. If you get a chance, could you give it a try and let me know if that sorts everything?

**Comment by manngo** [comment]
I’m looking forward to it, but how do I test it? It’s not in the Australian, App Store yet but maybe that’s just a delay.
Thanks

**Comment by hankinsoft** [comment]
How are you opening the SQLite files currently? Via the File menu, or adding it via the 'New' -> 'SQLite' menu on the connections dialog?

**Comment by manngo** [comment]
My mistake. My apps upload automatically, so I didn’t notice that I already had a new version.

The SQLite connection reopened perfectly after a restart, and I had no trouble adding a custom colour for the tab.

Thanks as always.

**Comment by hankinsoft** [comment]
Awesome, thanks for letting me know its all good.
