### ISSUE TITLE
Run All / Run Selected Shortcut

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#542]
This is probably more than one issue, but they’re related.

Would it be possible to allow an additional shortcut key to Run Selected? That way we don’t have to go back to Preferences to change the behaviour. I now that I can select either from the dropdown button, and I know that I can select and Run All, but the additional shortcut would be an added convenience.

Related to this is the behaviour when Run Selected is enabled. Even when it’s not the default, it highlights the current statement. Personally I find this distracting, especially when the statement is preceded by a comment. Would it be possible to turn this off?

**Comment by jim256** [comment]
FWIW on the first point, I have Run Selected as the default, and when I want to execute all, I just use CMD + A + E (CMD + E being my execution shortcut). Could be handy to combine them into one shortcut, but this is also quite fast.

**Comment by Next-Door-Tech** [comment]
This should definitely be split into two issues.

RE: separate shortcuts, I was just wishing I could assign a shortcut to execute all separate from execute selected. Jim's workaround is functional but I'd like to have run all and run current/selected on two different letter keys.

As for the soft highlighting on the current query, I think a good solution would be to add a second highlight color in the theme options menu, rather than using the current single selection color at lower opacity as I suspect it currently works.

Just my 2¢ here

**Comment by hankinsoft** [comment]
Currently, I have the 'Query execution' shortcut. If I add a 'Secondary query execution' shortcut option that basically does the secondary task, would that work? (For the first issue)?

**Comment by hankinsoft** [comment]
And if so, would 'Secondary query execution' be a good enough title?

**Comment by Next-Door-Tech** [comment]
If what you’re thinking is the secondary query execution keybind running the non-default setting (i.e. if run selected is default, then the secondary keybind runs all, and vise versa) - I think that’d be perfectly fine. Name seems a little vague though. Maybe rename the primary keybind to “Run query (default)” and the secondary to “Run query (alternate)”. I’d also add a note that explains the difference.

**Comment by manngo** [comment]
What about Run Query / Run All, and choose which is the default?

**Comment by hankinsoft** [comment]
> What about Run Query / Run All, and choose which is the default?
I think adding a choice for the default would be confusing with the existing `Execute query in range` preference.

I'm currently leaning towards having two shortcuts:

1. Run query (default)
2. Run query (alternate)

Where the actions would depend on the `Execute query in range` preference with the following:

`Disabled` would have the alternative do nothing. The `Run query (alternative)` would be disabled as well.
`Enabled (as default)` would have the default shortcut run the selected query and the secondary shortcut would run all.
`Enabled (but not default)` would have the default shortcut run the everything and the secondary shortcut would run the selected query.

**Comment by hankinsoft** [comment]
Just wanted to check in on this. Did anyone have any options about the previous post?

**Comment by jim256** [comment]
My personal opinion would be that, given other things that dev time could go to, that the ease of having the default be `Execute query in range` and just using CMD+A and [Execute Shortcut Command] makes it not worth dev cycles. That's what I always do and it's really convenient.

Just my two cents from a single user of course.

**Comment by hankinsoft** [comment]
Going to close for now. If I receive enough requests, I will revisit this.
