### ISSUE TITLE
dates always export in long format

### ISSUE THREAD

**Issue by bbyrd** [hankinsoft/SQLPro#544]
...at least I think that's the problem. 

When I "export as CSV" a result set that includes a date that is CAST as a date -- ie. CAST(chosendate as date) -- the result always comes out looking like this in the CSV: 2020-09-01 00:00:00 +0000

Meanwhile, in the UI table the date shows correctly as a short date (2020-09-01) and if I highlight a row from that table and copy it out it retains the short date format.

Am I holding it wrong?

**Comment by hankinsoft** [comment]
Thanks, I’ll investigate a which type of database are you connecting too?

**Comment by bbyrd** [comment]
Microsoft SQL Server 2017

**Comment by hankinsoft** [comment]
Fixed for the next build - Should be available later this week. Are you using SQLPro Studio, or SQLPro for MSSQL? And from the App Store or website?

**Comment by hankinsoft** [comment]
Closed as this has been sorted.
