### ISSUE TITLE
Feature Request: Built-in Ultra-Basic Charts / Graphs

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#545]
I recognize that this would be quite the task, but it would also be extremely valuable (and would do even more to set SQLPro apart from other, text-only clients).

In the new Snowflake preview app (as well as in some other SQL clients I've seen), some visualizations are available based off the query results:

<img width="1781" alt="image" src="https://user-images.githubusercontent.com/15026225/100945397-5fc35700-34be-11eb-8939-279bf68bd6e0.png">
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/15026225/100945419-6d78dc80-34be-11eb-98ae-958249506a61.png">

For just at-a-glance adhoc analysis, I've wanted something like this so so many times, because you've otherwise got to take the data outside SQLPro. Obviously it isn't meant to be a data visualization tool, but this kind of thing can sure be helpful in these scenarios.

I think this feature would pair very nicely with #286

**Comment by hankinsoft** [comment]
Going to close this, unless I receive additional requests for it.
