### ISSUE TITLE
How I can comment/uncomment selected multiple line?

### ISSUE THREAD

**Issue by trirex79** [hankinsoft/SQLPro#546]
1.How I can comment/uncomment selected multiple line? Is there any shortcut? 
2.How I can redefine shortcut? Shift+cmd+E is not comfortable shortcut.

**Comment by jim256** [comment]
1. You can (un)comment multiple selected lines using the keyboard shortcut you define in Preferences -> Keyboard
2. You can also redefine many shortcuts in the same place

<img width="471" alt="image" src="https://user-images.githubusercontent.com/15026225/101959112-ec0e0200-3bc1-11eb-885e-5faebab334bf.png">

**Comment by hankinsoft** [comment]
Thanks @jim256.
