### ISSUE TITLE
Question: Where are private SSH key files being stored? Apple or Hankinsoft?

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#547]
I recently switched computers and noticed that I was still able to connect via SSH to machines that did not have my new key.

I looked at my connections and noticed that they still showed the path and filename that were on the previous computer (and are not present on this computer).

I wasn't aware that the private keys were being stored anywhere. Where are they stored? I'd like to request that they aren't stored anywhere.

**Comment by hankinsoft** [comment]
SSH keys are stored in iCloud along with the other connection details. This is so that when switching macOS/iOS devices, the connections continue to work.

I'll add an option to disable SSH keys sync.

**Comment by hankinsoft** [comment]
Added for the next version. Please note that if sync is turned off, connections with SSH may not work on other devices unless the private key file path matches exactly on all devices.
