### ISSUE TITLE
PAYMENT PROBLEM

### ISSUE THREAD

**Issue by cuneytserdaroglu** [hankinsoft/SQLPro#549]
Hello;

I am having a problem entering my card information. Can you help me please.

The error I get is as follows.

"We regret that your order could not be accepted. We value your business and would like to help you complete this order. Please contact us for assistance.”

**Comment by hankinsoft** [comment]
Hi,
From what I can see on the payment side, there is an issue with the credit card being entered. Specifically I see:

> Credit Card Update Restricted 
> RESTRICTED, Proc=CVC Declined

Are you entering the correct CVC? Also, are you using a VPN of any sort? I've seen ordering issues with them in the past.

**Comment by cuneytserdaroglu** [comment]
Hi;
I tried it with different cards.  but the problem was not resolved.  When I tried it for the first time, my vpn connection was active, then I tried turning off the vpn.

Can you send a new link.
Thank you.

**Comment by hankinsoft** [comment]
Hi,
Could you send me an email via kyle@hankinsoft.com (or provide me with your email address) and I will put you in touch with the store providers support team.

**Comment by cuneytserdaroglu** [comment]
Hello, 

This is my email address :  cuneyt.serdaroglu@bahcesehir.edu.tr 

Thank you. 

iPhone’umdan gönderildi

> Kyle Hankinson <notifications@github.com> şunları yazdı (9 Ara 2020 16:39):
> 
> Could you send me an email via kyle@hankinsoft.com (or provide me with your email address) and I will put you in touch with the store providers support team.

**Comment by cuneytserdaroglu** [comment]
Hello, 

Can you give feedback this issue?

iPhone’umdan gönderildi

> Cuneyt Serdaroğlu <cuneytserdaroglu@gmail.com> şunları yazdı (9 Ara 2020 17:11):
> 
> ﻿Hello, 
> 
> This is my email address :  cuneyt.serdaroglu@bahcesehir.edu.tr 
> 
> Thank you. 
> 
> iPhone’umdan gönderildi
> 
>> Kyle Hankinson <notifications@github.com> şunları yazdı (9 Ara 2020 16:39):
>> 
>> Could you send me an email via kyle@hankinsoft.com (or provide me with your email address) and I will put you in touch with the store providers support team.

**Comment by hankinsoft** [comment]
Hi,
I have emailed Fastspring and am waiting a response. FYI, I see a note attached to that email:

"No longer blocked. However there previously was a block that has expired. The block was for 'Credit Card'.
Last Attempt: Dec. 8, 2020, 2:49 p.m."

If you try the purchase again (without a VPN) does it work?

**Comment by cuneytserdaroglu** [comment]
Thank you Kyle, 

My registration was completed successfully. 

iPhone’umdan gönderildi
