### ISSUE TITLE
"Finished with error" (but without details)

### ISSUE THREAD

**Issue by mklaber** [hankinsoft/SQLPro#55]
Using SQLPro w/ MSSQL connected via Windows Auth. Connected to a server and then changed my password. When I tried running a query again, not shocking, it lost a connection. But what wasn't particularly helpful was that the status bar just says "Finished with error." but no additional details. 

Results pane:

```
Executing query...
Command completed successfully.
```

Status bar:

⚠️ Finished with error. 0 records. 0.770 seconds.

I have no problem with it not keeping up with my auth changes. It'd be great, though, if it... you know... told me what error it finished with. And didn't say the command completed successfully.

**Comment by hankinsoft** [comment]
Thank you! I'll fix this in an upcoming build.

**Comment by hankinsoft** [comment]
This has been fixed for awhile, but I forgot to post a note. If you run into the issue again, please let me know (and preferable post a screenshot as well).

**Comment by mklaber** [comment]
@hankinsoft I'll give it a shot when I have a moment to change my password (easier said than done with windows auth/domain)
