### ISSUE TITLE
[Studio macOS] Preferences Menu - Info Button for "Execute Query in Cursor Range" Links to Deprecated Page

### ISSUE THREAD

**Issue by Next-Door-Tech** [hankinsoft/SQLPro#550]
This should be a quick and easy fix - the info button for the "Execute query in cursor range" option in the preferences menu links to the old [GitHub Wiki page](https://github.com/hankinsoft/SQLPro/wiki/Execute-query-in-cursor-range) instead of the [sqlprostudio.com blog post](https://www.sqlprostudio.com/blog/12-execute-query-in-cursor-range) where the help article is now located.

The other info buttons in that menu link to the correct location.

Encountered on SQLPro Studio for macOS Version 2020.106 (Build 110761.5)
I haven't checked any of the other mac apps to see if the issue occurs elsewhere.

![Screen Shot 2020-12-11 at 6 34 52 PM](https://user-images.githubusercontent.com/5867663/101970604-31d9c300-3be0-11eb-955f-8688f28c5ea7.png)

**Comment by hankinsoft** [comment]
Thank you for the note. This has been fixed for the next build (2021.05). I will close the issue once the build is available.

**Comment by hankinsoft** [comment]
New build is available. Please give it a try and let me know if this is fixed up for you.

**Comment by Next-Door-Tech** [comment]
Just checked - all fixed!
