### ISSUE TITLE
[sqlprostudio.com] "Execute Query in Cursor Range" Setting Descriptions Are Incorrect 

### ISSUE THREAD

**Issue by Next-Door-Tech** [hankinsoft/SQLPro#551]
https://www.sqlprostudio.com/blog/12-execute-query-in-cursor-range

The help article for the "Execute query in cursor range" preference menu on sqlprostudio.com has the descriptions for Enabled (as default) and Enabled (but not default) reversed from the way the setting acts in the macOS app.

The current description for those options is:

> ### Enabled (as default)
> When enabled, the `Current query` will have a slight highlight. The default `run query` button will still be `Run all`, however the dropdown will contain a `Run current` option.
> 
> ### Enabled (but not default)
> The `Current query` will have a slight highlight. The default `run query` button will still be `Run current`, however the dropdown will contain a `Run all` option.

However, setting Enabled (as default) *does* change the default to `Run current` and Enabled (but not default) leaves the default as-is.

The correct information would be as follows:
> ### Enabled (as default)
> When enabled, the `Current query` will have a slight highlight. The `Run query` button will default to `Run current`, however the dropdown will contain a `Run all` option.
> 
> ### Enabled (but not default)
> When enabled, the `Current query` will have a slight highlight. The `Run query` button will still default to `Run all`, however the dropdown will contain a `Run current` option.

**Comment by hankinsoft** [comment]
Thank you, I'll have this updated shortly.

**Comment by hankinsoft** [comment]
Fixed up. Thanks again.
