### ISSUE TITLE
Didn't receive license key after renewing subscription

### ISSUE THREAD

**Issue by JulienDemarque** [hankinsoft/SQLPro#552]
Is this the official support channel? I wrote email a week ago and didn't get any reply.

**Comment by hankinsoft** [comment]
Hi, yes this is the best support channel. I apologize as I don’t see the email anywhere. Did you purchase via the webstore or the apple store? If you purchased from the apple store you won’t have a license key - you should be able to hit the ‘restore’ button on the activation screen.

**Comment by JulienDemarque** [comment]
Oh thanks, it wasn't clear to me 'restore' was a button... Anyway it works now. Thanks!

**Comment by hankinsoft** [comment]
No problem and sorry for the issue!
