### ISSUE TITLE
Import from CSV Error (ORA-04036)

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#553]
Using SQLPro Studio I exported from SQL Server 1,773,338 records to import into Oracle.  Using SQLPro Studio I began the import process of the 1.7 million rows but received the error below after 7.15% of the data was imported (126,753 rows).

_Failed to perform insert with error: ORA-04036: PGA memory used by the instance exceeds PGA_AGGREGATE_LIMIT_

Without changing the Oracle parameter PGA_AGGREGATE_LIMIT is there an option to import the data in chunks?  Not sure if this would fix the issue.

**Comment by hankinsoft** [comment]
I think the fix for https://github.com/hankinsoft/SQLPro/issues/563 will help with this as well. I was not properly freeing oracle statements during 'non queries'. Because I am chunking inserts into 500 per insert, this means an import of 17 million would create > 3,000 dangling statements and the memory limit would be hit.

**Comment by cwolcott** [comment]
I believe this is fixed, I was able to import 1.4 million records before receiving an ORA-03113 End-of-file on communication channel.  I am working from home and may have had a hiccup on our VPN.  I will try again tomorrow from the office.

**Comment by cwolcott** [comment]
I tried the import again tonight while watching the chaos down the highway in DC.  Interesting enough it failed exactly at the same point after about 35 minutes (based on the log).  I was activity on the laptop during the import in other applications. 

The import was attempting to import 15,500,740 records.  The process failed with an the following error:
    _Failed to perform insert with error: ORA-03113: end-of-file on communication channel
    Process ID: 18713
    Session ID: 179 Serial number: 123145302347218_

I thought this error previously was because of a network hiccup, but after each failure there were 1,419,333 records.  This happening twice seems very odd.  There were 2,833 bulk inserts of 501 records before the oracle error.  The log has many sessions the latest starts on the following line in the attached log.

2021/01/07 02:04:15:973  importFromCSV - CSV file has 15500740 rows.
[com.hankinsoft.osx.sqlprostudio 2021-01-06--16-46-22-866.log](https://github.com/hankinsoft/SQLPro/files/5779243/com.hankinsoft.osx.sqlprostudio.2021-01-06--16-46-22-866.log)

I will try again at the office tomorrow.

**Comment by cwolcott** [comment]
Ran this a third time tonight and the same thing occurred.  Failed with the same error after 1,419,333 records being imported.

I made sure to click on the SQL Pro Studio several times during the import to make sure it was active.  The log shows: **_Application is becoming active_**.
[com.hankinsoft.osx.sqlprostudio 2021-01-07--03-05-02-110.log](https://github.com/hankinsoft/SQLPro/files/5779449/com.hankinsoft.osx.sqlprostudio.2021-01-07--03-05-02-110.log)

Any thoughts?

**Comment by hankinsoft** [comment]
Thanks - I see I need to add some extra logging --- additionally, I'm thinking I might need to add some 'COMMITs' to the insert process. Oracle by default does not use auto commit, so I'm thinking all those inserts even though its batched into 500 (or 501 according to the logs), are not committed -- it might be a memory issue. Maybe the connection has a memory limit which would make sense with it being the same point every. I'm going to investigate adding commits, plus add some additional logging for build 2021.02.

**Comment by cwolcott** [comment]
I have upgraded to **SQLPro Studio Version 2021.02** from the AppStore (Says 2021.01 in version history, but 2021.02 in about dialog). I see you fixed your loop to insert 500 and not 501 records :-).

I received the same error over VPN, but only 678,500 records were inserted this time instead of 1,419,333 records.  Attached is the log, not sure if it will tell you anything.  I will plan to go to the office on Saturday to try again.
[com.hankinsoft.osx.sqlprostudio 2021-01-08--19-15-03-271.log](https://github.com/hankinsoft/SQLPro/files/5789102/com.hankinsoft.osx.sqlprostudio.2021-01-08--19-15-03-271.log)

**Comment by cwolcott** [comment]
I am going to close this ticket.  I am currently 73% imported while running at the office and not via VPN at home.  Not sure why we get the disconnect on VPN.  I will research with the IT group and Oracle Admin.
