### ISSUE TITLE
Apple subscription account is randomly throwing "Activation" window

### ISSUE THREAD

**Issue by bbyrd** [hankinsoft/SQLPro#554]
It's hard to pinpoint what is causing this, but I'm getting the "Activate SQLPro Premium" window thrown.

This seems to have just started this week (or possibly on late last week).

My Apple account says that I have an active subscription, and when I try going ahead and subscribing again it tells me I'm already subscribed.

I tried restarting my machine and it worked on the first query or two and then retroactively popped the activation window.

Sorta a blocker, as you can imagine.

**Comment by hankinsoft** [comment]
I've had some users in the past run into similar issues. Generally the solution is to uninstall/reinstall the app (I have an article on it here: https://github.com/hankinsoft/SQLPro/wiki/App-Store-Subscription-not-Renewing).

If that still does not fix the solution I generally suggest cancelling the subscription from the app store and purchasing via the website.

Please let me know if any of these suggestions help out.

**Comment by bbyrd** [comment]
Is there a way to backup/save my saved queries (aka "Favorites") before uninstalling? Or will I need to manually save them all?

**Comment by hankinsoft** [comment]
Hi,
Favorites are stored externally to the app package, so unless you use
something like AppCleaner to remove the app, they won't be removed.

Cheers,
Kyle

**Comment by bbyrd** [comment]
Thanks. Just verified that favorites are there after re-installing. For anyone curious, I just moved the old app to the trash and then re-downloaded from the App Store.
