### ISSUE TITLE
Query results grid reverts to default scroll position (far left) after switching tabs

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#555]
If I scroll horizontally or vertically in the query results grid, then switch tabs, then come back to the previous tab, the query results grid is defaulted back to the 1st row and 1st column.

This has persisted across quitting and restarting the app, different database types, and happens whether switching via mouse or keyboard shortcut.

I've only noticed this in 2020.106 (Build 110761.5)
macOS 11.1 (20C69)

**Comment by hankinsoft** [comment]
Thank you. This is fixed for the next build (hopefully available later this week).

**Comment by cwolcott** [comment]
Looks good to me, hopefully jim256 agrees.

**Comment by jim256** [comment]
LGTM
