### ISSUE TITLE
Unable to apply license to SQLPro for MSSQL that I got from App Store on Mac

### ISSUE THREAD

**Issue by sahoko** [hankinsoft/SQLPro#556]
I have a license key that I got in 2016. I recently switched to a new Mac and got SQLPro from App Store. I tried to activate but it keeps telling me it's invalid.

**Comment by hankinsoft** [comment]
Can you email me a picture of the license dialog with your email and license key entered + plus visible? Email to kyle @ hankinsoft.com.

**Comment by hankinsoft** [comment]
Sorted via email.
