### ISSUE TITLE
Calling proc results in `Commands out of sync` error.

### ISSUE THREAD

**Issue by rherbelinpxg** [hankinsoft/SQLPro#557]
New issue.  Hasn't been previously observed.

After calling a stored procedure, any subsequent commands in the same query window fail and return "Commands out of sync; you can't run this command now. (Error #2014)Commands out of sync; you can't run this command now. (Error #2014)"

Attempted the same tests using another client and no issue there.

MAC OS Mojave
SQLPro version: Version 2020.103 (Build 10507.5)

**Comment by hankinsoft** [comment]
Hi,
Which type of database is this that you are connecting to? (MySQL, PostgreSQL, SQL Server, other)?

**Comment by rherbelinpxg** [comment]
My apologies for the omission.  I’m using the MySQL client.

[PXG]
Russ Herbelin
Database Architect | PXG<https://www.pxg.com/>
D: | C: 480-734-1627<tel:480-734-1627>
[Nobody makes golf clubs the way we do. Period. TM]

**Comment by hankinsoft** [comment]
Just trying to figure out what's going on here -- do you know if your procedure returns more than one result set?

**Comment by rherbelinpxg** [comment]
It does not.  Only a single result set is returned.  This is also a recent issue.  It hadn’t happened previously, back when I originally wrote these procs.  If you are having a difficult time reproducing we can set up a call and I can screen share for you.

[PXG]
Russ Herbelin
Database Architect | PXG<https://www.pxg.com/>
D: | C: 480-734-1627<tel:480-734-1627>
[Nobody makes golf clubs the way we do. Period. TM]

**Comment by hankinsoft** [comment]
Thanks - I've submitted a fix which I think might resolve it. SQLPro for MySQL 2020.110 should be available on the Mac app store sometime tomorrow.

**Comment by rherbelinpxg** [comment]
Thank you very much!  I’ll look for it and then let you know the results.


[PXG]
Russ Herbelin
Database Architect | PXG<https://www.pxg.com/>
D: | C: 480-734-1627<tel:480-734-1627>
[Nobody makes golf clubs the way we do. Period. TM]

**Comment by rherbelinpxg** [comment]
I installed the update and the problem has been resolved.  Thank you very much for your efforts!

[PXG]
Russ Herbelin
Database Architect | PXG<https://www.pxg.com/>
D: | C: 480-734-1627<tel:480-734-1627>
[Nobody makes golf clubs the way we do. Period. TM]


From: Russell Herbelin <rherbelin@pxg.com>
Date: Monday, January 4, 2021 at 12:08 PM
To: hankinsoft/SQLPro <reply@reply.github.com>, hankinsoft/SQLPro <SQLPro@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [EXTERNAL] Re: [hankinsoft/SQLPro] Calling proc results in `Commands out of sync` error. (#557)

Thank you very much!  I’ll look for it and then let you know the results.


[PXG]
Russ Herbelin
Database Architect | PXG<https://www.pxg.com/>
D: | C: 480-734-1627<tel:480-734-1627>
[Nobody makes golf clubs the way we do. Period. TM]
