### ISSUE TITLE
Bug: Query tab color does not change when changing connection

### ISSUE THREAD

**Issue by samrainey-mytech24** [hankinsoft/SQLPro#559]
The query tab color does not change automatically when changing the server / connection of a query. It will only change when you mouse over the tab. This could lead to accidentally running a query on the wrong server, such as running in production when meaning to run it on a test server.

Software: SQLPro Studio Version 2020.107 (Build 110762.5)
OS: MacOS Big Sur 11.1

Steps to reproduce:
- Create more than one server connection and assign a color to each
- Open a query
- Change the server / connection
- Tab color does not change
- Moving the mouse pointer over the tab changes the color to the correct one

**Comment by hankinsoft** [comment]
Thank you - this is fixed for the next build which should be available later this week.

**Comment by samrainey-mytech24** [comment]
Thank you for the quick response. I will respond again when the update is released.

**Comment by cwolcott** [comment]
Still has a bug if more than 2 tabs.
https://user-images.githubusercontent.com/3777526/103779137-4f445600-5001-11eb-9a41-45a9f18d3989.mov



**OS:** MacOS Catalina 10.15.7
**Software:** SQLPro Studio Version 2020.110 (Build 110763.5)
**Connection:** Oracle 18c

**Comment by hankinsoft** [comment]
Thank you for letting me know!

**Comment by hankinsoft** [comment]
Fixed for the next build (available either later this week or early next).

**Comment by samrainey-mytech24** [comment]
Thank you for the quick attention to this issue

**Comment by cwolcott** [comment]
Looks good to me.
