### ISSUE TITLE
App unhides itself or barges forward when refreshing

### ISSUE THREAD

**Issue by JetForMe** [hankinsoft/SQLPro#560]
If an external change to the DB occurs, it reloads the table (that's great), but it also unhides the app. This behavior is annoying and I have to turn off the auto reload, which I'd rather not do.

**Comment by hankinsoft** [comment]
Just to confirm, this is for SQLPro for SQLite?

**Comment by JetForMe** [comment]
Oh, yes, sorry. Didn't realize there were so many variants!

**Comment by hankinsoft** [comment]
Hi - in the latest builds using macOS 12.1, you will get a single bounce when re-loading and the app will not come forward. I think this should do?

**Comment by JetForMe** [comment]
Yes, this should do.
