### ISSUE TITLE
Bug: Import to new table not fully refreshed in side menu

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#561]
When importing from CSV to a new table the **Database Tree menu** is nicely updated with the new table name, but it is not fully updated.  The column names are missing.
![image](https://user-images.githubusercontent.com/3777526/103355261-d3d02b00-4a7b-11eb-987a-0b808650a6ec.png)

If I click on the new table and select the **Refresh** option from the context menu nothing is updated
![image](https://user-images.githubusercontent.com/3777526/103355344-fd895200-4a7b-11eb-9f2c-a2815b7e6374.png)

But if I click on the **Table** folder and select the **Refresh** option from the context menu the column details now appear.
![image](https://user-images.githubusercontent.com/3777526/103355478-5c4ecb80-4a7c-11eb-8030-26cb72931348.png)
![image](https://user-images.githubusercontent.com/3777526/103355435-3b867600-4a7c-11eb-90c9-c2b9cee8b860.png)

I noticed this because I have 5 files to import into this new table back to back.  After importing the first file I selected the table explicitly and  attempted to import the 2nd file.  I noticed that it did not preselect the correct table in the dropdown to import the data too.
![image](https://user-images.githubusercontent.com/3777526/103355991-b9974c80-4a7d-11eb-97cc-93a6d9445280.png)

Once I refreshed the information so the columns were defined I could select the table and import subsequent files and the table was preselected in the list.
![image](https://user-images.githubusercontent.com/3777526/103355939-91a7e900-4a7d-11eb-81cc-f88b44bfeded.png)

**OS:** MacOS Catalina 10.15.7
**Software:** SQLPro Studio Version 2020.107 (Build 110762.5)
**Connection:** Oracle 18c

**Comment by hankinsoft** [comment]
Fixed for the next build. Should be available later this week.

**Comment by cwolcott** [comment]
Confirmed that this is fixed.
