### ISSUE TITLE
Bug:  Import message says Processing NULLs

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#562]
After selecting a csv file for importing dialog messages are displayed:
- Reading CSV file, please wait.                 _[@ 2 seconds]_
- Processing NULLs. 99.14% complete.  _[@ 3 seconds]_

Is the word **NULLs** correct or is it suppose to say something else?

https://user-images.githubusercontent.com/3777526/103367197-7bf0ee80-4a92-11eb-81ef-c3f676da8878.mov

**OS:** MacOS Catalina 10.15.7
**Software:** SQLPro Studio Version 2020.107 (Build 110762.5)
**Connection:** Oracle 18c

**Comment by hankinsoft** [comment]
Hi - During this step the CSV entries are checked for NULL values - the string '<NULL>' and the 'NULL' (case insensitive) are both treated as null. This can sometimes take a while depending on the CSV size, which is why this message appears. Does that answer your question?

**Comment by cwolcott** [comment]
Yep, just thought variable being shown as **NULL**s my have been undefined.  Just looked a little odd.
