### ISSUE TITLE
Bug: Cursor leak during import

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#563]
I am importing several files into the same table.  Eventually I receive the following:
![image](https://user-images.githubusercontent.com/3777526/103379423-9dae9d80-4ab3-11eb-8daf-cc3dc903816e.png)

The error occurred during the 5th file import.
- **File 1:** 41,853 records
- **File 2:** 4,928 records
- **File 3:** 56,828 records
- **File 4:** 4,288 records
- **File 5:** 101,760 records **_(failed)_**

After the error there were 147,977 records, thus 40,080 records (39.39%) were inserted from **File 5** when the error occurred.  I was able to duplicate the results a 2nd time after truncating the table and quitting SQLPro.

I deleted the previous log and opened SQLPro fresh, executed the imports, received the error, then closed SQLPro.
[com.hankinsoft.osx.sqlprostudio 2020-12-30--20-19-29-058.MaxOpenCursors.log](https://github.com/hankinsoft/SQLPro/files/5755616/com.hankinsoft.osx.sqlprostudio.2020-12-30--20-19-29-058.MaxOpenCursors.log)

I ran it a third time importing the 5 files in a different order:
- **File 5:** 101,760 records
- **File 4:** 4,288 records
- **File 3:** 56,828 records **_(failed)_**

After the error there were 148,132 records, thus 42,084 records (74.05%) were inserted from **File 3** when the error occurred.

Here is the log for the 3rd run.
[com.hankinsoft.osx.sqlprostudio 2020-12-30--20-42-58-647.MaxOpenCursors.log](https://github.com/hankinsoft/SQLPro/files/5755679/com.hankinsoft.osx.sqlprostudio.2020-12-30--20-42-58-647.MaxOpenCursors.log)

I ran it a forth time quitting SQLPro after a couple imports, to hopefully cleanup any open cursors:
- **File 5:** 101,760 records
- **File 4:** 4,388 records
- _Quit and restart SQLPro_
- **File 3:** 56,828 records
- **File 2:** 4,928 records
- _Quit and restart SQLPro_
- **File 1 :** 41,853 records

That worked, but is obviously painful.

**OS**: MacOS Catalina 10.15.7
**Software:** SQLPro Studio Version 2020.107 (Build 110762.5)
**Connection:** Oracle 18c

**Comment by hankinsoft** [comment]
Hi,
So I do currently split inserts up into 500 entries per insert. When importing, something similar to the following will be run:

> INSERT ALL
> INTO mynewtable (SalesOrderID,SalesOrderDetailID,OrderQty,ProductID,UnitPrice,UnitPriceDiscount,LineTotal,rowguid,ModifiedDate) VALUES ('71938','113276','2','835','356.898','0','713.796','7D738F6B-9825-4FD3-9D21-F703CBCED4F4','2008-06-01 00:00:00.000')
> INTO mynewtable (SalesOrderID,SalesOrderDetailID,OrderQty,ProductID,UnitPrice,UnitPriceDiscount,LineTotal,rowguid,ModifiedDate) VALUES ('71938','113277','3','974','1020.594','0','3061.782','9B9A0C77-1B13-4411-9DD0-26027FAEB98C','2008-06-01 00:00:00.000')
> INTO mynewtable (SalesOrderID,SalesOrderDetailID,OrderQty,ProductID,UnitPrice,UnitPriceDiscount,LineTotal,rowguid,ModifiedDate) VALUES ('71938','113278','3','707','20.994','0','62.982','E000AFD3-CCD5-43E8-A10F-B29EC9CAEAED','2008-06-01 00:00:00.000')
> 
> ..... up to 500 inserts at a time .....
> 
> SELECT 1 FROM DUAL

BUT I think I might see what's going on with this issue - I'm making a fix which MIGHT fix it for the next build (I'm unfortunately not able to reproduce it, so I'm not 100% certain).

**Comment by cwolcott** [comment]
Since it is repeatable on my end I will be able to test it quickly.  If there are still issues I can perform any tests required and provide logs.

**Comment by hankinsoft** [comment]
Great! I'm just working on fixing a few of the other import items as well, but I hope to have the build available this week.

**Comment by hankinsoft** [comment]
The new version is now available. If you get the chance, could you check if this sorts it out? --- -Actually I forget - were you using SQLPro Studio or SQLPro for Oracle? (SQLPro Studio is available).

**Comment by cwolcott** [comment]
The ticket shows in the footer that I am using **SQLPro Studio Version** 2020.107 (Build 110762.5) right now.

I have a 1pm EST meeting that I am preparing for so I will not get to it until this afternoon.

**Comment by cwolcott** [comment]
Fix confirmed.  I was about to import 14 files back to back with a total of 380,816 records without any issues.

**OS:** MacOS Catalina 10.15.7
**Software:** SQLPro Studio Version 2020.110 (Build 110763.5)
**Connection:** Oracle 18c
