### ISSUE TITLE
Feature Request: Show FOREIGN KEY indexes in table tree

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#564]
Would it be possible to show **FOREIGN KEY** indexes in the Table Tree?

The current table **ASSAY_CONFIGURATION** has a _Primary Key_ and _Foreign Key_ defined.
![image](https://user-images.githubusercontent.com/3777526/103548221-75d48680-4e73-11eb-8cb1-cfb1cce41054.png)

But in the Table Tree only the Primary and Unique keys are shown.
![image](https://user-images.githubusercontent.com/3777526/103548060-37d76280-4e73-11eb-8e23-a7fc638f5200.png)

I might be doing something wrong when defining the foreign keys because when I try to disable the index I get:
    ALTER INDEX FK_ASSAYCONFIG_DEFID disable;
    ORA-01418: specified index does not exist

**OS:** MacOS Catalina 10.15.7
**Software:** SQLPro Studio Version 2020.107 (Build 110762.5)
**Connection:** Oracle 18c

**Comment by hankinsoft** [comment]
In Oracle, [a foreign key is not actually an index](https://stackoverflow.com/a/4127238/127853) which might be why you cannot disable it. Based on that, I'm not sure foreign keys would be best listed underneath the indexes tree node. Thoughts?

**Comment by cwolcott** [comment]
Wow how soon I forget.  I would be nice to see a Foreign Key folder with a list of foreign keys.  Using the query for the Oracle code from StackOverflow: [List of foreign keys and the tables they reference in Oracle DB](https://stackoverflow.com/questions/1729996/list-of-foreign-keys-and-the-tables-they-reference-in-oracle-db)

I see under SQL Server I see a Keys folder that is showing a primary key.  I guess you could do the same under Oracle and show a different icon for a Foreign Key.

SELECT a.table_name, a.column_name, a.constraint_name, c.owner, 
       -- referenced pk
       c.r_owner, c_pk.table_name r_table_name, c_pk.constraint_name r_pk
  FROM all_cons_columns a
  JOIN all_constraints c ON a.owner = c.owner
                        AND a.constraint_name = c.constraint_name
  JOIN all_constraints c_pk ON c.r_owner = c_pk.owner
                           AND c.r_constraint_name = c_pk.constraint_name
 WHERE c.constraint_type = 'R'
   AND a.table_name = :TableName

The tree item should be the CONSTRAINT_NAME.  The subtext could the the 1..n column names associated with the constraint.

The menu items should have:
    **Drop Constraint:**   alter table _tableName_ drop constraint _constraintName_

**Comment by hankinsoft** [comment]
Added for the upcoming 2021.05. Also, you are awesome for providing the SQL and what you want in the context menu!

**Comment by hankinsoft** [comment]
New build is available. Please give it a try and let me know if this is fixed up for you.

**Comment by cwolcott** [comment]
It does work.  I would like to submit one more suggestion on Thursday.

**Comment by hankinsoft** [comment]
Going to close this issue. If you come up with additional items, feel free to re-open or create a new item.
