### ISSUE TITLE
Table missing from search panel

### ISSUE THREAD

**Issue by cr00maui** [hankinsoft/SQLPro#565]
Hi,

MacOS 11.1
SQLStudioPro 2020.104 (Build 110760.1)

When reviewing the "schema/search" (left) panel I am not able to find a table I know exists when the panel is in "search" mode. Example: I know a table "GavelObjectAsset" exists. When the left panel is in "schema" mode (database icon) the table name is visible under DBNAME > TABLE > dbo.GavelObjectAsset. When I switch to "search" mode "search everywhere" and "ignore case" with no text entered in the search field the table name is not present in the list of objects. If I search for "asset" four other tables with the names containing "asset" appear but not "GavelObjectAsset."

I can query and otherwise interact with the table without issue. The db in question is MSSQL.

Thanks for reviewing,

Chris

**Comment by hankinsoft** [comment]
Hmm, if you right click on the 'database' tree node and choose 'refresh' then wait a few moments, are you able to search for the said item?

**Comment by cr00maui** [comment]
'Refresh' did not change the behaviour. I also tried 1) disconnect/reconnect and 2) limiting the connection to a single database with no change. When I duplicated the connection profile and used the new profile (alongside the old profile) the new profile shows the missing table and the old profile does not.

**Comment by hankinsoft** [comment]
Hi,
Were you still seeing this issue? I've made a few changes around search, but I was never able to reproduce it, so I'm not 100% sure the status.

**Comment by cr00maui** [comment]
Sorry for my delay in responding— I can confirm that the tables I noticed were missing are now visible in the search results. Thanks.
