### ISSUE TITLE
Exporting Data to MySQL messes the whole data

### ISSUE THREAD

**Issue by vdhub** [hankinsoft/SQLPro#567]
Hello, 

It would be nice if the Export to MySQL would have as well support for MariaDB as it is a more convenient version that we could use . Now, honestly I have to export it as it is , patch the sql file , adapt it to mariadb and then import it and some times it crashes due to some incompatibility issues. I do have 2 licenses and it would be nice to have it working as well.

Thanks.

**Comment by hankinsoft** [comment]
Hi,
The export should be working with MariaDB and MySQL - what are the patches you have to apply?

**Comment by hankinsoft** [comment]
No response.
