### ISSUE TITLE
Import CSV: Column Type Detection Wrong

### ISSUE THREAD

**Issue by andyoneal** [hankinsoft/SQLPro#568]
Studio macOS v2021.02 on macOS 11.1. Uploading a csv with >47k rows and 94 columns into PostgreSQL 12.3 (RDS) and creating a new table.

SQLPro seems to scan a subset of the rows and tries to guess int vs decimal vs character varying, and also tries to guess the length of the varchar and if the column allows nulls. For larger files, it seems to get this wrong most of the time. Because of this, I need to retry over and over by guessing which of the many "character varying(1)" fields might have caused the error and lengthen the field, allow null as it hit an issue for each one it didn't catch, change integer to bigint or decimal in some cases, etc. In addition, SQLPro does not drop the table on error, so I'm creating partially imported tables on each retry.

After 10 iterations of the above on this file, it encountered a value in a cell that contained a line break (no quotes in this file). Can't fault SQLPro for that, so I edit the file and fix the error. However, it appears that the edited csv is not loaded on the next retry. Instead, it seems to preserve a copy of the original file which it uses on each retry. Because of this, I need to close the csv import window after 11 tries and start over.

I know this is a "nice to have" feature and SQLPro will never be able to "magically" guess the table structure perfectly because csv is such a messy format. However, it's a very frustrating process each time. I have a few suggestions that I'm hoping are quicker paths than some grand field type parser.

1. If I right click the "Table" folder within a schema to select Import CSV, could the schema auto-populate when naming the new table being created, rather than defaulting to the public schema each time?
2. After picking that schema and table name once, could those be preserved on each retry if the import hits an error?
3. I imagine this doesn't apply for all use cases, but could there be on option to rollback/drop the table if any error is encountered?
4. If only a subset of rows are scanned to determine type/null, it would be nice to have an option to scan all. Would rather wait and only have to try once.
5. For PostgreSQL specifically, the "text" type is variable unlimited length and has no performance disadvantages compared to character varying(x). Would be nice if SQLPro just used the text type and didn't worry about length. [See the Tip on this page](https://www.postgresql.org/docs/12/datatype-character.html)
6. Could there be an option to toggle all/none for "Allow Null"? Obviously I could go through and check each one, but that can be tedious with higher column counts.
7. Could the file be pulled from its original path each time, so that external edits are included on subsequent retries?
8. It would also be nice to set all column names to lower case, since PostgreSQL is case sensitive.

Thanks for the fantastic app.

**Comment by hankinsoft** [comment]
Thank you for so many details! I'm going to focus on a few items here at a time:

> If I right click the "Table" folder within a schema to select Import CSV, could the schema auto-populate....

Great idea, I'll get that set.

> After picking that schema and table name once, could those be preserved on each retry if the import hits an error?

Just trying to understand the workflow -- this would be for if the import fails? The import dialog would stay open, it would just use the same table again? I think this would tie in with item 3 (drop/recreate the table).

> For PostgreSQL specifically, the "text" type is variable unlimited length and has no performance disadvantages compared to character varying(x). Would be nice if SQLPro just used the text type and didn't worry about length. See the Tip on this page

Thanks, I did not know that. (I'm not a huge Postgres user). I'll switch Postgres to default to 'TEXT' which will also improve the performance of item 4 (scanning rows) as I have a time based scan currently (scan rows until finished or until x seconds have passed). Not having to determine length will be a good boost.

> Could there be an option to toggle all/none for "Allow Null"? Obviously I could go through and check each one, but that can be tedious with higher column counts.

Great idea. For the first draft, I might hide it being a right click.

> Could the file be pulled from its original path each time, so that external edits are included on subsequent retries?

I'm not 100% sure what you mean by this. Could you explain this one a bit further in detail?

> It would also be nice to set all column names to lower case, since PostgreSQL is case sensitive.

Let me do a bit of investigation on the best way to add an option for this (I think I would like to have it set as an option).

**Comment by andyoneal** [comment]
> Just trying to understand the workflow -- this would be for if the import fails? The import dialog would stay open, it would just use the same table again? I think this would tie in with item 3 (drop/recreate the table).
Right, if the import fails, auto-populate the schema/table fields the same values again. Even if we don't drop the table each time, I could just append "_2" to the end of the table name as I have been for each retry.

> I'm not 100% sure what you mean by this. Could you explain this one a bit further in detail?
In an example workflow of Import CSV -> import fails -> edit CSV in text editor -> retry import (never closing the dialog), the edited file is not used in the retry. It seems that until I close the import dialog and start from scratch, the file on disk is not reloaded. I would like to reload the latest file without losing my progress on type/null selection. However, if starting from scratch becomes less painful with the other changes, maybe this is less important.

Thank you!

**Comment by hankinsoft** [comment]
Thanks for the additional details. I'm going to have a build available for testing later this week. Just to check, which version of SQLPro do you have installed? (SQLPro Studio, SQLPro for Postgres?) and is it from the App Store, or website?

**Comment by andyoneal** [comment]
Studio 2021.02 from the App Store.

**Comment by hankinsoft** [comment]
New build is available. Please give it a try and let me know if this is fixed up for you.

**Comment by andyoneal** [comment]
Using Version 2021.05 (Build 110767.5)

Not sure which of my comments you intended to implement already or ever, so I'll check each of them:

1. No change here. Default schema when creating a new table during import is still "public".
2. No change. On a subsequent retry of the same import after an error, the schema reverts to the default "public" and the table name is empty.
3. No change. When I use the same schema and table on a subsequent retry of the same import after an error, I get the error that the table already exists.
4. Can't tell if this has changed thanks to #5 being implemented. Certainly not as important now anyway.
5. **Done!** All fields are set to type=text.
6. **Done!** The right click menu is a great solution. So nice to have this.
7. No change. Edits to the csv file made after the Import CSV dialog is open are not reflected in what is actually imported into the db. Reloading the file requires closing the dialog and starting over.
8. No change, but I just threw this in as a bonus :)

Thanks! 5 and 6 are the biggest ones for me and the experience is already 10x better.

**Comment by hankinsoft** [comment]
Thanks for the feedback. Sorry I didn't clearly state what I had changed. I was expecting that build to fix item 1, 5, 6 and 8. I'll investigate a bit further.

**Comment by hankinsoft** [comment]
I'm going to mark this item as closed. I don't plan on implementing item 7 on the list `Could the file be pulled from its original path each time, so that external edits are included on subsequent retries?` as a workaround would be to re-open the file.

If you would like any of the other items re-listed, please add them as individual requests.
