### ISSUE TITLE
I paid for a 1 year subscription but software is not activated

### ISSUE THREAD

**Issue by BernieSumption** [hankinsoft/SQLPro#569]
This is really a support request not an issue but I can't find a support email, feel free to remove this issue and contact me on bernie at berniecode dot com.

I paid for a year and have an active subscription until Jan 2022, but am still seeing the "Activate SQLPro Premium to access results" notice when I try to run a query.

I did not receive any emails with a licence key when I initially paid.

**Comment by hankinsoft** [comment]
Hi,
Sorry about that. This is an issue which seems to occur for some Mac App Store users now and then. I’ve got an article and solution available here: https://github.com/hankinsoft/SQLPro/wiki/App-Store-Subscription-not-Renewing

**Comment by BernieSumption** [comment]
Great, that fixed it for me thanks!

B
