### ISSUE TITLE
Feature: duplication of rows

### ISSUE THREAD

**Issue by ghoffart** [hankinsoft/SQLPro#57]
It would be great to have a "duplicate this row of data" feature. "Sequel Pro" offers that, and I miss it really in SQLStudio Pro. It helps using existing rows as "templates" for new entries.

**Comment by hankinsoft** [comment]
Hi,
Would the copy as insert feature solve this? At the moment if you select a
single row (easiest way is to click on the row number header) then right
click on the data and choose 'copy as insert' you will get the inset into
for that table, allowing you to make any modifications and run it. I can
post a gif of this shortly, I only have phone access at the moment.

Please let me know if that does the trick.

**Comment by ghoffart** [comment]
Aaah! Yes, that works (for me). I did not find that, because I right-clicked on the row number header, and nothing happened there. I think it would be more consistent if that would be possible.

As this works perfect for my usage type, I can imagine situations with large row data sets, where this gets hard to handle, esp. when there are serveral larger varchar columns in it and the text in the textarea gets long.

**Comment by hankinsoft** [comment]
Here is the new insert and duplicate for the next release:

![CleanShot 2020-05-13 at 09 29 20](https://user-images.githubusercontent.com/3160528/81812491-94f56100-94fc-11ea-9234-69d4bf39ce67.gif)

You can also right click a row and choose edit to find the larger edit dialog which has more options such as import/export and view as hex.

**Comment by hankinsoft** [comment]
Going to close the issue. If anyone runs into issues or has feedback, please feel free to reopen and let me know.
