### ISSUE TITLE
Connection groups not working

### ISSUE THREAD

**Issue by costmeyer** [hankinsoft/SQLPro#570]
I have the mac store version 2021.04 (Build 110766.5) running on a mac running MacOS Catalina 10.15.7.

I noticed I can create connection groups.  But once created, I can't edit the name.  Right click the group name and all options are grayed out. (doesn't seem to matter if the group is empty or has entries in it).

I did find that if I go into the connection screen and then IMMEDIATELY click the edit (gear) icon next to the group, I can then edit the group name.  But after that, all groups are locked unless I close the screen and repeat.  But if I wait too long at the connection window, then I cannot edit the names.

![Screen Shot 2021-01-25 at 2 14 04 PM](https://user-images.githubusercontent.com/766486/105772950-d48f9c00-5f17-11eb-8fc6-fa8a8aea04e0.png)

**Comment by hankinsoft** [comment]
Thanks, I'm investigating this now.

**Comment by hankinsoft** [comment]
Fixed for the upcoming 2020.05 build.

**Comment by hankinsoft** [comment]
New build is available. Please give it a try and let me know if this is fixed up for you.

**Comment by costmeyer** [comment]
Wow, thanks for the quick turn-around!  it does seem to be better.  I can now edit, but only when right-clicking the gear icon.  I assume you should be able to left-click the gear and see the edit/delete menu?

**Comment by hankinsoft** [comment]
Hi, the gear icon should be bringing up the 'edit' dialog (rename). I discovered the label is actually over 3/4 of the edit button (if you click on the very right of the edit button you will see the expected behaviour). I've fixed that for the next build (2021.07). Thanks for proving me all the details BTW.

**Comment by hankinsoft** [comment]
FYI the latest available build should now sort this out.

**Comment by costmeyer** [comment]
Yep, works great!  Thanks!

**Comment by waltschmidtblet** [comment]
I'm am having the same issue, except I'm using SQLPro Studio through SetApp. I'm currently running Version 2020.101 (Build 110752).
