### ISSUE TITLE
PRAGMA foreign_keys; never changes

### ISSUE THREAD

**Issue by Sebastien-Remy** [hankinsoft/SQLPro#571]
I want to make test with foreign key. I follow this guide: [https://www.sqlite.org/foreignkeys.html](https://www.sqlite.org/foreignkeys.html) but it doesn't work as expected in SQLPro Version 2020.106 (Build 4217.5) on Mac OS 11.1

This sample code for example :

```
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys;
```

This is supposed to return 1 but it return 0

Any idea ?

**Comment by hankinsoft** [comment]
Sorry for the delay. I've invested this a bit and I think I know what's going on. `PRAGMA foreign_keys=ON;` must be set on each sqlite connection - previously SQLPro used to only use one connection which meant this worked. About a year or so ago that was changed and now each new connection is no longer getting `PRAGMA foreign_keys=ON;`. I'm investigating the best way to sort this.

**Comment by rtkunze** [comment]
Any news about this matter? I also tried to turn on foreign keys but experienced the same behavior like Sebastien-Remy. Also tried to turn on "Enforce foreign keys automatically" in Preferences... no change - and when I open up Preferences again it is unchecked. So it magically somehow turns itself off.
What can I do?

**Comment by mallman** [comment]
I'm seeing this exact behavior as well. @hankinsoft can you please update us on a fix?

**Comment by hankinsoft** [comment]
As of this build:
https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.32.app.zip

Using `PRAGMA foreign_keys=ON/OFF` should now work properly.
