### ISSUE TITLE
Wrong horizontal scroll behaviour

### ISSUE THREAD

**Issue by yeysman** [hankinsoft/SQLPro#572]
I found a very annoying issue with a horizontal scroll.
Please see the attached video.

https://user-images.githubusercontent.com/3490139/106586203-d4635200-6550-11eb-86f0-e5702c5664cf.mov

When you are scrolling over "big" functions/procedures (using a touchpad) the horizontal scroll jumps from left to right.
It happens because it allows scrolling to the left even if the scroll position at the start point.

SQLpro Version 2021.07 (Build 110769.5)

**Comment by hankinsoft** [comment]
I'm not quite understanding this one. The `bounce` is default macOS scroll behaviour?

**Comment by yeysman** [comment]
@hankinsoft yes.
I checked a few code editors and found they do not have this effect.
Is it possible to disable it?

**Comment by hankinsoft** [comment]
I've disabled scroll elasticity for the next build. 2021.14.
