### ISSUE TITLE
I can not connect to oracle server with ssh tunneling "Failed to connect. ORA-12537: TNS:connection closed"

### ISSUE THREAD

**Issue by msjuck** [hankinsoft/SQLPro#573]
![image](https://user-images.githubusercontent.com/3645165/106597431-bff77780-6599-11eb-8afb-0fb5e09abb51.png)

Version 2021.07 (Build 110769.5)

I can not connect to oracle server with ssh tunneling "Failed to connect. ORA-12537: TNS:connection closed"

![image](https://user-images.githubusercontent.com/3645165/106597837-5166e980-659a-11eb-8b9d-5f4900d2abe1.png)

**Comment by hankinsoft** [comment]
Hi,
Sorry for the delay. Would it be possible for me to receive a copy of the log file for this?

**Comment by hankinsoft** [comment]
Hi - just wanted to check in again and see if this was still an on-going issue?
