### ISSUE TITLE
Postgres: unable to set search_path

### ISSUE THREAD

**Issue by costmeyer** [hankinsoft/SQLPro#574]
This is specific to postgres...

The DBs I use have several tables under various schemas.  Because I often need to run several queries within a schema, I will often set the search path.  This way, I can run queries without having to prefix my table names with the schema name.
```sql
set search_path to global;
select * from my_table;  
-- If I had not set my search path, then I'd have to to type "global.my_table" instead
```

Unfortunately,. when I run this in SQLPro, I get an error:
`relation "my_table" does not exist`

I can work around this by running the "set search_path" line by itself.  This seems to then set that search path for the remainder of the session.  It seems like I should be able to run both statements together.

**Comment by hankinsoft** [comment]
If you run:

```
show search_path;
set search_path to global;
show search_path;
```

What do the two `show search_path`s return?

**Comment by costmeyer** [comment]
ok, so this is odd... I have my default set to "run all".  I noticed there's also a "run all queries".  if use the "run all queries" option, then it does what I expect.  From what I can tell "run all" and "run current query" are doing the exact same thing.  So either this is a bug or I just don't understand the subtleties of the 2 options.  Can you elaborate?

**Comment by hankinsoft** [comment]
Hi. You can find a detailed explanation at https://www.sqlprostudio.com/blog/12-execute-query-in-cursor-range

**Comment by costmeyer** [comment]
Yes, I saw that.  Unfortunately, it only mentions the options "Run current" and "Run all", but not "Run current query".  I have mine set to "enabled but not default".  This caused my default to be "Run all".  But like I said, this option is behaving exactly like "Run selected".  I have to actually select the option "Run current query"

![options_settings](https://user-images.githubusercontent.com/766486/106624940-08c41780-652b-11eb-908f-8587f86d0c9a.png)
![run_options](https://user-images.githubusercontent.com/766486/106624954-0cf03500-652b-11eb-9ada-932844484e4d.png)

**Comment by hankinsoft** [comment]
Hi, yes this looks like a bug. Investigating it now.

**Comment by hankinsoft** [comment]
Just to note this is all sorted in the latest available build. If you get the chance, could you confirm everything works as you would expect?

**Comment by costmeyer** [comment]
Yes, this works now too.  thanks!
