### ISSUE TITLE
Please remove my app name from your app store keywords

### ISSUE THREAD

**Issue by jakob** [hankinsoft/SQLPro#575]
I'd appreciate it if you could remove the name of my app from your app store keywords.

I appreciate friendly competition in the database client space, but I just don't think it's very nice to spam people who are searching explicitly for my app.

**Comment by hankinsoft** [comment]
Hi @jakob - done. Hope things are going well for you since we last chatted.

**Comment by jakob** [comment]
Thank you!

Things are going fine. I'm still slowly hacking away on my single app. I hired one developer to help. I don't know how you do it -- I just saw that you not only have an iOS app, but a Windows version as well! Very impressive.

**Comment by hankinsoft** [comment]
> Things are going fine. I'm still slowly hacking away on my single app.

Glad to hear!

> I hired one developer to help.

Thats awesome! I've contemplated hiring someone before, but I just can't bring myself to be responsible for someone else's livelihood. The thought of some day needing to let someone go if something unforeseen happens turns my stomach.

> I just saw that you not only have an iOS app, but a Windows version as well! Very impressive.

Thanks! I don't get to spend as much time as I would like on the Windows and iOS versions, but the majority of users seem to be happy with them.
