### ISSUE TITLE
Duplicate connection functionality creates 2 copies

### ISSUE THREAD

**Issue by costmeyer** [hankinsoft/SQLPro#576]
I have several connection groups.  When I right-click an item in one of the groups and duplicate, the UI make two copies.  One in the default group and one in the same group of the original as shown.  If I remove (delete) either one of the copies, then **BOTH** copies are deleted.

![Screen Shot 2021-02-02 at 9 45 29 AM](https://user-images.githubusercontent.com/766486/106641222-d1119b80-653b-11eb-81f1-6bdd50b29baf.png)
![Screen Shot 2021-02-02 at 9 47 29 AM](https://user-images.githubusercontent.com/766486/106641216-cf47d800-653b-11eb-9b69-36f9ebf13174.png)

**Comment by hankinsoft** [comment]
Thank you. Fixed for the next build (2021.09).

**Comment by costmeyer** [comment]
I have just installed the new build and have confirmed this is no longer an issue.  I'm going to mark this as closed.  (Great job guys!)

**Comment by hankinsoft** [comment]
Great, thanks for letting me know. FYI, SQLPro is independently developed - if you are enjoying the app, please consider leaving it a rating (or even better a review) on the App Store as they help me out a ton!
