### ISSUE TITLE
Locked out - despite annual subscription

### ISSUE THREAD

**Issue by BurtieBonus** [hankinsoft/SQLPro#577]
I can't use the application, despite paying 12 months in advance because a pop up appears asking me to activate or enter license key - which Apple have not given me
If I click to activate - it directs to App store which says I already have paid, so I open the app from there and a pop up appears asking me to activate or enter a license key......................
Ive tried entering every code from my invoice / receipt but nothing seems to work as license key
Please help

**Comment by hankinsoft** [comment]
Hi. Sorry about this issue. I have a support article available here: https://www.sqlprostudio.com/blog/13-app-store-subscription-not-activating which will help sort things out.

**Comment by hankinsoft** [comment]
Just wanted to check and see if that helped out?

**Comment by BurtieBonus** [comment]
Magically, the issue seems to have disappeared.
Thanks
David

**Comment by hankinsoft** [comment]
Thanks for letting me know and sorry for the issue.
