### ISSUE TITLE
Opening a .sql file tries to open it as a connection

### ISSUE THREAD

**Issue by caseyjerk** [hankinsoft/SQLPro#578]
This just happened after a recent Mac update, not sure if it's related. When I try to open a saved .sql file, it will try to open it as what appears to be a connection / database instead of just a file. I've tried opening it from within SqlPro, as well as from my file browser and it will always return the below - the name of the table and the path listed in the left pane, and no query in the query editor.

<img width="203" alt="sql_pro_issue" src="https://user-images.githubusercontent.com/62668889/106807968-c805f480-6637-11eb-9952-5541d0a79d1a.png">

**Comment by hankinsoft** [comment]
Very sorry about that. There is a version in review by apple now which
should sort that out. It hopefully should be available within a couple of
hours.

**Comment by gordroid** [comment]
This is fixed on Version 2021.09 (Build 110771.5)
