### ISSUE TITLE
Set time_zone on MySQL Connection

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#579]
Is it possible to get the feature added to configure setting of the session time zone on MySQL on the connection itself ?

Currently I have to manually run below before queries
SET SESSION time_zone = 'Australia/Melbourne';

**Comment by hankinsoft** [comment]
Sure, I have something similar for Postgres, so I can get this added to an upcoming version.

**Comment by hankinsoft** [comment]
Sorry for the delay on this. I've got it coming for the next build (early next week), along with some MySQL timeout settings. I'll post another note once its available.

<img width="1382" alt="Screen Shot 2021-06-02 at 9 34 25 AM" src="https://user-images.githubusercontent.com/3160528/120480884-e978b200-c385-11eb-8bca-00a9876ab0fa.png">

**Comment by poorlymac** [comment]
Hi Kyle, that looks perfect !

On the timeouts (also perfect) make sure you double check the syntax as I think MySQL and MariaDB are different. Plus the syntax may have changed by version

**Comment by hankinsoft** [comment]
Yep, for MySQL I run the query:

> SET time_zone = '-03:00'

(Basically the timezone offset).

Build has been submitted and should be available in ~24 hours.

**Comment by hankinsoft** [comment]
The build should now be available. Sorry for the delay.

**Comment by poorlymac** [comment]
No issue, confirmed working ! Thankyou very very much Kyle
