### ISSUE TITLE
FEATURE: Change Schema on Object Tree

### ISSUE THREAD

**Issue by gxsanchez** [hankinsoft/SQLPro#58]
On many of the Oracle databases I use, I have to connect with a view only user. Normally this user does not have objects created. Rather the user has grants to select objects from another schema. In other tools, I am able to switch Schemas so I can see objects that I have select rights. Add an option to **SQLPro Studio** Oracle connections to allow switching to different schemas on the object list on the left.

**Comment by tylerwince** [comment]
This would be a great feature to have @hankinsoft!

@gxsanchez, not sure if you have found a workaround, but you can get all the table names using: 

`SELECT * FROM all_tables WHERE owner NOT IN ( 'SYS', 'SYSTEM' )`

This is a slight workaround for now, but it would be great if there was an option to change which schema appeared in the tree immediately after login or if it was a right-click option alongside 'New Query' and 'Disconnect'.

**Comment by U47** [comment]
I'll pipe in a bit.

Oracle's a bit of a pig in that there isn't any concept of *schema visibility* (ie: every user can see all schemas, even those they have no grants to). This makes things a PITA when dealing with databases that have many schemas (users). Ideally, a method to filter the list of schemas would be really beneficial. At the very least, IMHO, selecting Schema/Owner should be the root of the tree, defaulting to Current User.

Also when deciding how to show visible objects in the tree by Schema/Owner, don't forget Views, Procedures, etc. etc.

([This reference](https://razorsql.com/articles/oracle_system_queries.html) helps me along.)

**Comment by U47** [comment]
I really think SQL Developer does this well with their two drop-downs in their Schema Browser. First drop-down is the user (schema), the second the object type. Could be implemented as the first two branches of the tree, as well.

![image](https://cloud.githubusercontent.com/assets/573316/22610422/96458ad6-ea22-11e6-8b85-57bbfaca1b1d.png)

**Comment by hankinsoft** [comment]
I changed the background queries for how oracle databases tree list entries. They should now be listing schemas outside the users own (as long as the user has access). I'm not sure if it will show exactly what you are looking for, but any feedback is welcome.
