### ISSUE TITLE
[Feature request] Open a query panel after connected to a database

### ISSUE THREAD

**Issue by elgs** [hankinsoft/SQLPro#580]
When I have quite a few databases open on the left panel, I will need to click to select that db and click the New Query button to open a query window. Most of time, if not all, when I connect to a new db, the first thing I want to do is to open a query against that db. So I think it may make sense to open a query window for any newly connected db. Thanks.

**Comment by hankinsoft** [comment]
FYI I've been debating this back and fourth with myself. I'm not sure its something the vast majority of users would want. At the moment I'm going to leave it as is, but if I receive requests from additional users for this I will consider adding an option for it.
