### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by bocaj** [hankinsoft/SQLPro#581]
Hi

First, thanks for the great app! It is a delight to use. Unfortunately, I have run into an issue today that is very frustrating. SQLPro Studio became unresponsive and so I force quit the app. Any subsequent attempt to launch ends in a crash. What I can see before it crashes is the windows that were previously open and so my guess is that it is attempting to restore state. I have attempted the following things to try and resolve the issue 

* Restarting
* Deleting the App app and re-downloading from App Store 
* Deleting the SQLPro directory from ~/Library/Saved Application State

I think if I could get the app back to its initial state, it would be fine but I cannot see a way to do this. Any help is appreciated. 

Mac: MacBook Air (M1, 2020)
macOS: 11.1 (20C69)
SQLPro Version: 2021.10

Thanks!

**Comment by ThomasBojer** [comment]
the same issue here, sql pro stopped working today.
Crashes on Launch.
mac OsS: 10.15.7
SQLPro Version: 2021.10

**Comment by hankinsoft** [comment]
FYI I'm currently investigating this. Would either of you happen to have a crash report available by any chance?

**Comment by bocaj** [comment]
Hi. Thanks for the quick response. Attached is a crash report
[sqlpro-crash-report.txt](https://github.com/hankinsoft/SQLPro/files/5953533/sqlpro-crash-report.txt)

Also, I was able to get 2021.05 from a TimeMachine backup and it launched just fine.

**Comment by hankinsoft** [comment]
This should be sorted in the latest build. If anyone still seeing the issue gets the chance, please give it a try.

**Comment by bocaj** [comment]
Got 2021.12. Looks good. Thanks for the quick turn around!
