### ISSUE TITLE
[Feature Request] Set the default view as setting

### ISSUE THREAD

**Issue by chrschmitz** [hankinsoft/SQLPro#582]
SQLPro for SQLite Version 2020.92 (Build 4212)

SQLPro for SQLite currently always starts up with the Schema view. It would be great if the program would either remember the last opened view or add a preference option, where the user can set the default view to one of the 4 options.

**Comment by hankinsoft** [comment]
I don't mind this idea, but I'm going to close this issue for now. If I receive additional requests for this, I will push it forward and take a further look into getting it added.
