### ISSUE TITLE
[Feature Request] Copy with header

### ISSUE THREAD

**Issue by chrschmitz** [hankinsoft/SQLPro#583]
SQLPro for SQLite Version 2020.92 (Build 4212)

It would be great having a second copy option (e.g. Edit > Copy with Header) with another shortcut to copy data including the header into the clipboard (similar to CSV export).

**Comment by hankinsoft** [comment]
Sure, for the next build (2021.14) CMD + Shift + C will copy as CSV with headers

**Comment by hankinsoft** [comment]
Just wanted to check if you have had a chance to give this a try via the latest verison?

**Comment by chrschmitz** [comment]
Yes, it works with charm! Many thanks!

The thumb up and the smiling face were set by me ;-)

**Comment by hankinsoft** [comment]
Great! Please let me know if I can help with anything else.

**Comment by chrschmitz** [comment]
Many thanks! Yes, there is still one feature request uncommented. And if I can add another: it would be great if changes made outside of SQLPro for SQLite could be pasted back. I currently use SQLPro for SQLite to copy rows into a spreadsheet and another tool to copy the changes back.
