### ISSUE TITLE
MySQL 8.0 ALTER TABLE issue

### ISSUE THREAD

**Issue by yeysman** [hankinsoft/SQLPro#585]
Hi,
There is an issue with rename columns using ALTER TABLE
Please see the attached screenshot.
<img width="682" alt="image" src="https://user-images.githubusercontent.com/3490139/107848863-9c38fa80-6dff-11eb-8b60-a511afeeee52.png">

SQLpro Version 2021.12 (Build 110774.5)

**Comment by hankinsoft** [comment]
Hmmm, if you manually run the query as:

> ALTER TABLE <yourdatabasename>.coursedb RENAME COLUMN user_email TO useremail;

Does that sort the issue out?

**Comment by hankinsoft** [comment]
Closing due to no response.
