### ISSUE TITLE
json null values are being represented by blank string ""

### ISSUE THREAD

**Issue by jacksonsox** [hankinsoft/SQLPro#586]
The json output isn't representing null values correctly.  nulls of all types seem to be represented by blank string.  I'm pretty sure that json null is supposed to be represented by the word null, not blank string "".  Blank string makes translation very intensive to process programatically.
"Walmart_SKU" : 46173529, <- Int
"Walmart_SKU" : "", <- not an int null.

**Comment by hankinsoft** [comment]
Thanks for this. I'll take a look into fixing it for the next build.

**Comment by hankinsoft** [comment]
Actually I'm not able to reproduce this. 

If I right click on a table and choose 'Export JSON' such as:
<img width="1085" alt="CleanShot 2021-02-17 at 09 14 53@2x" src="https://user-images.githubusercontent.com/3160528/108209396-a0675f80-7100-11eb-8155-e68ce419a0e8.png">

Then the output contains null.

```
[
  {
    "ContractStareId" : 1,
    "NewColumn0" : null
  }
]
```

Same if I run a query and export from the result set.

<img width="797" alt="CleanShot 2021-02-17 at 09 16 36@2x" src="https://user-images.githubusercontent.com/3160528/108209591-ddcbed00-7100-11eb-8430-d30d164d4330.png">

The resulting JSON file still contains `    "NewColumn0" : null`

**Comment by jacksonsox** [comment]
I've attached some images.  I'm exporting from a view.  This issue may be related to the other issue that I opened in that string data can be imported into integer fields.  I'm importing into the table using tab delimited excel.  Maybe the data is being imported as a a blank string "" rather than null?  And therefore being exported as "" rather than null.  When there is an actual integer in the field, the value in the json is exported as an integer.
<img width="295" alt="Screen Shot 2021-02-17 at 12 48 08 PM" src="https://user-images.githubusercontent.com/32544470/108245554-6b6a0580-711e-11eb-915a-0cc9be6d94ea.png">

<img width="569" alt="Screen Shot 2021-02-17 at 12 40 40 PM" src="https://user-images.githubusercontent.com/32544470/108245275-15955d80-711e-11eb-8065-25cff62f6543.png">
<img width="331" alt="Screen Shot 2021-02-17 at 12 41 57 PM" src="https://user-images.githubusercontent.com/32544470/108245281-175f2100-711e-11eb-8a5f-b1ec38310e11.png">
<img width="433" alt="Screen Shot 2021-02-17 at 12 42 25 PM" src="https://user-images.githubusercontent.com/32544470/108245283-175f2100-711e-11eb-863c-78511ed2ab7c.png">

**Comment by hankinsoft** [comment]
> Maybe the data is being imported as a a blank string "" rather than null?

Yes, that is expected behaviour. To import a NULL from a CSV, the cell should contain either NULL or <NULL>. Blank strings are handled only as blank strings.

I've submitted a new version of SQLPro for SQLite to the App Store which uses updated CSV import functionality. I think this build will sort both of the import issues you are seeing. 2021.14 should be available within ~24 hours.

**Comment by jacksonsox** [comment]
Thank you!

Jason Gloor
Sent from my iPhone

On Feb 18, 2021, at 11:14 AM, Kyle Hankinson <notifications@github.com> wrote:

﻿

Maybe the data is being imported as a a blank string "" rather than null?

Yes, that is expected behaviour. To import a NULL from a CSV, the cell should contain either NULL or . Blank strings are handled only as blank strings.

I've submitted a new version of SQLPro for SQLite to the App Store which uses updated CSV import functionality. I think this build will sort both of the import issues you are seeing. 2021.14 should be available within ~24 hours.

**Comment by jacksonsox** [comment]
The update doesn't seem to have fixed either to the 2 issues.
1) allowing import of non numeric into Integer or real fields
2) exporting null rather than "" for json integer or real null values that have no value in the database.

Steps
1) I exported all my data as CSV from the -> export function
2) I deleted all my data in the database
3) I imported all my data from the step 1 export
4) I exported the data as JSON and still get "" values in integer and real fields.

The import is still allowing import of text into Real fields

**Comment by jacksonsox** [comment]
When the data in the database is correctly represented as null, the JSON export appears to work correctly.

Although, now NULL is appearing in Tab deliminited files.  NULL in tab deliminated files should be nothing.  Just \t followed by \t.  Otherwise there is no way to distinguish between true null and the text literal "NULL"

**Comment by hankinsoft** [comment]
Hi,
NULLS in csv/tsv is by design. Similar to
> Otherwise there is no way to distinguish between true null and the text literal "NULL"

The inverse of having null as an empty string means there is no way to distinguish between empty string and null.

That said, I am adding a 'treat null as empty string' checkbox to the export dialog for next build. It will be off by default to preserver the existing functionality for users.

**Comment by hankinsoft** [comment]
The latest version available now has the 'treat null as empty string' option for import/export. Please give it a try if you get the chance.
