### ISSUE TITLE
SQLPro - Store Procedures are not exported properly

### ISSUE THREAD

**Issue by rliessum** [hankinsoft/SQLPro#588]
I run into issues that stored procedures are not exported properly.
![screenshot](https://user-images.githubusercontent.com/8915237/108234721-5d7bab00-7145-11eb-8f38-89ce226e1eb1.png)

Client: SQLPro for MSSQL.
Server: Microsoft SQL Server 2012 (SP4-GDR) 11.0.7507.2 (X64)

Generated SQL:
```
IF EXISTS ( SELECT * FROM sysobjects WHERE  id = object_id(N'DDI.usp_tblRequestDDI_Domain_Del') AND OBJECTPROPERTY(id, N'IsProcedure') = 1 )
	DROP PROCEDURE DDI.usp_tblRequestDDI_Domain_Del
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
<null>
GO
```

**Comment by hankinsoft** [comment]
What happens if you run the following query:

`SELECT OBJECT_ID('ddl.usp_tblRequestDDL_Domain_Del'), OBJECT_DEFINITION(OBJECT_ID('ddl.usp_tblRequestDDL_Domain_Del'))`

Does that give you a result or nulls?

**Comment by rliessum** [comment]
> SELECT OBJECT_ID('DDI.usp_tblRequestDDI_Domain_Del'), OBJECT_DEFINITION(OBJECT_ID('DDI.usp_tblRequestDDI_Domain_Del'))

Yes it does.

**Comment by hankinsoft** [comment]
Ok - and if you run:

> SELECT s.type FROM sys.objects s WHERE s.object_id = OBJECT_ID('DDI.usp_tblRequestDDI_Domain_Del')

What is the s.type column value?

**Comment by rliessum** [comment]
> > SELECT s.type FROM sys.objects s WHERE s.object_id = OBJECT_ID('DDI.usp_tblRequestDDI_Domain_Del')

Type is "P".

**Comment by hankinsoft** [comment]
Hmmm, ok.. Based on the results of those two queries I'm not positive on why the data is coming back as null... I'm going to add more logging and post a build for you to try if you get the chance.

**Comment by hankinsoft** [comment]
Could you grab this build and try right clicking on the stored procedure and doing 'Script as' -> 'Create'? Then send the log file? You can find it by going to 'View' -> 'Logs'.

https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.2021.13.app.zip

Specifically I'm looking for the log lines of:
> DEBUG-creationQueryForStoredProcedure:

It should list the procedure schema/name along with the script it runs. I would like to see the entirety of that please.

**Comment by rliessum** [comment]
Here you go:
```
2021/02/18 06:27:00:596  DEBUG-creationQueryForStoredProcedure: DDI.usp_RequestDDI_Get. Loading query is:
SELECT
          'SET QUOTED_IDENTIFIER ' + CASE WHEN OBJECTPROPERTY(s.object_id,'ExecIsQuotedIdentOn') = 1 THEN 'ON' ELSE 'OFF' END AS QuotedIdentifier,
          'SET ANSI_NULLS ' + CASE WHEN OBJECTPROPERTY(s.object_id, 'ExecIsAnsiNullsOn') = 1 THEN 'ON' ELSE 'OFF' END AS ANSINulls,
          (SELECT OBJECT_DEFINITION(OBJECT_ID('DDI.usp_RequestDDI_Get')))
        FROM
          sys.objects s
        WHERE
          s.type IN ('P','TR','V','IF','FN','TF')
        AND
          s.object_id = OBJECT_ID('DDI.usp_RequestDDI_Get')
          
```

**Comment by rliessum** [comment]
I did some digging. It's most likely related to the lack of permissions on exporting stored procedures.

**Comment by hankinsoft** [comment]
Hmmm, so if you manually run this query in SQLPro:

```
SELECT
          'SET QUOTED_IDENTIFIER ' + CASE WHEN OBJECTPROPERTY(s.object_id,'ExecIsQuotedIdentOn') = 1 THEN 'ON' ELSE 'OFF' END AS QuotedIdentifier,
          'SET ANSI_NULLS ' + CASE WHEN OBJECTPROPERTY(s.object_id, 'ExecIsAnsiNullsOn') = 1 THEN 'ON' ELSE 'OFF' END AS ANSINulls,
          (SELECT OBJECT_DEFINITION(OBJECT_ID('DDI.usp_RequestDDI_Get')))
        FROM
          sys.objects s
        WHERE
          s.type IN ('P','TR','V','IF','FN','TF')
        AND
          s.object_id = OBJECT_ID('DDI.usp_RequestDDI_Get')
```

Does column three contain the creation script for the procedure? Or an empty string?

**Comment by rliessum** [comment]
![image](https://user-images.githubusercontent.com/8915237/108358218-bf441f80-71ee-11eb-90b5-19dcbfd1db26.png)
Empty string. The permissions are set that I can use stored procedures but can't take them out. So technically, it makes sense, but it had put me on the wrong foot.

**Comment by hankinsoft** [comment]
Ok! Thanks for letting me know.
