### ISSUE TITLE
Upsert no longer the default behavior with CSV import in newest version - 2021.14 (Build 4219.5)

### ISSUE THREAD

**Issue by jacksonsox** [hankinsoft/SQLPro#590]
Hi, thank you for the new build.  Prior to the most recent version 2021.14 (Build 4219.5), upserts was the default CSV load behavior. Specifically, the CSV upload would conduct an upsert on load such that an insert occurred if the primary key was new or an update occurred if the record primary key existed.  Now when I upload the data, I get an error for Unique key constraint.

I was a bit surprised that upsert was the prior default.  Is the new bahavior what is wanted/needed?  If so, is there a way to allow for user preference to (1) reject on duplicate key or (2) upsert on duplicate key?

I would recommend the default be (1) reject/error on duplicate key and require the user to specifically select (2) upsert.
<img width="262" alt="Screen Shot 2021-02-19 at 10 37 16 AM" src="https://user-images.githubusercontent.com/32544470/108525786-79469480-729e-11eb-99fa-807b6f710bc3.png">

**Comment by hankinsoft** [comment]
Ohhh sorry about that. I recently switched SQLPro for SQLite's import to match that of SQLPro Studio as SQLPro Studio has quite a few more options and during that I would have caused this issue. I'll get it fixed for the next build (I might even add a toggle to switch between `INSERT` or `INSERT OR REPLACE`. Thanks for the notification and sorry for the issue.

**Comment by hankinsoft** [comment]
Just submitted 2021.16 which now has an INSERT or INSERT OR REPLACE option (see bottom left of this screenshot). Should be available within ~24 hours.

<img width="1192" alt="Screen Shot 2021-02-23 at 10 55 32 AM" src="https://user-images.githubusercontent.com/3160528/108861716-e66f6800-75c5-11eb-968d-85a3d94d95b7.png">

**Comment by jacksonsox** [comment]
Thank you!  This issue is fixed with the INSERT/INSERT or REPLACE feature.
