### ISSUE TITLE
[Bur report] SQLPro Studio does not show tables in SQLite database

### ISSUE THREAD

**Issue by chrschmitz** [hankinsoft/SQLPro#591]
SQLPro Studio Version 2021.12 (Build 110774)

SQLPro Studio does not show tables in SQLite database. I attach two screenshots (SQLPro for SQLite and SQLPro Studio) and a test database.

![SQLPro for SQLite](https://user-images.githubusercontent.com/13820940/108530572-048f4c80-72d6-11eb-8101-1a9e7f40522d.jpg)

![SQLPro Studio](https://user-images.githubusercontent.com/13820940/108530601-0c4ef100-72d6-11eb-9b1f-9d78753d24ec.jpg)

[test.zip](https://github.com/hankinsoft/SQLPro/files/6011322/test.zip)

**Comment by hankinsoft** [comment]
Are you using Setapp? I've got a build submitted which will fix this.

**Comment by chrschmitz** [comment]
Yes, I use the Setapp version.

**Comment by hankinsoft** [comment]
Great - the fix should be available within ~24 hours. Sorry for the delay!

**Comment by chrschmitz** [comment]
Many thanks! I can confirm that it works now correctly.

**Comment by hankinsoft** [comment]
Great, thanks for letting me know!
