### ISSUE TITLE
Exporting and then re-importing fails (see image for error)

### ISSUE THREAD

**Issue by jacksonsox** [hankinsoft/SQLPro#593]
I've downloaded the most recent version of the app (Version 2021.16 (Build 4221.5)) SQLPro for SQLite.

I'm trying to validate that the most recent updates allow me to import and export with NULLs in the json for integer/reals where my starting import file is a tab delimited export from Excel.

I tried to export my data "tab" delimited and re-import into a new table to see if the values on import would import correctly as null into the Integer and Real fields.

My plan to resolve the prior issue with text allowed in integer and real fields was to export the original "bad" data table and import into a new identical table that prevented "bad" data.

Steps:

1. Select the table I want - remember this table has text in integer and real fields.  This is the bug from prior releases that I am trying to correct.
2. Right click and export csv selecting tab delimited
3. Create the exact table structure as exists in the table from step (1) (just named with a 2 at the end)
4. Right click the table created in step (3) and select import csv selecting tab (and either choose the format or ascii).
5. Upon import, I get the error attached.

I guess I could sort though the output of over 3k rows the import is trying to deal with to find the comma "," issue, but it seems that export and then an import should work seamlessly.

<img width="903" alt="Screen Shot 2021-02-23 at 10 05 05 PM" src="https://user-images.githubusercontent.com/32544470/108941853-cec6cc80-7623-11eb-9468-55ed56984c5d.png">

**Comment by hankinsoft** [comment]
I believe I have this solved for the next build 2021.17 which I have submitted to the store.

**Comment by hankinsoft** [comment]
The latest build is available. If you get the chance, please let me know if you are still seeing this issue.

**Comment by jacksonsox** [comment]
Thanks for the new build Version 2021.18 (Build 4223.5).  When I do an export and an import and then import into an identical, empty table, I get a new error.  Nothing is loaded.

What is surprising is that if I chang from the "INSERT" to "INSERT OR REPLACE", the load works except 8 records don't load.  I need to dig into why these 8 records don't load, they don't appear to have the key violation indicated by the INSERT error, they key is unique.  They don't seem to have invalid data, i.e, Text in Int fields.

The exported data loads fine into Google Numbers.

The records that don't load are the last 8 records in the input file of 3850 records.
 
<img width="276" alt="Screen Shot 2021-02-26 at 12 51 16 PM" src="https://user-images.githubusercontent.com/32544470/109343818-e7a9ca80-783b-11eb-969e-10a5aec005c1.png">

**Comment by hankinsoft** [comment]
Would it be possible for you to provide me with the sqlite file? You could email it directly via kyle @ hankinsoft.com if you would rather not post it here.

**Comment by jacksonsox** [comment]
Strange, I had it fail all week.  Although, I imported some smaller files using the insert or replace.
Now the INSERT to a blank table works fine.

I'll let you know if it comes back.  I appreciate all the help and quick responses.

**Comment by hankinsoft** [comment]
Thanks for letting me know. I'll close the issue for now and if you see it again, please let me know.
