### ISSUE TITLE
Multiple UPDATES in grid produces Invalid SQL for SQLite

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#594]
For SQLite only, if I change values in multiple rows using the grid, and then `Preview and Apply`, the generated SQL omits the semicolon between subsequent `UPDATE` statements. As a result the update won’t run because the SQL is invalid.

If I apply _without_ previewing, the update works correctly.

All other SQLs generate the semicolon.

Ironically, the semicolons are inserted if I do the same thing with Microsoft SQL, which is the only SQL which doesn’t (yet) require semicolons.

**Comment by hankinsoft** [comment]
Thanks, fixed for the next build.

**Comment by hankinsoft** [comment]
This build is available. If you get the chance, please give it a try and let me know if all is sorted up.

**Comment by manngo** [comment]
Working perfectly. Thanks.
