### ISSUE TITLE
Feature Request: data updates in the grid get stored in history

### ISSUE THREAD

**Issue by szidikm** [hankinsoft/SQLPro#595]
Love the newer edit data features with apply / preview and apply.  Can those SQL statements be stored in the history?  That would be a big help.  Thanks!

**Comment by hankinsoft** [comment]
Thats a good idea.. It makes me think maybe any queries run through the 'apply/preview' dialog should go into history rather than just the edit. Do you have any thoughts on that?

**Comment by szidikm** [comment]
Yes, I agree, that way there is a log of all queries from the client.


Mark Szidik
Midwest Collaborative for Library Services (MCLS)
1407 Rensen, Lansing, MI 48910-3657
800-530-9019 ext 117
szidikm@mcls.org<mailto:szidikm@mcls.org>

**Comment by hankinsoft** [comment]
This is now available for the latest build of SQLPro Studio via the App Store. I'll be pushing it out to the other products shortly. Just to check, which app are you using?

**Comment by szidikm** [comment]
Mac App Store version.

Mark Szidik
Sent from my phone

On Mar 1, 2021, at 08:57, Kyle Hankinson <notifications@github.com> wrote:

﻿

This is now available for the latest build of SQLPro Studio via the App Store. I'll be pushing it out to the other products shortly. Just to check, which app are you using?

**Comment by hankinsoft** [comment]
The latest build should include this. If you get the chance, could you confirm if this works as expected?

**Comment by szidikm** [comment]
It works when I edit data then hit “preview and apply” button.  It does not update history when I choose the “apply” button.



Mark Szidik
Midwest Collaborative for Library Services (MCLS)
1407 Rensen, Lansing, MI 48910-3657
800-530-9019 ext 117
***@***.******@***.***>



From: Kyle Hankinson ***@***.***>
Reply-To: hankinsoft/SQLPro ***@***.***>
Date: Monday, March 22, 2021 at 1:27 PM
To: hankinsoft/SQLPro ***@***.***>
Cc: Mark Szidik ***@***.***>, Author ***@***.***>
Subject: Re: [hankinsoft/SQLPro] Feature Request: data updates in the grid get stored in history (#595)


The latest build should include this. If you get the chance, could you confirm if this works as expected?

**Comment by hankinsoft** [comment]
Ahhh, good catch. I'll get that fixed for the next build.

**Comment by hankinsoft** [comment]
As of the latest version this should be all fixed up. Please let me know if everything now works as expected.
