### ISSUE TITLE
Trying to open Preferences freezes/crashes app

### ISSUE THREAD

**Issue by UliZappe** [hankinsoft/SQLPro#596]
If I try to open the _Preferences_ window in **SQLPro for SQLite**, Version 2020.104 (Build 4215), the app hangs and finally (after a few minutes) crashes.

This is on macOS 10.14.6 (18G8022).

Analyzing the process shows a myriad of font related things going on. Does the app try to load all fonts of the system? (I have installed 24,000 …)

This was no problem at all with the last (2017) version I used.

**Comment by hankinsoft** [comment]
Thanks, I've reproduced this and am working on a fix.

**Comment by hankinsoft** [comment]
Hi,
This should be fixed up in the latest build. Please give it a try and let me know if you are still seeing the issue.

**Comment by UliZappe** [comment]
> This should be fixed up in the latest build. Please give it a try and let me know if you are still seeing the issue.

Where can I download the latest build? https://www.sqlitepro.com/ <https://www.sqlitepro.com/> still has the old version.

**Comment by hankinsoft** [comment]
Can you grab https://www.sqlitepro.com/download.php? That has been updated and should sort it out.

**Comment by UliZappe** [comment]
> Can you grab https://www.sqlitepro.com/download.php? That has been updated and should sort it out.

Yep, it’s fixed. 😊 Thank you!
