### ISSUE TITLE
SQLPro for Sqlite crash importing CSV

### ISSUE THREAD

**Issue by dave-redfern** [hankinsoft/SQLPro#597]
The recent updates appear to have broken CSV file import. Every time I try, regardless of file size, the app always crashes when trying to actually import. This was working a few weeks ago.

Steps:
* Create new Sqlite db file
* Create table without types, with columns from CSV
* Data -> Import -> CSV
* standard options, select file
* after processing, map columns
* import
* crashes

OS: macOS 11.2.3
Version: 2021.20 (Build 4226.5)

**Comment by outcoldman** [comment]
For me it is not crashing, but creating some weird SQL, that SQL Pro failed to import. The funny thing, that I exported data with the SQLPro itself from other table.... 

Do they just concatenate strings?

**Comment by hankinsoft** [comment]
Could either of you post the csv you are attempting to import? That should help me sort things out.

**Comment by dave-redfern** [comment]
@hankinsoft Sorry for the delay; I've only just found some time to work on a basic use case. Turns out that the following will crash with just a single row:

SQL:
```
create table test (id,name,uuid,created_at);
```

CSV:
```
id,name,uuid,created_at
123456,"foo bar","ee184d3b-8a6b-405a-9c29-8aa1156b0a3a","2021-03-18 14:48:00"
```

If data-types are set on the create table or applied after the fact, the import will work.

**Comment by hankinsoft** [comment]
@dave-redfern ahhh, thanks I see what's going on. Fix has been submitted to the App Store and should be available in ~24 hours or so.

**Comment by dave-redfern** [comment]
@hankinsoft thanks! you rock 😀  🙇

**Comment by hankinsoft** [comment]
If you get the chance, please let me know if this is fixed up for you in the latest version.

**Comment by dave-redfern** [comment]
I've not seen the update in the AppStore yet; but as soon as it's there I will update this issue!

**Comment by dave-redfern** [comment]
FYI: update still has not appeared for me in AppStore. I've been checking regularly.

**Comment by hankinsoft** [comment]
Sorry about that - I had left it as 'preparing for submission' rather than submitting it for review. It has been reviewed an approved and should be available on the store as of ~8 hours ago. If you get the chance, could you check and see if you have it available?

**Comment by dave-redfern** [comment]
No worries! Update installed and it's working again 😀  Was able to insert a 7MB csv into a type-less table without issues.
