### ISSUE TITLE
"There is already an open DataReader Associated with this command which must be closed first"

### ISSUE THREAD

**Issue by chaseblackmore** [hankinsoft/SQLPro#599]
Hi - 

We are experiencing an issue in our org with a user trying to run a script out of SQLPro Studio. When running a script, even a simple select statement, the user is met with the error "There is already an open DataReader associated with this command which must be closed first". We have another user in the org running the same scripts successfully through SQLPro Studio. Please let me know what additional information I can provide to get this resolved.

**Comment by hankinsoft** [comment]
Hi, two questions:

1. Do you see this for every query? Even a simple select?
2. When it does happen, does it happen the first time you run a query in the tab? Or after running a few queries?

**Comment by chaseblackmore** [comment]
Hi - 
Yes, we are seeing this error even on a simple select.
It happens the first time the user runs a query

**Comment by hankinsoft** [comment]
If you connect to the sample database, does the same issue occur?

**Comment by chaseblackmore** [comment]
I have not tried this yet, where can I find details for connecting to the sample database?

**Comment by chaseblackmore** [comment]
I am able to connect to the sample database with no issues, and no issues with creating a query.

**Comment by hankinsoft** [comment]
Thanks. I'm not 100% sure exactly what's going on yet. I am submitting a fix which MIGHT help as it has a bit better control of closing data readers. It usually takes ~24-48 hours for a new build to go live.

In addition, do you know if your server is doing any sort of login procedures? (Does it execute something when the user logs in)?

**Comment by chaseblackmore** [comment]
Kyle, 

This appears to be an issue on our end and not with the SQLPro Studio application itself. We have resolved the issue our user was experiencing. However, I do want to bring to your attention that connecting with Windows Authentication does have a slight bug of not wanting to save. Our workaround was filling in a few characters with "SQL Server Authentication", then removing the characters and flipping it over to windows authentication. This allowed the save button to pop up. Just wanted to bring it to your attention and I also want to give a huge thank you for the support you've given us with this problem.

**Comment by hankinsoft** [comment]
> This appears to be an issue on our end

Thanks for letting me know! Currious if its something you would be able to fill me in on as it might help with other users down the line.

> I do want to bring to your attention that connecting with Windows Authentication does have a slight bug of not wanting to save.

Thanks! I'll take a look into it.
