### ISSUE TITLE
FEATURE: SSH Tunneling for MSSQL

### ISSUE THREAD

**Issue by gxsanchez** [hankinsoft/SQLPro#60]
I noticed that you have the option to create an SSH tunnel on Oracle and Postgres. Could you also add this to MSSQL. I have a number of databases that I support that are behind firewalls and I need to  access them via a centralized cloud server using an SSH tunnel

**Comment by vintyara** [comment]
+1

**Comment by hankinsoft** [comment]
FYI I am working on this now. SSH tunnels for MSSQL have a few more things to deal with (instances for one), so its taking a bit longer.

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.108.app.zip? That should allow SSH tunnelling to Microsoft SQL Servers. Note, that if you are connecting to an instance you will need to specify the port (using the server,port\instancename format).
