### ISSUE TITLE
Feature request: SQL Editor: Highlight all instances of a selected string

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#600]
Here in VS Code, you'll notice that if I select the string "text", the other instance of "text" is also highlighted:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/15026225/111539911-12e55280-8734-11eb-8d12-6ba33be91c95.png">

I've found this to be extremely useful when working mid-large queries. It can help you to visually scan for instances of something without having to use "Find" and navigate to each one individually without any others highlighted.

SQLPro Studio 2021.21 (Build 110781.5)
macOS 11.2.3 (20D91)

**Comment by hankinsoft** [comment]
Something like the attached?
<img width="1162" alt="Screen Shot 2021-03-19 at 3 08 26 PM" src="https://user-images.githubusercontent.com/3160528/111824503-0fcd9c00-88c5-11eb-9abf-650a709a0f7e.png">

**Comment by jim256** [comment]
Yeah! That looks great

**Comment by hankinsoft** [comment]
This is available in the latest version. If you get the chance, please give it a try and provide any feedback.

**Comment by jim256** [comment]
I've noticed it works sometimes, but not other times:
<img width="233" alt="image" src="https://user-images.githubusercontent.com/15026225/113915299-db4e5100-979b-11eb-89c2-fcea14a00056.png">

Sometimes it'll also retain the highlighting on the secondary text even if the original text is no longer selected. Definitely looks like it's coming along though!

SQLPro Studio 2021.35 (Build 110789)
Snowflake 5.10.4
macOS 11.2.3 (20D91)

**Comment by hankinsoft** [comment]
Thanks - I believe I have this sorted in the latest available build. Please give it a try if you get the chance.

**Comment by jim256** [comment]
Awesome! So far so good. I'd personally prefer it to be more distinctive / jump out at you a bit more. Thoughts?

**Comment by jim256** [comment]
Also, it looks like it's doing single words only:

VS Code:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/15026225/114467521-425a7400-9ba7-11eb-8b39-3be8ae63f4dd.png">


SQLPro Studio:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/15026225/114467527-45556480-9ba7-11eb-8e3c-49df21cbf99b.png">


SQLPro Studio 2021.38 (Build 110792.5)
macOS 11.2.3 (20D91)

**Comment by jim256** [comment]
I like the increased opacity. Thanks for that! Very nice to have this and I'm taking advantage of it a lot.

It looks like the multi-word highlight has also improved, though it doesn't catch all scenarios:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/15026225/118045368-0c8ae580-b335-11eb-95a0-d578a6dd16b3.png">

**Comment by hankinsoft** [comment]
Fixed for the next build (2021.52) which has been submitted.

**Comment by jim256** [comment]
Awesome! Seems to be good there.

Doesn't seem to work for blocks, but maybe that's best? VS Code also does not.
<img width="901" alt="image" src="https://user-images.githubusercontent.com/15026225/118694459-52c6c580-b7c9-11eb-83f2-0b0c71362d91.png">

**Comment by hankinsoft** [comment]
I have it set to not do highlighting if a newline is selected. This is partially for performance, I don't want to be searching the visible area for to large of a string.

**Comment by hankinsoft** [comment]
Closing as I don't plan on adding support for when newlines are selected in the range.
