### ISSUE TITLE
Feature request: Results grid: Search for column names

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#601]
I absolutely love the filter (and search) capabilities in the results grid for data returned, and use it all the time.

One thing that'd also be helpful is the ability to search (with the same options of contains, begins with, etc.) the column names. When you're exploring a table you're unfamiliar with or which has been changed, this would be especially useful. You could, for example, look for "at" or "date" to quickly find a date column.

SQLPro Studio 2021.21 (Build 110781.5)
macOS 11.2.3 (20D91)

**Comment by hankinsoft** [comment]
I'm not exactly sure what you mean.... could you provide a bit more clarification on what your looking for?

**Comment by jim256** [comment]
Let's say that I have a 94-column table with which I'm unfamiliar. Let's say that I just double-click on the table name to get the default, 1000-result query to get a sense of the table.

After it executes, I may want to explore the table and look at / for specific columns. If I'm searching for a record's created date, but I'm not sure what that column is called in that table, I might want the results grid to help me find all columns whose names contain "date" or "created_at" or something like that.

Or maybe I'm looking for all columns in the table that may relate to shipping information, so I want to see all columns whose names contain  "ship".

Does that help?

I think that this feature would be the best if it were like the existing results grid search/filter features - meaning that it has both a search capability and a filter capability.

**Comment by hankinsoft** [comment]
Would it be possible to get a video of what you are looking for? I still can't seem to wrap my head around the idea.

**Comment by richardo2008** [comment]
I'll try to clarify. Say I have the below table, and I would like to get the full name of any column that contains "date" in it. In this case, I would get "signup_date" and "order_date" columns. This becomes super helpful when there are a lot of columns in the table.

![Screen Shot 2021-05-07 at 10 53 51 AM](https://user-images.githubusercontent.com/15026226/117483126-8cbede80-af22-11eb-84cb-f8da0628d405.png)

**Comment by jim256** [comment]
@hankinsoft did Richard's comment help?

**Comment by hankinsoft** [comment]
Sorry for the delayed response.
> did Richard's comment help?

I can give a firm maybe on my understanding :D

What I picture is a `Find column` context menu item on the table header context menu. It would contain a text entry, with a forward/back/done button, that would find the column name containing the text and highlight that column. Clicking forward/back would move to the next/previous matching column.

Would something like that work, or am I misunderstanding this completely?

**Comment by jim256** [comment]
Sounds like we're on the same page!

**Comment by hankinsoft** [comment]
Working on this for the next build:
![CleanShot 2021-08-06 at 14 15 01](https://user-images.githubusercontent.com/3160528/128548168-77951d6d-6c1b-4c94-90da-d05f2d3564ac.gif)

I still have a few things to work out but based on what you described, I think that should do the trick?

**Comment by hankinsoft** [comment]
This is available as of the latest version. Please give it a try if you get the chance and let me know if that suits the need.

**Comment by jim256** [comment]
Somehow missed your previous comment, but yes this does the trick! Awesome. It'd be nice to be able to use a keyboard shortcut, but definitely not a must.
