### ISSUE TITLE
Crash applying edited values in table-editor and often values aren't applied 

### ISSUE THREAD

**Issue by axmue** [hankinsoft/SQLPro#602]
Mac Os 11.2.3
mysql pro Version 2021.20 (Build 105012.5)

1) mysql pro crashes when applying edited values
2) values aren't applied after pressing apply without crashing.

**Comment by hankinsoft** [comment]
FYI, I've been working on a fix for this. It should be available mid next week.

**Comment by hankinsoft** [comment]
Hi,
The latest build is now available. It should sort the issue out. If you get the chance, please give it a try and let me know.

**Comment by hankinsoft** [comment]
Going to close this, as I no longer see any related crashes. If you still see this issue, please let me know.
