### ISSUE TITLE
SQLPro Studio, Feature Request: SQL Import

### ISSUE THREAD

**Issue by markbiek** [hankinsoft/SQLPro#603]
It would be really nice to be able to import data from `.sql` files in addition to CSV.

While you _can_ open a `.sql` file with the query editor, this doesn't work well for large files. I've found that SQLPro Studio can take several minutes to open even a relatively small sql file (<200mb).

**Comment by hankinsoft** [comment]
This has been requested a few times, so I'm adding it for the next build. Should be available early next week if not sooner.

**Comment by markbiek** [comment]
Excellent, thank you!

Once that's in, the app will be absolutely _perfect_

**Comment by hankinsoft** [comment]
SQL import is available in the latest SQLPro Studio build via the App Store. If you get a moment, please give it a try and let me know if it runs as expected.

**Comment by hankinsoft** [comment]
Going to close this. Please feel free to re-open if you find issues. Note to self - duplicate of #603.

**Comment by markbiek** [comment]
Sorry for the delay in responding. I've updated to the latest build & the import works great!
