### ISSUE TITLE
Progress window not closing - SQLPro SQLite

### ISSUE THREAD

**Issue by diek** [hankinsoft/SQLPro#604]
I am trying to export to csv for a table of 1000 rows. The file is created, but the progress window does not close. I have tried twice with the same result. I exited SQLPro SQLite before the second attempt.

<img width="1181" alt="export csv" src="https://user-images.githubusercontent.com/1261158/113037223-8d1dca00-916b-11eb-93d3-174ceebc1b75.png">

**Comment by diek** [comment]
A similar problem occurred when I tried to rename a table. The window refused to close.

**Comment by hankinsoft** [comment]
Hi. Are you using a build from the App Store, Setapp, or downloaded from the website?

**Comment by diek** [comment]
From the App Store, I have the most current release

**Comment by hankinsoft** [comment]
I wasn't able to reproduce, but I made a few changes to see if it would sort the CSV export window out. If you get the chance, can you update to the latest MAS build and see if that sorts it?

**Comment by diek** [comment]
Will do

**Comment by diek** [comment]
The export CSV is working.

The dialogue for 'Renaming Table' does not close. It renamed the table, I used the context menu to rename the table.

<img width="1134" alt="ScreenCapture 2021-04-03 at 01 08 33@2x" src="https://user-images.githubusercontent.com/1261158/113467490-ab105680-9419-11eb-8e97-56038d994ea2.png">

**Comment by hankinsoft** [comment]
I've updated a build for this. If you get the chance, could you give it a try? If you still don't see the window close, could you provide the log file?

**Comment by hankinsoft** [comment]
Did that latest build help out?
