### ISSUE TITLE
Feature Request: SQL Editor - Move line up/down

### ISSUE THREAD

**Issue by chrischain** [hankinsoft/SQLPro#605]
I have found many instances where it would be useful to move a line in it's entirety up or down, similar to the opt-up arrow/opt-down arrow commands in Visual Studio Code. I know that this can be accomplished using cut/paste, but that is more cumbersome that simply moving a line if the feature were available.

**Comment by hankinsoft** [comment]
Any chance you could post a video of VS Code doing what you mean? I think I understand, but I find vides are quite helpful to ensure what I implement is actually what you want. If its what I'm thinking, it should be pretty easy.

**Comment by chrischain** [comment]
This video shows the functionality pretty well: https://youtu.be/j_h1TcSrx_0?t=50

**Comment by hankinsoft** [comment]
This is available in the latest SQLPro Studio App Store build. If you get the chance, please give a try and let me know if its working for you.

**Comment by chrischain** [comment]
Another awesome and fast add. Works as expected. Thank you!
