### ISSUE TITLE
Feature Request: Connect Dialog - Move connection groups

### ISSUE THREAD

**Issue by chrischain** [hankinsoft/SQLPro#607]
It would be nice to be able to rearrange connection groups as I see fit. So far, I've had to resort to renaming them and moving around my connections to organize them the way I'd like to see them.

**Comment by hankinsoft** [comment]
Good idea. I'll take a look at this for an upcoming build.

**Comment by hankinsoft** [comment]
This is available in the latest SQLPro Studio App Store build. If you get the chance, please give a try and let me know if its working for you. (Use the up/down arrows to move connection groups - drag/drop might be implemented at a later point, but would take a much much longer time).

**Comment by chrischain** [comment]
It works fantastically... thank you for the speedy implementation!

**Comment by hankinsoft** [comment]
No problem! BTW, if you are enjoying the app, please consider leaving a rating or review in the App Store - as an independent developer they help me out a ton :)

**Comment by chrischain** [comment]
Consider it done.
