### ISSUE TITLE
Feature Request - Editor - Column mode or new copy option

### ISSUE THREAD

**Issue by pcarlson** [hankinsoft/SQLPro#608]
I am using SQLPro Studio.
I use SQLPro Studio to investigate data. Sometimes, I want to do a subset of data based on a previous query and adding an extra where clause isn't always easily.
Sometimes I use IN (value 1, value2, ...) to create that filter.

Today, I select the data I want and put it into sublime where I use the column mode and add a single quote and comma.
So I convert
a
b
c
to
'a',
'b',
'c'

It would be helpful if SQLPro Studio could make this easier.
I can think of two methods.
1) Add Copy option
when copying data, create an encapsulated CSV which would format the data into the clipboard as seen above.
2) Column Mode
A more generic solution would be to implement a column mode similar to sublime. Then I would add the single quote and comma on my own.

I appreciate you being open to new features. Let me know if you have any questions.

**Comment by hankinsoft** [comment]
Hi,
I just wanted to check, does [multi-cursor ](https://www.sqlprostudio.com/blog/11-multi-cursors) support do what your looking for?

In this example image:

![CleanShot 2022-01-12 at 09 05 44](https://user-images.githubusercontent.com/3160528/149145987-ad847d40-2038-4a6c-96db-2198fbcb0173.gif)


I hold option and drag between the results to add a cursor to each row, then press cmd-right to move the cursors to the end of the line, add a comma, then press delete to put them all on the same line.
