### ISSUE TITLE
allow access to SQL history after db has been moved

### ISSUE THREAD

**Issue by dmatthews-infoway** [hankinsoft/SQLPro#609]
I had to move a sqlite db to a different folder.  When I opened it in the new location none of the SQL query history was there.  I expected it to be stored in the database, not based on the location.

**Comment by hankinsoft** [comment]
This is something I'll have to think about as `I expected it to be stored in the database` is not something I would consider as I take a firm position of not adding and SQLPro metadata to any user databases. Currently as you noticed the history is based on the files location. I'll do a bit of research and see if I can find another way to uniquely identify a sqlite database.

**Comment by dmatthews-infoway** [comment]
Thanks for the response.

Is there anyway that I can change a config file or something so that I can get my queries back?

Dean Matthews
Manager, Jurisdiction Integration

Cell: 780.863.7341
[signature_307506597]

From: Kyle Hankinson ***@***.***>
Reply-To: hankinsoft/SQLPro ***@***.***>
Date: Wednesday, April 7, 2021 at 7:57 AM
To: hankinsoft/SQLPro ***@***.***>
Cc: "Matthews , Dean" ***@***.***>, Author ***@***.***>
Subject: [EXT]: Re: [hankinsoft/SQLPro] allow access to SQL history after db has been moved (#609)

________________________________
EXTERNAL EMAIL – USE CAUTION / COURRIEL EXTERNE – FAITES PREUVE DE PRUDENCE
________________________________

This is something I'll have to think about as I expected it to be stored in the database is not something I would consider as I take a firm position of not adding and SQLPro metadata to any user databases. Currently as you noticed the history is based on the files location. I'll do a bit of research and see if I can find another way to uniquely identify a sqlite database.

**Comment by hankinsoft** [comment]
If you place the file in the same location it was previously that should bring back query history.

**Comment by dmatthews-infoway** [comment]
Ok.  I’ll see if I can move things around to make the space on the old location.

Dean Matthews
Manager, Jurisdiction Integration

Cell: 780.863.7341
[signature_974520355]

From: Kyle Hankinson ***@***.***>
Reply-To: hankinsoft/SQLPro ***@***.***>
Date: Wednesday, April 7, 2021 at 8:13 AM
To: hankinsoft/SQLPro ***@***.***>
Cc: "Matthews , Dean" ***@***.***>, Author ***@***.***>
Subject: [EXT]: Re: [hankinsoft/SQLPro] allow access to SQL history after db has been moved (#609)

________________________________
EXTERNAL EMAIL – USE CAUTION / COURRIEL EXTERNE – FAITES PREUVE DE PRUDENCE
________________________________

If you place the file in the same location it was previously that should bring back query history.

**Comment by hankinsoft** [comment]
Hi. I'm going to close. I currently don't plan to make any changes to the query history for SQLite. As it stands, the history is based on the file location. If I receive more requests for this I will take a further look into it.
