### ISSUE TITLE
Bug: Script As ... Create/Alter getting other schemas where the view exists on multiple schemas

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#610]
SQL Pro Studio Version 2021.37 (Build 110791.5)
MySQL 5.7.31
The database has a lot of **identical** schemas in it with different names

When you chose a schema View and Script as > a Create or alter it comes back with SQL that has the table names prefixed with the schema name of the last similar schema. My guess is the bug is caused by the view existing in multiple schemas on the database server and it is picking up the last (or I have seen it pick another) schema name in the SQL. This is obviously bad as we don't want the view referencing a table across schemas. Note I also checked the information_schema.views SQL and it does not have the schema name prefixed on the table (unless It is deliberately specified by us)

Note this bug has been around a while, i.e. it is not a recent change that has caused it

This test case demonstrates it:
CREATE DATABASE A;
USE A;
CREATE TABLE TEST (id INTEGER);
CREATE VIEW TEST_VIEW AS SELECT * FROM TEST;

CREATE DATABASE B;
USE B;
CREATE TABLE TEST (id INTEGER);
CREATE VIEW TEST_VIEW AS SELECT * FROM TEST;

Right click on test_view in A and script as create and I get the following SQL that incorrectly references B
CREATE OR REPLACE test_view
AS
select `b`.`test`.`id` AS `id` from `b`.`test`;

Also another little bug is it should say CREATE OR REPLACE **VIEW** test_view

**Comment by hankinsoft** [comment]
Thanks, both items are fixed for the next build. It should be available by mid-next week or earlier.

**Comment by poorlymac** [comment]
Thanks a lot Kyle!

**Comment by hankinsoft** [comment]
FYI the latest build is available and this should be sorted. If you still have any issues with it, please re-open and let me know.

**Comment by poorlymac** [comment]
Hi Kyle, thank you for the fast response, I have tested on the new build and it looks good now.
