### ISSUE TITLE
"Format Query" has strange formatting for INSERT statements

### ISSUE THREAD

**Issue by markbiek** [hankinsoft/SQLPro#611]
Let's say I have the following query
```
select
*
from virtual_users;
insert into virtual_users (name, email) values ('Bob', 'bob@bob.com');
```

After running **Format Query**, I end up with this
```
SELECT
    *
FROM
	virtual_users; INSERT INTO virtual_users (name, email)
VALUES
	('Bob', 'bob@bob.com');
```

https://user-images.githubusercontent.com/917632/114462329-e1d03480-9bb0-11eb-9d7f-7e30574896b4.mp4

It'd be nice if the `INSERT` statement ended up on it's own line like other queries.

**Comment by hankinsoft** [comment]
Thanks, this is something I should be able to get sorted for the next build.

**Comment by markbiek** [comment]
FYI, it also appears to happen with `SHOW TABLES;` statements.

**Comment by hankinsoft** [comment]
The latest build is available via the App Store and should fix both of these.

**Comment by markbiek** [comment]
Awesome, thanks!
