### ISSUE TITLE
Feature Request: Support for Google BigQuery

### ISSUE THREAD

**Issue by adampresley** [hankinsoft/SQLPro#612]
**Product:** SQLPro Studio for Mac

I've found myself having to work in Google BigQuery a lot recently, and although there are tools out there, it would be great if I could connect to and work with BigQuery in a product I like (i.e. SQLPro, not DBeaver. :) ). 

Thanks for the awesome product!

**Comment by bruno-robert** [comment]
I would also use this feature. Another alternative would be to support ODBC or JDBC since BigQuery already has drivers for those.

**Comment by hankinsoft** [comment]
I’ve investigated ODBC in the past, but unfortunately it does not work with Apple sandbox. That said, I do have a partial JDBC implementation on the go. For people using JDBC, do you normally provide the jar files, or does the client you use provide them? Would you be willing to provide what your jdbc connection string might look like (minus private details)?

**Comment by bruno-robert** [comment]
For BigQuery, you would go to [this page](https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers) and download the jar files for BigQuery and pass them to the client (I've tested this with JetBrains DataGrip).

On that same page, there is a [document](https://storage.googleapis.com/simba-bq-release/jdbc/Simba%20Google%20BigQuery%20JDBC%20Connector%20Install%20and%20Configuration%20Guide.pdf) detailing how to use the JDBC files in more detail. This might contain useful information on how to implement
code that uses JDBC.

On page 12 of this pdf, there is a connection string template ` jdbc:bigquery://[Host]:[Port];ProjectId=[Project];OAuthType= [AuthValue];[Property1]=[Value1];[Property2]=[Value2];...`

When using DataGrip, I entered the connection details in the UI. I unfortunately don't remember seeing a connection string.

**Comment by adampresley** [comment]
The client I currently use for BigQuery is DBeaver. When you go to create a new BigQuery connection I believe it downloads the JAR files for you. From there you can provide connection information. Personally, I have no issue providing JAR files and connection strings myself.

**Comment by hankinsoft** [comment]
I've got a few requests for adding additional database types, so I'm creating a 'megathread' where I can keep track of what is being requested the most. I've going to close this issue, but if you could upvote 'Google bigquery' at https://github.com/hankinsoft/SQLPro/issues/833 that would be great!
