### ISSUE TITLE
Switch to tabular view on SELECT statements

### ISSUE THREAD

**Issue by jsoconnell** [hankinsoft/SQLPro#613]
It appears in the latest update of SQLPro for Postgres that after issuing an update or insert in the query panel, subsequent select statements default to the output vs. tabular view. 

<img width="762" alt="Screen Shot 2021-04-16 at 9 39 47 AM" src="https://user-images.githubusercontent.com/11394519/115032775-b2167a80-9e97-11eb-9d3f-091e66d73511.png">

The desired default behavior would be to automatically switch to the tabular view, as it did in previous versions. Thanks!

**Comment by hankinsoft** [comment]
Hi,
The app should switch you back and fourth automatically UNLESS you have manually switched between results and messages. Such as:

![CleanShot 2021-04-16 at 10 58 56](https://user-images.githubusercontent.com/3160528/115035346-e0e61e00-9ea2-11eb-94ae-51d23a9e4f4a.gif)

So in the above video, I run a 'resultless query', then a query with results. Resultless query switches me to the messages, then a query with results switches me back to the results grid.

If you have manually switch to messages or results, then at that point the app assumes thats what you have wanted to see and will stay there regardless. Is this not the behaviour you are seeing?

**Comment by jsoconnell** [comment]
On SQLPro for Postgres, Version 2021.38 (Build 1047832.5): I run an insert, switches me to messages, I run a select, stays on messages, does not automatically switch me back to results grid. If I manually switch to results grid and then run a series of select statements, stays in results. Any insert/update (haven't tried create) switches me to messages and subsequent queries stay in messages until I manually switch back.

**Comment by hankinsoft** [comment]
I've pushed a new build - can you let me know if you are still reproducing this? If so, would it be possible to get a video?

**Comment by jsoconnell** [comment]
Seems fixed! Thanks
