### ISSUE TITLE
CSV Export - Add support for \N as a NULL value option.

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#615]
Hi Kyle,

SQLPro Studio Version 2021.44 (Build 110798.5)

MySQL 5.7.31, though probably unimportant

Export result set as -> CSV then checking "Export nulls as blank string" still puts the string NULL in the CSV, e.g. 19,19,NULL,$19, where I was expecting 19,19,,$19

And whilst I am talking about the CSV
• On a separate note I think this should probably default to checked
• You may know common way to present NULL in a CSV file is as \N (it's more for system use not spreadsheet apps) so arguably you might be interested in implementing it as "Represent nulls as " with a text editable pulldown with options such as:
Blank (Default, and probably greyed like a suggest to indicate it's not the actual text "Blank")
\N
NULL
n.b. Adding \N support you would probably then want to add similar support to import, i.e. "treat NULL or \N as NULLs", too

CHEERS
Paul

**Comment by hankinsoft** [comment]
I've got the initial issue fixed for the next build (coming in a few days). I will take a look at adding \N support in a future build.

**Comment by poorlymac** [comment]
Thanks Kyle!

**Comment by poorlymac** [comment]
Fix confirmed working in Version 2021.46 (Build 110800.5), thanks again!

**Comment by hankinsoft** [comment]
Awesome, thanks for letting me know! I'm going to leave this issue open but chance the title to 'Add support for \N as a CSV export option'.

**Comment by hankinsoft** [comment]
Going to close this unless I get additional requests for it.
