### ISSUE TITLE
Dark/Light Themes Don't Switch when Mac is Locked

### ISSUE THREAD

**Issue by andyoneal** [hankinsoft/SQLPro#616]
iMac 5K 2017 with radeon pro 580. macOS 11.2.3 (though issue has been present throughout most or all of Big Sur versions). SQLPro Studio 2021.43 (did not start with this update. been a problem for a couple months.)

I have my macOS appearance set to Auto, which switches from Light to Dark mode automatically based on the time (at least I think it's based on time). I also have two separate themes in SQL Pro set to Default (Light) and Default (Dark).

As expected, SQLPro will switch themes as I'm using it along with the rest of the OS. However, if the Mac is locked during this switch over (especially noticeable when logging on in the morning after a late night), after unlocking the OS has switched themes correctly but SQLPro's Query Editor theme has not switched.

Opening preferences and hitting apply is usually enough to kick it back into the right theme, though there are occasionally some strange lingering issues with the Plain Text color or highlighted text.

Issue has been ongoing for at least two months. Wasn't a big enough issue to report. I assume it's a pretty small sliver of your user base that uses the Auto theme AND sets separate themes in SQLPro.

**Comment by hankinsoft** [comment]
Thanks for the report. Working on a fix.

**Comment by hankinsoft** [comment]
If you get the chance could you see if the latest build (2021.46) fixes this for you?

**Comment by hankinsoft** [comment]
I'm going to close this. Please let me know if you are having any additional troubles with this.

**Comment by andyoneal** [comment]
Sorry for not reporting back. This issue still exists on 2021.46.

**Comment by hankinsoft** [comment]
Hi - I think I've sorted this in the latest build. If you get a chance, could you check and confirm?
