### ISSUE TITLE
Bug: Snowflake: CURRENT_TIMESTAMP returning incorrect value

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#617]
This problem may not be restricted to `CURRENT_TIMESTAMP` only. It's just where I've noticed it so far.

If I execute the below in SQLPro Studio as well as in the Snowflake web console, I get different results:

```
SELECT
	CURRENT_TIMESTAMP
,	CURRENT_TIMESTAMP::TIMESTAMP
,	CURRENT_TIMESTAMP::TIMESTAMP_NTZ
,	CURRENT_TIMESTAMP::TIMESTAMP_TZ
,	CONVERT_TIMEZONE('America/Los_Angeles', CURRENT_TIMESTAMP::TIMESTAMP_TZ)
,	CONVERT_TIMEZONE('UTC','America/Los_Angeles', CURRENT_TIMESTAMP::TIMESTAMP_NTZ)
,	CONVERT_TIMEZONE('UTC','America/Los_Angeles', CURRENT_TIMESTAMP)
;
```

SQLPro Studio:
2021-04-27 20:50:22.291000000
2021-04-27 13:50:22.291000000
2021-04-27 13:50:22.291000000
2021-04-27 13:50:22.291000000 -07:00
2021-04-27 13:50:22.291000000 -07:00
2021-04-27 06:50:22.291000000
2021-04-27 06:50:22.291000000

Snowflake web console:
2021-04-27 13:50:09.964 -0700
2021-04-27 13:50:09.964
2021-04-27 13:50:09.964
2021-04-27 13:50:09.964 -0700
2021-04-27 13:50:09.964 -0700
2021-04-27 06:50:09.964
2021-04-27 06:50:09.964

The hour and time zones are the issue, not the minutes / seconds (simply didn't execute them at the exact same moment).

Our TIME ZONE parameter is 'America/Los_Angeles'.

SQLPro Studio 2021.45 (Build 110799.5)
Snowflake 5.14.1
macOS 11.2.3 (20D91)

**Comment by jim256** [comment]
FWIW, I spoke with Snowflake Support about this. The new Snowflake "preview" app is consistent with SQLPro (and inconsistent with their docs). The standard web console is inconsistent with SQLPro (and consistent with the docs).

They are looking into the issue regarding the preview app.

**Comment by jim256** [comment]
I received this response from Snowflake support:

> NEW UI issue:
> Unfortunately, the new UI issue is not a simple fix, so this will take a month or so to release. Sorry about that.
> However, once this enhancement is implemented it will be notified via release notes: https://docs.snowflake.com/en/release-notes.html#release-notes ;
> 
> SQLPro:
> This looks to be SQLPro settings. Please ask the SQLPro developer to check the app default settings and make the necessary changes.

Just to recap, SQLPro returns the same value for CURRENT_TIMESTAMP as the "new Snowflake UI" ("Preview App"), but not the same value as the Snowflake "Classic Console". Sounds like the "Classic Console" value is the "correct" one that everything should be returning, and that the new UI will return soonish.

**Comment by hankinsoft** [comment]
So is the underlying issue just that it displays '07:00' rather than '0700'? If so thats a super easy fix.

**Comment by hankinsoft** [comment]
I see that its not just that :D

**Comment by hankinsoft** [comment]
> Our TIME ZONE parameter is 'America/Los_Angeles'.

If you run `show parameters;` on your web console and on SQLPro does the timezone parameter show the same value?

**Comment by jim256** [comment]
It shows as both "value" and "default" in SQLPro Studio, the Snowflake Classic Console, and the Snowflake Preview App.

**Comment by hankinsoft** [comment]
Fixed for the next build:

<img width="990" alt="Screen Shot 2021-05-27 at 8 31 19 PM" src="https://user-images.githubusercontent.com/3160528/119909145-912b5580-bf2a-11eb-8037-3981e62be3fb.png">

<img width="1116" alt="Screen Shot 2021-05-27 at 7 54 08 PM" src="https://user-images.githubusercontent.com/3160528/119909154-9688a000-bf2a-11eb-9940-5d7374968ec9.png">

This handles the three timestamp types snowflake has. Also ensured it matched the sample database results. (Also added TO_TIMESTAMP_LTZ, TO_TIMESTAMP_NTZ and TO_TIMESTAMP_TZ as recognized functions).

It should be available early next week.

**Comment by jim256** [comment]
Great! Looks like you were very thorough, which I appreciate. Will provide feedback once I know it's avaiilable.

**Comment by hankinsoft** [comment]
2021.56 has been submitted with this fix. Should be available in ~24 hours.

**Comment by hankinsoft** [comment]
Did that latest build help out with this?

**Comment by jim256** [comment]
I think we're all squared away! Nice to have the newly-recognized functions, too. Thanks a lot.
