### ISSUE TITLE
cannot open password protected sqlite database

### ISSUE THREAD

**Issue by marchharesoftware** [hankinsoft/SQLPro#618]
I can't open any password protected sqlite database using sqlpro.  

The database is created:

                        SQLiteConnection.CreateFile(c1.sqlitedb);
                        c1.sqlitecx = new SQLiteConnection("Data Source=" + c1.sqlitedb + ";Version=3;");
                        if ((c1.sqlitepass != null) && (c1.sqlitepass != ""))
                        {
                            if (c1.sqlitepassset)
                                c1.sqlitecx.SetPassword(c1.sqlitepass);

We open it like this:

                        sqlcnxstr = "Data Source=" + c1.sqlitedb + ";Password=" + c1.sqlitepass + ";Version=3;";
                        c1.sqlitecx = new SQLiteConnection(sqlcnxstr);
                        c1.sqlitecx.Open();

Can you adapt your product so it has the ability to open password protected sqlite databases?

I can't believe anyone uses unencrypted databases beyond prototyping maybe...

**Comment by hankinsoft** [comment]
SQLite3 does not natively support encryption/passwords. What type of encryption are you using? SEE, SQLCipher, other?

**Comment by marchharesoftware** [comment]
We currently use SQLite .NET in c# using the built in encryption - as you can see in my code example, this is built in with c# on windows.

This article explains how the built-in encryption works in c#:
https://stackoverflow.com/a/10586975
and
https://stackoverflow.com/a/26206554

It seems that that particular encryption is poorly documented.

Since the library is open source, I’m a bit surprised it’s not been implemented/ported elsewhere.  When I have more time I’ll try and look into where the actual code for this lies and how difficult it is to compile on Mac and Linux.

I am also looking at whether to keep this encryption or maybe switch to SQLCipher, which seems a bit more common outside of Windows.

Including the SQLCipher Community Edition in your product may be an option for you too.

**Comment by hankinsoft** [comment]
I'm going to close this for now. If I receive additional requests to add support for SQLCipher I will take a further look into supporting it.

**Comment by marcardar** [comment]
+1 for supporting sqlcipher

**Comment by Axemasta** [comment]
+1 SQLCipher, SQLPro is amazing to use and its very frustrating I have to use other clients for encrypted databases
