### ISSUE TITLE
Bug: Query Results Grid: Horizontal Panning Behavior Inconsistent

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#619]
As of maybe a week ago, horizontal panning in the results grid seems to be sort of "sticky" sometimes, and will get stuck momentarily or become really slow momentarily, then go back to normal. Seems to be overall less fluid / responsive / consistent than before. Sort of hard to explain, but really easy to notice if you experiment with it for a bit.

SQLPro Studio 2021.45 (Build 110799.5)
macOS 11.3 (20E232) (was also present on 11.2)

**Comment by hankinsoft** [comment]
Hi,
In previous versions of the app you couldn't scroll (multiple record sets) horizontally unless your mouse was 'to the right' where the 'overall scrollbar' goes. You could scroll the individual record sets, but when coming to the top or bottom of a record set, there would be no more scrolling. The 'overall scrollbar' would stay still until you moved your mouse over to the side.

In the latest version, when you have multiple result sets and you scroll to the top or bottom of an individual result set it will 'pause' for 0.5 seconds with the assumption being that you were looking for the top and/or bottom. This gives you a chance to see the first or last record. WITHOUT this delay it's near impossible to stop at the top/bottom of an individual result set without having the 'outer scroller' scroll.

You should be able to receive the old scrolling behaviour by moving your mouse to the rightmost area and scrolling at that location (as you would have done in previous builds).

Please let me know if that helps out.

**Comment by jim256** [comment]
That makes a lot of sense, although there are two things I should point out:

I'm talking strictly about horizontal scrolling. I'm unable to scroll to the left or right via the touchpad without it's getting "stuck".

This is currently happening when there is only one result set.

Are both of those part of the new desired behavior?

**Comment by hankinsoft** [comment]
I totally had horizontal and vertical flipped in my head. Investigating to see if I can reproduce.

**Comment by hankinsoft** [comment]
If you get the chance could you see if the latest build (2021.46) fixes this for you?

**Comment by bencorey** [comment]
I was experiencing the same horizontal scrolling "stickiness" as @jim256. Today's released build (2021.46) definitely resolved my scrolling issues.

**Comment by jim256** [comment]
Seems to be working well now. Thanks!
