### ISSUE TITLE
Import/Export CSV or dump file?

### ISSUE THREAD

**Issue by tblanchard** [hankinsoft/SQLPro#62]
I can't seem to find a single postgresql admin tool that can import a csv file nearly as well as SequelPro for mysql does.

Really need that.

**Comment by hankinsoft** [comment]
Hello, SQLPro offers similar import. Are you running into a specific issue and/or missing feature with it?

**Comment by tblanchard** [comment]
Where?

File menu has no import or export item.

**Comment by hankinsoft** [comment]
I like to hide things!

https://github.com/hankinsoft/SQLPro/wiki/Importing%20data and
https://github.com/hankinsoft/SQLPro/wiki/Exporting%20data

Should hopefully help you out.

**Comment by tblanchard** [comment]
I see.  You should put that on the file menu.

But that worked great, thanks.

**Comment by hankinsoft** [comment]
Glad it did the trick. I'll take a look at making some menu improvements in a future build.
