### ISSUE TITLE
Bug: Snowflake: Query Editor: Multiple Statements Being Considered as One

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#620]
Starting April 20, my team and I noticed that SQLPro Studio will occasionally not highlight separate statements correctly and will fail when trying to execute multiple statements.

I have "Execute query in cursor range" set to "Enabled (as default)". The highlighting of each statement has stopped working correctly sometimes. Even though there is a line with a `;` on it, the highlighting won't stop there and will often continue on for the entire rest of the file, even if there are 10 different statements.

Also, if I attempt to manually highlight and execute a few statements in these scenarios, it will return the error:
"Multiple SQL statements in a single API call are not supported; use one API call per statement instead."

It seems that it's identifying the selection as indeed having only one statement and therefore trying to use that method rather than an executemany kind of method.

On other scripts, it continue to work without issue. I've been unable to identify a pattern yet.

Log file attached of running a few set variable statements, then one query using highlight, then trying to run the same query by simply clicking inside it (this is where the highlight showed that the entire rest of the file was selected):
[com.hankinsoft.osx.sqlprostudio 2021-05-03--17-44-41-679.log](https://github.com/hankinsoft/SQLPro/files/6416688/com.hankinsoft.osx.sqlprostudio.2021-05-03--17-44-41-679.log)

SQLPro Studio 2021.45 (Build 110799.5)
macOS 11.3 (20E232)
Snowflake 5.14.3

**Comment by jim256** [comment]
@hankinsoft This is continuing to happen. I think it has something to do with using variables (which require the `$` prefix), perhaps only when using them more than once.

**Comment by hankinsoft** [comment]
Ohhhh it’s probably totally a conflict with MySQL delimiters in the sql
parsing. Could you possibly post an example script you might see this in?

**Comment by jim256** [comment]
Happens in this one:

```
SET CURRENT_PACIFIC_TIME_TZ = CONVERT_TIMEZONE('America/Los_Angeles', CURRENT_TIMESTAMP);


SELECT
	*

FROM
	PRODUCTS prod

WHERE
	prod.CREATED_AT > $CURRENT_PACIFIC_TIME_TZ
;


SELECT
	*

FROM
	PRODUCTS prod

WHERE
	prod.CREATED_AT > $CURRENT_PACIFIC_TIME_TZ
;
```

If you remove the last use of the variable, then it doesn't happen.

**Comment by hankinsoft** [comment]
2021.51 submitted with the fix.
