### ISSUE TITLE
Improvement for column name autocomplete

### ISSUE THREAD

**Issue by yeysman** [hankinsoft/SQLPro#621]
Hello,
Is it possible to improve autocomplete feature in the following behavior:
Let say we have a table TEST (personFirstName , personLastname, personCreatedAt)
If we are starting to write "person.." it will show us all fields. But if we will right, let say "prsn" - it shows nothing.
Please see the attached screenshot which shows how Azure Data Studio deals with autocomplete.
![image](https://user-images.githubusercontent.com/3490139/117106727-07ec8d00-ad89-11eb-98eb-2568f5f1e35d.png)
Could you please add the same behavior of autocomplete to SQLpro?

**Comment by hankinsoft** [comment]
I'm investigating to see the difficulty on this. I should have an update as to if it will be implemented soon or not next week.

**Comment by yeysman** [comment]
@hankinsoft 
Thank you!

But could you please also check if you write "pkmn" does it show you "pokemon"?

**Comment by hankinsoft** [comment]
Just wanted to check if the latest update has resolved this issue for you?

**Comment by yeysman** [comment]
@hankinsoft 
Yes. Thank you a lot. 

I found something strange, that i didn't encounter previously. Sometimes autocomplete provides me duplicated results (shows me twice column ID, FirstName etc). I caught this issue few times, during work with some procedures (I can't share them), but after i close the tab and open the procedure again - autocomplete doesn't show me duplications. Something going strange.
I am not sure it is related to this fix. Probably, i will open an issue once I find out in which cases it happens.

**Comment by hankinsoft** [comment]
Ok. I’ll close this issue for now - if you do see duplicates again, please create a new issue. A screenshot of the problem would be helpful as well if/when you see it.

**Comment by jim256** [comment]
This is awesome!
