### ISSUE TITLE
MSSQL temporary table columns autocomplete 

### ISSUE THREAD

**Issue by yeysman** [hankinsoft/SQLPro#622]
There is an issue with temp table columns autocomplete.
No matter how did you declare a table
`create table #test (personFirstName VARCHAR, personLastname VARCHAR, personCreatedA datetime)`
or
`declare @test as table  (personFirstName VARCHAR, personLastname VARCHAR, personCreatedA datetime)`

SQLpro doesn't provide autocomplete for table columns.

SQLpro Studio
Version 2021.46 (Build 110800.5)

**Comment by hankinsoft** [comment]
What version of SQL server are you using?

I tried running your first query (`create table #test (personFirstName VARCHAR, personLastname VARCHAR, personCreatedA datetime)
`).

And I do get autocomplete (using SQL Server 2014).
<img width="1393" alt="Screen Shot 2021-05-07 at 10 00 15 AM" src="https://user-images.githubusercontent.com/3160528/117453270-21bdd980-af1b-11eb-9d15-9d213f8b5ef3.png">

After you create your temp table, what happens if you run this query after creating your temp table?

```
SELECT
    SUBSTRING(
        t.name,
        1,
        CHARINDEX('___', t.name)-1
    ),
    c.name,
    ISNULL(ty.Name, 'UNKNOWN') 'Data type'
FROM
    tempdb.sys.columns AS c
    INNER JOIN tempdb..sysobjects AS t ON c.object_id = t.id
    INNER JOIN sys.types ty ON (c.user_type_id = ty.user_type_id OR c.system_type_id = ty.user_type_id)
WHERE
    xtype = 'U'
    AND t.uid = DATABASE_PRINCIPAL_ID()
ORDER BY
    t.name ASC,
    c.column_id ASC
```

**Comment by yeysman** [comment]
@hankinsoft 
There is an issue with your query. SUBSTRING fails, because of some objects do not contain "____".
I removed substring and your query returned result including temp table columns

![image](https://user-images.githubusercontent.com/3490139/117560845-0b8a5780-b09a-11eb-87b5-4e6ec0df37af.png)

I use MSSQL server 2016

**Comment by yeysman** [comment]
@hankinsoft 
Could you please clarify, did you have chance to check this issue with SQL Server 2016?
What I also found, that even if I try to get access to column using #test.{column_name} - auto-complete doesn't provide me with suggestions.

**Comment by hankinsoft** [comment]
I haven't made this fix yet. I'm planning it for the next build (either later this week or early next).

**Comment by hankinsoft** [comment]
2021.53 has been submitted with this fix. Should be available in ~24 hours.

**Comment by yeysman** [comment]
@hankinsoft 
Unfortunately, there is still an issue.
I tried the following queries on SQLPro v. 2021.53 (Build 110808.5),  SQL Server 2016:

`create table #test (person varchar(20), age int)

select * from #test where per -- no aoutcomple

declare @person as table (person varchar(20), age int)

select * from @person where per -- no aoutcomplete

select * from @person as p where p.per -- no aoutcomplete`

Could you please check it?

**Comment by hankinsoft** [comment]
Hi,
Two things I want to check here:

1. SQLPro does not currently support table based variables for autocomplete. So the `declare @person ...` will not work. I don't currently have an ETA on that. (Sorry I didn't mention this when you first posted --- I saw the temp table of the first part and my brain skipped over the variable).

2. For the temp table autocomplete to work, you must RUN the create table statement before the autocomplete will work, as SQLPro queries the temp db to get the list of autocomplete tables and queries. Can you confirm you are doing this?

> Could you please clarify, the query you provided does it somehow related to the way how the SQLPro fetches column names?

Yes, a query is run to fetch the temp table columns. The updated query is:

```
SELECT
    t.name,
    c.name,
    ISNULL(ty.Name, 'UNKNOWN') 'Data type'
FROM
    tempdb.sys.columns AS c
    INNER JOIN tempdb..sysobjects AS t ON c.object_id = t.id
    INNER JOIN sys.types ty ON (c.user_type_id = ty.user_type_id OR c.system_type_id = ty.user_type_id)
WHERE
    xtype = 'U'
    AND t.uid = DATABASE_PRINCIPAL_ID()
    AND t.name LIKE '#%'
ORDER BY
    t.name ASC,
    c.column_id ASC
```

With some additional out-of-sql logic.

**Comment by yeysman** [comment]
@hankinsoft 
I run this query and it returned me a temp table column, but autocomplete still doesn't work.
Do not know why. Apart from my table column, the query also returns columns from other temp tables not related to the context. Can it cause the issue?

**Comment by hankinsoft** [comment]
Could you post a CSV of the results when you run that query? That might help me figure it out. I'm also adding extra logging for the next build.

**Comment by yeysman** [comment]
@hankinsoft 
I accidentally removed DB connection settings. After I created a new connection and tried to reproduce the issue autocomplete returned columns of temp table.
So, it seems everything works fine for now.
Thank.

**Comment by hankinsoft** [comment]
Ok. Thanks for letting me know.
