### ISSUE TITLE
Bug: Delete Selected Rows generates an incorrect script

### ISSUE THREAD

**Issue by josh-nexxt** [hankinsoft/SQLPro#623]
This is on Version 2021.104 (Build 10531), although I initially noticed the problem on Version 2019.45 (Build 10478). This is on OSX Version 10.14.4 and the log file is attached (with some sensitive information removed).
[com.hankinsoft.osx.tinysqlstudio 2021-05-04--18-13-22-501.log](https://github.com/hankinsoft/SQLPro/files/6427501/com.hankinsoft.osx.tinysqlstudio.2021-05-04--18-13-22-501.log)

Steps to replicate:
1. Run a SELECT query by writing it manually within a query tab (not by right clicking on a table). In my example, we have a table called `Respondent`, and I selected all rows `WHERE RespondentID=xx`
2. Select all of the response rows (with cmd+a)
3. Right-click and select "Delete selected rows"
4. The generated `DELETE` query shows the wrong database table.

The same bug occurs repeatedly once it has happened the first time. If I then right click on a table and click "Select top 1,000 rows", and then repeat step 2-4, the generated query looks correct. I am not sure what would be causing this issue, but I assume it has something to do with state/session management where a table which was previously selected is mistakenly regarded as the 'active' one, even after another has been selected?

**Comment by josh-nexxt** [comment]
(Since this is a fairly critical bug, might I suggest that as a temporary solution you add some sort of warning to the delete modal?)

**Comment by hankinsoft** [comment]
Could you grab this build:
https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.2021.47.app.zip

And see if you still have the same issue? If so, please post the log file for this version as well.

**Comment by hankinsoft** [comment]
Just wanted to check in and see if that helped?

**Comment by josh-nexxt** [comment]
Hey @hankinsoft , my apologies for the slow response. I did try your new build and couldn't reproduce the problem there, but then I was having trouble reproducing the issue on the other builds as well. I will continue occasionally to try to reproduce it, if I can I will let you know!

**Comment by hankinsoft** [comment]
No worries. Thanks for letting me know.
