### ISSUE TITLE
Question / bug: Snowflake: Sessions Randomly Being Dropped and Queries Canceled

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#625]
Just starting a few days ago, I've been experiencing:
- constantly lose my session (for example, I'll declare `USE SCHEMA PUBLIC;`, then create a temp table, both with success. Then I'll try to query the temp table and be told it's gone. If I just try to run the CREATE again, I'll be told that the current session doesn't have a schema specified).
- receiving the message `SQL execution canceled` (but not the message that it was canceled by user). Looking in the Snowflake query history, the queries do not show as canceled.

I'm not 100% sure this is SQLPro Studio. It may be a Snowflake problem, but I wanted to ask: can you think of any changes made in the last 1-3 versions that could have caused either of these issues?

SQLPro Studio 2021.46 (Build 110800.5) (started experiencing this at least 1 version prior, maybe 2)
macOS 11.3 (20E232)
Snowflake 5.15.4

**Comment by hankinsoft** [comment]
> Can you think of any changes made in the last 1-3 versions that could have caused either of these issues?

I can't think of anything straight forward, but I'll take a look thought the history and see if anything pops out.

**Comment by jim256** [comment]
I mostly think this was a problem with my connection or Snowflake or something. Closing for now.
