### ISSUE TITLE
Use Big Sur sized icon in next build 

### ISSUE THREAD

**Issue by aescolastico** [hankinsoft/SQLPro#627]
Believe it or not, the current icon is slightly larger than the standard size. Heres an icon that's the correct size, made from the original. You may use it if you like. 
[AppIcon.icns.zip](https://github.com/hankinsoft/SQLPro/files/6449101/AppIcon.icns.zip)

**Comment by hankinsoft** [comment]
Thanks, I'm taking a look and should have this fixed up for an upcoming build (I've got multiple apps that use similar icons, so I'd rather fix my source than use the one you provided). Appreciate you pointing this out though.

**Comment by aescolastico** [comment]
Understandable!

**Comment by hankinsoft** [comment]
Sorry for the delay on this. I've been checking out the icon you sent vs the one I use and I'm not seeing the difference in size. Could you clarify for me what it was you changed? That might help me figure out what I'm looking for.

**Comment by hankinsoft** [comment]
From what I can tell, you made it smaller and added a bit of a shadow? Was there a template you worked with to do this? Are you available for hire to update all of my SQLPro app icons?

**Comment by aescolastico** [comment]
No need to hire me, I used a free tool to create this icon: https://apps.apple.com/us/app/image2icon-make-your-icons/id992115977?mt=12 

It's dead simple to do.

**Comment by hankinsoft** [comment]
Oh wow, I've been using like four apps to get my icons generated. This is going to save me a ton of work, thank you so much. I'm working on getting them all updated for the next build.
