### ISSUE TITLE
Studio Crashes on a simple Snowflake Query

### ISSUE THREAD

**Issue by MYRepoMan** [hankinsoft/SQLPro#628]
A simple Select * from Snowflake.Table limit 1000; consistently crashes the Studio client. Any way to prevent this?

**Comment by hankinsoft** [comment]
Hi. What app version are you using? Could you send a screenshot of the about dialog?

**Comment by MYRepoMan** [comment]
Process:               SQLPro Studio [23451]
Path:                  /Volumes/VOLUME/*/SQLPro Studio.app/Contents/MacOS/SQLPro Studio
Identifier:            com.hankinsoft.osx.sqlprostudio
Version:               2021.41 (110795)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SQLPro Studio [23451]
User ID:               *********785

Date/Time:             2021-05-12 09:18:44.538 -0400
OS Version:            Mac OS X 10.15.7 (19H1030)
Report Version:        12
Bridge OS Version:     5.3 (18P4556)
Anonymous UUID:        B

Sleep/Wake UUID:       D

Time Awake Since Boot: 260000 seconds
Time Since Wake:       3800 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        7  Dispatch queue: HSQueryTabViewController (QOS: USER_INITIATED)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [23451]

VM Regions Near 0:
--> 
    __TEXT                 0000000107469000-0000000107531000 [  800K] r-x/r-x SM=COW  /var/folders/*/SQLPro Studio.app/Contents/MacOS/SQLPro Studio

**Comment by hankinsoft** [comment]
Could you try this build:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2021.50.app.zip

And let me know if that sorts the issue for you?

**Comment by MYRepoMan** [comment]
All sorted now with the new build. Was this recently released, I just downloaded my version from your website last week so wondering how I stay updated. Thank you.

**Comment by hankinsoft** [comment]
Hi - this build has not been released, it was just sent to you (and one other user for a separate issue) to see if it sorted things out.

For updates, website users will see 'An update is available' in the database tree, which can be clicked on to download the update. (You can also use the App Store version as well, which automatically updates. Just click the 'have a license key, click here to enter it' button when prompted).
