### ISSUE TITLE
Bug: Snowflake: Object Search Returns No Results

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#629]
No matter what I type in the object search bar, nothing is ever returned for my Snowflake connection. I've tried changing case and using the full, exact table name.

If I click "Search everywhere", the window that opens is empty if my only connection is to Snowflake. It populates great with all other connections (or with everything but Snowflake if I'm connected to both at the same time).

I think this has been this way for at least one month, but perhaps much longer.

Seems to work fine for Postgres and MySQL.

Log file attached:
[com.hankinsoft.osx.sqlprostudio 2021-05-13--19-14-10-468.log](https://github.com/hankinsoft/SQLPro/files/6474603/com.hankinsoft.osx.sqlprostudio.2021-05-13--19-14-10-468.log)

SQLPro Studio 2021.49 (Build 110803.5)
macOS 11.3 (20E232)
Snowflake 5.17.1

**Comment by hankinsoft** [comment]
Thanks 100% totally because i forgot to implement it. I’ll take a look into
it next week.

**Comment by hankinsoft** [comment]
Fixed for the next build (2021.52) which has been submitted.
