### ISSUE TITLE
FEATURE: Save/Restore Query Tabs and Opened Queries Documents on Exit/Launch

### ISSUE THREAD

**Issue by mkormendy** [hankinsoft/SQLPro#63]
When starting the application, I would like the application to restore the query tabs and queries I had open previously when I shut the application down.

**Comment by cfdude** [comment]
additionally on this request, I'd like to see the previously open files remember what database it was connected to so I'm not forced to always select that database when re-opening the files.

**Comment by hankinsoft** [comment]
The latest release adds two new options in preferences:

1. 'Autosave' -> When enabled, query contents will be saved automatically. You will not be prompted to save when closing a tab as the contents have already been saved. This behaviour changes slightly depending on the 'app shutdown' state (see below). If save state is enabled, you will not be prompted at all. Your temporary files will saved and restored on launch. If 'Clean shutdown' is enabled, you WILL be prompted to save temporary queries.

2. 'App shutdown' -> 'Save state' or 'Clean shutdown'. When 'Save state' is enabled, shutting down and relaunch the app will bring you to a mostly consistent state (expanded database nodes are not yet recovered). 'Clean shutdown' will start you with a fresh connection.

Any feedback is welcome.

**Comment by mkormendy** [comment]
I haven't fully tested it .. but will do over the next week! Thanks for working this out!
