### ISSUE TITLE
Feature Request: Keyboard Shortcut to Open Object Search + Keyboard Navigation + Fuzzy Object-Name Matching

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#630]
I've seen a lot of other clients that allow you to very quickly find a table and do a quick `SELECT TOP 1000` kind of query on it.

I think this could be sort of done (get 80% of the way there with very minimal effort) in SQLPro Studio by simply creating a keyboard shortcut that'd open the object search pane, with the cursor already in the search box, with any text already there highlighted.

It'd be great if this feature used the fuzzy matching that was brought into autocomplete with #621 

It'd be even better if there were were a mechanism to navigate to and open the default `SELECT * FROM [TABLE] LIMIT 1000;` query by hitting enter, but that'd just be a nice addition.

End target: If I have a couple connections, with a lot of databases, schemas, and tables, and simply want to glance at the table called "customer_orders", it'd be great to be able to hit a shortcut, type "cusord", hit tab or something, then hit enter, and see my table data.

**Comment by hankinsoft** [comment]
- `Ctrl+F` added to the next build to instantly switch to the database search input.

From here, you can search, hit tab then find the entry you want. The keyboard shortcut `Cmd+Down` already works as a 'select top 1000' for a table entry. So with this change I can do the following:


https://user-images.githubusercontent.com/3160528/118262735-b4b2c280-b48b-11eb-8bcd-275dad4beb9d.mp4

I think other than the fuzzy search (which I'm thinking I will add and set to the default method), that would cover it?

**Comment by hankinsoft** [comment]
Ready for the next build (2021.52) which has been submitted. Both the keyboard shortcut and fuzzy search as shown here:


https://user-images.githubusercontent.com/3160528/118480335-782fd280-b6e8-11eb-91d0-f1df3c5822a5.mp4

**Comment by jim256** [comment]
Thank you for implementing so quickly! This will be really nice. I wish I'd thought to ask for it sooner.

This definitely gets super close. I think there are two things (that are sort of one) that would make sense to change:
1. Change the shortcut so that it isn't the same as another (I'd personally prefer that it be user configurable) (CMD + F is also used for search in the query results grid)
2. Make it so the shortcut works from anywhere. Currently, you first have to click in the left pane. I think the greatest advantage from this whole feature request comes in the fact that no mouse activity would be required to quickly get to a table.

**Comment by hankinsoft** [comment]
Hi,
Shortcut is CTRL+F rather than CMD+F (CMD+F will only work if you have the database tree focused - CTRL+F will work anywhere).

**Comment by jim256** [comment]
FWIW, I'm noticing that the very first search produces the spinning color wheel and takes around ~13 - 17 seconds to complete. Subsequent searches are nearly instantaneous. If I disconnect and reconnect from the server, the first search after reconnect is also very fast. But if I disconnect, close the app, then reopen and reconnect, then it's really slow again on the first search.

This does not seem to be an issue for MySQL nor Postgres.

SQLPro Studio 2021.52 (Build 110807.5)
macOS 11.3 (20E232)
Snowflake 5.18.1

**Comment by hankinsoft** [comment]
> But if I disconnect, close the app, then reopen and reconnect, then it's really slow again on the first search.

Could you provide a fresh log file for this? (Clear the log, relaunch, reproduce). Thanks!

**Comment by jim256** [comment]
> Hi,
> Shortcut is CTRL+F rather than CMD+F (CMD+F will only work if you have the database tree focused - CTRL+F will work anywhere).

Ah, ok awesome!

I was just coming back to this thread to ask if there was a keyboard shortcut to get back to the database tree? If not, maybe CTRL + F could just toggle it?

**Comment by hankinsoft** [comment]
> I was just coming back to this thread to ask if there was a keyboard shortcut to get back to the database tree? If not, maybe CTRL + F could just toggle it?

Thats a good idea, I'll add that in.

**Comment by jim256** [comment]
Hmm. Hard to say. I think maybe the only reason to have it be only if the search is focused is because `F` isn't intuitive for "switch to database tree".

I guess even the focus is required, you could just use CTRL + F twice to do the same thing (once to get the focus there, and again to toggle to database tree)?

**Comment by jim256** [comment]
> > But if I disconnect, close the app, then reopen and reconnect, then it's really slow again on the first search.
> 
> Could you provide a fresh log file for this? (Clear the log, relaunch, reproduce). Thanks!

You got it!

In this log, I open, connect, then search. This time, I think the first one only took around ~6 seconds (didn't time it on this one). Then I disconnect, reconnect, and search again. I hoped that'd be more helpful so you could see the slow way and then the fast way.
[com.hankinsoft.osx.sqlprostudio 2021-05-18--17-16-06-173.log](https://github.com/hankinsoft/SQLPro/files/6503166/com.hankinsoft.osx.sqlprostudio.2021-05-18--17-16-06-173.log)

**Comment by jim256** [comment]
>     * `Ctrl+F` added to the next build to instantly switch to the database search input.
> 
> 
> From here, you can search, hit tab then find the entry you want. The keyboard shortcut `Cmd+Down` already works as a 'select top 1000' for a table entry.

I've got to use tab 3 times to get to the results, and when doing so, there's no visual indicator that I'm in the right place. The first tab outlines "Search everywhere". The second tab highlights "Ignoring Case", and the third tab doesn't highlight anything, though I can then use the down arrow to start moving through the results.
Intended?

**Comment by hankinsoft** [comment]
> I was just coming back to this thread to ask if there was a keyboard shortcut to get back to the database tree? If not, maybe CTRL + F could just toggle it?

After a bit of testing, I decided to add a second keyboard shortcut to focus the database tree. `CTRL-D` will be the default shortcut.

> Seems I need to use tab 3 times to get to the results, and when doing so, there's no visual indicator that I'm in the right place.

Next version automatically highlight the first search entry when tabbing to the database search results:

![CleanShot 2021-05-19 at 10 03 12](https://user-images.githubusercontent.com/3160528/118817425-93861380-b889-11eb-8a0c-47cd570b76cc.gif)

Giving a visual indication that the database tree has focus.

> RE: Performance issues

When you run this query:

```
SELECT
    default_schema_name 
FROM
    sys.database_principals 
WHERE 
    name = CURRENT_USER

UNION

SELECT 
    SCHEMA_NAME()
```

Does that run successful for you? Or does it always result in an error? You don't happen to know of a query to get the default schema for the logged in user do you?

**Comment by jim256** [comment]
Love it!

I can't execute either of those queries.

I'm also not sure how you'd get the current schema. I tried a few things that I thought may work, but the only one that worked was for admins only. Tried searching but came up empty... :thinking:

**Comment by jim256** [comment]
I asked our Snowflake rep. Any user can run `DESC USER [USER_NAME]` and one result will be `DEFAULT_NAMESPACE`, from which you could get the schema.

**Comment by hankinsoft** [comment]
Submitted a new build which no longer needs to know the default schema. I think this will increase that initial search performance and maybe even the initial database tree table/schema expand. If not, please post an additional clean log if you get the chance.

**Comment by jim256** [comment]
Initial search seems to be much faster!
