### ISSUE TITLE
Collate Localized in query

### ISSUE THREAD

**Issue by Sebastien-Remy** [hankinsoft/SQLPro#631]
Hello,

I'm trying to do a query and sorting localized name string 

SELECT * from Items ORBER BY name COLLATE LOCALIZED ASC;

It doesn't work

SELECT * from Items ORBER BY name COLLATE NOCASE ASC; 
works but do not return expected list.

I Expect

aa
bb
éea
eeb
ccc

And I got
aa
bb
cc
éea
eeb

**Comment by hankinsoft** [comment]
Hi,
Wouldn’t this be an issue with your SQL server rather than with SQLPro?
Being the client, no sorting is done via SQLPro but rather it’s performed
by the server itself.

**Comment by hankinsoft** [comment]
Closing as this seems to be a server issue rather than a client issue.
