### ISSUE TITLE
connect issue: Connect failed because target host or object does not exist

### ISSUE THREAD

**Issue by jone-c90** [hankinsoft/SQLPro#632]
Hi,
 I report an error when I connect to Oracle Database.It can be connected normally with other tools.

![image](https://user-images.githubusercontent.com/25919819/118615570-73a41080-b7f3-11eb-8b43-d6f63d905b72.png)

**Comment by hankinsoft** [comment]
Are you trying to use a TNS file? Those are currently not supported in SQLPro.

**Comment by jone-c90** [comment]
I am not using TNS.

**Comment by hankinsoft** [comment]
Are you specifying a connection string? Could I get a screenshot of your connection settings?

**Comment by jone-c90** [comment]
![Uploading image.png…]()

**Comment by hankinsoft** [comment]
I've made some changes to oracle connections (and unfortunately currently Oracle support has been moved to SQLPro for Oracle - you can get a free license key by attempting to add an oracle connection in SQLPro Studio).

If you get the chance, could you let me know if you still see this issue?
