### ISSUE TITLE
Unable to read table alias font in dark mode

### ISSUE THREAD

**Issue by MYRepoMan** [hankinsoft/SQLPro#633]
Hi - looking to configure a different color for table alias as the super dark blue isn't readible while in dark mode. The appearance preferences don't list this color as an option to change. Is this configurable to change or do I have to change out of dark mode? Using SqlPro Studio Version 2021.50 (Build 110805)

eg: where the a. and b. are very hard to read
SELECT 
a.*
,b.* 
FROM schema1.table1 a 
	left join schema2.table2 b
	on a.field1 = b.field1

**Comment by hankinsoft** [comment]
Good point. I'll add that in.

**Comment by hankinsoft** [comment]
Added for the next build:

<img width="634" alt="CleanShot 2021-05-18 at 14 41 00@2x" src="https://user-images.githubusercontent.com/3160528/118698718-1efa9880-b7e7-11eb-8b73-f6fa0e894986.png">

Should be available later this week or early next.

**Comment by MYRepoMan** [comment]
Great, very helpful. Thanks
Matt

**Comment by MYRepoMan** [comment]
I'm running .50 purchased off the web and don't see any option to upgrade in the db tree and the version on your site is .40. Is there a way to get this upgrade that I'm missing?

**Comment by hankinsoft** [comment]
Can you re-launch and see if the update appears now?

**Comment by MYRepoMan** [comment]
All set. Thanks.
