### ISSUE TITLE
Slow Reading of Sqlite DB

### ISSUE THREAD

**Issue by chipbeaulieu** [hankinsoft/SQLPro#634]
I have a sqlite db with 7 tables but some of those tables have millions of records. When SqlPro for Sqlite opens the db, it reads the number of records in each table which can take up to a minute. Any changes to the records also requires a re-read of the database. This makes working with large db's painfully slow. 

Can you make reading the number of records an optional setting or some other solution that doesn't tie up the gui?

**Comment by hankinsoft** [comment]
Hi. There is a preference for this in the preferences window… I’m away from my computer at the moment, but when I get back I will post it here.

**Comment by hankinsoft** [comment]
It's the 'Enable table row counts' preferences. If you uncheck this, rows will no longer be counted.

<img width="657" alt="Screen Shot 2021-05-19 at 1 01 52 PM" src="https://user-images.githubusercontent.com/3160528/118845751-71e55600-b8a2-11eb-9ab2-2e761b67c438.png">

Please let me know if that sorts this for you.

**Comment by chipbeaulieu** [comment]
Awesome. I thought I had checked the preferences, but clearly I didn't. Thank you for being kind and replying quickly.

**Comment by hankinsoft** [comment]
No worries. Please let me know if I can help with anything else. If you find that you are enjoying the app, please consider leaving it a rating or review. As an independent developer, they help me out a ton.

**Comment by chipbeaulieu** [comment]
Just finished my 5-star review.

**Comment by hankinsoft** [comment]
Thank you so much! I really appreciate that.
