### ISSUE TITLE
Bug iPadOS - SQLPro Studio: Stored SSH Key disappears after force quitting the app 

### ISSUE THREAD

**Issue by georgziganek** [hankinsoft/SQLPro#636]
Tested on iPadOS 14.5.1
SQLPro Studio V2021.39.63

![image](https://user-images.githubusercontent.com/71907804/119053544-d16b6080-b98b-11eb-98d1-f7955c745c18.png)

Steps to reproduce:
- Edit Connection
- Tap SSH Tunneling
- Activate "Use private key"
- Tap "Key"
- Paste ssh key
- tap save on the SSH modal
- tap save on the configuration modal

When you connect, it works fine. But if you force quit the app, the next time you open the app, the SSH is not stored anymore.

Please have a look on why this is happening. thanks

**Comment by hankinsoft** [comment]
Hi! The latest build available should have this sorted out. If you get the chance, please give it a try and let me know.

**Comment by georgziganek** [comment]
Excellent, I’ll try it out when it’s released

**Comment by georgziganek** [comment]
Tested this one as well and it seem to work! Thanks for the quick implementation!

**Comment by hankinsoft** [comment]
No worries. Please let me know if I can help with anything else. Also, please consider leaving a rating or review. As an independent developer, they help me out a ton!
