### ISSUE TITLE
Bug iPadOS - SQLPro Studio: Syntax highlighting not working with certain .sql files

### ISSUE THREAD

**Issue by georgziganek** [hankinsoft/SQLPro#637]
Tested on iPadOS 14.5.1
SQLPro Studio V2021.39.63

I work with a lot of .sql files in a repository that I access with the "Open File" functionality.
Unfortunately, when a file is opened, the Syntax highlighting does not always work. I noticed though that it mostly happens with .sql files that contain long queries. In those cases, I just see white letters everywhere. Here is a screebshot:

![image](https://user-images.githubusercontent.com/71907804/119055888-63c13380-b98f-11eb-9d7e-fe6fab53403c.png)

The same files work fine on other SQL clients on the mac.

**Comment by hankinsoft** [comment]
Hi! The latest build available should have this sorted out. If you get the chance, please give it a try and let me know. If you are still seeing issues, please let me know the file size of the files which are not highlighting (you could post them here if possible).

**Comment by georgziganek** [comment]
Excellent, I’ll try this one out as well and let you know.

**Comment by georgziganek** [comment]
Tested this now and it works! Thanks for the fast implementation!
