### ISSUE TITLE
Feature Request: Query Results viewer: Foreign key lookups

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#639]
Let's say I have an orders table and a products table. My orders table has a column `product_id`. This is a foreign key to products.id. When browsing the orders table data, it'd be great to be able to click on a row that has a value of 4 for `product_id` and have it show me the record for products WHERE id = 4.

I know Postico does this for Postgres and DBeaver does this for most databases. I think I personally prefer Postico's implementation. It has a popup window with filtering and sorting options and such, showing the target record highlighted / selected, but still showing a few other records as well, so you can get a sense of that table while you're at it.

This makes data exploration and browsing so much more friendly and fast.

Ideally this would work on all DB types. If I were asked to give an order of preference, I'd say Snowflake, then MySQL, then Postgres, then others.

**Comment by hankinsoft** [comment]
Hi. This actually already exists (except maybe not for snowflake 😁). On mysql or Postgres, you just need to mouse over the foreign key cell and a little arrow will appear. Click it and a new tab opens with a select x where x. I’m away from my system at the moment so I can’t send a video or screenshot. I’m fairly certain I never implemented it for snowflake, so I’ll take a look into getting it added.

**Comment by jim256** [comment]
I wondered this, so I checked a Postgres DB and a MySQL DB before posting.
Looking at a table in Postico, the DDL shows `REFERENCES [table_name]([column_name]`. If I do Script As on the same table in SQLPro Studio, it seems to be unaware that it links to anything else.

In the case of MySQL, it does show the correct `FOREIGN KEY` text when the table is scripted, but there is no arrow that appears when hovering over a cell in that column.

**Comment by hankinsoft** [comment]
Snowflake foreign key links have been added for the next build:


https://user-images.githubusercontent.com/3160528/119226014-86616280-badd-11eb-9775-a624def2e31d.mp4

In addition, there was an issue which was making these links fail on Big Sur. Im double checking MySQL, PostgreSQL, MSSQL, SQLite and Oracle now to make sure they still work.

**Comment by hankinsoft** [comment]
> If I do Script As on the same table in SQLPro Studio, it seems to be unaware that it links to anything else (just shows the INT data type and that's it).

So when you do a (Postgres) script in SQLPro Studio, you don't get

```
ALTER TABLE IF EXISTS ..
	ADD CONSTRAINT ...
	FOREIGN KEY (...)
	REFERENCES ... (...);
```

Such as:
<img width="1717" alt="Screen Shot 2021-05-22 at 10 42 52 AM" src="https://user-images.githubusercontent.com/3160528/119228685-887dee00-baea-11eb-8107-c89399c099b9.png">
?

**Comment by hankinsoft** [comment]
(Does your table have any special characters? Is it enclosed in quotes?)

**Comment by jim256** [comment]
I'm not sure I'm answering your question correctly, but this is what I get if I do Script As on the postgres table:
`BEGIN;

CREATE TABLE IF NOT EXISTS table_name (
	id_col_name integer DEFAULT nextval('stuff'::regclass) NOT NULL,
	col_name integer NOT NULL,
	col_name character varying,
	col_name integer,
	col_name integer NOT NULL,
	col_name integer NOT NULL,
	col_name double precision,
	col_name character varying,
	col_name timestamp without time zone DEFAULT now() NOT NULL,
	col_name timestamp without time zone DEFAULT now() NOT NULL,
	col_name double precision,
	col_name double precision,
	col_name double precision,
	col_name double precision,
	col_name double precision,
	col_name double precision,
	col_name double precision,
	col_name integer,
	col_name timestamp without time zone,
	col_name timestamp without time zone,
	col_name integer,
	PRIMARY KEY(id_col_name)
);

COMMIT;`

That's exactly as it is, with the exception (obviously) of the names and `stuff`.

If I right click on it and do Alter, I get this in the Foreign keys window
<img width="1822" alt="image" src="https://user-images.githubusercontent.com/15026225/119396921-bd2ca980-bc92-11eb-937e-6541ddaa1e8e.png">

It does have foreign keys. I can verify that in Postico or DBeaver and I just also know that this table has a few.

**Comment by hankinsoft** [comment]
If you run the following query in PostgreSQL:

```
select
  kcu.constraint_name,
  kcu.ordinal_position,
  kcu.table_schema AS primary_schema,
  kcu.table_name AS table_name,
  rel_kcu.table_schema AS foreign_table_schema,
  rel_kcu.table_name AS foreign_table_name,
  kcu.column_name as column_name,
  rel_kcu.column_name as foreign_column_name,
  rco.update_rule,
  rco.delete_rule,
  (SELECT DISTINCT obj_description(pg_constraint.oid) FROM pg_constraint where conname = kcu.constraint_name) as comment
from information_schema.table_constraints tco
join information_schema.key_column_usage kcu
          on tco.constraint_schema = kcu.constraint_schema
          and tco.constraint_name = kcu.constraint_name
join information_schema.referential_constraints rco
          on tco.constraint_schema = rco.constraint_schema
          and tco.constraint_name = rco.constraint_name
join information_schema.key_column_usage rel_kcu
          on rco.unique_constraint_schema = rel_kcu.constraint_schema
          and rco.unique_constraint_name = rel_kcu.constraint_name
          and kcu.ordinal_position = rel_kcu.ordinal_position
where tco.constraint_type = 'FOREIGN KEY' AND kcu.table_name = '{TABLE_NAME}' AND kcu.table_schema = '{TABLE_SCHEMA}'
order by kcu.table_schema,
         kcu.table_name,
         kcu.ordinal_position;
```

Replcing {TABLE_NAME} and {TABLE_SCHEMA} with your proper table and schema, are any results returned?

**Comment by jim256** [comment]
Hmm, no. Nothing.

In Postico, it does show the key under the "CONSTRAINTS" section if I right-click on the table and choose "Structure". If I choose "DDL", it just has "REFERENCES" in the column declaration in the CREATE statement (though it does give the caveat that a Postico-generated DDL script is not official).

DBeaver does not list it under References (though it does show other things there that make sense) nor "Constraints", but does have it under "Foreign Keys".
The DDL generated by DBeaver does indeed show the `ALTER TABLE [SCHEMA_NAME].[TABLE_NAME] ADD CONSTRAINT [CONSTRAINT_NAME] FOREIGN KEY ([COLUMN_NAME]) REFERENCES [SCHEMA_NAME].[TABLE_NAME](COLUMN_NAME);` that you asked about earlier. The DDL generated by Postico and SQLPro Studio do not.

**Comment by hankinsoft** [comment]
Hmmmm ok. If you run the query:

```
SELECT
  conname,
  pg_catalog.pg_get_constraintdef(r.oid, true) as condef
FROM pg_catalog.pg_constraint r
WHERE r.conrelid = '{TABLE_SCHEMA}.{TABLE_NAME}'::regclass
AND r.contype = 'f' ORDER BY 1
```

Replacing {TABLE_NAME} and {TABLE_SCHEMA} with your proper table and schema, are any results returned?

**Comment by hankinsoft** [comment]
the new build with fixed-support for Postgres and added support for snowflake should now be available.

**Comment by jim256** [comment]
Awesome!
Just to make sure, you saw in my earlier comments that it was not working for MySQL either, right? Details in [this comment](https://github.com/hankinsoft/SQLPro/issues/639#issuecomment-846200546).

**Comment by hankinsoft** [comment]
> Just to make sure, you saw in my earlier comments that it was not working for MySQL either, right? Details in this comment.

Yep --- Just wanted to check if some of the general fixes I had made sorted this out for you first before I dove into the MySQL. With Postgres, no FK's seemed to be loading for you at all, so that made it a bit easier to diagnose.

So -- that said:

1. I'm assuming you are still not seeing the foreign key links for MySQL when mousing over the cells.
2. If you connect to the sample Northwind MySQL database and double click on the `Orders` table, are you able to use the foreign key links on the `CustomerID` and `EmployeeID` columns?
3. Could you perform a `select` on your MySQL `subscriptions` table? (Thats the one you mentioned above). Can I get a screenshot of the query? (or an exact copy of the select query)?
4. Do the primary keys highlight when you run a select on the `subscriptions` table?

**Comment by jim256** [comment]
Great! Seems to be working great for Postgres and Snowflake.

1. Correct.
2. Yes.
3. 
<img width="745" alt="image" src="https://user-images.githubusercontent.com/15026225/119875538-193a3c80-bee4-11eb-9751-bc9f623b3732.png">
`SELECT
	id
,	user_id
,	alert_condition_id
,	date_deactivated
,	date_created
,	date_modified
    
FROM
	subscriptions`
4. Just the `id` column highlights. When I click on it (where the id is 1), it executes the following query (which, of course, fails):
`SELECT * FROM alert_conditions WHERE alert_condition_id = 1`

**Comment by hankinsoft** [comment]
> When I click on it (where the id is 1), it executes the following query (which, of course, fails) ....

Are you saying that the id column is showing the foreign key link button when you mouse over it?

Could you post the DDL for the `alert_conditions`? I think I might know what's up.

**Comment by hankinsoft** [comment]
You can ignore. I have it nailed down. Fixed for the next build. Basically I have the columns swapped --- alert_conditions_id vs id. Because my tables use the same column name 'CustomerID - CustomerID' I've never noticed this. I'm surprised it hasn't been reported by anyone else though.

**Comment by jim256** [comment]
Awesome! Thanks so much. Looking forward to it.

**Comment by jim256** [comment]
I believe this is resolved!
