### ISSUE TITLE
Allow me to choose if I want to overwrite the current file on save, automatically

### ISSUE THREAD

**Issue by jmpavlick** [hankinsoft/SQLPro#640]
Hey, after a few years away I have rediscovered SQLPro. It's a delightful application and I absolutely love it!

One thing that struck me right away, though, is that if I have a query open and I'd like to save changes, I'm prompted to save it as `SQLProQuery.sql` every time; I have to navigate to the file I'd like to save to and I'm prompted to overwrite every time.

This may be rare, but for the workflow I use for the project I'm working on - I manually create and test database migration scripts as `.sql` files, datestamped and linked to the related JIRA story. When I'm ready to deploy, I run my deployment scripts, SSH in to the server, and manually execute the migration. I don't release data layer changes often, and this approach has served me well for a few years now.

I searched the issues (open and closed) before posting this, so I really hope it's not a duplicate.

Not to "solution" for you - but it would be cool if I could check a box in the `Preferences` dialog that allowed me to choose to overwrite the current query automatically on save.

I'm on Windows 10, if that helps. Please let me know if you have any further questions. This aside, I am really enjoying the tool and hope to use it for years to come.

Thanks,
John

**Comment by jmpavlick** [comment]
Whoops. Nevermind. I forgot that I was accidentally saving a file to a folder inside of my WSL Debian installation.

So I guess the real bug here is that if a save fails, there's no notification from the application. None of my changes were actually persisted to the file, but I didn't lose any work because I copied my script out of SQLPro and into a text editor.

I don't know if this is weird edge-case behavior - I know that WSL folders are a little weird - but it's pretty reproducible.

**Comment by hankinsoft** [comment]
Hi,
So to confirm - this is SQLPro on Windows - when saving, there is an error? Does the log file write any errors out? You can find it by going to 'View' -> 'Logs'.

**Comment by hankinsoft** [comment]
Going too close. If this is still ongoing and you get the chance, please consider uploading the logs and re-opening this issue.
