### ISSUE TITLE
Light/dark mode does not switch automatically

### ISSUE THREAD

**Issue by gitjoost** [hankinsoft/SQLPro#642]
Light/dark mode appears to be implemented only partially; the query display is light/dark but the table selection on the right does not change color. Additionally, the application does not switch its light/dark mode when the OS does, one must exit and re-enter the application. (Big Sur).

**Comment by hankinsoft** [comment]
Hi,
Could you send a screenshot with the issue you are seeing? (What it is that is not switching between dark/light mode?). I'm not able to reproduce - if I switch between dark and light using Big Sur, everything is switching for me. A screenshot should help me figure out what your referencing.

**Comment by gitjoost** [comment]
Switched from light to dark: 
<img width="2116" alt="Screen Shot 2021-05-23 at 11 49 51 AM" src="https://user-images.githubusercontent.com/1977649/119272919-4d002400-bbbd-11eb-82c0-68acb7386448.png">

**Comment by hankinsoft** [comment]
Hi - I submitted a new build (2021.55). Could you check and see if that sorts this issue out for you?

**Comment by gitjoost** [comment]
Yep, working, thanks!

**Comment by gitjoost** [comment]
quick work, thanks

**Comment by chriseomi** [comment]
> Hi - I submitted a new build (2021.55). Could you check and see if that sorts this issue out for you?

Big fan and long time customer  of SQL Pro. I am having same issues as OP. However, I bought license direct and use stand alone version. Would love to use the latest version, however the one on the website at 

https://macpostgresclient.com/download.php

is 2021.53 which is what I'm currently using, which appears from your comment to be an older version that contains this issue.

**Comment by hankinsoft** [comment]
@chriseomi can you grab https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.2021.89.app.zip? Thats a newer version which should sort the issue.

**Comment by chriseomi** [comment]
New version works great. I'm a happy camper now. Thank you!
