### ISSUE TITLE
Feature Request iPadOS - SQLPro Studio: Arrow Key Navigation in result set

### ISSUE THREAD

**Issue by georgziganek** [hankinsoft/SQLPro#643]
Tested on iPadOS 14.5.1
SQLPro Studio V2021.53.71

It would be really nice to have an arrow key navigation in the result set. Right now the arrow keys only work in the editor but do nothing when a result set column, row or cell is selected.

**Comment by hankinsoft** [comment]
Good idea. I'll take a look for a future build.

**Comment by hankinsoft** [comment]
Hi. The latest build now has navigation, but I've got a couple improvements coming. The next build will include auto-scrolling when navigating via arrows, plus using shift to increase the selection.

**Comment by hankinsoft** [comment]
Hi - the latest build is now available which should have much improved keyboard navigation for result sets. If you get a chance, please give it a try and let me know what you think.
