### ISSUE TITLE
Snowflake: Question: Client Version

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#644]
I'm trying to optimize Snowflake costs. Snowflake advised making sure that everything connecting to it was using the recommended client version (listed [here](https://docs.snowflake.com/en/release-notes/requirements.html#recommended-client-versions)).

What client and what version is SQLPro Studio using?

**Comment by hankinsoft** [comment]
Hmmmm, none of the above. I'm using [libsnowflakeclient](https://github.com/snowflakedb/libsnowflakeclient) v0.5.13.

**Comment by jim256** [comment]
That's kind of interesting. Do you think this is anything to be explored? Ha "Under development. No functionality works. Suggestion is welcome at any time." doesn't exactly inspire confidence.

Do you think the app may benefit from using one of the other connectors? Snowflake has repeated to me a few times that they are constantly improving the performance of the connectors. I wonder if those same improvements make their way into this pre-1.0 code.

**Comment by hankinsoft** [comment]
> Do you think the app may benefit from using one of the other connectors? 

Unfortunate no. macOS does not support any of those technologies natively out of box (especially using the sandboxes model required for the App Store). Using the C connector is currently the only way for SQLPro to use Snowflake.

in addition, it’s also a bit deceiving that the version of libsnowflakeclient is 0.5.13 as this is actually the same library the php/pdo uses internally (possibly others as well).

**Comment by jim256** [comment]
Understood!
