### ISSUE TITLE
Feature Request: Default "Export nulls as blank strings" to last used value

### ISSUE THREAD

**Issue by sinklair** [hankinsoft/SQLPro#645]
When exporting to CSV, the ability to export nulls as blank strings is extremely useful. However, if you export a result set and check the option, you must check it each time you export a file.

Request: default the value to what it was on the last export and/or provide a system setting for this.

Incidentally, making this a system option would be great if it also affected Copy operations.

**Comment by hankinsoft** [comment]
Sorry for the delay. For 'Copy' there is actually a default in the preferences:

<img width="550" alt="Screen Shot 2021-06-10 at 8 24 28 AM" src="https://user-images.githubusercontent.com/3160528/121517151-67ac0880-c9c5-11eb-844e-590fd048a86c.png">

I think if I were to setup the export to default to use whatever you have set here, that should resolve everything you are looking for?

**Comment by sinklair** [comment]
@hankinsoft yes, that would be perfect.

**Comment by hankinsoft** [comment]
This has been added for awhile, but I forgot to close the issue. If your finding the latest build does not work as you wish, please feel free to re-open and let me know.
