### ISSUE TITLE
Possible Release Notes Updating Issue

### ISSUE THREAD

**Issue by jgajnak** [hankinsoft/SQLPro#646]
I noticed that my SQLPro Studio build has updated to 2021.53, but when I check the [release notes URL](https://www.sqlprostudio.com/releasenotes/) I only see up to 2021.14.

Is there a problem with updating the release notes, or am I just seeing an oddity of the release process?

**Comment by hankinsoft** [comment]
Sorry, this is my bad. I've been slack on updating the website release notes. I'll get them updated and post a note here once done.

**Comment by hankinsoft** [comment]
Release notes have now been updated.
