### ISSUE TITLE
MySQL unknown version

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#647]
Version 2021.56 (Build 110812.5), but I think the issue has been around for a while. Seems to only happen to MySQL 8.

App says the correct version, but quitting and restarting it says "MySQL unknown version" and refresh doesn't fix it.

How to replicate:
1. Connect to a MySQL 8 Database, correct database version will show
2. Quit SQLPro Studio
3. Start SQLPro Studio
4. Connection now says "MySQL unknown version"
5. Right click refresh doesn't fix it

Work around, disconnect and reconnect.

**Comment by hankinsoft** [comment]
I think I have this fixed for the next build. I had trouble reproducing, but I believe I see what's going on and have resolved it. Once its available, I'll check in and see if you continue to reproduce it or not.

**Comment by poorlymac** [comment]
Thanks Kyle, I will test when it comes out. And if it recurs I will try and narrow down the conditions and check the logs

**Comment by poorlymac** [comment]
Hi Kyle, thanks! It is working now, please feel free to close this ticket
