### ISSUE TITLE
Column output incomplete

### ISSUE THREAD

**Issue by YvesR** [hankinsoft/SQLPro#648]
I do not know why but it seems that this particular SQL Statement cut off the output.

```
SELECT COLUMN_NAME, *
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE OBJECTPROPERTY(OBJECT_ID(CONSTRAINT_SCHEMA + '.' + QUOTENAME(CONSTRAINT_NAME)), 'IsPrimaryKey') = 1
AND TABLE_NAME = 'xinfobasetreeacl' AND TABLE_SCHEMA = 'dbo'
```

<img width="946" alt="screenshot 1" src="https://user-images.githubusercontent.com/4928882/121541811-e6299a00-ca07-11eb-93ad-c80a89560413.png">
<img width="1011" alt="screenshot" src="https://user-images.githubusercontent.com/4928882/121541814-e75ac700-ca07-11eb-9250-79cc473dcda6.png">

**Comment by hankinsoft** [comment]
Hmm, this is very odd. A few questions to help me figure this out:

1. What version of MSSQL are you connecting to?
2. If you do a `SELECT LEN(CONSTRAINT_NAME)` what does that return for a value?

**Comment by hankinsoft** [comment]
3. If you right click on the `dbo.xinfobasetreeacl` in the database tree and do a script as, does it show the constraint name properly, or do you see it cut off as well?

**Comment by YvesR** [comment]
I did retry again to and got now the full name with the same query

```
SELECT COLUMN_NAME, *
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE OBJECTPROPERTY(OBJECT_ID(CONSTRAINT_SCHEMA + '.' + QUOTENAME(CONSTRAINT_NAME)), 'IsPrimaryKey') = 1
AND TABLE_NAME = 'xinfobasetreeacl' AND TABLE_SCHEMA = 'dbo'
```

and the CREATE script returns the correct name also

<img width="1256" alt="screenshot" src="https://user-images.githubusercontent.com/4928882/122405084-0b765500-cf80-11eb-871a-2f1cfb5120fa.png">

**Only difference** There was a `default (null)` constraint on this table I removed, do not know if this might cause the issue.

**Comment by hankinsoft** [comment]
Hmmm ok. I'm going to close the issue for now and if we run into it again I will investigate further. Please let me know if you see odd behaviour such as that again.

**Comment by YvesR** [comment]
@hankinsoft BTW: You do not show default value constraints in the tree, is this planned?

**Comment by hankinsoft** [comment]
> You do not show default value constraints in the tree, is this planned?

Not 100% sure what you mean... Do you mean you would like to see the default value for a column down with the datatype/not null text?

**Comment by YvesR** [comment]
Management Studio:

<img width="219" alt="screenshot 1" src="https://user-images.githubusercontent.com/4928882/122408577-cbfd3800-cf82-11eb-839f-a35a7807c991.png">

SQL Studio:

<img width="305" alt="screenshot" src="https://user-images.githubusercontent.com/4928882/122408584-cc95ce80-cf82-11eb-9419-8ebb0bd71670.png">

**Comment by hankinsoft** [comment]
Ahhhh, I see what you mean. Any chance you would consider adding a new issue for this? It helps me track items and not forget about them :)

**Comment by YvesR** [comment]
Sure, will do.
