### ISSUE TITLE
Feature: Add IntelliSense and code snippets

### ISSUE THREAD

**Issue by zacpwhite** [hankinsoft/SQLPro#65]
Please add an intellisense type feature that detects at least columns in tables and views. Ideally it would also detect input variables and types, as well as outputs from objects, much like SqlPrompt for SSMS. Code snippet functionality would also help quite a bit. For example type `ssf` + Tab, which would expand to `select * from`, again much like SQL Prompt. This functionality could come 
'out of the box' with a predefined set of snippets for common queries, but should also be customizable so that users can create custom snippets.

**Comment by hankinsoft** [comment]
Hi. SQLPro includes both intellisense/autocomcomplete and favourite queries which allow for custom completion snippets. I believe these should cover what you are looking for.
