### ISSUE TITLE
Bug: commented out query causes delete to point to wrong table

### ISSUE THREAD

**Issue by jorrill** [hankinsoft/SQLPro#650]
Given the following code in the query editor:

```
-- (select id from foo where some_col = 'asdf');
select * from bar where some_other_col = 'qwert';
```

Perform the following steps:

1. Execute the `select` query on table `bar`.
2. Highlight some number of rows in the results.
3. Right-click and select "Delete selected rows."

Expected behavior: the app generates the appropriate `delete` statements on table `bar`

Actual behavior: the app generates `delete` statements on table `foo` from the commented out code. (yikes!)

I get the same behavior attempting to update specific cells. The generated SQL references the table in the commented out line, instead of the actual table from the query.

**Comment by hankinsoft** [comment]
Ahhhh, thanks for that. The 'table detection' code was some of the first code I ever wrote for SQLPro and it seems I didn't account for comments. I've got much better SQL parsing code now - I'll get this fixed up for a build this coming week. Appreciate the details you provided.

**Comment by hankinsoft** [comment]
I've got this fixed for the next build which should be available early next week.

**Comment by hankinsoft** [comment]
If you are using SQLPro Studio, the fixed build should now be available. Please let me know if everything is working properly for you.
