### ISSUE TITLE
SQL pro studio app crash after run query

### ISSUE THREAD

**Issue by peethanut** [hankinsoft/SQLPro#651]
The application crash after run query by modifying any statement in ios and ipados

**Comment by hankinsoft** [comment]
What app version are you seeing this with?

**Comment by peethanut** [comment]
> What app version are you seeing this with?

Sqlpro studio V2021.55.74

**Comment by hankinsoft** [comment]
Sorry, I should have posted last night - I was able to reproduce this and am working on the fix. I hope to have it available by tomorrow.

**Comment by peethanut** [comment]
> Sorry, I should have posted last night - I was able to reproduce this and am working on the fix. I hope to have it available by tomorrow.

Noted, thank you. For more information, I'm using IOS 14.5.1

**Comment by hankinsoft** [comment]
Hi - the latest build should be available. If you get the chance, can you check and see if you are still having this crash?

**Comment by peethanut** [comment]
> Hi - the latest build should be available. If you get the chance, can you check and see if you are still having this crash?

It works now. Thanks a lot.
