### ISSUE TITLE
Cannot add records

### ISSUE THREAD

**Issue by IsleofGough** [hankinsoft/SQLPro#653]
Unlike a half dozen other IOS apps fro Postgres, this app will not allow you to add a new record without writing a insert into sql command. At its price, this omission is surprising.

**Comment by hankinsoft** [comment]
Hi. The iOS version of SQLPro does not current have an insert option (other than writing out the SQL). I'll add it to the backlog, but currently do not have an ETA as to when it will be ready.

**Comment by hankinsoft** [comment]
I was able to get the first implementation of this ready for the next build. From a Table menu, you can now choose 'Insert into'.

![CleanShot 2021-06-16 at 15 05 20](https://user-images.githubusercontent.com/3160528/122270197-6fcbe280-ceb4-11eb-8d8d-52b3f7acb115.gif)

It should be available within the next few days.

**Comment by IsleofGough** [comment]
Thank you. That will be very helpful!

**Comment by hankinsoft** [comment]
This should now be available. If you get the chance, please give it a try and let me know if it sorts this out.

**Comment by IsleofGough** [comment]
Thank you. The second time around Apple gave me a refund, so I cannot try it, but I know that will be important for others.
Best,
Philo

**Comment by hankinsoft** [comment]
No worries. I’ll consider the issue closed.
