### ISSUE TITLE
Have to purchase premium version twice

### ISSUE THREAD

**Issue by IsleofGough** [hankinsoft/SQLPro#654]
After paying Postgres Client Premium version for iPhone, I see that the Mac version requires paying twice (Unlike TablePlus and other apps). No license key is provided through Apple's site when one purchases. This seems stingy.

**Comment by hankinsoft** [comment]
Hi. Apple recently provide the ability to share IAP's for however, they only added support for NEW applications. At that time, SQLPro had already been the in the App Store for ~4 years, which means it did not automatically get the ability to share purchases between iOS and macOS.

Monthly and Yearly subscriptions purchased via the webstore can be used by iOS, macOS and Windows. Unfortunately, lifetime purchases are single platform only. As an independent developer, I found that this was the only way to make the product feasible to develop.

If you would like o switch to a webstore purchase, I would suggest reaching out to Apple and requesting a refund. You can additionally save 10% on the webstore purchase with the promo code `S10`.
