### ISSUE TITLE
Request: Snowflake: Add `PARTITION BY` and `FIRST_VALUE` as recognized keywords

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#655]
Neither `PARTITION BY` nor `FIRST_VALUE` are colorized nor suggested from autocomplete. It'd be nice to have all [window functions](https://docs.snowflake.com/en/sql-reference/functions-analytic.html) and [aggregate functions](https://docs.snowflake.com/en/sql-reference/functions-aggregation.html) added to both.

**Comment by hankinsoft** [comment]
I parsed those two pages and have added all of the functions to the [Snowflake functions resource file](https://github.com/hankinsoft/SQLPro/blob/master/sql/SnowflakeFunctions.json). They should all be available for the next build. I haven't had a chance to get to the autocomplete descriptions yet.

**Comment by jim256** [comment]
Could we also add DATE_TRUNC ?

**Comment by hankinsoft** [comment]
Sure, I’ll parse https://docs.snowflake.com/en/sql-reference/functions-all.html and add them all in.

**Comment by hankinsoft** [comment]
Added for the next build. Should be available later this week or early next.

**Comment by jim256** [comment]
For what it's worth, I noticed that `PARTITION BY` is not suggested nor recognized (though `FIRST_VALUE` is). I recognize that it isn't in that doc you linked, so I'm not sure if you were already aware or not.

**Comment by hankinsoft** [comment]
Should be fixed in the latest build (2021.70). Please let me know if you get the chance.

**Comment by jim256** [comment]
I'm not getting `PARTITION BY` suggested nor colorized. Just `BY` is colorized.
I also noticed that `OVER` is not suggested nor colorized.

SQLPro Studio 2021.70 (Build 110827.5)
macOS 11.5.1 (20G80)
Snowflake 5.30.2

**Comment by hankinsoft** [comment]
Could you send me an example query including your partition by and over? (Email is fine if you don't want to post it here). I'm getting both coloured and suggestions, HOWERVER there is some custom logic around the suggestion of keywords, so I'm guessing its something to do with that.

**Comment by jim256** [comment]
Here is one without colorization nor suggestion:
```
SELECT
	FIRST_VALUE(prd.ID) OVER(PARTITION BY prd.PRICE)

FROM
	PRODUCTS prd
;
```

<img width="498" alt="image" src="https://user-images.githubusercontent.com/15026225/128412458-cd6e98e3-fdb8-4522-84d6-37469d0b18d4.png">

[Uploading com.hankinsoft.osx.sqlprostudio 2021-08-05--19-52-42-015.log…]()

**Comment by hankinsoft** [comment]
Fixed for the next build. I'm going to wait a bit to post the next build as I want to try and catch #672.

![CleanShot 2021-08-06 at 10 42 37](https://user-images.githubusercontent.com/3160528/128519546-030e5ecb-f7e8-4895-ae42-47637c5627d7.gif)

**Comment by hankinsoft** [comment]
Just wanted to note that this should be all fixed up as of the latest build. If you get the chance, could you please let me know if you consider this resolved, or if you are still seeing any issues.

**Comment by hankinsoft** [comment]
Going too close. If you happen to find this is not sorted, please let me know.
