### ISSUE TITLE
Add existing constraints from MS SQL data inside tree.

### ISSUE THREAD

**Issue by YvesR** [hankinsoft/SQLPro#656]
As a user I want to see the existing `constraints` of a table in the tree bar similar to MS SQL Management Studio.

Example:

<img width="219" alt="screenshot 1" src="https://user-images.githubusercontent.com/4928882/122409461-74130100-cf83-11eb-8345-9f2aa02c07e1.png">

Current Tree data:

<img width="305" alt="screenshot" src="https://user-images.githubusercontent.com/4928882/122409465-74ab9780-cf83-11eb-93a6-34675362328a.png">

**Comment by hankinsoft** [comment]
The constraints folder basically shows defaults? Does anything else show up here?

**Comment by hankinsoft** [comment]
As far as I can tell, primary keys and indexes DO not show up underneath constraints?

**Comment by YvesR** [comment]
Constraints are additional parameters for the table, e.g. default values.

Example:

<img width="285" alt="Bildschirmfoto 2022-01-13 um 17 22 55" src="https://user-images.githubusercontent.com/4928882/149368622-56d9e6cc-6869-4279-92c9-3644f3667a01.png">

Which is: 
```
ALTER TABLE [dbo].[connector_connections] ADD  DEFAULT (N'') FOR [username]
GO
ALTER TABLE [dbo].[connector_connections] ADD  DEFAULT (N'') FOR [password]
GO
ALTER TABLE [dbo].[connector_connections] ADD  DEFAULT ((0)) FOR [emulate_booleans]
GO
ALTER TABLE [dbo].[connector_connections] ADD  DEFAULT ((0)) FOR [convert_numeric_literals]
GO
ALTER TABLE [dbo].[connector_connections] ADD  DEFAULT ((0)) FOR [trace]
GO
ALTER TABLE [dbo].[connector_connections] ADD  DEFAULT (N'odbc') FOR [driver]
GO
ALTER TABLE [dbo].[connector_connections] ADD  DEFAULT (N'UTF-8') FOR [charset]
```

**Comment by hankinsoft** [comment]
Something like this work:
<img width="495" alt="Screen Shot 2022-01-13 at 4 02 04 PM" src="https://user-images.githubusercontent.com/3160528/149401034-6dd423a3-335f-4399-b2a5-f006b17a9f66.png">

With 'right click' -> 'script as' showing the 'ALTER TABLE xxx ADD DEFAULT xxx'?

**Comment by YvesR** [comment]
Why I do not see this then on my installation?

**Comment by hankinsoft** [comment]
Sorry, I should have been specific --- I'm in the process of adding this and am just requesting feedback to make sure I'm on the right path and what I'm doing is what you want. It sounds like it is, so I'm expecting to have this finished up and available in the App Store within a few days.

**Comment by hankinsoft** [comment]
Latest build 2022.5 should now include these. Please let me know if they work as expected.

**Comment by YvesR** [comment]
Just updated app from store. See my constraints now. Thanks.
