### ISSUE TITLE
SQL Pro for IOS

### ISSUE THREAD

**Issue by IsleofGough** [hankinsoft/SQLPro#658]
I purchased the lifetime version of SQL Pro for Postgres for Mac. I had thought that would allow me to use the IOS version. Do I have to pay for that version separately?

**Comment by hankinsoft** [comment]
Hi,
As mentioned on #654 `Monthly and Yearly subscriptions purchased via the webstore can be used by iOS, macOS and Windows. Unfortunately, lifetime purchases are single platform only. As an independent developer, I found that this was the only way to make the product feasible to develop.`

Please let me know if you would like the lifetime purchase refunded and I can go ahead and do so.

**Comment by IsleofGough** [comment]
Yes, please refund. I have a few other good front ends for the Mac but never could find an app that works well for iOS.
Best,
Philo

**Comment by IsleofGough** [comment]
Thanks for the refund. If you decide to offer a lifetime purchase on just an IOS version, I would be interested. 
Respectfully,
Philo

**Comment by hankinsoft** [comment]
Refunds has been processed. If you decided to re-purchase the subscription, you can use promo code S10 to save 10%. If you are a student, you can request a free year at the link here: https://www.sqlprostudio.com/edu/ (it is SQLPro Studio rather than SQLPro for Postgres).

**Comment by IsleofGough** [comment]
Is there a way of purchasing the IOS version directly from you rather than through the Apple IOS store?
Thanks.
Philo

**Comment by hankinsoft** [comment]
> Is there a way of purchasing the IOS version directly from you rather than through the Apple IOS store?

Not currently for Lifetime. I have another user requesting this as well and I have been working on adding that as an option. I'm hoping to have it available within ~2 weeks, hopefully sooner.

**Comment by IsleofGough** [comment]
Great!!

**Comment by hankinsoft** [comment]
Hi again - I just got notified of two one star reviews which I think might have been you - I completely understand the issue with the price. I wanted to offer a one year subscription promo code (for iOS, macOS and Windows) at which point you can switch to lifetime should you wish. With the hopes that if you enjoy the app, you consider increasing the review. If you are interested, you can use the promo code `IsleofGough` at https://www.macpostgresclient.com/price.html. It is an auto-renewing subscription, but you can turn that off at any point. The initial purchase email will include the details to turn it off.

**Comment by IsleofGough** [comment]
Hi. I changed my review yesterday to three star based on the ability to insert records. If it works on the IOS version, I will change it to five star. Thanks.

**Comment by IsleofGough** [comment]
I clicked the link and completed the purchase and again it looks like it is just for Mac. Did I click the wrong link?

**Comment by hankinsoft** [comment]
Sorry, I should have been more clear - as a one year promo code, you have to choose the 'Yearly' subscription and enter `IsleofGough` as the promo code, such as:

<img width="846" alt="Screen_Shot_2021-06-19_at_5_42_27_PM" src="https://user-images.githubusercontent.com/3160528/122655045-e4598800-d125-11eb-8a03-5553d262fb12.png">

The iOS app does not yet handle lifetime codes, so the free one year has to be done through the yearly code.

**Comment by hankinsoft** [comment]
(I refused the yearly purchase - You should receive an email from fast spring shortly).

**Comment by hankinsoft** [comment]
Looks like that second one went through. You should be able to use that license key (beginning with S2) in the iOS app. If you run into any problems or issues, please let me know.

**Comment by IsleofGough** [comment]
Thank you for that license. I tried it and it works. I can send you the lifetime charge through PayPal if you like or wait until you have the lifetime available for purchase. I changed my review to five star.
/r
Philo

**Comment by IsleofGough** [comment]
I tried inserting and updating real data from a remote server and your program was the easiest to use. Thank you.

**Comment by hankinsoft** [comment]
> I tried inserting and updating real data from a remote server and your program was the easiest to use. Thank you.

Awesome, glad you are find it helpful.

> I can send you the lifetime charge through PayPal if you like or wait until you have the lifetime available for purchase.

Let's worry about this once your years subscription is nearing expiration.

>  I changed my review to five star.

Awesome, I very much appreciate this. As an independent developer, ratings and reviews are extremely helpful.

Lastly, I just found a few emails from you in my spam folder. I have marked these as 'not spam' so any additional emails you send should come though - that said GitHub is the preferred route for issues as it ensures items do not get forgotten about over time.

If you run into any other suggestions or issues, please let me know.

**Comment by IsleofGough** [comment]
Do you have a lifetime price for the iOS version? Thanks
Philo Calhoun

**Comment by hankinsoft** [comment]
In the end, I've decided not to add a lifetime (iOS) version via the website. Lifetime is only going to be offered via the app itself. To purchase lifetime license via the app:

1. Open settings
2. In the 'usage' section, the top item 'SQLPro Basic', choose Upgrade.
3. Choose the 'One time payment' option from the bottom of the list (under yearly and monthly).

If I receive more requests for adding a lifetime purchase option via the website, I will again take a look into it, but unfortunatley the low volume of requests for it does not justify adding it.

**Comment by knd775** [comment]
> In the end, I've decided not to add a lifetime (iOS) version via the website. Lifetime is only going to be offered via the app itself. To purchase lifetime license via the app:
> 
> 
> 
> 1. Open settings
> 
> 2. In the 'usage' section, the top item 'SQLPro Basic', choose Upgrade.
> 
> 3. Choose the 'One time payment' option from the bottom of the list (under yearly and monthly).
> 
> 
> 
> If I receive more requests for adding a lifetime purchase option via the website, I will again take a look into it, but unfortunatley the low volume of requests for it does not justify adding it.

I'd really appreciate the ability to make a lifetime purchase for the iOS version via the website. My reason is that'd I'd like to use my work card instead of my personal Apple account.
