### ISSUE TITLE
Filtering "is null" excludes all records not just records with not null entries.

### ISSUE THREAD

**Issue by DaveKT** [hankinsoft/SQLPro#659]
Steps to reproduce.

Select from a table that has some records with null values.
Enable Filtering
Filter where column is null (for a column that has null entries)
-> ALL Records are filtered out, even those with no nulls

Note: is not null filtering works as expected.

https://user-images.githubusercontent.com/16257495/122831145-4a691b00-d29e-11eb-9d95-9eb18306a3c7.mov

**Comment by hankinsoft** [comment]
Reproduced and working on a fix. Thanks for including the video.

**Comment by hankinsoft** [comment]
Fixed for the next build:

![CleanShot 2021-06-22 at 09 33 03](https://user-images.githubusercontent.com/3160528/122925150-f06b6280-d33c-11eb-880e-4066dd142178.gif)

Will be available late this week or early next.

**Comment by DaveKT** [comment]
Great! Thank you!!

**Comment by hankinsoft** [comment]
Hi, just wanted to confirm that this fix works for you as expected?

**Comment by DaveKT** [comment]
Works perfectly! Thank you! Would you like me to comment on or close the ticket?

**Comment by hankinsoft** [comment]
Just wanted to make sure it was working as expected. Also if you get a moment and find you are enjoying SQLPro please consider leaving a rating or review on the App Store. As an independent developer they help me out a ton.
