### ISSUE TITLE
Incorrect query format when updating

### ISSUE THREAD

**Issue by mlmajor** [hankinsoft/SQLPro#66]
I am trying to update a datetime field and I am getting this error:

Msg 102, Level 15, State 1.
Incorrect syntax near '20'.

I went into the log file and this the information that goes with that error:
2017/01/10 10:37:48:839  Resultset update query is:
SET QUOTED_IDENTIFIER OFF
UPDATE
	archive_data_set_all
SET
	ads_release_date = '2017-01-06 20:20:00:000'
WHERE
	ads_data_set_name = 'JD8B01OQQ' AND ads_archive_class = 'PVW' AND ads_generation_date = 2016-10-27 20:00:45 +0000 AND ads_mission = 'HST'
2017/01/10 10:37:48:839  executeQueryDetails (1 queries).
2017/01/10 10:37:48:863  Query failure, retcode was: 0
2017/01/10 10:37:48:863  Error executing command: Msg 102, Level 15, State 1.
Incorrect syntax near '20'..

The query is incorrect.  The quotes are missing on the value of the ads_generation_date.

Let me know if you need more information.

MLMajor

**Comment by hankinsoft** [comment]
Hi,
Very sorry for the delay on this. I have the issue sorted if you are interested in trying a build out? If so, please let me know and I can provide a download link.
