### ISSUE TITLE
Export Query Results to CSV Nothing Happens

### ISSUE THREAD

**Issue by stephanieherndon** [hankinsoft/SQLPro#660]
I'm using SQLPro for MySQL on a mac and I'm trying to export my query results. When I click on CSV nothing happens. There are no download settings in preferences and I need to export my data to use it. This seems like basic functionality so I'm not sure if I'm missing something.

**Comment by hankinsoft** [comment]
Hi. Try rebooting macOS. I’ve seen this happen a few times in the past (the save panel should be appearing when you choose CSV). Rebooting macOS in those instances has been the only solution.

**Comment by stephanieherndon** [comment]
That did it! Thank you :)
