### ISSUE TITLE
Feature Request: Double clicking a table change from SELECT * to SELECT column names

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#662]
Hi Kyle,

Currently when you double click on a table in SQL Pro it opens a new tab with the select like this:
SELECT * FROM table_name LIMIT 1000;

About half of the time I find I am then using this to filtering it down to the columns I want to construct an SQL for my use case which then involves typing or drag dropping each column name. What I am suggesting is that it instead lists the columns so that we have them there to more easily edit if we wish e.g.
SELECT column1, column2, \`column a\`, \`column b\` FROM table_name LIMIT 1000;

I guess also this may not suit everyone, or a 'wide' table may be annoying, so could be accomplished by something like
- A check box preference 'List columns when creating Select'
- Holding down a meta key e.g. Option when double clicking makes it do the list columns method

n.b. I would kind of like both those myself so I  would check the preference and hold Option when I wanted * instead

CHEERS
Paul

**Comment by hankinsoft** [comment]
Hi Paul,
I like the idea of holding down option when double clicking to add the columns. I'll take a look at getting it added for an upcoming build.

**Comment by jim256** [comment]
I'd also really like this. I currently use "Script As", and then multiple cursors to achieve the same thing in a cumbersome manner. This would be nice.

**Comment by poorlymac** [comment]
Hi Kyle works beautifully thank you, will save me a lot of time every day.

Minor sub request for your consideration put a return before the FROM clause, this is because I will often edit the LIMIT number, or add add a "schema name." to the table and if it is right below I don't have to scroll across to the right and put it in myself.

**Comment by hankinsoft** [comment]
> Minor sub request for your consideration put a return before the FROM clause, this is because I will often edit the LIMIT number, or add add a "schema name." to the table and if it is right below I don't have to scroll across to the right and put it in myself.

Sure, I can add some formatting to this. I might take it a step further and do:

```
SELECT
    column1,
    column2
FROM
    myTable
LIMIT 1000
```

(I plan on running it through the query formatter, so it should be the same output as a right click, format query).

What do you mean by `or add add a "schema name." to the table` --- this should already include the schema name? Are you not seeing it included?

**Comment by poorlymac** [comment]
Hi Kyle,

That's perfect, thanks.

What I mean is table_schema.table_name, e.g. SELECT * FROM schema1.myTable LIMIT 1000, why I need to do this is that at my work we have 100 schemas all the same structure servicing different customers so rather than flicking across to the different schema I will write the schema name and rerun the query. Also sometimes I am joining across schemas e.g. SELECT * FROM mainschema.services m, schema1.services o WHERE m.id = o.id.

As an aside, and nothing I think of we can do with SQLPro I can run a query whilst connected to schema1 that is SELECT * FROM schema2.services then do a data edit and stuff things up :-P , I just need to be careful. n.b. This is also why I don't suggest the schema name should be added to the auto query.

This makes me think of another helpful thing you could consider/think about, automatic table alias. As you see above it's a common habit to alias a table name with 1 or 2 characters to save typing/improve readability e.g. SELECT * FROM contacts, titles WHERE contacts.title_id = titles.title_id to the easier/quicker SELECT * FROM contacts c, titles t WHERE c.title_id = t.title_id. I think in about 80% of cases auto aliasing the first character would be enough, 2 characters might cover 98% of cases usually. Just a thought for your consideration. (call me scope creep ;-))

Cheers
Paul

**Comment by hankinsoft** [comment]
Thanks for the explanation. Per the auto-aliasing, I'm not sure if thats something I want to add as I'm not sure how many user would use it.

FYI the latest build should be available which now formats the select query automatically. Please let me know if that sorts this out.

**Comment by poorlymac** [comment]
Fair enough !

I can confirm Version 2021.68 (Build 110825.5) works perfectly, and is 100% awesome, thanks again for implementing this for us.

**Comment by jim256** [comment]
@hankinsoft , this is great!
I noticed that if there's a column named "DATE" in a Snowflake table, it will be placed in the query editor as "Date" (title case rather than upper case), even though all other columns have the proper case.
