### ISSUE TITLE
Subquery Joins and Aliases/Auto-Complete

### ISSUE THREAD

**Issue by andyoneal** [hankinsoft/SQLPro#663]
SQLPro Studio 2021.68 from the App Store. macOS 11.4.

It seems like subqueries are not being handled correctly for alias formatting and auto-complete. See example attached.

The alias defined within the subquery (ct_1) is formatted correctly and auto-complete works fine within the subquery. However, that alias is also formatted and auto-completes **outside** of the subquery, where it should not be accessible.

The alias given to the table created by the subquery (ct) is not formatted correctly and does not auto-complete when used in the select or where clauses.

[example_subquery.txt](https://github.com/hankinsoft/SQLPro/files/6824596/example_subquery.txt)

**Comment by hankinsoft** [comment]
I believe this is sorted in the latest build. If you get the chance could you let me know? If your still seeing it, could you post a screenshot of what your seeing?
