### ISSUE TITLE
App Store Pricing Question

### ISSUE THREAD

**Issue by LemonsterOG** [hankinsoft/SQLPro#664]
I downloaded the 7-day free trial version from the App Store, because I saw it included a Premium Lifetime price of $129.99, but when I opened the app for the first time I was presented with only one option. Free for 7 days, then $69.99 per year. Can I change to the lifetime price afterwards?

![Screen Shot 2021-07-17 at 12 36 03 PM](https://user-images.githubusercontent.com/57635629/126043736-3a484fc9-0bcb-47aa-9343-27cbad6c57ec.jpg)

![Screen Shot 2021-07-17 at 12 36 24 PM](https://user-images.githubusercontent.com/57635629/126043740-3157fb8d-1f35-463c-a3e6-92eb0a718043.jpg)

**Comment by hankinsoft** [comment]
You can find lifetime by:

1. Closing that dialog
2. Creating your own MySQL connection.
3. Connecting to it and running a query.
4. Clicking activate on the overlay that appears over your results.

You could also purchase via the website and use the promo code S10 to save
10% (
https://www.mysqlui.com/price.php).

Please remember that lifetime purchases as well as any purchase made on the
store purchase are single platform only.

**Comment by LemonsterOG** [comment]
I'll purchase from the website. Thanks SO MUCH for the info and link.

**Comment by hankinsoft** [comment]
I saw you purchase both MySQL and Studio. Did you want me to refund the MySQL purchase?

**Comment by LemonsterOG** [comment]
Yes, please. It was my mistake. Thank you so much for all your help.
