### ISSUE TITLE
Reconnect to Snowflake not working

### ISSUE THREAD

**Issue by MYRepoMan** [hankinsoft/SQLPro#667]
Snowflake connection times out and reconnect option doesn't work. Is there something easier than disconnect/connect and select schema every time?

**Comment by hankinsoft** [comment]
What error do you get when this happens? Could I get a screenshot and/or
copy/paste of the error message?

**Comment by MYRepoMan** [comment]
Below is the error message with no change to my connection. Only way to resolve this is to disconnect/connect and select the db again. This only seems to happen to my Snowflake connection. 

Initializing connection...
Connection ready. Took 0.026 seconds.

Request returned as being unsuccessful 0.421 seconds. (Line 1).

Finished. Total time: 0.448 seconds.

**Comment by hankinsoft** [comment]
This should be sorted as of the latest versions. If you are still seeing it, please let me know.

**Comment by hankinsoft** [comment]
If you continue to see this, please let me know.
