### ISSUE TITLE
Feature Request: Alphabetic sort for schema names

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#668]
As of a couple of versions ago, it seems that schemas are no longer sorted alphabetically in the explorer pane.

For example, "BUSINESS_INTELLIGENCE" will come after "PUBLIC".

SQLPro Studio 2021.68
Snowflake 5.29.1
macOS 11.5.1 (20G80)

**Comment by hankinsoft** [comment]
Should be fixed in the latest build (2021.70). Please let me know if you get the chance.

**Comment by jim256** [comment]
Oops. Somehow missed this. It was fixed. Thanks!
