### ISSUE TITLE
SQLPro Studio - Invalid SQL generated when updating columns in a table

### ISSUE THREAD

**Issue by beerlington** [hankinsoft/SQLPro#671]
App Version 2021.69 (Build 110826.5)

I started seeing this issue after updating yesterday through the app store. When I run a query like `select * from stores;` and then try to edit a column in the result set, I get an error due to invalid SQL. When I click "Preview and Apply", I can see that the sql it's generating is invalid:

![Screen Shot 2021-08-05 at 10 28 18 AM](https://user-images.githubusercontent.com/77580/128367460-7e3f58af-37fd-4b72-8bcb-051236497e53.png)

I do this action almost daily, so it seems like an issue that was introduced with the latest version.

**Comment by hankinsoft** [comment]
Thank you - I've reproduce and have submitted a fix. As a workaround until it's available, if your table specific the full path ex: myschema.mytable rather than just mytable that should get you going for the moment.

**Comment by beerlington** [comment]
Great, thank you!

**Comment by beerlington** [comment]
I got the update today and it's working great. Thanks for the quick turn around!

**Comment by hankinsoft** [comment]
Awesome, thanks for letting me know. Apologies for the issue to begin with.
FYI if you are enjoying the app please consider leaving a rating or review
on the App Store. As an independent developer they help me out a ton.
