### ISSUE TITLE
Crash when comparing databases

### ISSUE THREAD

**Issue by chrisperkins** [hankinsoft/SQLPro#673]
Attempting to compare databases results in a crash immediately after the comparison window displays. Crash report attached:
[SQLPro crash when comparing databases.txt](https://github.com/hankinsoft/SQLPro/files/6942420/SQLPro.crash.when.comparing.databases.txt)

**Comment by hankinsoft** [comment]
Thank you - I've reproduced and am submitting a fix to the App Store now.

**Comment by hankinsoft** [comment]
Hi - Just wanted to check in and see if the updated build sorted the issue you were seeing?

**Comment by chrisperkins** [comment]
Hi Kyle-

I just tried to download it to test and the link on your site is still pointing to the 3/22/21 build; I have the version/license for the non-AppStore version, 2021.27 (4229), purchased back in 2016.

Thanks for checking back, this is truly outstanding product support!

Chris

**Comment by hankinsoft** [comment]
Ohhhh, sorry about that - I'll be push a new website version update hopefully tomorrow (also FYI, the license key you have will also work on the App Store version).

**Comment by chrisperkins** [comment]
I Didn't know that, I'll just grab it from the AppStore and get right back to you.

**Comment by hankinsoft** [comment]
Ahhhh my bad. I deal with my other product that use free download + IAP and forgot SQLite was an upfront purchase.

I've pushed an updated website build which can be downloaded at:
https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2021.72.app.zip

That should sort the crashing issue. Apologies for the delay.

**Comment by chrisperkins** [comment]
No need to apologize; the update has fixed the crash and database comparison works perfectly, thanks!

**Comment by hankinsoft** [comment]
Awesome. I'm going to close the issue. If you run into anything else, please let me know.
