### ISSUE TITLE
Feature Request: Split Query Editor Windows

### ISSUE THREAD

**Issue by mkormendy** [hankinsoft/SQLPro#674]
Currently if I want to see two queries side-by-side I have to have two windows open and then let the OS handle the window arrangement. This isn't a deal-breaker, but it might be nice to have tab frames that you could split into two vertical query editor windows to compare query code against.

**Comment by gitjoost** [comment]
Not sure if this is the same/similar; I often work on multiple tables within a database and would really like to have the ability to create a 2nd (3rd etc..) view of the database which would give me the ability to view/edit the data table and also run queries side by side.
