### ISSUE TITLE
Missing Views from schema

### ISSUE THREAD

**Issue by luisfscosta** [hankinsoft/SQLPro#676]
Recently left a message in the app store which you responded and guided me here. I'm using it to connect to a Postgresql database in RDS. I have two schemas: "public" and "analysis". I can see views in my 'public' schema but not the 'analysis' schema. I can see tables in both schemas.
Also, under Functions, I see both schemas but every function gives me the "-- Failed to load query with no error. (Empty result)" message. This is why I mentioned 'Functions don't work'.

**Comment by hankinsoft** [comment]
Hi - I'm investigating the view issue now. For the functions, I was actually sorting this for another customer and the build is available on the App Store as of ~7 hours ago. If you get the chance, could you upgrade and confirm if functions are working for you now? I hope to have the views fixed by tomorrow.

**Comment by luisfscosta** [comment]
I have applied the update and the issue with the functions has been rectified. I can now see both of my schemas with their respective functions. Thank you for your excellent support with this.
Once the other issue with the views not showing other schemas is sorted out, please send me a note and I will update.

**Comment by hankinsoft** [comment]
Hi - if you get the chance, could you check the latest build and see if that helps sort the issue with views?

**Comment by luisfscosta** [comment]
Hi, I did check the latest build on my phone and tablet and it is working again. I can now see my other schema under views. Thank you for the excellent support.

**Comment by hankinsoft** [comment]
Awesome, thanks for letting me know. I’m going to close this issue. If you get the chance, please consider updating your review on the app store - as an independent developer, these help me out a ton.
