### ISSUE TITLE
New DB connection issue 

### ISSUE THREAD

**Issue by chaseblackmore** [hankinsoft/SQLPro#678]
Hi -
A user of ours  (Mac OS Big Sur) is having an issue with SQLPro, specifically when trying to create a new connection. We go to connect, type in the DB info, and click Save and the software crashes. I have also tried this on my Win10 PC and am running into the same issue of it crashing after making a new connection. We have tried uninstalling and reinstalling as well. Working with Version 2021.30

Please let me know what other info I can provide.

**Comment by hankinsoft** [comment]
Hi,
I'm trying to reproduce the issue. A few questions:

1. What type of connecting are you trying to make (mysql, postgres, sql server, etc)?
2. Are you choosing 'Save', or 'Save and Connect' in the edit connection dialog?
3. Does it crash as soon as this dialog is closed, or is it crashing when attempting to connect? (Double clicking the connection)?

**Comment by chaseblackmore** [comment]
Hi,
1. MySql
2. Save. That is the only option when creating a new connection in the Edit Connection menu
3. I click "save", the edit connection menu closes, and the app crashes. One of our users on Mac is working fine for creating new connections

**Comment by hankinsoft** [comment]
If I send you a new version with additional logging, would you be able to try it out? Also, are you using SQLPro Studio, or SQLPro for MySQL?

**Comment by chaseblackmore** [comment]
Sure. We are using SQLPro Studio

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2021.73.app.zip? I believe it will still crash, but afterwards, could you send me the log file found by going to 'View' -> 'Logs'?

**Comment by chaseblackmore** [comment]
I am not seeing a installer/.exe in that folder you sent to get started. What should I be looking for to run?

**Comment by chaseblackmore** [comment]
Reminder that I am on Windows, not Mac. I see the MacOS folder

**Comment by hankinsoft** [comment]
Sorry, I thought you were using the macOS version. A few more questions then:

1. Are you installed from the Windows App Store, or via the installer?
2. Could you post a screenshot of the about dialog?

Thanks and sorry for the confusion.

**Comment by chaseblackmore** [comment]
I am installed from the Windows App Store. Can you clarify what you mean about dialog?

**Comment by hankinsoft** [comment]
You can ignore that. I might know what's going on. Do you know if you have `FIPS` configured on your system?

**Comment by chaseblackmore** [comment]
I believe so yes

**Comment by chaseblackmore** [comment]
Scratch that response. We are not enforcing FIPS specifically

**Comment by hankinsoft** [comment]
Ok. I see a couple issues going on in the 2021.30 windows build. I'm taking a look into them now. Hope to have a build available for tomorrow.

**Comment by chaseblackmore** [comment]
Ok. Please keep me updated on this. Thanks!

**Comment by hankinsoft** [comment]
I have had the new build approved by Microsoft. I'm not sure how long it will take to be available in the store, but if you refresh updates it might appear already. If you get the chance, could you check and see if build 2021.32 is available and if so, if this fixes the issue?

**Comment by chaseblackmore** [comment]
Hi, let me check with my user that is having issues and get back to you!

**Comment by chaseblackmore** [comment]
Hi, Good to go. Issue resolved and i will close the ticket. Thanks for your quick help!

**Comment by hankinsoft** [comment]
No problem, thanks for letting me know! If your user finds they are enjoying the app, please consider having them leave a rating or review on the App Store. As an independent developer, they help me out a ton.
