### ISSUE TITLE
Move to another mac

### ISSUE THREAD

**Issue by usernamealreadypicked** [hankinsoft/SQLPro#680]
Hi,

I am migrating to another mac, Is possible to migrate Sql Pro there? I have the full unlimited version.

Thanks!

**Comment by hankinsoft** [comment]
Yep, if you purchased a license key just enter it on the new Mac, no
worries. If you’ve purchased via the app store, if you are logged in
through the same iCloud account everything should just work out of box.

**Comment by usernamealreadypicked** [comment]
Yes, I purchased a license key, I will checkout my email, I don't remember how was sent to me , neither were I wrote it.
Thanks for the quick response!

**Comment by usernamealreadypicked** [comment]
(I 've found the email!)
