### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by itadam** [hankinsoft/SQLPro#681]
When will M1 support be added to the Desktop version?

I'm not able to open SQLite databases using SQLPro Studio on my M1 Mac. I have a lifetime license, so using the iOS version does not work for me.

These are the same SQLite databases I created and managed using SQLPro Studio on my old Intel based Mac.

**Comment by hankinsoft** [comment]
> When will M1 support be added to the Desktop version?

Unfortunately I'm stuck waiting on Oracle to release an M1 compatible driver. Everything else has been fully updated and ready to go (all other SQLPro products fully support arm).

> I'm not able to open SQLite databases using SQLPro Studio on my M1 Mac. I have a lifetime license, so using the iOS version does not work for me.

What happens when you open the SQLite database? Do you receive an error? Or no action?

**Comment by itadam** [comment]
> What happens when you open the SQLite database? Do you receive an error? Or no action?
No action. No error is displayed. It just doesn't open it.

**Comment by hankinsoft** [comment]
I'm working on adding some extra logging to try and figure out what's going on here. Are you using SQLPro from the App Store, Website, or Setapp?

**Comment by itadam** [comment]
> I'm working on adding some extra logging to try and figure out what's going on here. Are you using SQLPro from the App Store, Website, or Setapp?

The App Store

**Comment by hankinsoft** [comment]
A new build is available which has extra logging. Can you attempt to open the sqlite file, then choose 'View' -> 'Logs' and send me the resulting log file?

**Comment by itadam** [comment]
> A new build is available which has extra logging. Can you attempt to open the sqlite file, then choose 'View' -> 'Logs' and send me the resulting log file?

It opens the sqlite files successfully now! It seems to be working. Do you still need a log file?

**Comment by hankinsoft** [comment]
Awesome, no log file needed. I had made a small change in addition to logging, but I wasn’t sure if this was going to sort for you or not. Glad to see it works!

if you find your enjoying the app please consider leaving a rating review on the App Store. As an independent developer they help me out a ton.
