### ISSUE TITLE
Cannot create nor view trigger functions through SQLPro

### ISSUE THREAD

**Issue by eddesplaines** [hankinsoft/SQLPro#682]

**Comment by hankinsoft** [comment]
What type of database are you having this issue with?

**Comment by hankinsoft** [comment]
Not enough details, going to close.

**Comment by chuongtrh** [comment]
@hankinsoft  With PostgreSQL, when click to open trigger on the table the app will be crash.

**Comment by hankinsoft** [comment]
Hi @chuongtrh - a few questions to help me figure this out:

1. What version of SQLPro are you using? (Screenshot from the about dialog would be best).
2. What version of postgres are you connecting to? Is it redshift, or any other specific version I should know about?
3. When does the app crash? As soon as you expand the 'triggers' tree node?

**Comment by eddesplaines** [comment]
1. Version 2022.1 (Build 1047848.5)
2. Postgresql 9.6
3. I cannot create trigger functions. There is no option from the gui. I
can do it through straight SQL, though I have to create the sql without any
"helper" wizard.  These are features in the standard PGAdmin. It would be
great if a create trigger function option existed. Not a bug, but a
convenience.

An additional suggestion would be to add a script to "update" type.

**Comment by hankinsoft** [comment]
You can edit a trigger like this:
![CleanShot 2022-01-19 at 08 28 46](https://user-images.githubusercontent.com/3160528/150129664-b762b5d8-a9e7-4f40-b516-e27bd84f2355.gif)

If you want to find the function for a trigger, you can find it in the database tree like this:
![CleanShot 2022-01-19 at 08 30 33](https://user-images.githubusercontent.com/3160528/150129934-519d755c-f2d2-477c-ac19-acb515bc55e1.gif)

Do those help with what your looking for? Or am I miss-understanding? If I am miss-understanding, could you post a screenshot of what your looking for from PGAdmin?

**Comment by eddesplaines** [comment]
Not really. I already knew if I already had a trigger and trigger function,
I can copy the pattern to a new one. I expect to have a general create
query set up as an option in the context menu in the Triggers node, and a
create function to build a trigger function with. I am sure you are
familiar with pgAdmin. They provide this feature. It would be a help if
SQLPro had these options as well as a update query builder option as well
in other context menus. Just a suggestion.
