### ISSUE TITLE
No Updates on Website?

### ISSUE THREAD

**Issue by jgajnak** [hankinsoft/SQLPro#684]
I purchased SQLPro Studio via the website, and have been getting my updates through there. Unfortunately, it looks like the [last version I can download](https://www.sqlprostudio.com/download.php) is 2021.53, and the [Release Notes page](https://www.sqlprostudio.com/releasenotes/) shows the last update as 2021.14. When I look at the Mac App Store, however, the latest version appears to be 2021.75.

Did the site URL change, or is some release engineering automation broken, perhaps?

**Comment by hankinsoft** [comment]
Hi,
I've posted the latest build: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2021.77.app.zip and will have the update notifications set to include this shortly. I will also be fixing the release notes.

**Comment by hankinsoft** [comment]
Release notes have now been updated.
