### ISSUE TITLE
Please add support "require ssl" for mysql connections

### ISSUE THREAD

**Issue by YvesR** [hankinsoft/SQLPro#685]
I am able to connect to a mySQL Server

```
mysql -h <server> -P <port> --ssl-mode=required -u <user> -p <pwd>
```

on my Mac. In this case the connection is encrypted.
If I try to connect the same machine using SQL Studio Pro I get this error message:

![screenshot](https://user-images.githubusercontent.com/4928882/132813734-70d46766-b392-40e6-810a-bb35a43b59c9.png)

In SQL Studio Pro the SSL support needs some certificates which does not fit the requirement.

![screenshot 1](https://user-images.githubusercontent.com/4928882/132813730-e22e1f06-982e-4023-942a-a162c7e67e66.png)

Id like to request the feature to enable this connection with this simple parameter.

Thanks and kind regards, Yves

**Comment by hankinsoft** [comment]
Thanks for the suggestion, I'll take a look into adding this in for the next build.

**Comment by filecage** [comment]
Would be a great addition to the tool for me as well.

**Comment by hankinsoft** [comment]
Once connected (via non SQLPro) are you able to run the query:
> SHOW SESSION STATUS LIKE 'Ssl_version' TLSv1

And let me know what the results of that are?

**Comment by filecage** [comment]
@hankinsoft for sure!

I guess the TLSv1 at the is a mistake, as that is invalid MySQL syntax.
```mysql
SHOW SESSION STATUS LIKE 'ssl_version'
```

While connected to a MySQL 5.7.31 server using SSL, Sequel Pro outputs:
```
Variable_name	Value
Ssl_version	TLSv1
```

**Comment by hankinsoft** [comment]
If you get the chance, could you try this and see if it sorts the issue:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2021.96.app.zip

Or if you still get the same error?

**Comment by YvesR** [comment]
I can verify that this version works for me for mySQL. 
I can also now access MongoDB using BI Connector with this.

**Comment by hankinsoft** [comment]
Great, thanks for letting me know! This build is also available via the Mac app store, so I'm going to go ahead and close the issue.

**Comment by filecage** [comment]
@hankinsoft I think what is missing for this feature to be complete is to actually force an SSL connection with a checkbox somewhere in the SSL connection options. Then it would not only support servers that force the client to use SSL, but also allow opting in to SSL which is a huge benefit.

Would you like me to open up a new issue on this?

**Comment by hankinsoft** [comment]
I'm adding this preference for the next build.

**Comment by hankinsoft** [comment]
This has been added as of the latest build - you can now choose between 'Preferred' (the default'), required or disabled. Please let me know if anyone sees any issues with this, otherwise I will close the issue in a few days.
