### ISSUE TITLE
Feature Request: Sync More in iCloud

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#686]
I've meant to request this before but forgotten. I just switched computers, so now it's fresh again.

It'd be great if your ~~"Favorites" (queries)~~, shortcuts, autocomplete delay, query history, etc. synced between devices (including mobile where applicable).

**Comment by hankinsoft** [comment]
Favourites have been moved to iCloud as of ~January 2022.

**Comment by hankinsoft** [comment]
Preferences syncing can be enabled os of the next build. You will need to enable 'Sync preferences over iCloud' in the preferences on one device to enable it. I will post here once the build is available.

**Comment by hankinsoft** [comment]
Going to close this. The preference has been available for a bit. If anyone runs into any issue with this, please feel free to reopen.
