### ISSUE TITLE
Crash when renaming table

### ISSUE THREAD

**Issue by roguewavelimited** [hankinsoft/SQLPro#687]
Mac version 10.14.6

Created a couple of empty tables.  Tried to rename one from "Sales" to "sales".  The "Renaming Table" box displayed but never went away basically locking up display.  Could still look at app menus etc but none would function.

Had to force quit app from Activity Monitor

**Comment by hankinsoft** [comment]
Hi,
A few questions to figure out what could be going on:

1. Is this reproducible? If you run the same actions, does it happen again?
2. Which version of SQLPro are you using? (Could you post a screenshot of the about dialog)?
3. After seeing this, could you post the log file? You can find it by going to 'View' -> 'Logs'.

**Comment by roguewavelimited** [comment]
Just for clarity: I tried changing the name from "Sales" to "sales" by
changing only the "S" to an "s"

1. Yes, every time.
2. Version 2021.27 (Build 4229)
3.

**Comment by hankinsoft** [comment]
Could you give this build a try: https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2021.78.app.zip?

**Comment by roguewavelimited** [comment]
Same result.

Rick

**Comment by hankinsoft** [comment]
After reproducing this, could you post the log file? You can find it by going to 'View' -> 'Logs'.

(If you tried to send it before, it didn't attach - I don't think you can attach files to GitHub via email response).
