### ISSUE TITLE
Question: is there a way to connect to AWS Athena?

### ISSUE THREAD

**Issue by junghoon-picwell** [hankinsoft/SQLPro#689]
Hi, Kyle. 

I was wondering whether there is a way to connect to AWS Athena using SQLPro Studio. I think it is a hosted Apache Presto service and supports ODBC/JDBC connections. 

Thank you.

**Comment by hankinsoft** [comment]
I've got a few requests for adding additional database types, so I'm creating a 'megathread' where I can keep track of what is being requested the most. I've going to close this issue, but if you could upvote 'AWS Athena' at https://github.com/hankinsoft/SQLPro/issues/833 that would be great!
