### ISSUE TITLE
SQLPro forcing discrete GPU

### ISSUE THREAD

**Issue by mcackay** [hankinsoft/SQLPro#69]
SQLPro seems to force the discrete GPU in my MacBook Pro to be on all the time, draining the battery a lot faster even if SQL Pro is just sitting idle in the background while I do other work.

![screen shot 2017-01-18 at 11 37 00 am](https://cloud.githubusercontent.com/assets/234387/22042999/7b2f3740-dd72-11e6-87ef-b88442a2fae1.png)

I _think_ all that's required to be done is to put this key in the app plist (from http://supermegaultragroovy.com/2016/12/10/auto-graphics-switching/):

`NSSupportsAutomaticGraphicsSwitching  = YES`

Be very much appreciated if this could be supported.

**Comment by hankinsoft** [comment]
Thanks. Which app are you using? I'll post a beta soonish which should help.

**Comment by mcackay** [comment]
Thanks :)  SQLPro Studio

**Comment by hankinsoft** [comment]
Can you try:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.103.app.zip

That should sort it. Please let me know if you have any issues.

**Comment by mcackay** [comment]
Seems to have fixed it, thanks!
