### ISSUE TITLE
MySQL cleartext password support

### ISSUE THREAD

**Issue by dlitty** [hankinsoft/SQLPro#693]
Our organization is moving all of our mysql databases over to Active Directory authentication (rather than having to create local mysql user accounts for everyone), and it turns out in order to do this, each client needs to support sending passwords in cleartext (over SSL) instead of hashed passwords.   Apparently this can be done "globally" by setting an environment variable:   setenv LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN 1, however, trying this produces an error that mysql_clear_password.so could not be loaded (followed by access denied).   Ideally, we would need to be able to set this option at a connection level, since, for example, right now all of our test databases have been converted, but not our production databases.

Can this be added as a new option?   Please let me know if you have any questions.

**Comment by hankinsoft** [comment]
Could you try connecting (without LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN set), then connecting again with LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN set and send me the log file? (For security reasons, you might want to email it to me via kyle @ hankinsoft.com, just put a note that its linked to this ticket). cleartext should actually already work automagically.

**Comment by hankinsoft** [comment]
Per email conversation this is now all fixed up. Build is now available via the App Store as well. I think we should be good to close this?

**Comment by dlitty** [comment]
Yes, although I do still need Oracle - you mentioned we can get a standalone (just Oracle) version?

**Comment by hankinsoft** [comment]
Yep - anyone who needs oracle can download it from the App Store. In SQLPro Studio if you try and make a new Oracle connection it will give you a license key you can use and once Oracle adds support for arm64 I will bring it back into SQLPro Studio. Sorry for the inconvenience!

**Comment by dlitty** [comment]
Got it - thanks!

**Comment by dlitty** [comment]
Hello again Kyle - this issue has resurfaced for us - it turned out back then that the plugin on the server had caused stability issues on the mysql server itself, so they reverted it back out again.  Well, fast forward to today, and they are trying it again.  However, setting the environment variable does not seem to make it work, even with choosing the mysql_clear_password option.  Is there something else required?   Or did we perhaps lose support for this somewhere along the way?

**Comment by dlitty** [comment]
Disregard my comment above - the issue I had turned out to be as a result of the instability on the server.  Sorry about that.
