### ISSUE TITLE
No json_extract() function in SQLPro/SQlite/macOS

### ISSUE THREAD

**Issue by cameronelliott** [hankinsoft/SQLPro#694]
Just downloaded a trial, but the json functions don't seem to be compiled-in/enabled,
is there a way to fix this?
Thanks

**Comment by hankinsoft** [comment]
Hi. Could you grab https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2021.86.app.zip and give it a try?

**Comment by hankinsoft** [comment]
Can you grab https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2021.91.app.zip and give it a try?
