### ISSUE TITLE
Request: Universal SQLPro Studio sans Oracle

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#696]
Hi Kyle,

I read M1/ARM64 SQLPro support is stuck due to Oracle support, fair enough. However in my experience from working with/on Oracle (for a couple of decades) they are more than glacial at updating their instant client libraries for anything ... ever. Considering that myself and many users perhaps don't use Oracle could I tempt you to do a Universal side release sans Oracle on M1/ARM64 for us ? I would happily manually manage it as a side release (e.g. as I recently had to do with IntelliJ IDEA CE by having one named IntelliJ IDEA CE ARM64). I ask as I would love to experience the amazing performance M1 has to offer in SQLPro Studio ... not that the Intel emulated performance is bad, its just it is probably much better.

As a side story ages ago I got so sick to death of waiting for Oracle on Mac Instant Client support that I faked the bulk of the instant client API's in our PHP solution and used the PHP Java bridge http://php-java-bridge.sourceforge.net/pjb/ with the readily available Oracle JDBC driver to do the work. The hack was imperceptible in our app but obviously YMMV

Cheers
Paul

**Comment by poorlymac** [comment]
TIL I can run things using Rosetta2 from the command line e.g. arch -x86_64 zsh

**Comment by hankinsoft** [comment]
Can you try:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2021.95a.app.zip

This is the first build without Oracle. I plan on adding a 'Oracle requires SQLPro for Oracle, here is a license key you can use' dialog to replace Oracle for existing users until I can add it directly into Studio again.

**Comment by poorlymac** [comment]
Thank you so much Kyle, I can confirm it is working fine so far, and is MUCH MUCH snappier on the M1, I really appreciate your effort on this.

**Comment by hankinsoft** [comment]
Going to close this as the build is now available via the website and Mac app store.
