### ISSUE TITLE
Feature Request: Copy selected as update

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#698]
Hi Kyle,

We have the super useful "Copy selected as insert", can we please also have "Copy selected as update" ?

Obviously it would need to have a SET for each non-primary key column, and the WHERE would use the table primary key(s).

Cheers
Paul

**Comment by hankinsoft** [comment]
Something like this:

https://user-images.githubusercontent.com/3160528/142010711-17c2bdca-994c-4b2a-8ace-3cb26868f1e6.mp4

?

**Comment by poorlymac** [comment]
Hi Kyle,

That's perfect !

In fact it's even more, and better, than I was thinking of, I love it.

CHEERS
Paul

**Comment by poorlymac** [comment]
Thanks again so much, confirmed working very well in Version 2021.101 (Build 110863.5)

**Comment by hankinsoft** [comment]
Awesome. Closing the issue.
