### ISSUE TITLE
Crash when resizing result area

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#699]
Hi Kyle,

SQLPro studio Version 2021.80 (Build 110841.5), and SQLPro for MySQL, on M1 MacBook Pro with Monterey 12.0.1

Kick off a bunch of queries and resize the result area crashes the app. Little video attached.

CHEERS
Pau

https://user-images.githubusercontent.com/16620846/138827430-86fe3f6f-ed6c-4470-a188-1c98d2019d42.mov

l

**Comment by hankinsoft** [comment]
Are you seeing this all the time? I'm not able to reproduce it.

**Comment by poorlymac** [comment]
I see it 100% of the time, and on both clients, I will share a way to do it but it might rely on having a decent sized database

**Comment by poorlymac** [comment]
I was able to reproduce this on Version 2021.95 (Build 110858) SQLPro Studio, with the following steps using a MySQL database (though I am fairly confident this is not database dependant):

1. Connect to a MySQL server and generate table rebuild and analyse statements using this:
SELECT CONCAT('ALTER TABLE ', table_schema, '.', table_name, ' ENGINE=InnoDB; ANALYZE TABLE ', table_schema, '.', table_name, ';')
FROM information_schema.tables
WHERE engine = 'InnoDB'
AND   table_schema != 'mysql'
AND   table_type = 'BASE TABLE'
ORDER BY data_length+index_length

2. Copy the resulting SQL and paste in a **brand new tab**

3. Select All statements, and click Run Selected

4. Whilst the statements are running attempt to resize the results area and the app will crash

And here is the new finding, if the query window already exists (e.g. if you have run just one of the queries successfully already), the crash does not occur !!!

Also I notice that if you have run a query already the result area is text and doesn't crash when resizing the result area e.g.
Initializing connection...
Connection ready. Took 0.099 seconds.

Statement completed successfully. (0 rows affected). 0.080 seconds. (Line 1).
Statement completed successfully. (1 result). 0.036 seconds. (Line 1).
Statement completed successfully. (0 rows affected). 0.058 seconds. (Line 2).
Statement completed successfully. (1 result). 0.034 seconds. (Line 2).
Statement completed successfully. (0 rows affected). 0.061 seconds. (Line 3).
Statement completed successfully. (1 result). 0.035 seconds. (Line 3).
Statement completed successfully. (0 rows affected). 0.077 seconds. (Line 4).
Statement completed successfully. (1 result). 0.034 seconds. (Line 4).
etc.

But if you haven't run query already the results come as tables with the columns Table, Op, Msg_type, Msg_text, and resizing the result area crashes the app as they are still coming in

**Comment by poorlymac** [comment]
[SQLPro#699.txt](https://github.com/hankinsoft/SQLPro/files/7479961/SQLPro.699.txt)

**Comment by hankinsoft** [comment]
Reproduced. Working on figuring it out now.

**Comment by poorlymac** [comment]
Awesome. Confirmed fixed in SQLPro Studio Version 2021.102 (Build 110865.5).

On a side note I have noticed Cancel Query seems to have recently started not working for me when running a bunch of queries like I do in this example. Has something changed ? I will create a new ticket with some more analysis if you prefer.

**Comment by poorlymac** [comment]
n.b. my hack to stop them running is to quit the app, no biggie but I can't always do that when I have multiple things in flight

**Comment by hankinsoft** [comment]
New ticket would be great - If you could post log files with you run a query then hit cancel, that would be very helpful.
