### ISSUE TITLE
Feature Request: Query Result "Title" Separator

### ISSUE THREAD

**Issue by blak3r** [hankinsoft/SQLPro#701]
As a user, I often write 2-3 related queries, save them to disk and come back to them periodically (month end reporting or a common support issue).

A textual blurb between each result datagrid would: 
1. Allow users to take a screenshot of the result set without needing to explain the first table is x, the second is y.
2. Allow less technical (not SQL Pros) to view a query and understand the difference between them.
3. Be beneficial to SQL Experts  as you wouldn't need to scroll through long queries in the query editor.

I propose adding a `title` syntax in a SQL comment that would allow for something like this: 

![image](https://user-images.githubusercontent.com/1581785/140099074-93e5148c-0092-43c7-a542-1d68389c8bb5.png)

A potential workaround for a user that really needs this would be to do something like `Select 'DSO By Customer ID' as " ";` between the queries, but it looks more like a broken query then documentation.

**Comment by hankinsoft** [comment]
I like the idea, but I'm not 100% sure if its something I'll implement at the moment. I'm not sure many users would use it -- that said if I get more requests for it, I will consider adding it, but for the moment I'm going to mark this as closed without an ETA. Again, if I were to receive enough requests for this I would consider re-opening it.
