### ISSUE TITLE
Issue: MySQL Access denied for user 'root'@'localhost' (using password: YES). (Error #1045)

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#703]
Hi Kyle,

When using SQLPro Studio Version 2021.98 (Build 110860.5) to Local MySQL 8.0.27 running on a M1 on Monterey and I get "Access denied for user 'root'@'localhost' (using password: YES). (Error #1045)" when using the Default authentication Method, it may be related to a MySQL 8.0.27 change but I am not certain. I can connect OK if I change the Authentication Method to **any** of the other methods.

Also I see in the log below from a default connect after it fails it says "MySQL going to connect with Authentication: mysql_old_password." but the failure still occurs and it cannot get in. This is odd since when I change the Authentication Method to mysql_old_password in the UI it does actually successfully log in.

And, as a total aside, if you get a 1045 from MySQL you might alert the user to maybe changing the Authentication Method in the connection to the user.

No other issues connecting to other remote MySQL's 

Cheers
Paul

Log details:
2021/11/17 02:17:47:108  NSApp sendAction: collectionItemViewDoubleClick
2021/11/17 02:17:47:108  collectionItemViewDoubleClick
2021/11/17 02:17:47:108  connectToConnectionId: 4752F4AA-F175-473C-8E49-CA2683456854-2939-00006DABC37BEFF8
2021/11/17 02:17:47:108  connectToRecentConnectionById (not requesting password)
2021/11/17 02:17:47:108  doConnect: localhost (detected port: 0 specified port: 0)
2021/11/17 02:17:47:128  HSDispatchGroup enter com.hankinsoft.connectionWindowDispatchGroup
2021/11/17 02:17:47:128  doConnect calling getHost:andPort:forServer:userSpecifiedPort:
2021/11/17 02:17:47:128  doConnect self->internalDatabaseConnectionDetails createNewClient
2021/11/17 02:17:47:128  doConnect calling databaseClient->connect
2021/11/17 02:17:47:128  mysql:connect using default authentication
2021/11/17 02:17:47:128  MySQL going to connect with Authentication: Default.
2021/11/17 02:17:47:137  MySQL:connect with MySQLAuthenticationMethodDefault failed (Access denied for user 'root'@'localhost' (using password: YES). (Error #1045)). Going to attempt MySQLAuthenticationMethodOldPassword.
2021/11/17 02:17:47:137  mysql:connect using MySQLAuthenticationMethodOldPassword
2021/11/17 02:17:47:137  MySQL going to connect with Authentication: mysql_old_password.
2021/11/17 02:17:47:147  doConnect databaseClient->connect finished
2021/11/17 02:17:47:147  setDBC: connectionId: 4752F4AA-F175-473C-8E49-CA2683456854-2939-00006DABC37BEFF8
2021/11/17 02:17:47:147  checkSSHFingerprintError returning NO
2021/11/17 02:17:47:147  HSMinimumDelay need to wait 0.98 seconds (elapsed was 0.02).
2021/11/17 02:17:48:133  HSMinimumDelay after delay, elapsed is: 1.01 seconds.
2021/11/17 02:17:48:134  SQLProConnectingWindowController endSheetWithReturnCode: OK
2021/11/17 02:17:48:134  HSDispatchGroup leave com.hankinsoft.connectionWindowDispatchGroup
2021/11/17 02:17:48:135  MySQLClient::disconnect settings reconnect = 0
2021/11/17 02:17:48:135  MySQLClient::disconnect begin mysql_close
2021/11/17 02:17:48:135  MySQLClient::disconnect finished mysql_close
2021/11/17 02:17:48:135  Failed to connect with error: Access denied for user 'root'@'localhost' (using password: YES). (Error #1045)
2021/11/17 02:17:48:135  Clearing internal database connection details.
2021/11/17 02:17:48:135  setDBC: nil
2021/11/17 02:17:51:088  Application is resigning activity.

**Comment by hankinsoft** [comment]
Hi. 
Three questions to get me started:

1. Are you specifying 'localhost' or 127.0.0.1 in your connection currently?
2. What happens if you specify the other?
3. This is true localhost - you'r not using an ssh tunnel to connect to the localhost of another system?

Thanks!

**Comment by poorlymac** [comment]
1) I tried both localhost and 127.0.0.1, both fail on Default
2) As per above I had already tried both (I've been around MySQL for too long :-P )
3) This is true localhost not ssh

I am fairly certain it was working on 8.0.26 & all other clients I have work Workbench, Sequel Ace, command line, DBeaver & HeidiSQL. Are you using the MariaDB lib not libmysql perhaps ?

**Comment by hankinsoft** [comment]
What are you using for your local mysql server? I'd like to try setting up the same system - if I can reproduce it, it will be easier for me to figure out.

**Comment by hankinsoft** [comment]
I was able to reproduce. It's related to this: https://github.com/hankinsoft/SQLPro/issues/685 - putting a fix in for next version.

**Comment by poorlymac** [comment]
Awesome ! Local mysql (like almost all of my software) I am managing with brew, so brew install mysql

**Comment by hankinsoft** [comment]
If you switch back to automatic is this working as of the latest build?

**Comment by poorlymac** [comment]
Yes it is thank you !

**Comment by hankinsoft** [comment]
You mentioned seeing this again? Could you reproduce, then send me a log file? (kyle@hankinsoft.com) -> I'm not able to reproduce it using my localhost connection.

**Comment by poorlymac** [comment]
Fixed again in Version 2021.104 (Build 110868.5)!
