### ISSUE TITLE
Crashes whenever attempts to connect to postgres db

### ISSUE THREAD

**Issue by quinceleaf** [hankinsoft/SQLPro#704]
Love SQLPro. Been using SQLPro Studio without issue for months. 

Just switched machines, and the new installation crashes whenever I attempt to connect to a remote postgres db (tried several). To try to bound the problem, I established that there is no problem using it on new machine to open sqlite3 files.

Can still connect to these remote dbs on the previous machine using SQLPro Studio, no issue

- On both machines SQLPro Studio was installed via Setapp, in case that matters.
- Both machines running macOS Catalina 10.15.7

Any advice would be useful.

[crash-report.txt](https://github.com/hankinsoft/SQLPro/files/7565651/crash-report.txt)

**Comment by halindrome** [comment]
My machine upgraded itself today, and now it crashes whenever I try to open a connection to any of my mariadb instances (local and remote).  It was working perfectly.  My installation also comes in via Setapp.  I am running macOS Big Sure 11.6.1

**Comment by levinhtxbt** [comment]
I have the same problem with MSSQL.

**Comment by hankinsoft** [comment]
Sorry for the issue! I’ve got a build submitted which will sort it. Usually Setapp is very quick at approving builds so hopefully it’s available tomorrow. Again, sorry for the issue!

**Comment by quinceleaf** [comment]
> Sorry for the issue! I’ve got a build submitted which will sort it. Usually Setapp is very quick at approving builds so hopefully it’s available tomorrow. Again, sorry for the issue!

Thank you, new build resolved it.

**Comment by hankinsoft** [comment]
Thanks for letting me know and sorry for the issue to begin with.
