### ISSUE TITLE
Bug:  Cancel Query not stopping

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#706]
Hi Kyle,

Version 2021.102 (Build 110865.5)

When running a bunch of Queries to MySQL the cancel doesn't cancel, workaround is to quit, see attached little video.

`CREATE TABLE testtable (
  id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
) ENGINE=InnoDB;`

rm -f testtable.sql ;for i in {1..100000..1}
    do
       echo "INSERT INTO test.testtable VALUES ("$i");" >> testtable.sql
 done
open testtable.sql

The log file shown in the video seems to get truncated so the attached log doesn't include the same content.

n.b. Also the Access denied for user 'root'@'localhost' (using password: YES). (Error #1045) seems to have come back in this build

https://user-images.githubusercontent.com/16620846/143536232-5c70575c-5e6b-4eb7-8f5e-86eb39e3b2a6.mp4
[com.hankinsoft.osx.sqlprostudio 2021-11-26--06-10-24-832.log](https://github.com/hankinsoft/SQLPro/files/7606734/com.hankinsoft.osx.sqlprostudio.2021-11-26--06-10-24-832.log)

CHEERS
Paul

**Comment by poorlymac** [comment]
https://user-images.githubusercontent.com/16620846/143672320-7aa43bc9-a4cb-4d78-a2ec-20ef54c4984d.mp4

**Comment by hankinsoft** [comment]
Reproduced and working on a fix. Unrelated question - Would you be interested in testing a build which moves favourites to be stored in the iCloud Drive?

**Comment by poorlymac** [comment]
Hi Kyle, Always happy to test new releases !

**Comment by hankinsoft** [comment]
Per testing the release:

I would like to request that you manually backup favourites before updating (the update also creates a backup, but I like suggesting to having an extra backup).

To create a manual backup, open keychain access and search for: 'FavoriteQueries'
<img width="788" alt="Screen Shot 2021-11-30 at 2 31 03 PM" src="https://user-images.githubusercontent.com/3160528/144233322-705895ed-0ca6-4025-bb2d-3ca31eac9765.png">

Right click and copy to clipboard. Enter your password. Paste the results of this to a file (Its a base64 encoded string).

The new build will automatically create individual sql files either in your iCloud Drive (if iCloud Drive is enabled), or under the SQLPro sandbox documents/favorites path if iCloud Drive is not enabled.

Ideally with this build, you basically just shouldn't notice any difference. Unless you go to another system, using the build, your favourites should exist.

Build is at:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2021.106.app.zip

(This should also fix the mysql cancel issue).

**Comment by poorlymac** [comment]
As I had no queries saved in my favourites I lost the list of connections, see attached screenshot. I fixed it by reverting to 102 saving a favourite and then going back to 106. i.e. I think you have a bug if a person has not favourited a query yet 
![Screen Shot 2021-12-02 at 1 01 17 pm](https://user-images.githubusercontent.com/16620846/144350532-88326f0d-a13c-4bac-b69d-7db6cec4b9e9.png)

**Comment by hankinsoft** [comment]
Thanks for testing that for me!

The cancel issue should be fixed up for the latest build. If you get the chance, can you please give it a try?

**Comment by hankinsoft** [comment]
Marking as fixed. If you are still seeing this, please let me know.
