### ISSUE TITLE
Create Table misses closing )

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#707]
Just created a table where the last field had a Default value of ```GETDATE()```

The generated code missed the closing bracket from the end of the line:

Correct code should be:
```

CREATE TABLE dbo.TableName (
  ITEMNMBR CHAR(21) NOT NULL,
  LOCNCODE CHAR(15) NOT NULL,
  QtyOnHand INT NOT NULL,
  AtyAlloc INT NOT NULL,
  QtyOnOrder INT NOT NULL,
  RowID BIGINT IDENTITY(1,1) NOT NULL,
  CreatedTS DATETIME NOT NULL DEFAULT(GETDATE())
);

ALTER TABLE dbo.Vax_Stock_NightlySnapshot ADD PRIMARY KEY(ITEMNMBR, LOCNCODE);
```

The generated code was:

```
CREATE TABLE dbo.TableName (
  ITEMNMBR CHAR(21) NOT NULL,
  LOCNCODE CHAR(15) NOT NULL,
  QtyOnHand INT NOT NULL,
  AtyAlloc INT NOT NULL,
  QtyOnOrder INT NOT NULL,
  RowID BIGINT IDENTITY(1,1) NOT NULL,
  CreatedTS DATETIME NOT NULL DEFAULT(GETDATE()
);

ALTER TABLE dbo.Vax_Stock_NightlySnapshot ADD PRIMARY KEY(ITEMNMBR, LOCNCODE);
```

**Comment by hankinsoft** [comment]
Thanks, I'll take a look - just to confirm this is SQL Server you are seeing it with?

**Comment by davidharrison92** [comment]
Thanks. 

Sorry, yes this is SQL Server (2014). Using Version 2021.98 (Build 110860)

**Comment by hankinsoft** [comment]
Thanks. Reproduced and fixed for the next build (hopefully early next week - just doing some finishing touches and testing with moving favourites to iCloud Drive).

**Comment by hankinsoft** [comment]
This build is available and this portion should be fixed up.

**Comment by hankinsoft** [comment]
Going to close this. If you see it again, please feel free to re-open.
