### ISSUE TITLE
Crashes on CMD + Shift + F

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#708]
Whenever I try to filter my query results using the keyboard shortcut, the app crashes. If I use the mouse to select the Filter option, it works fine.

Full log file:
[com.hankinsoft.osx.sqlprostudio 2021-11-30--21-20-34-826.log](https://github.com/hankinsoft/SQLPro/files/7628954/com.hankinsoft.osx.sqlprostudio.2021-11-30--21-20-34-826.log)

If I clear out the log file right before I do the command, the only thing in the file after crash is:
```
2021/11/30 21:23:58:307  Application is becoming active.
2021/11/30 21:24:32:835  Main thread has not been responsive for 34.60 seconds.
```

Tried with MySQL 8.0.25 and Snowflake 5.41.1

SQLPro Studio 2021.104 (Build 110868.5)
macOS 11.6 (20G165)

**Comment by hankinsoft** [comment]
Yes, sorry about that I need to get the website version updated. If you download the AppStore version, it already has that fix And your license key will continue to work. I will post the website build tomorrow.

**Comment by jim256** [comment]
FWIW, this is from the App Store, and I checked for updates immediately prior to creating this issue, and it showed that there were none.

**Comment by hankinsoft** [comment]
Hmmm ok. I’ll do some investigating once I get home.

**Comment by hankinsoft** [comment]
Reproduced and fixed for the next build (early next week ETA).

**Comment by jim256** [comment]
FWIW, this still happens with 2021.110 (Build 110874.5)
I use this functionality a ton

**Comment by hankinsoft** [comment]
2021.111 is out - can you let me know if that fixes it? (I was able to reproduce it originally, but then fixed what I was seeing for 2021.110. I've made additional changes along the same line for .111, so I'm hopeful you no longer see the crash).

If you do still see the crash --- could you post a screenshot of your 'keyboard shortcut' preferences? Specifically anything that is non-default.

**Comment by hankinsoft** [comment]
Are you still seeing this as of the latest build?

**Comment by jim256** [comment]
Seems to be fixed! Thank you so much.
