### ISSUE TITLE
Inconsistent DELETE commands

### ISSUE THREAD

**Issue by CarlosNZ** [hankinsoft/SQLPro#709]
When I select a row (or rows) and right-click "Delete selected rows", the SQL command wants to delete by the 'id' field, which is the primary key, so is correct, and the deletion works fine:
<img width="635" alt="Screen Shot 2021-12-01 at 1 30 44 PM" src="https://user-images.githubusercontent.com/5456533/144150570-e67597c3-dbd0-4bfb-9b8a-1472d851847c.png">

However, when I try to do exactly the same thing again, the suggested SQL command wants to match on every single field, like so:
<img width="632" alt="Screen Shot 2021-12-01 at 1 31 12 PM" src="https://user-images.githubusercontent.com/5456533/144150622-adeb9bb4-a9de-4c1c-b378-9ce000195c5f.png">

And then the deletion doesn't actually work, since I assume something doesn't quite match, not sure. 

But the problem is the inconsistent query generation -- it should always do the first case, should it not?

**Comment by hankinsoft** [comment]
Hi - SQLPro does some 'query analysis' to figure out what table you are focusing on and the primary keys, foreign keys, etc. In the first case, it has detected that id is the primary key (you probably see id highlighted in blue in the results grid). The second case, SQLPro has NOT detected id as the primary key and defaults too using a where that includes all available fields.

Was the same query ran for both queries? Such as 'select * from public.review_assignment'? Was there difference clauses used in the were of each? If you happen to notice any difference, would you be able to post?

**Comment by CarlosNZ** [comment]
Yes, as far as I can tell the situation was the same for both. The query to generate the list is just the default one created by double-clicking on the table list in the sidebar: `SELECT * FROM ...`

> In the first case, it has detected that id is the primary key (you probably see id highlighted in blue in the results grid).

Yes, this is correct. What I have found is that with the same query in the editor (default SELECT), when I repeatedly press the "Run all" button to regenerate the list, after a few runs, the list then appears without the primary key highlighted (in blue), and this is when the other DELETE behaviour occurs. Somehow, even with the same query, the primary is not detected after a certain number of runs (seems to be 3, but not sure it's consistent).

This wouldn't be such a problem if it worked properly, but the other DELETE command (with all columns) doesn't actually *work*. It seems to have run, and no errors are reported, but when I re-run the SELECT * query again, the records are still all there.

If it's any help, I'm connecting to a Postgres 12 database.

**Comment by hankinsoft** [comment]
k - so it looks like there are two underlying issues.

1. The primary key is not always being detected after a certain number of re-runs.
2. The delete is not being formatted correctly.

I'm going to try and reproduce item 1 and see what I can come up with. For item 2, could you possibly post the full delete statement you are seeing? I'll take a look at it and see if I can figure out what's up.

**Comment by hankinsoft** [comment]
Reproduced and fixed item 1. Are you using SQLPro Studio, or SQLPro for Postgres? I would like to post a build later today for testing if thats ok.

**Comment by CarlosNZ** [comment]
Thanks. Yes, I'm using SQLPro Studio, downloaded through Setapp (subscription).

As for the 2nd point, I can see the problem -- it's the `NULL` values that are messing it up. The auto generated query is something like:
```
DELETE FROM public."user" WHERE id = 18 AND first_name = 'Admin' AND last_name = 'Admin' AND username = 'admin' AND  date_of_birth = NULL etc...';
```
which doesn't delete anything. The `null` value should be `date_of_birth IS NULL` (tested and works)

**Comment by hankinsoft** [comment]
Ahhhh, that makes sense. I've got this fixed:
<img width="1382" alt="Screen Shot 2021-12-02 at 4 07 17 PM" src="https://user-images.githubusercontent.com/3160528/144495058-07ec26d0-4d72-422d-9c7f-69f634c02970.png">

So I will submit a build to setapp with both items fixed. It should be available sometime tomorrow. I will make a post here once I see that its available.

**Comment by CarlosNZ** [comment]
That's great, much appreciated! :)

**Comment by hankinsoft** [comment]
Sorry forgot to post - the build is available. Can you confirm if you still see this issue?

**Comment by CarlosNZ** [comment]
Yeah, all seems good now. Thanks for the prompt turnaround.
