### ISSUE TITLE
SQLPro Oracle failing to import

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#715]
This is my first time importing a csv using SQLPro Oracle.  I have been using SQLPro Studio successful for years, but am obviously using SQLPro Oracle for the last couple of months since you had to disable the Oracle interface in SQLPro Studio.

This is a simple import of two columns, 8 rows.  
   First Row contains column name
   Column Separator: Auto
   Table: New Table named ETL_COMPOUND_ID_TYPES

I have attached the CSV and log file.

OS: MacOS Catalina 10.15.7
Software: SQLPro Oracle Version 2021.101 (Build 497.5)
Connection: Oracle 19

[com.hankinsoft.osx.sqlpro.oracle 2021-12-20--17-36-08-114 copy.log](https://github.com/hankinsoft/SQLPro/files/7747066/com.hankinsoft.osx.sqlpro.oracle.2021-12-20--17-36-08-114.copy.log)
[COMPOUND_ID_TYPES.20211220.csv](https://github.com/hankinsoft/SQLPro/files/7747067/COMPOUND_ID_TYPES.20211220.csv)

**Comment by cwolcott** [comment]
Any thoughts?

**Comment by hankinsoft** [comment]
Uploading the fix today.

**Comment by cwolcott** [comment]
Confirmed the fix. What ever you did fixed the import issues I was having in SQLPro Oracle.

I assume this was only an issue in SQLPro Oracle and not SQLPro Studio?

**Comment by hankinsoft** [comment]
> I assume this was only an issue in SQLPro Oracle and not SQLPro Studio?

I had broken something with Oracle import recently (no matter which product) at a point when I was refactoring some code. Based on your CSV I was able to see where I broke it and made the fix.
