### ISSUE TITLE
SQLPro for SQLite - add new record doesn't show/select that record

### ISSUE THREAD

**Issue by jmadren** [hankinsoft/SQLPro#717]
Viewing data, click + button to add a record. It jumps to the top of the list instead of to the new record at the end of the list. It seems like it is refreshing the entire table. So I have to scroll back to the end and click in the new record to edit it. Becomes a pain on larger tables (1000+ records).

**Comment by hankinsoft** [comment]
Investigating.

**Comment by hankinsoft** [comment]
I've got a build submitted which should fix this:
![CleanShot 2022-01-06 at 20 02 57](https://user-images.githubusercontent.com/3160528/148557739-a233bbd3-c86c-4c0d-9ace-8964e2fcec97.gif)

**Comment by jmadren** [comment]
Just got the update, and it works as described. Thanks!

One additional tweak would be to put the edit cursor in the first field of the new row, ready for entry. As shown above, after adding the row, you still have to click in it to start typing. Most other similar tools put you directly in editing mode when adding a new row.

**Comment by hankinsoft** [comment]
Sure, that makes sense.

**Comment by hankinsoft** [comment]
Are you using Setapp?

**Comment by jmadren** [comment]
Yes.

**Comment by hankinsoft** [comment]
Perfect - I'm going to push the new build to setapp right away. It takes ~24 hours or so for them to review it.

**Comment by jmadren** [comment]
Downloaded the update. It works as expected, but encountered an error: discarding the new record crashes the app.

**Comment by hankinsoft** [comment]
If you add a row, then discard you see a crash?

**Comment by hankinsoft** [comment]
Reproduced, working on the fix.

**Comment by hankinsoft** [comment]
Build submitted. That will fix the crash on discard when a cell is being edited - should be available in ~24 hours.

**Comment by jmadren** [comment]
Got the update. Works great. Thanks!
