### ISSUE TITLE
SQLPro for SQLite - The Execute button on the toolbar doesn't execute the query

### ISSUE THREAD

**Issue by tsuliwaensis** [hankinsoft/SQLPro#718]
Clicking the Execute button doesn't do anything. I'm running the App Store version on macOS 12.1

**Comment by hankinsoft** [comment]
huh, thats odd. I've reproduced and am working on a fix - as a workaround, use either the 'run all' or keyboard shortcut.

**Comment by hankinsoft** [comment]
The latest build (2022.1) should fix this. If your still running into it, please re-open this issue and let me know.
