### ISSUE TITLE
Stay on active row after edit

### ISSUE THREAD

**Issue by gitjoost** [hankinsoft/SQLPro#719]
SQLPro (Version 2021.110 (Build 4237.5) always refreshes the table display and positions cursor at the top row after editing a record/row. If e.g., I edit row 400 and save the record (data view), rather then keeping that row active and in view, SQLpro refreshes the entire table and positions the cursor at row 1. This means I am scrolling and scrolling and scrolling to get back to the next row to edit.

Can this be fixed please.

**Comment by hankinsoft** [comment]
Investigating. Just to confirm, this is with SQLPro for SQLite?

**Comment by gitjoost** [comment]
Yes, correct

**Comment by hankinsoft** [comment]
I've got a build submitted which should fix this:
![CleanShot 2022-01-06 at 20 02 57](https://user-images.githubusercontent.com/3160528/148557539-6c38b6b2-f126-4e8e-a0bf-c8c63b8dd450.gif)

**Comment by hankinsoft** [comment]
All fixed and the build is available. If you continue to see the issue, please let me know.
