### ISSUE TITLE
Feature Request - SQLPro for SQLite - save pane sizes

### ISSUE THREAD

**Issue by jmadren** [hankinsoft/SQLPro#720]
A nice feature would be to remember the three pane sizes (db tree, query/table pane, results pane) and restore those when opening the app, preferably unique for each db. Currently it always sets each pane size to some default.

Thanks!

**Comment by hankinsoft** [comment]
Going to close this as a copy of #411. Its been requested a few times I just haven't gotten to it yet. I will bump the priority up.
