### ISSUE TITLE
Pollution of ~/Documents folder

### ISSUE THREAD

**Issue by DeLoeribas** [hankinsoft/SQLPro#723]
Because SQLPro stores data in ~/Library/Containers/com.hankinsoft.osx.sqliteprofessional/Data/Documents, this folder is always visible in  ~/Documents.
I want to keep my Documents folder tidy, so it would be great if SQLPro would store this data at another location.

**Comment by hankinsoft** [comment]
Hi. If I receive additional requests for this, I will take a look into adding an option for users to specify the location. For now, I'm going to close the issue, but again if I receive enough requests, I'll add a feature to change it.
