### ISSUE TITLE
SQLPro for SQLite - reload on external changes can cause data column widths to reset

### ISSUE THREAD

**Issue by jmadren** [hankinsoft/SQLPro#724]
Hi again!

If the "Reload database on external changes" is on and the Data view of a table is being displayed, when an external change causes that table to reload, it will reset the column widths, losing the set widths that had been saved.

**Comment by hankinsoft** [comment]
A build has been submitted to setapp.

**Comment by hankinsoft** [comment]
Should be fixed as of the latest setapp build. Please let me know if you are still seeing this.

**Comment by jmadren** [comment]
Just tested it - works correctly now. Thanks!
