### ISSUE TITLE
Oracle Import: CLOB 4000 characters or larger

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#725]
This is the first time I have tried to import into a CLOB column.  I have provided 2 files.

- CLOB.3999.csv contains a string of 3999 characters
- CLOB.4000.csv contains a string of 4000 characters

OS: MacOS Catalina 10.15.7
Software: SQLPro Oracle Version 2022.1 (Build 498.5)
Connection: Oracle 19

I perform **Import > from CSV** _CLOB.3999.csv_ to a new table CLOB_Test and it works perfectly.
![image](https://user-images.githubusercontent.com/3777526/150467216-b2a52ebd-ff31-4343-91d4-8521fc3dd44d.png)

Next I **Import > from CSV** _CLOB.4000.csv_ to the existing table CLOB_Test and I receive and error.
![image](https://user-images.githubusercontent.com/3777526/150467446-5a15cc0b-503d-4e31-a9ba-7ae049041039.png)

I understand that Import from CSV is performing the following (500 records at a time):

```
   INSERT ALL
      INTO ...
      INTO ...
   SELECT 1 FROM DUAL
```
So that is the reason for the issue.

SQL Error: ORA-01704: string literal too long
- **Cause:**    The string literal is longer than 4000 characters.
- **Action:**   Use a string literal of at most 4000 characters.  Longer values may only be entered using bind variables.

Am I not going to be able to use SQL Pro Oracle or Studio to import large CLOB values?
[CLOB.3999.csv](https://github.com/hankinsoft/SQLPro/files/7910493/CLOB.3999.csv)
[CLOB.4000.csv](https://github.com/hankinsoft/SQLPro/files/7910494/CLOB.4000.csv)

**Comment by hankinsoft** [comment]
Submitting a fix. It does:

> INSERT INTO x (column) VALUES(SELECT TO_CLOB('first 3999 chars') || TO_CLOB('next 3999 chars') || etc FROM DUAL)

Should be available tomorrow.

**Comment by cwolcott** [comment]
I will watch for the update and test it out.  My max string going into a CLOB is ~40,000 characters.  Iterating over 215,000 records.

**Comment by cwolcott** [comment]
Attached are two more examples if you need test cases
[CLOB.1record.15995.csv](https://github.com/hankinsoft/SQLPro/files/7916708/CLOB.1record.15995.csv)
[CLOB.3LargeRecords.csv](https://github.com/hankinsoft/SQLPro/files/7916710/CLOB.3LargeRecords.csv)
.

**Comment by hankinsoft** [comment]
Build is available - please let me know if that sorts everything out for you.

**Comment by cwolcott** [comment]
Almost, when you import **CLOB.1record.15995.csv** dataset above it says the import was successful but it only imported the first three 3999 character chunks.  There should be 1 additional chunk to import.

**Comment by cwolcott** [comment]
Ignore the numbers I added to the file name.  Those were the lengths of the column the SQL SERVER was reporting, but when I open in a text file the counts are less.

**Comment by cwolcott** [comment]
> Build is available - please let me know if that sorts everything out for you.

So is this just a looping error.  It looks like the last chuck is not loaded when I import the 3 records from **CLOB.3LargeRecords.csv**.  The last chuck of each mol_file column did not load.

ID	        LENGTH(MOL_FILE)
379147	3999
384898	3999
114896	11997      (Missing last chunk)
132235	23994    (Missing last chunk)
132236	23994    (Missing last chunk)
132502	35991    (Missing last chunk)

**Comment by hankinsoft** [comment]
Ok, I think I see why the last entry is being skipped. Fixing now.

**Comment by hankinsoft** [comment]
Build submitted. I've been testing my results by using a merge tool to compare the contents of the CSV to the results from querying via SQLPro after insert. Everything should be set once you have this build.

**Comment by cwolcott** [comment]
I will watch for it in the AppStore and report back.

**Comment by cwolcott** [comment]
Looks good the CLOBS > 3999 characters imported just fine.  Thank you.
