### ISSUE TITLE
Error at step generate sql create index for table

### ISSUE THREAD

**Issue by chuongtrh** [hankinsoft/SQLPro#726]
Version 2021.98 (Build 110860)
Database: Postgres

![image](https://user-images.githubusercontent.com/7924855/150474065-a6f0851b-2267-4353-8cad-1ba41cecc5f1.png)

![image](https://user-images.githubusercontent.com/7924855/150474164-2b40e632-8873-4404-b5ca-f0a8db6d2656.png)

**Comment by hankinsoft** [comment]
Reproduced. Working on a fix.

**Comment by hankinsoft** [comment]
Are you using the website build, or setapp?

**Comment by chuongtrh** [comment]
Download version from website build.

**Comment by hankinsoft** [comment]
Could you grab https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.6.app.zip and see if that helps?
