### ISSUE TITLE
Question: Dialog box: "Volume does not support permanent version storage"

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#727]
<img width="285" alt="StorageVolume" src="https://user-images.githubusercontent.com/15026225/150580302-4e5dbdf3-2888-4d04-98a1-75efd6c5abae.png">

Just had this pop up for the first time and wasn't sure what it meant. Mind explaining?

2022.5 (Build 110878.5)
macOS 12.1 (21C52)

**Comment by hankinsoft** [comment]
Build in macOS dialog. Not 100% sure exactly what it means, but I found some people discussing it here:
https://discussions.apple.com/thread/3200388

**Comment by hankinsoft** [comment]
Going to close this as it's non-specific too SQLPro, but macOS.
