### ISSUE TITLE
ORA-00932: inconsistent datatypes: expected NUMBER got CLOB

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#729]
A very odd occurrence.  I have a table with 44 columns, 3 of which are CLOB.  All of the CLOB are currently NULL until #725 is fixed.

The following query is producing the error - **ORA-00932: inconsistent datatypes: expected NUMBER got CLOB**
`SELECT * FROM MOLMAN.COMPOUNDS WHERE rownum <= 1000;`

But if I run either of the following queries it works just fine.
```
SELECT * FROM MOLMAN.COMPOUNDS WHERE rownum <= 999;
SELECT * FROM MOLMAN.COMPOUNDS WHERE rownum <= 1001;
```
The 1000th record that is returned in (rownum <=1001) looks just fine.  

An alternate way to retrieve 1000 records executes just fine also:
`select * from MOLMAN.COMPOUNDS WHERE id <= 1003;`

Any thoughts on further tests?  Not really a big deal, but the error does not occur in SQL Developer Plus.

OS: MacOS Catalina 10.15.7
Software: SQLPro Oracle Version 2022.2 (Build 499.5)
Connection: Oracle 19

**Comment by hankinsoft** [comment]
Do you possibly have a CSV I could use to reproduce this? I currently have absolutely no idea what’s going on.

**Comment by cwolcott** [comment]
I can try to put something together

**Comment by cwolcott** [comment]
For this issue and potentially a future issue is there a limit to the attachment size for a ticket?  None of the data I am working with is proprietary so it was just be easier to provide an actual dataset, but they can be very large.  The one I am working with right now is 842 MB.

**Comment by hankinsoft** [comment]
I think GitHub issues max size is 50mb. You could probably email 842mb to me though I think -- kyle @ hankinsoft.com.

**Comment by cwolcott** [comment]
Ok, trying to debug a little more to give you better details on what I am seeing.

**Comment by cwolcott** [comment]
Closing the issue, because I can no longer duplicate it.  The **COMPOUNDS** table has been restructured, moving columns around since the last test.  The MOL_FILE used to be the 2nd column after the first column that is a NUMBER, but now it is the 9th column after a varchar2 column.
