### ISSUE TITLE
Importing large CSV file with CLOBs is failing

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#733]
After the previous fix for large CLOB data values (#725) I attempted to reimport my 842.1 MB file which contains 215,412 records.  It failed after importing 146,500 records with the message:
![image](https://user-images.githubusercontent.com/3777526/151621233-a8ab9eb4-da95-4062-85ed-0a61cabf26a2.png)

**OS:** MacOS Catalina 10.15.7
**Software:** SQLPro Oracle Version 2022.5 (Build 500.5)
**Connection:** Oracle 19

I don't believe the error message and will explain why below.

I created a table name ETL_COMPOUNDS which has 42 columns (3 of which are CLOB).  See attachment below.
[ETL_COMPOUNDS.txt](https://github.com/hankinsoft/SQLPro/files/7961829/ETL_COMPOUNDS.txt)

My first attempt, while ticket #725 was being fixed, was to skip the 3 CLOB columns (MOL_FILE, THUMBNAIL and THREEDFILE).  This worked perfectly.  All 215,412 records imported.

We then tested some individual records to verify #725 was fixed and it was able to import the individual records with very large MOL_FILE values (31,000+ characters).

So now I attempted to import the full csv file and just skip 2 CLOB columns (THUMBNAIL and THREEDFILE). Thus including the MOL_FILE column.  Everything looked to be going well until it didn't.  Received the error above and selected the 'View failed statement" button.  I have attach this segment of 500 records (1.5MB)
[FailedSegment.146500.MolFileColumnEnabled.log](https://github.com/hankinsoft/SQLPro/files/7961898/FailedSegment.146500.MolFileColumnEnabled.log)

I then tried to process the statement in the file and the 500 records inserted just fine.

So what is occurring?  Why did it fail on these 500 records when it was part of the larger import.  Is there a memory leak?

**Comment by cwolcott** [comment]
Couldn't send an attached file that large, so instead I sent you an invite to a private directory in my MS Box Account containing the zipped file:

**Issue733.COMPOUNDS.20220128.csv.zip**

**Comment by hankinsoft** [comment]
File received. Trying an import now.

**Comment by cwolcott** [comment]
Hopefully it will error out for you in the same location so you can debug.  If it does error out you should be able to insert the offending block of 500 records in a separate tab.  That will be the head scratcher.

If you can't duplicate I assume there is no configuration/preference item that I can change the 500 block insert to something smaller so I can try to narrow down the offending record import all the records.

**Comment by hankinsoft** [comment]
Could you post the exact DDL for your table as well too please? I received a different error, but it was due to sizing issues with my table.

**Comment by cwolcott** [comment]
That should have been the attached file ETL_COMPOUNDS.txt.  I will create it again exactly how SQLPro Oracle provided it
[CREATE_ETL_COMPOUNDS.txt](https://github.com/hankinsoft/SQLPro/files/7972422/CREATE_ETL_COMPOUNDS.txt)

Obviously you will have to change the tablespace names

**Comment by hankinsoft** [comment]
Reproduced at 146500 records - so hopefully I can figure this out based on that.

**Comment by cwolcott** [comment]
It is always nice when it is repeatable elsewhere.

**Comment by hankinsoft** [comment]
Think I've got it sorted, just waiting for the full import to finish. I should have the build submitted tomorrow (it will also include #732).

**Comment by cwolcott** [comment]
Sorry it was so large.  My I ask what it was?  Odd occurrence since the block of 500 could be inserted on its own and that it was just caused an issue after 146500 records were already inserted.

**Comment by hankinsoft** [comment]
When I found the resulting row, It worked if I chunked the data up smaller - previously I was letting the max size be 3999, but now its down to 3990 and I'm at 44% imported.
