### ISSUE TITLE
Bug: Inserting a New Record (SQLite)

### ISSUE THREAD

**Issue by bwminick** [hankinsoft/SQLPro#735]
Hello,

There seems to be a bug in the SQLite program -- version 2022.4 (Build 4241.5).  When one adds a new record via the "Data" tab and clicks on the [+] button, (and then "applies" it), the GUI is not fully refreshing / updating, as it should.

For example, if I add a new row, I will see the "Updating Records" message pop up (letting me know it was manually added successfully), but then it still says that I have the same amount of records showing and the new primary key is not displaying for that record.  The only way to get correct info is to "Refresh Schema."  (Please see attached illustration.)

<img width="1185" alt="example" src="https://user-images.githubusercontent.com/77753152/152220366-cbf403fc-82e4-4a1b-8d3d-12cae4ae53c0.png">
.

**Comment by hankinsoft** [comment]
Thanks, I'll take a look into this.

**Comment by cwolcott** [comment]
I noticed the same issue in the results pane for SQLPro Oracle

**Comment by hankinsoft** [comment]
For the next build, the number of rows will now get updated properly when adding/removing records via the data view. I'm still investigating having a 'DEFAULT' value get updated.

**Comment by hankinsoft** [comment]
I think I've got something figured out for SQLite, but it will only work if your table does NOT have `without row id` applied to it. Once I've got this finished 100% I will see what I can do for oracle.

**Comment by hankinsoft** [comment]
> I have noticed this for awhile, but just assumed you didn't plan on refreshing the results pane after an update.

I didn't really plan for them to update, but while investigating this issue, I was able to figure out a way to do so. I've submitted both a SQLPro for Oracle and SQLPro for SQLite build which adds this in. SQLPro Studio will possibly be getting this for the other database types as well depending on the individual clients.

**Comment by bwminick** [comment]
Thank you for all of your work on this!  It is appreciated.  :-)

**Comment by hankinsoft** [comment]
Both builds are now available via the Mac app store. Please let me know if that sorts this issue up for everybody when you get the chance.

**Comment by bwminick** [comment]
Thank you!  It's fixed...  Much appreciated!!  :-D

**Comment by cwolcott** [comment]
For SQLPro Oracle the results pane does not update with the generated id.
<img width="346" alt="image" src="https://user-images.githubusercontent.com/3777526/153230376-a923d275-5fd1-46b9-ba67-3de046131bf0.png">

SQLPro Oracle: Version 2022.11 (Build 504.5)

**Comment by hankinsoft** [comment]
Can you post the ddl of the table please?

**Comment by cwolcott** [comment]
Here is the definition of the table.

```
CREATE TABLE MOLMAN.REF_NOTEBOOK_TYPES (
    ID            NUMBER(3,0) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 NOCACHE NOT NULL, 
    NAME          VARCHAR2(100) NOT NULL, 
    CONSTRAINT PK_REF_NTBTYPES PRIMARY KEY (ID)
);
```

**Comment by hankinsoft** [comment]
Submitted a bug fix. For reload to work with Oracle it will only work when the table has a numeric primary key.

**Comment by cwolcott** [comment]
Ok, once I see a new release for SQL Pro Oracle I will try it out.
Still have Version 2022.11 (Build 504.5), nothing new in the AppStore

**Comment by cwolcott** [comment]
Well look at that.  SQL Pro Oracle Version 2022.12 (Build 506.5) just should up at it takes care of the issue.  Nice way to end the week.
