### ISSUE TITLE
Feature Request: multiple windows open on same database

### ISSUE THREAD

**Issue by gitjoost** [hankinsoft/SQLPro#737]
I would like to be able to have two (or more) windows open on different tables of the same database. Each window giving me access to data and query displays so that I can make edits and run queries side by side.

SQLPro for SQLite Version 2022.4 (Build 4241.5)

**Comment by cwolcott** [comment]
I have wanted the same thing.  One of my IDE's allow you to Split Right and Move
![image](https://user-images.githubusercontent.com/3777526/152877954-a1e591b2-c209-4a92-83a5-bb6ea694cc41.png)

So it looks like this afterwards.
![image](https://user-images.githubusercontent.com/3777526/152878053-21fc4743-6bbc-4f0b-879c-480dd25a71c5.png)

**Comment by hankinsoft** [comment]
No plans for this in SQLPro for SQLite. Side by side tabs MIGHT come to SQLPro Studio in the future, but its not something I could currently put an ETA on.

**Comment by michaeldesu** [comment]
Agree, having multiple query tabs open on the same database is a really desirable feature.

Hopefully it will come in some future version and/or there's an upgrade path for those on SQLPro for SQLite to move to Studio (should it have the feature). In any case, I've bought a license for SQLPro for SQLite to show some support to the developer in the meantime. Thanks for making this nice client.

**Comment by hankinsoft** [comment]
I've done a bit of investigation on this, currently have planned not to go forward with it. The difficulty in implementation risk/reward is unfortunately not there. Maybe in the future if enough people were to request it, but currently as it stands it is unplanned.
