### ISSUE TITLE
Feature Request: Filter button position and shortcut

### ISSUE THREAD

**Issue by gitjoost** [hankinsoft/SQLPro#739]
I use the filter button/feature quite often and have two grips with it:
- there is no short cut for it. CMD-F would be very handy to toggle on/off
- the button is located at the bottom of the window whereas the content to filter on, options etc are located at the top causing me to mouse move up/down constantly when turning the filter on/off.

Would be nice if this could get a bit of attention in some of the next releases.

**Comment by hankinsoft** [comment]
Hi,
You should be able to filter via the '⇧ + ⌘ + F' (shift, command, f) keyboard combination:
<img width="234" alt="Screen Shot 2022-04-01 at 8 52 17 AM" src="https://user-images.githubusercontent.com/3160528/161258197-de411be5-fc44-4b3b-b989-7ff3dc7e66b1.png">

Does that work for you?

> The button is located at the bottom of the window whereas the content to filter on, options etc are located at the top causing me to mouse move up/down constantly when turning the filter on/off.

No currently plan to move the button. I can't picture where else on the UI I would put it that it does not look out of place.

**Comment by gitjoost** [comment]
First of, I have no Filter menu option anywhere, I have Edit/Find which is same/similar/different? (SQLPro for SQLite) Anyhow, it is also not behaving in a way that makes sense to me; 

For me the Edit/Find menu options are permanently grayed out. 
<img width="267" alt="Screen Shot 2022-04-01 at 8 28 27 AM" src="https://user-images.githubusercontent.com/1977649/161294758-88a9edb4-9cae-4e50-b7e8-8f5f7d95afea.png">

Interestingly sometimes the first option Edit/Find/Find... appears enabled yet it does nothing when invoked. Poking around a bit I figured out that if I first enter a table (just by selecting it from the left panel, coming from another table), Edit/Find/Find... shows enabled (but doesn't do anything when selected). However, after I invoke the Filter functions (Filter button bottom right), and either do some filtering or not and eventually press "done", the Edit/Find/Find... is greyed out. 

Pressing '⇧ + ⌘ + F' gives me an error (audio "ding").

**Comment by hankinsoft** [comment]
Hi - I think we are looking at two different menu's. The one I attached is a context menu if you right click on the data grid.

For the `⇧ + ⌘ + F`, have you focused the data grid by clicking on it. If you focus it first, does the shortcut then work?

**Comment by gitjoost** [comment]
Yes it seems you are correct. I never new there was a context menu. Having to right-click and then a keyboard shortcut seems illogical to me. The whole reason to use keyboard shortcuts is to not have to always grab that mouse.  Going through the context menu, I don't quite understand why these options must be made available as a context menu and not just be provided as a menu from the main menu bar. Yes I understand that some menu choices will not make sense depending on what is visible (schema, data, query) but those can then be grayed out as many other apps do.

Apologies for my ignorance, however, my original request still stands; can we get a keyboard shortcut that can be activated with keeping ones fingers on the keyboard?   I'd like to extend that request by suggesting to move that entire context menu into a standard menu.

**Comment by jim256** [comment]
CMD + Shift + F has always pulled up the filter GUI for me regardless of whether my focus is in the Results panel, query editor, the Database Tree, or the Database Search.

I use this many times every single day and have for over a year (and just now tried it again with the focus in those different places in the app). I never need to use the mouse in order to get the shortcut to work.

My personal vote would be to leave the context menu where it is. I like that it's easily visible right next to results, and otherwise out of the way. Makes more sense to me to have it in context.

SQLPro Studio 2022.28 (Build 110897.5)
macOS 12.3.1 (21E258)

**Comment by gitjoost** [comment]
"CMD + Shift + F" gives me a "dinggg"...

**Comment by hankinsoft** [comment]
> CMD + Shift + F has always pulled up the filter GUI for me regardless of whether my focus is in the Results panel, query editor, the Database Tree, or the Database Search.

@gitjoost is using SQLPro for SQLite. The global shortcut for filter had not been implemented in it (I thought it had, but I was mistaken).

> can we get a keyboard shortcut that can be activated with keeping ones fingers on the keyboard?
I've added that option for the filter shortcut.

>  I'd like to extend that request by suggesting to move that entire context menu into a standard menu.
If I receive additional requests for specific shortcuts, I'll take a look at adding global support. For now the data grid will need to be focused by clicking on it.

The build is available here:
https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.30.app.zip

SetApp and website builds will be available shortly as well.

**Comment by hankinsoft** [comment]
Is the filter shortcut working for you in the latest build? (v2022.30)?

**Comment by gitjoost** [comment]
I just tried it and yes it is working. Thanks for caring and follow up!

**Comment by hankinsoft** [comment]
Awesome, glad its working for you.
