### ISSUE TITLE
Intellisense/autocomplete mistakes Views as Tables (in Oracle)

### ISSUE THREAD

**Issue by U47** [hankinsoft/SQLPro#74]
The intellisense/autocomplete magic whathaveyou shows Views as Tables. Trivial bug, but noteworthy.

(This is against an Oracle 12c database.)

In this image, all of these objects are Views, not Tables.
![image](https://cloud.githubusercontent.com/assets/573316/22610053/d6cb7b1c-ea20-11e6-99aa-9073bd91c5cd.png)

**Comment by hankinsoft** [comment]
Thanks. This is actually an issue in all SQLPro apps. I'll add it to the todo, but no ETA at the moment.

**Comment by hankinsoft** [comment]
Closing - autocomplete now changes the icon based on if an object is a table or view.

<img width="682" alt="Screen Shot 2022-01-04 at 2 04 59 PM" src="https://user-images.githubusercontent.com/3160528/148103732-b6f1f786-4229-4078-9899-74b1a27cc388.png">
