### ISSUE TITLE
Renaming a favorite query to change the case of letters doesn't save the new name

### ISSUE THREAD

**Issue by GaryMeyers1** [hankinsoft/SQLPro#741]
Renaming a favorite query doesn't detect a change when the user is only changing the case of one or more letters, so the new name isn't saved.  The user has to make a non-case change to the name first and then rename the query to the desired name in a second step.

**Comment by hankinsoft** [comment]
Thanks, I have reproduced and will investigate.

**Comment by hankinsoft** [comment]
Fixed for the next build (2022.23+).

**Comment by hankinsoft** [comment]
SQLPro Studio v2022.24 as well as SQLPro for SQLite is now available on the Mac app store with this resolved. If you get the chance, please let me know if this resolves the issue for you.

**Comment by GaryMeyers1** [comment]
Hi,

I don’t see how to download 2022.24 from the app store without paying $49.99 for it but I am already a registered user.  When I went to sqlpro.com <http://sqlpro.com/>, the version that downloads is 2022.12.  Please let me know how I can try version 2022.24.

Thanks,
Gary


On Apr 6, 2022, at 6:29 AM, Kyle Hankinson ***@***.***> wrote:


SQLPro Studio v2022.24 as well as SQLPro for SQLite is now available on the Mac app store with this resolved. If you get the chance, please let me know if this resolves the issue for you.

**Comment by hankinsoft** [comment]
Hi,
Please try https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.25.app.zip and see if that helps.

**Comment by GaryMeyers1** [comment]
Version v2022.25 handled favorite query renames where the only change was to change the case of characters in the name.

If you have a chance, I’d like to hear your reason for not widening the favorite query grid on the Edit Favorites screen.  When I was writing Windows apps, it would have taken me five minutes to add a splitter to a screen, including checking the file out of and back into version control, so I don’t think this would require a lot of your time.  I have many more app suggestions for you and other users to consider but I’m not going to submit them until I hear why you have not made this change yet.




On Apr 6, 2022, at 6:29 AM, Kyle Hankinson ***@***.***> wrote:


SQLPro Studio v2022.24 as well as SQLPro for SQLite is now available on the Mac app store with this resolved. If you get the chance, please let me know if this resolves the issue for you.

**Comment by hankinsoft** [comment]
> Version v2022.25 handled favorite query renames where the only change was to change the case of characters in the name.

Awesome, thats great to know. I'll close the issue.

> If you have a chance, I’d like to hear your reason for not widening the favorite query grid on the Edit Favorites screen.  When I was writing Windows apps, it would have taken me five minutes to add a splitter to a screen, including checking the file out of and back into version control, so I don’t think this would require a lot of your time.  I have many more app suggestions for you and other users to consider but I’m not going to submit them until I hear why you have not made this change yet.

Multiple reasons:
1. It's fairly low priority. The UI exists and works for most people as it is. As an independent developer, I balance my time on what I believe will be a priority for the most users.2. 
2. The current issue #675 includes three items, with the tagging and sorting being the more difficult. Every time I look at the issue, I contemplate the tagging and sorting and decided that the effort for them is beyond the value at the moment. Honestly, up to this point I've never considered separating the resize into its own ticket, but I may take a look at for an upcoming build.
