### ISSUE TITLE
Bug: Snowflake: Database Tree including schema in table names

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#742]
As of just recently, the app is prepending all my table names with the schema name in the Database Tree:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/15026225/153673581-e28b1995-693f-4acb-9746-842264d68285.png">

SQLPro Studio 2022.11 (Build 110882.5)
macOS 12.1 (21C52)
Snowflake 6.3.2

**Comment by hankinsoft** [comment]
Fixed for the next build:

<img width="311" alt="Screen Shot 2022-02-18 at 9 20 38 AM" src="https://user-images.githubusercontent.com/3160528/154690344-45adc32f-e981-4d57-8331-031ecdcbc70f.png">

It will be available sometime next week.

**Comment by hankinsoft** [comment]
If you are still seeing this with the latest version, please let me know.
