### ISSUE TITLE
Can't remove "My Connections" group

### ISSUE THREAD

**Issue by beerlington** [hankinsoft/SQLPro#743]
I'm using SQLPro Studio Version 2022.11 (Build 110882.5).

After setting up some connection groups, I cannot delete the default "My Connections" group.

I'm clicking the trash can icon in the top right:

![Screen Shot 2022-02-14 at 12 04 18 PM](https://user-images.githubusercontent.com/77580/153911719-437cf054-2baa-48f9-ab4b-3898d3397246.png)

When I first tried to remove it, I got this message saying there was 1 connection. Even though there isn't one, I clicked
![Screen Shot 2022-02-14 at 12 04 05 PM](https://user-images.githubusercontent.com/77580/153911787-2c1e7650-2fd1-4960-a0f9-7c31a13e93c0.png)

When I clicked "Accept" the modal closed, but nothing happened. Now when I click the trash can next to the "My Connections" group, nothing happens. I've tried quitting and restarting the app, but am still seeing this.

**Comment by hankinsoft** [comment]
I'm working on adding some additional logging for this. I'll have a build available early next week to help get this figured out. Sorry for the issue.

**Comment by beerlington** [comment]
Thanks! I can still work around it, but figured I'd report it since it's sort of a strange one. I'll keep an eye out for the next build.

**Comment by beerlington** [comment]
@hankinsoft It looks like I have the new version now. Is there anything I can do on my end to help troubleshoot?

**Comment by hankinsoft** [comment]
Could you:
1. Delete the log file (you can find it by going to 'View' -> 'Logs').
2. Relaunch SQLPro
3. Try and remove the group.
4. Send me the resulting log file?

It now provides addition log details on the connections it thinks exist.

**Comment by beerlington** [comment]
Here you go. I clicked the remove button twice.

[com.hankinsoft.osx.sqlprostudio 2022-02-23--16-28-44-301.log](https://github.com/hankinsoft/SQLPro/files/8126054/com.hankinsoft.osx.sqlprostudio.2022-02-23--16-28-44-301.log)

**Comment by hankinsoft** [comment]
Did you get the prompt `The connection group 'My connections' contains 1 connection. ...` when clicking the remove button? I'm not seeing the log messages I would expect.....

**Comment by hankinsoft** [comment]
If you get the chance, could you try reproducing the issue again using this build:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.23.app.zip

And post the log files after reproducing? Thank you (and sorry for the delay).

**Comment by beerlington** [comment]
I cleared the logs and clicked the trash can in the My Connections group a few times. I'm happy to try any other builds too.

[com.hankinsoft.osx.sqlprostudio 2022-04-05--16-42-36-942.log](https://github.com/hankinsoft/SQLPro/files/8420211/com.hankinsoft.osx.sqlprostudio.2022-04-05--16-42-36-942.log)

**Comment by hankinsoft** [comment]
Thank for that! I see:

> 2022/04/05 16:42:41:797  SQLProConnectionsListView:collectionView:viewForSupplementaryElementOfKind:atIndexPath: entered removeConnectionBlock for section: My connections.
> 2022/04/05 16:42:41:797  SQLProConnectionsListView:collectionView:viewForSupplementaryElementOfKind:atIndexPath: removeConnectionBlock has no entries. Going to remove it.

So its either failing to remove it, or re-creating it further down the lines. I'm going to add some extra logging for both cases to try and figure out which it is.

**Comment by hankinsoft** [comment]
Can you try:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.24.app.zip

I think thats going to fix the problem, but if not could you post the log file?

**Comment by beerlington** [comment]
It looks like the connection is now gone, so that's great!

![Screen Shot 2022-04-05 at 1 20 35 PM](https://user-images.githubusercontent.com/77580/161814113-4df3cc28-5270-4385-8114-fc4f40e6901b.png)

**Comment by hankinsoft** [comment]
Awesome! I'm going to close the issue. Please let me know if you run into anything else I can help with.
