### ISSUE TITLE
MSSQL Server Datetime2

### ISSUE THREAD

**Issue by peachesontour** [hankinsoft/SQLPro#744]
Datetime2 columns are shown in the object explorer with the number of bytes they use (I assume) in parentheses instead of the accuracy/number of decimal places. For example, in MSSQL Management Studio, if I define a column as Datetime2(6) it appears in SQLPro as Datetime2(8). See comparison below:
<img width="229" alt="Screen Shot 2022-02-15 at 07 46 43" src="https://user-images.githubusercontent.com/67612358/154046579-23bbed33-8722-4173-9685-eeeb65f83886.png">
<img width="246" alt="Screen Shot 2022-02-15 at 07 44 30" src="https://user-images.githubusercontent.com/67612358/154046682-fb2fcebf-1280-4299-a3cd-45b7cb5bee15.png">

**Comment by hankinsoft** [comment]
Fixed for the next build:
<img width="936" alt="Screen Shot 2022-02-18 at 9 00 11 AM" src="https://user-images.githubusercontent.com/3160528/154687474-b6aad42a-b6f3-45ef-84bf-ccd386ebe33b.png">

What version of SQLPro are you using and is it from the website, App Store, setapp?

**Comment by hankinsoft** [comment]
This has been fixed for a bit now. If you are still having issues, please let me know.
