### ISSUE TITLE
Varbinary column crashes app

### ISSUE THREAD

**Issue by Tomfox91** [hankinsoft/SQLPro#75]
[HotCRP](https://github.com/kohler/hotcrp) stores some comments in a MySQL varbinary column. These data is shown as hex in SQLPro Studio, but I want to see it as text. Clicking the downward arrow at the end of the field (see screenshot below) **crashes** the application.

![screenshot](https://cloud.githubusercontent.com/assets/2546080/22730871/f7c98194-ede8-11e6-858c-044eb7075ef3.png)

OS: macOS 10.12.3 (16D32)
DB: MariaDB 10.0.27
SQLPro Studio 1.0.107 (Build 1038)

Excerpt from crash log:
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
Crashing on exception: -[_NSInlineData _isCString]: unrecognized selector sent to instance 0x6000002c2990
```

Table definition:
```sql
CREATE TABLE `PaperComment` (
  `commentId` int(11) NOT NULL AUTO_INCREMENT,
  `contactId` int(11) NOT NULL,
  `paperId` int(11) NOT NULL,
  `timeModified` int(11) NOT NULL,
  `timeNotified` int(11) NOT NULL DEFAULT '0',
  `timeDisplayed` int(11) NOT NULL DEFAULT '0',
  `comment` varbinary(32767) DEFAULT NULL,
  `commentType` int(11) NOT NULL DEFAULT '0',
  `replyTo` int(11) NOT NULL,
  `paperStorageId` int(11) NOT NULL DEFAULT '0',
  `ordinal` int(11) NOT NULL DEFAULT '0',
  `authorOrdinal` int(11) NOT NULL DEFAULT '0',
  `commentTags` varbinary(1024) DEFAULT NULL,
  `commentRound` int(11) NOT NULL DEFAULT '0',
  `commentFormat` tinyint(1) DEFAULT NULL,
  `commentOverflow` longblob,
  PRIMARY KEY (`commentId`),
  UNIQUE KEY `commentId` (`commentId`),
  KEY `contactId` (`contactId`),
  KEY `paperId` (`paperId`),
  KEY `contactPaper` (`contactId`,`paperId`),
  KEY `timeModified` (`timeModified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by hankinsoft** [comment]
Thank you for posting your stack trace and your table. I'm going to try reproducing and hopefully will have a fix to you within a few days.

**Comment by hankinsoft** [comment]
Can you try the following build:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.110.app.zip

It should sort the issue. Note that the results grid itself will still display hex (I currently do not resolve otherwise due to performance constraints, but I might be able to improve this in the future). The expanded popup should resolve it as a string though.

**Comment by Tomfox91** [comment]
I didn't try your link but I can confirm that version 1.0.111 (Build 1042) fixes the problem. Feel free to close the issue. Thanks for your quick response.
