### ISSUE TITLE
SQLPro Studio crashes when going to Edit menu with Azure MSSQL database

### ISSUE THREAD

**Issue by stona1** [hankinsoft/SQLPro#750]
Hi,

Today I download SQLPro Studio. I connected to sample connection from the app start window "SQL Server Sample". Database "sqlprosample" and execute this query: "SELECT TOP 1000 * FROM SalesLT.Address;". When query finish when I just hover cursor over Edit manu application will crash. It is replicable. All other menus are working (beside "Edit). I tried it with different tables with same result. 
I am using MacBookPro with m1 Pro processor, macOS Monterey 12.2.1 and SQLPro Studio from your website version 2021.102 (Build 110865). 

Best regards
Arek

### Apple error details:
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               SQLPro Studio [62760]
Path:                  /Applications/SQLPro Studio.app/Contents/MacOS/SQLPro Studio
Identifier:            com.hankinsoft.osx.sqlprostudio
Version:               2021.102 (110865)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-02-27 21:39:14.7847 +0100
OS Version:            macOS 12.2.1 (21D62)
Report Version:        12
Anonymous UUID:        210EFE98-DDEC-8ACB-0C62-3D337AAA1A20

Sleep/Wake UUID:       FD233D6E-2BE2-4D8F-B393-47C2A6F23B92

Time Awake Since Boot: 550000 seconds
Time Since Wake:       3035 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001a10fb5c4
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [62760]

Application Specific Information:
Validating menu item 'Format query' with action @selector(onFormatQuery:)
Refcount overflow in NSResponder or subclass. Too many unbalanced -retains!

**Comment by hankinsoft** [comment]
Can you grab https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.12.app.zip? that should sort it out.

**Comment by stona1** [comment]
This one working correct.
Thank you.

**Comment by hankinsoft** [comment]
No problem and sorry for the inconvenience!
