### ISSUE TITLE
Is for SQLPro Studio lifetime license available or not?

### ISSUE THREAD

**Issue by stona1** [hankinsoft/SQLPro#751]
Hi,
I am wondering is for SQLPro Studio lifetime license available or not. On this website: https://www.sqlprostudio.com/blog/ I can read: 
_SQLPro Studio, SQLPro for MSSQL, SQLPro for MySQL and SQLPro for Postgres are yearly licenses. The license will auto-renew unless cancelled (cancellation details are included in the initial email received upon purchase).
SQLPro for SQLite is a lifetime license (does not need to be renewed each year)._

but when I go to this website: https://www.sqlprostudio.com/price.php? third option to purchase is Lifetime (for macOS).
Which of this information is correct?

**Comment by hankinsoft** [comment]
Hi,
Yep. That first article is the 'Reseller FAQ'. I don't offer lifetime to resellers. You can absolutely purchase a lifetime license at https://www.sqlprostudio.com/price.php, but please remember that lifetime licenses are single platform only, whereas subscription license keys (purchased from the website) support macOS, iOS and Windows.

Lifetime licenses are available via the website for Windows and macOS. iOS lifetime licenses must be purchased via the App Store.
