### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by stona1** [hankinsoft/SQLPro#752]
During my work I need to export many results from MSSQL to Excel. I know it is possible in SQLPro Studio to export to Excel via CSV but it I need to do this meny times per day and I am looking for a way how to do this directly. I mean in result window when I have option to save in CSV (JSON, etc.) export to XLSX too. 
Do you consider to add this option?

**Comment by hankinsoft** [comment]
Unfortunate I currently have no plans for exporting directly to excel. You might be able to use a command line tool (one example is here: https://stackoverflow.com/a/56071455) to make converting csv files easier.
