### ISSUE TITLE
Issues with re-connecting to named instances

### ISSUE THREAD

**Issue by aaksyonenko** [hankinsoft/SQLPro#757]
SQLPro Studio Version 2022.15 (Build 110886) on MacBook Pro (14-inch, 2021) chip Apple M1 Pro macOS Monterey version 12.2.1 (21D62)

When starting SQLPro or connecting to a saved MS SQL Server (specifically, a named instance), I get the following error:
`Login failed. The login is from an untrusted domain and cannot be used with Windows authentication. (Msg 18452, Level 14).`

In order to successfully connect, I have to edit the server, making sure that I re-type the password (same password that has been saved), save the server, then connect to it — in this case it works.  No other changes — just re-typing the same password again.

It appears that saved passwords in the server configurations are not being saved properly, or do not remain saved between shutting down and restarting SQLPro Studio. Or there's some other issue with working on VPN with this.

**Comment by aaksyonenko** [comment]
No.  I get the same error when connecting to duplicate.
If I edit the original by updating the password - it connects.  If I make a duplicate of the original after updating the password - it connects without the need to update password on duplicate
If I make a duplicate, then update password on the duplicate - the duplicate connects, but the original still fails.
Leads me to believe that password updates are saved only until I quit the app, and if the app is restarted - the link to credentials is lost, or passwords revert to whatever the item was originally created with.

**Comment by hankinsoft** [comment]
> If I edit the original by updating the password - it connects. If I make a duplicate of the original after updating the password - it connects without the need to update password on duplicate
If I make a duplicate, then update password on the duplicate - the duplicate connects, but the original still fails.

The above is all expected behaviour. But your saying if you close the app, then relaunch the app, the passwords are all reverted to their previous state?

If you change something else, such as the 'alias' then close and re-open does that reset to the previous state?

**Comment by hankinsoft** [comment]
Just wanted to check in again. If you change something else, such as the 'alias' then close and re-open does that reset to the previous state?

**Comment by aaksyonenko** [comment]
Hi. If I close (quit) and re-launch the app - I do not know if the passwords are going back to previous, or are just missing, but they do not work.  The edit screen does show the placeholders for the password, but I have to type it in again and save in order for it to start working again.
Changing anything else other than the passcode has no effect, still does not work.

**Comment by hankinsoft** [comment]
Could you try this build:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.45.app.zip

And see if that helps out?

**Comment by aaksyonenko** [comment]
After updating, opened the app (with remembered open tabs) and was able to run a query without changing any settings, updating passwords or anything else - connected automatically.  Based on this test looks like the issue is resolved, thank you!  Will update you as I use it if anything crops up.  SQLPro is an absolute lifesaver for a Mac user, thank you for creating it!

**Comment by hankinsoft** [comment]
Thank you for letting me know all is good now and sorry for the delay with getting this sorted.

**Comment by aaksyonenko** [comment]
Kyle, hi.  Looks like this issue has come back for me after updating to Version 2022.77 (Build 110948)  :-(  same symptoms.

**Comment by hankinsoft** [comment]
Is it possible your connections are reverting back to previous versions? Similar to #834?

**Comment by weelassie23** [comment]
After a recent update this last week, I'm getting this error now. Nothing has changed with my password or data connection settings.
![sqlpro error](https://user-images.githubusercontent.com/125701593/219793946-42b2e25d-65fa-4805-a03f-11ee1b43e8d7.png)

**Comment by hankinsoft** [comment]
Going to close this issue as it seems the persistence issue has been resolved. @weelassie23 please open a new issue with all of the require details and I'll see what I can do to help out.
