### ISSUE TITLE
Delete selected row sometimes generates SQL using the last table name if more than 1 select is executed in the same tab

### ISSUE THREAD

**Issue by peachesontour** [hankinsoft/SQLPro#758]
If I run 2 queries in the same tab while connected to an MSSQL Server, and then right click to select one of the rows in the first output set, and click Delete from the pop up menu, the generated SQL with the delete command uses the columns from the first output in its where clause, but the table name comes from the second output window. Note: This only happens if the first query doesn't have a WHERE clause, nor a semicolon at the end.

Ie: Run 2 queries. In this example the id column in Table1 is an UUID and the id column in Table2 is an Integer.
SELECT * FROM dbo.Table1
SELECT * FROM dbo.Table2 WHERE id = 14

Then right click "delete selected row" on a row from the first output generates this SQL:
DELETE TOP (1) FROM dbo.Table2 WHERE id = '738CC370-E84D-468D-BACB-262327598F02';

**Comment by hankinsoft** [comment]
Reproduced. Checking into this now.

**Comment by hankinsoft** [comment]
For the next build, you won't be able to modify/delete rows when multiple select statements are used without a semicolon. 

I'm still investigating to see if I can get it to work properly if there is no semicolon, but I'm not 100% sure if that will be an option yet.

**Comment by hankinsoft** [comment]
SQLPro Studio v2022.24 is now available on the Mac app store. You can no longer modify multiple-result sets unless separated by a ; or a GO. I have not been able to find a good way of otherwise handing this, but I may re-visit that in the future.
