### ISSUE TITLE
Help-->search

### ISSUE THREAD

**Issue by duncanelliot** [hankinsoft/SQLPro#760]
If you click help and enter anything into the search bar, it crashes the application.
![image](https://user-images.githubusercontent.com/34279184/161955195-041f020e-75cc-4aed-8d8e-666adae3cbce.png)

**Comment by hankinsoft** [comment]
Hmmm, the search bar shouldn’t exist. What version of macOS are you using
and what version of SQLPro?

**Comment by duncanelliot** [comment]
latest and latest
![image](https://user-images.githubusercontent.com/34279184/161983957-33139f32-74d4-4a49-a614-629d3cc91aee.png)
![image](https://user-images.githubusercontent.com/34279184/161984010-9768d767-4937-4a06-8b08-1615102a8b6d.png)

**Comment by hankinsoft** [comment]
Could you possibly send me the crash report? If you open 'Console.app' and choose 'Crash reports' over on the left side, it should then list SQLPro for MySQL on the right side. You should be able to click on it here and copy/paste the report from the bottom section?

**Comment by hankinsoft** [comment]
I've submitted a build which might fix this. It should be available in ~24 hours or so.

**Comment by hankinsoft** [comment]
2022.26 is now available. If you get the chance, please give it a try and let me know if that sorts things out for you.
