### ISSUE TITLE
SQLPro for SQLite drops ON CONFLICT IGNORE when rewriting a database

### ISSUE THREAD

**Issue by hivehand** [hankinsoft/SQLPro#761]
SQLPro for SQLite, Version 2022.1 (Build 4238)
macOS Monterey, Version 12.3.1 (21E258)

When rewriting a SQLite database to update the schema, SQLPro drops existing ON CONFLICT IGNORE clauses.

Steps to reproduce:

1. Create a new database file (`touch example.sqlite`).
2. Open it with sqlite3, and create a minimal table with an `ON CONFLICT IGNORE` clause: `CREATE TABLE IF NOT EXISTS "paths" ("id" integer PRIMARY KEY NOT NULL,"name" text UNIQUE NOT NULL ON CONFLICT IGNORE);`. Exit sqlite3.
3. Open database with SQLPro, and add a new column to the `paths` table. Exit SQLPro.
4. Issue the command `sqlite3 example.sqlite .schema` and examine the output. Notice that the `ON CONFLICT IGNORE` clause has been dropped from the definition of the `name` column.

**Comment by hivehand** [comment]
Addendum: just upgraded SQLPro for SQLite to the current latest, Version 2022.12 (Build 4252), and confirmed that the issue exists there as well.

**Comment by hankinsoft** [comment]
Reproduced and working on a fix.

**Comment by hankinsoft** [comment]
2022.26 has been submitted to Apple. It usually takes ~24 hours or so for the fix to become available.

**Comment by hivehand** [comment]
Wow. Thank you for addressing this so quickly!

**Comment by hankinsoft** [comment]
No worries. The fix should now be available in the App Store - if you get the chance, please give it a try and let me know if that sorts things out for you. If your not using the App Store version, let me know if you are using the website or setapp version and I will get them updated for testing.

**Comment by hivehand** [comment]
I'm using the website version — installed via Homebrew, on the off chance
that that matters. Thanks!

**Comment by hankinsoft** [comment]
Ah - https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.28.app.zip would be the latest version then.
