### ISSUE TITLE
Bug: SQLpro for SQLite -- Missing Records

### ISSUE THREAD

**Issue by bwminick** [hankinsoft/SQLPro#762]
Hello,

In SQLPro for SQLite, there seems to be a bug.  For example, while in the **Data** tab, when changing from one table to another, some of the records won't always display on the screen.

<img width="1650" alt="example01" src="https://user-images.githubusercontent.com/77753152/162275604-447c43b0-a6e5-4493-a3e8-ab100734f9a3.png">

**To replicate this bug:**

1. Download and open the DemoDatabase.sqlite file.  ([Link to download it.](https://drive.google.com/file/d/1oSFOLvj38ufZ44QZ6FCnLRlWPxmbRazI/view?usp=sharing))
2. Click on **Data** at the top of the program.
3. Click on the **Products** table.
4. Click on the **Employees** table.  (Note that there are only 8 records showing, instead of 10.)

NOTE: No worries about privacy, as the database only contains fictitious info.

Thank you,

Byron

**Comment by hankinsoft** [comment]
Reproduced. Investigating this now.

**Comment by hankinsoft** [comment]
A fixed build has been submitted to the App Store. It should be available in ~24 hours.

**Comment by bwminick** [comment]
Thank you very much!  It's working...  😃
