### ISSUE TITLE
Feature Request: SQL Editor - Move Multiple Lines

### ISSUE THREAD

**Issue by chrischain** [hankinsoft/SQLPro#763]
Previously you added the ability to move lines as requested in https://github.com/hankinsoft/SQLPro/issues/605

It works great, however I've noticed that this only works with a single line. I'd like to be able to select multiple lines and have it move them together.

Thanks!

**Comment by hankinsoft** [comment]
If this is what you mean:

![CleanShot 2022-04-08 at 15 30 44](https://user-images.githubusercontent.com/3160528/162500821-e6209217-2d91-4a71-a3a1-44b7b45dc0bc.gif)

Then it was super easy and I've got it ready for a build next week.

**Comment by chrischain** [comment]
Yep, that's totally it! Awesome!

**Comment by chrischain** [comment]
Tested the feature on the .28 build, this also seems to have a similar issue with #764 where it appears to be inserting blank lines before actually moving a line/lines when using selected text.

**Comment by chrischain** [comment]
https://user-images.githubusercontent.com/1153561/162824600-ea0bc2fe-c3ba-43bd-90bd-7dc877925c71.mov
