### ISSUE TITLE
Feature Request: SQL Editor - Copy Line(s) down/up

### ISSUE THREAD

**Issue by chrischain** [hankinsoft/SQLPro#764]
This is another VS Code feature that I'd love to see implemented in SQL Pro Studio: copy code line or multiple selected lines. A demo of the feature in VS Code can be seen here: https://youtu.be/j_h1TcSrx_0?t=27

There's been a few times when I've found myself using the key combo and forgetting that I'm not in VS Code. It would be a handy feature to have when you're working on large or complex scripts, especially when debugging.

Thanks!

**Comment by hankinsoft** [comment]
So its just like the other item, except it duplicates the line(s) rather than moves them?

**Comment by chrischain** [comment]
That's right. Makes it simple to duplicate a line (or lines) once or many times.

**Comment by hankinsoft** [comment]
> Also, if you use the up arrow, will it copy above the current line?

That is the example of 'duplicate above'. The 'current line' is 'LINE 5', so it inserts a copy above that line making it 'LINE 5\nLINE 5'.

Should it be inserting it above 'LINE 4'? And if so, the next insert would be above line three? So if you selected line 5 and did a copy above twice, would you expect to see:

LINE 1
LINE 2
LINE 5
LINE 3
LINE 5
LINE 4
LINE 5?

(If so, the current build in review has the wrong behaviour :)

**Comment by chrischain** [comment]
Oh, no... it should just insert above the current line (or selected lines) only. Sounds like you had the behavior correct from the outset. So the down arrow triggers duplicate below, correct? It should just insert the selected line(s) below the current cursor or selection?

**Comment by hankinsoft** [comment]
It's actually already approved by apple, so the update should be available anytime. Once you have it, give a try and let me know if the behaviour is what you expect.

**Comment by chrischain** [comment]
Thanks! Will do. It doesn't appear to have hit the app store for me just yet, but I'll keep checking.

**Comment by chrischain** [comment]
Got the update, works as expected save for one minor glitch: it seems to insert blank lines when selecting (highlighting) a single line or multiple lines. If you just put the cursor in the line to copy, it doesn't do it, but when using selections it does.

**Comment by hankinsoft** [comment]
Screenshot or video of what you mean?

**Comment by chrischain** [comment]
https://user-images.githubusercontent.com/1153561/162823609-8b028683-aab9-4a7a-a171-3414d38b2fee.mov

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.29.app.zip and see if that fixes it?

**Comment by chrischain** [comment]
It's still doing the same thing.

![2022-04-13 08 40 12](https://user-images.githubusercontent.com/1153561/163218563-6be5b3e6-fe34-4db3-a126-66db7679dc7a.gif)

**Comment by chrischain** [comment]
I found a few references in the VS Code source that might help shed some light on the way they do it:

- https://github.com/microsoft/vscode/blob/b2a7720f3f65f85607e5a70a1616217f8dadd39e/src/vs/editor/contrib/linesOperations/browser/linesOperations.ts
- https://github.com/microsoft/vscode/blob/1498d0f34053f854e75e1364adaca6f99e43de08/src/vs/editor/contrib/linesOperations/browser/copyLinesCommand.ts
- https://github.com/microsoft/vscode/blob/1498d0f34053f854e75e1364adaca6f99e43de08/src/vs/editor/contrib/linesOperations/browser/moveLinesCommand.ts

Hope that helps!

**Comment by hankinsoft** [comment]
Thanks for that. Unfortunately, it's a completely different codebase, so it doesn't really translate over. The main reason I haven't resolved it yet is because I was sick with covid for the last ~week, and I've also had trouble reproducing the issue. I think I know what's up, and I hope to have it resolved next week.

**Comment by chrischain** [comment]
Sorry to hear you've been sick... hope you're feeling better! If you need additional help testing, please let me know, I'm happy to help in any way I can.

**Comment by hankinsoft** [comment]
Could you send me one of the scripts you're seeing this with. I'm not able to reproduce and just want to see if anything in your script is the difference.

**Comment by chrischain** [comment]
I verified this script is doing the same thing on v2022.29 as the ones I used earlier to demonstrate.

FYI - I had to change the file extension from .sql to .txt to attach it...

[Search_Views_and_SPs_for_Text.txt](https://github.com/hankinsoft/SQLPro/files/8575122/Search_Views_and_SPs_for_Text.txt)

**Comment by hankinsoft** [comment]
K, I've kind of reproduced it... I'm only seeing it once in awhile, but hopefully thats enough.

**Comment by chrischain** [comment]
Cool, glad that helped!

**Comment by hankinsoft** [comment]
2022.37 has been approved by Apple earlier today which should fix this up.

**Comment by hankinsoft** [comment]
Just wanted to check in and see if the latest builds helped out with this? If your using the website build, it would be at https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.41.app.zip.

**Comment by hankinsoft** [comment]
Can you post a video of you reproducing it with the [Search_Views_and_SPs_for_Text.txt](https://github.com/hankinsoft/SQLPro/files/8575122/Search_Views_and_SPs_for_Text.txt) file you attached? I'm unable to reproduce it anymore, so if I can see the exact lines you highlight that might help.

**Comment by chrischain** [comment]
Sorry, was on vacation... just getting back into the swing of things. I'm now using 2022.50, and I'm not able to replicate the issue... perhaps you fixed it already??
