### ISSUE TITLE
Can't create new connections

### ISSUE THREAD

**Issue by gordroid** [hankinsoft/SQLPro#767]
Hi, I'm currently using SQLPro Studio Version 2022.28 (Build 110897.5)
I can't create new connections, and my older connections are gone. Couldn't find a way to restore to default. 
Deleted the app and reinstalled, even a restart, as suggested on https://github.com/hankinsoft/SQLPro/issues/759
Everything started a few weeks ago, when i wanted to delete the default `My Connections` group, I've created a couple of new groups, move all my connections to the new groups and deleted the default `My Connections` group, all went great up until i've to restart SQLPro Studio, the default `My Connections` group appear back again, after that all my connections re-arrenged again and i was not able to re-arrenged as i wanted. Then i tried to restore everything to default, clicked on `Default` button on preferences(i belive it only restored to default the keyboard shortcuts only), and clicked the `Clear all` button for saved connections. Now i cant add no more connections(only tested with Postgres connections).
<img width="1655" alt="Screen Shot 2022-04-12 at 22 50 13" src="https://user-images.githubusercontent.com/650441/163085272-2e3c5248-4c03-4849-828b-0d32cb9a7db9.png">

**Comment by hankinsoft** [comment]
Could you try creating a connection, then send me the log file? You can find it in 'View' -> 'Logs'.

**Comment by gordroid** [comment]
Hi Kyle,

Here you have:
[com.hankinsoft.osx.sqlprostudio 2022-04-13--13-15-09-405.log](https://github.com/hankinsoft/SQLPro/files/8481735/com.hankinsoft.osx.sqlprostudio.2022-04-13--13-15-09-405.log)

**Comment by hankinsoft** [comment]
Could you try opening keychain searching for `com.hankinsoft.sqlpro.connectionGroups` and delete that entry?

<img width="1043" alt="Screen Shot 2022-04-14 at 12 55 59 PM" src="https://user-images.githubusercontent.com/3160528/163427827-8cfe8488-d536-4739-9389-ad779b2a43e5.png">

(Close SQLPro first, then relaunch after). Try adding a connection after that and see if that works properly.

**Comment by gordroid** [comment]
hi Kyle, I did that yesterday, i deleted all the `iCloud` keychain entries (it didn't allow me to delete the 4 `login` keychain items), deleted the app from the applications directory, install again from app store, no luck.
Here you have the logs for my recent attempt after your suggestion:
[com.hankinsoft.osx.sqlprostudio 2022-04-14--15-59-43-792.log](https://github.com/hankinsoft/SQLPro/files/8490654/com.hankinsoft.osx.sqlprostudio.2022-04-14--15-59-43-792.log)
I was making changes on my connection while you were fixing stuff last month and my setup end up in a weird state i belive, is not an bug, but a weird state i belive, so i was thinking, what do i need to delete for a fresh install? Or if you want to try other stuff first let me know.

**Comment by gordroid** [comment]
after that test i search for the `com.hankinsoft.sqlpro.connectionGroups` entry on the keychain and it didn't exist, so i created a new group and that create the entry, after that i create a new connection to test, no luck.
<img width="1382" alt="Screen Shot 2022-04-14 at 13 13 51" src="https://user-images.githubusercontent.com/650441/163430687-8b66c58a-25d8-47ce-b805-2da608d66a61.png">

here you have the logs:
[com.hankinsoft.osx.sqlprostudio 2022-04-14--15-59-43-792.log](https://github.com/hankinsoft/SQLPro/files/8490712/com.hankinsoft.osx.sqlprostudio.2022-04-14--15-59-43-792.log)

**Comment by hankinsoft** [comment]
> (it didn't allow me to delete the 4 login keychain items),

Do you know which four it wouldn't let you delete? The other items that would need to be removed would be listed if you search for `RecentConnections`.

<img width="1043" alt="Screen Shot 2022-04-14 at 1 14 35 PM" src="https://user-images.githubusercontent.com/3160528/163430765-84a98538-6f11-4e93-974b-e20b34321516.png">

I would suggest deleting all of them to be in a fresh state. I also plan on doing a build with extra logging for you, but it won't be until next week. (I'm currently sick with covid, so I'm unfortunately not getting a lot done this week).

Do you have iCloud Keychain enabled on your system?

**Comment by gordroid** [comment]
Kyle, i was able to delete the 4 entries on the keychain, it looks that i couldn't delete as the search result, but i search for them under the `login` Default Keychain, and i was able to delete them.
So i deleted all the keycain entries, delete the app, and reinstall it from the app store again, open it and the connections were restored to the previous state the 2 empty groups and the test connections, the same weird state as before:
<img width="1382" alt="Screen Shot 2022-04-14 at 13 40 25" src="https://user-images.githubusercontent.com/650441/163434784-17cdd5ad-54f4-45f8-a73c-d63ad9ee1caa.png">
So the state was not a fresh new one, which is ood, i'm a really old user, can't remember when, but, there is not potentially any other file on my system that might be messing this up?

**Comment by hankinsoft** [comment]
You mentioned above that you had

> after that test i search for the com.hankinsoft.sqlpro.connectionGroups entry on the keychain and it didn't exist, so i created a new group and that create the entry, after that i create a new connection to test, no luck.

So if you didn't delete the `com.hankinsoft.sqlpro.connectionGroups` again, then that would cause the DDD to still exist.

And you still cannot create connections after deleting those four items? Weird question, but could you try a reboot and see if that helps?

> So the state was not a fresh new one, which is ood, i'm a really old user, can't remember when, but, there is not potentially any other file on my system that might be messing this up?

No, the connections are all stored in the keychain, nothing in filesystem for them.

**Comment by gordroid** [comment]
I did this: deleted the app, I deleted all keychain entries, even `com.hankinsoft.sqlpro.connectionGroups`, reinstall it and the groups were restored, so they are coming from somewhere.

**Comment by gordroid** [comment]
reboot didn't help either

**Comment by hankinsoft** [comment]
So odd. Ok, I'll be adding some extra debugging to a build and get it available for testing.

**Comment by gordroid** [comment]
hey Kyle, i think i find the issue, for some reason i can't see the original group `"groupId" : "my-connections"`

all the connections are being successfully created on that group, but i can see that group on the UI:
<img width="1382" alt="Screen Shot 2022-04-14 at 16 57 05" src="https://user-images.githubusercontent.com/650441/163466247-bded8706-ef7a-4494-aed6-5a59cfec2519.png">

`com.hankinsoft.sqlpro.connectionGroups`:
```
{
  "modifications" : [
    {
      "modifiedDate" : "2022-04-14 16:52:44",
      "productId" : "com.hankinsoft.osx.sqlprostudio"
    }
  ],
  "groups" : [
    {
      "groupId" : "my-connections",
      "groupIsCollapsed" : false,
      "groupName" : "My connections",
      "sortOrder" : 0,
      "groupEntries" : [
        {
          "connectionId" : "CD682FCB-D7B3-4C15-B424-F68EA57FD45C-1717-00000892D4989CF2",
          "sortOrder" : 0
        },
        {
          "connectionId" : "F3B4C393-E979-4BFB-93FD-0030E53FF6D2-24915-00026143DC5B43F9",
          "sortOrder" : 1
        },
        {
          "connectionId" : "9BE219EC-5D6A-4F0A-9D36-7148941DDDFC-71312-0000CDB0BD245D2A",
          "sortOrder" : 2
        },
        {
          "connectionId" : "2D0464CD-3D66-4CAA-8FE6-FC469D7A6391-26862-0000BABC74DCCAF9",
          "sortOrder" : 3
        },
        {
          "connectionId" : "FEBC3D84-CE90-40FB-97F1-96DF77ACD0A5-72187-0000CDC382D87910",
          "sortOrder" : 4
        },
        {
          "connectionId" : "59027287-DF23-44F3-B5FF-45517B5EB8D0-2477-0002742040DF9A0B",
          "sortOrder" : 5
        }
      ]
    },
    {
      "groupId" : "sample-servers",
      "groupIsCollapsed" : false,
      "groupName" : "Sample connections",
      "sortOrder" : 1000,
      "groupEntries" : [

      ]
    },
    {
      "groupId" : "7016E9C9-765E-40CB-B05D-18705DDD9F52",
      "groupIsCollapsed" : false,
      "groupName" : "ddd",
      "sortOrder" : 0,
      "groupEntries" : [

      ]
    },
    {
      "groupId" : "6979F82E-FB0F-494A-8243-6DD0FBEA64DB",
      "groupIsCollapsed" : false,
      "groupName" : "My connections",
      "sortOrder" : 0,
      "groupEntries" : [

      ]
    },
    {
      "groupId" : "C851BA32-DAE3-4880-81BB-B03B3383774F",
      "groupIsCollapsed" : false,
      "groupName" : "My connections",
      "sortOrder" : 0,
      "groupEntries" : [

      ]
    }
  ]
}
```

**Comment by hankinsoft** [comment]
Thats so odd.... There are only two entries showing in the json you sent, but there are three entries in your UI (include two `My connections`).

**Comment by hankinsoft** [comment]
Just had a thought. Could you try running https://freemacsoft.net/appcleaner/ on SQLPro Studio? If for some reason its unable to access iCloud, it would use `NSUserDefaults` to save/load connections. If thats the case, your previous question about file system would be correct, as those are stored on the file system. App Cleaner would take care of removing them.

**Comment by gordroid** [comment]
that totally worked! 🚀 
thanks Kyle for your help!
hope you feel better soon!!
