### ISSUE TITLE
Connecting to local forwarded port is prohibitively slow

### ISSUE THREAD

**Issue by cobyrne09** [hankinsoft/SQLPro#768]
I am using SQL pro to connect to a local port which is forwarded to through a bastion and to a RDS db with AWS session manager. 

Here is my connection string

```
ssh ubuntu@"${BASTION_ID}" -i /tmp/temp \
    -Nfq \
    -L "${LOCAL_PORT}":"${DB_HOST}" \
    -o "StrictHostKeyChecking=no" \
    -o "UserKnownHostsFile=/dev/null" \
    -o ProxyCommand="aws ssm start-session --target %h --document AWS-StartSSHSession --parameters portNumber=%p --region=<some region>" >/dev/null
```

In this configuration, connecting can take ~60 seconds, and opening the table/schema inspector on this sidebar seems to take an additional 60 seconds, although the data does (usually) ultimately load. Other SQL clients connections to these local ports are instantaneous. 

Connecting to local DB's which are not forwarded, using SQLPro as the client, are fine as well.

**Comment by hankinsoft** [comment]
Could you:
1. Clear the logs and close SQLPro.
2. Relaunch SQLPro and attempt to connect to a forwarded port.
3. Provide the logs.

Logs can be found by going to 'View' -> 'Logs'.
