### ISSUE TITLE
Better JSON result support

### ISSUE THREAD

**Issue by donwb** [hankinsoft/SQLPro#77]
Currently, it is very difficult to handle query results that return JSON.  The results are packed into a single column in the datagrid, making it difficult to assess the result.  In addition, exporting/copying it out into an external editor is problematic (\"\ get escaped, the entire result is wrapped in \"\).

SQLPro is my favorite sql editor, but I do a lot of JSON queries so any improvements here would be 👍

**Comment by hankinsoft** [comment]
> The results are packed into a single column in the datagrid, making it difficult to assess the result.

Hmmm, first which database type is this? Is there a specific column that maps to json, or is it text with json in it? What I'm able to to may depend on those a bit.

Also, any suggestions for an alternative way to display them? :)

**Comment by donwb** [comment]
I'm using Postgres, and do a lot of `json_agg` queries, which basically takes the results of the query itself and converts it into a JSON array.  In this case the entire result set is just a JSON string. 



Option 1 - have a text based output window that pretty-prints the JSON so i can easily see the result of the query.  But i totally get that this would take some work.

Option 2 - Make it so that when i copy the JSON out of the 1 row/1 column result set it's not being escaped that way i can easily copy it to a text editor and view it

I've attached a few screenshots to help illustrate
Thanks!

<img width="893" alt="screen shot 2017-02-09 at 9 03 21 am" src="https://cloud.githubusercontent.com/assets/532590/22786493/c5090086-eea6-11e6-90fe-21e353291a83.png">
<img width="766" alt="screen shot 2017-02-09 at 8 58 54 am" src="https://cloud.githubusercontent.com/assets/532590/22786494/c5095a36-eea6-11e6-9b28-4c24f8acfcd0.png">

**Comment by hankinsoft** [comment]
Would allowing you to expand json rows help? Something like this:

<img width="1073" alt="screen shot 2017-02-09 at 10 27 44 am" src="https://cloud.githubusercontent.com/assets/3160528/22787384/82d8940e-eeb2-11e6-882f-dbd244a92cae.png">

**Comment by donwb** [comment]
ya, this would be *much* better!

**Comment by hankinsoft** [comment]
Hi,
Can you give https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.113.app.zip a try? That should allow for the popover (in both cases) and also fix the copy from results grid issue.

**Comment by donwb** [comment]
Uh oh.. looks the same

<img width="1225" alt="screen shot 2017-02-10 at 2 46 50 pm" src="https://cloud.githubusercontent.com/assets/532590/22841543/03e1b164-efa0-11e6-9c2c-93e98a5d1011.png">

**Comment by hankinsoft** [comment]
If you mouse over the cell with data in it does a down arrow appear? Or nothing? Also if you copy the cell does it paste properly now?

**Comment by donwb** [comment]
ahh.. ya, my bad.  yes, the drop down appears and the data looks right...  copy/paste works!

awesome!

**Comment by hankinsoft** [comment]
Great! FYI, I'll add a future task to add some better json support (syntax highlighting, plus a maybe an option to view a clean version of the json), but no ETA on that at the moment.
