### ISSUE TITLE
[Feature Request]: Display sqlite_sequence table under "System Tables"

### ISSUE THREAD

**Issue by bwminick** [hankinsoft/SQLPro#771]
Hello,

Is it possible to show the **sqlite_sequence** table under the "**System Tables**" section in SQLPro for SQLite?  This would be really handy for setting the starting primary key value before adding a bunch of records into a new table.

Thank you much!  :-)

<img width="1512" alt="sqlite_sequence_table" src="https://user-images.githubusercontent.com/77753152/164996864-96369793-6b53-4730-bf61-5fde8733033f.png">

_P.S. - No worries about privacy, as the personal info shown above is fictitious._

**Comment by hankinsoft** [comment]
Fixed for the next build. Fun fact - it actually used to show sequences but I broke it some time ago.   Are you using the website, App Store, or setapp build?

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.31.app.zip if your using the website build.
