### ISSUE TITLE
Creating Stored Procedures

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#773]
Should I be able to create a stored procedure via SQLPro?

OS: MacOS Catalina 10.15.7
Software: SQLPro Oracle Version 2022.30 (Build 510.5)
Connection: Oracle 19

When I attempt to create the following **stored procedure** with the code below it produces several errors in SQLPro, but it runs just fine in SQL Developer.
```
create or replace PROCEDURE SEQUENCE_SETTO(p_name IN VARCHAR2, p_val IN NUMBER)
AS
   l_num   NUMBER;
BEGIN
   EXECUTE IMMEDIATE 'select ' || p_name || '.nextval from dual' INTO l_num;

   -- Added check for 0 to avoid "ORA-04002: INCREMENT must be a non-zero integer"
   IF (p_val - l_num - 1) != 0
   THEN
      EXECUTE IMMEDIATE 'alter sequence ' || p_name || ' increment by ' || (p_val - l_num - 1) || ' minvalue 0';
   END IF;

   EXECUTE IMMEDIATE 'select ' || p_name || '.nextval from dual' INTO l_num;

   EXECUTE IMMEDIATE 'alter sequence ' || p_name || ' increment by 1 ';

   DBMS_OUTPUT.put_line('Sequence ' || p_name || ' is now at ' || p_val);
END;
```

```
ORA-06550: line 2, column 35:
PLS-00201: identifier 'P_NAME' must be declared
ORA-06550: line 2, column 4:
PL/SQL: Statement ignored
ORA-06550: line 5, column 8:
PLS-00201: identifier 'P_VAL' must be declared
ORA-06550: line 5, column 4:
PL/SQL: Statement ignored
ORA-06550: line 10, column 35:
PLS-00201: identifier 'P_NAME' must be declared
ORA-06550: line 10, column 4:
PL/SQL: Statement ignored
ORA-06550: line 12, column 43:
PLS-00201: identifier 'P_NAME' must be declared
ORA-06550: line 12, column 4:
```

**Comment by hankinsoft** [comment]
Try changing:

>   l_num   NUMBER;

To

>   l_num   NUMBER

(remove the semicolon)

I think this is an issue on my end, but that should at least get you working.

**Comment by hankinsoft** [comment]
What do you mean by they won't compile? I don't know much about oracle..... is there a command I need to run to compile a procedure?

**Comment by cwolcott** [comment]
In most other IDEs I have dealt with they automatically perform the compile after creating the stored procedure.   Of course I can issue the same command. It looks like the format is:
`ALTER PROCEDURE SEQUENCE_SETTO COMPILE; `

https://docs.oracle.com/en/database/oracle/oracle-database/21/lnpls/ALTER-PROCEDURE-statement.html

_Use the ALTER PROCEDURE statement to explicitly recompile a standalone stored procedure. Explicit recompilation eliminates the need for implicit run-time recompilation and prevents associated run-time compilation errors and performance overhead._

Having the IDE show invalid compilations is nice.

**Comment by hankinsoft** [comment]
I've submitted a build which I think should sort the procedure creation out.

**Comment by cwolcott** [comment]
Works well, thank you.  I may add a couple of feature requests relating to Stored Procedures later as an issue.
