### ISSUE TITLE
Recent Files

### ISSUE THREAD

**Issue by scriptebob** [hankinsoft/SQLPro#776]
When I first open SQLPro that window opens with a list of what appears to be recently opened files. Except, almost every time, the file I just had open is not in the list. 

Is it just me or is it some bug/feature?

**Comment by hankinsoft** [comment]
Hi - recent files are stored by the system and it resets them each time a new version of the app is released. I had released a bunch of versions in a row while sorting a few items, so they would have unfortunately, been removed a bunch of times. This shouldn't happen as often in the future.
