### ISSUE TITLE
Can no longer create views

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#778]
I can no longer create views?

OS: MacOS Catalina 10.15.7
Software: SQLPro Oracle Version 2022.31 (Build 511.5)
Connection: Oracle 19

I have previously be able to create views on SQLPro for Oracle, but can no longer.  Execute each statement seperately so you can see what is happening.

- Create Table works jut fine,
- Insert records works just fine,
- Create View disconnects from database with create view

```
--------------------------------------------
CREATE TABLE Tab_ABC (
	COL_A    VARCHAR2(25) NOT NULL,
	COL_B    VARCHAR2(25) NOT NULL
);

--------------------------------------------
INSERT ALL 
   INTO Tab_ABC VALUES (  'A', 'X')
   INTO Tab_ABC VALUES (  'B', 'Y')
   INTO Tab_ABC VALUES (  'C', 'Z')
 SELECT 1 FROM DUAL;
   
--------------------------------------------
CREATE VIEW View_ABC AS
   SELECT COL_A, COL_B FROM Tab_ABC;
```

Attached is the log for jut these three commands
[com.hankinsoft.osx.sqlpro.oracle 2022-04-29--17-39-00-627a.log](https://github.com/hankinsoft/SQLPro/files/8592656/com.hankinsoft.osx.sqlpro.oracle.2022-04-29--17-39-00-627a.log)

**Comment by hankinsoft** [comment]
Can you check if the latest build (2022.33) fixes this?

**Comment by cwolcott** [comment]
No it does not.  Attached is the log
<img width="631" alt="image" src="https://user-images.githubusercontent.com/3777526/167511427-5199a32b-5498-4c88-a328-cee3ec5790ce.png">
[com.hankinsoft.osx.sqlpro.oracle 2022-05-09--22-54-24-981.log](https://github.com/hankinsoft/SQLPro/files/8655877/com.hankinsoft.osx.sqlpro.oracle.2022-05-09--22-54-24-981.log)

**Comment by cwolcott** [comment]
Any process?  I just noticed I can't create tables either. SO I am installing another 3rd party product so I can continue working today.

**Comment by hankinsoft** [comment]
Can you try the latest build (2022.34) that should sort it out.

**Comment by cwolcott** [comment]
Build (2022.34) resolved the issues
