### ISSUE TITLE
Disconnect do not work with active filter on

### ISSUE THREAD

**Issue by YvesR** [hankinsoft/SQLPro#78]
Hello,

while on the server list a active filter is used it is not possible to right click on the server and click on disconnect. I have to remove the filter first to disconnect a server.

Kind regards,
Yves Rausch

**Comment by hankinsoft** [comment]
Hi,
This was fixed a few versions ago. If you get the chance, please consider giving it a try.

**Comment by YvesR** [comment]
Hello,

unfortunately not.
I filter in tables, click on disconnect but nothing happens.

Check my screenshot to clarify.

![Bildschirmfoto 2019-03-29 um 08 44 28](https://user-images.githubusercontent.com/4928882/55217766-9d0f1600-5200-11e9-850d-94fa5d0446c5.png)

**Comment by hankinsoft** [comment]
Hi,
Which version of SQLPro are you using? And is it from the Mac App Store, or
website? If possible, could you send a screenshot of the 'about' dialog?

Thanks!

**Comment by YvesR** [comment]
From App-Store

![Bildschirmfoto 2019-03-29 um 12 42 39](https://user-images.githubusercontent.com/4928882/55230454-2c77f180-5220-11e9-9f82-bf9cbe506ea8.png)

**Comment by hankinsoft** [comment]
Thanks! I see now, I didn't update SQLPro Studio in the App Store. The
update has been submitted and should be available by the end of the weekend.

**Comment by YvesR** [comment]
Ah ok, then I will check when it is available.

**Comment by hankinsoft** [comment]
Hi, the new version is available. If you get the chance, could you give it a try? Thanks!

**Comment by YvesR** [comment]
Hi, I can confirm it works now. Thanks.
