### ISSUE TITLE
[Feature Request:] Please remove "Themes" from the "Documents" folder.

### ISSUE THREAD

**Issue by milke** [hankinsoft/SQLPro#780]
I've just discovered **SQL Pro Studio** and I find it to be an excellent tool. I'm in a trial period and I'm considering purchasing a lifetime license, which I'll probably do. But I have one very small request. It seems you put `Themes` folder in the (sandboxed) user's `Documents` folder, which then ends up in `~/Library/Containers/com.hankinsoft.osx.sqlprostudio/Data/Documents`. However, that automatically adds a reference to it in the `~/Documents` folder, see attached picture.

I really don't want to see anything in my `~/Documents` I didn't put myself in there. Besides, themes don't really sound like something that should go into the `Documents` folder, `Application Support` (or something similar) sounds like much better solution.

Thanks for considering this and keep up the great work!

<img width="598" alt="documents" src="https://user-images.githubusercontent.com/291305/166249049-62ca6d1b-7a29-4c24-b531-94cc4313185a.png">

**Comment by El-Ekim** [comment]
I agree with Mike. I tried to hide the folder Themes in 
~/Library/Containers/com.hankinsoft.osx.sqlprostudio/Data/Documents
That does work but now I have an empty SQLProStudio folder in my Documents folder.
Any suggestions on how to hide that one as well?

**Comment by hankinsoft** [comment]
I can take a look into moving themes for a future build as it would make sense for those to be part of application support, but just as an FYI other items such as favourites can also be stored in the documents directory in certain contains.

**Comment by hankinsoft** [comment]
Decided not to move these at the moment as documents is a require location for them to be shared via iCloud 9(when using sqlpro on multiple systems).

**Comment by m-thomson** [comment]
@hankinsoft 

Apps should not write anything to the Documents folder without permission. Please remove this cruft - it's a terrible practice and nobody else does it. I have over 50 apps from Setapp currently installed and over 160 on my system in total. None of them do this except yours. Not one.

Seriously. Please. Allow the user to specify the location or use the appropriate `~/Library/...` folder.

Related: https://github.com/hankinsoft/SQLPro/issues/723

**Comment by milke** [comment]
As a fellow developer, one of the customer feedbacks I hate the most (to the extent that I even try to completely ignore them if possible) is "this is a great application, but I will buy/purchase it only if you implement _that_and_that_…". Unfortunately, I ended up in a similar situation (as a customer) in this case. In my defence, I'm not asking for a feature, but for a change in behaviour, which I find to be a borderline bug; the application messes with some file location(s) where it has no business at all!

As stated in my initial post here, more than a year ago, I was damn serious about purchasing lifetime license for the product and I wouldn't even mind paying some upgrade costs from time to time. Instead, I opted for a monthly subscription, waiting to see how this issue will be resolved. I cancelled the subscription only after 2 (or was it maybe 3) months, because I effectively stopped using the application. All bells and whistles it brings were comfortably outweighed by my frustration every time I went into the _~/Documents_ folder (and I go there MANY times a day).

It's really a shame, since the application is great otherwise and the implementation of the change isn't complicated nor time consuming at all.

**Comment by hankinsoft** [comment]
I'll be away until late next week, but I'll re-evaluate this at that point.

**Comment by El-Ekim** [comment]
Adobe, FL Studio, Native Instruments all adds a folder (with lots of subfolders) in the Documents folder. SQL Pro doing this is not unique. Happily I managed to hide them all. 
It doesn't bother me now but I do like the luxury of being able to choose the folder myself ;)
I love SQL Peo Studio and a extra folder in my Documents folder is not going to change that.

**Comment by hankinsoft** [comment]
My plan is to move the themes into a folder under the applications '/Library/Themes' folder. Does anyone have any concerns with that?

**Comment by milke** [comment]
> My plan is to move the themes into a folder under the applications '/Library/Themes' folder. Does anyone have any concerns with that?

Not me.

**Comment by El-Ekim** [comment]
Sounds great.

**Comment by m-thomson** [comment]
Thanks for taking this up @hankinsoft !

**Comment by hankinsoft** [comment]
A build has been submitted to setapp which should resolve this. A website build is of SQLPro Studio also available at https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2023.55.app.zip. The App Store build should be available sometime next week.

**Comment by hankinsoft** [comment]
The App Store version of SQLPro studio now includes this as well.
