### ISSUE TITLE
Lost License Key

### ISSUE THREAD

**Issue by cpitzak** [hankinsoft/SQLPro#781]
Hello,

My work bought me a license to SQLPro a few years back (lifetime). The Mac that it was on had a hardware failure. We fixed the Mac but we lost all the data. How do the license key? What information do you need and who do I send it to?

**Comment by hankinsoft** [comment]
Hi, I would need to know the email address. You could either post it here or send it to kyle@hankinsoft.com.

**Comment by cpitzak** [comment]
Thanks!
