### ISSUE TITLE
Blob data doesnt showing

### ISSUE THREAD

**Issue by iamcodder** [hankinsoft/SQLPro#784]
Hello,

I'm using the SQL Pro for Oracle but the showing my blob data null. When I use the another sql tool (toad etc.),showing my blob data.

**Comment by hankinsoft** [comment]
I've been unable to reproduce this - is there any chance you could privide a sample 'create table' + 'insert' statement which you are able to reproduce this with?

**Comment by hankinsoft** [comment]
If you get a chance to post some statements which can reproduce this, please let me know as I have been unable to as of yet.
