### ISSUE TITLE
Drop instruction in a table doesn't work

### ISSUE THREAD

**Issue by cvillalobos** [hankinsoft/SQLPro#788]
I incorrectly ran a script that defined double schema in the table name. Something like: "testing.dbo.testing_table""

When trying to run the drop table option, it visually seems like the table has been deleted, however, when refreshing the tables it shows again the table. When running the drop command through script it says like the user doesnt have access to it. I assumme it simply cannot interpret "double schema" indication.

**Comment by hankinsoft** [comment]
Hi,
A few questions:

1. What type of database is this? (MySQL, SQL Server, etc).
2. Could you post the script you are running to drop the table?
3. 'When trying to run the drop table option' do you mean via the database tree context menu?

**Comment by cvillalobos** [comment]
1. This is SQLServer.
2. It was not a script. It was through the right-click option.
3. Yes, the UI tree context menu.

Happening when (by mistake) the table name had two dot separation on its name like: "partA.partB.name", In my case was: "cvillalobos_admin.dbo.users"

**Comment by cvillalobos** [comment]
No problem at all. The application works just fine and I have another machine on which I can proceed with that action if needed.
Thanks.
