### ISSUE TITLE
Features for Exporting Structure / Data?

### ISSUE THREAD

**Issue by tblanchard** [hankinsoft/SQLPro#79]
SequelPro (mysql) has a really nice tool for doing data and structure dumps.

While it is very nice that csv and sqlite exports are supported, not having a UI over pg_dump that allows me to clone a database structure or even make a dump file for backups seems like a glaring oversight.

**Comment by hankinsoft** [comment]
So just to confirm, you would like a dump option that does full table
structures, indexes,  foreign keys, etc.  along with all the data?  Would
that do the trick?

**Comment by tblanchard** [comment]
Options to dump just structure or structure and data or just data.

Basically the options available in Sequel Pro.

Picture:
https://monosnap.com/file/1E0jr3rDRisL7uMaxaxs7ISWCumKlp

**Comment by MisterPeepers** [comment]
+1 +1 

Love this tool vs Oracle but constantly have to go back and forth due to this.

**Comment by hankinsoft** [comment]
Closing this as a copy of #101 as that has more follows. I've been working on export (so far MSSQL is completed) and I'll be working on adding the other servers soon.
