### ISSUE TITLE
Unable to delete/remove connections - 2022.34 (Build 110902)

### ISSUE THREAD

**Issue by pilotgeraldb** [hankinsoft/SQLPro#790]
### Hardware:
MacBook Pro (13-inch, M1, 2020)
16GB Ram

### Software:
Mac OS 12.4
SQL Pro Studio Version 2022.34 (Build 110902)
Downloaded the app via [SetApp](https://setapp.com/)

### Issue:
From the connections screen, I am unable to delete/remove connections. I get all the prompts that ask if I am sure, but then nothing happens.

Please note, I can successfully add and duplicate without issue. This only happens with deletion of a connection.

**Comment by hankinsoft** [comment]
Do you have iCloud Keychain enabled?

**Comment by alexio777** [comment]
Version 2022.35 (Build 110903.5)
Mac OS 12.3.1 (21E258)

Im unable to remove connections too.
Keychain is enabled.

**Comment by hankinsoft** [comment]
I've figured out what going on. I'll have the build submitted within a few hours which usually makes it available in about ~24 hours or so.

**Comment by pilotgeraldb** [comment]
Confirmed, my issue is resolved!!

**Comment by hankinsoft** [comment]
Thanks for letting me know!
