### ISSUE TITLE
[MongoDB] authSource is broken

### ISSUE THREAD

**Issue by neoromantique** [hankinsoft/SQLPro#791]
When applying authSource to the mongodb without specifying a database following error message appears:
```
    Connection failed.
    Invalid host string in URI
```

It works as expected if database is provided, however that limits the scope to that database, even if user has access to more that one.

If authSource is not provided, then current database is used, which means that user should be added to every single database, rather than being specified only in Admin. 

`Version 2022.36 (Build 110904)`

Thanks!

**Comment by hankinsoft** [comment]
Can you reproduce the issue, then open the log file (found via 'View' -> 'Logs').
Search the log file and you should find:

MongoDB connection string is: xxxxxxxx

Where xxxxxx is the generated connection string (with the password removed).

Could you post both the working connection string and the failing connection string?

**Comment by hankinsoft** [comment]
Just wanted to check and see if you've had a chance to get the connection strings?

**Comment by neoromantique** [comment]
Sorry, couldn't do it earlier.

This is Auth source specified, but Database empty.
```mongodb://username:password@172.20.0.2?authSource=admin```

If I specify database(any), then it works, but that limits the scope only to that database, which is not ideal and breaks my workflow for example.

**Comment by hankinsoft** [comment]
Could you try this version:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.41.app.zip

And see if you reproduce the same behaviour?

**Comment by hankinsoft** [comment]
Could you give https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.43.app.zip a try? I think that will sort it out.

**Comment by neoromantique** [comment]
That works! :)
