### ISSUE TITLE
[Feature request] Restore tabs from previous session

### ISSUE THREAD

**Issue by yoktan** [hankinsoft/SQLPro#792]
I'm writing this as a feature request, but perhaps it's already supported and just not working for me.

When relaunching SQLPro I would appreciate it if it would restore all the tabs (and their order) from my previous session (from when I last quit the app).

Currently it seems to do this with only some tabs (the ones I haven't explicitly saved — although it's not systematic… or I haven't figured out the logic). In any case, it would be great if it did with all the previously open tabs.

Thank you

**Comment by hankinsoft** [comment]
What is your `app shutdown` state set as in the preferences?

<img width="545" alt="Screen_Shot_2022-05-31_at_10_55_16_AM" src="https://user-images.githubusercontent.com/3160528/171191030-c1dfb04f-9786-4247-a36d-578cad84564c.png">

If it's set to 'save state', then all tabs should restore.

**Comment by yoktan** [comment]
Thanks Kyle! I'm already in "Save state" but only some tabs restore — mainly those which were auto-saved. But my whole set of key/standard tabs is never restored. I have to reopen it every time and then reshuffle all the tabs because the ones which reappeared appear first and that's not where I want them. It gets tedious after a while…

**Comment by hankinsoft** [comment]
The next time you see this, could you open up the logs via 'View' -> 'Logs' and look for the latest entry of:

> restoreUIState - Started restoring. App recovery URL is xxxxxxxx

Then open the xxxxxxxxx folder and send me the contents along with the log file? (You can send them to kyle @ hankinsoft.com).

That should help me figure out why it's not restoring properly.

**Comment by yoktan** [comment]
Hi. I wonder if this doesn't have to do with permissions on the directory where my files are. Recently SQLPro started telling me that it couldn't auto-save some of my documents for lack of permissions. 
What should my perms be? I have them set to 755 for staff and myself.
Note: I'm on Monterey (12.2.1)

**Comment by hankinsoft** [comment]
The 755 should be correct. Are you still seeing this issue where they do not restore? Is it all the time or some of the time?

**Comment by hankinsoft** [comment]
Are you still running into this issue?  Is it all the time or some of the time?
