### ISSUE TITLE
MySQL Constraints Query

### ISSUE THREAD

**Issue by poorlymac** [hankinsoft/SQLPro#793]
Hi Kyle,

As a background we have a lot of schemas that are the same, over 100, on our database. i.e. it is a schema per client.

With the latest release Version 2022.37 (Build 110905.5) and RDS MySQL 8.0.29 I noticed a new issue which is this query SQLPro is sending doesn't seem to return in a reasonable time (I give up it takes so long, 1,000's of seconds waited). The query in question is:
`SELECT
  DISTINCT
  i.TABLE_NAME,
  i.CONSTRAINT_TYPE,
  i.CONSTRAINT_NAME,
  k.REFERENCED_TABLE_NAME,
  k.REFERENCED_COLUMN_NAME,
  k.COLUMN_NAME,
  c.UPDATE_RULE,
  c.DELETE_RULE,
  k.ORDINAL_POSITION
FROM
  information_schema.TABLE_CONSTRAINTS i
INNER JOIN
  information_schema.KEY_COLUMN_USAGE k ON i.CONSTRAINT_NAME = k.CONSTRAINT_NAME
INNER JOIN
  information_schema. REFERENTIAL_CONSTRAINTS c ON c.CONSTRAINT_NAME = k.CONSTRAINT_NAME
WHERE i.CONSTRAINT_TYPE = 'FOREIGN KEY'
AND i.TABLE_SCHEMA = DATABASE()
ORDER BY k.ORDINAL_POSITION ASC`

The tables in question aren't really that big and we have a large server so I dont know what MySQL is doing wrong:
`SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS -- 20,162
;
SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE -- 21,738
;
SELECT COUNT(*) FROM information_schema.REFERENTIAL_CONSTRAINTS -- 11,135
;`
I get that its probably doing a multiplier but even then I thought it should be slow but still return fairly fast anyways.

However I think you actually  need to optimise the query to pass through the table schema name in addition, i.e.
`SELECT
  DISTINCT
  i.TABLE_NAME,
  i.CONSTRAINT_TYPE,
  i.CONSTRAINT_NAME,
  k.REFERENCED_TABLE_NAME,
  k.REFERENCED_COLUMN_NAME,
  k.COLUMN_NAME,
  c.UPDATE_RULE,
  c.DELETE_RULE,
  k.ORDINAL_POSITION
FROM
  information_schema.TABLE_CONSTRAINTS i
INNER JOIN
  information_schema.KEY_COLUMN_USAGE k ON i.CONSTRAINT_NAME = k.CONSTRAINT_NAME AND i.table_schema = k.table_schema
INNER JOIN
  information_schema.REFERENTIAL_CONSTRAINTS c ON c.CONSTRAINT_NAME = k.CONSTRAINT_NAME AND c.constraint_schema = k.table_schema
WHERE i.CONSTRAINT_TYPE = 'FOREIGN KEY'
AND i.TABLE_SCHEMA = DATABASE()
ORDER BY k.ORDINAL_POSITION ASC;`
This query with the schema returns in 3.5s for me.

CHEERS
Paul

**Comment by hankinsoft** [comment]
Thank you - fixed for the next build which I will get submitted later today.

**Comment by hankinsoft** [comment]
I forget, do you use the App Store, or website build?

**Comment by poorlymac** [comment]
App Store, but I can also grab website no issue

**Comment by poorlymac** [comment]
Note I also set global innodb_stats_on_metadata=0; as per https://www.percona.com/blog/2011/12/23/solving-information_schema-slowness/ but it is still slow.

**Comment by poorlymac** [comment]
FYI I modified my MySQLBackingQueries.plist temporarily, I assume you have done List_ForeignKeysForTable as well as List_AllForeignKeys ?

**Comment by poorlymac** [comment]
So with the updated query I was still getting poor performance of around 50 seconds 😡. So I tried all sorts of the usual optimisations, filtered subqueries, even CTE's in MySQL 8, but all to no avail. However I did notice that its the final join to REFERENTIAL_CONSTRAINTS where everything falls apart so this oddity actually works perfectly and I think still meets the need, now running in less than 1 second:

SELECT
  i.TABLE_NAME,
  i.CONSTRAINT_TYPE,
  i.CONSTRAINT_NAME,
  k.REFERENCED_TABLE_NAME,
  k.REFERENCED_COLUMN_NAME,
  k.COLUMN_NAME,
  (SELECT c.UPDATE_RULE FROM information_schema.REFERENTIAL_CONSTRAINTS c WHERE c.CONSTRAINT_NAME = k.CONSTRAINT_NAME AND c.CONSTRAINT_SCHEMA = k.TABLE_SCHEMA) UPDATE_RULE,
  (SELECT c.DELETE_RULE FROM information_schema.REFERENTIAL_CONSTRAINTS c WHERE c.CONSTRAINT_NAME = k.CONSTRAINT_NAME AND c.CONSTRAINT_SCHEMA = k.TABLE_SCHEMA) DELETE_RULE,
  k.ORDINAL_POSITION
FROM
  information_schema.TABLE_CONSTRAINTS i
INNER JOIN
  information_schema.KEY_COLUMN_USAGE k ON i.CONSTRAINT_NAME = k.CONSTRAINT_NAME AND i.TABLE_SCHEMA = k.TABLE_SCHEMA
WHERE i.CONSTRAINT_TYPE = 'FOREIGN KEY'
AND i.TABLE_SCHEMA = DATABASE()
ORDER BY k.ORDINAL_POSITION ASC

Note I removed the DISTINCT as it should be unnecessary, and perhaps a LIMIT 1 on the SELECT (SELECT)'s would make it perfectly safe.

**Comment by poorlymac** [comment]
ping -v kyle

🤣

**Comment by hankinsoft** [comment]
Can you grab https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.41.app.zip and give it a try?

**Comment by poorlymac** [comment]
Hi Kyle, Thanks, tested and it works as expected !

**Comment by poorlymac** [comment]
Note that column sorting in release 2022.41 is broken

**Comment by hankinsoft** [comment]
Thanks - https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.43.app.zip should fix the sorting.
