### ISSUE TITLE
Feature Request: Big Query Integration

### ISSUE THREAD

**Issue by MYRepoMan** [hankinsoft/SQLPro#798]
Hi - Hoping a Google Big Query integration is on the list of  possible connections for SqlPro Studio. If its possible today can you share how? 

Matt

**Comment by hankinsoft** [comment]
Hi. Unfortunately it's not currently possible and it's also not something I can currently put a timeframe on. There is an open issue to add it in [here](https://github.com/hankinsoft/SQLPro/issues/612).
