### ISSUE TITLE
SQLPro for MSSQL doesn't restore state when it (un)expectedly exits

### ISSUE THREAD

**Issue by sumanyu** [hankinsoft/SQLPro#80]
Sublime + just about any other editor will continually flush data to disk so user doesn't lose data. I've had cases where the client just craps out and I lose my unsaved ad hoc queries. This is a pretty major flaw in the product.

**Comment by hankinsoft** [comment]
Hmm, the app should already be doing this. You are seeing no tabs restored when the product crashed? Were the tabs existing files or temporary queries (both should be restored).
