### ISSUE TITLE
Unable To Insert CSV Files

### ISSUE THREAD

**Issue by abdul380-git** [hankinsoft/SQLPro#802]
I'm having challenges inserting csv files into mysql. However I had no problems inserting these files using DBeaver or VSCode. Please help. I wish to request that I send you this file to try so that I learn how you were able to insert it or what the problem is and how to address it. 

Just to clarify, I tried to upload using the Postgres dababase and it was successful. What could be the reason why I can upload a csv file on Postgres but not on mysql?

Thank you.

**Comment by hankinsoft** [comment]
Closed, as the required template was not followed. If you wish to re-open, please re-create the issue and follow the template.
