### ISSUE TITLE
Feature Request: Force to readonly DB

### ISSUE THREAD

**Issue by yeysman** [hankinsoft/SQLPro#803]
Hello,
I would like to have an option that allows forcing any connection to "read-only" (even if we have full access).
The reason for that is to avoid running mistakenly called statements that affect data. 

The idea here, once we enabled "readonly" for connection and trying to run any statements which affect DB data/structure (INSERT, UPDATE, MERGE, DELETE, ALTER etc) application should ask for the confirmation before run (something like: " Connection is read-only, but your query contains modification actions." and then two buttons: "Cancel" and "Run" )

Could you please review my request and let me know if it is possible to add such functionality to the SQLpro?

**Comment by hankinsoft** [comment]
Hi,
This is something I've been working on but do not currently have an ETA. Just to check, what type of database are you using (mysql, postgres, sql server, etc)?

**Comment by yeysman** [comment]
Hello @hankinsoft,
First of all, thank you for the feedback.
Mostly I work with sql server. But from to time, I switch to the mysql.

**Comment by hankinsoft** [comment]
I'm working on this for the next build. All connections will have a 'readonly' checkmark when editing the connection. If this is checked, all UI options to modify the database will be removed. This however <WILL NOT> prevent the user from manually running code from making a modification.

**Comment by hankinsoft** [comment]
The latest build now has the 'readonly' option when modifying a connection. If you notice any issues with this, please let me know. Again, it will <ONLY> remove the UI elements from the app as SQLPro is unable to put your database in a true readonly mode.
