### ISSUE TITLE
Filtering query results causes crash

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#804]
After executing a query and seeing the results panel display the results, the app always crashes if I try to filter the results via either CMD + Shift + F or clicking the "Filter" context menu option. Log only shows:

```
2022/06/20 20:02:46:893  Application is becoming active.
2022/06/20 20:02:47:778  Current document is: <SQLDocument: 0x13dedecd0>
2022/06/20 20:02:47:778  Showing filter view.

```

SQLPro Studio 2022.45 (Build 110913.5)
Snowflake 6.19.0
macOS 12.4 (21F79)

**Comment by hankinsoft** [comment]
Thanks, bug fix submitted.

**Comment by hankinsoft** [comment]
Just to confirm, this is all fixed in the latest build?

**Comment by jim256** [comment]
Yep, looks to be squared away. Thanks!
