### ISSUE TITLE
Feature Request: new document with current database

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#806]
When I open or create a new document, a need to set the Server/Database again. Is it possible to set this automatically from the current document?

**Comment by hankinsoft** [comment]
Could you send a video of what you are seeing? It should do this automatically, so a video would help me figure out what's up.

**Comment by hankinsoft** [comment]
Fixed for the next build.

**Comment by hankinsoft** [comment]
The latest build is up which should sort this out. Please give it a try and let me know.

**Comment by hankinsoft** [comment]
If you get the chance, can you check the latest build and confirm that the behaviour works as expected? Thanks!

**Comment by jim256** [comment]
Works great for me!
