### ISSUE TITLE
File operations not always working.

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#807]
Sometimes I find that after a while I can no longer save, close or open documents either with shortcut keys or through the menu. If, for example, I try to close a document, using the shortcut, close button or menu, the menu item highlights, but nothing else happens.

Everything is OK after I quit and restart.

I cannot reproduce this reliably, so I don’t know what I have done to trigger this.

**Comment by hankinsoft** [comment]
There [used to be an issue with older versions if macOS](https://github.com/hankinsoft/SQLPro/issues/99) where users would lose the ability to save after so many file operations, but your not seeing any error messages, just no saving?

When you see this again, could you attempt to save, then 'View' -> 'Logs' and post the log here?

**Comment by hankinsoft** [comment]
Please post the logs and re-open once you are able to reproduce this.
