### ISSUE TITLE
Confirm on close tab (Are you sure?)

### ISSUE THREAD

**Issue by tstrilch** [hankinsoft/SQLPro#808]
Can this be a configurable option? I use SQLPro Studio for the Mac and when too many tabs are open I sometimes accidentally close tabs by clicking on them (the "X" takes up most of the tab). I've been trying to switch to command-[ and command-] to move one tab to the left or right, but if I want to select a tab that's far from my current tab I have to surgically select the few pixels on the bottom right so it doesn't close by mistake.

**Comment by hankinsoft** [comment]
Hi,
Sorry I'm not exactly sure what your asking. What do you want to happen when you click the x button?

**Comment by jim256** [comment]
If I try to close a tab, it prompts me with this if I've edited it
![image](https://user-images.githubusercontent.com/15026225/177642122-5127e5a1-b800-4304-980a-06398c2a4c0f.png)

SQLPro Studio 2022.48 (Build 110917.5)

**Comment by tstrilch** [comment]
Maybe I just need to upgrade. I'm using: Version 2021.38 (Build 110792.5)

When I click the "X" it simply closes the tab without warning.

Cheers,
Todd.

**Comment by hankinsoft** [comment]
Might have reproduced this - if I open a file from the file system and make a change and close, I am not prompted. This is default macOS behaviour. What I'm thinking of doing is making the minimum width for tabs larger - that way there is always a bit more room and you can avoid the close button easier. Would that be helpful?

**Comment by hankinsoft** [comment]
Added for the next build:

![CleanShot 2022-07-14 at 12 54 01](https://user-images.githubusercontent.com/3160528/179024833-5b93cce3-843a-408e-b10d-8effceba79cd.gif)

Should be available sometime next week.

**Comment by tstrilch** [comment]
That's awesome. And there's no way to override the close tab in MacOS to
add an "are you sure" prompt?

Cheers,
Todd.

**Comment by hankinsoft** [comment]
> And there's no way to override the close tab in MacOS to
> add an "are you sure" prompt?

Not currently. It's not something I would change without many users requesting it.

I've added the right click, switch to tab for the latest build (2022.51). If you get the chance, can you see if it works as expected?
