### ISSUE TITLE
Azure SQL Data Warehouse issues with SQLPro for MSSQL

### ISSUE THREAD

**Issue by dnln** [hankinsoft/SQLPro#81]
I've recently been using SQLPro for MSSQL with [Azure SQL Data Warehouse](https://azure.microsoft.com/en-gb/services/sql-data-warehouse/). 

Most of the functionality works well, however in a few scenarios I get variations of the following error:

```
Msg 103010, Level 16, State 1.
Parse error at line: 2, column: 5: Incorrect syntax near 'ANSI_NULLS'.
```

Recently this has happened in two different scenarios:

1. When I select a query and run it. If I then unselect it and run it again the error message usually disappears and the query runs successfully. 
1. When I try and connect to the SQL Data Warehouse with a read only user and specify the database I want to connect to.

**Comment by hankinsoft** [comment]
Hi,
If you run the query:

SELECT @@VERSION

(on the sql data warehouse) What do you get for output?

Thanks!

**Comment by dnln** [comment]
Thanks for getting back to me. I get `Microsoft Azure SQL Data Warehouse - 10.0.9009.5 Feb 23 2017 23:55:50 Copyright (c) Microsoft Corporation`

**Comment by hankinsoft** [comment]
Thanks! A few more questions.

1. What product are you using (SQLPro for MSSQL or SQLPro Studio)?
2. Where from? (Website, App Store, SetApp)?

3. Does the following query succeed, or do you get another error? If you
get an error, could you attempt eliminating options until it succeeds and
let me know what you are left with?

SET QUOTED_IDENTIFIER, CONCAT_NULL_YIELDS_NULL, ANSI_WARNINGS,
ANSI_PADDING, ANSI_NULL_DFLT_ON ON

SELECT 1

Thank again!

Cheers,
Kyle

**Comment by dnln** [comment]
Sorry for the delay in replying Kyle, and thanks for you help with this. To answer your questions:

1. I'm using SQLPro for MSSQL (Version 1.0.136 Build 4287)
2. From the website
3. It does error. If I remove the settings one by one until it works, all I'm left with is:

```
SET ANSI_NULL_DFLT_ON ON
SELECT 1
```

Cheers, 
Dan

**Comment by dnln** [comment]
That seems to work much better, thanks Kyle. 

The only other issue I can see now is, in the left hand panel where the DBs and tables are listed, if I expand: 

DB name > Tables > Table name > Columns 

Then I get 'An error occurred'. If I double click the error for details, I get the message 'Msg 103010, Level 16, State 1. Parse error at line: 2, column: 5: Incorrect syntax near 'ANSI_NULLS'.'

**Comment by hankinsoft** [comment]
Hi,
SQL Data Warehouse isn't officially supported, however if your still interested in getting it working and possibly running some test queries, please let me know.

**Comment by dnln** [comment]
Hey. I'm afraid I no longer work with SQL Data Warehouse so can't really help with this anymore.

**Comment by hankinsoft** [comment]
No worries! I have another open ticket with warehouse and I've asked them if they are inserted to run some test queries as well. I'll close this ticket. Thanks for letting me know!
