### ISSUE TITLE
Feature Request: Add DB2 as connection option

### ISSUE THREAD

**Issue by scariest-darius** [hankinsoft/SQLPro#811]
This is a great tool.  I'm wondering if it's possible to add IBM DB2 as a connection option.

**Comment by hankinsoft** [comment]
Hi! I generally only add new connectors if I get enough user requests. SQLPro is an independently developed product, so I can only commit to adding something like that once I've received enough requests.

**Comment by hankinsoft** [comment]
Closing this thread as I have made a generic database support request thread #833.
