### ISSUE TITLE
Feature Request: Shift + Enter create newline but remove indent

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#813]
Let's say I have the following query:

```
SELECT
	COL1

FROM
	TABLE1
```

If my cursor is immediately after `COL1`, and then I hit Return (or Shift + Return), SQLPro Studio creates a new line with the same level of indentation.

Most of the time, this is what I want. But, It'd be handy if I could so Shift + Return to do a new line with 0 indentation (so, in this case, with the cursor below `COL1` but vertically aligned with `SELECT`.

**Comment by hankinsoft** [comment]
Sure, will add this for the next version.

**Comment by hankinsoft** [comment]
This is available in the latest build (2022.51). If you get the chance, can you see if it works as expected.

**Comment by jim256** [comment]
Works like a charm! Thank you
