### ISSUE TITLE
Feature Request: Hotkeys / keyboard shortcuts for "transformations" ("Make Upper Case" specifically)

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#814]
It'd be great to have some configurable keyboard shortcuts for the items in this context menu:

<img width="534" alt="image" src="https://user-images.githubusercontent.com/15026225/179630111-d599fa16-7a52-45bd-b908-46d7241a4de7.png">

**Comment by hankinsoft** [comment]
Any suggestions for default shortcuts? Probably just need make uppercase and make lowercase with shortcuts?

**Comment by jim256** [comment]
Yeah, I think those two are the most relevant for me and my team.

Maybe CMD + Ctrl + U and CMD + Ctrl + L?

**Comment by hankinsoft** [comment]
2022.61 is now available in the App Store. If you get the chance, can you see if that sorts this out for you?

I decided to skip a default shortcut for these items.

**Comment by jim256** [comment]
Seems to work great! Thank you.
