### ISSUE TITLE
Feature Request: Format: Match identifier casing to casing in database

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#815]
Let's say I have the following query with a Snowflake schema with a table named PRODUCTS (all caps):
```
SELECT
	STUFF
FROM
	MY_SCHEMA.products
```

If I use "Format query", it doesn't change the casing of the products table.

It'd be nice if the format option made the casing of identifiers match the casing of the DB in question. Most all our identifiers in Snowflake follow the default all-caps casing, whereas most our identifiers in Postgres follow the default lower casing, and it'd be nice to have the formatter work for whatever DB the query was written for.

**Comment by hankinsoft** [comment]
Fixed for the next build (hopefully available by the end of this week).

**Comment by hankinsoft** [comment]
This build is now available (2022.81). If you get the chance, please give it a try and let me know if it has sorted this out.
