### ISSUE TITLE
Feature Request: CMD + Click to create multiple cursors in different locations

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#816]
[Snowsight](https://docs.snowflake.com/en/user-guide/ui-snowsight.html#web-interface-the-snowflake-web-interface) allows you to create multiple cursors by using CMD + Click, even if those cursors are in different locations.

This would be handy! Please see the attached for a demo video.

[multiple_disjointed_cursors.mov.zip](https://github.com/hankinsoft/SQLPro/files/9142858/multiple_disjointed_cursors.mov.zip)

SQLPro Studio
macOS

**Comment by hankinsoft** [comment]
I'll get this added for the next build - I will probably however use option - click as option is the shortcut key I'm using for all other [multi cursor shortcuts](https://www.sqlprostudio.com/blog/11-multi-cursors).

**Comment by hankinsoft** [comment]
Just wanted to note that I have been investigating this one, however, it’s been giving me a rough time. At the moment, I’ve only been able to get mouse drag to insert cursors or click to insert cursor to work one at a time, but not both at the same time. I’m still investigating and have a few ideas but it won’t be in the next build.

**Comment by jim256** [comment]
> but not both at the same time

This made me want to clarify to make sure we're on the same page.

My request isn't necessarily to make more than one thing happen at the same time, but to add the ability to CMD + Click (or Option + Click) in as many places in the query as desired and have a cursor created in each one, regardless of whether or not they're vertically aligned.

Does that make sense? Did my demo video attachment from my initial post work?

**Comment by hankinsoft** [comment]
Im 99% sure I understand what you want. I think it's my post that's confusing the issue.

Current I'm able to make a build of SQLPro Studio where:
1. You can option + click + drag to insert multiple cursors as you drag.
2. But you cannot option + click to insert (one or more cursors at multiple locations).

Or I can create a separate build where you can:
1. option + click to insert (one or more cursors at multiple locations).
2. But you cannot option + drag to insert cursors.

But I've almost got it sorted so you can do either/or in the same build.

**Comment by hankinsoft** [comment]
Going to close this. It ended up being more more difficult than expected and I could never get it working quite right. If I get additional requests for it in the future, I will consider re-opening it.
