### ISSUE TITLE
Feature Request: Reorder the columns in the datagrid

### ISSUE THREAD

**Issue by blak3r** [hankinsoft/SQLPro#818]
Sometimes the columns I want to look at are separated by lots of others such that i can't see them all on the screen.
This requires that I then alter the select query to specifically itemize the important columns... this works but takes time.

I'd be nice if you could drag and drap the columns like you can in many spreadsheet and datagrids.

**Comment by hankinsoft** [comment]
A new build (2022.65) has been submitted which allows you to reorder columns. It should be available within a few days.

**Comment by hankinsoft** [comment]
Going to mark this as closed. If you find an issue or have any questions/comments please feel free to re-open.
