### ISSUE TITLE
Feature Request: Hotkey for "Find Column"

### ISSUE THREAD

**Issue by blak3r** [hankinsoft/SQLPro#819]
I love this feature but find myself not using it because in my head it's easier to scroll to the right than find the option in the menu below.

Would love the option to hotkey and type it in.   

Default Hotkey: Command+g or Command+Shift+H.

**Comment by hankinsoft** [comment]
2022.61 is now available in the App Store. If you get the chance, can you see if that sorts this out for you?

**Comment by hankinsoft** [comment]
Going to mark this as closed. If you find an issue or have any questions/comments please feel free to re-open.
