### ISSUE TITLE
No Import (CSV/JSON) data on Windows

### ISSUE THREAD

**Issue by jeromemaurey** [hankinsoft/SQLPro#82]
I've been using SQLPro for SQLite on mac for a long time and was excited to see that a version was available for Windows. After purchasing it on the Windows Store, I realized that none of the import functions, [as highlighted in the wiki](https://github.com/hankinsoft/SQLPro/wiki/Importing%20data), are available in the PC version.

I migh be missing something, so is there a way to import data on the Windows version?

**Comment by Wladislav** [comment]
Hello! Please, please update Windows version!

**Comment by hankinsoft** [comment]
Hello, unfortunately the Windows version does not yet have feature comparison with the Mac version yet. At the moment I do not have an ETA on when it will. Sorry about that!

**Comment by hankinsoft** [comment]
I haven't added this yet as it is a large feature and the windows products have very few users. It's one of the next things on my list, but I'm going to close this issue and point users requesting it to https://github.com/hankinsoft/SQLPro/issues/311.
