### ISSUE TITLE
Unable to "Edit selected row" if  table name is Pascal Case or Camel case in postgres

### ISSUE THREAD

**Issue by goblinss** [hankinsoft/SQLPro#821]
Reproduction steps
1. Connect postgres database.

2. Create Table with the pascal case name or camel case name

2. Insert data .

3. Select to 1000 rows
<img width="582" alt="1" src="https://user-images.githubusercontent.com/28497604/183288202-457d1380-f74d-4f43-acf8-897d9ea2d95d.png">

4. Select row and  Click "Edit selected row..."
<img width="666" alt="2" src="https://user-images.githubusercontent.com/28497604/183288218-52846b5d-905a-410b-ac11-c9837b8f65a4.png">

5. Unable to edit data because columns and values are empty
<img width="1149" alt="3" src="https://user-images.githubusercontent.com/28497604/183288301-69ce2fbb-5f9a-4723-a1c1-7b79c4c484c8.png">

**Comment by hankinsoft** [comment]
2022.61 is now available in the App Store. If you get the chance, can you see if that sorts this out for you?

**Comment by goblinss** [comment]
This version (2022.61) doesn't fix it.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.62.app.zip? If that sorts it, I'll get the App Store build submitted as well.

**Comment by goblinss** [comment]
I have confirmed that there are no issues.

Thanks.

<img width="1267" alt="edit" src="https://user-images.githubusercontent.com/28497604/185724675-028aa2d7-4105-4a8f-864a-ac33a45f03d6.png">
<img width="1265" alt="version" src="https://user-images.githubusercontent.com/28497604/185724680-f2fef207-5502-4c7f-b090-c5503025b92d.png">

**Comment by hankinsoft** [comment]
Great! I'm hoping to get the App Store build submitted either today or tomorrow. It usually takes ~24 hours for apple to approve the build, so it should be available Wednesday at the latest.

**Comment by goblinss** [comment]
I’ll keep my fingers crossed!

**Comment by goblinss** [comment]
Installed The App Store build 2022.65.
I have confirmed that there are no issues.

**Comment by hankinsoft** [comment]
Great, thanks for letting me know. I'm going to close this issue. Apologies for the delay.
