### ISSUE TITLE
SSL SYSCALL error

### ISSUE THREAD

**Issue by beerlington** [hankinsoft/SQLPro#822]
I've recently started getting errors like this when trying to query a remote Postgres database:

```
Initializing connection...
Connection ready. Took 0.039 seconds.

SSL SYSCALL error: Operation timed out. 0.000 seconds. (Line 1).

Finished. Total time: 0.039 seconds.
```

It works again if I disconnect from the database and reconnect, but it's a bit frustrating since it happens a couple times a day.

I'm on version `Version 2022.51 (Build 110920.5)` on MacOS 12.4.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.2022.70.app.zip? I've upgraded the internal Postgres version and im curious if that will sort it out.

**Comment by beerlington** [comment]
I'm away for a few days but will try to test it next week. Thanks!

**Comment by beerlington** [comment]
@hankinsoft I haven't been able to reproduce this issue for a while. Is there a chance one of the production builds already addressed it?

**Comment by hankinsoft** [comment]
Yep, it would be in a production build now as well. I'll close this issue, but if you see it again, please let me know.
