### ISSUE TITLE
SQL Server - Can't hit linked servers

### ISSUE THREAD

**Issue by mannycastaneda** [hankinsoft/SQLPro#823]
I'm using Windows authentication in this client and I can hit all my SQL Servers OK. However, whenever I try to use a linked server, I get this 

```
Msg 18456, Level 14, State 1.
Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'
```

I have no issues when I use my Windows machine with Management Studio or with Toad - it's just with this client on my Mac. My DBAs said it has nothing to do with my permissions.

**Comment by hankinsoft** [comment]
Hmmm, I'm not 100% sure what the difference would be in a linked server. If possible, could you go into the advanced connection preferences and try setting the encryption level to disabled and see if that connects?

<img width="507" alt="Screen Shot 2022-08-18 at 10 22 05 AM" src="https://user-images.githubusercontent.com/3160528/185405602-4b0b851f-f1d6-4cc5-8efb-bbd03d5501c7.png">
 
Additionally, if that fails, would you be able to provide an audit log from the target sql server?

**Comment by mannycastaneda** [comment]
No joy on disabling encryption level. I'll try to get those audit logs. DBAs around here have consumed too much Microsoft Koolaid and aren;t too keen on folks who use SQL clients not called Management Studio

**Comment by hankinsoft** [comment]
Please let me know if/when you are able to provide audit logs.
