### ISSUE TITLE
Redshift Materialized Views not Editable

### ISSUE THREAD

**Issue by DM1145** [hankinsoft/SQLPro#824]
Selecting "Alter View" or "Script as / Create to / New Query Window" on a Redshift cluster to change a materialized view returns an empty script.

Using "Alter View":
```
/* Generation failed with the following error: 

ERROR:  schema "" does not exist


*/
```

Using "Script as":
```
CREATE OR REPLACE VIEW schemaName.viewName AS
/*
* Error loading function definition.
* ERROR:  schema "" does not exist
*/
```

**Comment by DM1145** [comment]
<img width="442" alt="image" src="https://user-images.githubusercontent.com/43502723/186039677-332b1bf4-c994-4111-a18b-e3b1062c5d25.png">

**Comment by hankinsoft** [comment]
Hi,
This should be fixed in the app store version and in https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.72.app.zip if you are using the website version. If you get the chance, please let me know.

**Comment by DM1145** [comment]
I downloaded from S3.

The view menu now looks and acts like the table menu, there are no options to alter view, for either materialized or normal views.

![image](https://user-images.githubusercontent.com/43502723/191295313-091ebd38-6dfa-4233-ba19-727a310f22f0.png)

**Comment by hankinsoft** [comment]
Hmmm, no, I've messed something up. Looking into it now.

**Comment by hankinsoft** [comment]
Can you try: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.73.app.zip? That should sort it out.

**Comment by DM1145** [comment]
That build works.

Thank you.
