### ISSUE TITLE
MSSQL table export IDENTITY_INSERT

### ISSUE THREAD

**Issue by MMeffert** [hankinsoft/SQLPro#825]
MSSQL table export is incorrectly using IDENTITY_INSERT.  The spelling needs to be fixed and the SET IDENTITY_INSERT database OFF should be after the records are inserted.

Please let me know if I can supply additional information or testing.

Thank you,
Mitchell

<img width="334" alt="Screen Shot 2022-08-17 at 12 12 05 PM" src="https://user-images.githubusercontent.com/1237395/185225403-369237d7-6e1d-48d3-b6f9-90002797e2ec.png">

**Comment by hankinsoft** [comment]
Thanks, should be an easy fix. Could you provide a screenshot of the about dialog if possible so I can confirm which sqlpro app and version you’re using? (That way the first fix I provide will target your build).

**Comment by MMeffert** [comment]
Attached.

Thanks
Mitchell

**Comment by hankinsoft** [comment]
Thanks! Unfortunately attachments don’t come through when using GitHub emails. If possible, could you either login to github and post it or even just respond on the Twitter thread if that’s easier. Sorry about that.

**Comment by MMeffert** [comment]
Sorry about that.  Hopefully this works.

<img width="636" alt="Screen Shot 2022-08-17 at 3 06 34 PM" src="https://user-images.githubusercontent.com/1237395/185233403-3b937384-366c-426c-94f2-12633590e0b4.png">

**Comment by hankinsoft** [comment]
Thanks! I've submitted a fixed build to Apple. It usually takes ~24 hours or so for the build to be approved.

**Comment by MMeffert** [comment]
Sounds great!  Thank you so much for the quick fix.  I will watch for the update to be released and verify everything is working.

**Comment by hankinsoft** [comment]
2022.61 is now available in the App Store. If you get the chance, can you see if that sorts this out for you?

**Comment by MMeffert** [comment]
I installed the update this morning and everything looks good.  Thank you so much!
