### ISSUE TITLE
The "File does not exist" error message should show the whole file path

### ISSUE THREAD

**Issue by GaryMeyers1** [hankinsoft/SQLPro#826]
I am getting error messages in SQLPro that say that it is unable to perform an update because the database file does not exist.  The app successfully opened the .db file and it operates as expected when I view the data in a table, so it seems that it's just on an update that it can't find the file.  The error message should show the full path of the file so the user can more quickly determine the cause of the error.

<img width="260" alt="does not exist version 2" src="https://user-images.githubusercontent.com/60852956/186620149-0a7d1cce-bc91-4896-848b-279ff64ba58b.png">

<img width="260" alt="does not exist on update" src="https://user-images.githubusercontent.com/60852956/186620198-d244935b-0c95-496f-b218-dcd16d91e0de.png">

**Comment by vmlrodrigues** [comment]
I think it's a file permissions issue. I had to give SQLPro full disk access to fix the problem.

**Comment by hankinsoft** [comment]
Could you post the log file next time you see this issue? Just trying to figure a few things out. You can find the log by doing 'View' -> 'Logs'.

**Comment by hankinsoft** [comment]
If you get the chance to provide a log file for the issue, please let me know.
