### ISSUE TITLE
Bug: Database in database picker incorrect when doing right click -> Select top 1,000 rows in query editor

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#827]
**Describe the bug**
When I right-click on a table name from DATABASE_TWO written in the query editor with DATABASE_ONE selected in the database picker and select "Select top 1,000 rows", the new tab's database picker will show DATABASE_TWO (which I'd expect, as that's the database the table is in). However, the query will often fail with this error message:
```
Initializing connection...
Connection ready. Took 0.010 seconds.

SQL compilation error:
Schema 'DATABASE_ONE.SCHEMA_NAME does not exist or not authorized. 0.312 seconds. (Line 1).

Finished. Total time: 0.322 seconds.
```
DATABASE_ONE there reveals that it's actually trying to query using the context of the original tab, and not the context displayed in the database picker of the new tab.

**To Reproduce**
1. Open a new query tab with DATABASE_ONE.SCHEMA_ONE selected in the database picker.
2. Write a table name that references something in a different database, as in `FROM DATABASE_TWO.SCHEMA_FOUR.THIS_TABLE`
3. Right click on the table name in `DATABASE_TWO.SCHEMA_FOUR.THIS_TABLE` that you just wrote, and click "Select top 1,000 rows"

**Expected behavior**
I'd expect the database picker to match the context it's actually using.
In this case specifically, I'd expect the context to switch to the database of the table name I clicked on (and what is now being shown in the database picker), not stay on the same database as the first tab.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 12.5.1 (21G83)

**Additional context**
SQLPro Studio 2022.65 (Build 110938.5)
Snowflake 6.28.1

I don't _believe_ this is related to the resolution of #806, as this bug has been present for 12+ months

**Comment by hankinsoft** [comment]
I think I have an idea whats going on here. Attempting to get a fix ready for the next build.

**Comment by hankinsoft** [comment]
Next time you run into this could you show me the results of:

select current_schema();
select current_database();

<BEFORE> doing anything to resolve it, along with the results <AFTER> resolving it?
