### ISSUE TITLE
Feature Request: Option to show the full path of the .db file in the interface

### ISSUE THREAD

**Issue by GaryMeyers1** [hankinsoft/SQLPro#828]
I have been working with a .db file for years and I occasionally copy the file to a different folder for a snapshot backup.  I don't know how it happened but for some reason I opened the snapshot copy in SqlPro instead of the .db file that my app changes.  Because I did not know that I was looking at an old but recently changed version that was conceivably my active database, I wasted many hours altering my code to return the number of records affected, which was correct, and adding other logging statements because I was not seeing the changes in the database.

Please give the user the option to show the full path of the .db file in the interface.  Showing just the file name might be a "cleaner" look but I would have saved **many** hours of debugging if I could have seen the full path of the database.

**Comment by hankinsoft** [comment]
Where is it that you would want to see the path? Screenshot please.

**Comment by GaryMeyers1** [comment]
<img width="1101" alt="full path of database" src="https://user-images.githubusercontent.com/60852956/187626739-67d38f99-0b07-477e-96e6-690f8a7e0b8e.png">
I realize how this issue happened.  I once opened both my main database and a snapshot database to compare data between the two.  That must have made SQLPro think that the snapshot was now my main database, not the one that I've opened for years, so when I clicked on the top .db in the list the next time, I got the snapshot.

**Comment by hankinsoft** [comment]
How about something like this:

<img width="1480" alt="Screen Shot 2022-09-07 at 10 34 27 AM" src="https://user-images.githubusercontent.com/3160528/188891892-fbc8f965-f634-411e-8902-4b80bd88d918.png">

(I tried right aligning it, but it looks out of place and conflicts with the macOS default UI).

**Comment by GaryMeyers1** [comment]
That would be OK but I shouldn't have said "full path" which implies that the file name would be shown twice.  Showing just the folder path in a different label would work so I'd like to see an example of where you would put a path label without the file name.

**Comment by GaryMeyers1** [comment]
There wouldn’t be two new labels. Leave the file name and title bar as it is now and add one label for the folder.

**Comment by hankinsoft** [comment]
Hmmm, I'm not understanding what you mean......

> There wouldn’t be two new labels. Leave the file name and title bar as it is now and add one label for the folder.

That would be one label for the title bar and one label for the folder?
