### ISSUE TITLE
ssh tunneling feature should honor ~/.ssh/config

### ISSUE THREAD

**Issue by jkrauska** [hankinsoft/SQLPro#83]
OSX's built in ssh has lots of other tunable parameters in the ~/.ssh/config file.

It would be great if SQLPro used the local ssh config info -- it doesn't seem to currently.

**Comment by marcreynolds** [comment]
+1 for this... Sequel Pro respects the ~/.ssh/config file... it would be awesome if SQLPro did the same.

**Comment by windware** [comment]
+1

**Comment by lunij** [comment]
Is this still in development?

**Comment by hankinsoft** [comment]
The tunnel library has been replaced completely. If anyone runs into this issue, please let me know.

**Comment by Lbsl** [comment]
![image](https://user-images.githubusercontent.com/7035546/61182833-8c799300-a66b-11e9-9a5f-960e5b158325.png)
I set the keep alive interval but my SqlPro Studio still need more than 30 seconds to reconnect to server after a few minutes idle

**Comment by hankinsoft** [comment]
@jfbramlett ssh tunneling does not use the .ssh/config due to sandbox restrictions. Could you post the error you are receiving within SQLPro?
