### ISSUE TITLE
Bug: Ctrl + Enter Adds "Unusual Line Terminators"

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#830]
**Describe the bug**
The Ctrl + Enter feature to create a newline without any indentation adds unexpected characters

**To Reproduce**
1. Go to the SQL editor
2. Hit 'Tab' and write a valid query
3. Hit Ctrl + Enter to create a new line without indentation
4. Try to execute the query and see error.
5. Copy the code and try to paste it into VS code and see the error

**Expected behavior**
I don't know what Ctrl+Enter should do.

**Screenshots**
<img width="404" alt="image" src="https://user-images.githubusercontent.com/15026225/187760696-3ef75e35-90a7-4d38-b3de-b7d8fe36a65f.png">
<img width="249" alt="image" src="https://user-images.githubusercontent.com/15026225/187760656-7aa34cb5-0082-4aba-9ff2-7e6d1a73df63.png">

**Desktop (please complete the following information):**
 - macOS 12.5.1 (21G83)
 - SQLPro Studio 2022.65 (Build 110938.5)

**Comment by hankinsoft** [comment]
For the next build, I've set ctrl+enter to do the same as a shift+enter with the assumption that someone trying to do ctrl+enter is attempting to do https://github.com/hankinsoft/SQLPro/issues/813.

If I get a bug report about the behaviour in the future I will look into changing it. Thanks for the report, build will be available later this week.

**Comment by hankinsoft** [comment]
SQLPro Studio 2022.71 has been submitted which should sort this. Generally builds are approved in ~24 hours or so.
