### ISSUE TITLE
Support for AWS Aurora Serverless (Postgres) Data API

### ISSUE THREAD

**Issue by bensullivan** [hankinsoft/SQLPro#832]
**Is your feature request related to a problem? Please describe.**
There isn't a db client currently on the market that I'm aware of that allows a dev to manage data in an AWS Aurora Serverless instance (I use postgres) via the Data API.

**Describe the solution you'd like**
Ability to run sql queries and ddl in postgres instance hosted on AWS Aurora and exposed by the public Data API.

**Describe alternatives you've considered**
None that I know of.  I have to use query editor in browser which kinda sucks.

**Comment by hankinsoft** [comment]
I've got a few requests for adding additional database types, so I'm creating a 'megathread' where I can keep track of what is being requested the most. I've going to close this issue, but if you could upvote 'AWS Aurora Serverless' at #833 that would be great!
