### ISSUE TITLE
syntaxe error : use go instead of GO

### ISSUE THREAD

**Issue by py-nux** [hankinsoft/SQLPro#835]
**Describe the bug**
In SMSS on windows , this syntaxe is correct but in SQLPro for MSSQL we have an error : (use go instead of GO) 

**To Reproduce**
create a requete with a "end go" 

**Screenshots**
<img width="1039" alt="GraphiqueCollé-1" src="https://user-images.githubusercontent.com/8087648/189603326-e21b7d18-9060-4d4a-9491-5b26c6230369.png">

 windows SQL SMSS work fine with the same sql code :
<img width="801" alt="GraphiqueCollé-2" src="https://user-images.githubusercontent.com/8087648/189603346-084b37f4-b01c-4460-95b1-9f07b8b6105f.png">

**Comment by hankinsoft** [comment]
Reproduced. Working on a fix for this now. Are you using SQLPro for MSSQL, or SQLPro Studio? And is it from the website or App Store?

**Comment by py-nux** [comment]
I use sqlPro for mssql from App Store Envoyé de mon iPhoneLe 15 sept. 2022 à 18:54, Kyle Hankinson ***@***.***> a écrit :﻿
Reproduced. Working on a fix for this now. Are you using SQLPro for MSSQL, or SQLPro Studio? And is it from the website or App Store?

**Comment by hankinsoft** [comment]
This should be fixed as of the new build.

**Comment by hankinsoft** [comment]
Has the latest build sorted this? It is available via the macOS App Store.
