### ISSUE TITLE
Oracle: Problems subtracting som dates.

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#836]
**Describe the bug**

I am getting error subtracting some dates.

**To Reproduce**

```sql
select current_timestamp-current_timestamp from dual;
```

I get a result, but it says `Unknown column type: 10`.

If I try something similar against a table full of data, I still just get the one result above.

**Expected behavior**

I should get `0` or something like it.

**Screenshots**

<img width="341" alt="image" src="https://user-images.githubusercontent.com/3796633/190054296-10d422f0-9692-45f0-9b50-82cab12744be.png">

**Environment (please complete the following information):**

-	MacOS 12.6 Monterey
-	SQLPro for Oracle Version 2022.46 (Build 515.5)

**Additional context**

I really don’t know much about Oracle, and I find how it reacts to subtle variations of data type overwhelming. I did test on Oracle’s SQL Developer application, as well as on DBFiddle ([https://dbfiddle.uk/7pUo6bU_](https://dbfiddle.uk/7pUo6bU_)) and find that it works better.

The DBFiddle also includes a sample which is more about what I am trying to do. The `current_timestamp-current_timestamp` example is just a desperate experiment to see what is going on.

**Comment by hankinsoft** [comment]
Fixed for the next build - although your fiddle link just shows me 'not found'.

**Comment by manngo** [comment]
Thanks for that.

I have just found a bug in GitHub’s comment editor: when it auto-detects a URL, it doesn’t notice a trailing underscore, which is why the link to DBFiddle didn’t work. I have fixed it with a full MarkDown link.

**Comment by hankinsoft** [comment]
The new build is available which should sort this out.

**Comment by manngo** [comment]
Thanks, that fixed it.

Out of morbid curiosity, can you describe what was happening?

**Comment by hankinsoft** [comment]
> Out of morbid curiosity, can you describe what was happening?

Oracle types all need to be handled with custom code. When I wrote the connector, I tried to find as many types as I could and handle them, but I missed time interval. Once you provided a sample I was able to figure it and get it sorted :)
