### ISSUE TITLE
Add Query in cursor range option to SQL Pro for Oracle

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#837]
**Is your feature request related to a problem? Please describe.**

Earlier this year you added this feature to SQL Pro Studio. This small change made working with the product so much more pleasant.

**Describe the solution you'd like**

As Oracle currently requires the separate product, would it be possible to add this feature there?

**Comment by hankinsoft** [comment]
The new build is available which should sort this out.

**Comment by manngo** [comment]
Brilliant. Works perfectly. Thanks
