### ISSUE TITLE
How does SQL Pro for Oracle define a current query?

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#838]
**Describe the bug**

I’m not sure whether this is a bug or should be a feature request.

**To Reproduce**

If I turn on the option `Execute query in cursor range:` and click on a large script, a large section of the entire script is highlighted, including many queries.

I think this leads to some bizarre results. For example, if I have the following, without the forward-slash breaks, the whole script will be hightlighted, and I get an error: `ORA-00933: SQL command not properly ended.`

Adding the slashes helps to fix it.

In some larger scripts, the behaviour is not always consistent.

```sql
	SELECT 'hello'
	FROM dual;
/
	SELECT
  		acos(-1) AS pi,
  		sin(45*acos(-1)/180) AS sin,
		sqrt(2) AS root2,
 		log(10,3) AS log3,
		ln(10) AS ln10,
		power(4,3) AS four_cubed_again,
		1 as two
	FROM dual;
/
	SELECT
		200/7 AS integer_result,
		200/7.0 AS decimal_result,
		ceil(200/7.0) AS ceiling,
		floor(200/7.0) AS floor,
		round(200/7.0) AS rounded_integer,
		round(200/7.0,2) AS rounded_decimal
	FROM dual;
```

**Screenshots**

I have attached an mp4 with the behaviour.

**Environment (please complete the following information):**

-	macOS 12.6 Monterey
-	SQL Pro for Oracle
**Additional context**

https://user-images.githubusercontent.com/3796633/190059463-832fa50f-a2f3-4104-85fc-80a5fb766b8f.mp4

**Comment by hankinsoft** [comment]
That's correct - in oracle you do need to specify the / between multiple statements.

**Comment by manngo** [comment]
That’s curious. After a slash, I had a number of additional statements, and the individual statements did select properly:

```sql
/

drop table test;
create table test (
	id int generated by default as identity primary key,
	data int,
	more int
);
insert into test(data,more)
select 1,4 from dual union all
select 2,5 from dual union all
select 3,6 from dual;

UPDATE TEST t SET (t.data, t.more) = (
	SELECT vars.n*t.data, vars.n*t.more
    FROM (SELECT 5 AS n FROM dual) vars
);

SELECT * FROM test;

with vars as (select 5 as n from dual)
update test set data=data*vars.n;
```

This was also true of a few other batches separated by slashes.

On the other hand, I have one group where the highglighting starts after two characters, and so the statement won’t run:

```sql
/
	UPDATE sales s
	SET (s.ordered,s.shipped) = (
		SELECT ordered + d.diff,cast(s.shipped + d.diff as date)
		FROM (SELECT cast(sysdate-cast(max(ordered) as date) as int) AS diff FROM sales) d
	);
	WITH d AS (SELECT cast(sysdate-cast(max(ordered) as date) as int) AS diff FROM sales)
	SELECT
		s.id,
		s.ordered, s.ordered + d.diff as new_ordered,
		s.shipped, cast(s.shipped + d.diff as date) as new_shipped,
		d.diff
	FROM sales s , d
	ORDER BY s.ordered DESC;
/
```

I’m not normally an Oracle user, so I have no Idea whether my code contains something confusing.

**Comment by hankinsoft** [comment]
Did that latest update help sort this out?

**Comment by hankinsoft** [comment]
Closing this. If you still have issues, please let me know.

**Comment by manngo** [comment]
It now works perfectly, with and without slashes. Thanks.
