### ISSUE TITLE
Temp Table Creation Errors out when using variables

### ISSUE THREAD

**Issue by alexwhite-pattern** [hankinsoft/SQLPro#840]
**Describe the bug**
For whatever reason I can't create a temp table when using date variables. If I comment out the create temp table statement it runs just fine and returns the expected results, but when I uncomment it, it fails. This has be an issue across multiple queries, but it's not always the case. As far as I can tell when I remove the date variables from the where clause/case statements it's still able to create the temp table. I'm not able to isolate the issue between those two things. I'll go ahead and attach the log files for a successful run and a failed run.

**Expected behavior**
I'd expect it to create a temp table to be referenced in later queries

**Screenshots**

**Environment (please complete the following information):**
 - Device: Macbook Pro
 - OS: macOS 12.6
 - SQLPro app Version: 2022.65
- Target database server: Snowflake

**Additional context**
Here are the .log files
[Error Run.log](https://github.com/hankinsoft/SQLPro/files/9570485/Error.Run.log)
[Successful Run.log](https://github.com/hankinsoft/SQLPro/files/9570486/Successful.Run.log)

**Comment by hankinsoft** [comment]
Reproduced. Trying to figure out what's up.

**Comment by alexwhite-pattern** [comment]
Sweet thanks Kyle!

**Comment by hankinsoft** [comment]
SQLPro Studio 2022.71 has been submitted which should sort this. Generally builds are approved in ~24 hours or so.
