### ISSUE TITLE
Redshift Stored Procedures alter scripts missing "Security Definer" property

### ISSUE THREAD

**Issue by DM1145** [hankinsoft/SQLPro#841]
When selecting "Alter Proc" on Redshift connection where the "security definer" property has been set (meaning the proc executes in the security context of the definer, and not the executing user), that property is not included in the generated script.

It is critical to maintain this functionality, as many procedures do not have privileges needed to function when running in a non-admin context.

**Comment by hankinsoft** [comment]
Do you know much about how security definer is stored within redshift? I've found that the column prosecdef from pg_proc is true when security definer is enabled, but it's my understanding the script should only display SECURITY DEFINER if the script is output from the user who created it?

**Comment by DM1145** [comment]
Based on my data review, I think you located the right field in the pg tables.

I'd think that, if that flag is set, it should be included in the create or replace script, regardless of whether that user matches the current definer.  

I consider this a question of design intent.   If the intent when this is set is that this procedure should run under specific privileges (or simply sufficiently elevated privileges), then not including it will automatically break that intent.   

In my specific use case, there are a number of people that administer the server.  Under your suggested logic (assuming that the entire team used this product), were I to create a ticket to update a procedure with this set,  I'd find it odd that only one of them would have this setting automatically included in their create/replace script.  I'd have to note in the ticket to manually add this if not present.

If you don't mind me asking, where did you find the use case you referenced?

**Comment by hankinsoft** [comment]
>I'd think that, if that flag is set, it should be included in the create or replace script, regardless of whether that user matches the current definer.

Perfect, thats what I will do.

> If you don't mind me asking, where did you find the use case you referenced?

It's was just my understanding when I read the documentation. Sounds like I misunderstood (I don't use postgres much and this is my first time interacting with 'SECURITY DEFINER').

Can you grab this build and see if that sorts the issue: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.74.app.zip?

**Comment by DM1145** [comment]
The SECURITY DEFINER setting is all about execution context.   

Consider the use case where there is an account created with minimal rights to select data also has privileges to execute procs - but the procs perform ETL including CRUD operations that the account ordinarily doesn't have the rights to execute.  

The ETL account can only be used to execute specific, deployed instruction sets to affect production data - those credentials can't be used to execute ad-hoc scripts that change data.  This way, ad-hoc updates can only be performed by appropriately credentialed users while making sure that users without admin credentials can keep the updates happening.

**Comment by DM1145** [comment]
Oh - and the code is appropriately injecting security definer.

**Comment by hankinsoft** [comment]
Sounds good. Thanks for the details.
