### ISSUE TITLE
SQL Pro Crashes when trying to select a trigger

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#842]
**Describe the bug**

I wanted to alter an existing trigger.

**To Reproduce**

From the database tree, I select connection | database | public | table | Triggers .

It’s on the last step when the software quits.

**Expected behavior**

Not crashing? 

**Environment (please complete the following information):**

 - Device: iMac
 - OS: macOS 12.6 Monterey
 - SQLPro app Version Version 2022.71 (Build 110942.5)
- Target database server PostgreSQL

**Additional context**

**Comment by hankinsoft** [comment]
You are seeing this as soon as you expand the triggers node?
Could you post your crash log? Open 'console.app' and look for crashes in the left side. select that and find the latest SQLPro crash and post it here.

**Comment by manngo** [comment]
> You are seeing this as soon as you expand the triggers node? Could you post your crash log? Open 'console.app' and look for crashes in the left side. select that and find the latest SQLPro crash and post it here.

Is this is?

[SQLPro Studio-2022-09-23-091159.ips.zip](https://github.com/hankinsoft/SQLPro/files/9629935/SQLPro.Studio-2022-09-23-091159.ips.zip)

**Comment by hankinsoft** [comment]
Thats exactly it, thank you. I HOPE to get this fixed tomorrow.

**Comment by hankinsoft** [comment]
If you run the following query:

```
SELECT
  trigger_name,
  action_statement
FROM
  information_schema.triggers
WHERE
  trigger_schema = '{TABLE_SCHEMA}' AND
  event_object_table = '{TABLE_NAME}'
```

Replacing table_schema and table_name with your target table and schema, can you post me the results?

**Comment by manngo** [comment]
| trigger_name | action_statement |
| --- | --- |
| job_delete | EXECUTE FUNCTION do_job_archive() |

… which would be correct.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.76.app.zip and see if that sorts it out? If so, I'll get the App Store version updated as well.

**Comment by manngo** [comment]
Sorry, it’s not working properly for me. When I open the triggers folder, it doesn’t crash, which is good, but the folder is empty. I re-ran the query above to check that the trigger is still there.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.77.app.zip?

**Comment by manngo** [comment]
Sorry, still not appearing. I have checked in pgAdmin, and it’s there all right.

**Comment by hankinsoft** [comment]
Hmmm ok. I should have included logging but I was pretty sure that was going to work. I’ll post a new build with extra logging. And just to verify, if you right click and choose refresh on the triggers node it’s still empty?

**Comment by manngo** [comment]
No, you’re right. I should have checked that. Refresh does work, and I now have access to the trigger.

**Comment by hankinsoft** [comment]
Awesome. I’ll get this submitted to the App Store as well.

**Comment by manngo** [comment]
Thanks again.
