### ISSUE TITLE
SSH Tunnel

### ISSUE THREAD

**Issue by northernfrontier** [hankinsoft/SQLPro#843]
**Describe the bug**
Cannot get SSH Tunnel to work on a new installation of the SQL Studio Pro on a new MacOS Workstation

**To Reproduce**
Connection works on older installation but not on new install, get error

Access denied for user 'root'@'localhost' (using password: YES). (Error #1045)

**Expected behavior**
Connects to remote MySQL database via SSH Tunnel fine on one machine but not the other

**Screenshots**

**Environment (please complete the following information):**
 - Device: MacbookProM1 for both devices
 - OS: [MacOS Monterey 12.6 both devices
 - SQLPro app Version [2022.15 Build 110886
- Target database server MySQL

**Additional context**
Attached are console logs from both workstations.
[sqlprolog failure.txt](https://github.com/hankinsoft/SQLPro/files/9630476/sqlprolog.failure.txt)
[sqlprolog success.txt](https://github.com/hankinsoft/SQLPro/files/9630477/sqlprolog.success.txt)
[Screen Shot 2022-09-22 at 6.59.39 PM.pdf](https://github.com/hankinsoft/SQLPro/files/9630489/Screen.Shot.2022-09-22.at.6.59.39.PM.pdf)

**Comment by hankinsoft** [comment]
1. Is it the same SQLPro version on both systems?
2. On the failing system, if you edit the connection, edit SSL and choose 'Validate' does it validate?

**Comment by northernfrontier** [comment]
In Connection Edit, SSH Tunnel, the Validate button is always grayed out.


[Screen Shot 2022-09-23 at 8.18.58 AM.pdf](https://github.com/hankinsoft/SQLPro/files/9635381/Screen.Shot.2022-09-23.at.8.18.58.AM.pdf)

**Comment by northernfrontier** [comment]
Both installs are
Version 2022.15 (Build 110886)

**Comment by hankinsoft** [comment]
Can you try grabbing https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.75.app.zip and see if that helps?

Does your keyfile have no password set?

**Comment by northernfrontier** [comment]
Downloaded the new version and yet no pass on the keyfile.

**Comment by hankinsoft** [comment]
Can you check your mysql server to make sure that your second device is allowed to connect? I actually see in the logs that the SSH tunnel itself opens and connects, but its the mysql login that fails. Error #1045 is usually a permissons issue - since once system can connect then its problem that the other system is not whitelisted. Check https://www.percona.com/blog/2019/07/05/fixing-a-mysql-1045-error/ for more help with 1045 errors.

**Comment by northernfrontier** [comment]
Figured it out, there was a typo in the root password.  Thanks for helping me debug it.  

On a different subject the online status reported in the Connect View Window is just verifying TCP connectivity correct?

**Comment by hankinsoft** [comment]
> Figured it out, there was a typo in the root password. Thanks for helping me debug it.

No worries, glad you were able to get everything working.

> On a different subject the online status reported in the Connect View Window is just verifying TCP connectivity correct?

Yes, that's correct. It's more of an 'offline', 'online' thing than connection success. Otherwise you might end up locking an account out if the password was wrong and it tried connecting multiple times.
