### ISSUE TITLE
Feature request: Make autocomplete only apply suggestion with tab, and not enter

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#845]
**Is your feature request related to a problem? Please describe.**
I can currently accept an autocomplete suggestion using either return or tab. This can cause issues if I've just finished typing something, and the autocomplete window pops up right before I hit the return key, as it then inserts whatever suggestion is there.

**Describe the solution you'd like**
I'd like the autcomplete-acceptance key to be configurable in preferences. I was going to say I'd like it to be just tab, but that is sometimes annoying too, if you've just typed something and the suggestion pops up right when you're hitting the tab key and thereby inserts unwanted text.

Additional context
SQLPro Studio 2022.71 (Build 110942.5)
macOS 12.5.1 (21G83)
Snowflake 6.31.1 (though I'd hope to see this implemented for at least Snowflake, Postgres, and MySQL)

**Comment by hankinsoft** [comment]
Added for the next build.

<img width="545" alt="Screen Shot 2022-10-06 at 12 13 08 PM" src="https://user-images.githubusercontent.com/3160528/194351095-5c891c72-bc90-4cd6-88ab-83e00efffe95.png">

![CleanShot 2022-10-06 at 12 13 39](https://user-images.githubusercontent.com/3160528/194351107-75a73db4-641a-492c-9a83-1cc3cb6e1fe2.gif)

Should be avaialble by late next week.

**Comment by hankinsoft** [comment]
This build is now available (2022.81). If you get the chance, please give it a try and let me know if it has sorted this out.

**Comment by jaredx435k2d0** [comment]
Very nice! Thank you.
