### ISSUE TITLE
What is the simplest way to migrate settings to a new machine?

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#846]
**Is your feature request related to a problem? Please describe.**

I don’t know whether there is a simple method already, but I would like to migrate my settings from one machine to another. This includes settings from SQLPro Studio, Oracle, SQLite and PostgreSQL.

The settings would be connections plus whatever’s in the Preferences.

**Describe the solution you'd like**

Could there be either:

- Import & Export of settings
- Instructions on which files/folders to copy.

**Describe alternatives you've considered**

I have looked inside the Library and find that there are _hundreds_  of files and folders with either `hankinsoft` or `sqlpro` in the name. My brain is starting to explode.

**Additional context**

Happy to do a manual copy if I know which files and folders to do.

**Comment by hankinsoft** [comment]
Your SQLPro preferences would be in:

Studio:
~/Library/Containers/com.hankinsoft.osx.sqlprostudio/Data/Library/Preferences/com.hankinsoft.osx.sqlprostudio.plist

Oracle:
~/Library/Containers/com.hankinsoft.osx.sqlpro.oracle/Data/Library/Preferences/com.hankinsoft.osx.sqlpro.oracle.plist

SQLite:
~/Library/Containers/com.hankinsoft.osx.sqliteprofessional/Data/Library/Preferences/com.hankinsoft.osx.sqliteprofessional.plist

Postgres:
~/Library/Containers/com.hankinsoft.osx.SQLProPostgres/Data/Library/Preferences/com.hankinsoft.osx.SQLProPostgres.plist

To move the settings to anther system/app, you would replace the target plist file with the source.

I currently have no plans to make an import/export option for settings, but there a request [#686](https://github.com/hankinsoft/SQLPro/issues/686) which will see settings copy from one system to another automatically.

**Comment by manngo** [comment]
Thanks for that.

Is it possible to include this in an FAQ?

I notice that directories like `com.hankinsoft.osx.sqlprostudio` show a different name when using the Finder, which adds tremendously to the confusion.

The main settings worked well, but that doesn’t appear to include the appearance settings?

**Comment by hankinsoft** [comment]
> Is it possible to include this in an FAQ?

Thats a good idea. I'll take a look at doing so.

> I notice that directories like com.hankinsoft.osx.sqlprostudio show a different name when using the Finder, which adds tremendously to the confusion.

What do you mean by this? Could you post a screenshot if possible?

> The main settings worked well, but that doesn’t appear to include the appearance settings?

Ohhh, themes are stored in a separate folder. The themes are in:

~/Library/Containers/<product>/Data/Documents/Themes/

**Comment by manngo** [comment]
Here is a screen shot of the folder:

![image](https://user-images.githubusercontent.com/3796633/194473172-7ed9b5b1-1991-4b4b-80dd-649fc4441a10.png)

Here the folder name is `SQLPro Studio`; <kbd>⌘I</kbd> Get Info agrees with that.

However when I get the actual path name:

![image](https://user-images.githubusercontent.com/3796633/194474535-f67d8e76-74ca-4925-ad35-61746c288633.png)


I get `com.hankinsoft.osx.sqlprostudio`.

Obviously, Finder is doing something magical, to use the technical term.

**Comment by hankinsoft** [comment]
Hello,
> Obviously, Finder is doing something magical, to use the technical term.

Yes, finder does seem to be doing more and more magical things over time. I really wish it wouldn't.

Were you able to get everything migrated?
