### ISSUE TITLE
Long running query after laptop waked-up

### ISSUE THREAD

**Issue by yeysman** [hankinsoft/SQLPro#847]
**Describe the bug**
In case the laptop went to sleep for 10-15 minutes, the simple query runs about 40 seconds (sometimes more than minute).

**To Reproduce**
1. Run some query 
2. Wait until your laptop went to sleep.
3. After 10-15 minutes open the laptop and run the same query

**Expected behavior**
Once the application becomes active after the laptop waked up, all connections should be closed and reopened.
A few SQL editors/IDEs use the same behavior (DataGrip, TablePlus) which helps to avoid this issue.

**Environment (please complete the following information):**
 - Device: MacBook
 - OS: macOS 12.6
 - SQLPro app Version 2022.77 (Build 110949.5)
- Target database server Microsoft SQL Server 2019

**Comment by hankinsoft** [comment]
The next time you see this behaviour, could you provide the log file? You can find it by going to 'view' -> 'logs'. The connections should already be getting cleaned up during the sleep cycle, so the log file should help me figure out whats going on.

**Comment by yeysman** [comment]
@hankinsoft, I have sent the log file to your email with the subject "Log file for issue #847"
One thing i didn't mention:
In order to have access to DB server, I should be connected to VPN. So, once system waked up it runs wifi connection first and after VPN connection. All this time SQLpro is opened.
Once VPN connection is up, I run query and it runs a lot of time. If I click "cancel" - it affects nothing and at the end query will return result.

**Comment by yeysman** [comment]
Thank you!

**Comment by hankinsoft** [comment]
If you get the chance, can you try this build:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.81.app.zip

For a few days and see if that helps sort this out? If that does, I'll get the build submitted to the app store as well.

**Comment by yeysman** [comment]
@hankinsoft, thank you.
Will try it tomorrow and get back to you with the feedback.

**Comment by yeysman** [comment]
@hankinsoft,
I did few checks and seems issue is resolved with this build.
There is one issue i caught during the test:
I accidentally run query when vpn was turned off. SQLpro started to run query. Then i turned on VPN and tried to cancel running query in order to re-run it, but was not able to do this (when i clicked "cancel" sound indicated that action is not available, and of course nothing happened ). So, i had to wait more then one minute to get error "unable to connect to the server..." and only then i was able to re-run query.
I think it is because "cancel" refers to query, but we were in "connection" process. Is it possible to stop "connection" in case we clicked "cancel"?

**Comment by yeysman** [comment]
@hankinsoft,
I have sent new logs to the email. The issue appeared with the latest build.
During work in SQLpro, I lost wifi connection. After the connection was established I tried to run the query and again it was running for about 2 minutes without a way to cancel it. 
Probably it is still a delay in the connection process (probably it stops running once it reached the timeout limit). So, I think if we will have a way to drop the connection and reconnect it will solve this and previously described issue.

**Comment by hankinsoft** [comment]
> I did few checks and seems issue is resolved with this build.

Great, I'll get the app store build submitted with this.

For the unable to cancel during connection, this is an existing issue, although I don't believe there is a bug report submitted for it. Unfortunately, this issue with most likely persist as this phase of the connection is a bit less controllable than the query itself. My suggestion if you run into that, would be to either wait it out or close and open a new tab.

**Comment by hankinsoft** [comment]
This build is now available via the app store (2022.81). If you get the chance, please give it a try and let me know if it has sorted this out.

**Comment by hankinsoft** [comment]
Great! Please let me know if there is anything else I can help with.
