### ISSUE TITLE
History not saving

### ISSUE THREAD

**Issue by definedfunctions** [hankinsoft/SQLPro#848]
Each time I open / close SQLPro, the history for my MySQL connection is empty.

I am on the latest version, using a MacBook Pro.

Any advice on how to troubleshoot? Happy to provide additional info.

**Comment by hankinsoft** [comment]
Could you post your app version from the about screen please?

**Comment by hankinsoft** [comment]
As well as the app - SQLPro studio, SQLPro for MySQL, etc

And the platform (iOS, macOS, windows).

**Comment by definedfunctions** [comment]
Version 2022.77

SQLPro Studio

macOS

Thanks!

**Comment by hankinsoft** [comment]
Are you able to:
1. Write and run a query.
2. Open history and see if the entry is there.
3. Close and re-open the app. Check the history again.
4. Provide the log files. You can find them by going 'View' -> 'Logs'.

**Comment by definedfunctions** [comment]
Attached.

Probably worth pointing out that in this instance when I checked the history, it was still there.  That said the furthest the history goes back is yesterday at 10:45am.

[com.hankinsoft.osx.sqlprostudio 2022-10-26--19-06-56-804.log](https://github.com/hankinsoft/SQLPro/files/9880941/com.hankinsoft.osx.sqlprostudio.2022-10-26--19-06-56-804.log)

**Comment by hankinsoft** [comment]
Has your history continued saving since that date? Or has the history before that date now been removed as well?

**Comment by definedfunctions** [comment]
I just opened SQLPro and the history is empty.  I was writing and running queries throughout the day yesterday.

Attached are the logs in case it's helpful.

Is it possible the history is reset whenever I go on and off my VPN?

[com.hankinsoft.osx.sqlprostudio 2022-11-01--14-55-58-759.log](https://github.com/hankinsoft/SQLPro/files/9911141/com.hankinsoft.osx.sqlprostudio.2022-11-01--14-55-58-759.log)

**Comment by definedfunctions** [comment]
@hankinsoft  - Any advice? Sorry I'm not able to provide more info for making the troubleshooting process more straightforward.

**Comment by hankinsoft** [comment]
Are you using any sort of disk cleaning tool such as 'Clean my mac x'?

**Comment by jaredx435k2d0** [comment]
I've also experienced this regularly.

I do not have any sort of disk-cleaning tool.

**Comment by hankinsoft** [comment]
I've made some changes in the latest App Store version for history. If you get the chance:

1. Please update to the latest version.
2. Launch SQLPro. Go to 'View' -> 'DB History folder'.
3. Make a note of what items exist along with the file sizes.
4. Run a query which would add a history entry.
5. See if any of these files have changed and note the results.

**Comment by hankinsoft** [comment]
Going to close this. If you continue to see the issue with the newest version, please provide me the log files found by going to ‘view’ -> ‘logs’.
