### ISSUE TITLE
High RAM usage or memory leaks

### ISSUE THREAD

**Issue by Renset** [hankinsoft/SQLPro#849]
**Describe the bug**
I'm using SQLPro Studio as a part of Setapp subscription for a while. It worked well, but last time it consumes too much RAM when running: even without any opened connections, it takes about ~3GB (see screenshot below). With opened connection(s) and a small number of tabs opened (2-3), it may consume up to 10GB of RAM.

**To Reproduce**
1. Open SQLPro Studio (as a part of Setapp subscription)
2. Wait for 10-20 minutes

**Expected behavior**
SQLPro Studio doesn't consume so much RAM without any active connections.

**Screenshots**
<img width="1297" alt="CleanShot 2022-10-24 at 13 52 04@2x" src="https://user-images.githubusercontent.com/364877/197510815-83e8a238-31a5-4d5e-bd3c-a8f66af8e422.png">

![CleanShot 2022-10-24 at 13 52 26@2x](https://user-images.githubusercontent.com/364877/197510835-c962d4a6-39ce-453d-97e0-7e3f015f9b1b.png)

**Environment:**
 - Device: 15" MBP 2017 with 16 GB RAM
 - OS: macOS Monterey 12.6
 - SQLPro Studio Version 2022.80 (Build 110955)
- Target database server: Microsoft SQL Server

**Additional context**
Currently, swap memory is turned off in my system due to an inadequate number of IO writes when the swap is turned on (which leads to the rapid obsolescence of SSD). This is probably the root cause of the issue, but I'm not sure: other apps work without such issues.

**Comment by hankinsoft** [comment]
Thanks for the post.

I haven't been able to reproduce the issue so far. I've had the app open and running for about an hour and I'm still sitting around ~100mb of memory.

A few questions:

1. Can you post a log file after letting it idle and having the memory climb? (Logs can be found by going to 'View' -> 'Logs').
2. Can you post a 'sample' from the process? In the activity monitor, select the process then click the little 'i' button in the activity monitor toolbar, then 'Sample' near the bottom left of the dialog that opens.

Thanks!

**Comment by Renset** [comment]
Thank you for your quick reply! Here are the requested files:

[Sample of SQLPro Studio.txt](https://github.com/hankinsoft/SQLPro/files/9852754/Sample.of.SQLPro.Studio.txt)

[sqlpro_studio_log.log](https://github.com/hankinsoft/SQLPro/files/9852801/sqlpro_studio_log.log)

**Comment by hankinsoft** [comment]
Hmmm thanks. From the log file, I'm guessing its due to the size of the autocomplete cache.....

```
2022/10/24 13:32:11:532  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - ) has 132409 entries.
2022/10/24 13:32:11:535  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - Accounting) has 71 entries.
2022/10/24 13:32:34:069  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - testdb) has 2482140 entries.
2022/10/24 13:32:35:150  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - testdb2) has 132410 entries.
2022/10/24 13:32:35:280  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper) took 37.65 seconds
2022/10/24 13:32:35:281  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - 90BE0BDE-4FB4-4FA3-9D6C-885A5DA959AF-20291-00008C23CE5304C1.json) begin
2022/10/24 13:32:36:412  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - ) has 50 entries.
2022/10/24 13:32:36:933  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - testdb2) has 77012 entries.
2022/10/24 13:32:39:410  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - testdb) has 321964 entries.
2022/10/24 13:32:39:423  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper) took 4.14 seconds
2022/10/24 13:32:39:423  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - FE15113C-7593-490F-A918-2495F696E033-1057-00000A34120D36BD.json) begin
2022/10/24 13:32:46:679  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - testdb2) has 1204 entries.
2022/10/24 13:32:46:995  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - ) has 57 entries.
2022/10/24 13:33:00:676  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - testdb) has 1561405 entries.
2022/10/24 13:33:00:712  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper) took 21.29 seconds
2022/10/24 13:33:00:712  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - 625A2339-F61B-4A0A-883D-4CFC9981B9F0-76859-000011D1BB9B586C.json) begin
2022/10/24 13:34:35:804  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - testdb2) has 1153 entries.
2022/10/24 13:34:35:811  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - ) has 57 entries.
2022/10/24 13:38:28:567  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - testdb) has 6945495 entries.
2022/10/24 13:38:29:107  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper) took 328.45 seconds
2022/10/24 13:38:29:108  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - 5FE441FB-2E68-41A8-AEC0-05BB5B674067-49432-0000AB251DE34489.json) begin
2022/10/24 13:38:57:752  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - testdb2) has 967 entries.
2022/10/24 13:39:43:351  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper - testdb) has 4300449 entries.
2022/10/24 13:39:43:584  HSAutocompleteHelper:loadAutocompleteCacheFromURL (MSSQLAutocompleteHelper) took 74.48 seconds
```

It absolutely should not take up that much memory though, so give me a bit too dig further into this.

**Comment by hankinsoft** [comment]
Per email conversation, this seems to be sorted. If you find the memory creeping up again, please let me know.
