### ISSUE TITLE
Can't connect to Render.com Postgres DB 

### ISSUE THREAD

**Issue by Tialcis** [hankinsoft/SQLPro#851]
**Describe the bug**
Connecting to my DB hosted on render.com is not working and gives this error consistently when I attempt to connect

connection to server at "##.###.###.###", port 5432 failed: SSL connection has been closed unexpectedly

https://community.render.com/t/multiple-databases-ssl-connection-has-been-closed-unexpectedly/4249/2 -- Render has addressed this issue here with other clients

**To Reproduce**
1. Attempt to connect to DB hosted on render.com using the ExternalDatabaseURL
2. Click connect and see error

**Expected behavior**
It would connect to the database and show the tables

**Environment (please complete the following information):**
 - Device: M1 MacBook
 - OS: macOS 13.0
 - SQLPro app Version: SQLPro for Postgres 2022.77
- Target database server: PostgreSQL

**Additional context**
My coworker also using SQLPro was able to connect running 2022.1 of SQLPro for Postgres.

**Comment by hankinsoft** [comment]
If you try https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.2022.14.app.zip are you able to connect?

**Comment by Tialcis** [comment]
Okay, I realized this was completely on me. I hadn't setup my IP address correctly with my Render DB which was causing the issues. Sorry for the inconvenience!

**Comment by hankinsoft** [comment]
Thanks for letting me know!
