### ISSUE TITLE
Adding new varchar column doesn't clear out Size value.

### ISSUE THREAD

**Issue by kwadsten** [hankinsoft/SQLPro#856]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Size field should probably not default to "128" for any of the datatypes except perhaps for text/char.  

**Screenshots**

![CleanShot 2022-11-29 at 11 34 12@2x](https://user-images.githubusercontent.com/3610869/204587770-bd6d06b8-4f1c-4fb0-ba24-273009f5dbea.jpg)

Environment (please complete the following information):

Device: Mac Studio
OS: macOS 13.0.1 (Ventura)
SQLPro for SQLite Version 2022.96 (Build 4296)
Target database server: Local SQlite database

**Additional context**

**NOTE**
If your environmental details above were not completely filled in, the bug report will be closed until they are provided.

**Comment by hankinsoft** [comment]
In SQLite char and varchar are the same thing (they are both handled by the TEXT affinity) (https://www.sqlite.org/datatype3.html).

Varchar will continue to have a default size to maintain compatibility with other database types such as mysql in which a size would be required for varchar (https://dev.mysql.com/doc/refman/8.0/en/char.html).
