### ISSUE TITLE
How to specify empty string as default for non null text column?

### ISSUE THREAD

**Issue by kwadsten** [hankinsoft/SQLPro#857]
How to specify empty string as default for non null text column in the Schema view window?

I've tried '' and "" in the default field in the schema view but they both insert literal quotes in the default value.

Product: SQLPro for SQLite

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.101.app.zip? That should treat '' and "" as an empty string.

**Comment by kwadsten** [comment]
Entering a default of double quotes ("") still don't seem to work:
  "test_def" text NOT NULL DEFAULT('""')
But entering single quotes does:
  "test_def_2" text NOT NULL DEFAULT('')

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.102.app.zip should sort that up.

**Comment by kwadsten** [comment]
Yep, seems to be good now.  Thank you!
