### ISSUE TITLE
connection list cannot be cleared

### ISSUE THREAD

**Issue by erickbp** [hankinsoft/SQLPro#858]
Hi,

1. Where are connections stored? locally in our computers or on your servers?
2. When I use the option "Clear all" then connections go away as intended but a few days later they come back.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/10678433/206782482-58d0a851-0978-44da-b154-ac33ffc0a5f9.png">

**Comment by hankinsoft** [comment]
Closed. Required details such as app and app version were not provided.

**Comment by hankinsoft** [comment]
For item 1, connectors are stored in the iCloud Keychain if iCloud Keychain is enabled. If not, they are stored in the local keychain. Additional details are required before item two could be diagnosed.

**Comment by erickbp** [comment]
Here is the app version. The issues as simple as I describe it. I delete saved connections and days later they show up again.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/10678433/209195997-bca8a407-e0a2-4580-a654-8d1961ed6d09.png">
