### ISSUE TITLE
Feature Request: Snowflake: SSO Single Sign On (Microsoft)

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#859]
**Is your feature request related to a problem? Please describe.**
Our organization is switching our Snowflake authentication to SSO via Microsoft. Because of this, we'll no longer be able to use SQLPro Studio unless we are able to authenticate via SSO in SQLPro Studio.

**Describe the solution you'd like**
I'd like SSO sign-in via Microsoft to be implemented in SQLPro Studio.

**Describe alternatives you've considered**
The only alternative really available to us would be to use a different SQL client.

**Additional context**
We have a hard cutoff of February 10 by which we have to switch and will no longer be able to use SQLPro Studio without this feature enabled. If possible, it'd be great to have this implemented by then so our whole team can continue to use.

**Comment by hankinsoft** [comment]
Unfortunately it’s very unlikely I will be able to add SSO for snowflake. I asked the snowflake team about this back in 2020 and they said it was backlogged with no plans to add support. I’ve reached out to them again (
https://github.com/snowflakedb/libsnowflakeclient/issues/193) but unfortunately without them adding support SQLPro will be unable to include it.

Sorry for the bad news!

**Comment by jaredx435k2d0** [comment]
I appreciate your checking with them.

I'm trying to consider alternative methods to secure our Snowflake instance better.

Do you have any way to support MFA (including the word multi-factor authentication for searchability) with Snowflake?

**Comment by hankinsoft** [comment]
Closing as a copy of #661.
