### ISSUE TITLE
Bug in SQL when Creating Table

### ISSUE THREAD

**Issue by fresler** [hankinsoft/SQLPro#860]
There's a bug in the MySQL version when creating a table. When specifying a column can accept nulls, the SQL statement contains a syntax error. Specifically, there isn't a space between the column type and NULL.

![Screenshot 2022-12-19 at 12 39 37 PM](https://user-images.githubusercontent.com/791351/208487959-e9887598-6eee-44c6-aa51-ad6fa5c22a14.png)

**Comment by hankinsoft** [comment]
Please post your environment details.

**Environment (please complete the following information):**
 - Device: [e.g. iPhone6, MacBook]
 - OS: [e.g. iOS8.1, macOS 11]
 - SQLPro app Version [e.g. SQLPro Studio 2022.x] Please ensure you specify the full app name. (ex: SQLPro Studio, SQLPro for MySQL, etc).
- Target database server [e.g. MySQL, PostgreSQL, Microsoft SQL Server, etc]

**Comment by hankinsoft** [comment]
Can you grab https://d3fwkemdw8spx3.cloudfront.net/mysql/SQLProMySQL.2022.103.app.zip? That should sort it up.

**Comment by fresler** [comment]
That took care of it! Will you be updating the App Store version? My subscription is through there.

Thanks!
Floyd

**Comment by hankinsoft** [comment]
Submitted. Should be available in ~24 hours.

**Comment by fresler** [comment]
Wonderful!

Thanks!
Floyd

**Comment by hankinsoft** [comment]
The new version should be available on the App Store now.
