### ISSUE TITLE
Delete row button (-) not enabled when entire row is selected

### ISSUE THREAD

**Issue by kwadsten** [hankinsoft/SQLPro#861]
**Describe the bug**
Delete row button (-) not enabled when selecting entire row in Data view.

**To Reproduce**
Select table in left-hand list
Click Data toolbar button
Select a row by clicking on Row #

**Expected behavior**
Delete row button (-) should be enabled.

**Screenshots**
Attached

Device: Mac Studio
OS: macOS 13.1 (Ventura)
SQLPro for SQLite Version 2022.96 (Build 4296.5)
Target database server: Local SQlite database

**Additional context**
Delete button is enabled if individual fields are selected, but not when entire row is selected.

**NOTE**
If your environmental details above were not completely filled in, the bug report will be closed until they are provided.
![CleanShot 2022-12-19 at 13 50 47@2x](https://user-images.githubusercontent.com/3610869/208499210-9064d4a4-e4e1-47c7-8f69-68baf6919572.jpg)
![CleanShot 2022-12-19 at 13 50 41@2x](https://user-images.githubusercontent.com/3610869/208499212-b4562295-b56f-4863-b8d6-3212261d1245.jpg)

**Comment by hankinsoft** [comment]
Thanks, reproduced and should have a build submitted tomorrow.

**Comment by hankinsoft** [comment]
New version should be approved on the app store and available shortly if it's not available now. When you get the chance, please let me know if it's working for you.

**Comment by kwadsten** [comment]
Looks good. Thanks!
