### ISSUE TITLE
MSSQL: Export -> MySQL option at database level produces invalid SQL

### ISSUE THREAD

**Issue by linc** [hankinsoft/SQLPro#862]
SQLPro for MSSQL
Version 2022.70 (Build 115570)
MacOS 12.5.1 (21G83) on an M1 MBP

Right-clicking on a database and choosing Export -> MySQL... 

<img width="361" alt="Screen Shot 2022-12-24 at 10 16 16 AM" src="https://user-images.githubusercontent.com/117672/209442309-0c4e1038-c9fb-40ea-aaf6-0a7421d36e51.png">

I end up with an invalid `.sql` file for MySQL. It has a number of repeated syntax errors:

* A `GO` string after each query on its own line.
* Use of an `IDENTITY` function that doesn't exist. Ex:  `IDENTITY(1,1)`
* Use of an `OBJECT_ID` function that doesn't exist. Ex: `IF OBJECT_ID('dbo.pgd_Members', 'U') IS NOT NULL`
* Use of statements like `SET IDENTITY_INSERT pgd_AdminLog OFF`.
* Invalid constraint syntax like `ALTER TABLE dbo.pgd_album ADD CONSTRAINT PK__pgd_albu__97B4BE1737A5467C PRIMARY KEY (AlbumID)`.
* Invalid `[type]` parameter in `CREATE` statement. Ex: `[type] tinyint NOT NULL`.
* Tables all have the prefix `dbo.` which prevent import into a database named anything other than 'dbo'.

When I export an individual table to a new query tab or file I do not see these issues.

**Comment by linc** [comment]
See #863 for table-level export issues.

**Comment by hankinsoft** [comment]
Ahhh, it looks as if the database level export was actually doing a basic mssql export. Switched this to mysql export for the next build. Also planning on #863. Will post when available.

**Comment by hankinsoft** [comment]
Fixed as per #863.
