### ISSUE TITLE
MSSQL: Export -> MySQL option at table level has column typing and escaping problems

### ISSUE THREAD

**Issue by linc** [hankinsoft/SQLPro#863]
SQLPro for MSSQL
Version 2022.70 (Build 115570)
MacOS 12.5.1 (21G83) on an M1 MBP

Right click on an individual table -> Export -> MySQL -> File

<img width="554" alt="Screen Shot 2022-12-24 at 1 45 15 PM" src="https://user-images.githubusercontent.com/117672/209447981-47fc1fe1-741d-4685-9946-8b5334507939.png">

I encountered these issues:

* Use of column type `nvarchar(0)` where it contained far too much data. Using `longtext` is a safer conversion.
* Use of `varchar` with a number far too large, e.g. `varchar(21844)`. Here again, `longtext` may be a safer conversion.
* Error "Unknown data type: 'smallmoney'" — I substituted `int` successfully.
* A stored string ending in `\` accidentally escaped the ending delimiter single quote. Ex with delimiting quotes: `'Oh well :\'`.
* This stored string was a bit of a nightmare (without delimiters): `AddText(''[:\''(]''))''` — It requires both the `\` and the `(` to be escaped for it to parse.

Example above are pulled from the produced export, not the database directly.

After manually correcting the above issues in my export I was able to import to MySQL (MariaDB via Querious, specifically).

**Comment by hankinsoft** [comment]
> Use of column type nvarchar(0) where it contained far too much data. Using longtext is a safer conversion.
> Use of varchar with a number far too large, e.g. varchar(21844). Here again, longtext may be a safer conversion.

Both fixed for the next build.

> Error "Unknown data type: 'smallmoney'" — I substituted int successfully.

It looks like money columns can contain decimals, so I'm thinking double rather than int.

Still investigating the last two entries.

**Comment by hankinsoft** [comment]
Would it be possible for you to provde a small

create table bugexampletable....
insert into buxexampletable(id,bugvalue) values(1, 'string your having an issue with');

I think I'm getting something not quite right when i'm trying to reproduce it.

**Comment by linc** [comment]
I think this is it:

```
CREATE TABLE dbo.pgd_PMsg (
	PMID int NOT NULL,
	SenderID int NOT NULL,
	subject nvarchar(150) NOT NULL,
	body nvarchar(max) NOT NULL,
	stored tinyint NOT NULL,
	sentTo nvarchar(1000) NOT NULL,
	datesent datetime NOT NULL,
	msgIcon tinyint NOT NULL,
	withsig tinyint NOT NULL,
	upfile varchar(50) NULL,
	isGroup tinyint NOT NULL DEFAULT (0),
	groupID smallint NULL,
	upfileinfo nvarchar(25) NULL,
	PMReceipt tinyint NULL,
	basePMID int NULL
);
GO

ALTER TABLE dbo.pgd_PMsg ADD CONSTRAINT PK_pgd_PMsg PRIMARY KEY (PMID);
GO

INSERT INTO dbo.pgd_PMsg (PMID, SenderID, subject, body, stored, sentTo, datesent, msgIcon, withsig, upfile, isGroup, groupID, upfileinfo, PMReceipt, basePMID) VALUES (34879, 3927, ' RE: gbfr', ' But I already submitted it.javascript:void(AddText(''[:\''(]''))', 1, 'Bruce', '2010-03-06 17:35:52.000', 11, 1, '', 0, -1, '', 1, NULL);
```

**Comment by linc** [comment]
Note this is just the output from the app. I don't have the original because I restored from a provided `.bak` file. So I'm not 100% certain this will reproduce for you.

**Comment by linc** [comment]
The problematic value as seen in the in-app editor:
<img width="500" alt="Screen Shot 2022-12-29 at 11 21 39 AM" src="https://user-images.githubusercontent.com/117672/209980935-495dc0cc-226c-4a5f-a40e-bfd0dee3e998.png">

**Comment by linc** [comment]
The other value I mentioned above, same table:

```
INSERT INTO dbo.pgd_PMsg (PMID, SenderID, subject, body, stored, sentTo, datesent, msgIcon, withsig, upfile, isGroup, groupID, upfileinfo, PMReceipt, basePMID) VALUES (4169, 1932, ' Follow-up', ' Robert says the photo is a fake. Oh well :\', 0, 'Golden Nugget', '2004-02-16 02:38:43.000', 1, 0, '', 0, NULL, NULL, NULL, NULL);
```

**Comment by hankinsoft** [comment]
Can you grab https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.2022.100.app.zip and give it a try? I think that should sort everything out.

**Comment by linc** [comment]
Using that build, I was able to export the same table (`dbo.pgd_PMsg`) to MySQL (file) and imported it without error using Querious (MySQL). 👍
