### ISSUE TITLE
Loading SpatiaLite extension doesn't work

### ISSUE THREAD

**Issue by rbrtmrtn** [hankinsoft/SQLPro#864]
**Describe the bug**
Can't load [SpatiaLite](https://www.gaia-gis.it/fossil/libspatialite/index) extension.

**To Reproduce**
1. `brew install libspatialite`
2. Get the path to libspatialite with `brew --prefix libspatialite`; `cd` there and look for path to `mod_spatialite.dylib`
3. In SQLPro, run `select load_extension(<that path to mod_spatialite>)`
4. Try running a spatial query; it doesn't work. For example:

```sql
select count(*) from parcels where fid not in (select p.fid from parcels p join boundary b on st_intersects(p.geom, b.geom));
```

I get an error: 

```
no such function: st_intersects 0.000 seconds. (Line 1).
```

**Expected behavior**
I expect the `st_intersects` function to be found because I've loaded SpatiaLite. If I go through these same steps from the sqlite CLI it works.

**Screenshots**

**Environment (please complete the following information):**
 - Device: MacBook Air
 - OS: macOS 13.1
 - SQLPro app Version: SQLPro for SQLite 2022.103 (Build 4303.5)
- Target database server SQLite

**Comment by hankinsoft** [comment]
unfortunately, loading extensions will not work due to sandboxing restrictions.
