### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by davidbitton** [hankinsoft/SQLPro#865]
**Is your feature request related to a problem? Please describe.**
Lack of GraphQL support in the product line.

**Describe the solution you'd like**
SQLPro for GraphQL

**Describe alternatives you've considered**
Browser based apps.

**Additional context**
A desktop experience is preferred for the same reasons as your other apps.

**Comment by hankinsoft** [comment]
Added to the 'additional database type' request thread. #833
