### ISSUE TITLE
Removing a connection with iCloud syncing enabled

### ISSUE THREAD

**Issue by derekforeman** [hankinsoft/SQLPro#866]
**Describe the bug**
Removing a connection does not persist. A connection can be removed, but reappears at a later time. It looks similar to this issue. https://github.com/hankinsoft/SQLPro/issues/790

**To Reproduce**
Right click and remove a connection. Go back to work or close application and the connection reappears. 

**Expected behavior**
The connection should stay removed. 

 - Device: Macbook Pro, M1, iPad M1
 - OS: Ventura 13.1
 - SQLPro app Version Sql Pro Studio - Version 2022.83 (Build 110960.5)
- Target database server - not specific to database server.

**Comment by hamza24za** [comment]
hello how can use in macbook

**Comment by hankinsoft** [comment]
And you're seeing this every time you remove a connection? What should be happening is an entry gets added into 'deleted connections' to ensure it does not come back even if it grabs an old version from iCloud.

Is this on one device or multiple devices?

**Comment by derekforeman** [comment]
Across devices and every time a connection is removed.

**Comment by NickA55** [comment]
It also happens when you give a connection an alias.  Next time I open SQLPro Studio the new (or renamed) alias reverted back to blank, or the prior name.  I will say though when I opened SQLPro Studio today, none of my removed connections returned.  So maybe something was going on with iCloud at some point.

**Comment by hankinsoft** [comment]
> It also happens when you give a connection an alias. Next time I open SQLPro Studio the new (or renamed) alias reverted back to blank, or the prior name. I will say though when I opened SQLPro Studio today, none of my removed connections returned. So maybe something was going on with iCloud at some point.

@NickA55 are you using one more devices?

**Comment by NickA55** [comment]
No, just on my M1 Pro MBP

**Comment by hankinsoft** [comment]
@NickA55 could you post your app version please? (SQLPro Studio, SQLPro for MSSQL, installed from website, setapp, App Store?).

**Comment by NickA55** [comment]
Sorry, shoud have provided that info:

Installed from the App Store, version 2022.83, Build 110960.5
macOS Venture 13.1

I had several no longer used SQL Server connections that I removed.  I usually leave everything running and just let the laptop sleep when I'm not using it.  When I opened the Connect dialog I noticed all the connections I removed had returned.  I removed them again, closed and reopend SQLPro Studio, and it was fine (the removed connections were still gone).  The next day I opened SQLPro Studio the removed connections had returned.

It's been fine the last few days though.

**Comment by NickA55** [comment]
Update - Today all my old conections are back again, and all aliases reverted back.  Version 2023.1, Build 111000.  SQL Pro has not been opened all weekend.  Launched it this morning and noticed all my removed connections were back.

**Comment by hankinsoft** [comment]
Could you provide the log files? You can find them by going to 'view' -> 'logs'. Please include both the 'com.hankinsoft.osx.sqlprostudio.xxx.log' and 'connections.log'.

**Comment by rbg** [comment]
I also see similar sync mess ups "Version 2022.84 (Build 1047879.5)" - I do run on two different laptops.

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2023.07.app.zip? This is the website version rather than the App Store version, so it will work as a trial, but if you could check and see if removing a connection works well for you, that would be super helpful. Assing that goes well, the app store version should be available next week.

**Comment by hankinsoft** [comment]
Latest App Store build is out as well. Please let me know if you continue to see this issue, otherwise I'll close this in a few days.

**Comment by hankinsoft** [comment]
Going to mark this as closed. If you find you still have issues, please feel free to re-open.
