### ISSUE TITLE
Autocomplete on Enter after typing valid keyword

### ISSUE THREAD

**Issue by jsoconnell** [hankinsoft/SQLPro#867]
**Describe the bug**
The autocomplete suggestion box appears after a brief pause in typing before a space is entered. This is welcome behavior except for when the end of a line is reached, at which point, if the user hits `enter`, the first item in the suggestions list will _replace_ the last word typed. This seems to happen very frequently for me as I format SQL for readability and often end each segment of my WHERE clause with a keyword (usually `and`).

This is a minor usability nuisance that would greatly improve the editor experience.

**To Reproduce**
1. In the query editor, type out an SQL statement with a keyword such as `and` as the final word on the line.
2. The autocomplete suggestion box displays
3. Hit enter
4. The first suggested result replaces the desired text that should have remained intact.

**Expected behavior**

Admittedly, it is unknowable by the application whether the user intends to finish the line or select the first suggestion, but some possible heuristics for improving usability might be:

- Do not show the autocomplete suggestion list if the current word is a recognized symbol (table name, column name, SQL keyword)
- Do not select the first suggestion from the suggestion list upon user hitting `enter` if the current word is a recognized symbol. If/once user uses arrow keys, hitting enter will select the highlighted suggestion
- A hack but possibly an easier fix: Add the current word as the first suggestion in the suggestion list :-) if it is a recognized symbol
- Add any of the above behaviors but place behind a user preference if there are concerns that changing this behavior may cause different/unforeseen usability issues for other users as the functionality works today

**Screenshots**

<img width="605" alt="Screen Shot 2023-01-16 at 1 18 55 PM" src="https://user-images.githubusercontent.com/11394519/212747298-8acc1143-f7c7-4dea-91c0-d55e0b4e6934.png">

_Hitting "enter" in the above scenario changes the final word on the line to `bit_and`, when the user intends a carriage return_

**Environment**
 - Device: MacBook
 - OS: macOS 12.6.1
 - SQLPro for Postgres 2022.84 (behavior has existed for many prior versions)
- Target database server: PostgreSQL

**Comment by hankinsoft** [comment]
Hi. I recently added a preference where autocomplete can be disabled for the return key completely and rather just tab can be used. Would this help out in your case?

https://github.com/hankinsoft/SQLPro/issues/845

**Comment by jsoconnell** [comment]
Ah yes, "Tabs only" resolves the issue for me, didn't realize that was added, thanks so much!
