### ISSUE TITLE
Detailed view of table structure 

### ISSUE THREAD

**Issue by gabriel-r** [hankinsoft/SQLPro#868]
Please add a detailed view for table structures. The little sub-items under the table don't show all the relevant info.

All DB tools I ever used have a detailed interface to view and even manage table structures.

![Screenshot 2023-01-23 at 17 51 27  SQLPro Studio — public webhooks@2x](https://user-images.githubusercontent.com/51084/214100820-4b7e2568-2670-4f90-974e-7c3005499544.png)

**Comment by hankinsoft** [comment]
In SQLPro, you can right click on the table name and choose 'alter table' to see a similar view.

**Comment by gabriel-r** [comment]
It's awesome, thanks!  
Would probably work better if named _"Structure…"_
