### ISSUE TITLE
sql editor panel looses scroll position after copy/paste

### ISSUE THREAD

**Issue by cr00maui** [hankinsoft/SQLPro#87]
SQLPro Studio
v1.0.105 (Build 1036)
MacOS v10.12.3

Copy/paste while editing long queries (long enough to scroll) causes the scroll position to jump to a completely different location (which can be very frustrating). It does not happen every time but seems to be more common the longer the script. I'm currently editing an 800-line MSSQL Server script and happens nearly every paste/insert. It is not specific to the script and has been happening for months in a variety of scripts.

Thanks.

**Comment by hankinsoft** [comment]
This should be sorted. If you continue to see this issue, please let me know.
