### ISSUE TITLE
Unmap ^F as a menu shortcut

### ISSUE THREAD

**Issue by depaul-kenk** [hankinsoft/SQLPro#870]
Since time immemorial (courtesy of its NextStep roots), MacOS text containers have supported emacs-ish keybindings to move the cursor around: ^A for beginning of line, ^E for end of line, ^B for back one character, and ^F for move forward one character. ^P & ^N also work as expected for emacs devotees. 

The issue is that the SQL editor panel in SQLPro works as expected with all these keybindings *except* ^F which has been mapped to the menu item `Focus database tree search`. As a life long emacs user, these cursor movements are etched into my muscle memory and it's a hard stop into a brick wall when editing text and ^F doesn't move the cursor as expected. 

For my sanity and (more importantly) for UI consistency, please unmap ^F as a menu shortcut.

P.S. Unrelated to this issue specifically but on the topic of consistency: MacOS menu items use capitalized words. For some of its menu items, SQLPro uses uncapitalized words. For example, `Focus database tree search` should be `Focus Database Tree Search` to maintain visual consistency across all menus.

**Comment by hankinsoft** [comment]
This all makes sense. I will add a shortcut preference for 'focus database search' which you can clear which should let ^F do its default behaviour. I'll also take a look into fixing the capital letters in the menu items. Thanks for pointing that out!

Please provide which SQLPro app you are using (along with the source ie, App Store, website, etc) so I can provide the initial build once its available.

**Comment by depaul-kenk** [comment]
Awesome, thanks. There's a handful of other emacs-ish keybindings that should also be undone (^D comes to mind). Rather than play whack-a-mole with finding and fixing, it might be better to not use ctrl as a modifier for any menu shortcut.

Looks like I have the app store version:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/124091807/217009638-64c6da00-5b38-40db-8dfa-f162c4f088fa.png">

**Comment by hankinsoft** [comment]
The latest App Store version should now be out which allows you to remap or clear the two shortcuts currently using ^D and ^F. Please give it a try and let me know if that sorts things out.

**Comment by hankinsoft** [comment]
Going to mark this as closed. If you find any issues with it, please let me know.

**Comment by depaul-kenk** [comment]
Thanks for the quick fix!
