### ISSUE TITLE
App SQLPro is not opening at all

### ISSUE THREAD

**Issue by Nooor14050** [hankinsoft/SQLPro#871]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Device: [e.g. iPhone6, MacBook]
 - OS: [e.g. iOS8.1, macOS 11]
 - SQLPro app Version [e.g. SQLPro Studio 2022.x] Please ensure you specify the full app name. (ex: SQLPro Studio, SQLPro for MySQL, etc).
- Target database server [e.g. MySQL, PostgreSQL, Microsoft SQL Server, etc]

**Additional context**

**NOTE**
If your environmental details above were not completely filled in, the bug report will be closed until they are provided.

**Comment by hankinsoft** [comment]
Closed. Unable to investigate issue without required details such as the app and platform.
