### ISSUE TITLE
Resume version updates to sqlprostudio.com

### ISSUE THREAD

**Issue by normal-coder** [hankinsoft/SQLPro#872]
## The problem

The current version of SQLPro Studio on sqlprostudio.com is stagnant at `Version 2022.77 (Build 110948)`, while the App Store already supports `2023.05`, noting that the official website has not provided updates for at least 4 versions/more than 4 months, which is irresponsible for non-App Store.  **This is irresponsible and harmful to non-app store paid users.**

I purchased the Lifetime version through the software reseller lizhi.io, which is an extremely smooth and excellent client on macOS. SQL Pro Studio is a large part of my work, and I open it many times a day, almost to the point of being resident in the background. So I can feel the excitement and anticipation for every update (even though you have very limited updates a year and very little feature evolution, at least the project is alive :))

## The solution

Restore support for version updates to SQLPro Studio on sqlprostudio.com

## The alternatives

I hope to get a response from the author on the reason why the updated version is not available on the official website. I understand the difficulties of software development and distribution, but I don't want to give up SQL Pro and switch to other software for this reason.

## Additional context

![image](https://user-images.githubusercontent.com/6902432/216833314-52514cc3-081c-4050-b45d-6225c83c7cc3.png)

![image](https://user-images.githubusercontent.com/6902432/216833234-c8a5ed39-c1bd-45c3-8a11-1b65fa369ddf.png)

**Comment by hankinsoft** [comment]
HI,
I expect an update to the SQLPro Studio website build either later this week or early next. That said, I don't always update the website and App Store builds at the same time and there may sometimes be gaps. This is not something I expect to change in the future. Sometimes the website version is ahead and sometimes the App Store version is ahead. Just as an FYI the purchased license keys can also be used on the App Store version, so you are able to switch to whichever version you would prefer to use.
