### ISSUE TITLE
App crashes on Launch

### ISSUE THREAD

**Issue by rudilof** [hankinsoft/SQLPro#873]
**Describe the bug**

The app just won't load and crashes on launch.

 - Device: iPad Pro
 - OS: iPadOS 16.1
 - SQLPro app Version: mysql-client-by-sqlpro.   id:1270754173

**Comment by PelleNeksor** [comment]
Same here, I also notices that recent changes to my queries weren’t saved.

Device iPad Pro M2
OS: iPad OS 16.3
SQL PRO version: 2023.07

**Comment by hankinsoft** [comment]
Reproduced the not launching on iPad issue. Working on getting it sorted now and hope to have a build available within the next few days.

**Comment by hankinsoft** [comment]
A new version is available and should sort this out. Please let me know if you are able to launch sqlpro 2023.10 properly.
