### ISSUE TITLE
App store subscription not activating

### ISSUE THREAD

**Issue by ukr15** [hankinsoft/SQLPro#874]
Hi there,
my company bought with appleId demo-software@fraunhofer.de a license of Sqlpro 4 Postgres from AppStore . Since today, the license is lost.
Since we bought from AppStore, there is no license key.

What's the best way to activate the software.

Thanks in advance

ukr15

**Comment by hankinsoft** [comment]
Hi,
For an App Store issue, please ensure you are signed into the App Store using the same account which was used to make the purchases. If launching the app does not recognize a purchase, I would suggest a reboot. If that still does not sort the issue, I would suggest uninstalling and re-installing the app. Finally if you are still experiencing activation issues, you would need to contact Apple for further assistance.

**Comment by hankinsoft** [comment]
A few other users have had this issue and the ‘restore purchase’ button sorted them out. Please give that a try if you’re still having issue. The other thread is at https://github.com/hankinsoft/SQLPro/issues/876.
