### ISSUE TITLE
SQLPro for SQLite filename overlaying icons

### ISSUE THREAD

**Issue by aether7** [hankinsoft/SQLPro#875]
**Describe the bug**

I've just downloaded the latest version of SQLPro for SQLite, after installing it 

**To Reproduce**
1. Open a SQLite db with the application
2. check the filename close to the icon to write a new query command

**Expected behavior**
The filename above the icons should not overlay them.

Additional Note: The previous build before this, does not have this issue. If there's something i could be of help, please let me know.

**Screenshots**
![image](https://user-images.githubusercontent.com/1638567/217401281-800563cb-ea01-4b8a-b222-552145b00723.png)

**Environment (please complete the following information):**
 - Device: MacBook Pro
 - OS: MacOS 10.15.7
 - SQLPro app Version: SQLPro for SQLite Version 2023.10 (Build 4304
- Target database server: SQLite

**Additional context**

**NOTE**
If your environmental details above were not completely filled in, the bug report will be closed until they are provided.

**Comment by hankinsoft** [comment]
Investigating now, hope to have a fix later this week.

**Comment by hankinsoft** [comment]
Can you check https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2023.15.app.zip and see if that sorts things out for you?

**Comment by aether7** [comment]
@hankinsoft , Indeed, this build is working as expected, thank you so much for your help 😄
