### ISSUE TITLE
One time membership prompting me again to enter license key

### ISSUE THREAD

**Issue by achadee** [hankinsoft/SQLPro#876]
**Describe the bug**
One time membership prompting me again to enter license key

**To Reproduce**
Open Client, Also happening on my friends client too - which means the issue isnt isolated to just my account.

**Expected behavior**
Ive already paid and have been using it for over 2 years

**Screenshots**
![Screenshot 2023-02-08 at 5 47 47 pm](https://user-images.githubusercontent.com/5952918/217436293-d971a05b-fa60-4636-a966-4e7ef5c784e4.png)

**Environment (please complete the following information):**
 - OS: 13.0.1 (22A400)
 - SQLPro app Version Version 2020.30 (Build 1047806.5)
- Target database server Postgres

**Comment by achadee** [comment]
Restarting my computer doesnt solve the issue - Also I only have one Apple Account

**Comment by hankinsoft** [comment]
Could you post your log file? You can find it by going to 'View' -> 'Logs'.

**Comment by hankinsoft** [comment]
Also, what type of license did you previously purchase? Monthly, yearly, lifetime?

**Comment by hankinsoft** [comment]
Lastly, have you tried the 'restore purchase' button? I had anther customer with a similar issue who also tried a reboot and the license was not picked up until they used the restore purchase button.

> I quit all my apps and powered down my MacBook Pro.  I then booted the OS and restarted SQLPro and it displayed a box to try SQLPro for free.  Below that was a button to restore purchase or something like that.  I clicked that and all my windows to my databases started working normally again.

**Comment by hankinsoft** [comment]
Had one more user with the same issue confirm that a 'restore purchase' resolved the issue. Still trying to figure out why thats being required, but that should at least get you going again.

**Comment by achadee** [comment]
```
2023/02/09 10:52:32:935  HSSpreadSheetTable selectRowIndex (0) extending NO. (Possible size 0x15)
2023/02/09 10:52:32:942  HSLiense::isEmailValid = false. email address to short or empty.
2023/02/09 10:52:32:942  HSLiense::isLicensed = false. email is not valid.
2023/02/09 10:52:32:942  HSLiense::isEmailValid = false. email address to short or empty.
2023/02/09 10:52:32:942  HSLiense::isLicensed = false. email is not valid.
```

I purchased a lifetime license, so did my friend - we are both experiencing the issue, on two different laptops at the same time.

**Comment by achadee** [comment]
Where can I find the Restore Purchase button? Keep in mind I dont know where my license is now - as its been 2 years since ive bought it.

**Comment by hankinsoft** [comment]
> Where can I find the Restore Purchase button?

The restore purchase button is about 2/3rd down on the screenshot you initially posted. Highlighted below:

![IMG_9108](https://user-images.githubusercontent.com/3160528/217661985-45b3f148-ef40-4b2c-bc53-713a4ce46ff6.png)

> Keep in mind I dont know where my license is now - as its been 2 years since ive bought it.

If you've purchased via the App Store you wouldn't have a license key. macOS keep's track of the purchases. I believe my code-signing certificate changed between the builds which is why your previous purchase receipt is not validating. Restoring the purchase should sort that out.

**Comment by achadee** [comment]
Ok great, worked, thankyou!

**Comment by hankinsoft** [comment]
Great, thanks for letting me know.
