### ISSUE TITLE
Sometimes the Save screen appears blank

### ISSUE THREAD

**Issue by sirash007** [hankinsoft/SQLPro#878]
**Describe the bug**
When saving only a white screen appears

**To Reproduce**
No real way to reproduce the error but it is getting more frequent.

**Expected behavior**
A screen to show up where I can save the current script

**Screenshots**

**Environment (please complete the following information):**
 - Device: MacBook
 - OS: Ventura 13.2.1
 - SQLPro app Version 2023.10 (Build 115594.5)
- Target database server SQL SERVER

**Additional context**
I tried to download app again from app store but it keeps wanting a KEY - I can't find or don't have. I did pay for a subscription

**NOTE**
If your environmental details above were not completely filled in, the bug report will be closed until they are provided.

**Comment by hankinsoft** [comment]
Would it be possible to get a screenshot of what your seeing?

> I tried to download app again from app store but it keeps wanting a KEY - I can't find or don't have. I did pay for a subscription

Press the 'restore purchase' button. That should sort any previous purchase out.

**Comment by sirash007** [comment]
Thanks for responding. Attached is a screen shot.

Forgive me but I don't see a RESTORE PURCHASE button. Any guidance would be
appreciated

**Comment by hankinsoft** [comment]
![](https://user-images.githubusercontent.com/3160528/217661985-45b3f148-ef40-4b2c-bc53-713a4ce46ff6.png)

for an example of where the restore purchase button is. There is a similar button on the startip purchase screen as well.

would it be possible for you to add the image via the GitHub website? Unfortunately, emails
Don’t add images in.

**Comment by sirash007** [comment]
![Screenshot 2023-02-21 at 8 07 35 AM](https://user-images.githubusercontent.com/57608602/220456334-eaea3c19-cd3a-4ff7-a91c-88a95ac20e3f.png)

Screen image

**Comment by hankinsoft** [comment]
Could you reproduce this again, then provide the log files? You can find the log files by going to 'View' -> 'Logs'. (You will need to post them to the GitHub page rather than as an attachment via email).

**Comment by sirash007** [comment]
Sorry for the delay here are the log files
[connections.log](https://github.com/hankinsoft/SQLPro/files/10829648/connections.log)
[com.hankinsoft.osx.tinysqlstudio 2023-02-24--19-38-39-376.log](https://github.com/hankinsoft/SQLPro/files/10829649/com.hankinsoft.osx.tinysqlstudio.2023-02-24--19-38-39-376.log)

**Comment by hankinsoft** [comment]
Going to close. If you are still seeing this issue and get the chance to post the previous answers, please go ahead and reopen.
