### ISSUE TITLE
Autocomplete wildcard search

### ISSUE THREAD

**Issue by dveloudos** [hankinsoft/SQLPro#879]
When typing with autocomplete on, it would be handy if the feature could perform a wildcard search rather than filtering on fields starting with whatever I'm typing.

For example, I typed the following TSQL query:
`SELECT * from [MyTable] where mail`

When typing _mail_, I expected autocomplete to return the field labelled _E-mail_

Instead I currently have to write the following statement for autocomplete to suggest the E-mail field:
`SELECT * from [MyTable] where E`

To follow on from this, it would be nice if autocomplete would still find the relevant table field if we enter a square bracket before the starting letter. For example:
`SELECT * from [MyTable] where [E`
I would expect the above to return the [E-mail] field in the autocomplete dropdown but it doesn't.

**Comment by hankinsoft** [comment]
As noted when creating a bug the following environment details are required:

**Environment (please complete the following information):**
 - Device: [e.g. iPhone6, MacBook]
 - OS: [e.g. iOS8.1, macOS 11]
 - SQLPro app Version [e.g. SQLPro Studio 2022.x] Please ensure you specify the full app name. (ex: SQLPro Studio, SQLPro for MySQL, etc).
- Target database server [e.g. MySQL, PostgreSQL, Microsoft SQL Server, etc]

Please re-open once those details have been provided.

**Comment by dveloudos** [comment]
Device: Macbook Pro 16" M1 2021
OS: macOS Ventura 13.1
SQLPro Studio: 2023.12 (Build 111012.5)
Target database server: Microsoft SQL Server

**Comment by hankinsoft** [comment]
Hmmm, wildcard search should work, but from what I can tell, I think the specific issue is with the '-' in your e-mail column. Investigating this now and should have a fix by next week.

**Comment by hankinsoft** [comment]
SQLPro Studio 2023.15 has been released on the App Store and should sort this out. If you get the chance, please give it a try and let me know.

**Comment by dveloudos** [comment]
This is now working, thank you.
