### ISSUE TITLE
SQLPro for MSSQL - missing Format Query on Edit menu

### ISSUE THREAD

**Issue by mwoffenden** [hankinsoft/SQLPro#88]
Would like to see the same Format Query that is available in SQL Pro Studio.

**Comment by hankinsoft** [comment]
This has been added to all the latest versions of SQLPro for MSSQL.

**Comment by mwoffenden** [comment]
How do we check for and download updates?  I don't see it on the menu.

**Comment by hankinsoft** [comment]
Hi, depending on what version you are using if an update is available it will automatically show in the database tree above the connected database.

If you are using an older version, you will need to manually update. The latest version is available at: https://macsqlclient.com/download.php

**Comment by mwoffenden** [comment]
Nearly all Mac apps I use have a "check for updates" option -- or updates are available via the app store.  Will you be following one of these standard update paths in the future?

**Comment by hankinsoft** [comment]
Hi,
Unfortunately no, I do not plan on adding a manual 'check for updates'
option. SQLPro will only check for an update once when the application is
launched.

If you are using the Mac App Store version of the app you can update via
the Mac App Store as per usual.

Cheers,
Kyle

**Comment by mwoffenden** [comment]
I'm not using the app store version but would like to.  How may I switch over to the app store version?

**Comment by hankinsoft** [comment]
Please send me an email (kyle @ hankinsoft.com) and I can provide you with
a promo code that will allow you to get the Mac App Store version.

**Comment by mwoffenden** [comment]
Ok, just sent an email.

**Comment by mwoffenden** [comment]
The app store is showing 1.0.122, is that the latest?

**Comment by hankinsoft** [comment]
> Ok, just sent an email.
Great, I've responded with the promo code.

> The app store is showing 1.0.122, is that the latest?
Yes, this is the latest.

Cheers,
Kyle
