### ISSUE TITLE
Grid appearance settings don't save

### ISSUE THREAD

**Issue by dveloudos** [hankinsoft/SQLPro#880]
When turning on _Horizontal grid_ and _Vertical grid_ settings under Preferences > Appearance > Results and hitting _Apply_ or _Apply & Close_, the settings seem to apply to the currently open query tab. However when I run that query again or open an existing or new query tab, the horizontal & vertical grid lines don't appear anymore.

My system is a 2021 16" M1 Macbook Pro running Ventura 13.1.

To reproduce:
1) Open Preferences > Appearance > Results
2) Horizontal Grid > ON
3) Vertical Grid > ON
4) Apply & Close
5) View current query window, it will show both horizontal & vertical grid lines
6) Re-run the current query, notice all grid lines disappear
7) Check Preferences > Appearance > Results > Horizontal/Vertical Grid settings again, they're still checked.

![image](https://user-images.githubusercontent.com/99000718/220483566-414cfabd-4df0-4544-96d3-bde07096d637.png)

**Comment by hankinsoft** [comment]
As noted when creating a bug the following environment details are required:

**Environment (please complete the following information):**
 - Device: [e.g. iPhone6, MacBook]
 - OS: [e.g. iOS8.1, macOS 11]
 - SQLPro app Version [e.g. SQLPro Studio 2022.x] Please ensure you specify the full app name. (ex: SQLPro Studio, SQLPro for MySQL, etc).
- Target database server [e.g. MySQL, PostgreSQL, Microsoft SQL Server, etc]

Please re-open once those details have been provided.

**Comment by dveloudos** [comment]
Device: Macbook Pro 16" M1 2021
OS: macOS Ventura 13.1
SQLPro Studio: 2023.12 (Build 111012.5)
Target database server: Microsoft SQL Server

**Comment by hankinsoft** [comment]
Reproduced. Working on a fix - should be available by next week.

**Comment by hankinsoft** [comment]
SQLPro Studio 2023.15 has been released on the App Store and should sort this out. If you get the chance, please give it a try and let me know.

**Comment by dveloudos** [comment]
Interesting, the Vertical grid now persists, however the Horizontal grid disappears when I re-run my query. It appears again when I uncheck and recheck "Horizontal grid", but disappears when I run my query.

![image](https://user-images.githubusercontent.com/99000718/221442344-4945330a-e06d-4033-86e4-3dc5fa78816e.png)

**Comment by hankinsoft** [comment]
Oh shoot, yep I see. Got it fixed for the next build which will be later in the week. Will post an update here once its available.

**Comment by hankinsoft** [comment]
SQLPro Studio 2023.20 should be available now and should sort this. If you get the chance, please confirm if everything is working as expected.

**Comment by dveloudos** [comment]
This issue has been resolved.

**Comment by hankinsoft** [comment]
Awesome, thanks for letting me know.
