### ISSUE TITLE
Login failed untrusted domain cannot be used with integrated authentication (Msg 18452, Level 14)

### ISSUE THREAD

**Issue by weelassie23** [hankinsoft/SQLPro#881]
**Describe the bug**
After recent SLQPro Studio update, now getting a Connection Failed login error:
"Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication. (Msg 18452, Level 14)."

**To Reproduce**
1. Go to My Connections (connection has a server host address and is Windows Authentication on a Mac, login format is domain\username)
2. Click on  Connect
3. See error

**Expected behavior**
Login succeeds and I'm taken directly to query interface.

**Screenshots**
![image](https://user-images.githubusercontent.com/125701593/220985508-3fcba691-d30d-4f18-9f7e-fa190daafbe8.png)

**Environment (please complete the following information):**
 - Device: MacBook Pro 2020 2.3 ghz quad-core intel i7
 - OS: MacOS Ventura 13.2.1
 - SQLPro app Version: Version 2023.12 (Build 111012.5)
- Target database server: Microsoft SQL Server

**Additional context**
I've been using this connection for a couple years with no problem. No changes on our end. I can connect with no problems within a windows environment (virtual machine on the same Mac). 
A coworker using SQLPro for MSSQL on version 1.0.198 (Build 4361) is still able connect just fine.

**Comment by weelassie23** [comment]
a coworker using SQLPro for MSSQL on version 1.0.198 (Build 4361) is still able connect just fine.

**Comment by hankinsoft** [comment]
Can you download a previous version and confirm that you are indeed able to connect?

A few options for pervious versions would be:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.99.app.zip
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.52.app.zip

These will be trial builds, however your connections should show up the same as they do now.

**Comment by weelassie23** [comment]
Hmm, I'm actually getting the same error with both of those builds.

**Comment by hankinsoft** [comment]
It sounds as if something in your environment has changed. I would suggest deleting the connection and re-creating it to ensure that all details are entered properly.

**Comment by weelassie23** [comment]
Hm. I’ve tried deleting the connection multiple times. Could you provide a download for SQLPRO for MySQL version 1.0.198 (Build 4361) that I know does work in our environment?

**Comment by hankinsoft** [comment]
You can find the older version here:
https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.1.0.198.app.zip

**Comment by hankinsoft** [comment]
FYI, there are some preferences you can try in the 'advanced' section when editing a MSSQL connection.

<img width="405" alt="Screenshot 2023-02-27 at 3 03 35 PM" src="https://user-images.githubusercontent.com/3160528/221658402-74d12134-8514-44af-907d-3cda4c3111b4.png">

Changing the encryption level to off can sometimes help when connecting to older versions of MSSQL.

**Comment by weelassie23** [comment]
Thank you! I got connected!

**Comment by hankinsoft** [comment]
Awesome, thanks for letting me know. If you don’t mind me asking, what was the final solution?

**Comment by weelassie23** [comment]
To be honest, I’m not sure, it could have been one of two things.
I had recently done a clean install of Ventura, which changed the name of
my computer. I had asked our tech support to add my computer name back to
the domain / update it in JAMF.
At the same time I was trying a different version and was able to connect.
So I’m not sure which it was.
Thanks for providing alternate options to try.
