### ISSUE TITLE
Aren't listed partitioned tables for postgresql

### ISSUE THREAD

**Issue by usernamealreadypicked** [hankinsoft/SQLPro#883]
I am working with partitioned tables with Postgresql 13.9
and the partitioned table is show, but the partitioned tables arent.

**Comment by hankinsoft** [comment]
As noted when creating a bug or feature request the following environment details are required:

Environment (please complete the following information):

Device: [e.g. iPhone6, MacBook]
OS: [e.g. iOS8.1, macOS 11]
SQLPro app Version [e.g. SQLPro Studio 2022.x] Please ensure you specify the full app name. (ex: SQLPro Studio, SQLPro for MySQL, etc).
Target database server [e.g. MySQL, PostgreSQL, Microsoft SQL Server, etc]

Please re-open once those details have been provided.
