### ISSUE TITLE
How to completely uninstall SLQPro Studio or SQLPro for MSSQL

### ISSUE THREAD

**Issue by weelassie23** [hankinsoft/SQLPro#886]
Please provide steps to manually completely uninstall SQLPro from Mac, specifically system or library files that save any preferences, connection or license information, etc.

**Comment by hankinsoft** [comment]
Like other macOS apps, you can delete the 'SQLPro for MSSQL.app' to remove the app itself. To hunt down more information such as library files, preferences, etc I would suggest grabbing an app such as https://freemacsoft.net/appcleaner/.
