### ISSUE TITLE
system error: 35. (Error #2013) when connecting to MariaDB through SSH tunnel

### ISSUE THREAD

**Issue by geminixdev** [hankinsoft/SQLPro#887]
**Describe the bug**
When trying to connect to MariaDB on a Linux server through SSH there comes always this error:
"Lost connection to server at 'handshake: reading initial communication packet', system error: 35. (Error #2013)"
According to the log the error happens after the SSH tunnel is established, when connecting to MariaDB.

**To Reproduce**
1. Configure a MariaDB connection with SSH tunnel.
2. Click on 'Connect'
3. At the first connection attempt, the "Accept Fingerprint" message shows, accept it.
4. Then the error pops up: "Connection failed.", "Lost connection to server at 'handshake: reading initial communication packet', system error: 35. (Error #2013)"

**Expected behavior**
Successful connection

**Environment (please complete the following information):**
 - Device: Mac Mini M1 
 - OS: Ventura 13.2.1
 - SQLPro app Version: SQLPro for MySQL Version 2023.10 (Build 105078.5)
- Target database server: MariaDB on Linux servers.

**Additional context**
Tried with several MariaDB servers. 
Connecting to these MariaDB installations definitely works (using the same configuration on the same device) with Sequel Ace or Sequel Pro

**Example Log extract**

2023/02/28 09:38:51:277  Application is becoming active.
2023/02/28 09:38:56:292  connectToRecentConnectionById (not requesting password)
2023/02/28 09:38:56:292  doConnect: MYMARIADBSERVER (detected port: 22123 specified port: 0)
2023/02/28 09:38:56:310  HSDispatchGroup enter com.hankinsoft.connectionWindowDispatchGroup
2023/02/28 09:38:56:310  doConnect calling getHost:andPort:forServer:userSpecifiedPort:
2023/02/28 09:38:56:311  doConnect self->internalDatabaseConnectionDetails createNewClient
2023/02/28 09:38:56:311  doConnect calling databaseClient->connect
2023/02/28 09:38:56:311  HSSSHTunnelPool - reusing an existing connection.
2023/02/28 09:38:56:312  initializeSSH (allow pool) took 0.00 seconds.
2023/02/28 09:38:56:312  MySQL going to connect with Authentication: Default, ssl enforced: NO.
2023/02/28 09:38:56:529  MySQL:connect mysql_real_connect failed. Authentication: Default, ssl enforced: NO.
2023/02/28 09:38:56:529  MySQL:connect going to retry connection without ssh pool.
2023/02/28 09:38:56:529  Creating tunnelHelperWithoutPool
2023/02/28 09:38:56:529  (SSH) HSChilkatSSHTunnelHelper:connect called
2023/02/28 09:38:56:530  HSChilkatSSHTunnelHelper:connect - ssh authentication methods exist in cache: (
    publickey,
    password,
    "keyboard-interactive"
)
2023/02/28 09:38:57:436  SSHTunnel:keysForHost:port: returning an array (1 entries) of fingerprints.
2023/02/28 09:38:57:436  Keydata was found (user previously stored).
2023/02/28 09:38:57:436  SSH:authenticateViaPublicKey - publickey auth path is accessable. Not using bookmark.
2023/02/28 09:38:57:439  HSChilkatSSHTunnelHelper:authenticateViaPublicKey loaded privateKey.
2023/02/28 09:38:58:150  SSH tunnel open. Waiting for local connection.
2023/02/28 09:38:58:150  initializeSSH (no pool) took 1.62 seconds.
2023/02/28 09:38:58:150  MySQL going to connect with Authentication: Default, ssl enforced: NO.
2023/02/28 09:38:58:577  MySQL:connect mysql_real_connect failed. Authentication: Default, ssl enforced: NO.
2023/02/28 09:38:58:577  MySQL:connect - Checking to see if we should try other methods.
2023/02/28 09:38:58:577  MySQL:connect (ssh retry no pool) (Default) had error: Lost connection to server at 'handshake: reading initial communication packet', system error: 35. (Error #2013)
2023/02/28 09:38:58:577  doConnect databaseClient->connect finished
2023/02/28 09:38:58:577  setDBC: connectionId: 4A14337D-96C3-4340-BEEE-3D6BAFB9ABCC-6559-00000396201399A1
2023/02/28 09:38:58:577  checkSSHFingerprintError returning NO
2023/02/28 09:38:58:577  HSChilkatSSHTunnelHelper disconnect
2023/02/28 09:38:58:579  SQLProConnectingWindowController endSheetWithReturnCode: OK
2023/02/28 09:38:58:580  HSDispatchGroup leave com.hankinsoft.connectionWindowDispatchGroup
2023/02/28 09:38:58:580  MySQLClient::disconnect entered. Is executing query: NO
2023/02/28 09:38:58:580  MySQLClient::disconnect settings reconnect = 0
2023/02/28 09:38:58:580  MySQLClient::disconnect begin mysql_close
2023/02/28 09:38:58:580  MySQLClient:disconnect - cancelResult is: 1
2023/02/28 09:38:58:691  HSChilkatSSHTunnelHelper:closeConnection success YES.
2023/02/28 09:38:58:831  MySQLClient::disconnect finished mysql_close
2023/02/28 09:38:58:831  Failed to connect with error: Lost connection to server at 'handshake: reading initial communication packet', system error: 35. (Error #2013)
2023/02/28 09:38:58:831  Clearing internal database connection details.
2023/02/28 09:38:58:831  setDBC: nil
2023/02/28 09:39:06:120  Application is resigning activity.

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/mysql/SQLProMySQL.2023.21.app.zip? It's the website version so it will be a trial, but if that sorts it out, I'll get the App Store version submitted as well.

**Comment by hankinsoft** [comment]
1. What version of MySQL are you attempting to connect to?
2. If you run this query:

> SELECT CURRENT_USER() AS User, IF(plugin='','Native MySQL',plugin) AS Auth_Method
> FROM mysql.user WHERE CURRENT_USER()=CONCAT(user,'@',host);

What do you receive for the authentication type?

3. Could you try changing your authentication method in the 'Advanced' -> 'Connection preferences'? Try specifically the answer to number 2 if possible.

**Comment by geminixdev** [comment]
_1. What version of MySQL are you attempting to connect to?_
several servers, with 10.5.8-MariaDB and 10.9.3-MariaDB and in between. 
The MariaDB server from the log examples is 10.9.3-MariaDB.

_2. The query output is :_
`root@127.0.0.1	mysql_native_password
`
_3. Could you try changing your authentication method in the 'Advanced' -> 'Connection preferences'?_

I had tried before all 4 offered methods (besides default), with the same error.

<img width="566" alt="SQLPro-Authentication-methods" src="https://user-images.githubusercontent.com/125993656/222156356-0243b37d-e9b6-4e5b-9bfe-1f1f94c610b5.png">

There is no "mysql_native_password" offered in the selection.

See below the log extract for the 4 different autentication methods besides "default":

**mysql_clear_password :**
```
2023/03/01 13:45:01:735  MySQL going to connect with Authentication: mysql_clear_password, ssl enforced: NO.
2023/03/01 13:45:02:501  MySQL:connect mysql_real_connect failed. Authentication: mysql_clear_password, ssl enforced: NO.
2023/03/01 13:45:02:501  MySQL:connect - Checking to see if we should try other methods.
2023/03/01 13:45:02:502  MySQL:connect (ssh retry no pool) (mysql_clear_password) had error: Lost connection to server at 'handshake: reading initial communication packet', system error: 35. (Error #2013)
```

**mysql_old_password**
```
2023/03/01 13:49:06:679  MySQL going to connect with Authentication: mysql_old_password, ssl enforced: NO.
2023/03/01 13:49:07:448  MySQL:connect mysql_real_connect failed. Authentication: mysql_old_password, ssl enforced: NO.
2023/03/01 13:49:07:448  MySQL:connect - Checking to see if we should try other methods.
2023/03/01 13:49:07:449  MySQL:connect (ssh retry no pool) (mysql_old_password) had error: Lost connection to server at 'handshake: reading initial communication packet', system error: 35. (Error #2013)
```

**caching_sha2_password**
```
2023/03/01 13:50:26:079  MySQL going to connect with Authentication: caching_sha2_password, ssl enforced: NO.
2023/03/01 13:50:26:831  MySQL:connect mysql_real_connect failed. Authentication: caching_sha2_password, ssl enforced: NO.
2023/03/01 13:50:26:831  MySQL:connect - Checking to see if we should try other methods.
2023/03/01 13:50:26:832  MySQL:connect (ssh retry no pool) (caching_sha2_password) had error: Lost connection to server at 'handshake: reading initial communication packet', system error: 35. (Error #2013)
2023/03/01 13:50:26:832  doConnect databaseClient->connect finished
```

**sha256_password**
```
2023/03/01 13:51:33:914  MySQL going to connect with Authentication: sha256_password, ssl enforced: NO.
2023/03/01 13:51:34:676  MySQL:connect mysql_real_connect failed. Authentication: sha256_password, ssl enforced: NO.
2023/03/01 13:51:34:676  MySQL:connect - Checking to see if we should try other methods.
2023/03/01 13:51:34:677  MySQL:connect (ssh retry no pool) (sha256_password) had error: Lost connection to server at 'handshake: reading initial communication packet', system error: 35. (Error #2013)
2023/03/01 13:51:34:677  doConnect databaseClient->connect finished
```

**Comment by geminixdev** [comment]
I just tested on iPad, using the current Appstore App, and I get the same error. Also there, other Apps connect. 

![SQLPro-iPad](https://user-images.githubusercontent.com/125993656/222243472-636de755-b4f8-40b8-a579-babcd4671dc2.jpg)

**Comment by hankinsoft** [comment]
Thanks for the info.

Just to check the ssh server is also the mysql server? So your mysql server name is set as 127.0.0.1?

Is your linux server hosted by a cloud provider? If so, which? (I'd like to try and replicate - unfortunately I'm not getting much information from the logs/error message).

**Comment by geminixdev** [comment]
_the ssh server is also the mysql server?_
 Yes, these are a dozen remote Linux servers, running OpenSUSE 15.2 - 15.4 Linux, and MariaDB.
 Connection to the server is through SSH, and then local connection to MariaDB.
 
 Here is a screenshot from a working configuration of Sequel Ace:
  
<img width="467" alt="Configuration-SequelAce" src="https://user-images.githubusercontent.com/125993656/222251291-ef2e6425-9e62-4aee-b4bd-2169bcda296c.png">

 The Linux servers are our servers, dedicated, no cloud. I have full access and can test everything you might need, as long as I don't stop them, they are in production.

**Comment by geminixdev** [comment]
The server from the screenshot above is openSUSE Leap 15.4 Linux, with 10.9.3-MariaDB. The other servers, which I also unsuccessfully tested, are similar, may be 1 or 2 versions older.

**Comment by hankinsoft** [comment]
FYI, I've been trying to reproduce this with no luck so far. I'm trying to figure out what I can add for logging as well that might be helpful. I hope to have a build later this week with at least some additional logging to help narrow down why this is happening.

**Comment by hankinsoft** [comment]
Two more questions:

1: In your do you have 'AllowTcpForwarding yes' in your server ssh config?
2: Could you try changing your MySQL host from 127.0.0.1 to localhost in SQLPro and see if that makes any change?

**Comment by geminixdev** [comment]
_1: In your do you have 'AllowTcpForwarding yes' in your server ssh config?_
AllowTcpForwarding is not specified, and the default is yes (according to the sshd_config Linux man page). Nevertheless I tested with explicitly setting  'AllowTcpForwarding yes'  and restaring sshd, but unfortunately no change, the same error.

_2: Could you try changing your MySQL host from 127.0.0.1 to localhost in SQLPro and see if that makes any change?_
Your question pointed me to the cause of this issue. In the SQLpro config, I assumed that the field 'Server name' is just the label for the server, so I entered a name, such as "MyGreatServer". 

But this 'Server name' field is the field where to put either "127.0.0.1", or "localhost", and then it works!!!

<img width="591" alt="SQLPro-config-edit" src="https://user-images.githubusercontent.com/125993656/224007772-6a946c68-bc38-41fe-a3ba-e253de1cd1dd.png">

The (text) name of the server, the label, does not go into the "Server name" field, but in the "Alias" field on top of the Edit window.

May be change the name of the field to "Server" only, instead of "Server name" ?

**Comment by geminixdev** [comment]
This can get closed now, thanks for your help!

**Comment by hankinsoft** [comment]
Awesome, I was having a hugely difficult time figuring this out so I'm glad we were able to get it sorted! :)

I've switched the 'Server name' label to be 'Server host' for the next build.
