### ISSUE TITLE
Issues with multiple statements in SQL Pro for Oracle

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#888]
**Describe the bug**

I have finally traced a dreaded `ORA-00933: SQL command not properly ended.` error to not putting a slash between statements.

If I attempt to run this:

```sql
SELECT 200 AS integer_result FROM DUAL;
SELECT 200 AS integer_result FROM DUAL;
```

everything is fine. If I try this:

```sql
SELECT 200/7 AS integer_result FROM DUAL;
SELECT 200/7 AS integer_result FROM DUAL;
```

I get 

>ORA-00933: SQL command not properly ended.

I can fix it by including a slash:

```sql
SELECT 200/7 AS integer_result FROM DUAL;
/
SELECT 200/7 AS integer_result FROM DUAL;
```

**To Reproduce**

The error in the middle example occurs whether or not I have `Execute query in cursor range:`, but not when I highlight an individual statement.

**Expected behavior**

Here I’m not sure about what should happen. In other clients, notably __Oracle SQL Developer__ I can run each statement individually and together without problems.

**Environment (please complete the following information):**

-	Mac Mini M1
-	macOS Ventura 13.2.1
-	SQL Pro for Oracle Version 2022.70 (Build 570.5)

**NOTE**

I posted a question on Stack Exchange, where they say it’s not the DBMS but it’s the client.

I also posted another issue here (https://github.com/hankinsoft/SQLPro/issues/838) which may be related.

I don’t think it’s the case that I need a slash between _all_ statements, since I have successfully run a script with a large number of statements. The only slash I needed was after a `CREATE TRIGGER` statement.

I think the division is causing the confustion.

**Comment by hankinsoft** [comment]
Decently an SQLPro issue. I’ll take a look into it and see what I can figure out.

**Comment by hankinsoft** [comment]
Got this fixed and I think it will also fix what you're seeing with (https://github.com/hankinsoft/SQLPro/issues/838). Going to get it submitted to Apple shortly, so it should be available within a few days.

**Comment by manngo** [comment]
Thanks again for this. I have updated the software and it works perfectly!
