### ISSUE TITLE
CSV import does not include tables in non-public schemas

### ISSUE THREAD

**Issue by cparnot** [hankinsoft/SQLPro#889]
BUG

**Steps to reproduce:**

- Connect to a server with a database that includes tables in a schema other than "public".
- Select the Import... CSV option from the contextual menu of one of those tables.
- Select the file and options to import.
- Click to the next step, which opens the interface for selecting a table (popup menu on the top right) and setting up the options for the different columns to import into.

**Result:**

- The popup menu only includes tables that the "public" schema.
- One cannot import data from CSV into a table that is not in the "public" schema.

**Expected result:**

- Tables that are not in the "public" schema should also be listed.
- One should be able to import data from CSV into a table that is not in the "public" schema.

**Environment:**

Device: MacBook Pro 16-inch M1 Max
OS: MacOS 12.6.3
SQLPro Version 2023.20 (Build 111020) on Setapp
Target database server: PostgreSQL

**Comment by cparnot** [comment]
I noticed that similar bug with the "Duplicate Table" feature. Probably true of all features that propose a list of tables to pick from.

**Comment by hankinsoft** [comment]
Resolved for the next build. Please ensure you include environment details such as device, OS, SQLPro product + app version and database type in the future or the issue will be closed until they are included.

**Comment by cparnot** [comment]
Thanks @hankinsoft ! Sorry I just followed the link from the app, and did not see instructions on issue formatting. But indeed, seems obvious in retrospect to include that information... Keep up the good work!

I added the info in the issue description, for the sake of completeness.

**Comment by hankinsoft** [comment]
Thanks for including that! I had updated the App Store with the fix, but I see you're using Setapp. I'll get the fixed submitted now.

**Comment by hankinsoft** [comment]
The setapp version (2023.21) should now be available with this fix. If you get the chance, please give it a try and let me know if everything works as expected.

**Comment by hankinsoft** [comment]
Going to close this. If you run into any issues, please feel free to re-open it.

**Comment by cparnot** [comment]
ALL GOOD! — Tested CSV import for SQLPro Version 2023.21 (Build 111021), on Setapp version for macOS.
