### ISSUE TITLE
Drop multiple tables

### ISSUE THREAD

**Issue by dlitty** [hankinsoft/SQLPro#89]
It would be convenient, especially when working on development of a new app that requires new tables, to be able to select multiple tables in the tree and drop them all at once (with an option to disable foreign key restrictions if available in the database engine - e.g., mysql).  Sometimes I decide to implement things a bit differently and need to change the structure around before committing changes to source control; so I currently delete them one at a time then re-run my creation script.

**Comment by hankinsoft** [comment]
Hi,
Unfortunately this is not something I plan on adding (multiple database tree selection, plus actions). I would suggest running a query to generate your delete statement instead. Such as the following example: https://youtu.be/O8CDeAX6a5o
