### ISSUE TITLE
Small decimal numbers display as 0

### ISSUE THREAD

**Issue by stcherenkov** [hankinsoft/SQLPro#890]
**Describe the bug**
After the last update very small float numbers in PostgreSQL DB started to show up as 0.

**To Reproduce**
1. Create a very small numeric value in the PostgreSQL database, like `0.0000000000000000029149516579778970315535814938674983782254972126`.
2. Open the table in SQLPro Studio.
3. See it as 0.

**Expected behavior**
Expected to be displayed with all its decimal digits.

**Screenshots**
How it looks like in DataGrip:
<img width="404" alt="CleanShot 2023-03-02 at 12 43 24@2x" src="https://user-images.githubusercontent.com/1773729/222377846-7054c78d-8178-427f-8ae1-966698e184c4.png">

How it looks like in SQLPro Studio:
<img width="184" alt="CleanShot 2023-03-02 at 12 43 55@2x" src="https://user-images.githubusercontent.com/1773729/222378049-fe534414-8fde-40c7-ac18-2bcd435d7291.png">

**Environment (please complete the following information):**
 - Device: MacBook
 - OS: macOS 13.2.1
 - SQLPro app Version: SQLPro Studio Version 2023.20 (Build 111020.5)
- Target database server: PostgreSQL

**Additional context**
Looks like it is related to the latest update where you started treating numeric values like numbers instead of treating them as text. And the available precision of the language or library you are using is smaller than available precision of numeric values in PostgreSQL.

**Comment by hankinsoft** [comment]
Reproduced. Working on a fix.

**Comment by stcherenkov** [comment]
I'm seeing this fixed at SQLPro Studio Version 2023.21 (Build 111021.5).

Thanks a lot, that was fast!
