### ISSUE TITLE
foreign key relations on SQLite not being parsed correctly

### ISSUE THREAD

**Issue by aether7** [hankinsoft/SQLPro#891]
**Describe the bug**

when using a SQL file to create the SQL schema which contains the "`" symbol, it does not create the proper relation between tables.

**To Reproduce**

1. Go to 'Query view'
2. select demo schema provided and execute the statements
3. Got to 'Structure view'
4. the relation schema should be something similar to the image below

**Expected behavior**

Using the demo SQL which contains basic schema creation, should be able to parse and create the relations between tables correctly.

**Screenshots**

schema view shows the format being misbehaving
![wrong-behavior](https://user-images.githubusercontent.com/1638567/222920913-b2620949-002c-4707-9f78-8c2588e729f1.png)

the relation in the column role_id is not being linked.
![image](https://user-images.githubusercontent.com/1638567/222921168-93aac2bd-0dca-4127-b664-d49e92fe274f.png)

**Environment (please complete the following information):**
 - Device: Macbook
 - OS: MacOS 10.15
 - SQLPro app Version: SQLPro for SQLite Version 2023.15 (Build 4306)
- Target database: SQLite

**Additional context**
DEMO data to create The same schema:

```sql
create table `role` (`id` integer primary key autoincrement, `name` varchar(255));
create table `demo_user` (`id` integer not null primary key autoincrement, `name` varchar(255), `email` varchar(255), `role_id` integer, foreign key(`role_id`) references `role`(`id`));
insert into `role`(`name`) values('senior dev');
insert into `demo_user`(`name`, `email`, `role_id`) values('john doe', 'john.doe@mailinator.com', 1);
```

**NOTE**
If your environmental details above were not completely filled in, the bug report will be closed until they are provided.

**Comment by hankinsoft** [comment]
I've got a fix ready - are you using the App Store version, website, or setapp version? (So I know where to post the build first).

**Comment by aether7** [comment]
@hankinsoft sorry for the delay, Im currently using the website to check the latest version. 👀

**Comment by hankinsoft** [comment]
Could you grab https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2023.26.app.zip and see if that sorts this out for you?

**Comment by aether7** [comment]
@hankinsoft indeed, this fix does not have the issue, thanks for your help 👍
