### ISSUE TITLE
Add Version Check menu option

### ISSUE THREAD

**Issue by DM1145** [hankinsoft/SQLPro#892]
Please add a menu option which checks whether the running version is most current, and displays an alert noting whether the installed version is the most current, or a note that there is an upgrade with a downlink for newer versions if available..

The only other way I think I can determine if there is an update available is to download the software from your website and check the version of that in the file name.

Alternatively, if this is already available in the app, please feel free to note wha tI need to do to do so and close the ticket.

Thank you,

David Martin

Device: Mac M2 PowerBook
OS: Ventura 13.1 (22C65)
SQL Pro Studio Version 2023.10 (Build 111008.1)
Server Type: N/A

**Comment by hankinsoft** [comment]
Hi,
The website version of the app checks on launch to see if it’s the latest. If so, it adds a top-level entry into the database tree stating that an update is available. 2023.10 is the latest available website build.

**Comment by hankinsoft** [comment]
Hmm, how about a ‘Help’ -> ‘Check for update’ menu item? The about screen is not somewhere I would want to put it.

**Comment by DM1145** [comment]
That would work just as well.   It's really up to you where you think it _should_ go.  From my perspective, where it goes isn't as important as it being available.

If I forget that the on-launch check is there, it would be helpful to have an easy way to know the app is up to date.   Realistically, it's not "If"...  It's "When".

The on-launch notification reminder is extremely useful, too, I certainly wouldn't do this in favor of that.


TYVM

**Comment by hankinsoft** [comment]
The next time you launch the SQLPro website build, it should show you a new version is available in the database tree. That new version also includes the manual 'Help' -> 'Check for Updates' menu item.
