### ISSUE TITLE
Core Data date string converts to wrong day

### ISSUE THREAD

**Issue by patricks** [hankinsoft/SQLPro#893]
I have a core data sqlite database with the following timestamp:

Presented in integer:
<img width="262" alt="Screenshot 2023-03-10 at 08 57 54" src="https://user-images.githubusercontent.com/132167/224299523-b7c25f02-b980-4a22-a0a4-bdec710123aa.png">

If I change the settings to present it as core data string:
<img width="266" alt="Screenshot 2023-03-10 at 08 58 26" src="https://user-images.githubusercontent.com/132167/224299604-81359592-f353-43f7-958b-c67faa4912f7.png">

It looks like the day is wrong, because if I convert it via the website: https://www.epochconverter.com/coredata

I get the following result:
<img width="631" alt="Screenshot 2023-03-10 at 09 01 13" src="https://user-images.githubusercontent.com/132167/224299769-6488e32a-cf2d-4774-a5aa-dcc9ab600e74.png">

**Comment by hankinsoft** [comment]
Closed for missing environment details. Please reopen once they have been provided.

```
**Environment (please complete the following information):**
 - Device: [e.g. iPhone6, MacBook]
 - OS: [e.g. iOS8.1, macOS 11]
 - SQLPro app Version [e.g. SQLPro Studio 2022.x] Please ensure you specify the full app name. (ex: SQLPro Studio, SQLPro for MySQL, etc).
- Target database server [e.g. MySQL, PostgreSQL, Microsoft SQL Server, etc]

**NOTE**
If your environmental details above were not completely filled in, the bug report will be closed until they are provided.
```

**Comment by patricks** [comment]
**Environment**
 - Device: MacBook Pro
 - OS: macOS 13.2.1 (22D68)
 - App: SQLPro for SQLite (Version 2023.15 (Build 4306.5))

**Comment by hankinsoft** [comment]
Thanks! I've submitted a build to the App Store which I think will fix this. In preferences, there are now two core data options:

1. Core data (local time) string
2. Core data (utc) string

I believe picking the second option should sort this out for you.

Build should be available tomorrow, but I'll pop a note here once I get notified that Apple has approved it.

**Comment by patricks** [comment]
Thanks for releasing a new version so quickly. I already installed it, but this doesn't fix my problem:

Take a closer look at the day of the ZSTART column. It always displays the 12. as day, but it should be 13. If I use the integer format I get the following output (see screenshot) `700390980`. Converting this with https://www.epochconverter.com/coredata the output is correct (see screenshot).

With localtime setting:
<img width="566" alt="Screenshot 2023-03-13 at 10 06 21" src="https://user-images.githubusercontent.com/132167/224656263-34034b1b-bca3-48aa-bb89-0062b68d8897.png">

With utc setting:
<img width="603" alt="Screenshot 2023-03-13 at 10 06 38" src="https://user-images.githubusercontent.com/132167/224656417-81e76f2e-e417-482b-b021-b5b0b25dfa87.png">

With integers setting:
<img width="575" alt="Screenshot 2023-03-13 at 10 06 52" src="https://user-images.githubusercontent.com/132167/224656717-1dbfb640-1c01-4827-b02e-578488423955.png">

Converted:
<img width="584" alt="Screenshot 2023-03-13 at 10 13 27" src="https://user-images.githubusercontent.com/132167/224657320-dcd1376a-07d4-45de-a2d0-9d7a13bb71bb.png">

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2023.28.app.zip?

I think that should sort it. If so, I'll submit the App Store build.

**Comment by patricks** [comment]
Yes this looks better now 👍. 

Another thing is that the "display timestamps as" feature only works in the data view. If I query data (example: SELECT ZSTART * from ZRECORD) it is always displayed as integer. But I think this another problem.

**Comment by hankinsoft** [comment]
Great, I'll get the build submitted to the App Store.

> Another thing is that the "display timestamps as" feature only works in the data view. If I query data (example: SELECT ZSTART * from ZRECORD) it is always displayed as integer. But I think this another problem.

No plans on changing that. The query view is meant to display what the user queries for, so if you want dates there, you would query have to manually query:

> SELECT datetime(yourcolumn + 978307200, 'unixepoch','localtime')

**Comment by hankinsoft** [comment]
The App Store version (2023.28) is now available. I'm going to close this issue, but if you find it's not working as expected please feel free to re-open.
