### ISSUE TITLE
OSX and iOS licensing

### ISSUE THREAD

**Issue by grdollar** [hankinsoft/SQLPro#894]
I recently purchased SQLPro Studio and installed on OSX. I now want to use this on iOS but I am being prompted to buy it, which I already did. Is there a "restore purchase" option for this product?

**Comment by hankinsoft** [comment]
Hello,
Unfortunately no App Store purchases can be shared cross platform. While Apple introduced the ability to share in app purchases across apps a few years ago, only NEW apps from that point forward got that ability. At the time SQLPro had already been in the store over five years. Also, it's against Apple's rules to display any of this within the app.

My usual suggestion is to cancel the App Store purchase during your next renewal and instead purchase via the website. You can even use the promo code S10 to save 10%.

Please note that NO lifetime licenses are cross platform. ONLY a monthly or yearly subscription purchased via the website - which will work on macOS, iOS and Windows.
