### ISSUE TITLE
Latest update from App Store not loading/working macOS 13.2.1

### ISSUE THREAD

**Issue by brownidj** [hankinsoft/SQLPro#895]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               SQLPro for SQLite [13672]
Path:                  /Applications/database_stuff/SQLPro for SQLite.app/Contents/MacOS/SQLPro for SQLite
Identifier:            com.hankinsoft.osx.sqliteprofessional
Version:               2023.31 (4311.5)
App Item ID:           586001240
App External ID:       856170390
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-04-11 14:48:11.6882 +1000
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Bridge OS Version:     7.2 (20P3045)
Anonymous UUID:        4C9F29BB-9098-3693-8627-9948BED1D447

Sleep/Wake UUID:       67998BB4-F023-4A68-8865-06431320131B

Time Awake Since Boot: 75000 seconds
Time Since Wake:       5754 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/SQLProSQLiteMacOS.framework/Versions/A/SQLProSQLiteMacOS
Referenced from: <E0233D8C-472B-31A2-856F-EDA70EE3381D> /Applications/database_stuff/SQLPro for SQLite.app/Contents/MacOS/SQLPro for SQLite
Reason: tried: '/Applications/database_stuff/SQLPro for SQLite.app/Contents/Frameworks/SQLProSQLiteMacOS.framework/Versions/A/SQLProSQLiteMacOS' (no such file), '/Applications/database_stuff/SQLPro for SQLite.app/Contents/Frameworks/SQLProSQLiteMacOS.framework/Versions/A/SQLProSQLiteMacOS' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/SQLProSQLiteMacOS.framework/Versions/A/SQLProSQLiteMacOS' (no such file), '/Applications/database_stuff/SQLPro for SQLite.app/Contents/Frameworks/SQLProSQLiteMacOS.framework/Versions/A/SQLProSQLiteMacOS' (no such file), '/Applications/database_stuff/SQLPro for SQLite.app/Contents/Frameworks/SQLProSQLiteMacOS.framework/Versions/A/SQLProSQLiteMacOS' (no such file), '/System/Library/Frameworks/SQLProSQLiteMacOS.framework/Versions/A/SQLProSQLit
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff80acfdb4a __abort_with_payload + 10
1   dyld                          	    0x7ff80ad16d07 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff80ad16d39 abort_with_payload + 9
3   dyld                          	    0x7ff80ac9e1e1 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff80ac9b660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
5   dyld                          	    0x7ff80ac9a281 start + 2289

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bfaa24d8  rdx: 0x00007ff7bfaa2940
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bfaa2520  rsp: 0x00007ff7bfaa24d8
   r8: 0x00007ff7bfaa2540   r9: 0x0000000000000000  r10: 0x00000000000000a8  r11: 0x0000000000000246
  r12: 0x00000000000000a8  r13: 0x00007ff7bfaa2940  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff80acfdb4a  rfl: 0x0000000000000246  cr2: 0x0000000100601000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
    0x7ff80ac94000 -     0x7ff80ad28caf dyld (*) <bba77709-6cad-3592-ab03-09d0f7b8610e> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=183.3M resident=0K(0%) swapped_out_or_unallocated=183.3M(100%)
Writable regions: Total=8708K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8708K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                             267K        2 
__DATA_CONST                        20K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       181.9M        3 
__TEXT                            1396K        2 
dyld private memory                512K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            248.1M       16 

-----------
Full Report
-----------

{"app_name":"SQLPro for SQLite","timestamp":"2023-04-11 14:48:11.00 +1000","app_version":"2023.31","slice_uuid":"e0233d8c-472b-31a2-856f-eda70ee3381d","adam_id":"586001240","build_version":"4311.5","platform":1,"bundleID":"com.hankinsoft.osx.sqliteprofessional","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.2.1 (22D68)","roots_installed":0,"name":"SQLPro for SQLite","incident_id":"48D79819-686B-4A13-BEA1-1F988ED83FF4"}
{
  "uptime" : 75000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro16,1",
  "coalitionID" : 5231,
  "osVersion" : {
    "train" : "macOS 13.2.1",
    "build" : "22D68",
    "releaseType" : "User"
  },
  "captureTime" : "2023-04-11 14:48:11.6882 +1000",
  "incident" : "48D79819-686B-4A13-BEA1-1F988ED83FF4",
  "pid" : 13672,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-04-11 14:48:11.6803 +1000",
  "procStartAbsTime" : 75774574926152,
  "procExitAbsTime" : 75774582626341,
  "procName" : "SQLPro for SQLite",
  "procPath" : "\/Applications\/database_stuff\/SQLPro for SQLite.app\/Contents\/MacOS\/SQLPro for SQLite",
  "bundleInfo" : {"CFBundleShortVersionString":"2023.31","CFBundleVersion":"4311.5","CFBundleIdentifier":"com.hankinsoft.osx.sqliteprofessional"},
  "storeInfo" : {"storeCohortMetadata":"10|date=1681187400000&sf=143460&pgtp=Search&pgid=osx&prpg=Genre_25211&ctxt=Search&issrch=1&imptyp=card&kind=macSoftware&lngid=27","itemID":"586001240","deviceIdentifierForVendor":"751C2DC0-DE73-5518-B688-99999FEBDDCA","thirdParty":true,"softwareVersionExternalIdentifier":"856170390"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.hankinsoft.osx.sqliteprofessional",
  "crashReporterKey" : "4C9F29BB-9098-3693-8627-9948BED1D447",
  "throttleTimeout" : 2147483647,
  "wakeTime" : 5754,
  "bridgeVersion" : {"build":"20P3045","train":"7.2"},
  "sleepWakeUUID" : "67998BB4-F023-4A68-8865-06431320131B",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/SQLProSQLiteMacOS.framework\/Versions\/A\/SQLProSQLiteMacOS","Referenced from: <E0233D8C-472B-31A2-856F-EDA70EE3381D> \/Applications\/database_stuff\/SQLPro for SQLite.app\/Contents\/MacOS\/SQLPro for SQLite","Reason: tried: '\/Applications\/database_stuff\/SQLPro for SQLite.app\/Contents\/Frameworks\/SQLProSQLiteMacOS.framework\/Versions\/A\/SQLProSQLiteMacOS' (no such file), '\/Applications\/database_stuff\/SQLPro for SQLite.app\/Contents\/Frameworks\/SQLProSQLiteMacOS.framework\/Versions\/A\/SQLProSQLiteMacOS' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS@rpath\/SQLProSQLiteMacOS.framework\/Versions\/A\/SQLProSQLiteMacOS' (no such file), '\/Applications\/database_stuff\/SQLPro for SQLite.app\/Contents\/Frameworks\/SQLProSQLiteMacOS.framework\/Versions\/A\/SQLProSQLiteMacOS' (no such file), '\/Applications\/database_stuff\/SQLPro for SQLite.app\/Contents\/Frameworks\/SQLProSQLiteMacOS.framework\/Versions\/A\/SQLProSQLiteMacOS' (no such file), '\/System\/Library\/Frameworks\/SQLProSQLiteMacOS.framework\/Versions\/A\/SQLProSQLit"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":790945,"threadState":{"r13":{"value":140702049249600},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140702049248576},"cr2":{"value":4301262848},"rdx":{"value":140702049249600},"r10":{"value":168},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703310011210,"matchesCrashFrame":1},"rbp":{"value":140702049248544},"rsp":{"value":140702049248472},"r12":{"value":168},"rcx":{"value":140702049248472},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":432970,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":535815,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":0},{"imageOffset":535865,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":41441,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":0},{"imageOffset":30304,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4502,"imageIndex":0},{"imageOffset":25217,"symbol":"start","symbolLocation":2289,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703309578240,
    "size" : 609456,
    "uuid" : "bba77709-6cad-3592-ab03-09d0f7b8610e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703308972032,
  "size" : 21474836480,
  "uuid" : "57815a20-af2c-3b56-9006-23abde7962b0"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=183.3M resident=0K(0%) swapped_out_or_unallocated=183.3M(100%)\nWritable regions: Total=8708K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8708K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                             267K        2 \n__DATA_CONST                        20K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       181.9M        3 \n__TEXT                            1396K        2 \ndyld private memory                512K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            248.1M       16 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6297d96be2c9387df974efa4",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000013
    }
  ]
}
}

Model: MacBookPro16,1, BootROM 1916.80.2.0.0 (iBridge: 20.16.3045.0.0,0), 8 processors, 8-Core Intel Core i9, 2.3 GHz, 16 GB, SMC 
Graphics: Intel UHD Graphics 630, Intel UHD Graphics 630, Built-In
Graphics: AMD Radeon Pro 5500M, AMD Radeon Pro 5500M, PCIe, 4 GB
Display: Color LCD, 3072 x 1920 Retina, Main, MirrorOff, Online
Display: U2868, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-2G6E1
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-2G6E1
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Dec  1 2022 17:36:56 version 9.30.489.6.32.5.85 FWID 01-23419ed2
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB3.1 Hub
USB Device: USB 10/100/1000 LAN
USB Device: USB31Bus
USB Device: USB2.1 Hub
USB Device: USB 2.0 Hub
USB Device: Generic Billboard Device
USB Device: Magic Trackpad
USB Device: T2Bus
USB Device: composite_device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5

**Comment by hankinsoft** [comment]
Fix is submitted. Should be available for tomorrow. Sorry about that!

**Comment by hankinsoft** [comment]
Version 2023.35 was approved about 10 hours ago and should now be available via the Mac app store. Please update when you get the chance and let me know if this sorts things out for you.

**Comment by hankinsoft** [comment]
Closing. If anyone is using 2023.35 or above and continues to see the issue, please feel free to re-open.
