### ISSUE TITLE
Feature Request: Export into separate files

### ISSUE THREAD

**Issue by DaveSanders** [hankinsoft/SQLPro#899]
**Is your feature request related to a problem? Please describe.**
I'm exporting / importing a large database worth of data, using the Postgres SQL method. When exporting multiple tables, I only have the option to export them to one large sql file.  I can do this manually by going through the process for each individual table, but its very time consuming.

**Describe the solution you'd like**
I'd like the option to be able to export each table into its own file, resulting in a folder with a set of scripts for the database.

**Describe alternatives you've considered**
Only alternative I can think of is to do it manually.

**Environment (please complete the following information):**
 - Device: Mac
 - OS: 13.1.1
 - SQLPro app Version: SQLPro Sutdio 2023.35
- Installation source: App Store
- Target database server Postgres (but this should apply to all exports)

**Comment by hankinsoft** [comment]
Working on this for the next build. You can now check 'Create a file for each entry'. I hope to have it available late next week.

<img width="1270" alt="Screenshot 2023-05-12 at 8 47 44 AM" src="https://github.com/hankinsoft/SQLPro/assets/3160528/fc7d05c6-f14b-4613-a146-d98f8868ec61">

**Comment by DaveSanders** [comment]
Wow, thanks! Great to hear!

Dave

**Comment by DaveSanders** [comment]
Tried it out this morning, and it looks like it's working well. Thank you!

Minor, minor visual bug - the message "Exporting object X of X" might be
using a zero index instead of a 1 index?  It says here that it's exporting
object 9, but it's really working on exporting object 10 in this
screenshot.  Otherwise, it looks good!

[image: image.png]


--
Dave Sanders, Founding Partner
Avenue 80

**Comment by hankinsoft** [comment]
> Minor, minor visual bug - the message "Exporting object X of X" might be
using a zero index instead of a 1 index?  It says here that it's exporting
object 9, but it's really working on exporting object 10 in this
screenshot.  Otherwise, it looks good!

Thanks for that. I've got this fixed up for the next build.

**Comment by hankinsoft** [comment]
You right click on a database or table and choose export -> sql. Similar to this:

<img width="1162" alt="Screenshot 2024-12-03 at 3 23 01 PM" src="https://github.com/user-attachments/assets/09238444-c65d-43d2-bd00-4b0acf3d0ece">

Then you are at the export dialog which looks like this:

<img width="1162" alt="Screenshot 2024-12-03 at 3 23 17 PM" src="https://github.com/user-attachments/assets/d0f1df5c-9b9c-4668-8240-bc4475f53b9f">

**Comment by designosis** [comment]
Right clicking a specific table looks like this ...
![Screenshot 2024-12-03 at 1 19 50 PM](https://github.com/user-attachments/assets/f9106b06-f5c9-430b-8ce5-f56333b72f88)
... and just opens the file browser for where to save the file.

Right clicking the database or the word "Tables" ...
![Screenshot 2024-12-03 at 1 20 21 PM](https://github.com/user-attachments/assets/a1126dbc-d1cc-4ac2-bff7-c0fb92bc6dc2)
... does nothing.

Any tips?

**Comment by designosis** [comment]
I see. So there's no way to batch export MySQL, only MSSQL. Ok thanks!

**Comment by hankinsoft** [comment]
> So there's no way to batch export MySQL, only MSSQL

If you were connected to a MySQL server batch export would be an option, but the MSSQL to MySQL converter unfortunately does not provide that as an option.
