### ISSUE TITLE
New Feature Request: Support for AWS Athena

### ISSUE THREAD

**Issue by pcarlson** [hankinsoft/SQLPro#900]
This is a feature request to support Athena in SQLPro so that I can have people in my company use a better tool to query using Athena.

Here is a link to someone describing some of the different tools that support Athena along with AWS JDBC for Athena.
https://garystafford.medium.com/executing-amazon-athena-queries-directly-from-jetbrains-pycharm-ide-7a2c609bb5f5

**Comment by hankinsoft** [comment]
Thank you. I've actually got a specific thread for 'additional supported database types'. If you get the chance, please upvote 'AWS Athena' at https://github.com/hankinsoft/SQLPro/issues/833#issuecomment-1241912955.

**Comment by pcarlson** [comment]
Thank you.
I have upvoted all the databases I am currently interested in.
Thank you.

--Peter

From: Kyle Hankinson ***@***.***>
Date: Thursday, May 4, 2023 at 7:39 AM
To: hankinsoft/SQLPro ***@***.***>
Cc: Peter Carlson ***@***.***>, Author ***@***.***>
Subject: Re: [hankinsoft/SQLPro] New Feature Request: Support for AWS Athena (Issue #900)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Thank you. I've actually got a specific thread for 'additional supported database types'. If you get the chance, please upvote 'AWS Athena' at #833 (comment)<https://github.com/hankinsoft/SQLPro/issues/833#issuecomment-1241912955>.
