### ISSUE TITLE
no such module: FTS4 

### ISSUE THREAD

**Issue by sserye** [hankinsoft/SQLPro#901]
Hi, using SQLPro for Sqlite on a database with FTS tables it return the following error:

```
Initializing connection...
Connection ready. Took 0.012 seconds.
**no such module: FTS4** 0.000 seconds. (Line 2).
Finished. Total time: 0.013 seconds.
```
I am using the latest version of the App,
Thanks

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2023.41.app.zip and see if that works? If so I'll update the App Store version as well.

In the future, when reporting bugs please ensure you use the template or items will be closed.

**Comment by sserye** [comment]
> Can you try https://sqlprostudio.s3.us-east-1.amazonaws.com/sqlite/SQLProSQLite.2023.41.app.zip and see if that works? If so I'll update the App Store version as well.
> 
> In the future, when reporting bugs please ensure you use the template or items will be closed.

Thank you so much!! it worked !!

Sorry for submitting the issue in the wrong way, thanks for help!

**Comment by hankinsoft** [comment]
Great, I’ll get the App Store version updated as well. It can take 2-3 days
for the update to go through.

**Comment by hankinsoft** [comment]
This should be all sorted for the App Store build. If you get a second can you confirm if it's working properly for you and if so, I'll go ahead and close the issue.
