### ISSUE TITLE
Refresh open Document

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#902]
**Is your feature request related to a problem? Please describe.**

I use SQLPro Studio not only to run queries, but also to develop tutorial documents. One thing I do is to test a query in different database connections, and also in the separate SQL Pro for Oracle.

If I make a change to the document on one tab or in a separate document, I would like SQLPro to be able to reload the document.

**Describe the solution you'd like**

Something like File | Refresh Tab (⌘R) to reload/refresh a currently selected tab.

**Environment (please complete the following information):**
 - Device: Mac Mini M1
 - OS: macOS 13.3.1 Ventura
 - SQLPro app Version: SQLPro Studio Version 2023.35 (Build 111030.5) (Would apply to SQLPro for Oracle)
- Installation source: App Store
- Target database server: Any

**Comment by hankinsoft** [comment]
Are these files that you have saved to disk? I could potentially look into adding a shortcut to reload a save file from disk.

**Comment by manngo** [comment]
Saved to disk.

I notice that SQLPro is aware when a file on disk has changed, even if the change hasn’t bee saved. For example, if I open a file in the Oracle version and type something without actually saving it, and then switch back to Studio and save it, I get a warning about the file’s having been changed.

Actually I’m getting some odd behaviour as I test this. If I have the same document open twice in Studio and switch between the tabs, I sometimes get the message that I no longer have permission to save the original, and I sometimes find the second instance showing up blank.

I suppose opening the same document twice in one application is stretching the friendship a bit.

**Comment by hankinsoft** [comment]
I’ve fixed the issue with opening a document multiple times for the next build and I will be adding a refresh menu item as well.

**Comment by hankinsoft** [comment]
This has been added for the latest SQLPro studio version in the App Store. If you get the chance, please give it a try and let me know if it sorts the issue out.

**Comment by hankinsoft** [comment]
Closed. If not as expected, or you are still having issues, please let me know.
