### ISSUE TITLE
CSV Import UI becomes unresponsive after mapping changes

### ISSUE THREAD

**Issue by gabriel-r** [hankinsoft/SQLPro#907]
**Describe the bug**
While importing a CSV as a new table, setting a column as `<SKIP>` grays out the other columns and doesn't allow reverting to a valid column title.

**To Reproduce**
1. With an open Postgres connection
2. Select a DB and choose the Import CSV option
3. The file is read and the mapping modal window opens
4. Select to "Import xxx rows into a _New table_"
5. Set a new column name to `<SKIP>`
    * **Expected behavior** The column type and Null checkbox should be deactivated. 
    * **Actual result** They instead remain editable, but the changes don't stick. The other fields on the list are grayed out.
 6. Set the column title value back to a valid column title
    * **Expected behavior** The columns become active, editable and have some default values.
    * **Actual result** The fields appear editable, but the changes don't stick.

**Screenshots**

https://github.com/hankinsoft/SQLPro/assets/51084/9f9ccd66-74be-4b5b-a997-01a4a93c5de5

**Environment details (please complete the following information):**
 - Device: MacBook Pro M1
 - OS: macOS latest 13.3.1 (a)
 - SQLPro app Version: SQLPro Studio Version 2023.37 (Build 111031)
- Installation source: Setapp
- Target database server: PostgreSQL (local setup)

**Comment by hankinsoft** [comment]
Investigating now. Sorry for the delay, where I live (Nova Scotia Canada) has been in a state of emergency the last few weeks due to wildfires and are just calming down this week. Should have a fix by early next week.

**Comment by gabriel-r** [comment]
No rush, take care of yourself and close ones!

**Comment by hankinsoft** [comment]
A fix has been pushed to setapp and should be available in ~24 hours or so. If you get the chance, please give it a try when you see the update and let me know if that sorts things out.

**Comment by gabriel-r** [comment]
Works a lot better, thanks! 

Disclaimer: I only tested the UI and didn't run the actual import, but I don't expect that to have changed.
