### ISSUE TITLE
Failed to generate View script

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#908]
**Describe the bug**
Selected a existing view and used the Menu 'Script as' ...'Create to' ... 'New query window' and received the following error

/* Generation failed with the following error: 
ORA-31603: object "SF_DSF_VIEW" of type **TABLE** not found in schema "MOLMAN"

Why does it think this is a **TABLE** and not a **VIEW**?
Selecting a **TABLE** and performing the same menu actions works just fine.

**To Reproduce**
1. Select any view
2. Click on 'Script as' ... 'Create to' ... 'New query window'
3. See error

**Expected behavior**
A creation script would be generated for the **VIEW**.

**Screenshots**
<img width="1005" alt="image" src="https://github.com/hankinsoft/SQLPro/assets/3777526/c8863727-c9ce-44b0-a631-b133d5985883">

**Environment details (please complete the following information):**
 - **Device:** MacBook Pro (2019)
 - **OS:** Ventura 13.4
 - **SQLPro Version:** SQLPro for Oracle 2023.21
 - **Installation source:** App Store
 - **Target database server:** Oracle

**Comment by hankinsoft** [comment]
I should have this sorted for a build next week.

**Comment by hankinsoft** [comment]
New build have been approved and should be available. If not then by tomorrow. If you get the chance, please give it a try and let me know if things are sorted up.

**Comment by cwolcott** [comment]
Version 2023.50 (Build 575.5) fixes the issue.
Thank you.
