### ISSUE TITLE
Default MySQL Connection Options

### ISSUE THREAD

**Issue by joshourisman** [hankinsoft/SQLPro#909]
I'm attempting to debug a strange situation I have where I can use SQLPro for MySQL to successfully connect to and interact with a database, but I cannot seem to get the mysql CLI to connect from the same machine using the same credentials. The only thing I can think of is that SQLPro is setting some option that I'm not, but I haven't been able to find any documentation of what it might be doing.

Is there any reference that might provide a hint of the default connection settings being used by SQLPro?

**Comment by hankinsoft** [comment]
Hi,
The only options I could think of would be the compassion enabled option and the authentication method option. I don't know much about the mysql command line so, I'm not sure exactly how you would specify them either. Good luck!
