### ISSUE TITLE
Closing all tabs freezes the app

### ISSUE THREAD

**Issue by heruan** [hankinsoft/SQLPro#91]
I'm on SQLPro Studio 1.0.115 (Build 1046) and when I right-click + close all tabs the app freezes and I have to forcibly quit.

**Comment by hankinsoft** [comment]
Can you try: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.118.app.zip?

It should sort the crash, but has an underlying issue. If you have more than one unsaved tab when you choose to close all, it will stop at the first unsaved tab and prompt you if you want to save (breaking the 'close all' cycle).

As someone who uses this feature, what would your preferred behaviour be when closing all tabs? (Specific to the case that you have more than one unsaved tabs).

Should it:
1. Close tabs without prompting (possibly loosing unsaved work).
2. Prompt that you have X unsaved tables, with the options to review, close all, or cancel?
3. Other?

**Comment by heruan** [comment]
Thank you for the updated app!

I see two possible behaviors when closing all tabs with unsaved data on one or more:

1. prompt to save those, one by one (e.g. like Atom does)
2. a single prompt with a checkbox list of tabs to save (like Eclipse does)

<img width="397" alt="screen shot 2017-04-05 at 08 22 51" src="https://cloud.githubusercontent.com/assets/851745/24692511/b105c822-19d9-11e7-9fd0-10855f587cdc.png">

I understand options 2 could be tricky to implement, but option 1 seems pretty simple. BTW, I'd exclude your first option, of course, since unsaved data should never be discarded without notice; your option 2 could work if you let also a "save all" option ("review" and "cancel" are the same, I suppose).

**Comment by hankinsoft** [comment]
Closing this one as the freeze no longer occurs. I've been working on better restore/recovery/messages on close, but I'm going to reference those in item #63.
