### ISSUE TITLE
Unable to Filter Multiple Columns Using "Any"

### ISSUE THREAD

**Issue by wchisenski** [hankinsoft/SQLPro#910]
**Describe the bug**

First of all, I'm not sure if this is working "as designed", or if this is a bug. Using Filter, it appears that you should be able to use a dropdown (select) list to either choose "All of the following are true", or possibly "Any of the following are true", but the only option is "All". Which limits the capability of the filter feature and requires someone to write a SQL query instead by using an OR (instead of AND).

**To Reproduce**

1. Click the Filter button
2. Add a second filter condition
3. Click on "All", expecting to see other options (like "Any").

**Expected behavior**

Given that this is a selectable dropdown field, one would expect more options. Only having "All" limits the filter capabilities.

**Screenshots**

<img width="429" alt="image" src="https://github.com/hankinsoft/SQLPro/assets/53623427/84576284-1b6e-413c-a74b-379327baeeee">

**Environment details (please complete the following information):**

 - Device: MacBook Pro 14-inch, 2021 (M1 Pro)
 - OS: macOS Ventura 13.4
 - SQLPro for SQLite 2023.43 (build 4343.5)
- Installation source: App Store
- Target database server SQLite Files

**Comment by hankinsoft** [comment]
Investigating this now.

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2023.45.app.zip? If that sorts it out, I'll get the App Store build submitted as well.

**Comment by wchisenski** [comment]
Hi Kyle,

The latest build provided seems to address the issue, thank you! Look forward to the update via the App Store.
