### ISSUE TITLE
Add shortcut keys and menu support for query result export

### ISSUE THREAD

**Issue by normal-coder** [hankinsoft/SQLPro#913]
**Is your feature request related to a problem? Please describe.**

When I export SQL queries(just like export csv file or json file), I always need to interact with the mouse instead of using shortcut keys, which makes my efficiency suffer.

**Describe the solution you'd like**

Hope to add shortcut keys and menu support for the export function

**Describe alternatives you've considered**
1. Different types of export support different shortcut keys at the same time.
2. The same problem, support different menu options (macOS has a global menu search, you can use the shortcut menu search to replace the shortcut keys, I use the third-party menu assistant tool Paletro, which is very helpful to me).

**Additional context**

![image](https://github.com/hankinsoft/SQLPro/assets/6902432/2529f5af-0610-4ef5-9c11-9e8b350c89a7)

![image](https://github.com/hankinsoft/SQLPro/assets/6902432/bb5e1666-6294-4643-9760-682c15d57d82)

**Environment (please complete the following information):**
 - Device: MacBook Pro
 - OS: macOS
 - SQLPro app Version: SQLPro Studio Version 2023.35 (Build 111030)
- Installation source: Website download
- Target database server: All

**Comment by hankinsoft** [comment]
Can do. Any default shortcut suggestions for either? If not, I'll leave them unset by default.

**Comment by normal-coder** [comment]
> Can do. Any default shortcut suggestions for either? If not, I'll leave them unset by default.

It seems that there is no good way. Can consider `Cmd E` and then do the second step selection (like VSCode)? certainly. Setting shortcut keys individually is also worth considering. . .

also. A menu is necessary. I can call up the global help by default `Cmd /`, and quickly call this function by searching, which is the design of macOS.

**Comment by hankinsoft** [comment]
If you get the chance, could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2023.55.app.zip? That should add the shortcuts. They have no default value, so you will need to set the shortcut to a value of your choice.

**Comment by hankinsoft** [comment]
Going to close. If you have any issues with this, please feel free to reopen.
