### ISSUE TITLE
Right-align numbers/numerical values in results table

### ISSUE THREAD

**Issue by gabriel-r** [hankinsoft/SQLPro#914]
**Is your feature request related to a problem? Please describe.**
In a big results table, it would be much easier to scan numerical values if they were right aligned. This is the standard in spreadsheet and any other data table UI. 

**Describe the solution you'd like**
Columns of numerical type are right aligned. 

**Describe alternatives you've considered**
Exporting the results to a spreadsheet. Or, squinting. 

**Additional context**
![Screenshot 2023-06-29 at 12 45 56 Preferences@2x](https://github.com/hankinsoft/SQLPro/assets/51084/76dfb174-6778-4741-b72d-53205d43091e)

**Environment (please complete the following information):**
 - Device: Mac with external screen.
 - OS: macOS 13.4.1
 - SQLPro Studio Version 2023.45 (Build 111045) 
- Installation source: SetaApp
- Target database server: PostgreSQL

**Comment by hankinsoft** [comment]
Could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2023.49.app.zip?

**Comment by gabriel-r** [comment]
GORGEOUS!

**Comment by hankinsoft** [comment]
Great, I'll get the setapp build submitted here shortly.

**Comment by hankinsoft** [comment]
The Setapp build has been available for about a week or so. If you are having any issues, please let me know.
