### ISSUE TITLE
After timeout, running query doesn't return results

### ISSUE THREAD

**Issue by cwolcott** [hankinsoft/SQLPro#915]
**Describe the bug**
If a tab has not been active for a while and I attempt to execute a command the message area will say "Initializing connection...", but will then finish and not actually execute the command after making the new connection

**To Reproduce**
1. Open a connection and a new query tab
2. Execute 'SELECT * FROM _sometable_'
3. It should return records from the database.
4. What 30 minutes and run the same query in the same tab

**Expected behavior**
Understand we have lost connection and the application needs to reconnect, but I was hoping it would run the query after reconnecting.  The message is confusing when it says "Statement completed successfully" and 0 records are returned.

**Screenshots**
<img width="915" alt="image" src="https://github.com/hankinsoft/SQLPro/assets/3777526/5e551548-3e2c-4e52-a0e9-6baba2fe5f03">

**Environment details (please complete the following information):**
 - **Device:** MacBook Pro (2019)
 - **OS:** Ventura 13.4.1
 - **SQLPro Version:** SQLPro for Oracle 2023.50
 - **Installation source:** App Store
 - **Target database server:** Oracle

**Comment by hankinsoft** [comment]
I believe I've got this fixed for the next SQLPro for Oracle build. I had a bit of trouble reproducing the exact scenario you mentioned, but I was able to get a similar state where the query was saying success, but had obvious failed, which will now display an error. I've got some more Oracle issues to resolve as well, so I expect early September for the release.

**Comment by hankinsoft** [comment]
Going to close the issue. If you continue to run into troubles, please let me know.
