### ISSUE TITLE
Export MySQL empty

### ISSUE THREAD

**Issue by shenghui0779** [hankinsoft/SQLPro#916]
### Version

Version 2023.41 (Build 111041)

### Screenshots

<img width="730" alt="image" src="https://github.com/hankinsoft/SQLPro/assets/67535398/226cde0e-2782-4233-9732-e8aa0943a323">

### Result

The exported file is empty.

**Comment by hankinsoft** [comment]
Closed. Please feel free to reopen once the environmental details listed when filing an issue have been filled out.
