### ISSUE TITLE
Set grid not effective

### ISSUE THREAD

**Issue by shenghui0779** [hankinsoft/SQLPro#918]
#### Version

SQLPro for MySQL Version 2023.10 (Build 105078)

#### Screenshots

<img width="706" alt="image" src="https://github.com/hankinsoft/SQLPro/assets/67535398/5f504712-67da-47fc-8eaf-23f171089df0">

<img width="1270" alt="image" src="https://github.com/hankinsoft/SQLPro/assets/67535398/d27371f8-291e-4001-a4dc-1d94cd8d812c">

**Comment by hankinsoft** [comment]
Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened.
