### ISSUE TITLE
Crash from App Store install (2023.45) on macOS 10.13.6

### ISSUE THREAD

**Issue by jcunningham** [hankinsoft/SQLPro#919]
**Describe the bug**
Launching the app results in crash. Possibly related to issue #895  (https://github.com/hankinsoft/SQLPro/issues/895)

**To Reproduce**
1. Open app
4. See error message in Additional context section

**Expected behavior**
App should launch. If the hardware or OS version isn't supported, app store shouldn't update and old version would be used. App Store compatibility lists macOS version 10.12 or later is supported.

**Screenshots**
n/a

**Environment details (please complete the following information):**
 - Device:MacBook Pro 2010
 - OS: 10.13.6
 - SQLPro app Version: SQLPro for SQLite 2023.45
- Installation source: App Store
- Target database server: SQLite

**Additional context**
Details from the crash report...

Process:               SQLPro for SQLite [90909]
Path:                  /Applications/SQLPro for SQLite.app/Contents/MacOS/SQLPro for SQLite
Identifier:            com.hankinsoft.osx.sqliteprofessional
Version:               2023.45 (4345.5)
App Item ID:           586001240
App External ID:       858104519
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SQLPro for SQLite [90909]
User ID:               501

Date/Time:             2023-07-02 15:41:52.219 -0600
OS Version:            Mac OS X 10.13.6 (17G14042)
Report Version:        12
Anonymous UUID:        14187884-08C8-9C3C-BE7C-C3EA38F4914E

Sleep/Wake UUID:       AAF67DB3-53C6-4A28-95B2-AF1DCC9F406F

Time Awake Since Boot: 4300000 seconds
Time Since Wake:       24000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/SQLProSQLiteMacOS.framework/Versions/A/SQLProSQLiteMacOS
  Referenced from: /Applications/SQLPro for SQLite.app/Contents/MacOS/SQLPro for SQLite
  Reason: no suitable image found.  Did find:
	/Applications/SQLPro for SQLite.app/Contents/MacOS/../Frameworks/SQLProSQLiteMacOS.framework/Versions/A/SQLProSQLiteMacOS: cannot load 'SQLProSQLiteMacOS' (load command 0x80000034 is unknown)
	/Applications/SQLPro for SQLite.app/Contents/MacOS/../Frameworks/SQLProSQLiteMacOS.framework/Versions/A/SQLProSQLiteMacOS: stat() failed with errno=1

Binary Images:
       0x106bc6000 -        0x106c8dff7 +com.hankinsoft.osx.sqliteprofessional (2023.45 - 4345.5) <D0D641DF-5546-3DD1-AE3E-D55BD5182179> /Applications/SQLPro for SQLite.app/Contents/MacOS/SQLPro for SQLite
       0x10ea5c000 -        0x10eaa6adf  dyld (551.5) <CB9BFB56-4511-36F1-A546-891FF770C01C> /usr/lib/dyld
    0x7fff38124000 -     0x7fff38f82fff  com.apple.AppKit (6.9 - 1561.61.100) <4E6EA3FA-8C2C-3B21-BFF9-6F8C458B7BE1> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3ccd3000 -     0x7fff3d09affb  com.apple.Foundation (6.9 - 1455.300) <0479E072-1DD0-3881-A9A2-EDAD3EE58C23> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff45f75000 -     0x7fff461c1ff7  com.apple.QuartzCore (1.11 - 584.64.2) <FD9A3180-479E-3DAC-9CF0-0D214C7E46A7> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff469f9000 -     0x7fff46d24fff  com.apple.security (7.0 - 58286.70.19) <E118FC23-2E20-3999-826B-58488049A277> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff4718c000 -     0x7fff471fcff3  com.apple.SystemConfiguration (1.17 - 1.17) <41D509AB-AED3-30FF-BB00-615BB5A8AC00> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff60b23000 -     0x7fff60b79fff  libc++.1.dylib (400.9) <142D6292-F30F-3949-9F37-3C97A579F540> /usr/lib/libc++.1.dylib
    0x7fff624d5000 -     0x7fff62662ff7  libsqlite3.dylib (274.8.1) <B70A2908-E0F7-364E-952A-1D2D19787B89> /usr/lib/libsqlite3.dylib
    0x7fff629bd000 -     0x7fff629cfffb  libz.1.dylib (70) <47278BDC-596E-3037-B8DA-05FE9D5DBEF6> /usr/lib/libz.1.dylib

Model: MacBookPro6,1, BootROM 99.0.0.0.0, 2 processors, Intel Core i5, 2.53 GHz, 8 GB, SMC 1.57f18
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x0198, 0x393930353432382D3030352E4130324C4620
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x0198, 0x393930353432382D3030352E4130324C4620
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.7f22, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: OCZ-VERTEX4, 512.11 GB
Serial ATA Device: HL-DT-ST DVDRW  GS23N
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB Receiver
USB Device: IR Receiver
USB Device: Built-in iSight
Thunderbolt Bus:

**Comment by hankinsoft** [comment]
Submitting a build now which should sort this out. It should be available within ~24 hours or so.

**Comment by hankinsoft** [comment]
Should be all sorted. If you are still seeing issues, please let me know.
