### ISSUE TITLE
Feature request Script as -> Select to...

### ISSUE THREAD

**Issue by jackfruh** [hankinsoft/SQLPro#92]
Tools like MSSQL management studio have a feature to create a new query in a new window.
The queries they generate list every field 

ie 

   Select  [field1]
               ,[field2]
              ,[field3]
   From [dbo].[tablename]

This is a nice timesaver if a user needs to create a query with a subset of field names from a table with a lot of fields.

**Comment by hankinsoft** [comment]
I'm not 100% sure what you mean by this. You want a script as select option that shows the column names basically?

**Comment by jackfruh** [comment]
Hi Kyle, yep that was the request, SQL server management studio does this, when you do a "Select first 1000 rows" what you get is a select statement with all the fields, instead of a select *

This benefits users who don't want all the fields in the output.

With select *, a user must delete the star, then add each field they want.
With the field list, they can just comment out each field they want to remove from the output.

**Comment by hankinsoft** [comment]
Added for the next build. Should be available next week!

**Comment by hankinsoft** [comment]
FYI, this has been around for the last few builds. I'm going to close the issue, but feel free to let me know if you run into any issues with it.
