### ISSUE TITLE
iCloud Sync appears to not be working

### ISSUE THREAD

**Issue by DJFriar** [hankinsoft/SQLPro#921]
**Describe the bug**
I bought a new computer, and while setting it up I noticed that the connections list does not match what is on my other computer.

**To Reproduce**
1. Open the app
2. The Connections screen appears automatically.
3. Compare both machines and see that they have very different content.

**Expected behavior**
Both computers should have identical connection lists.

**Screenshots**
Withheld for privacy/security reasons.

**Environment details (please complete the following information):**
 - Device: Mac Studio M1 & MacBook Pro M2
 - OS: macOS 13.5 on both
 - SQLPro app Version: SQLPro Studio 2023.35 (Build 111030) on both
- Installation source: Website
- Target database server: MySQL

**Additional context**
Log Files from both machines are attached. It appears that the MBP and MS have 7 entries that are matched, but there are 4 on the MS that are not appearing on the MBP.

**Attachments**
[Mac Studio M1 Logs.zip](https://github.com/hankinsoft/SQLPro/files/12165834/Mac.Studio.M1.Logs.zip)
[MBP M2 Logs.zip](https://github.com/hankinsoft/SQLPro/files/12165831/MBP.M2.Logs.zip)

## Issues will be closed until environmental details are provided.
If the above template is not completed, issues with be closed with the statement `Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened`.

**Comment by hankinsoft** [comment]
There was an issue on older SQLPro versions where iCloud sync was having troubles. If you've just upgraded one of those systems lately, you might need to modify a connection for them to sync over properly. I would suggest on the system that has the 'proper' connection list to make a small change (alias maybe) to one of the connections and save it. Give it a few minutes, then re-launch SQLPro on the other system and see if the change has made it through.

Also, just to confirm, both systems are using the same iCloud account and iCloud Keychain is enabled on both?

**Comment by DJFriar** [comment]
Editing the alias did make it sync again. Thank you!
