### ISSUE TITLE
Renaming a table doesn't update autocomplete suggestions

### ISSUE THREAD

**Issue by gabriel-r** [hankinsoft/SQLPro#922]
**Describe the bug**
Renaming a table doesn't update autocomplete suggestions, old table name still listed

**To Reproduce**
1. Connect to a Postgres DB, with a table name `myrecords_once`
2. Type a query and notice the nice autocomplete for table names
3. Rename the table to `myrecords_later`
2. Type a query and "oh no!"

**Expected behavior**
New table name should be listed

**Screenshots**
![Screenshot 2023-07-29 at 15 10 47  SQLPro Studio — public p1_ids_2023_upto_07-28](https://github.com/hankinsoft/SQLPro/assets/51084/7d4419f5-cb5e-419f-88ac-b0cf1068f46c)

**Environment details (please complete the following information):**
 - Device: MacBok M1
 - OS: macOS 13.4.1 (22F82)
 - SQLPro app Version: Version 2023.50 (Build 111050)
 - Installation source: Setapp
- Target database server: PostgreSQL

**Comment by hankinsoft** [comment]
If you wait about 10 seconds, then check the autocomplete again, has it updated?

**Comment by gabriel-r** [comment]
A good workaround is to use the Refresh option in the table or DB contextual menu. But it still looks and feels bad.

**Comment by hankinsoft** [comment]
Fixed for a build which should be available late next week.
