### ISSUE TITLE
Renaming a table has old name in example instead of placeholder

### ISSUE THREAD

**Issue by gabriel-r** [hankinsoft/SQLPro#923]
**Describe the bug**
Renaming a table has old name in example instead of placeholder, so it can't be _edited_ only retyped.

**To Reproduce**
1. Connect to a DB, i.e Postgres
2. In the left side bar, right-click a table and "Rename table…"
3. In the dialog, notice the input field has the old name as an example, instead of an editable placeholder

**Expected behavior**
The table name field to have the old name, editable and all.

**Screenshots**
![Screenshot 2023-07-29 at 15 16 47@2x](https://github.com/hankinsoft/SQLPro/assets/51084/2a6ea1f3-b1bf-4ede-985f-d86f9beab0fb)

**Environment details (please complete the following information):**
 - Device: MacBok M1
 - OS: macOS 13.4.1 (22F82)
 - SQLPro app Version: Version 2023.50 (Build 111050)
 - Installation source: Setapp
- Target database server: PostgreSQL

**Comment by hankinsoft** [comment]
This is sorted for a future build. Possibly available late next week.

**Comment by hankinsoft** [comment]
2023.56 should now be available on setapp and should sort this. If you get the chance, please check if this now works as expected.

**Comment by gabriel-r** [comment]
Works great! 

tested on latest SetApp build.
