### ISSUE TITLE
Import JSON files with nested fields

### ISSUE THREAD

**Issue by gabriel-r** [hankinsoft/SQLPro#925]
The new JSON import works well for "flat" JSON files. Even very large files seems are parsed nicely and fast. However, the import will only convert the _root_ level elements, while nested fields are imported as text.

Add support for nested JSON fields to support the any generic JSON documents exports. 

For example, this JSON content:

```JSON
[
  {
    "documentation": "For region ap-south-1",
    "expect": {
      "endpoint": {
        "url": "https://appstream2-fips.ap-south-1.api.aws"
      }
    },
    "params": {
      "UseDualStack": true,
      "UseFIPS": true,
      "Region": "ap-south-1"
    }
  },
  {
    "documentation": "For region ap-south-2",
    "expect": {
      "endpoint": {
        "url": "https://appstream2-fips.ap-south-1.amazonaws.com"
      }
    },
    "params": {
      "UseDualStack": false,
      "UseFIPS": true,
      "Region": "ap-south-1"
    }
  }
]
```

Should result in column names like:

![Screenshot 2023-12-20 at 15 44 31 Untitled@2x](https://github.com/hankinsoft/SQLPro/assets/51084/c3c913e6-0e38-4f7d-bcce-4964c2778a6d)

```CSV
"documentation","expect.endpoint.url","params.UseDualStack","params.UseFIPS","params.Region"
"For region ap-south-1","https://appstream2-fips.ap-south-1.api.aws",true,true,"ap-south-1"
"For region ap-south-2","https://appstream2-fips.ap-south-1.amazonaws.com",false,true,"ap-south-1"
```

_Originally posted by @gabriel-r in https://github.com/hankinsoft/SQLPro/issues/924#issuecomment-1671054289_

**Comment by hankinsoft** [comment]
No plans for this at the moment. If enough users request support for nested fields, I'll re-evaluate support for them.
