### ISSUE TITLE
Syntax highlighting suddenly stops working

### ISSUE THREAD

**Issue by jonjacs** [hankinsoft/SQLPro#929]
**Describe the bug**
Suddenly the syntax highlightning stops working. Only colored item left is strings (in red). The green (keyword) and blue (tables and columns) stops working and becomes grey as unhighlighted text. Sometimes after just opening the program with a few tabs open and just waiting a minute or two. Sometimes after working a while. To make it work again, the program has to be closed and reopened.

**To Reproduce**
Unfortunately I cannot find a good way of reproducing it. It just suddenly happens.
Will add steps if I can find what triggers it.

**Expected behavior**
The syntax highlightning should work.

**Screenshots**
Currently no screenshot.

**Environment details (please complete the following information):**
 - Device: MacBook Pro, 15-inch 2019
 - OS: macOS Ventura 13.5
 - SQLPro Studio Version 2023.56 (Build 111056.5)
- Installation source: App Store
- Target database server: PostgreSQL

**Additional context**
Nothing special.

**Comment by hankinsoft** [comment]
If you are able to provide a way to reproduce this, please let me know and re-open the issue.
