### ISSUE TITLE
Connection fails when restarting system

### ISSUE THREAD

**Issue by unikitty37** [hankinsoft/SQLPro#93]
When using a database on localhost, with postgresql installed using Homebrew, SQLPro does not reconnect correctly when the system is rebooted.

Steps:
1. Reboot system, making sure that "reopen windows when logging back in" is selected.
2. Log back in.
3. SQLPro restarts.
4. SQLPro fails to connect to the local database, because it has restored and tried to reconnect ahead of PostgresQL completing startup.

When SQLPro is restoring previous connections on startup, would it be possible for it to wait a few seconds and retry any failed ones before throwing an error dialog and causing the Dock icon to bounce incessantly?

I'm running version 1.0.85 (build 200) — I assume this is the latest version, but I can't actually find any autoupdate button, and the download link doesn't say what the current version is. It might be useful to make that a bit easier to find, as it's a pain to keep downloading the installer just in case it's been updated :)

**Comment by hankinsoft** [comment]
Hi,
SQLPro does not actually restore the previous connection at startup. Could you possibly post the error message you are seeing if you get the chance?

**Comment by unikitty37** [comment]
I get `Failed to connect to 'localhost' on port 5432. Connection refused.` in the "My connections" panel. Unfortunately I can't get the message that is shown on startup without logging out or rebooting.

macOS will restore the previously opened database windows when restarting the app after a reboot, which is standard behaviour, so if any database windows were open when the app is restored by macOS, they will be reopened after the reboot, and SQLPro will try to reconnect then.

This is desired behaviour, as the point is to make rebooting for OS updates as painless as possible, and to get users back to the state they were in immediately before the reboot (but with updated software, obviously).

Having to manually close and reopen all the SQLPro windows is not painless, nor is having the Dock icon continually bounce until I take this step :)

**Comment by hankinsoft** [comment]
I'm going to close this for the time being. If I get more requests from additional users, I will take a look at opening it back up.
