### ISSUE TITLE
high cpu usage, while doing nothing

### ISSUE THREAD

**Issue by dotob** [hankinsoft/SQLPro#930]
**Describe the bug**
high cpu usage, while doing nothing. no query running. app is in the background

**To Reproduce**
not clear why or when this happens. 

**Expected behavior**
when is not running any tasks it should not use a signifikant amount of cpu

**Screenshots**
-

**Environment details (please complete the following information):**
 - Device: macbook pro intel i7 2020
 - OS: macos 13.4.1
 - SQLPro app pro studio Version 2023.56 (Build 111056)
- Installation source: setapp
- Target database server postgres

**Comment by hankinsoft** [comment]
When you seeing this, are there tabs open? Any connections to any databases open? Could you send a log file while you are seeing the high CPU usage? You can find one by going -> 'View' -> 'Logs'.

**Comment by dotob** [comment]
dear kyle,

thanks for getting back. some days ago i changed my main laptop from an old
intel macbook pro to a new m2 version. until now sqlstudio pro works like a
charm.

nevertheless: yes i had multiple tabs open and i am always connected to
5-10 databases.

greetings
sebastian

**Comment by hankinsoft** [comment]
Alight. Im going to close the issue - if you reproduce it, please provide me with the log files.
