### ISSUE TITLE
License invalid message after laptop switch

### ISSUE THREAD

**Issue by mburnsandroid** [hankinsoft/SQLPro#931]
**Describe the bug**
I purchased a license. When I got a new laptop (a year or 2 later). It says that the license is invalid on the new laptop.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment details (please complete the following information):**
 - Device: MacBook
 - OS: macOS 13.4.1
 - SQLPro app Version: SQLPro Studio 2023.35]
- Installation source: Website download
- Target database server: Microsoft SQL Server

**Additional context**

## Issues will be closed until environmental details are provided.
If the above template is not completed, issues with be closed with the statement `Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened`.

**Comment by hankinsoft** [comment]
Hi,
For a website download, you will need to enter the license key details into the license dialog. Have you done that?

**Comment by hankinsoft** [comment]
Also, did you purchase via the website? If you purchase via the App Store, you will need to re-download via the App Store again.

**Comment by mburnsandroid** [comment]
Yes. I entered the email address and license code that I saved off from the original install.
I believe that I installed both times from the website, but maybe the first time I installed it was from the app store.

**Comment by mburnsandroid** [comment]
I could try that.

**Comment by mburnsandroid** [comment]
That worked! I downloaded it from the store and the key worked. Thanks. Sorry for the trouble.
