### ISSUE TITLE
MySQL supports to set `Charset` and `Collation` for columns.

### ISSUE THREAD

**Issue by shenghui0779** [hankinsoft/SQLPro#935]
- **Querious**

![image](https://github.com/hankinsoft/SQLPro/assets/67535398/3195af09-dea9-48c3-be66-53ae39dcbfd5)

If add `reset auto increment value` support, that's good !

![image](https://github.com/hankinsoft/SQLPro/assets/67535398/8262f295-b163-4914-a90d-871ce8195895)

**Comment by hankinsoft** [comment]
Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened
