### ISSUE TITLE
You don't support identity columns in postgresql

### ISSUE THREAD

**Issue by willer** [hankinsoft/SQLPro#938]
**Describe the bug**
Identity columns are not identified as such anywhere. Not in the Alter Table screen, and not in generated scripts.

**To Reproduce**
look at a table with identity columns

**Expected behavior**
show the identity columns

**Screenshots**

**Environment details (please complete the following information):**
SQLPro for Postgresql on Mac

**Additional context**
This is a column type that Postgresql apparently added with version 10.

## Issues will be closed until environmental details are provided.
If the above template is not completed, issues with be closed with the statement `Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened`.

**Comment by hankinsoft** [comment]
Reproduced. Investigating this now.

**Comment by hankinsoft** [comment]
I've got them showing in the database tree and working for the script as.

<img width="790" alt="Screenshot 2023-09-15 at 1 16 44 PM" src="https://github.com/hankinsoft/SQLPro/assets/3160528/20fc859f-d49a-4f56-9fd5-17e5fe43fb2c">

Just need to figure out the UI for the visual alter/creation. Hopefully will have something last next week or early the week after.

**Comment by hankinsoft** [comment]
If you get the chance can you try https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.2023.57.app.zip? That should have improved identity column support.

**Comment by hankinsoft** [comment]
Marking as closed. If you find any issues, please let me know.
