### ISSUE TITLE
Feature Request: Visualize Indent Levels

### ISSUE THREAD

**Issue by neema-esfandi** [hankinsoft/SQLPro#939]
**Is your feature request related to a problem? Please describe.**
It's very difficult to keep track of of the opening partner of a closed parentheses when working with multiple levels of indentation.

**Describe the solution you'd like**
A visualization of the different indent levels similar to VSCode's implementation (the color coding is nice but not necessary)

**Describe alternatives you've considered**
No real alternatives available 

**Additional context**
See VSCode example here
![image](https://github.com/hankinsoft/SQLPro/assets/129785625/3b5cb96a-9222-4c84-8661-637ebfbfd362).

**Environment (please complete the following information):**
 - Device: MacBook
 - OS: macOS 13.4
 - SQLPro app Version 2023.56 (Build 111056.5)
- Installation source: Website Download
- Target database server: PostgreSQL

**Requests will be closed until environmental details are provided.**

**Comment by hankinsoft** [comment]
I like this and will look into adding it for a future build.

**Comment by hankinsoft** [comment]
Could you give this version a try:

https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.2023.58.app.zip?

That should add the vertical indent levels for curly brackets.

**Comment by neema-esfandi** [comment]
Great, thanks for the work on this. I found one issue with (see attached picture).  I replaced a small script's parantheses with the curly brackets and noticed if a blank indention is made , the curly brackets respective vertical indent levels did not shift over with the brackets.

This might just be because of how vertical indent lines are only attached to the curly brackets at the moment , but it might useful to have the indent lines for all tabulations? 

![Screenshot 2023-10-10 at 1 34 58 PM](https://github.com/hankinsoft/SQLPro/assets/129785625/325abaee-b67b-4438-97ec-67903dff49b5)

**Comment by hankinsoft** [comment]
Could you give this build a try? It should include indents for each level.

https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.2023.60.app.zip

**Comment by neema-esfandi** [comment]
This looks great! Exactly what I was looking for

**Comment by neema-esfandi** [comment]
While using it , I have noticed some performance problems with long queries (500+ rows). Lagging cursor and text

**Comment by hankinsoft** [comment]
Can you try:
https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres.2023.61.app.zip

That should resolve the performance issues. Please let me know if you get the chance.

**Comment by hankinsoft** [comment]
Going to mark this as closed. Please let me know if you run into any additional issues.
