### ISSUE TITLE
SQLPro for MS SQLServer - Untrusted domain - Mac unable to logon 

### ISSUE THREAD

**Issue by divyavanmahajan** [hankinsoft/SQLPro#94]
From a Mac that is registered on the domain, Excel is able to connect using NTLM and user credentials. However SQLPro is unable to connect to the same SQL Server
The error is

Connection failed: Login failed. The login is from untrusted domain and cannot be used with Windows Authentication. (Msg 18452, Level 14)

(See Forum messages - http://www.hankinsoft.com/forum/viewtopic.php?f=8&t=1284&p=3283&hilit=Msg+18452&sid=c11b07e638c49fc6ddf6c54b76fa95bb#p3283)

**Comment by hankinsoft** [comment]
Hi,
What format are you using for the username? Are you specifying the
domain/workstation?

Is the sql server on a domain? Or a workstation?

Cheers,
Kyle

**Comment by alopezSILA** [comment]
yes I am using it like that

**Comment by hankinsoft** [comment]
Generally this issue means an incorrect password was specified. Is anyone currently running into this issue? I can post some steps to get audio logins from the server which will help diagnose the issue.

**Comment by alopezSILA** [comment]
> Generally this issue means an incorrect password was specified. Is anyone currently running into this issue? I can post some steps to get audio logins from the server which will help diagnose the issue.

Yes I am, I am using http://www.actualtech.com driver for ODBC connection I tried to resolve it with they support team and they have not been able to see why is this issue or the root cause, also the user us able to get connected using another laptop with the same driver using same credentials.

**Comment by hankinsoft** [comment]
It sounds like you are using a separate product? You will have to contact their support for help.

**Comment by alopezSILA** [comment]
> It sounds like you are using a separate product? You will have to contact their support for help.

I am using sqlPro that use the ODBC connection in MAC to connect to the database, is there any other way to connect sqlPro without using the Mac ODBC connection?

**Comment by hankinsoft** [comment]
SQLPro does not use ODBC. Could you please post a screenshot of the error
message you are seeing?
