### ISSUE TITLE
Allow remapping or disabling Command+number shortcut

### ISSUE THREAD

**Issue by ondrejholecek** [hankinsoft/SQLPro#942]
On my Mac I use Command+number to switch between desktops. But when switching desktop from SQLPro, it always changes the tab to some "random" one (depending to switch desktop number I am jumping to). This is very annoying because I need to manually switch it back when I return to SQLPro.

In SQLPro Keyboard settings there are options to configure "Previous tab" and "Next tab" shortcuts, but it is not possible to configure "Direct tab jump" shortcut.

I would like to have at least an option to disable this shortcut, or (even better) to remap it.

- Device: MacBook
- OS: macOS Ventura
- SQLPro Studio 2023.56
- Installation source: AppStore
- Target database server: all

**Comment by hankinsoft** [comment]
I'll add an option to disable these shortcuts for the next build.

**Comment by hankinsoft** [comment]
Added an option to disable this for the next build (Should be available late next week).

<img width="550" alt="Screenshot 2023-10-27 at 10 19 10 AM" src="https://github.com/hankinsoft/SQLPro/assets/3160528/a054f488-6488-45fd-a154-e2ff703fa7c6">

I'm not currently planning a remap option for it.

**Comment by hankinsoft** [comment]
Build has been available for a bit. If your running into any issues, please let me know.
