### ISSUE TITLE
Conflicting Shortcuts for Shift+Command+C

### ISSUE THREAD

**Issue by adrian-awesome** [hankinsoft/SQLPro#943]
**Describe the bug**
The shortcut for "Copy selected with headers as Comma separated" `Shift+Command+C` is identical to the shortcut to open the Connect prompt from the File menu. Neither of these shortcuts appear to be customizable so remove the overlap.

**To Reproduce**
1. Select results from a completed query
2. Use `Shift+Command+C` to copy the selected data as a comma separated list with headers
3. See the connection box open
4. Data is not copied

**Expected behavior**
One or both of the shortcuts should be customizable to remove the overlap. Preferably both since people will have different personal preferences.

**Environment details (please complete the following information):**
 - Device: M1 MacBook Pro
 - OS: macOS Sonoma 14.0
 - SQLPro app Version: SQLPro Studio Version 2023.61 (Build 111061)
- Installation source: Setapp
- Target database server PostgreSQL

**Comment by hankinsoft** [comment]
Hmmm, thats a good point. I'll do a bit of investigating for the next build.

**Comment by adrian-awesome** [comment]
Hi @hankinsoft !

I now have the ability to change the shortcut to open the connection box, but it doesn't seem to persist after closing the app. I have to re-set the shortcut each first opening.

**Comment by hankinsoft** [comment]
A new build is up. Can you check and see if that sorts this out.

**Comment by adrian-awesome** [comment]
Sorry for not commenting sooner! It is working as intended 😃 

Thanks for the prompt updates!
