### ISSUE TITLE
Delete multiple tables or views at once

### ISSUE THREAD

**Issue by ondrejholecek** [hankinsoft/SQLPro#944]
Very often during development and testing I need to delete many tables/views. Currently it seems that the only way how to do that is one by one. That is very annoying when you need to delete like 20 tables.

I would like to be able to select multiple tables or views and delete them all at once.

It is of course possible to workaround this by creating SQL query and run it when needed, but it is not very comfortable.

- Device: MacBook
- OS: macOS Ventura
- SQLPro Studio 2023.56
- Installation source: AppStore
- Target database server: all

**Comment by hankinsoft** [comment]
Hi,
Unfortunately, deleting multiple tables/views is not something I will add to the app. I don't believe this is something many users would use and IMO it to easy for a user to delete something by accident. Sorry about that!
