### ISSUE TITLE
Closing Query Tab Modal Delete Shortcut or Turn Off

### ISSUE THREAD

**Issue by phillclark** [hankinsoft/SQLPro#949]
When closing a query tab, the modal that pops up asking if you wish to save the document doesn't appear to have any shortcut keys to allow you to seletc the "Delete" option without needing to press the button. Adding a shortcut key to this view would save considerable time having to move the mouse point back and forwards when closing multiple tabs.

Alternatively; in the application settings - add an on/off toggle as to whether the closing tab modal should display or not.

**Comment by hankinsoft** [comment]
> When closing a query tab, the modal that pops up asking if you wish to save the document doesn't appear to have any shortcut keys to allow you to seletc the "Delete" option without needing to press the button. Adding a shortcut key to this view would save considerable time having to move the mouse point back and forwards when closing multiple tabs.

This is a system UI dialog so unfortunately, I don't have any controls over shortcuts on it.

> Alternatively; in the application settings - add an on/off toggle as to whether the closing tab modal should display or not.

I could see adding this. How about 'Auto-close non-file tabs without saving'. Basically the option would only apply to the generated tabs and not tabs that have been opened via 'File' -> 'Open'. Thoughts?

**Comment by phillclark** [comment]
I reckon that would work well as a solution.

**Comment by hankinsoft** [comment]
This should now be available. Please let me know if your seeing any issues.
