### ISSUE TITLE
Unable to view Oracle Timestamp field in table

### ISSUE THREAD

**Issue by tallius** [hankinsoft/SQLPro#95]
Hi,
I am currently working on Oracle 11g Enterprise for a client.
My client is Mac OSX 10.11.6 (15G1217) and SQLPRO Studio 1.0.122 (Build (1054).
I have encountered an issue viewing a table with FieldType as _TIMESTAMP(6)NULLABLE_ returning `Unknown column type: 9`.
From other clients e.g. (Navicat, SQL Developer) I am able to view the timestamp record. 

Thanks.

**Comment by hankinsoft** [comment]
Just to confirm this is all fixed up? We chatted via email.

**Comment by softwareplumber** [comment]
Any possibility you might share the solution? Have same problem.

**Comment by hankinsoft** [comment]
Hi. The Mac App Store version has now been updated. For some reason, the submission had sat at 'in review' for almost a month.
