### ISSUE TITLE
Search function in "Favorites"

### ISSUE THREAD

**Issue by edmond484** [hankinsoft/SQLPro#950]
**Is your feature request related to a problem? Please describe.**

I have over +100 saved query in favorites. It´s really complicated to remember with wich letter did I saved it so I can access my query easily. 
I would LOVE to have a "search" field, in wich I could type any given word of the name of the favorite query so it automatically founds it.

**Describe the solution you'd like**
A search field for the "favorites" query

**Describe alternatives you've considered**
I have to leave MySQL pro and search via Finder in iCloud Drive the wished query.

**Additional context**

That´s sums about it. 
I have been using MySQL for over 3 years now, approximately 2 hours a day.

**Environment (please complete the following information):**
 - Device: MacBook Air 13 - 2022 ''
 - OS: Sonoma 14.1.1
 - SQLPro app Version: SQLPro for MySQL version 2023.27 (build 105082.5)
- Installation source: App Store.
- Target database server:MySQL

**Requests will be closed until environmental details are provided.**

**Comment by hankinsoft** [comment]
I like this idea. I actually have something similar in a side project, so it's something I should be able to port over fairly easy. I'll take a look for an upcoming build.

**Comment by edmond484** [comment]
Thank´s so much! 
It will help me a lot.

Here is an idea of how many saved queries I have.
(There is 3 pages of them)

Thanks!

Sincerely,
Edmond


￼

**Comment by hankinsoft** [comment]
I've got this added, but without the environmental details filled out I'm not sure which build to provide you with. Please fill those out and I'll get a build posted.

For reference this is what the update consists of:

![CleanShot 2023-11-23 at 10 39 37](https://github.com/hankinsoft/SQLPro/assets/3160528/bcf0607b-3d46-4ccb-bd5e-536384ea30a2)

**Comment by edmond484** [comment]
Thanks Kyle!

It seems very good!
I just have one question:
Is it possible to search the favorites query by saved name?
Meaning that if I have a query saved under the name of “Customers by age”, I can search any of those words and the saved items appear?
That´s what would help me the most!


Thanks!

**Comment by hankinsoft** [comment]
It does both, search by name and by contents.

**Comment by edmond484** [comment]
Amazing!
I would love to have those functions!

Thanks a lot!

**Comment by hankinsoft** [comment]
No worries. Again, the environmental details in the initial post need to be filled out before I am able to provide an update.

**Comment by edmond484** [comment]
Of course.

I´m sorry but I don’t understand what are the environmental details that you would like me to fill out.

Can you explain a little bit more so I can provide them to you?


Thanks

**Comment by hankinsoft** [comment]
Open https://github.com/hankinsoft/SQLPro/issues/950 in a browse and look for the 'Environment' section in your first post, then provide the details on each item in that section.

**Comment by edmond484** [comment]
Sorry!
I just updated them.
Thanks so much!
Hoping there's everything you need.

Thanks!

**Comment by hankinsoft** [comment]
SQLPro for MySQL 2023.75 is now available on the Mac app store. If you get the chance, please upgrade and see if this search works as you were expecting.

**Comment by edmond484** [comment]
Hi!

I´m sorry but I can´t find the search button.

(Here are the attached photos)

Thanks.

￼￼

**Comment by hankinsoft** [comment]
Hi,
Unfortunately, photos don't come through via email. You must log into the GitHub site to post them.

**Comment by edmond484** [comment]
Here are the photos.
Thanks!
<img width="633" alt="Captura de pantalla 2023-11-24 a la(s) 9 59 36 a m" src="https://github.com/hankinsoft/SQLPro/assets/151590452/eb78409b-d24e-46e4-8a02-39771372816d">
<img width="1495" alt="Captura de pantalla 2023-11-24 a la(s) 9 59 24 a m" src="https://github.com/hankinsoft/SQLPro/assets/151590452/0aedaef9-180c-4a4a-92e7-1af194a49047">

**Comment by hankinsoft** [comment]
Hi! From the second screenshot you posted, click on the 'Edit Favorites...' button.

**Comment by bbrown** [comment]
I'm only on the trial (seriously considering a switch) but I've found the search field hidden by default aspect of SQLPro to be offputting. For example, in this "Favorites" search Sequel Pro has an integrated search field that gets immediate focus so you can just start typing with the results immediately filtered:

![Screen Shot 2023-12-11 at 11 23 24 AM](https://github.com/hankinsoft/SQLPro/assets/5862/3600791c-310d-4980-9ab7-96eed1337012)

Similarly, on the list of tables the search field is right there instead of behind an eyeglass button:

![Screen Shot 2023-12-11 at 11 25 12 AM](https://github.com/hankinsoft/SQLPro/assets/5862/f26ff930-fad0-408f-9f4c-44e455657fda)

It's not a dealbreaker of course but it's so much more usable since it's rare that anything in a database doesn't require _a lot_ of scrolling.

**Comment by edmond484** [comment]
Yes!!That would be so much better!El 11 dic 2023, a la(s) 12:26 p.m., Bill Brown ***@***.***> escribió:﻿
I'm only on the trial (seriously considering a switch) but I've found the search field hidden by default aspect of SQLPro to be offputting. For example, in this "Favorites" search Sequel Pro has an integrated search field that gets immediate focus so you can just start typing with the results immediately filtered:
Screen.Shot.2023-12-11.at.11.23.24.AM.png (view on web)
Similarly, on the list of tables the search field is right there instead of behind an eyeglass button:
Screen.Shot.2023-12-11.at.11.25.12.AM.png (view on web)
It's not a dealbreaker of course but it's so much more usable since it's rare that anything in a database doesn't require a lot of scrolling.

**Comment by hankinsoft** [comment]
Hi,
I'm on board for adding the search in the favourite dropdown. Should be able to get that added for the next build.

No plans for switching the database search into the main database tree. It used to be there ~4 or 5 years ago, but when I added the additional search options (contains, starts with, etc) I moved it into the secondary search as the UI became cluttered and from analytics not many users were using search to begin with to warrant it having predominant placing in the UI. As a workaround, there is also a configurable 'focus database tree search' keyboard shortcut which can be setup and will swap you directly to the search.

**Comment by hankinsoft** [comment]
A SQLPro for MySQL build has been submitted to apple which contains searching directly in the menu dropdown. @bbrown which version of SQLPro are you using?

**Comment by edmond484** [comment]
Perfect!

I´m using Version 2023.75 (Build 105085.6)

**Comment by bbrown** [comment]
I'm on the trial version from the Web site - `Version 2023.10 (Build 105078)`

**Comment by hankinsoft** [comment]
@bbrown you can grab an updated website version here:
https://d3fwkemdw8spx3.cloudfront.net/mysql/SQLProMySQL.2023.80.app.zip

@edmond484 it usually takes Apple ~24 hours or so to approve a build, so the App Store build will not be available until sometime tomorrow.

**Comment by hankinsoft** [comment]
The App Store version of 2023.80 is now available as well. Once upgraded the search should be available in the favourites dropdown.

**Comment by edmond484** [comment]
LOVE IT 
The search function that way.

Thanks!
Edmond.

**Comment by hankinsoft** [comment]
Great! Going to re-close the issue.
