### ISSUE TITLE
Geo point looks incorrect

### ISSUE THREAD

**Issue by gpolyansky** [hankinsoft/SQLPro#952]
**Describe the bug**
Postgres databases support POINT data type. But this type of data displaying like "0101000020E6100000A0755E0921CE42403DEA7C2CFCE04B40"

**To Reproduce**
1. Go to view database
2. Click on any table, that has geo point data type
3. Look at the data

**Expected behavior**
For example, DBeaver presenting that data type like this:
<img width="302" alt="image" src="https://github.com/hankinsoft/SQLPro/assets/15886508/3b054a73-043c-4dff-9218-8bd2137faa8d">
and displaying map with this point.

**Screenshots**
<img width="297" alt="image" src="https://github.com/hankinsoft/SQLPro/assets/15886508/5da9cc19-b457-4845-9ca6-51d511e8e819">

**Environment details (please complete the following information):**
 - Device: MBP 2021 M1 Pro 16
 - OS: macOS 14
 - SQLPro Studio Version 2023.73 (Build 111073)
- Installation source: Setapp
- Target database server PostgreSQL

**Comment by hankinsoft** [comment]
Hmmm, I'm not able to reproduce this. I've run the following code:

```
CREATE TABLE locations (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    coordinates POINT
);

INSERT INTO locations (name, coordinates) VALUES
('Location1', POINT(40.7128, -74.0060)),
('Location2', POINT(51.5074, -0.1278));

SELECT * FROM locations;

```

And I receive point's as expected:

<img width="1264" alt="Screenshot 2024-01-05 at 8 39 09 AM" src="https://github.com/hankinsoft/SQLPro/assets/3160528/dec4571a-7a8d-470c-a217-e906902ededf">

Would you be able to provide any sort of sample statements to recreate the issue?

**Comment by hankinsoft** [comment]
Closed due to no response.
