### ISSUE TITLE
Feature Request: Limit open connections

### ISSUE THREAD

**Issue by stcherenkov** [hankinsoft/SQLPro#953]
**Is your feature request related to a problem? Please describe.**
Somehow SQLPro Studio consistently keeps hitting connection limit of 5. Sometimes with only 1 tab open, sometimes with 3 open tabs. I can't figure out the pattern and prevent it from reaching the limit.

**Describe the solution you'd like**
I would like to set a limit of open connections in configuration, or have a documentation saying, that I need {number} of connection limit for SQLPro Studio to work properly.

**Describe alternatives you've considered**
Closing old tabs. Not pressing the "connect" button, which seams to refresh all the connections (I guess, this requires establishing one more connection). Increasing connection limit (50 is good, but drains the available PostgreSQL limit too fast).

**Additional context**

**Environment (please complete the following information):**
 - Device: MacBook
 - OS: macOS 14.2.1
 - SQLPro app Version: SQLPro Studio 2023.56
- Installation source: App Store
- Target database server: PostgreSQL 15

**Requests will be closed until environmental details are provided.**

**Comment by hankinsoft** [comment]
Hi,
Unfortunately, this is something I currently won't be able to implement. When the product was built, it was built with using as many connections as possible (as needed) to increase performance. Being built into the core mechanics of the app it's not something which would be changeable without causing side-issues and possible slowdowns for others users. As such this is not something I plan on changing (unless I were to receive many, many requests from users).

Sorry about that!
