### ISSUE TITLE
Status shows Initializing connection... when long running DDL is executing on MySQL

### ISSUE THREAD

**Issue by kpconnell** [hankinsoft/SQLPro#955]
**Describe the bug**
The status pane shows "Initializing Connection" rather than "Query Executing"

**To Reproduce**
1. Issue a **long running** DDL statement that does not return data
2. Observe Results Pane

**Expected behavior**
The status should reflect that the query is running

**Environment details (please complete the following information):**
 - Device: [e.g. iPhone6, MacBook]
 - Macbook M1
 - SQLPro app Version [e.g. SQLPro Studio 2022.x] Please ensure you specify the full app name. (ex: SQLPro Studio, SQLPro for MySQL, etc).
 - Latest App
 - Target database is MariaDB/MySQL on AWS RDS, Latest.
 -

**Comment by hankinsoft** [comment]
Could you please provide the app you are using along with the version? There are multiple SQLPro apps and multiple installation sources which may have different versions.

**Comment by kpconnell** [comment]
Version 2023.35 (Build 111030)
Mac Desktop

**Comment by hankinsoft** [comment]
Hmmm, I'm not able to reproduce this at all:

![CleanShot 2024-02-05 at 08 40 33](https://github.com/hankinsoft/SQLPro/assets/3160528/e2a0cd0b-14f4-40ae-906b-61a6909058f7)

Can you post an example recording of what you're seeing? That should help me figure it out.

**Comment by kpconnell** [comment]
https://www.loom.com/share/41134cdca9cc42b0954042f1121f1fa4?sid=a1c0addc-061e-4447-9d98-1c010dc4a90a

**Comment by hankinsoft** [comment]
Could you try this build:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2024.12.app.zip

That should sort it out.

**Comment by kpconnell** [comment]
It appears that particular issue is resolved in this build, however, the UI in that build is un responsive for me -   90% UI rainbow swirly time.  ( my normal mode of working involves many tabs open across many connections, some of which aren't reachable at a given point in time : ) )

**Comment by hankinsoft** [comment]
Could you give https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2024.13.app.zip a try and see if that improves the hangs?

**Comment by kpconnell** [comment]
@hankinsoft  much better, looks great, thank you!

**Comment by hankinsoft** [comment]
Glad to hear this fixed everything up.
