### ISSUE TITLE
Unable to connect to neon postgresql instance - SSL issue

### ISSUE THREAD

**Issue by bensullivan** [hankinsoft/SQLPro#956]
Hi

I'm trying to connect to a [neon](https://neon.tech/) postgresql instance and I'm getting the following error:

<img width="256" alt="Screenshot 2024-02-05 at 20 02 28" src="https://github.com/hankinsoft/SQLPro/assets/104990/cfcf2c0f-7a22-4cbe-be9b-ff02be0ea7f5">

How do I configure certs on my macos to get the verification to succeed?

I'm on SqlPro Studio 2023.73 on macos 14.3 (intel).

Thanks

Ben

**Comment by hankinsoft** [comment]
Hello. On the SSH tunnelling configuration page what response do you receive if you press the 'Validate' button?

**Comment by bensullivan** [comment]
Seems to work if I configure connection to use macos cert.pem as per doco: 

https://neon.tech/docs/connect/connect-securely#location-of-system-root-certificates

Is this correct for SQL Pro to encrypt traffic to and from neon DB instances?

Thanks

Ben

**Comment by hankinsoft** [comment]
No, I believe you would need to edit the connection, choose 'Advanced' -> 'SSL Configuration'. Set your SSL mode as probably verify-full but possibly require, or verify-ca.

**Comment by bensullivan** [comment]
<div></div><div>No, I believe you would need to edit the connection, choose 'Advanced' -&gt; 'SSL Configuration'. Set your SSL mode as probably verify-full but possibly require, or verify-ca.
<br/>
<br/>-- 
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/hankinsoft/SQLPro/issues/956#issuecomment-1935874041
<br/>You are receiving this because you authored the thread.
<br/>
<br/>Message ID: ***@***.***&gt;</div>

**Comment by hankinsoft** [comment]
Hi,
Unfortunately your response came through jumbled. Any chance you could log into GitHub and repost?

**Comment by bensullivan** [comment]
edited :-)

**Comment by hankinsoft** [comment]
No worries, glad to hear you were able to get everything working.
