### ISSUE TITLE
Columns for Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by fabio-colasanti** [hankinsoft/SQLPro#96]
Having connected to Microsoft Azure SQL Data Warehouse (10.0.9009.9) using SQLPro for MSSQL (desktop distribution, 1.0.148), when I try to expand the columns of a given table from the left hand side tree i get an error:
"Msg 104162, Level 16, state1. 'object_definition' is not a recognized built-in function name"

Let me know if more details needed.
F

**Comment by hankinsoft** [comment]
Hi,
SQL Data Warehouse isn't officially supported, however if your still interested in getting it working and possibly running some test queries, please let me know.
