### ISSUE TITLE
Renaming or dropping a column in a table locks up SQLPro for SQLite

### ISSUE THREAD

**Issue by GaryMeyers1** [hankinsoft/SQLPro#961]
This is probably going to be hard for you to reproduce but I have run PRAGMA integrity_check on my database.  I tried to rename a column in a table with just 195 rows and 52 columns but SQLPro locked up.  I exported the data from the table into a JSON file and then truncated the table, but the rename attempt still locked up SQLPro.  I then clicked the minus sign in the upper right corner to drop the column, with the table still being empty, and SQLPro locked up.  I downloaded another app from the internet to drop the column from the table.  I then launched SQLPro and loaded my JSON data, mapping the deleted column to SKIP. 

**Expected behavior**
SQLPro should have renamed the column without an error.  SQLPro should have dropped the column without an error.

**Screenshots**
<img width="857" alt="column rename" src="https://github.com/hankinsoft/SQLPro/assets/60852956/512f7cfa-aeb5-4d13-87c3-94ec1f7829ca">
<img width="903" alt="column drop" src="https://github.com/hankinsoft/SQLPro/assets/60852956/77ee4fe4-e844-49cb-a9d6-3d2b8945fdc0">

**Environment details (please complete the following information):**
 - Device: iMac
 - OS: 13.6.4 (22G513)
 - SQLPro for SQLite: Version 2024.10 (Build 4361) 
- Installation source: Website download

**Comment by GaryMeyers1** [comment]
I have old versions of my database that I can delete records from, to make them small enough to email to Kyle, after confirming that the rename and drop operations also fail on those smaller files.

**Comment by GaryMeyers1** [comment]
I emailed a sample database to Kyle that locks up when dropping a column.

**Comment by hankinsoft** [comment]
Reproduced and am working on a fix now.

**Comment by hankinsoft** [comment]
Could you try this build:

https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2024.12.app.zip

And let me know if that helps out?

**Comment by GaryMeyers1** [comment]
I both dropped and renamed a column in this table from a mid-February version of my database.  Both operations succeeded without locking up SQLPro.

Thank you,
Gary

On Mar 4, 2024, at 12:26 PM, Kyle Hankinson ***@***.***> wrote:


Could you try this build:

https://sqlprostudio.s3.us-east-1.amazonaws.com/sqlite/SQLProSQLite.2024.12.app.zip

And let me know if that helps out?

**Comment by hankinsoft** [comment]
Great, thanks for letting me know!
