### ISSUE TITLE
Host 'xxx' is not allowed to connect to this MySQL server. (Error #1130)

### ISSUE THREAD

**Issue by vvruan** [hankinsoft/SQLPro#962]
I just downloaded sqlpro for mySQL.

After I entered host address, username and password and clicked 'connect', it shows Host 'xxx' is not allowed to connect to this MySQL server. (Error #1130). -- xxx is my ip address.

How can I change my system setting to make successful connection? Many thanks!

**Comment by hankinsoft** [comment]
You will need to configure mysql to allow your current ip address. https://stackoverflow.com/questions/8348506/grant-remote-access-of-mysql-database-from-any-ip-address is an example of how to do this, but your mysql provider should have some details as well.
