### ISSUE TITLE
SQLPro Studio quits unexpectedly

### ISSUE THREAD

**Issue by racain** [hankinsoft/SQLPro#963]
**Describe the bug**
SQLPro Studio closes/crashes every time a I start to write a query.

**To Reproduce**
1. Open the SQLPro Studio app
2. Connect to DB
3. Start writing a query
4. Quits unexpectedly and displays Problem Report

**Expected behavior**
Expected behavior is not to quit unexpectedly midway through each attempt to write a query. 

**Screenshots**
N/A

**Environment details (please complete the following information):**
 - Device: Macbook Pro (15-inch, 2016)
 - OS: MacOS Monterey 12.7.4
 - SQLPro app Version SQLPro Studio 2023.73 (Build 111073.5)
- Installation source: App Store
- Target database server: MySQL and Microsoft SQL Server

**Additional context**
N/A

**Comment by hankinsoft** [comment]
I've submitted build 2024.15 which I believe should solve this. It generally takes Apple ~24 hours or so to approve a build, so hopefully this is available by this weekend.

**Comment by hankinsoft** [comment]
2014.15 should now be available. If you get a moment, please give it a try and see if that sorts things out.

**Comment by racain** [comment]
Unfortunately, I have to report that the problem continues.

**Comment by hankinsoft** [comment]
Hmm, ok. I see a crash report that I believe is related. Doing further investigation. A workaround for the moment, would be to go into the settings and uncheck the 'Enable auto-complete'. That said, I'm hoping to have a fixed build submitted by end of day.

**Comment by hankinsoft** [comment]
If you get the chance, could you grab the build here:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2024.17.app.zip

Try re-enabling autocomplete and see if it continues to crash?

**Comment by racain** [comment]
So far so good, no crash. Thank you very much for the prompt fix!

**Comment by hankinsoft** [comment]
Great, I'll get the App Store version submitted as well (unfortunately, this version won't recognize an App Store purchase). Again, it takes about 24 hours for the App Store version to be approved.

**Comment by hankinsoft** [comment]
FYI the updated version should now be available on the App Store. If you happen to get the chance, please consider leaving a rating or review. You can do so easily by running the query:

rate;

Cheers!
