### ISSUE TITLE
Option for how to resize columns on execution of queries

### ISSUE THREAD

**Issue by sinklair** [hankinsoft/SQLPro#966]
**Is your feature request related to a problem? Please describe.**
When executing a query, the columns are sometimes autosized to fill the width of the results window and sometimes sized to fit the data in each column (I think this is dependent on the number of rows returned). I, personally, prefer the option where columns are sized to fit the data rather than fill the width of the results area, especially when a query returns only a few columns.

**Describe the solution you'd like**
Provide an app setting to allow the user to choose which option they prefer, regardless of the number of results.

**Describe alternatives you've considered**
Another solution (or even a nice additional feature) would be to modify the right-click menu to break "Autosize Columns" into two options - Size to fit and Autosize to window

**Additional context**
![Screenshot](https://github.com/hankinsoft/SQLPro/assets/2170324/822f5920-6770-4c62-8170-1f50c5b6cd71)

**Environment (please complete the following information):**
 - Device: MacBook Pro
 - OS: MacOs 14.2.1
 - SQLPro app Version SQLPro Studio 2024.17
- Installation source: Website download
- Target database server: Postgres

**Comment by hankinsoft** [comment]
Adding the extended menu items for the next build. Thinking of going with:

'Autosize columns' -> 'Size uniform'
'Autosize columns' -> 'Size to data'

The first option will attempt to resize the columns to be the same width. Possibly within the window width if possible. The second option will try and size the columns to the data within them.

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2024.33.app.zip adds the right click option which contains two different sizing options. If you get the chance, please give it a try and let me know if it works as you would expect.

**Comment by sinklair** [comment]
The column sizing seems for "To Content" seems to be sizing to the first row only. Not sure is you can improve on that it's causing truncation on following rows that have more text.
![Screenshot by Dropbox Capture](https://github.com/hankinsoft/SQLPro/assets/2170324/5ad258fa-d1d1-4c71-9ac8-a799daec6e9a)

I'm wondering now if there should be a third option for the old behavior that sized to fit in the window.

**Comment by hankinsoft** [comment]
Thanks for that, I was able to reproduce with a bit more testing. Could you try:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2024.34.app.zip

I think that should sort it out.

**Comment by sinklair** [comment]
Seems now there is a crash on queries with a large number of columns. This statement crashes the app:
```sql
SELECT
	'This',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text',
	'That',
	'This is a long piece of text'
```

**Comment by hankinsoft** [comment]
Oh shoot, that was a dumb mistake on my part. A fixed build is here:

https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2024.35.app.zip

FYI, tables with more than 20 columns will be uniform regardless of the formatting choice. This is to help prevent performance issues. I could potentially increase this a bit if its causing you issues, but I think most tables will be less than 20 columns.

**Comment by sinklair** [comment]
Sounds like a reasonable restriction. 

This version works for me. Thanks
