### ISSUE TITLE
Crash when renaming a column

### ISSUE THREAD

**Issue by tazzben** [hankinsoft/SQLPro#967]
**Describe the bug**
When renaming a column, the app crashes.

**To Reproduce**

Attempt to rename a column by right clicking on the column in the left panel. Note column named "DOT2_Zpos.1".  Trying to rename to "DOT2_Zneg".

**Environment details (please complete the following information):**
 - Device: Mac
 - OS: macOS 14.4.1. (Note: Apple M2 chip)
 - SQLPro for SQLite 2024.10.
- Installation source: App Store.
- Target database server SQLite

**Comment by hankinsoft** [comment]
Thinks for the details. I've submitted a build which I think will sort this out. For App Store builds it usually takes ~24 hours or so for it to be approved. I'll post again once the build is available.

**Comment by hankinsoft** [comment]
The latest build (2024.21) should now be available as an update on the App Store. If you get the chance, please update and let me know if that sorts the issue for you.

**Comment by tazzben** [comment]
@hankinsoft Solved!  Thanks!

**Comment by hankinsoft** [comment]
Awesome, glad to hear it. If you happen to get the chance, would you consider leaving a rating or review on the App Store? As an independent developer, they help me out a ton. There is even a quick way to leave one, by running the query 'rate;'. No worries if not.

**Comment by tazzben** [comment]
@hankinsoft Done!
