### ISSUE TITLE
on tables that have special characters, the default query should handle this

### ISSUE THREAD

**Issue by lifeiscontent** [hankinsoft/SQLPro#968]
**Describe the bug**

in a DB that has a database such as  `#tmp_1st_week` the default query should be valid

**To Reproduce**
1. Create table with special chars
2. double click on table
3. see invalid SQL

**Expected behavior**
```sql
SELECT * FROM public."#tmp_1st_week" LIMIT 1000;
```

**Actual behavior**

```sql
SELECT * FROM public.#tmp_1st_week LIMIT 1000;
```

**Screenshots**

**Environment details (please complete the following information):**
 - Device: [e.g. iPhone6, MacBook]
 - OS: [e.g. iOS8.1, macOS 11]
 - SQLPro app Version [e.g. SQLPro Studio 2022.x] Please ensure you specify the full app name. (ex: SQLPro Studio, SQLPro for MySQL, etc).
- Installation source: [App Store, Website download, Setapp].
- Target database server [e.g. MySQL, PostgreSQL, Microsoft SQL Server, etc]

**Additional context**

## Issues will be closed until environmental details are provided.
If the above template is not completed, issues with be closed with the statement `Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened`.

**Comment by hankinsoft** [comment]
Hello,
I will need the environmental details to continue so that I can target a fix for the right device/os/app/etc. Please provide those details, then re-open.
