### ISSUE TITLE
Truncate doesn't update Data tab

### ISSUE THREAD

**Issue by AlexHedley** [hankinsoft/SQLPro#97]
In SQLPro for SQLite
Version 1.0.105 (Build 2996)

Right click on a Table and Truncate
The #rows count changes to 0 but the Data tab still shows the old records.
Could there be an option to refresh this?
If you click onto another Table and back to the original the Data tab then updates and shows 0 records.

I can understand Query Results still showing but not data.

**Comment by hankinsoft** [comment]
Thank you. I've fixed this for the next build which should be available either late this week or early next week.

**Comment by hankinsoft** [comment]
Build is now available both inside and outside of App Store. If you get the chance, please give it a try. Thanks!

**Comment by AlexHedley** [comment]
Works like a charm, thanks :-)
