### ISSUE TITLE
Textual values are shown as hex strings in sqlite DB

### ISSUE THREAD

**Issue by tempelmann** [hankinsoft/SQLPro#972]
An sqlite3 DB I'm looking at uses types such as "text" for its columns. SQLPro for SQLite shows ALL their values as 0x… strings instead of text, even if the text is fully printable.

However, with other DBs, this does not happen. I cannot figure out what's special about this one DB that makes SQLPro decide to show all text in hex notation.

I have attached a sample DB. The table "badTextDisplay" shows all text fields in hex, while "badTextDisplay2" shows some rows correctly as text in the "name" col, and others as hex. Same odd thing happens with the dates - they, too, shouldn't be showing hex values but proper dates.

Test environment: Version 2024.10 (Build 4361) on macOS 12.7.4 (Intel), English system language with German locale.

[master copy.db.zip](https://github.com/hankinsoft/SQLPro/files/14981041/master.copy.db.zip)

**Comment by tempelmann** [comment]
Ahh, I made a mistake: Turns out the values were _stored_ as BLOBs. The other DB viewer I often use (SQLVue) ignores that and still attempts to show BLOB data as text whenever possible. It would be nice if SQLPro could do the same, assuming either a default encoding or at least simple ASCII (and only if the encoding doesn't it, or if the data contains unprintable chars, especially < chr(32), show it as hex.

**Comment by tempelmann** [comment]
So, basically, this can be turned from a bug report into a feature request.

**Comment by hankinsoft** [comment]
<img width="1530" alt="Screenshot 2024-04-15 at 1 37 48 PM" src="https://github.com/hankinsoft/SQLPro/assets/3160528/cf7be032-84d6-4768-b887-52dcccf14626">
<img width="1530" alt="Screenshot 2024-04-15 at 1 37 41 PM" src="https://github.com/hankinsoft/SQLPro/assets/3160528/bbe1b21d-46ef-4c18-982c-d0dc520a5d02">

Should be sorted here:
https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2024.23.app.zip

**Comment by tempelmann** [comment]
That was fast, and it works! Thank you so much for the effort - I'm still in the middle of working on my project, so that helps me with it (I'm the author of iClip, where I needed this while adding an iOS version, finally). PM me if you like a free license for iClip or for FindAnyFile.

**Comment by hankinsoft** [comment]
Glad to hear it sorted it out. I've actually already got a few of your apps - I recognized the coffee cup from twitter :)
