### ISSUE TITLE
Should escape table/columns for default query in SQLPro for Postgres

### ISSUE THREAD

**Issue by lifeiscontent** [hankinsoft/SQLPro#973]
**Describe the bug**
in a DB that has a database such as  `#tmp_1st_week` the default query should be valid

**To Reproduce**
1. Create table with special chars
2. double click on table
3. see invalid SQL

**Expected behavior**
```sql
SELECT * FROM public."#tmp_1st_week" LIMIT 1000;
```

**Actual behavior**

```sql
SELECT * FROM public.#tmp_1st_week LIMIT 1000;
```

**Screenshots**
<img width="1624" alt="Screenshot 2024-04-15 at 10 11 49 AM" src="https://github.com/hankinsoft/SQLPro/assets/180963/e4d6e48a-1219-44bc-9445-cc823b7ce9f5">

**Environment details (please complete the following information):**
 - Device: Macbook Pro
 - OS: Mac OS 14.4.1
 - SQLPro app Version SQLPro for Postgres Version 2024.21 (Build 1047899.5)
- Installation source: App Store
- Target database server PostgreSQL

**Additional context**

## Issues will be closed until environmental details are provided.
If the above template is not completed, issues with be closed with the statement `Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened`.

**Comment by hankinsoft** [comment]
Ahhh, thanks for those details. I've got this reproduced and fixed. A build has been submitted to apple. It usually takes about 24 hours for it to be approved.

**Comment by hankinsoft** [comment]
Latest build is up and has this all sorted. If you get the chance please let me know if everything is working as expected.

**Comment by lifeiscontent** [comment]
@hankinsoft thanks again for a very quick turn around 🎉
