### ISSUE TITLE
SQLPro Studio is showing all postgres fields as using using identity defaults

### ISSUE THREAD

**Issue by sinklair** [hankinsoft/SQLPro#976]
**Describe the bug**
Using SQLPro Studio 2024.21 connected postgres, I'm seeing all fields showing with the default value of `generated by default as identity`

This is also coming through when you script a table to the clipboard or a window. 

**To Reproduce**
1. Open SQLPro Studio
2. Connect to postgres database
3. Expand any table to show the fields

**Expected behavior**
Correct definition of each field

**Screenshots**
![Screenshot](https://github.com/hankinsoft/SQLPro/assets/2170324/2d82d502-d10e-4f2d-97af-b5c698f1132f)

**Environment details (please complete the following information):**
 - Device: MacBook Pro 14" 2021
 - OS: macOS 14.4.1
 - SQLPro app Version SQLPro Studio 2024.21
- Installation source: Website
- Target database server postgres

**Comment by hankinsoft** [comment]
Hi. What version of Postgres are you connecting to? If you connect to the sample database do you see this as well?

**Comment by sinklair** [comment]
I see this on a local Postgres database running 14.9. I also see this same behavior on Aurora Postgres 15.4.

**Comment by hankinsoft** [comment]
If you run this query:

        SELECT a.attname, a.attidentity, s.seqstart, s.seqincrement
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        LEFT JOIN pg_sequence s ON c.oid = s.seqrelid
        WHERE c.relname = '{TABLE_NAME}'
        AND n.nspname = '{TABLE_SCHEMA}'
        AND a.attnum > 0; -- to ensure we're looking at table columns and not system/internal ones

And replace TABLE_NAME and TABLE_SCHEMA with your actual schema/names, what do you get for results?

**Comment by sinklair** [comment]
| attname | attidentity | seqstart | seqincrement |
| --- | --- | --- | --- |
| id |  | NULL | NULL |
| state_abbrev |  | NULL | NULL |
| maponics_release |  | NULL | NULL |
| maponics_name |  | NULL | NULL |
| geometry |  | NULL | NULL |
| name |  | NULL | NULL |

Not sure if it matters but attidentity is coming back as blank, not NULL.

**Comment by hankinsoft** [comment]
If you get the chance, could you give this build a try:

https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2024.30.app.zip

And let me know if that sorts it?

**Comment by sinklair** [comment]
That has solved it for display in the database tree, but it is still showing when I right click a table and `Script As > Create to > New Query Window`.

**Comment by hankinsoft** [comment]
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2024.31.app.zip?

**Comment by sinklair** [comment]
That did it.

**Comment by hankinsoft** [comment]
Awesome, thanks for letting me know.
