### ISSUE TITLE
Wrong Postgres database version displayed after upgrade

### ISSUE THREAD

**Issue by karlbecker** [hankinsoft/SQLPro#978]
**Describe the bug**
After upgrading a Postgres database running locally on my machine from Postgres 13 to 14, SQLPro for Postgres shows the wrong version

**To Reproduce**
1. Create a database in the main launch screen
2. Connect to it and note the version on the left nav bar (in my case, version 13.10)
3. Upgrade your Postgres database to a newer version
4. Quit SQLPro for Postgres (or just disconnect from the server - but I tried quitting, too, to see if that fixed it)
5. Reopen SQLPro for Postgres, and connect to the database
6. Run `SELECT version();` to see the version of the database, and compare that to the version at the top of the left nav bar

**Expected behavior**
I expect the new version (in my case, version 14.21) to appear in the nav bar, either after I upgrade the server, or quit and reopen SQLPro for Postgres, or after I right-click on the server's name in the left nav bar and choose "Refresh".  

**Screenshots**

![CleanShot 2024-05-13 at 09 38 52@2x](https://github.com/hankinsoft/SQLPro/assets/1091559/80838761-98bb-4d35-a7c2-cf06ce8269a6)

**Environment details (please complete the following information):**
 - Device: MacBook Pro
 - OS: macOS Sonoma 14.4.1
 - SQLPro app Version: SQLPro for Postgres 2024.21 (but it also impacted a previous version from multiple months ago, I just upgraded to 2024.21 to see if it fixed this)
- Installation source: Website download
- Target database server: PostgreSQL

**Comment by hankinsoft** [comment]
Could you try right clicking on the database, choosing disconnect, then reconnect from the connection screen? Does that cause it to load the proper version?

**Comment by karlbecker** [comment]
@hankinsoft that worked! 

Still seems like a bug I suppose, but that workaround is helpful to know.  Thanks!

**Comment by hankinsoft** [comment]
Glad that sorted it. While I do agree that this is a bug, it's very low priority. I'm going to mark it as closed for the time being.
