### ISSUE TITLE
All columns show "GENERATED BY DEFAULT AS IDENTITY"

### ISSUE THREAD

**Issue by 8zero7** [hankinsoft/SQLPro#979]
**Describe the bug**
For any PostgreSQL table in any database (even production instances), all columns show "GENERATED BY DEFAULT AS IDENTITY" regardless of data type. This only started happening recently. None of these columns should be marked that way. Scripting the table  as a CREATE statement also includes this for each column which is obviously impossible. Even the default postgres database tables all have this.

**To Reproduce**
1. Open any database and view a table
2. Expand the table columns
3. Observe "GENERATED BY DEFAULT AS IDENTITY" next to each column

**Expected behavior**
"GENERATED BY DEFAULT AS IDENTITY" should only appear next to columns marked with that option.

**Screenshots**
<img width="476" alt="Screenshot 2024-05-19 at 4 41 10 PM" src="https://github.com/hankinsoft/SQLPro/assets/49440346/9f2eda26-ff62-4eb5-83c0-5058e09ebb3a">

**Environment details (please complete the following information):**
 - Device: MacBook M3
 - OS: macOS 14.3
 - SQLPro app Version: 2023.73 (Build 111073.5)
- Installation source: App Store
- Target database server: PostgreSQL

**Additional context**
n/a

**Comment by 8zero7** [comment]
Some additional context: I downloaded pgAdmin4 (which is terrible) and scripted the same tables as a CREATE statement. None of the columns have the "GENERATED BY DEFAULT AS IDENTITY" designation. This is a SQLPro Studio UI issue.

**Comment by 8zero7** [comment]
I confirmed with a co-worker that this is present on her machine as well. My other machine that does not seem affected is on version 2023.56. Trying to alter a table on the affected machines shows the value and it cannot be removed.


https://github.com/hankinsoft/SQLPro/assets/49440346/b90ea2cf-2ee2-4c40-bbed-cf956d84b2a9

**Comment by hankinsoft** [comment]
Sorry about that. I’ve actually fixed this issue in the website build but unfortunately I’m currently away. I’ll get the App Store build fixed up first thing next week.

Pleaae see https://github.com/hankinsoft/SQLPro/issues/976 for details on the website build.

**Comment by 8zero7** [comment]
Ok great. Glad I wasn't going crazy. Thanks for the update.

Jason Rosensweig
President Eight Zero Seven LLC

**Comment by 8zero7** [comment]
Great thanks

Jason Rosensweig
President Eight Zero Seven LLC

**Comment by hankinsoft** [comment]
The new version should now be available. If you get the chance, please give it a try and let me know if that sorts things out for you.

**Comment by 8zero7** [comment]
Still shows .21 in the App Store. I'll check again later.[image: image.png]
Sincerely,

Jason Rosensweig
Owner / President
Eight Zero Seven LLC
***@***.***

**Comment by hankinsoft** [comment]
Are you seeing the update now? If not, when you get the chance, could you reboot your macOS device and see if the update shows as available after that? Or try uninstalling the app, then re-install from the App Store is another way to force the latest version.

**Comment by 8zero7** [comment]
Yeah it showed up the next day. Seems to work fine. Thanks for fixing it
so quickly.

Sincerely,

Jason Rosensweig
Owner / President
Eight Zero Seven LLC
***@***.***

**Comment by hankinsoft** [comment]
Awesome, glad to hear it. If you happen to get the chance, would you consider leaving a rating or review on the App Store? As an independent developer, they help me out a ton. There is even a quick way to leave one, by running the query 'rate;'. No worries if not.

**Comment by 8zero7** [comment]
Left you a 5-star review on the app store

Sincerely,

Jason Rosensweig
Owner / President
Eight Zero Seven LLC
***@***.***
