### ISSUE TITLE
Editing a record in-line crashes the app

### ISSUE THREAD

**Issue by PeteFox** [hankinsoft/SQLPro#98]
Since the latest update (1.0.122), the app crashes every time I try to edit a record in-line. 

I'm on an iMac with macOS Sierra v. 10.12.4

A crash report has been submitted.

**Comment by hankinsoft** [comment]
Hi,
Just to note this should be all fixed up. Are you still seeing this? If so, please post which product you are using along with the version (best would be a screenshot from the about dialog).
