### ISSUE TITLE
The ability to purchase lifetime subscription from Microsoft Store after free trial expires

### ISSUE THREAD

**Issue by nafoiw1410** [hankinsoft/SQLPro#980]
**Is your feature request related to a problem? Please describe.**

Currently on the Microsoft Windows store version of the program, there is no option to purchase lifetime subscription from within the store system after free trial expires where as during the free trial, the lifetime purchase option is visible

**Describe the solution you'd like**
Make the in-store Lifetime Subscription button accessible to users with expired free trial.

**Environment (please complete the following information):**
 - Device: PC
 - OS: Windows 11 23H2
 - SQLPro app Version: SQLPro Studio 2024.22
- Installation source: Microsoft Store
- Target database server PostgreSQL

**Requests will be closed until environmental details are provided.**

**Comment by hankinsoft** [comment]
Hi. I’m currently away, but I will take a look into this early next week.

**Comment by hankinsoft** [comment]
There is a new build available. Could you check that and the lifetime version should be available. If you're not seeing it, could you post a screenshot of what you do see? Thanks!
