### ISSUE TITLE
SQLPro for SQLite locks up with all tables "Loading rows" after making many changes to a table

### ISSUE THREAD

**Issue by GaryMeyers1** [hankinsoft/SQLPro#983]
**Describe the bug**
I exported three columns from a table into a CSV clipboard with the "Copy as Insert -> Batch" right click menu item and then manually created many delete statements from those values.  When I run the 492 commands, they succeed very quickly but then the user interface locks up with every table showing a "Loading rows" status message under its name.  After about three minutes, SQLPro for SQLite crashes.

**To Reproduce**
1. Open a table
2. Go to the Query tab
3. Execute many change commands.  I have used only deletes but I am guessing that updates would also crash.
4. See the interface lock up showing "Loading rows" under every table name.
5. After about three minutes in my case, the app crashes.

**Expected behavior**
No lockups and no crashes

**Screenshots**
I tried to attach a MP4 screen recording of my experience but it is 60.4 MB and the limit is 10 MB.  It is 3:12 long because I waited until the app crashed.  I trimmed out the middle section but that reduced the file size to just 47 MB.  I uploaded two screen shots instead.
<img width="1337" alt="2024-05-27-sqlpro screenshot from video" src="https://github.com/hankinsoft/SQLPro/assets/60852956/462cba24-b782-4600-8d2f-a15322c53a36">
<img width="1000" alt="2024-05-27-sqlpro crash" src="https://github.com/hankinsoft/SQLPro/assets/60852956/5070e772-9703-47a5-8c36-1ddea0356724">

**Environment details (please complete the following information):**
 - Device: iMac
 - OS: macOS 13.6.7
 - SQLPro for SQLite 2024.20 (Build 4370)
- Installation source: Website download

**Additional context**

## Issues will be closed until environmental details are provided.
If the above template is not completed, issues with be closed with the statement `Issue has been closed. Please edit the initial post (or create a new issue) and follow the template. Once completed, the issue may be reopened`.

**Comment by hankinsoft** [comment]
I believe I have this fixed for the next build. Just taking a look into the import thing as well before I make it available.

**Comment by hankinsoft** [comment]
I believe this one is fixed as well based on the other comment (#982), but if not please feel free to reopen.
