### ISSUE TITLE
Re-Connecting Does not Requery DNS

### ISSUE THREAD

**Issue by kpconnell** [hankinsoft/SQLPro#987]
**Describe the bug**
If your database changes IP addresses, and you attempt to run a query without closing SQLPro, it will initially get an error about the connection being closed.  Upon retry, you will get an error:  Can't connect to server on 'a.b.c.d' where a.b.c.d is the old IP address of your database  Closing and re-opening SQLPro solves it.

**To Reproduce**
1.  make a connection and issue a query
2.  scale your db instance in a way that it receives a new IP address
3.  attempt to run a query

**Expected behavior**
When a connection fails, IP address cache should not be used

**Environment details (please complete the following information):**
 - Device: M1 Macbook Pro 
 - OS: Mac OS Latest
 - SQLPro app Version Version 2024.13 (Build 111086)

**Comment by hankinsoft** [comment]
Hi,
A few questions here to help me out.

1. What type of database is this? MSSQL, Postgres, etc?
2. Are you manually scaling the DB, or is that something that happens automatically?
3. What specific error are you getting? Would it be possible to post a screenshot or copy of the error?
