### ISSUE TITLE
Windows Store Version Tab Management Bugs

### ISSUE THREAD

**Issue by nafoiw1410** [hankinsoft/SQLPro#988]
**Describe the bug**
When closing unfocused tabs, incorrect tabs get closed instead of the selected ones.

**To Reproduce**
1. Have Multiple Tabs Open
2. Close An Unfocused Tab
3. Tab Other Than the One Selected Get Closed.

**Environment details (please complete the following information):**
 - Device: PC
 - OS: Windows 11 23H2
 - SQLPro app Version: SQLPro Studio v2024.30
- Installation source: Microsoft Store
- Target database server: Postgres

**Comment by hankinsoft** [comment]
I've submitted a build which should sort this out. It generally takes about ~24 hours or so for a build to become available on the App Store, so sometime by tomorrow it should be available.

**Comment by hankinsoft** [comment]
Marking as closed. If you continue to see this issue, please let me know.
