### ISSUE TITLE
Crashing every time in iOS 18 developer Beta

### ISSUE THREAD

**Issue by LukeStephen** [hankinsoft/SQLPro#992]
Crashing on launch every time in iOS 18 developer Beta

**To Reproduce**
1. click icon to open the app
2. Select existing database or the settings gear icon
3. Crashes right away
4. No prompt on re-start to submit a crash report.

**Expected behavior**
Not crash

**Screenshots**
crashes and disappears, nothing to screenshot

**Environment details (please complete the following information):**
 - Device: iPhone 15 Pro Max and 2024 iPadPro 11"
 - OS: iOS 18 Developer Beta on both devices
 - SQLPro 
- Installation source: App Store
- Target database server Microsoft SQL Server

Can I be part of the test flight version to test this fix if it's not ready for the app store yet?

**Comment by LukeStephen** [comment]
Added it under the correct iOS git repo

**Comment by hankinsoft** [comment]
There is a new build of SQLPro Studio available on the App Store. Can you confirm if this sorts the issue you were seeing?

**Comment by LukeStephen** [comment]
Yes, that does not crash for me.

can that fix be pushed to this app of yours that I subscribe to https://apps.apple.com/us/app/sql-server-mssql-by-sqlpro/id1176218536

thanks,
Lucas

**Comment by hankinsoft** [comment]
The MSSQL version should now be available and fixed.

**Comment by LukeStephen** [comment]
Yes on my iPhone this is fixed and the app works great

On my iPad when I paste in a SQL command and try to run it the app crashes

**Comment by hankinsoft** [comment]
Fixed build for SQLPro for MSSQL has been submitted to apple.

**Comment by hankinsoft** [comment]
A new build is available. Could you give it a try and see if you are still having the crashes?

**Comment by LukeStephen** [comment]
No more crashes, thank you!!
