### ISSUE TITLE
Autosizing columns to content doesn't work

### ISSUE THREAD

**Issue by spudnick02** [hankinsoft/SQLPro#994]
**Describe the bug**
The new autosize columns feature doesn't size the results 'To content', instead they're always spaced equally.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a database with tables containing data
2. Write a simply select query that returns content from the database table
3. Notice that all columns returned are equally spaced
4. Right-click on any column header and select 'Autosize columns > To content', columns don't shrink and re-running the query doesn't return the results with the columns sized to fit the data.

**Expected behavior**
When selecting 'Autosize columns > To content' that columns returned from queries are always sized to fit the content, even when opening a new tab/window.

**Screenshots**
![image](https://github.com/hankinsoft/SQLPro/assets/48037268/ca713ee0-0768-434a-be97-268a21d0e869)

**Environment details (please complete the following information):**
 - Device: Macbook Pro M1 Pro
 - OS: Sonoma 14.5
 - SQLPro app Version: SQLPro Studio Version 2024.38 (Build 111106.6)
- Installation source: App Store
- Target database server: Microsoft SQL Server, SQLite, MySQL

**Additional context**
This bug is frustrating because a select * on a table with many columns now requires you to horizontally scroll for a long time due to empty columns or columns with data smaller than the column width always being sized equally even after selecting 'Autosize columns > To content'. Recommend that the setting 'To Content' firstly works as it should and that it remembers the last selected preference perhaps with a tick after 'To content'/'Equally' or perhaps even in bold text?

**Comment by hankinsoft** [comment]
Hmmm, just to check how many columns do you have in the table? If you do it to a table with fewer columns (or select fewer columns) is it working?

**Comment by spudnick02** [comment]
I have 30 columns in the table. What I found is that if there are <= 20 columns it autosizes, as soon as there's 21 or more they all size equally.

**Comment by hankinsoft** [comment]
I've got the limit updated to 50 for the next build. It will be available mid-next week.

**Comment by hankinsoft** [comment]
2024.60 is available on the App Store and should sort this issue out. If you get the chance, please give it a try and let me know.

**Comment by hankinsoft** [comment]
Going to mark as closed. If you continue to have any issues with this, please let me know.
