### ISSUE TITLE
Apple USB Keyboard Arrow Keys Not Functioning on iPad

### ISSUE THREAD

**Issue by chrcapone** [hankinsoft/SQLPro#997]
I am writing to report an issue with the Apple USB Keyboard when used with the iOS version of SQL Pro on my iPad.

The arrow keys on the keyboard do not function when attempting to scroll and select elements from the content menu that appears after typing the name of a table followed by a period (“.”). This issue significantly affects my ability to navigate and select items efficiently.

- Device: iPad Pro 12.9” 6th Generation
- iOS Version: 17.5.1
- Keyboard Model: Apple Smart Keyboard Folio

Could you please provide guidance on how to resolve this problem?

Thank you for your assistance.

**Comment by hankinsoft** [comment]
Hi,
You mentioned possibly providing a video? If that’s an option, could you please upload here? Please note that files will not attach via email - it must be uploaded directly to GitHub.

**Comment by chrcapone** [comment]
Thank you for coming back to me so quickly. In this video
https://share.icloud.com/photos/08d-rRsDWBsY2MWJqSdjS1uNQ you can see:
1. I cannot use arrow down or any arrow, to select the list in the context
menu
2. Even using the touchscreen, either with the finger or Apple Pencil, the
software selects something different on what I click

*CHRISTIAN CAPONE* | PROGRAM MANAGER

Mob. +998 90 047 9956
Skype: christian.capone


*Fleet Support S.r.l.*

Via Varese, 5 - 00185 Roma

Tel. +39 06 49212 1

Fax +39 06 49212 212

fleetsupport.it



*“Per lo sviluppo innovativo del software che risponde alle esigenze in
continua evoluzione dei fleet manager e dei driver”*

*L'utilizzo non autorizzato del presente messaggio è vietato e potrebbe
costituire reato. Se il presente messaggio non e' a Lei indirizzato, Le
saremmo grati se, via e-mail, ne comunicasse l'errata ricezione. Il
contenuto del presente messaggio non deve essere considerato come trasmesso
o autorizzato da Fleet Support. Fleet Support non si assume alcuna
responsabilità per eventuali intercettazioni, modifiche o danneggiamenti
del presente messaggio e-mail.*

*Notice: the information contained in this message is intended only for use
of the individual(s) named above and may contain confidential, proprietary
or legally privileged information. No confidentiality or privilege is
waived or lost by any mistransmission. if you are not the intended
recipient of this message you are hereby notified that you must not use,
disseminate, copy it in any form or take any action in reliance of it. If
you have received this message in error please delete it and any copies of
it and notify the sender immediately.*

*P* *stampa questo messaggio solo se veramente necessario, pensa
all'ambiente!*

**Comment by chrcapone** [comment]
Hi again, just checking out if you have access to the video by the above link, or if I need to upload it here.
Thank you!

**Comment by hankinsoft** [comment]
Hi, I’ve actually got this sorted, I’m just fighting with the build process after I upgraded macOS to the latest beta. Hope to have it available late this week or early next. Can you confirm that your using SQLPro studio, or SQLPro for MSSQL?

**Comment by chrcapone** [comment]
> Hi, I’ve actually got this sorted, I’m just fighting with the build process after I upgraded macOS to the latest beta. Hope to have it available late this week or early next. Can you confirm that your using SQLPro studio, or SQLPro for MSSQL?

That’s great! Thank you for your support. I am using SQLPro MSSQL, on iPad

**Comment by chrcapone** [comment]
> Hi, I’ve actually got this sorted, I’m just fighting with the build process after I upgraded macOS to the latest beta. Hope to have it available late this week or early next. Can you confirm that your using SQLPro studio, or SQLPro for MSSQL?

I confirm that with the last update, the issue is closed! Thank you!
