### ISSUE TITLE
How to make a connection

### ISSUE THREAD

**Issue by fercar29** [hankinsoft/SQLPro#999]
Hi, I don´t know the basics of SQL and downloaded SQLPro last week, but I am trying to create a new connection, but I don't know the host, the user nor the password. I tried with localhost, sa, and the master password but they don't work. MacOS Sonoma 14.5. 

Then I saw that maybe i would need freetds, i installed that using homebrew but then I don't know what to do.

Thanks in advance.

**Comment by hankinsoft** [comment]
Hi, your server administrator, teacher, etc would need to provide you with these details as they are not something I would have for you. You would need to contact one of the above to receive those details.
